### ISSUE TITLE
Add An Example for AspNetCore app

### ISSUE THREAD

**Issue by gregoryagu** [ClosedXML/ClosedXML#1000]
There seems to be no existing sample for downloading a file in aspnetcore, so I wrote this which works for me in a razor page:

```
public async Task<IActionResult> OnGet()
{
	var workbook = GenerateClosedXMLWorkbook();
	MemoryStream memoryStream = new MemoryStream();
	workbook.SaveAs(memoryStream);
	memoryStream.Position = 0;
	return File(memoryStream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "hello.xlsx");

}
		

private XLWorkbook GenerateClosedXMLWorkbook()
{
	var workbook = new XLWorkbook();
	var worksheet = workbook.Worksheets.Add("Sample Sheet");
	worksheet.Cell("A1").Value = "Hello World!";
	worksheet.Cell("A2").FormulaA1 = "=MID(A1, 7, 5)";
	return workbook;
}
```
Note: The memory stream in the above is purposely NOT being closed, as it does not work otherwise.  See [this SO question](https://stackoverflow.com/questions/52329071/do-i-need-to-close-this-memory-stream?noredirect=1#comment91605522_52329071)

**Comment by igitur** [comment]
Is the https://github.com/ClosedXML/ClosedXML.Extensions.Mvc library not sufficient to do this?

**Comment by gregoryagu** [comment]
Yes, I think so.  No reason not to close this at this time.
