### ISSUE TITLE
Support Excel-DNA UDFs in formula evaluation

### ISSUE THREAD

**Issue by govert** [ClosedXML/ClosedXML#1003]
It might be useful to allow some limited support for UDFs that are defined in Excel-DNA add-ins.
It is not a use case I need myself, but I can help to implement if it would be useful to others.
So this is more a placeholder than an actual feature request.

Technically this should not be too difficult to implement by examining the add-in assemblies via reflection, and disallowing, restricting or working around C API or COM calls made from a UDFs.

**Comment by igitur** [comment]
There are other things that have higher priority at this time, but if someone submits a pull request, I'll review it.

**Comment by igitur** [comment]
As mentioned, I'll review pull requests in this regard. Closing for now.
