### ISSUE TITLE
Woorkbook-scoped Named Ranges on a deleted sheet corrupt workbook.

### ISSUE THREAD

**Issue by CPSibo** [ClosedXML/ClosedXML#1007]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.93.1

**What is the current behavior?**

If the workbook has a named range at its level which points to a sheet which then gets deleted, the saved workbook is corrupt. This can be solved by deleting the named range from the workbook.

**What is the expected behavior or new feature?**

Workbook should not be corrupt.

**Did this work in previous versions of our tool?  Which versions?**

Unknown.

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
    using (var workbook = new XLWorkbook())
    {
        var sheetToDelete = workbook.AddWorksheet("Sheet To Delete");
        workbook.AddWorksheet("Blank Sheet"); // So we don't throw an exception on saving an empty workbook.

        var range = sheetToDelete.FirstCell().AsRange();

        // Add a range to the workbook.
        // This also works if opening an existing workbook with a
        // workbook-scoped named range.
        workbook.NamedRanges.Add("TestRange", range);

        // Delete the sheet to which the named range points.
        sheetToDelete.Delete();

        workbook.SaveAs("Test.xlsx");
    }
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Test.xlsx](https://github.com/ClosedXML/ClosedXML/files/2403287/Test.xlsx)

**Comment by machj** [comment]
I think there is the same problem when I delete entire row where named range is present. I used to delete all named ranges before saving a file to prevent this type of error.
