### ISSUE TITLE
Request to work in sandboxed environments

### ISSUE THREAD

**Issue by fayezm** [ClosedXML/ClosedXML#1008]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [X] Feature

**Version of ClosedXML**

0.9.3

**What is the current behavior?**

Unable to deploy this in a sandboxed environment (e.g. Dynamics 365 Plugin). An error is thrown due to the use of reflection libraries

**What is the expected behavior or new feature?**

The facility to deploy to a sand-boxed environment

**Did this work in previous versions of our tool?  Which versions?**

N/A

## Reproducibility

Just add a reference to this library and deploy the output dll to a sandbox environment and attempt to create an instance of the class. 

**Code to reproduce problem:**
```c#
public void Main()
{
using (var workbook = new XLWorkbook())
{
    var worksheet = workbook.Worksheets.Add("Sample Sheet");
    worksheet.Cell("A1").Value = "Hello World!";
    worksheet.Cell("A2").FormulaA1 = "=MID(A1, 7, 5)";
    workbook.SaveAs("HelloWorld.xlsx");
}
}
```

**Comment by igitur** [comment]
@fayezm If you can propose an implementation of `XLColumnAttribute` that doesn't use reflection, then it might be possible. Do you have a solution?

**Comment by fayezm** [comment]
> @fayezm If you can propose an implementation of `XLColumnAttribute` that doesn't use reflection, then it might be possible. Do you have a solution?

I don't have a solution at this stage. 

There'd need to be a way to also replace the references to FastMember. My quick investigation shows that its used for generating headings automatically and for dealing with complex types
