### ISSUE TITLE
Add shapes to workbook

### ISSUE THREAD

**Issue by kitzler-walli** [ClosedXML/ClosedXML#1009]
Is it yet possible to add shapes with ClosedXML?

**Comment by igitur** [comment]
No, not yet.

**Comment by kitzler-walli** [comment]
OK - maybe I can use Image for my usecase...
Is it possible to get the space between two cells to create an image for that?
I've seen in the code I'm able to assign two cells to an image (TopLeftCellAddress, BottomRightCellAddress) - when I can get the size of this rectangle I could draw the image on the fly.

**Comment by kitzler-walli** [comment]
I tried to add a 1x1 pixel image and then resize it between two cells. But the width/height of the image don't change in code:
````
 ws.AddPicture(@"C:\temp\BLANK.GIF").WithPlacement(ClosedXML.Excel.Drawings.XLPicturePlacement.MoveAndSize).MoveTo(ws.Cell("AA20"),ws.Cell("AJ26"))
````


The image is placed correctly in the document, but I don't see a way to get the image size after the resize.

**Comment by igitur** [comment]
ClosedXML doesn't render the image internally to recalculate its size.
