### ISSUE TITLE
row.CopyTo() produces corrupted file

### ISSUE THREAD

**Issue by machj** [ClosedXML/ClosedXML#1013]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

Not working in: 0.94.0.0 (development), 0.93.0 and 0.93.1 (NuGet package)

**What is the current behavior?**

When I insert a new row and copy to old row over the new one, it can produce corrupted worksheet.MergedRanges - there are duplicated ranges. When I try to open the file in Excel, it says that the file is corrupted and tries to repair it (remove some merging).

Since version 0.93.0 the result in MergedRanges is wrong, randomly with duplicates, e.g. A1:F1, A501:F501, A4:F4, A499:F499, A4:F4, (...)

It must be repeated many times (inserting and copying merged cells), the original file must have at least some cells merged. Inserting and copying only one row is working. Inserting rows without CopyTo is working. Copying unmerged row to the new one is working too.

**What is the expected behavior?**

MergeRanges has no duplicates, e.g. A1:F1, A501:F501, A500:F500, A499:F499, A498:F498, (...)

**Did this work in previous versions of our tool?  Which versions?**

Yes/v0.92.1

## Reproducibility

The result is unpredictable - sometimes duplicates are added into MergedRanges, sometimes aren't. I haven't found any key to this, it's random every run. You can try my example and see different results each run (I will add some results into comment).

But if you iterate many times (300-500 rows inserted in my example), there will be finally duplicates almost all the time, 1-3 same cells repeated in MergedRanges.

**Code to reproduce problem:**

I have more complex templates, where I can insert (or delete) only 2 rows and get a corrupted file. But I habe prepared a simplified template with only first row merged (A1:F1).

I'm VB.NET programmer in ASP.NET, sorry:-) Template test.xlsx is attached. Results are random.

```vb
        'Open template workbook with cells A1:F1 merged; ws.MergedRanges: {List1!A1:F1}
        Dim wb = GetExcelWorkbook(HttpContext.Current.Server.MapPath("/App_Data/test.xlsx"))
        'Get the first worksheet "List1"
        Dim ws = wb.Worksheets.First
        'Get the first row
        Dim row As IXLRow = ws.Rows("1").FirstOrDefault

        'Add some line and copy format & merging
        For r = 1 To 500
            row.InsertRowsBelow(1)      'insert a row below row 1, as a row 2
            row.CopyTo(row.RowBelow)    'copy format and merging from row 1 to row 2
        Next

        'List all merged ranges, without "List1!" to have shorter list
        Debug.WriteLine($"WS.MERGEDRANGES: {ws.MergedRanges.ToString.Replace("List1!", " ")}")

        'There are probably some duplicates in wsMergedRanges
        'Get only duplicates, remove "List1!" from the merged range name to simplify text
        Dim duplicates = ws.MergedRanges.GroupBy(Function(s) s.ToString).Where(Function(g) g.Count() > 1).[Select](Function(y) New With {Key .Element = y.Key, Key .Counter = y.Count()}).ToList()


        'list duplicated ranges
        Debug.WriteLine($"Total duplicates: {duplicates.Count}")    'Number of duplicates
        For Each item In duplicates
            Debug.WriteLine($"- {item.Element}")                    'Write duplicated range, or $"- {item.Element} {item.Counter}x" writes range and number of occurences
        Next

        Debug.Assert(duplicates.Count = 0, "MergedRanges is corrupted!")
```

```c# (converted by http://converter.telerik.com/)
{
    // Open template workbook with cells A1:F1 merged; ws.MergedRanges: {List1!A1:F1}
    var wb = GetExcelWorkbook(HttpContext.Current.Server.MapPath("/App_Data/test.xlsx"));
    // Get the first worksheet "List1"
    var ws = wb.Worksheets.First;
    // Get the first row
    IXLRow row = ws.Rows("1").FirstOrDefault;

    // Add some line and copy format & merging
    for (var r = 1; r <= 500; r++)
    {
        row.InsertRowsBelow(1);      // insert a row below row 1, as a row 2
        row.CopyTo(row.RowBelow);    // copy format and merging from row 1 to row 2
    }

    // List all merged ranges, without "List1!" to have shorter list
    Debug.WriteLine($"WS.MERGEDRANGES: {ws.MergedRanges.ToString.Replace("List1!", " ")}");

    // There are probably some duplicates in wsMergedRanges
    // Get only duplicates, remove "List1!" from the merged range name to simplify text
    var duplicates = ws.MergedRanges.GroupBy(s => s.ToString()).Where(g => g.Count() > 1).Select(y => new { Element = y.Key, Counter = y.Count() }).ToList();


    // list duplicated ranges
    Debug.WriteLine($"Total duplicates: {duplicates.Count}");    // Number of duplicates
    foreach (var item in duplicates)
        Debug.WriteLine($"- {item.Element}");// Write duplicated range, or $"- {item.Element} {item.Counter}x" writes range and number of occurences

    Debug.Assert(duplicates.Count == 0, "MergedRanges is corrupted!");
}
```
[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/2435550/test.xlsx)
[corrupted1.xlsx](https://github.com/ClosedXML/ClosedXML/files/2435586/corrupted1.xlsx)
[corrupted2.xlsx](https://github.com/ClosedXML/ClosedXML/files/2435587/corrupted2.xlsx)

**Comment by machj** [comment]
CORRECT OUTPUT FROM THE VERSION 0.92.1
WS.MERGEDRANGES:  A1:F1, A501:F501, A500:F500, A499:F499, A498:F498, A497:F497, A496:F496, A495:F495, A494:F494, A493:F493, A492:F492, A491:F491, A490:F490, A489:F489, A488:F488, A487:F487, A486:F486, A485:F485, A484:F484, A483:F483, A482:F482, A481:F481, A480:F480, A479:F479, A478:F478, A477:F477, A476:F476, A475:F475, A474:F474, A473:F473, A472:F472, A471:F471, A470:F470, A469:F469, A468:F468, A467:F467, A466:F466, A465:F465, A464:F464, A463:F463, A462:F462, A461:F461, A460:F460, A459:F459, A458:F458, A457:F457, A456:F456, A455:F455, A454:F454, A453:F453, A452:F452, A451:F451, A450:F450, A449:F449, A448:F448, A447:F447, A446:F446, A445:F445, A444:F444, A443:F443, A442:F442, A441:F441, A440:F440, A439:F439, A438:F438, A437:F437, A436:F436, A435:F435, A434:F434, A433:F433, A432:F432, A431:F431, A430:F430, A429:F429, A428:F428, A427:F427, A426:F426, A425:F425, A424:F424, A423:F423, A422:F422, A421:F421, A420:F420, A419:F419, A418:F418, A417:F417, A416:F416, A415:F415, A414:F414, A413:F413, A412:F412, A411:F411, A410:F410, A409:F409, A408:F408, A407:F407, A406:F406, A405:F405, A404:F404, A403:F403, A402:F402, A401:F401, A400:F400, A399:F399, A398:F398, A397:F397, A396:F396, A395:F395, A394:F394, A393:F393, A392:F392, A391:F391, A390:F390, A389:F389, A388:F388, A387:F387, A386:F386, A385:F385, A384:F384, A383:F383, A382:F382, A381:F381, A380:F380, A379:F379, A378:F378, A377:F377, A376:F376, A375:F375, A374:F374, A373:F373, A372:F372, A371:F371, A370:F370, A369:F369, A368:F368, A367:F367, A366:F366, A365:F365, A364:F364, A363:F363, A362:F362, A361:F361, A360:F360, A359:F359, A358:F358, A357:F357, A356:F356, A355:F355, A354:F354, A353:F353, A352:F352, A351:F351, A350:F350, A349:F349, A348:F348, A347:F347, A346:F346, A345:F345, A344:F344, A343:F343, A342:F342, A341:F341, A340:F340, A339:F339, A338:F338, A337:F337, A336:F336, A335:F335, A334:F334, A333:F333, A332:F332, A331:F331, A330:F330, A329:F329, A328:F328, A327:F327, A326:F326, A325:F325, A324:F324, A323:F323, A322:F322, A321:F321, A320:F320, A319:F319, A318:F318, A317:F317, A316:F316, A315:F315, A314:F314, A313:F313, A312:F312, A311:F311, A310:F310, A309:F309, A308:F308, A307:F307, A306:F306, A305:F305, A304:F304, A303:F303, A302:F302, A301:F301, A300:F300, A299:F299, A298:F298, A297:F297, A296:F296, A295:F295, A294:F294, A293:F293, A292:F292, A291:F291, A290:F290, A289:F289, A288:F288, A287:F287, A286:F286, A285:F285, A284:F284, A283:F283, A282:F282, A281:F281, A280:F280, A279:F279, A278:F278, A277:F277, A276:F276, A275:F275, A274:F274, A273:F273, A272:F272, A271:F271, A270:F270, A269:F269, A268:F268, A267:F267, A266:F266, A265:F265, A264:F264, A263:F263, A262:F262, A261:F261, A260:F260, A259:F259, A258:F258, A257:F257, A256:F256, A255:F255, A254:F254, A253:F253, A252:F252, A251:F251, A250:F250, A249:F249, A248:F248, A247:F247, A246:F246, A245:F245, A244:F244, A243:F243, A242:F242, A241:F241, A240:F240, A239:F239, A238:F238, A237:F237, A236:F236, A235:F235, A234:F234, A233:F233, A232:F232, A231:F231, A230:F230, A229:F229, A228:F228, A227:F227, A226:F226, A225:F225, A224:F224, A223:F223, A222:F222, A221:F221, A220:F220, A219:F219, A218:F218, A217:F217, A216:F216, A215:F215, A214:F214, A213:F213, A212:F212, A211:F211, A210:F210, A209:F209, A208:F208, A207:F207, A206:F206, A205:F205, A204:F204, A203:F203, A202:F202, A201:F201, A200:F200, A199:F199, A198:F198, A197:F197, A196:F196, A195:F195, A194:F194, A193:F193, A192:F192, A191:F191, A190:F190, A189:F189, A188:F188, A187:F187, A186:F186, A185:F185, A184:F184, A183:F183, A182:F182, A181:F181, A180:F180, A179:F179, A178:F178, A177:F177, A176:F176, A175:F175, A174:F174, A173:F173, A172:F172, A171:F171, A170:F170, A169:F169, A168:F168, A167:F167, A166:F166, A165:F165, A164:F164, A163:F163, A162:F162, A161:F161, A160:F160, A159:F159, A158:F158, A157:F157, A156:F156, A155:F155, A154:F154, A153:F153, A152:F152, A151:F151, A150:F150, A149:F149, A148:F148, A147:F147, A146:F146, A145:F145, A144:F144, A143:F143, A142:F142, A141:F141, A140:F140, A139:F139, A138:F138, A137:F137, A136:F136, A135:F135, A134:F134, A133:F133, A132:F132, A131:F131, A130:F130, A129:F129, A128:F128, A127:F127, A126:F126, A125:F125, A124:F124, A123:F123, A122:F122, A121:F121, A120:F120, A119:F119, A118:F118, A117:F117, A116:F116, A115:F115, A114:F114, A113:F113, A112:F112, A111:F111, A110:F110, A109:F109, A108:F108, A107:F107, A106:F106, A105:F105, A104:F104, A103:F103, A102:F102, A101:F101, A100:F100, A99:F99, A98:F98, A97:F97, A96:F96, A95:F95, A94:F94, A93:F93, A92:F92, A91:F91, A90:F90, A89:F89, A88:F88, A87:F87, A86:F86, A85:F85, A84:F84, A83:F83, A82:F82, A81:F81, A80:F80, A79:F79, A78:F78, A77:F77, A76:F76, A75:F75, A74:F74, A73:F73, A72:F72, A71:F71, A70:F70, A69:F69, A68:F68, A67:F67, A66:F66, A65:F65, A64:F64, A63:F63, A62:F62, A61:F61, A60:F60, A59:F59, A58:F58, A57:F57, A56:F56, A55:F55, A54:F54, A53:F53, A52:F52, A51:F51, A50:F50, A49:F49, A48:F48, A47:F47, A46:F46, A45:F45, A44:F44, A43:F43, A42:F42, A41:F41, A40:F40, A39:F39, A38:F38, A37:F37, A36:F36, A35:F35, A34:F34, A33:F33, A32:F32, A31:F31, A30:F30, A29:F29, A28:F28, A27:F27, A26:F26, A25:F25, A24:F24, A23:F23, A22:F22, A21:F21, A20:F20, A19:F19, A18:F18, A17:F17, A16:F16, A15:F15, A14:F14, A13:F13, A12:F12, A11:F11, A10:F10, A9:F9, A8:F8, A7:F7, A6:F6, A5:F5, A4:F4, A3:F3, A2:F2
Total duplicates: 0

There are some results from different runs of the example code with version 0.93+:
WS.MERGEDRANGES:  A1:F1, A1001:F1001, A4:F4, A999:F999, A4:F4, A997:F997, A4:F4, A995:F995, A4:F4, A993:F993, A4:F4, A991:F991, A4:F4, A989:F989, A4:F4, A987:F987, A4:F4, A985:F985, A4:F4, A983:F983, A4:F4, A981:F981, A4:F4, A979:F979, A4:F4, A977:F977, A4:F4, A975:F975, A4:F4, A973:F973, A4:F4, A971:F971, A4:F4, A969:F969, A4:F4, A967:F967, A4:F4, A965:F965, A4:F4, A963:F963, A4:F4, A961:F961, A4:F4, A959:F959, A4:F4, A957:F957, A4:F4, A955:F955, A4:F4, A953:F953, A4:F4, A951:F951, A4:F4, A949:F949, A4:F4, A947:F947, A4:F4, A945:F945, A4:F4, A943:F943, A4:F4, A941:F941, A4:F4, A939:F939, A4:F4, A937:F937, A4:F4, A935:F935, A4:F4, A933:F933, A4:F4, A931:F931, A4:F4, A929:F929, A4:F4, A927:F927, A4:F4, A925:F925, A4:F4, A923:F923, A4:F4, A921:F921, A4:F4, A919:F919, A4:F4, A917:F917, A4:F4, A915:F915, A4:F4, A913:F913, A4:F4, A911:F911, A4:F4, A909:F909, A4:F4, A907:F907, A4:F4, A905:F905, A5:F5, A903:F903, A5:F5, A901:F901, A5:F5, A899:F899, A5:F5, A897:F897, A5:F5, A895:F895, A5:F5, A893:F893, A5:F5, A891:F891, A5:F5, A889:F889, A5:F5, A887:F887, A5:F5, A885:F885, A5:F5, A883:F883, A5:F5, A881:F881, A5:F5, A879:F879, A5:F5, A877:F877, A5:F5, A875:F875, A5:F5, A873:F873, A5:F5, A871:F871, A5:F5, A869:F869, A5:F5, A867:F867, A5:F5, A865:F865, A5:F5, A863:F863, A5:F5, A861:F861, A5:F5, A859:F859, A5:F5, A857:F857, A5:F5, A855:F855, A5:F5, A853:F853, A5:F5, A851:F851, A5:F5, A849:F849, A5:F5, A847:F847, A5:F5, A845:F845, A5:F5, A843:F843, A5:F5, A841:F841, A5:F5, A839:F839, A5:F5, A837:F837, A5:F5, A835:F835, A5:F5, A833:F833, A5:F5, A831:F831, A5:F5, A829:F829, A5:F5, A827:F827, A5:F5, A825:F825, A5:F5, A823:F823, A5:F5, A821:F821, A5:F5, A819:F819, A5:F5, A817:F817, A5:F5, A815:F815, A5:F5, A813:F813, A5:F5, A811:F811, A5:F5, A809:F809, A5:F5, A807:F807, A5:F5, A805:F805, A5:F5, A803:F803, A5:F5, A801:F801, A5:F5, A799:F799, A5:F5, A797:F797, A5:F5, A795:F795, A5:F5, A793:F793, A5:F5, A791:F791, A5:F5, A789:F789, A5:F5, A787:F787, A5:F5, A785:F785, A5:F5, A783:F783, A5:F5, A781:F781, A5:F5, A779:F779, A5:F5, A777:F777, A5:F5, A775:F775, A5:F5, A773:F773, A5:F5, A771:F771, A5:F5, A769:F769, A5:F5, A767:F767, A5:F5, A765:F765, A5:F5, A763:F763, A5:F5, A761:F761, A5:F5, A759:F759, A5:F5, A757:F757, A5:F5, A755:F755, A5:F5, A753:F753, A5:F5, A751:F751, A5:F5, A749:F749, A5:F5, A747:F747, A5:F5, A745:F745, A5:F5, A743:F743, A5:F5, A741:F741, A5:F5, A739:F739, A5:F5, A737:F737, A5:F5, A735:F735, A5:F5, A733:F733, A5:F5, A731:F731, A5:F5, A729:F729, A5:F5, A727:F727, A5:F5, A725:F725, A5:F5, A723:F723, A5:F5, A721:F721, A5:F5, A719:F719, A5:F5, A717:F717, A5:F5, A715:F715, A5:F5, A713:F713, A5:F5, A711:F711, A5:F5, A709:F709, A5:F5, A707:F707, A5:F5, A705:F705, A5:F5, A703:F703, A5:F5, A701:F701, A5:F5, A699:F699, A5:F5, A697:F697, A5:F5, A695:F695, A5:F5, A693:F693, A5:F5, A691:F691, A5:F5, A689:F689, A5:F5, A687:F687, A5:F5, A685:F685, A5:F5, A683:F683, A5:F5, A681:F681, A5:F5, A679:F679, A5:F5, A677:F677, A5:F5, A675:F675, A5:F5, A673:F673, A5:F5, A671:F671, A5:F5, A669:F669, A5:F5, A667:F667, A5:F5, A665:F665, A5:F5, A663:F663, A5:F5, A661:F661, A5:F5, A659:F659, A5:F5, A657:F657, A5:F5, A655:F655, A5:F5, A653:F653, A5:F5, A651:F651, A5:F5, A649:F649, A5:F5, A647:F647, A5:F5, A645:F645, A5:F5, A643:F643, A5:F5, A641:F641, A5:F5, A639:F639, A5:F5, A637:F637, A5:F5, A635:F635, A5:F5, A633:F633, A5:F5, A631:F631, A5:F5, A629:F629, A5:F5, A627:F627, A5:F5, A625:F625, A5:F5, A623:F623, A5:F5, A621:F621, A5:F5, A619:F619, A5:F5, A617:F617, A5:F5, A615:F615, A5:F5, A613:F613, A5:F5, A611:F611, A5:F5, A609:F609, A5:F5, A607:F607, A5:F5, A605:F605, A5:F5, A603:F603, A5:F5, A601:F601, A5:F5, A599:F599, A5:F5, A597:F597, A5:F5, A595:F595, A5:F5, A593:F593, A5:F5, A591:F591, A5:F5, A589:F589, A5:F5, A587:F587, A5:F5, A585:F585, A5:F5, A583:F583, A5:F5, A581:F581, A5:F5, A579:F579, A5:F5, A577:F577, A5:F5, A575:F575, A5:F5, A573:F573, A5:F5, A571:F571, A5:F5, A569:F569, A5:F5, A567:F567, A5:F5, A565:F565, A5:F5, A563:F563, A5:F5, A561:F561, A5:F5, A559:F559, A5:F5, A557:F557, A5:F5, A555:F555, A5:F5, A553:F553, A5:F5, A551:F551, A5:F5, A549:F549, A5:F5, A547:F547, A5:F5, A545:F545, A5:F5, A543:F543, A5:F5, A541:F541, A5:F5, A539:F539, A5:F5, A537:F537, A5:F5, A535:F535, A5:F5, A533:F533, A5:F5, A531:F531, A5:F5, A529:F529, A5:F5, A527:F527, A5:F5, A525:F525, A5:F5, A523:F523, A5:F5, A521:F521, A5:F5, A519:F519, A5:F5, A517:F517, A5:F5, A515:F515, A5:F5, A513:F513, A5:F5, A511:F511, A5:F5, A509:F509, A5:F5, A507:F507, A5:F5, A505:F505, A5:F5, A503:F503, A5:F5, A501:F501, A5:F5, A499:F499, A5:F5, A497:F497, A5:F5, A495:F495, A5:F5, A493:F493, A5:F5, A491:F491, A5:F5, A489:F489, A5:F5, A487:F487, A5:F5, A485:F485, A5:F5, A483:F483, A5:F5, A481:F481, A5:F5, A479:F479, A5:F5, A477:F477, A5:F5, A475:F475, A5:F5, A473:F473, A5:F5, A471:F471, A5:F5, A469:F469, A5:F5, A467:F467, A5:F5, A465:F465, A5:F5, A463:F463, A5:F5, A461:F461, A5:F5, A459:F459, A5:F5, A457:F457, A5:F5, A455:F455, A5:F5, A453:F453, A5:F5, A451:F451, A5:F5, A449:F449, A5:F5, A447:F447, A5:F5, A445:F445, A5:F5, A443:F443, A5:F5, A441:F441, A5:F5, A439:F439, A5:F5, A437:F437, A5:F5, A435:F435, A5:F5, A433:F433, A5:F5, A431:F431, A5:F5, A429:F429, A5:F5, A427:F427, A5:F5, A425:F425, A5:F5, A423:F423, A5:F5, A421:F421, A5:F5, A419:F419, A5:F5, A417:F417, A5:F5, A415:F415, A5:F5, A413:F413, A5:F5, A411:F411, A5:F5, A409:F409, A5:F5, A407:F407, A5:F5, A405:F405, A5:F5, A403:F403, A5:F5, A401:F401, A5:F5, A399:F399, A5:F5, A397:F397, A5:F5, A395:F395, A5:F5, A393:F393, A5:F5, A391:F391, A5:F5, A389:F389, A5:F5, A387:F387, A5:F5, A385:F385, A5:F5, A383:F383, A5:F5, A381:F381, A5:F5, A379:F379, A5:F5, A377:F377, A5:F5, A375:F375, A5:F5, A373:F373, A5:F5, A371:F371, A5:F5, A369:F369, A5:F5, A367:F367, A5:F5, A365:F365, A5:F5, A363:F363, A5:F5, A361:F361, A5:F5, A359:F359, A5:F5, A357:F357, A5:F5, A355:F355, A5:F5, A353:F353, A5:F5, A351:F351, A5:F5, A349:F349, A5:F5, A347:F347, A5:F5, A345:F345, A5:F5, A343:F343, A5:F5, A341:F341, A5:F5, A3:F3, A338:F338, A3:F3, A336:F336, A3:F3, A334:F334, A3:F3, A332:F332, A3:F3, A330:F330, A3:F3, A328:F328, A3:F3, A326:F326, A3:F3, A324:F324, A3:F3, A322:F322, A3:F3, A320:F320, A3:F3, A318:F318, A3:F3, A316:F316, A3:F3, A314:F314, A3:F3, A312:F312, A3:F3, A310:F310, A3:F3, A308:F308, A3:F3, A306:F306, A3:F3, A304:F304, A3:F3, A302:F302, A3:F3, A300:F300, A3:F3, A298:F298, A3:F3, A296:F296, A3:F3, A294:F294, A3:F3, A292:F292, A3:F3, A290:F290, A3:F3, A288:F288, A3:F3, A286:F286, A3:F3, A284:F284, A3:F3, A282:F282, A3:F3, A280:F280, A3:F3, A278:F278, A3:F3, A276:F276, A3:F3, A274:F274, A3:F3, A272:F272, A3:F3, A270:F270, A3:F3, A268:F268, A3:F3, A266:F266, A3:F3, A264:F264, A3:F3, A262:F262, A3:F3, A260:F260, A3:F3, A258:F258, A3:F3, A256:F256, A3:F3, A254:F254, A3:F3, A252:F252, A3:F3, A250:F250, A3:F3, A248:F248, A3:F3, A246:F246, A3:F3, A244:F244, A3:F3, A242:F242, A3:F3, A240:F240, A3:F3, A238:F238, A3:F3, A236:F236, A3:F3, A234:F234, A3:F3, A232:F232, A3:F3, A230:F230, A3:F3, A228:F228, A3:F3, A226:F226, A3:F3, A224:F224, A3:F3, A222:F222, A3:F3, A220:F220, A3:F3, A218:F218, A3:F3, A216:F216, A3:F3, A214:F214, A3:F3, A212:F212, A3:F3, A210:F210, A3:F3, A208:F208, A3:F3, A206:F206, A3:F3, A204:F204, A3:F3, A202:F202, A3:F3, A200:F200, A3:F3, A198:F198, A3:F3, A196:F196, A3:F3, A194:F194, A3:F3, A192:F192, A3:F3, A190:F190, A3:F3, A188:F188, A3:F3, A186:F186, A3:F3, A184:F184, A3:F3, A182:F182, A3:F3, A180:F180, A3:F3, A178:F178, A3:F3, A176:F176, A3:F3, A174:F174, A3:F3, A172:F172, A3:F3, A170:F170, A3:F3, A168:F168, A3:F3, A166:F166, A3:F3, A164:F164, A3:F3, A162:F162, A3:F3, A160:F160, A3:F3, A158:F158, A3:F3, A156:F156, A3:F3, A154:F154, A3:F3, A152:F152, A3:F3, A150:F150, A3:F3, A148:F148, A3:F3, A146:F146, A3:F3, A144:F144, A3:F3, A142:F142, A3:F3, A140:F140, A3:F3, A138:F138, A3:F3, A136:F136, A3:F3, A134:F134, A3:F3, A132:F132, A3:F3, A130:F130, A3:F3, A128:F128, A3:F3, A126:F126, A3:F3, A124:F124, A3:F3, A122:F122, A3:F3, A120:F120, A3:F3, A118:F118, A3:F3, A116:F116, A3:F3, A114:F114, A3:F3, A112:F112, A3:F3, A110:F110, A3:F3, A108:F108, A3:F3, A106:F106, A3:F3, A104:F104, A3:F3, A102:F102, A3:F3, A100:F100, A3:F3, A98:F98, A3:F3, A96:F96, A3:F3, A94:F94, A3:F3, A92:F92, A3:F3, A90:F90, A3:F3, A88:F88, A3:F3, A86:F86, A3:F3, A84:F84, A3:F3, A82:F82, A3:F3, A80:F80, A3:F3, A78:F78, A3:F3, A76:F76, A3:F3, A74:F74, A3:F3, A72:F72, A3:F3, A70:F70, A3:F3, A68:F68, A3:F3, A66:F66, A3:F3, A64:F64, A3:F3, A62:F62, A3:F3, A60:F60, A3:F3, A58:F58, A3:F3, A56:F56, A3:F3, A54:F54, A3:F3, A52:F52, A3:F3, A50:F50, A3:F3, A48:F48, A3:F3, A46:F46, A3:F3, A44:F44, A3:F3, A42:F42, A3:F3, A40:F40, A3:F3, A38:F38, A3:F3, A36:F36, A3:F3, A34:F34, A3:F3, A32:F32, A3:F3, A30:F30, A3:F3, A28:F28, A3:F3, A26:F26, A3:F3, A24:F24, A3:F3, A22:F22, A3:F3, A20:F20, A3:F3, A18:F18, A3:F3, A16:F16, A3:F3, A14:F14, A3:F3, A12:F12, A3:F3, A10:F10, A3:F3, A8:F8, A3:F3, A6:F6, A3:F3, A4:F4, A3:F3, A2:F2
Total duplicates: 3
- List1!A4:F4
- List1!A5:F5
- List1!A3:F3

WS.MERGEDRANGES:  A1:F1, A501:F501, A3:F3, A499:F499, A3:F3, A497:F497, A3:F3, (...)
Total duplicates: 1
- List1!A3:F3

WS.MERGEDRANGES:  A1:F1, A501:F501, A4:F4, A499:F499, A4:F4, (...)
Total duplicates: 1
- List1!A4:F4

WS.MERGEDRANGES:  A1:F1, A501:F501, A4:F4, A499:F499, A4:F4, A497:F497, A4:F4, (...)
Total duplicates: 2
- List1!A4:F4
- List1!A3:F3

WS.MERGEDRANGES: (...)
Total duplicates: 2
- List1!A3:F3
- List1!A4:F4

WS.MERGEDRANGES: (...)
Total duplicates: 2
- List1!A3:F3
- List1!A5:F5

**Comment by igitur** [comment]
Please provide a reduced test case to illustrate the problem. VB is OK.

**Comment by machj** [comment]
> Please provide a reduced test case to illustrate the problem. VB is OK.

Here it is:

~~~c#
using ClosedXML.Excel;
using System.Diagnostics;
using System.Linq;

namespace ClosedXMLbug
{
    class Program
    {
        static void Main(string[] args)
        {
            var wb = new XLWorkbook();
            var ws = wb.AddWorksheet("Sheet1");

            //create merged row
            ws.Cell("A1").Value = "Merged Row(1) of Range (A1:F1)";
            ws.Range("A1:F1").Row(1).Merge();

            // Get the first row
            var row = ws.FirstRow();

            // Add some lines and copy format & merging
            for (var r = 1; r <= 500; r++)
            {
                row.InsertRowsBelow(1);         // insert a row below row 1, as a row 2
                row.CopyTo(row.RowBelow());     // copy format and merging from row 1 to row 2
            }

            var duplicates = ws.MergedRanges.GroupBy(s => s.ToString()).Where(g => g.Count() > 1).Select(y => new { Element = y.Key, Counter = y.Count() }).ToList();
            Debug.Assert(duplicates.Count == 0, "MergedRanges is corrupted!");

            wb.SaveAs("result.xlsx");
        }
    }
}
~~~
