### ISSUE TITLE
Cells.GetValue<Decimal>() does not handle exponential notation

### ISSUE THREAD

**Issue by PrairieTrailDave** [ClosedXML/ClosedXML#1014]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

Copied the convert code from the development version and tested with that. 

**What is the current behavior?**

Attempt to GetValue<Decimal>() on "1.60000001869776E-06" will throw an exception but Excel handles it quite nicely.

The current code (TryGetValue) has on line 1612
            if (typeof(T) == typeof(decimal)) return TryGetBasicValue<T, decimal>(out value, strValue, decimal.TryParse);

TryGetBasicValue code is:
            if (func(currValue, out U tmp))
            {
                value = (T)Convert.ChangeType(tmp, typeof(T));
                {
                    return true;
                }
            }
            value = default(T);
            return false;

When TryGetBasicValue is fed the exponent value, it returns false. GetValue then generates the exception. 

**What is the expected behavior or new feature?**

I would recommend changing the call from TryGetBasicValue to one that specifically handles decimals. 

            if (typeof(T) == typeof(decimal)) 
            {
                NumberStyles style = System.Globalization.NumberStyles.Any, // <-- this allows for everything but hex numbers
                if (Decimal.TryParse (strValue, style, 
                        System.Globalization.CultureInfo.CreateSpecificCulture("es-US"), out value)
                     return true;
                value = default(T);
                return false;
            }

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.

            XLWorkbook Workbook = new XLWorkbook("WorksheetSample.xlsx");
            IXLWorksheet WorkSheet = Workbook.Worksheet(1);
 
     // the following statement causes an exception
            Decimal value = WorkSheet.Cell(1, 1).GetValue<Decimal>();


}
```
- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)
[WorksheetSample.xlsx](https://github.com/ClosedXML/ClosedXML/files/2448324/WorksheetSample.xlsx)

**Comment by igitur** [comment]
I'm just curious. Why specifically are you using `decimal` instead of `double`?

**Comment by PrairieTrailDave** [comment]
Because, in the application this was discovered in, double was changing the 8/9th decimal place and that change was significant.

**Comment by igitur** [comment]
ClosedXML stores numeric values internally as `double` values. So you might run into the same problem anyway. I think the limitation is in OpenXML itself. I'll have to double check that though.

**Comment by igitur** [comment]
Try the build at https://ci.appveyor.com/project/ClosedXML/closedxml/builds/19400383/job/464k32bfag365l8k/artifacts please

**Comment by PrairieTrailDave** [comment]
Thank you. I’ll admit to my ignorance. I have never pulled a package in from this type of format and I could not get NuGet to install this.

**Comment by PrairieTrailDave** [comment]
The install-package never worked, but when I restructured the test and simply replaced the dll, the test worked.

Thank you.

David Randolph
