### ISSUE TITLE
DataValidation.List does not work with larger input

### ISSUE THREAD

**Issue by horato** [ClosedXML/ClosedXML#1016]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

dev

**What is the current behavior?**

When cell list validation is added with values exceeding certain character limit, excel refuses to open the xls and asks for repair.
I am using the `void List(string list, bool inCellDropdown);` overload

**What is the expected behavior or new feature?**

The file can be opened without repair and validation dropdown is present.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
    var filePath = "test.xlsx";
            using (var workbook = new XLWorkbook())
            {
                var values = new List<string>();
                for (var i = 0; i < 20; i++)
                {
                    values.Add(Guid.NewGuid().ToString("N"));
                }

                workbook.AddWorksheet("Sheet 1");
                workbook.Worksheet("Sheet 1").Cell(1, 1).DataValidation.List($"\"{string.Join(",", values)}\"", true);
                workbook.SaveAs(filePath);
            }
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by Pankraty** [comment]
Fill in the complete issue template. It was created by purpose.

**Comment by horato** [comment]
done

**Comment by Pankraty** [comment]
It's not the CLosedXML issue. You cannot specify more than 255 characters (delimiters included) in Excel either. If you seek for a possibility to choose from a larger list of values use the reference to the range.

ClosedXML, on the other hand, could raise the exception on an attempt to specify a longer value. This can be easily done.
