### ISSUE TITLE
ClosedXML - How can you test for style on specific characters within a cell?

### ISSUE THREAD

**Issue by bwiltfong** [ClosedXML/ClosedXML#1018]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [X] Feature

**Version of ClosedXML**

Ver 0.87.0

**What is the current behavior?**
Not sure if this is a current feature. Do not see it in the documentation.

**What is the expected behavior or new feature?**
I would like to be able to test on each character of a cell if a character has a strikethrough. I have spreadsheets with cells that have some strikethrough characters in part of the cell. In some cases I want to remove these characters.

## Description
I'm replacing code that uses the Excel Interop. The Excel Interop has a method called ".characters" allowing it to look at a position and length within a cell. 

In the code below, if IgnoreStrikeThrough is set to false, then it will return the contents of a cell without any characters that were formatted with the strikethrough characters. Besides looping through each character, I couldn't find a way to replace based on the style.

This sample was converted from VB.NET to C#.

**Code to reproduce problem:**
```c#
    private Microsoft.Office.Interop.Excel.Application xlApp;
    private Microsoft.Office.Interop.Excel.Workbook xlWB;
    private Microsoft.Office.Interop.Excel.Worksheet xlWS;

public string GetCellContents(int Column, int Row, bool IgnoreStrikeThrough = true)
{
    xlWS.Range(xlWS.Cells(Row, Column), xlWS.Cells(Row, Column)).Columns.HorizontalAlignment = Excel.XlHAlign.xlHAlignLeft;

    if (IgnoreStrikeThrough)
        return xlWS.Cells(Row, Column).text.ToString;
    else
    {
        string Remaining = "";
        string CurrentCell = xlWS.Cells(Row, Column).text.ToString;

        for (int CharLoop = 1; CharLoop <= CurrentCell.Length; CharLoop++)
        {
            if (xlWS.Cells(Row, Column).characters(CharLoop, 1).font.strikethrough == false)
                Remaining += CurrentCell.Substring(CharLoop - 1, 1);
        }

        return Remaining;
    }
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)
[StrikethroughExample.xlsx](https://github.com/ClosedXML/ClosedXML/files/2461668/StrikethroughExample.xlsx)

**Comment by igitur** [comment]
Refer to https://github.com/ClosedXML/ClosedXML/wiki/Using-Rich-Text (specifically at the bottom of that page).
