### ISSUE TITLE
ClosedXML fails in Azure Functions v2 for non-trivial operations

### ISSUE THREAD

**Issue by AdrianPell** [ClosedXML/ClosedXML#1020]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.93.1 (but also latest dev build)

**What is the current behavior?**

Using ClosedXML in Azure Functions v2 throws a "Platform Not Supported" exception when requiring the use of any functionality from XLHelper (e.g. resolving an A1-type reference)

**What is the expected behavior or new feature?**

Ideally, normal functionality would be available - but since this appears to be a System.Drawing issue, having non-graphics related operations succeed would be sufficient.

**Did this work in previous versions of our tool?  Which versions?**

Yes, in Azure Functions v1 (.NET Framework based)

**Code to reproduce problem:**
This needs to be run as part of an Azure Functions v2 project, not a console app.  Sorry!

```c#
    public static class Function1
    {
        [FunctionName("TestClosedXML")]
        public static async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = null)]HttpRequest req, ILogger log)
        {
            log.LogInformation("Function start.");

            var workbook = new XLWorkbook();
            var worksheet = workbook.AddWorksheet("Sheet 1");
            worksheet.Cell("A1").SetValue<string>("Hello");

            return new OkObjectResult("Success");
        }
    }
```

**Problem identification:**

XLHelper.cs has a static dependency on System.Drawing.Bitmap (lines 24 and 25):
```c#
internal static readonly Graphics Graphic = Graphics.FromImage(new Bitmap(200, 200));
internal static readonly Double DpiX = Graphic.DpiX;
```
The constructor for System.Drawing.Bitmap throws the PlatformNotSupported exception because Azure Functions v2 (Web Apps in general) run in a sandbox which denies access to Win32 functions, even when those are supported by the .Net Standard assemblies (see [this article](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#win32ksys-user32gdi32-restrictions)).

Can we move that into a function that is only called if necessary? Graphics-related functions might still fail (but could perhaps be caught in a cleaner manner) but non-graphics operations would succeed.

**Comment by ThomsCass** [comment]
+1

**Comment by tjones0808** [comment]
was this fixed? still getting this issue with azure functions

**Comment by igitur** [comment]
Nobody has submitted a fix yet, so no, as far as I'm aware, it hasn't been fixed.

**Comment by igitur** [comment]
@tjones0808 Sorry, there was a fix to lazy load the references to `Bitmap`, which was a problem on sandboxed environment. If you don't need it, e.g. if you don't call `ws.Columns().AdjustToContents()` then it should work for you. However, if you do make a call to methods that require to any `System.Drawing.Common` functions, then you'll get the exception.

**Comment by tjones0808** [comment]
@igitur  hmm ok, im just calling the worksheets.add function and azure functions doesnt like it.

**Comment by tjones0808** [comment]
@igitur  ahh ok i got ya. Manually added my datatable without the AdjustToContents and we're good to go. thanks!

**Comment by Pankraty** [comment]
I finally managed to try Azure Functions myself, and `AdjustToContents()` seems to work in version 3.

Code of my function:
```
            string name = req.Query["name"];
            var wb = new XLWorkbook();
            var ws = wb.AddWorksheet();
            ws.FirstCell().Value = name;
            ws.Column(1).AdjustToContents();
            var res = ws.Column(1).Width.ToString(CultureInfo.InvariantCulture);
            return new OkObjectResult(res);
```

Response to `?name=Test`: `4.71`
Response to `?name=TestTest`: `8.3`
