### ISSUE TITLE
Additional Cell Formatting Options

### ISSUE THREAD

**Issue by dkintgen** [ClosedXML/ClosedXML#103]
Is there any way to apply cell formatting options outside of the values found in the XLCellValues enum, such as percentage or custom?  If not, is there any plan to implement this functionality?

**Comment by igitur** [comment]
Have you looked at https://github.com/ClosedXML/ClosedXML/wiki/Styles-NumberFormat ?

**Comment by dkintgen** [comment]
Yes, thanks, this is what I am looking for.

I am trying to display a number as a percentage, but the Number Formats for percentage keep multiplying my number by 100.  For example, if I have the value 0.1, which I want to display as 0.1%, the formatter will display it as 10%.  Is there a way to prevent this?

**Comment by igitur** [comment]
That behaviour is as intended. 0.1 is equal to 10%.  You'll have to divide the value manually by a 100.
