### ISSUE TITLE
Retrieve the name of opened workbook ie Open file name

### ISSUE THREAD

**Issue by akshaybheda** [ClosedXML/ClosedXML#1040]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.93.1

**What is the current behavior?**

I cannot get the workbook name

**What is the expected behavior or new feature?**

There should be some property which gives the name of the opened workbook

**Did this work in previous versions of our tool?  Which versions?**

No

**Comment by igitur** [comment]
What do you mean by name? The filename?

**Comment by akshaybheda** [comment]
Yes i mean the filename.

**Comment by igitur** [comment]
You should be able to use standard `System.IO.FileInfo` for that information.

**Comment by akshaybheda** [comment]
I am passing file through the ctor but it would be useful if there is an property that gives filename/workbook name

**Comment by Pankraty** [comment]
```
public class WorkbookWithName : IDisposable
{
    public string FileName { get; set; }
    public IXLWorkbook Workbook { get; set; }
    public WorkbookWithName(string fileName)
    {
       // ..
    }
}
```

You can do something like this.

**Comment by igitur** [comment]
To add to this, notice that not all `XLWorkbook` instances are opened from a file. Some are opened from a `Stream` object, which could be any kind of stream, e.g. `MemoryStream`. In many of those cases, a filename isn't available. So it's better to leave the implementation up to you, as @Pankraty suggested in the previous comment.

That said, there is an existing `XLWorkbook.ToString()` method that might help you:

```c#
        public override string ToString()
        {
            switch (_loadSource)
            {
                case XLLoadSource.New:
                    return "XLWorkbook(new)";

                case XLLoadSource.File:
                    return String.Format("XLWorkbook({0})", _originalFile);

                case XLLoadSource.Stream:
                    return String.Format("XLWorkbook({0})", _originalStream.ToString());

                default:
                    throw new NotImplementedException();
            }
        }
```

**Comment by akshaybheda** [comment]
I was kind of looking for _originalFile. as exposed property. as the ToString() method adds "XLWorkbook()". Nevermind i will look for the value inside the brackets
