### ISSUE TITLE
Inserting an adjacent row does not copy the data validation of cells

### ISSUE THREAD

**Issue by gh5692** [ClosedXML/ClosedXML#1046]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.94.999.1469

**What is the current behavior?**

Inserting an adjacent row does not copy the data validation of cells.

**What is the expected behavior or new feature?**

Inserting an adjacent row does copy the data validation. This would be similar to how ClosedXML copies other cell attributes (e.g. text wrapping), and would mimic the behavior of Excel.

**Did this work in previous versions of our tool?  Which versions?**

I do not know if this worked in previous versions.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

**Code to reproduce problem:**
```c#
public void Main()
{
    using (var workbook = new XLWorkbook())
    using (var worksheet = workbook.AddWorksheet("WorksheetOne"))
    {
        worksheet.Range("A1:A3")
            .SetValue(1);

        //This will copy to new row on insert
        worksheet
            .Cell("A1")
            .Style
            .Alignment
            .SetWrapText(true);

        //This will not copy to new row on insert
        worksheet
            .Cell("A1")
            .DataValidation
            .Decimal
            .Between(0,1);

        worksheet
            .Row(2)
            .InsertRowsAbove(1);

        worksheet
            .Cell("A2")
            .InsertCellsAbove(1);

        workbook.SaveAs("WorkbookOne.xlsx");
    }
}
```
- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)
[WorkbookOne.xlsx](https://github.com/ClosedXML/ClosedXML/files/2516771/WorkbookOne.xlsx)

**Comment by igitur** [comment]
Good catch. Anything that is also omitted from being copied besides data validation?

**Comment by gh5692** [comment]
> Good catch. Anything that is also omitted from being copied besides data validation?

Thanks. I haven't noticed anything other than the data validation.
