### ISSUE TITLE
Remove Dependency on Original File Stream

### ISSUE THREAD

**Issue by JaedenRuiner** [ClosedXML/ClosedXML#1050]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [x] Feature

**Version of ClosedXML**
0.93.1

**What is the current behavior?**

Known issue:  Retention of IO.Stream used to Load workbook.

**What is the expected behavior or new feature?**

Don't do this.  Once loaded, the in-memory Workbook should retain all data necessary.  There is no need to retain access to the original file.  I know, because I have written my own xlsx interpreters and never once needed to maintain the original stream.  As well, if I can create a XLWorkbook from scratch and set everything in memory, then call SaveAs without needing an original source stream, then loading from a file should follow this default behavior as well.  

I understand that for the scenario of a possible Out-Of-Memory, there should be a specific methodology for handling "big" files, and in that one very rare circumstance does it make sense to keep reference to the source stream.  But this is not the norm.  

A good chuck of the usage of wrappers like ClosedXml, is to design a template file, and then load, populate, and save as during process operations.  In those circumstances it is natural to loading from streams like this:
```c#
using (Stream stream = FileInfo.Open(...)) {
  new XLWorkbook(stream);
}
```
You don't typically want to keep the file handle locked during in memory processes once it's been loaded.

**Did this work in previous versions of our tool?  Which versions?**
Haven't used previous versions so I don't know.

## Reproducibility
```c#
public void Main()
{
    FileInfo fi = new FIleInfo("filename.xlsx");
    XLWorkbook book;
    using (Stream stream = fi.OpenRead())
    {
       book = new XLWorkbook(stream);
    }
    book.Cell(3, 1).Value = "Hello";
    fi = new FileInfo("newfilename.xlsx");
    using (Stream stream = fi.OpenWrite())
    {
        book.SaveAs(stream); //This throws error because the first stream has been closed
    }
}
```

Thanks
Jaeden "Sifo Dyas" al'Raec Ruiner

PS - Granted there are work around, but we have several systems in place that many programs use which were originally wrapping Interop Excel operations.  Before ClosedXml became a more notable standard I wrote my own xml parser to read and process the xlsx file directly, again using  the same wrapper systems that make life easy.  Now, the above code is the "simple" reproduction, but the more complex systems in place means that I now have to retain the stream in my wrapper and dispose of it with the wrapper, which can create havoc and confusion in multi-threaded applications, all because ClosedXml requires the original file stream to remain open.

**Comment by igitur** [comment]
Hi. The behaviour is by design. This is to allow as much as possible of the unsupported features, eg charts (not supported by ClosedXML) to be retained in the `SaveAs` method. In that method the original stream is copied over to the destination stream (which keeps charts, etc in tact) and then ClosedXML overwrites the parts that it supports.

If you have to dispose your input stream before saving the workbook, I suggest you make a copy of the stream's contents in a new `MemoryStream` and pass that as input to your workbook.
