### ISSUE TITLE
Reading RichText Property Delete Value property

### ISSUE THREAD

**Issue by Tarboeuf** [ClosedXML/ClosedXML#1052]
## Read and complete the full issue template

- [x] Bug

**Version of ClosedXML**

0.93
0.94 (develop branch at the time of the bug)

**What is the current behavior?**

After reading the RichText property, the Value property return null.

**Did this work in previous versions of our tool?  Which versions?**

I don't know.

## Reproducibility

```c#
public void Main()
{
    using (XLWorkbook wb = new XLWorkbook(@"D:\RichTextReadIssue.xlsx"))
    {
        Console.WriteLine("First time value " + wb.Worksheets.First().Cell("A1").Value);
        Console.WriteLine("RichText value " + wb.Worksheets.First().Cell("A1").RichText.Text);
        Console.WriteLine("Second time value " + wb.Worksheets.First().Cell("A1").Value);
        Console.Read();
    }
}
```
The console display
```
First time value 6807
RichText value 6,807
Second time value
```
- [x] I attached a sample spreadsheet.
[RichTextReadIssue.xlsx](https://github.com/ClosedXML/ClosedXML/files/2528777/RichTextReadIssue.xlsx)

**Comment by Tarboeuf** [comment]
FYI, 
I found a workaround using GetFormattedString() instead of RichText

**Comment by igitur** [comment]
The file that you attached doesn't have any rich text in cell A1. It just contains a number.

When you call `.Value`, it just returns the value.
When you call `.RichText.Value`, the code creates a new `XLRichText` class and populates it with the `.GetFormattedString()` value. This also clears the default `.Value`, which is why it returns a null the 2nd time you call it.

```c#
public IXLRichText RichText
{
    get
    {
        if (_richText == null)
        {
            var style = GetStyleForRead();
            _richText = _cellValue.Length == 0
                            ? new XLRichText(new XLFont(Style as XLStyle, style.Font))
                            : new XLRichText(GetFormattedString(), new XLFont(Style as XLStyle, style.Font));
        }

        return _richText;
    }
}
```

**Comment by igitur** [comment]
You can use `IXLCell.HasRichText` to peek whether the cell has rich text without creating a new `XLRichText` class.
