### ISSUE TITLE
Use different version of DocumentFormat.OpenXML.dll

### ISSUE THREAD

**Issue by jomabes** [ClosedXML/ClosedXML#1053]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.93.1.0

**What is the current behavior?**
failed to load DocumentFormat.OpenXML.dll version 2.7.2.0

Description/Requirement:
At the customer enviorment, there ist an old version of the dll "DocumentFormat.OpenXML (2.5.5631.0)" which is used by other libraries. ClosedXML needs version 2.7.2.0 of these file. We have tried to configure it out by inserting the runtime, assemblyBining and dependentAssembly tags at the app.config file, without success. I think this is based, that we deliver an library (.dll) and no application (.exe). My idea to solve this problem, are to rename the DocumentFormat.OpenXML.dll like DocmentFormat.OpenXML2720.dll. It's only an approach to solve this problem. Whats your proposal to take this requirement to success?

changes  app.config file:
`<?xml version="1.0" encoding="utf-8" ?>
<configuration>
 <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="ADReportengine;" />
-      <dependentAssembly>
        <assemblyIdentity name="ClosedXML"  culture="neutral" publicKeyToken="null"/>
        <codeBase version="0.93.1.0" href="FILE:///D:/xxxxx/xxxxx/Bin/ADReportengine/ClosedXML.dll"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="DocumentFormat.OpenXml"  culture="neutral" publicKeyToken="8fb06cb64d019a17"/>
        <codeBase version="2.7.2.0" href="FILE:///D:/xxxxx/xxxxx/Bin/ADReportengine/DocumentFormat.OpenXml.dll"/>
      </dependentAssembly>
    </assemblyBinding>
 </runtime>
</configuration>`

**Comment by vbjay** [comment]
You need to put the binding config in the exe.config.

**Comment by jomabes** [comment]
Hi Francois,


thanks for your answer. You are right, the public key have changed between the two versions. Unfortunately it's not possible for me to upgrade the third party libraries. But  I have solved this issue by using the "bingingRedircet" statement in the app.config
 file of the master application (<bindingRedirect oldVersion="2.5.5631.0-2.7.2.0" newVersion="2.7.2.0" />). At the moment the solution works fine, but I have not tested  all cases. Your suggestion, to download the source code of closedXLM is also an option
 for me. I will try to do this. If you agree with me, I want that all users can parcitipate of this information. How can I do this? Shall I post it at the wiki?



Best regards
Joachim​





Von: Francois Botha <notifications@github.com>
Gesendet: Dienstag, 30. Oktober 2018 15:28
An: ClosedXML/ClosedXML
Cc: Weber, Joachim; Author
Betreff: Re: [ClosedXML/ClosedXML] Use different version of DocumentFormat.OpenXML.dll (#1053)
 


This is not a ClosedXML issue, but you will notice that the public key for DocumentFormat.OpenXml changed between v2.5.0 (31bf3856ad364e35) and v2.7.1 (8fb06cb64d019a17). There's nothing I can do it, sorry.
My suggestion is that the other libraries upgrade their references to DocumentFormat.OpenXml. That's the best solution. If you can't manage that, I suggest you download ClosedXML's source code and do a custom build, but reference v2.5.0 of OpenXml. You might
 need to exclude or fix some issues. I'm not sure whether ClosedXML will build against that version of OpenXml as is.
As @vbjay mentioned, there might be a solution by using binding redirects, but I don't have any experience referencing multiple versions of the same strong named assembly that has multiple public
 key tokens.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.




 












-------------------------------------------------------     >>> business. people. technology. <<<-------------------------------------------------------adesso AG mit Sitz in DortmundVorstand: Michael Kenfenheuer (Vors.), Christoph Junge, Dirk Pothen, Andreas PrenneisVorsitzender des Aufsichtsrates: Prof. Dr. Volker GruhnAmtsgericht Dortmund HRB 20663

**Comment by igitur** [comment]
Thanks for your offer, but I would like to discourage users from using such an old version of DocumentFormat.OpenXml, so I don't think it's necessary to post this on the wiki. Closing this issue now, as you seem to have solved it.
