### ISSUE TITLE
DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Marusyk** [ClosedXML/ClosedXML#1056]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.92.1

**Wh at is the current behavior?**

I got an exception
> System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
>    at Interop.Libdl.dlopen(String fileName, Int32 flag)
>    at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
>    at System.Drawing.SafeNativeMethods.Gdip..cctor()
> System.TypeInitializationException: The type initializer for 'Gdip' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
>    at Interop.Libdl.dlopen(String fileName, Int32 flag)
>    at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
>    at System.Drawing.SafeNativeMethods.Gdip..cctor()
>    --- End of inner exception stack trace ---
>    at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, PixelFormat format, IntPtr scan0, IntPtr& bmp)
>    at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
>    at ClosedXML.Excel.XLHelper..cctor()
> System.TypeInitializationException: The type initializer for 'ClosedXML.Excel.XLHelper' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Gdip' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
>    at Interop.Libdl.dlopen(String fileName, Int32 flag)
>    at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
>    at System.Drawing.SafeNativeMethods.Gdip..cctor()
>    --- End of inner exception stack trace ---
>    at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, PixelFormat format, IntPtr scan0, IntPtr& bmp)
>    at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
>    at ClosedXML.Excel.XLHelper..cctor()
>    --- End of inner exception stack trace ---
>    at ClosedXML.Excel.XLCell.SetValue(Object value)
>    at ClosedXML.Excel.XLCell.set_Value(Object value)
>    at CaoWijzer.API.Features.Surcharges.Get.OutputFormatters.ExcelConverter.FillSheetTemplate(IXLWorksheet worksheet, Surcharge surcharge) in /src/CaoWijzer.API/Features/Surcharges/Get/OutputFormatters/ExcelConverter.cs:line 113
>    at CaoWijzer.API.Features.Surcharges.Get.OutputFormatters.ExcelConverter.ConvertSurchargesToExcel(ICollection`1 surcharges, ICollection`1 dayOfWeeks) in /src/CaoWijzer.API/Features/Surcharges/Get/OutputFormatters/ExcelConverter.cs:line 90
>    at CaoWijzer.API.Features.Surcharges.Get.OutputFormatters.ExcelOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context) in /src/CaoWijzer.API/Features/Surcharges/Get/OutputFormatters/ExcelOutputFormatter.cs:line 40
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

## Reproducibility

I use ClosedXML in aspnetcore2.1 project that runs in linux Docker contailer (microsoft/dotnet:2.1-aspnetcore-runtime)

**Code to reproduce problem:**
```c#
using (var workbook = new XLWorkbook())
{
        using (IXLWorksheet worksheet = workbook.Worksheets.Add("Empty"))
         {
              worksheet.Cell(1, 1).Value = "Name";  <- Here an exception
          }
}
```

**Comment by Marusyk** [comment]
Found solution here https://github.com/dotnet/dotnet-docker/issues/618

**Comment by gerbertsantos** [comment]
@Marusyk Thanks!

**Comment by wan766405890** [comment]
How to Solve it on windows

**Comment by WREpic** [comment]
I have this same issue but with a different library, any ideas how to solve it?

System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcvextern: cannot open shared object file: No such file or directory
