### ISSUE TITLE
IDisposable was removed from IXLRow

### ISSUE THREAD

**Issue by zgirod** [ClosedXML/ClosedXML#1057]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Version of ClosedXML**

0.93.1 (Latest as of now)

**What is the current behavior?**

I am currently using 0.92.1 and based upon the documentation here https://github.com/ClosedXML/ClosedXML/wiki/Where-to-use-the-using-keyword I have code like the following:

```
using (var workbook = new XLWorkbook())
{
    var worksheet = workbook.Worksheets.Add("Sample Sheet");
    using(var excelRow = worksheet.Row(1))
    {
        //do something
    }
    workbook.SaveAs("HelloWorld.xlsx");
}
```

I am updating to 0.93.1 and that same code is throwing an error.  Did you mean to get rid of IDisposable and there is a new recommended way or was that an accident?  See the following screen shots.

![0 92 1](https://user-images.githubusercontent.com/252274/47928925-f7988600-de9d-11e8-8f10-364a1643d1f3.PNG)
![0 93 1](https://user-images.githubusercontent.com/252274/47928926-f7988600-de9d-11e8-88fc-6bf553b3bc6c.PNG)
![error](https://user-images.githubusercontent.com/252274/47928927-f7988600-de9d-11e8-89e1-04b09416ea24.PNG)

**What is the expected behavior or new feature?**

I would think IXLRow should still implement IDisposable.

**Did this work in previous versions of our tool?  Which versions?**

Yes. 0.92.1

## Reproducibility

I did this above, you can use the code above and toggle between nuget 0.92.1 and 0.93.0 or 0.93.1.

- no sample file needed.

**Comment by igitur** [comment]
Yes, see https://github.com/ClosedXML/ClosedXML/releases/tag/0.93.0

I'll update the wiki.
