### ISSUE TITLE
simple reading textbox from excel file

### ISSUE THREAD

**Issue by benjamin275** [ClosedXML/ClosedXML#1059]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.93.1

i simply try to read a textbox from a excel file. They textbox has e.g. the name textbox_22
Im not able to see or find any API hat the ClosedXML.dll to read the values of this textbox.

**Comment by igitur** [comment]
Textboxes, shapes, charts, etc aren't supported yet.

**Comment by benjamin275** [comment]
any timeframe or is it hard to solve ?

**Comment by vbjay** [comment]
Pull requests are welcome.

**Comment by benjamin275** [comment]
thx for you answer so far
