### ISSUE TITLE
Defined Name Visibility

### ISSUE THREAD

**Issue by Moonlgum** [ClosedXML/ClosedXML#106]
Please add visiblity property to defined names.

Seems like it should be easy to implement for reading 
var visible = definedName.Hidden == null;

Thanks!

**Comment by igitur** [comment]
Excuse my ignorance, but where in Excel does one manage visibility for defined names? I've never seen that.

**Comment by Moonlgum** [comment]
It's not managed directly through the UI that I know of, but can be accessed from VBA. e.g. :
    Dim n As Name        n.Visible = False 

    On Tuesday, December 6, 2016 1:25 PM, Amir <notifications@github.com> wrote:
 

 Closed #106 via #116.—
