### ISSUE TITLE
How I can insert X Y Scatter Chart to excel?

### ISSUE THREAD

**Issue by VahedCivil** [ClosedXML/ClosedXML#1060]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

How I can insert  Scatter Chart with X and Y data to excel?

**Comment by igitur** [comment]
Charts aren't supported yet. I'm waiting for user contributions in this regard.

**Comment by VahedCivil** [comment]
Thanks.
