### ISSUE TITLE
large numbers

### ISSUE THREAD

**Issue by ManuelmJY** [ClosedXML/ClosedXML#1061]
Hi,
is there a way to prevent Excel to format large numbers in Exponent style?

I've  tried following according to the wiki entries.
```c#
XLWorkbook wb = new XLWorkbook();
wb.Worksheets.Add(dt, "Report" + jahr);
wb.Cells("GLN").Style.NumberFormat.Format = "0";
```
kind regards
Manuel

**Comment by igitur** [comment]
Format the cell in Excel the way you want it, check out what the format string is, and use that in your code to format the cell.

**Comment by igitur** [comment]
or try this

```c#
ws.Cell("A10")
    .SetValue(123456789123)
    .Style.NumberFormat.SetNumberFormatId((int)XLPredefinedFormat.Number.Integer);
```

**Comment by ManuelmJY** [comment]
thank you!
It's working now.

```C#
 wb.Worksheet("Report" +jahr).Columns("A,B,M").Style.NumberFormat.SetNumberFormatId((int)XLPredefinedFormat.Number.Integer);
```

**Comment by ArafatSabbir** [comment]
> 

Thanks @igitur  It's working.
