### ISSUE TITLE
Excel Comments (Sizing) gets distroyed when inserting a row at row 1 

### ISSUE THREAD

**Issue by datamd** [ClosedXML/ClosedXML#1062]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.93.1.0

**What is the current behavior?**

1) I add cell values and cell comments and autosize the comments then 
2) I add in a row at row 1 then
3) The Error is my excel comments sizing looks all bad 

**What is the expected behavior or new feature?**

To remember the settings before rows are added at row 1

**Did this work in previous versions of our tool?  Which versions?**

Unknown ... only using latest version 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{

I have code that looks like the following 2 lines 

                ws.Cell(intRow, intCol).Comment.SetVisible(false).AddText(strExcelComment);
                ws.Cell(intRow, intCol).Comment.Style.Alignment.SetAutomaticSize();

later this final line messes up the Excel Comment Sizes created by the above 2 lines

            ws.Row(1).InsertRowsAbove(1);

            for (int intCol = 1; intCol < 101; intCol = intCol + 7)
            {
                ws.Cell(1, intCol + 3).Value = "Mon";
                ws.Cell(1, intCol + 4).Value = "Tue";
                ws.Cell(1, intCol + 5).Value = "Wed";
                ws.Cell(1, intCol + 6).Value = "Thu";
                ws.Cell(1, intCol + 7).Value = "Fri";
                ws.Cell(1, intCol + 8).Value = "Sat";
                ws.Cell(1, intCol + 9).Value = "Sun";
            }


File callled "Comments_Sizing_Issues_Bad_And_Good.xlsx" is Attached 

I enjoy using the ClosedXML code - keep up the great work - many thanks in advance 

[Comments_Sizing_Issues_Bad_And_Good.xlsx](https://github.com/ClosedXML/ClosedXML/files/2558184/Comments_Sizing_Issues_Bad_And_Good.xlsx)


}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by datamd** [comment]
[Comments_Sizing_Issues_Bad_And_Good.xlsx](https://github.com/ClosedXML/ClosedXML/files/2558202/Comments_Sizing_Issues_Bad_And_Good.xlsx)

**Comment by igitur** [comment]
Please a code sample I can compile.

**Comment by datamd** [comment]
CODE is here

using System;
using ClosedXML.Excel;

namespace ExcelCommentSizingProbs
{
    class Program
    {
        static void Main(string[] args)
        {
            var wb = new XLWorkbook();
            var ws = wb.AddWorksheet("ExcelCommentsSizeIssue");

            string strExcelComment = "1) ABCDEFGHIJKLMNOPQRSTUVWXYZ ABC ABC
ABC ABC ABC" + Environment.NewLine;
            strExcelComment = strExcelComment + "1)
ABCDEFGHIJKLMNOPQRSTUVWXYZ ABC ABC ABC ABC ABC" + Environment.NewLine;
            strExcelComment = strExcelComment + "2)
ABCDEFGHIJKLMNOPQRSTUVWXYZ ABC ABC ABC ABC ABC" + Environment.NewLine;
            strExcelComment = strExcelComment + "3)
ABCDEFGHIJKLMNOPQRSTUVWXYZ ABC ABC ABC ABC ABC" + Environment.NewLine;
            strExcelComment = strExcelComment + "4)
ABCDEFGHIJKLMNOPQRSTUVWXYZ ABC ABC ABC ABC ABC" + Environment.NewLine;
            strExcelComment = strExcelComment + "5)
ABCDEFGHIJKLMNOPQRSTUVWXYZ ABC ABC ABC ABC ABC" + Environment.NewLine;
            strExcelComment = strExcelComment + "6)
ABCDEFGHIJKLMNOPQRSTUVWXYZ ABC ABC ABC ABC ABC" + Environment.NewLine;
            strExcelComment = strExcelComment + "7)
ABCDEFGHIJKLMNOPQRSTUVWXYZ ABC ABC ABC ABC ABC" + Environment.NewLine;
            strExcelComment = strExcelComment + "8)
ABCDEFGHIJKLMNOPQRSTUVWXYZ ABC ABC ABC ABC ABC" + Environment.NewLine;
            strExcelComment = strExcelComment + "9)
ABCDEFGHIJKLMNOPQRSTUVWXYZ ABC ABC ABC ABC ABC" + Environment.NewLine;
//Step 1
            ws.Cell(2, 2).Value = "Comment 1";
            ws.Cell(2,
2).Comment.SetVisible(false).AddText(strExcelComment);
            ws.Cell(2, 2).Comment.Style.Alignment.SetAutomaticSize();
//Step 2
            ws.Row(1).InsertRowsAbove(1);
            ws.Cell(1, 1).Value = "Row 1 INSERTED";
// Step3
            ws.Cell(4, 2).Value = "Comment 2";
            ws.Cell(4,
2).Comment.SetVisible(false).AddText(strExcelComment);
            ws.Cell(4, 2).Comment.Style.Alignment.SetAutomaticSize();
            wb.SaveAs("Output.xlsx");


        }
    }
}


Regards
Mark Dicken

**Comment by datamd** [comment]
[code.txt](https://github.com/ClosedXML/ClosedXML/files/2558324/code.txt)
