### ISSUE TITLE
Cell With Apostrophe Has Symbol Removed

### ISSUE THREAD

**Issue by TechyGypo** [ClosedXML/ClosedXML#1069]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.93.1

**What is the current behavior?**

If a spreadsheet already has a cell with it's contents set to only `'` (to identify it as a text), when the sheet is saved the apostrophe is no longer there.

The `'` is not being added via code, it was added by a user (already in the file). See attached file as an example.

**What is the expected behavior or new feature?**

When a sheet is saved, the user entered `'` should remain intact.

**Did this work in previous versions of our tool?  Which versions?**

No _That I know of_

**Code to reproduce problem:**
```c#
public void Main()
{
    //Using attached file
    ClosedXML.Excel.XLWorkbook wkbk = new ClosedXML.Excel.XLWorkbook("C:\Book1.xlsx");
    wkbk.SaveAs("C\Book2.xlsx");
}
```
- [Book1.xlsx](https://github.com/ClosedXML/ClosedXML/files/2575987/Book1.xlsx)

**Comment by igitur** [comment]
Did you try with the latest version?

**Comment by TechyGypo** [comment]
I used NuGet manager in Visual Studio and 0.93.1 is marked as the latest stable version. So as far as I can see: yes.

**Comment by igitur** [comment]
0.94.0-rc1 is out.

**Comment by TechyGypo** [comment]
Thank you. I installed 0.94.0-rc1 and have the same symptoms.
