### ISSUE TITLE
Poor performance with data validation

### ISSUE THREAD

**Issue by zabulus** [ClosedXML/ClosedXML#1071]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
tried 0.93.1 and 0.94.999.1504

**What is the current behavior?**
Generation of excel file takes too long. Have waited for 10 minutes, and still not completed.

**Did this work in previous versions of our tool?  Which versions?**
Yes. Using the 0.87.1 version the same generation takes around 1 sec.

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
            XLWorkbook template = new XLWorkbook(@"Template.xlsx");
            var ws = template.Worksheet("Template");
            XLWorkbook template2 = new XLWorkbook();
            ws.CopyTo(template2, "2");
}
```
The issue is with the template.xlsx content + CopyTo method call. There are 1000+ rows with data validation and formatting of cells. 
Template is narrowed down sample, that demonstrates the same issue we have with our prod template.
[Template.xlsx](https://github.com/ClosedXML/ClosedXML/files/2589139/Template.xlsx)

**Comment by zabulus** [comment]
Do you need any additional info?

**Comment by igitur** [comment]
I'm focusing on the release of 0.94 for now. Will look at this later.

**Comment by zabulus** [comment]
@igitur 
I've debugged a little to find the difference between current develop and 0.87, found out the difference here:
XLWorksheet.CopyTo method.
0.87
```
public IXLWorksheet CopyTo(XLWorkbook workbook, String newSheetName, Int32 position)
        {
            var targetSheet = (XLWorksheet)workbook.WorksheetsInternal.Add(newSheetName, position);
            Internals.ColumnsCollection.ForEach(kp => targetSheet.Internals.ColumnsCollection.Add(kp.Key, new XLColumn(kp.Value)));
            Internals.RowsCollection.ForEach(kp => targetSheet.Internals.RowsCollection.Add(kp.Key, new XLRow(kp.Value))); // <----- Here
            Internals.CellsCollection.GetCells().ForEach(c => targetSheet.Cell(c.Address).CopyFrom(c, false));
```
0.94:
```
public IXLWorksheet CopyTo(XLWorkbook workbook, String newSheetName, Int32 position)
        {
            var targetSheet = (XLWorksheet)workbook.WorksheetsInternal.Add(newSheetName, position);
            Internals.ColumnsCollection.ForEach(kp => kp.Value.CopyTo(targetSheet.Column(kp.Key)));
            Internals.RowsCollection.ForEach(kp => kp.Value.CopyTo(targetSheet.Row(kp.Key))); // <--- Here
            Internals.CellsCollection.GetCells().ForEach(c => targetSheet.Cell(c.Address).CopyFrom(c, false, false));
````
In 0.87 version highlighted row just adds references to XLRows, copied from source worksheet.
In 0.94 version highlighted row does FULL copying of all data from source row. This includes datavalidation of cells. BTW it copies DVs somewhat odd: cell by cell. Using the example you'll finish with 51792 validation rules each for each cell.
Stack that copies all the data is following:
```
 	ClosedXML.dll!ClosedXML.Excel.XLCell.CopyDataValidation(ClosedXML.Excel.XLCell otherCell, ClosedXML.Excel.IXLDataValidation otherDv) Line 2489	C#
 	ClosedXML.dll!ClosedXML.Excel.XLCell.CopyFromInternal(ClosedXML.Excel.XLCell otherCell, bool copyDataValidations) Line 2438	C#
 	ClosedXML.dll!ClosedXML.Excel.XLCell.SetRange(object rangeObject) Line 2014	C#
 	ClosedXML.dll!ClosedXML.Excel.XLCell.Value.set(object value) Line 637	C#
 	ClosedXML.dll!ClosedXML.Excel.XLRangeBase.CopyTo(ClosedXML.Excel.IXLCell target) Line 1761	C#
 	ClosedXML.dll!ClosedXML.Excel.XLRangeBase.CopyTo(ClosedXML.Excel.IXLRangeBase target) Line 1756	C#
 	ClosedXML.dll!ClosedXML.Excel.XLRange.CopyTo(ClosedXML.Excel.IXLRangeBase target) Line 308	C#
 	ClosedXML.dll!ClosedXML.Excel.XLRow.CopyTo(ClosedXML.Excel.IXLRow row) Line 413	C#
>	ClosedXML.dll!ClosedXML.Excel.XLWorksheet.CopyTo.AnonymousMethod__1(System.Collections.Generic.KeyValuePair<int, ClosedXML.Excel.XLRow> kp) Line 608	C#
 	ClosedXML.dll!ClosedXML.Excel.EnumerableExtensions.ForEach<System.Collections.Generic.KeyValuePair<int, ClosedXML.Excel.XLRow>>(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<int, ClosedXML.Excel.XLRow>> source, System.Action<System.Collections.Generic.KeyValuePair<int, ClosedXML.Excel.XLRow>> action) Line 272	C#
 	ClosedXML.dll!ClosedXML.Excel.XLWorksheet.CopyTo(ClosedXML.Excel.XLWorkbook workbook, string newSheetName, int position) Line 608	C#
 	ClosedXML.dll!ClosedXML.Excel.XLWorksheet.CopyTo(ClosedXML.Excel.XLWorkbook workbook, string newSheetName) Line 601	C#
```

**Comment by zabulus** [comment]
As workaround, I think I could clear all validation from source worksheet, copy it to destination and reapply validations. But here I stuck with our previous optimization, that constraints source worksheet to be read-only, as parsing of template takes around 8s, and we keep it in memory.

**Comment by zabulus** [comment]
@igitur
Please take a look at PR. It fixes the issue, but I'm not sure everything is good. Tests are all green. My reproduce sample finishes fine.

**Comment by zabulus** [comment]
I've continued an investigation of the issue. I think the problem is related to method XLCell.CopyDataValidation, more precisely in method SetDataValidation. When we are copying big range, data validation is created for each cell, as I mentioned before. Nevertheless, we know that the current cell is a part of wider validation, and should not create a new one for this single cell. 

As I understand here lies a bigger problem of how to handle subranges when only part of a validation range is copied to a new place. and copying cell by cell is a fix for this problem.

**Comment by Pankraty** [comment]
@zabulus,
With #1207 your code sample finishes in 4 seconds. You may try [these binaries](https://ci.appveyor.com/project/ClosedXML/closedxml/builds/24595339/job/711jm56mij1fd5bi/artifacts) to check yourself.
