### ISSUE TITLE
Carriage return missing

### ISSUE THREAD

**Issue by MrManhoso** [ClosedXML/ClosedXML#1075]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.93.1

**What is the current behavior?**

Reading an excel file where a cell contains CRLF, for example abc\r\ndef, when i look at the text property (Value or InnerText) in debugger the value is abc\ndef. If I look at the private _richText property it seems correct, however the Text property of RichText shows the same as Value of the cell. If i add a new line to the cell, for example cell.SetValue(cell.Value + Environment.NewLine), that trailing new line is \r\n in for example cell.Value (abc\n\def\r\n).

Normally the file is created from data in DB. When i look at the cell value upon creation of the file (using ClosedXML) it is correctly shown as abc\r\n\def. Also when I open the file in Excel and look at the cell value (in for example notepad++) it is show as abc<CR><LF>def

**What is the expected behavior or new feature?**

Not sure if it is supposed to be like this or not? Dont know enough about Excel behaviour. But for me i would prefer that the cell.Value contained the full abc\r\ndef.

**Did this work in previous versions of our tool?  Which versions?**

Have only tried the latest from nuget so far (0.93.1).

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

**Code to reproduce problem:**
```c#
public void Main()
{
	var path = System.IO.Path.Combine(Environment.CurrentDirectory, "Bok1.xlsx");
	using(var book = new XLWorkbook(path)) {
		var cell = book.Worksheets.First().Cell(1, 2);
		var s = cell.GetString();
		var richText = cell.RichText;
		//cell.SetValue(cell.Value.ToString() + Environment.NewLine);
		s = cell.GetString();
	}

}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[Bok1.xlsx](https://github.com/ClosedXML/ClosedXML/files/2599934/Bok1.xlsx)

best regards
/Erik

**Comment by MrManhoso** [comment]
Sorry some incorrect variable names in the example:
		static void Main(string[] args) {
			// please place Bok1.xlsx in c:\
			var path = @"C:\Bok1.xlsx";
			using(var book = new XLWorkbook(path)) {
				var cell = book.Worksheets.First().Cell(1, 2);
				var s = cell.GetString();
				var richText = cell.RichText;
				//cell.SetValue(cell.Value.ToString() + Environment.NewLine);
				s = cell.GetString();
			}
		}

**Comment by vbjay** [comment]
Just an fyi.  Instead of forcing C:\ use https://docs.microsoft.com/en-us/dotnet/api/system.environment.currentdirectory.

**Comment by MrManhoso** [comment]
> Just an fyi. Instead of forcing C:\ use https://docs.microsoft.com/en-us/dotnet/api/system.environment.currentdirectory.

Ah, thanks. Updated the original post.

**Comment by igitur** [comment]
I think you're confusing the escape rules. Cell A1's values is:
![image](https://user-images.githubusercontent.com/145854/50146115-b62c3080-02bb-11e9-91d7-a27f98f67156.png)
which does *not* contain a new line. It contains a blackslash (`\`) and the letter `r` and another backslash and the lettern 'n'. If you're getting these values out of a database, then you have to apply your own logic to convert these to actual control characters.
