### ISSUE TITLE
File contains corrupted data.

### ISSUE THREAD

**Issue by jmawebtech** [ClosedXML/ClosedXML#1076]
Hi,

I exported a spreadsheet to excel and I get the attached error, when I try to read it. I attached my code. Do I need to make a change?

            //Open the Excel file using ClosedXML.
            using (XLWorkbook workBook = new XLWorkbook(sr))
            {
                //Read the first Sheet from Excel file.
                IXLWorksheet workSheet = workBook.Worksheet(1);
            }

I am using HSSFWorkbook, another library, to export data to Excel. How do I export a DataTable to excel using this library?

**Comment by vbjay** [comment]
Heading the documentation would be a highly recommended action.
https://github.com/ClosedXML/ClosedXML/blob/develop/README.md

**Comment by Anarios** [comment]
Since this is the first result for the error in google - I'll leave a comment for those who might encounter it - make sure you aren't trying to open an .xls (old format) file. ClosedXML  only supports .xlsx files.
