### ISSUE TITLE
How can I align an image horizontally and vertically center in a merged cell range?

### ISSUE THREAD

**Issue by jithin-shaji** [ClosedXML/ClosedXML#1095]
I have inserted an image in a cell using the following code
```
var image = MyWorkSheet.AddPicture(Server.MapPath("/images/product.png"))
                                .MoveTo(MyWorkSheet.Cell(1,1).Address)
                                .Scale(0.2);
```

Then I merged this cell with 3 cells to the right using the code

 `MyWorkSheet.Range(MyWorkSheet.Cell(1,1).Address, MyWorkSheet.Cell(1,4).Address).Merge();
`

I need to align the image in center of the merged range. How can I do that?

**Comment by igitur** [comment]
People have already responded at https://stackoverflow.com/questions/53588258/how-to-center-image-inside-a-merged-cell-range-in-closedxml
