### ISSUE TITLE
replace a range of formulas with its text value

### ISSUE THREAD

**Issue by CanYouProgram** [ClosedXML/ClosedXML#1097]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.93.1

**What is the current behavior?**

There isn't one

**What is the expected behavior or new feature?**

Be able to copy a specific range, and paste the range in the exact same place as text values.

This will let us convert all the formulas in a range to their text values so that they stay permanently.

## Reproducibility

I've tried the below.. but its not working as expected.

**Code to reproduce problem:**
```c#
detailWs.Range(companyModel.NoChargeFormulaRangeDollars).Value = detailWs.Range(companyModel.NoChargeFormulaRangePercent);

and 

detailWs.Range(companyModel.NoChargeFormulaRangeDollars).Value = detailWs.Range(companyModel.NoChargeFormulaRangePercent).ToString();
```
I have also tried this
```c#
            detailWs.Range(Regex.Replace(companyModel.NoChargeFormulaRangePercent, "Col", wedColumn)).FormulaR1C1 = $"{companyModel.NoChargeFormulaPercent}";
            var test = detailWs.Range(companyModel.NoChargeFormulaRangePercent).CellsUsed(i => i.HasFormula);
            foreach(var c in test)
            {
                c.Value = c.Value;
            }
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by Pankraty** [comment]
You can do something like this:

```
detailWs.Range(companyModel.NoChargeFormulaRangeDollars).CellsUsed().ForEach(c => ReplaceFormulaWithTextValue(c));

private void ReplaceFormulaWithTextValue(IXLCell cell)
{
  // do whatever you want
}
```

**Comment by igitur** [comment]
@CanYouProgram You didn't complete the original issue template properly. For a start, you didn't provide code that we can run ourselves. If you want us to help you, go find the original issue template, and edit your original post with ALL the required information. Read carefully of what is required.
