### ISSUE TITLE
Copying sheet doesn't bring graphs over

### ISSUE THREAD

**Issue by brettyj** [ClosedXML/ClosedXML#110]
Hi,

I'm copying a sheet using CopyTo, however it's not copying over graphs that are on that worksheet. How do I go about copying objects programmatically?

Thanks,
Brett

**Comment by igitur** [comment]
Graphs aren't supported in ClosedXML yet. It would be a major project to support them. Sorry.

**Comment by jjfeldcher** [comment]
ClosedXML does not run graphics but other third party software might (Unity)

etc

**Comment by igitur** [comment]
Graphs aren't supported yet. Sorry.
