### ISSUE TITLE
Format HTML string to be readable in Excel file

### ISSUE THREAD

**Issue by whiterabbitj** [ClosedXML/ClosedXML#1100]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.93.1.0

**What is the current behavior?**
Currently the string is displayed as is: `<ol><li>555</li><li>2222</li><li>3333</li></ol>`

**What is the expected behavior or new feature?**

HI I have an issue I am trying to populate an excel file from the data table it is populating fine however some of the datable columns have HTML elements in it in example:
`<ol><li>555</li><li>2222</li><li>3333</li></ol>`

How do I achieve a well formatted and readable string using ClosedXML in my excel file

**Did this work in previous versions of our tool?  Which versions?**

Yes/No/v0.XX

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
           SqlConnection conn = new System.Data.SqlClient.SqlConnection(connectionString);
            var cmd = new System.Data.SqlClient.SqlCommand("dbo.GetExport", conn);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            conn.Open();
            var output = new StringBuilder();
            DataTable dt = new DataTable();

            dt.Load(cmd.ExecuteReader());

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt, "MainTable");

                Response.Clear();
                Response.Buffer = true;
                Response.Charset = "US-ASCII";
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment;filename=TrainCatExport.xlsx");
                using (MemoryStream MyMemoryStream = new MemoryStream())
                {
                    wb.SaveAs(MyMemoryStream);
                    MyMemoryStream.WriteTo(Response.OutputStream);
                    Response.Flush();
                    Response.End();
                }
            }
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by vbjay** [comment]
Better. You still failed to read https://stackoverflow.com/help/mcve. We
don't have your DB. Your sample needs to be able to be copied verbatam from
the issue with the exception of altering paths to fit our system and we
should be able to press f5 in a console project and it runs.

**Comment by whiterabbitj** [comment]
Yes but the question seem quite straightforward one of the strings within the data table is formatted like this : `<ol><li>555</li><li>2222</li><li>3333</li></ol>`. Is there a straightforward approach maybe using some method to format the excel cells?

**Comment by vbjay** [comment]
What happens in Excel when you copy that and paste it into a cell and then
type it into another cell?  That should be your guide. If you can paste it,
then press Ctrl ~ to see the actual value.

**Comment by whiterabbitj** [comment]
I guess you guys don't support this feature sorry to hear it...

**Comment by vbjay** [comment]
It was an experiment to see if Excel would convert the info. I know Excel
has a paste special feature. What I wanted to know is did it convert it to
a different value. So do as I asked. Try paste and paste spwcial and then
use Ctrl ~ to look at the original value.

Excel doesn't display it the way you would expect. What you do is not use
html but character 0149 in front of each li value.

Let's say * is character 0149. Your calue in the cell would be

* Value
* Value2
* Value3

Don't use html.

**Comment by whiterabbitj** [comment]
ok thank you

**Comment by vbjay** [comment]
Wow. Excuse my phone keyboard.

**Comment by vbjay** [comment]
Apparently emails get converted into one big paragraph. 


* Value
* Value2
* Value3
