### ISSUE TITLE
StackOverflowException when empty table header.

### ISSUE THREAD

**Issue by MizardX** [ClosedXML/ClosedXML#1101]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.94.0-rc2

**What is the current behavior?**

When a table header cell is empty; Trying to access `IXLTable.Fields` or trying to save throws a `StackOverflowException`.

**What is the expected behavior or new feature?**

No exception should be thrown.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
using ClosedXML.Excel;
public void Main()
{
	var workbook = new XLWorkbook();
	var sheet = workbook.AddWorksheet("Sheet1");
	sheet.Cell(1, 1).Value = "x";
	sheet.Cell(1, 3).Value = "y";
	var table = sheet.Range(1, 1, 1, 3).CreateTable("test");
	table.Fields.ToList();
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

---

The code seems to have been written to handle this problem, but instead caused an infinite recursion loop.
* `XLTable.FieldNames` getter calls `RescanFieldNames()` when no cached value exists.
* `XLTable.RescanFieldNames()` looks for empty values, and assigns a generated header by calling `XLCell.SetValue()`
* `XLCell.SetValue()` calls `XLCell.SetTableHeaderValue()` which calls `XLTable.HeadersRow()`
* `XLTable.HeaderRow()` (with default value for `scanForNewFieldsNames`) calls property `XLTable.FieldNames`
* ... and the loop begins again.

`XLTable.Fields` is accessed when saving the workbook, so this is easy to encounter.

**Comment by igitur** [comment]
I can't reproduce this with the latest development branch.

This code:
```c#
var workbook = new XLWorkbook();
var sheet = workbook.AddWorksheet("Sheet1");
sheet.Cell(1, 1).Value = "x";
sheet.Cell(1, 3).Value = "y";
var range = sheet.Range(1, 1, 1, 3);
var table = range.CreateTable("test");
var fields = table.Fields.ToList();

foreach (var f in fields)
{
    Console.WriteLine(f.Name);
}
```

gives me:
```
x
Column2
y
```

**Comment by MizardX** [comment]
I am unable to recreate the bug now, neither with 0.93.1 nor 0.94.x. I'll close the bug for now.
