### ISSUE TITLE
Reading a stream, to get header information

### ISSUE THREAD

**Issue by papyr** [ClosedXML/ClosedXML#1105]
Hi, I dont have poco objects, a user is uploading a files as stream, and I am **trying to get the header or Column names**. Can you please help I saw your doc/help, but could not find help on this.

All I need is the _names of the columns_ headers (and _their types_ if possible), can you please show me how to get it from a file stream with out a POCO or class.?

```
var parser = new CsvParser( textReader );
while( true )
{
    list<string> columnNames = parser.Read().GetHeadersList???
}
```

thanks

**Comment by igitur** [comment]
Wrong project. This is ClosedXML, not CSVHelper
