### ISSUE TITLE
The value of a merged range is determined incorrectly

### ISSUE THREAD

**Issue by traf72** [ClosedXML/ClosedXML#1106]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.94.0

**What is the current behavior?**

If I have a merged range, the value of the first cell is determined correctly, but the value of other cells is 
an empty string.

**What is the expected behavior or new feature?**

The value of all merged cells must be the same.

**Did this work in previous versions of our tool?  Which versions?**

Yes/v0.93.1

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
        var wb = new XLWorkbook();
        var ws = wb.AddWorksheet("Sheet");
        ws.Cell(1, 1).Value = "Test";
        ws.Cell(1, 2).Value = "Test";

        var valueOfCell1 = ws.Cell(1, 1).Value; // "Test" (correct)
        var valueOfCell2 = ws.Cell(1, 2).Value; // "Test" (correct)

        ws.Range(1, 1, 1, 2).Merge();

        valueOfCell1 = ws.Cell(1, 1).Value; // "Test" (correct)
        valueOfCell2 = ws.Cell(1, 2).Value; // "" (incorrect)
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by traf72** [comment]
This is also actual for determining styles (e.g. borders) of a merged range.

**Comment by Pankraty** [comment]
```
ws.Cell(1, 1).Value = "Test";
ws.Cell(1, 2).Value = "Test";
```
If you'd set different values here you'd notice that in versions prior to 0.94 they remained unchanged. I consider this as a wrong behavior and fixed it in 0.94.
Try this in Excel. When you merge cells their values and styles are lost. If you unmerge cells their values are not the same as they were before merging. 
![default](https://user-images.githubusercontent.com/19576939/50054125-549f8100-0158-11e9-8526-472f663e11fb.png)
![default](https://user-images.githubusercontent.com/19576939/50054130-63863380-0158-11e9-8b7e-55433b430034.png)
![default](https://user-images.githubusercontent.com/19576939/50054134-73057c80-0158-11e9-9255-9d4cd693a8d1.png)
Starting from 0.94 ClosedXML behaves similarly.

**Comment by Pankraty** [comment]
We could, of course, return the value of the first cell in a merged range when any of the merged cells are examined, but this would be wrong too. First, it would differ from what Excel does, second, formulas like `=SUM(A1:B2)` would produce an incorrect result when merged ranges are involved (it just occurred to me, this had to be reported as a bug years ago...)

**Comment by vbjay** [comment]
Then we need a mergedRange property on a cell  or a GetMergedRange(...)
function in a worksheet that is the range equal to the merged range of a
cell if in a merged range.  Null if not in a merged range.

**Comment by igitur** [comment]
@vbjay There are already a `IXLCell.IsMerged()` and `IXLCell.MergedRange()` methods.
