### ISSUE TITLE
System.Drawing is not supported on this platform.

### ISSUE THREAD

**Issue by nefcanto** [ClosedXML/ClosedXML#1107]
- [x] Bug

**Version of ClosedXML**

e.g. 0.94.0

**What is the current behavior?**

I can't create Excel file in my real project. The same code that works in a Console app or a simple Web App doesn't work in my app. This is the log:

```

System.Drawing is not supported on this platform.

   at ClosedXML.Excel.FontBaseExtensions.GetCachedFont(IXLFontBase fontBase, Dictionary`2 fontCache)
   at ClosedXML.Excel.FontBaseExtensions.GetWidth(IXLFontBase fontBase, String text, Dictionary`2 fontCache)
   at ClosedXML.Excel.XLColumn.AdjustToContents(Int32 startRow, Int32 endRow, Double minWidth, Double maxWidth)
   at ClosedXML.Excel.XLColumns.<>c__DisplayClass10_0.<AdjustToContents>b__0(XLColumn c)
   at ClosedXML.Excel.XLColumns.AdjustToContents(Int32 startRow, Int32 endRow)
   at ClosedXML.Excel.XLWorksheets.Add(DataTable dataTable, String sheetName)
```

**What is the expected behavior or new feature?**

It should work, or it should give me more data on what the underlying problem is:

**Did this work in previous versions of our tool?  Which versions?**

Yes but I don't have access to old code and don't remember the previous version.

## Reproducibility

**Code to reproduce problem:**
```c#
public class ExcelController : Controller
    {
        [HttpGet]
        public IActionResult Test()
        {
            var table = new DataTable();
            table.Columns.Add("Name", typeof(string));
            table.Columns.Add("Age", typeof(int));
            var row = table.NewRow();
            row["Name"] = "First Name";
            row["Age"] = 10;
            table.Rows.Add(row);
            var workbook = new XLWorkbook();
            workbook.Worksheets.Add(table, "Export");
            var result = new MemoryStream();
            workbook.SaveAs(result);
            result.Position = 0;
            var bytes = result.ToArray();
            var fileName = "Export.xlsx";
            return File(new MemoryStream(bytes), "application/octet-stream", fileName);
        }
    }
```

This code works just find in an isolated newly created Web App. But it throws that error in my real microservices, and I can't find out why.

**Comment by igitur** [comment]
So, according to the error message, you have to ensure that `System.Drawing` is supported on your platform. What platform are you using?

**Comment by igitur** [comment]
And what is the exact type of Exception that is thrown?

@Pankraty Maybe should catch that exception and swallow it?

**Comment by nefcanto** [comment]
My platform is this:

Windows 10 Enterprise 64bit
Visual Studio 2017 Community Edition 15.8.6
.NET Core 2.1.5 (both SDK and runtime)
Hosted in IIS 10.0.17134.1
C#

**Comment by nefcanto** [comment]
System.PlatformNotSupportedException

The point is, this code works outside my project. I mean, if I copy/paste that simple code in a Console application created from Template, it works, on the exactly same platform. That's why it's weird.

**Comment by igitur** [comment]
It is weird. But without a reproducible test case I can't help you. And you're not a first time poster, so you should know the drill by now. We don't throw that exception. So it really does look like there is a difference in platforms between your dev and production machines. And that is for you to debug.

**Comment by nefcanto** [comment]
@igitur my dev and production machine IS ONE MACHINE. I know that you're not throwing that exception. But how can we find out about the underlying problem? Method `GetCachedFont` is the place where this exception is raised. Maybe we need to catch the exception and find out what causes that error. If it's from a third party code, then why not adding the stack trace of that library too?

Since my real project is much more complex and I can't share it, perhaps you can guide me on how to debug ClosedXML on my machine and see its code line by line.

**Comment by igitur** [comment]
So clone the project and reference it directly instead of the nuget package. https://help.github.com/articles/cloning-a-repository/

**Comment by ThomsCass** [comment]
As far as I know `system.drawing` is not support in .Net Core ?

**Comment by igitur** [comment]
The netstandard20 build of ClosedXML references https://www.nuget.org/packages/System.Drawing.Common. And all our tests pass for the netstandard20 build. So I have no idea what's causing this and without a reproducible test case I can't help.
