### ISSUE TITLE
There is a phenomenon that the setting of Border does not apply.

### ISSUE THREAD

**Issue by stein2nd** [ClosedXML/ClosedXML#111]
VB.NET 2013, ClosedXML 0.80.0.0, OpenXML 2.5.5631.0.

While processing the DataTable in the For Each loop, there is a phenomenon that the Border setting is not always applied only in the case of the second DataRow from the beginning.

It occurs only in the first sheet of the book. From the second onward, the Border setting is applied normally.

**Comment by igitur** [comment]
Please post your code so that I can try to reproduce the problem.
