### ISSUE TITLE
Border Style changes without changing

### ISSUE THREAD

**Issue by benjamin275** [ClosedXML/ClosedXML#1111]
[border Problem.zip](https://github.com/ClosedXML/ClosedXML/files/2700579/border.Problem.zip)
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

latest

**What is the current behavior?**

the border changes after these commands:

ws1.Cell(21, 1).Value = "a string..."
ws1.Cell(25, 2).Value = "a string..."
ws1.Cell(26, 2).Value = "a string..."
ws1.Cell(31, 1).Value = beschreibung;

**What is the expected behavior or new feature?**

just changes the values of these 4 cells, but not the border

**Comment by Pankraty** [comment]
Ah, sorry, I missed the archive at the top.

**Comment by benjamin275** [comment]
i just found out, than in 0.93.0 it is working correctly but not with version 0.94.2
