### ISSUE TITLE
Chart do not change location on row insert

### ISSUE THREAD

**Issue by hayhaylonton** [ClosedXML/ClosedXML#1118]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

When I use function InsertRowsBelow to insert row any chart below in worksheet not move. So row cover by chart.

**Version of ClosedXML**

0.94.2.0

**What is the current behavior?**

I write in C# library

**What is the expected behavior or new feature?**

when insert row chart in row move follow.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
private static void FillWorksheetData(string filename, string templatefilename, DataSet data, DataTable dtvarios, string[] deminator)
        {
            if (File.Exists(filename))
                File.Delete(filename);
            
            using (var excelfile = new XLWorkbook(templatefilename))
            {
                foreach (DataTable dt in data.Tables)
                {
                    try
                    {
                        foreach (var ws in excelfile.Worksheets)
                        {
                            var address = findAddress(string.Format("{0}{1}{2}", deminator[0], dt.TableName, deminator[1]), ws);
                            if (address != null)
                            {
                                //insert emty row before insert datatable 
                                ws.Row(address.RowNumber).InsertRowsBelow(dt.Rows.Count - 1);
                                ws.Cell(address).InsertData(dt);
                            }
                            
                        }
                        foreach (DataRow row in dtvarios.Rows)
                        {
                            foreach (DataColumn col in dtvarios.Columns)
                            {
                                var findtext = "{" + col.ColumnName + "}";
                                Replace(findtext, row[col].ToString(), excelfile);
                            }
                        }
                    }
                    catch { }
                }
                excelfile.SaveAs(filename);
            }
        }
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[baocaotheonguoixuly.xlsm.zip](https://github.com/ClosedXML/ClosedXML/files/2747969/baocaotheonguoixuly.xlsm.zip)

**Comment by igitur** [comment]
Complete the template

**Comment by hayhaylonton** [comment]
Can I find and move chart in worksheet. I think can fix if has this future

**Comment by igitur** [comment]
Code sample too complicated. Post a MCVE. See https://stackoverflow.com/help/mcve

**Comment by hayhaylonton** [comment]
I Update code 
```c#
ws.Row(address.RowNumber).InsertRowsBelow(dt.Rows.Count - 1);
```
this can insert row affter insert row chart below not move

**Comment by igitur** [comment]
>  I attached a sample spreadsheet. (You can drag files on to this issue)

**Comment by hayhaylonton** [comment]
are you check this issues

**Comment by igitur** [comment]
Not yet, sorry.

**Comment by igitur** [comment]
I still can't run your code sample. I don't have `findAddress`, `Replace` and the necessary data to populate the parameters in `FillWorksheetData`. I'm closing this for now. I'll reopen when I have a runnable code sample.
