### ISSUE TITLE
After the first 4 sheets, Border is assigned only to specific cells

### ISSUE THREAD

**Issue by stein2nd** [ClosedXML/ClosedXML#112]
VB.NET 2013, ClosedXML 0.80.0.0, OpenXML 2.5.5631.0.

From the first 4 sheets, only the cell N12 (Row: 12, Column: 14), Border is given phenomenon occurs.

**Comment by igitur** [comment]
Sorry, I don't understand the problem. Please explain clearly and give a code sample, if possible.
