### ISSUE TITLE
File corrupts when adding sheet in workbook sheet has pivot table in it

### ISSUE THREAD

**Issue by Umeshpatil0012** [ClosedXML/ClosedXML#1120]
[Test.xlsx](https://github.com/ClosedXML/ClosedXML/files/2726780/Test.xlsx)

I have one excel file that contains pivot table, i need to add 1 sheet in that file. For that i have created following code.
When I open the file generated i get a error message that says "We found a problem with some content in 'Test.xlsx' Do you want us to try and recover as much as we can? If you trust the source of this workbook, click yes." and it will remove pivot table.
It works fine in ClosedXml 0.75 version but it gives error in ClosedXml 0.94.2.0 version 

```
private void Generate_Sheet1()
        {
var _xlWorkBook = new ClosedXML.Excel.XLWorkbook(filePath);
  var worksheets = _xlWorkBook.Worksheets;
_xlWorkBook.AddWorksheet("Test", 1);
}
```

**Comment by igitur** [comment]
Since v0.75 partial support for pivot tables has been added. Currently pivot *charts* are not supported at all, and this leads to a corrupt file. My suggestion is to stay on v0.75 or replace your pivot chart with a traditional chart.
