### ISSUE TITLE
Evaluating Formulas "TRUNC" need to 2 arguments

### ISSUE THREAD

**Issue by jwjirakit** [ClosedXML/ClosedXML#1123]
I need to formula "TRUNC" to 2 arguments for remove decimal without rounding
ex. 
TRUNC(2.64799257, 4) = 2.6479
TRUNC(2.64799257, 3) = 2.647
TRUNC(2.64799257, 2) = 2.64

Thank you.

**Comment by igitur** [comment]
This is fixed in #1130. But please, next time you log an issue, complete the full issue template. You were lucky... usually I close issues immediately when people blatantly ignore the issue template.
