### ISSUE TITLE
Closed Xml not open excel file in server

### ISSUE THREAD

**Issue by Umeshpatil0012** [ClosedXML/ClosedXML#1127]
**Do you want to request a *feature* or report a *bug*?**
- Bug

**Version of ClosedXML**
 0.94.0.0

**What is the current behavior?**
I have opened excel file using ClosedXml in C#. It works good on local, but on the **Server** it throws a **File Format exception**. When I open the excel file in Open XML SDK productivity Tool 2.5, it shows that ExtendedFilePropertiesPart is missing. 

**Did this work in previous versions of our tool?  Which versions?**
No

**What is the expected behavior or new feature?**
Open excel file on Server also without throwing any exception at the time of opening file in ClosedXml.

## Reproducibility
Create console application for opening attached excel file with below code and ClosedXml 0.94.0.0. Upload project exe on server it will throws exception.

[148159_out1s5bc.xlsx](https://github.com/ClosedXML/ClosedXML/files/2740246/148159_out1s5bc.xlsx)

**Code to reproduce problem:**

```
public static ClosedXML.Excel.XLWorkbook OpenClosedXMLWorkBook(string FilePath) //int[] Scores, int Student_id)
        {
            string strErrorMsg = "OpenClosedXMLWorkBook()";
            Stream fileStream = null;
            try
            {
                fileStream = new MemoryStream(File.ReadAllBytes(FilePath));
                var _xlWorkBook = new ClosedXML.Excel.XLWorkbook(fileStream);
                return _xlWorkBook;
            }
            catch (Exception ex)
            {
                strErrorMsg += ":Exception=" + ex.ToString();
                Console.WriteLine(strErrorMsg);
                return null;

            }
            catch (FileFormatException ex1)
            {
                Console.WriteLine(ex1);
                return null;
            }
        }

```

**Comment by igitur** [comment]
Please complete the full issue template. I don't know why you're deleting sections from the provided issue template.

**Comment by Umeshpatil0012** [comment]
I have edited the question with proper template please check.

**Comment by thanhtamns** [comment]
Have you solved this problem yet? How did you do it?
