### ISSUE TITLE
Closed Xml not open excel file in server 

### ISSUE THREAD

**Issue by Umeshpatil0012** [ClosedXML/ClosedXML#1128]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**
0.94.0.0

**What is the current behavior?**
I have opened excel file using ClosedXml in C#. It works good on local, but on the Server it throws a exception. When I open the excel file in Open XML SDK productivity Tool 2.5, it shows that ExtendedFilePropertiesPart is missing.

**What is the expected behavior or new feature?**
Open excel file on Server also without throwing any exception at the time of opening file in ClosedXml.

**Did this work in previous versions of our tool?  Which versions?**
No

## Reproducibility
Create console application for opening attached excel file with below code and ClosedXml 0.94.0.0. Upload project exe on server it will throws exception.

**Code to reproduce problem:**
```c#
public static ClosedXML.Excel.XLWorkbook OpenClosedXMLWorkBook(string FilePath) 
        {
            string strErrorMsg = "OpenClosedXMLWorkBook()";
            Stream fileStream = null;
            try
            {
                fileStream = new MemoryStream(File.ReadAllBytes(FilePath));
                var _xlWorkBook = new ClosedXML.Excel.XLWorkbook(fileStream);
                return _xlWorkBook;
            }
            catch (Exception ex)
            {
                strErrorMsg += ":Exception=" + ex.ToString();
                Console.WriteLine(strErrorMsg);
                return null;

            }            
        }
```
- [x] I attached a sample spreadsheet.  
[148159_iHEEH5bc.xlsx](https://github.com/ClosedXML/ClosedXML/files/2744013/148159_iHEEH5bc.xlsx)

**Comment by igitur** [comment]
I can't replicate the issue. Please post the full stack trace of the exception.

**Comment by igitur** [comment]
And also try with 0.94.2

**Comment by Umeshpatil0012** [comment]
I have upload the file on server and execute above code exe on server it throws exception.

**Comment by igitur** [comment]
Stack trace please
