### ISSUE TITLE
Getting format exception and not getting proper value of a cell which shows properly on excel

### ISSUE THREAD

**Issue by yon86** [ClosedXML/ClosedXML#113]
I am getting a ```'((ClosedXML.Excel.XLCell)timeCell).Value' threw an exception of type 'System.FormatException'``` when trying to access the value of a cell which contains a date with a custom format of  ``` [$-en-US]dddd, mm/dd ``` .

Appreciate all the help.

**Comment by igitur** [comment]
ClosedXML won't be able to evaluate a custom format like that. I suggest changing the format to something more standard before trying to retrieve the value.

**Comment by yon86** [comment]
thanks for the reply I changed the format to a standard date format and still throwing the same error....is there another lib you suggest for this kind of issues. thank you

**Comment by igitur** [comment]
If you can attach your spreadsheet, I can have a look at the problem.

**Comment by yon86** [comment]
[Book1.xlsx](https://github.com/ClosedXML/ClosedXML/files/616268/Book1.xlsx)
 Can you format the cell with Monday, 11/21 text. Thank you.

**Comment by igitur** [comment]
Using the latest code from the `develop` branch, I can successfully retrieve the date value using this code:

```c#
private static void Main(string[] args)
{
    using (var wb = new XLWorkbook("test.xlsx"))
    {
        var ws = wb.Worksheets.First();
        var cell = ws.Cell("B11");
        cell.Style.NumberFormat.SetFormat("yyyy-MM-dd");
        cell.DataType = XLCellValues.DateTime;
        Console.WriteLine(cell.Value);
    }

    Console.WriteLine("Press any key to continue");
    Console.ReadKey();
}
```

**Comment by yon86** [comment]
ok Thank you I will clone and test.
