### ISSUE TITLE
XLWorkbook.LoadCells constructs XLAddress mixing row and cell number

### ISSUE THREAD

**Issue by lahma** [ClosedXML/ClosedXML#1131]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

`XLWorkbook.LoadCells` mixes rows and columns when constructing `XLAddress`

**What is the expected behavior or new feature?**

`XLAddress` instance should have cell and row address the right way around.

**Did this work in previous versions of our tool?  Which versions?**

Yes, I am upgrading from from 0.88 where this worked as expected.

## Reproducibility

I have a file that I cannot share which surfaces this problem. When I try to clean the file and re-save MS Excel seems to produce format that has `cell.CellReference` in place or something similar which causes this wrong constructor call to be skipped. I hope the current source code references in GH repo demonstrate the problem well enough.

See line 1409: https://github.com/ClosedXML/ClosedXML/blob/303b15a20aa6033b9d9c0631edda174fb08f84c2/ClosedXML/Excel/XLWorkbook_Load.cs#L1408-L1410

The constructor signature is:

https://github.com/ClosedXML/ClosedXML/blob/c9fcc6b196eeaafe17ac79a39e40ff80b8264bff/ClosedXML/Excel/Coordinates/XLAddress.cs#L138

Example console-based sample:

```
public class Program
{
    private static void Main()
    {
        var method = typeof(XLWorkbook).GetMethod("LoadCells", BindingFlags.NonPublic | BindingFlags.Instance);
        var workbook = new XLWorkbook();
        var sheet = workbook.AddWorksheet("sheetname");

        // first cell in row 6
        int rowIndex = 6;
        var cell = new Cell
        {
            DataType = CellValues.String,
            CellValue = new CellValue("text")
        };

        method.Invoke(workbook, new object[]
        {
            Array.Empty<SharedStringItem>(),
            new Stylesheet(),
            new NumberingFormats(),
            new Fills(),
            new Borders(),
            new Fonts(),
            new Dictionary<uint, string> {{ 0, "" }},
            sheet,
            new Dictionary<Int32, IXLStyle> {{ 0, null }},
            cell,
            rowIndex
        });

        Console.WriteLine("CELL A6: " + sheet.Cell(6, 1).GetString());
        Console.WriteLine("CELL F1: " + sheet.Cell(1, 6).GetString());
    }
}
```

**Comment by igitur** [comment]
Please add a console-based code sample to illustrate the issue, as requested.

**Comment by lahma** [comment]
I've updated the description to include minimal repro which shows how row 6, cell 1 is handled, A6 is actually stored to F1.

**Comment by igitur** [comment]
Do you have a real-world example which fails (i.e. not using reflection to gain access to private methods)? It does seem like you've discovered, but I'm concerned that none of our current tests fail. Which is why I'm looking for a real-world use case that fails.

**Comment by lahma** [comment]
Like I said, the original file triggers the issue, but if I try to clean the sensitive data and save, the data changes in file losing the triggering behavior. The original file was generated by customer system which I don't have access to.

**Comment by igitur** [comment]
Oh, I missed that part. Is there no way to get hold of that file?

**Comment by Pankraty** [comment]
@igitur if you have a spare minute try this file from our suit: Misc.LO.xlsx.row-index-1-based.xlsx.
I suspect the issue can be reproduced with it.

**Comment by igitur** [comment]
@Pankraty Thanks, that's just what I needed.
