### ISSUE TITLE
Numeric values not displayed default android app

### ISSUE THREAD

**Issue by MSAppsDev** [ClosedXML/ClosedXML#1141]
- [x] Bug

Hi, I am using ClosedXML library to build excel files in my API and render then in UI. When i open the excel file returned by my API in default Android app(Hancom Office Editor), its not displaying numeric values in the file. 

**Version of ClosedXML**

0.93.1

**What is the current behavior?**

I dont see numbers in the file, it lists them when i open in Excel application.

**What is the expected behavior or new feature?**

File should display all the content irrespective of the app used to view it.

**Did this work in previous versions of our tool?  Which versions?**

N/A. I never used previous versions of Closed XML.

## Reproducibility
Open the excel file created thru ClosedXML library in default Android app, it does not lists numeric values. It lists the same if the excel file created by some other library or created manually. 

**Code to reproduce problem:**
```c#
code to generate simple excel file having some numeric fileds using ClosedXML library.
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[WeeklyTimesheets.xlsx](https://github.com/ClosedXML/ClosedXML/files/2817749/WeeklyTimesheets.xlsx)

**Comment by igitur** [comment]
Code sample please.

**Comment by MSAppsDev** [comment]
you can open the attached excel file in default app in android phone to see the issue. But if you are looking on code to generate the attached excel, below is the api code to generate it. Please note that below code is aspnet core 2.1 

1) Below is my controller "ReportControoler.cs".

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Angular_netcore.BusinessLayer;
using System.Net;

namespace Angular_netcore.Controllers
{
    [Route("api/report")]
    public class ReportController : Controller
    {
        private IReportService reportService;

        /// <summary>
        /// Constructor of the UserController, assigns userService and logger service local objects.
        /// </summary>
        /// <param name="reportService">report service business object</param>
        public ReportController(IReportService reportService)
        {
            this.reportService = reportService;
        }

        /// <summary>
        /// this method returns the requested report
        /// </summary>
        /// <returns>Report</returns>
        [Route("generateReport")]
        [HttpPost]
        public async Task<IActionResult> GenerateReport()
        {
            try
            {
                byte[] report = reportService.GenerateReport();
                var response = File(report, "application/vnd.ms-excel", "Employee Timesheets.xlsx");
                return response;

            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, ex);
            }
        }
    }
}


2) Below is the code for "Angular_netcore.BusinessLayer.ReportService.cs"
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ClosedXML.Excel;

namespace Angular_netcore.BusinessLayer
{
    public class ReportService:IReportService
    {
        /// <summary>
        /// this method build the weekly timesheets report.
        /// </summary>
        /// <returns>weekly timesheets report</returns>
        public byte[] GenerateReport()
        {
            byte[] data;
            string reportTitle = "Employee Weekly Timesheets";
            using (var workbook = new XLWorkbook(XLEventTracking.Disabled))
            {
                int firstRow = 1;
                //set first column of the excel sheet
                string firstColChar = "A";
                //set last column of the excel sheet
                string lastColChar = "L";
                var worksheet = workbook.Worksheets.Add(reportTitle);

                //define Title and set the style from A1:L2 
                var rngTitle = worksheet.Range(firstColChar + firstRow.ToString() + ":" + lastColChar + (firstRow + 1).ToString());
                rngTitle.Merge();
                rngTitle.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                rngTitle.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
                rngTitle.Style.Font.Bold = true;
                rngTitle.Style.Font.FontSize = 14;
                rngTitle.Style.Fill.BackgroundColor = XLColor.FromHtml("#A5D6A7");
                rngTitle.Value = reportTitle;

                //Filter Column Headers and filter Values

                //Department
                int filterStartRow = firstRow + 3;
                worksheet.Cell(filterStartRow, 1).Value = "Department:";

                worksheet.Cell(filterStartRow, 2).Value = "All";

                //Category filters
                int filterEndRow = filterStartRow + 1;
                worksheet.Cell(filterEndRow, 1).Value = "Category:";
                worksheet.Cell(filterEndRow, 2).Value = "All";

                //Employee filters
                filterEndRow = filterEndRow + 1;
                worksheet.Cell(filterEndRow, 1).Value = "Employee:";
                
                worksheet.Cell(filterEndRow, 2).Value = "All";
                //date range filter
                filterEndRow = filterEndRow + 1;
                worksheet.Cell(filterEndRow, 1).Value = "Week:";
                worksheet.Cell(filterEndRow, 2).Value = $"12/29/2018 - 01/04/2019";

                //set the style for Filter Column headers A4:A7
                var rngFilterHeaders = worksheet.Range(firstColChar + filterStartRow.ToString() + ":" + firstColChar + filterEndRow.ToString());   //A4:A7
                rngFilterHeaders.Style.Font.Bold = true;

                //define data table column headers range A8:L8 and set the style
                int colHeadersRow = filterEndRow + 2;
                int firstColNum = 1;

                worksheet.Cell(colHeadersRow, firstColNum).Value = "Department";
                worksheet.Cell(colHeadersRow, firstColNum + 1).Value = "Category";
                worksheet.Cell(colHeadersRow, firstColNum + 2).Value = "ID";
                worksheet.Cell(colHeadersRow, firstColNum + 3).Value = "Name";
                worksheet.Cell(colHeadersRow, firstColNum + 4).Value = "Week Ending";
                worksheet.Cell(colHeadersRow, firstColNum + 5).Value = "Date";
                worksheet.Cell(colHeadersRow, firstColNum + 6).Value = "WeekDay";
                worksheet.Cell(colHeadersRow, firstColNum + 7).Value = "Time-In";
                worksheet.Cell(colHeadersRow, firstColNum + 8).Value = "TimeZone (Time-In)";
                worksheet.Cell(colHeadersRow, firstColNum + 9).Value = "Time-Out";
                worksheet.Cell(colHeadersRow, firstColNum + 10).Value = "TimeZone (Time-Out)";
                worksheet.Cell(colHeadersRow, firstColNum + 11).Value = "Total Hours";

                var rngColHeader = worksheet.Range(firstColChar + colHeadersRow.ToString() + ":" + lastColChar + colHeadersRow.ToString());
                rngColHeader.Style.Font.Bold = true;
                rngColHeader.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                rngColHeader.Style.Fill.BackgroundColor = XLColor.FromHtml("#9FA8DA");
                rngColHeader.Style.Border.RightBorder = XLBorderStyleValues.Thin;
                rngColHeader.Style.Border.BottomBorder = XLBorderStyleValues.Thin;

                //start data row,insert data
                int dataRow = colHeadersRow + 1;
                
                worksheet.Cell(dataRow, firstColNum).Value = "ABC";
                worksheet.Cell(dataRow, firstColNum + 1).Value = "Test";
                            
                worksheet.Cell(dataRow, firstColNum + 2).Value = "12363";
                worksheet.Cell(dataRow, firstColNum + 3).Value = "Test User";
                worksheet.Cell(dataRow, firstColNum + 4).Value = "01/04/2019";
                worksheet.Cell(dataRow, firstColNum + 5).Value = "12/31/2019";
                worksheet.Cell(dataRow, firstColNum + 6).Value = "Monday";
                //each day entries
                                        
                worksheet.Cell(dataRow, firstColNum + 7).Value = "08:00";
                worksheet.Cell(dataRow, firstColNum + 8).Value = "EST";
                worksheet.Cell(dataRow, firstColNum + 9).Value = "12:00";
                worksheet.Cell(dataRow, firstColNum + 10).Value = "EST";
                worksheet.Cell(dataRow, firstColNum + 11).Value = "4:00";
                dataRow++;
                                        
                                       
                //add weekly total for each week
                worksheet.Cell(dataRow, firstColNum + 4).Value = "Weekly Total";
                worksheet.Cell(dataRow, firstColNum + 4).Style.Font.Bold = true;
                worksheet.Cell(dataRow, firstColNum + 11).Value = "4:00";
                worksheet.Cell(dataRow, firstColNum + 11).Style.Font.Bold = true;
                worksheet.Range(firstColChar + dataRow.ToString() + ":" + lastColChar + dataRow.ToString()).Style.Fill.BackgroundColor = XLColor.FromHtml("#E6EE9C");
                                    
                var rngDivision = worksheet.Range(firstColChar + dataRow.ToString() + ":" + lastColChar + (dataRow - 1).ToString());
                rngDivision.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;

               
                //set the formatting for Date, time columns
                worksheet.Columns("E:F").Style.DateFormat.Format = "MM/dd/yyyy";
                worksheet.Columns("G").Style.DateFormat.Format = "dddd";
                worksheet.Columns("H").Style.DateFormat.Format = "HH:mm";
                worksheet.Columns("J").Style.DateFormat.Format = "HH:mm";
                worksheet.Columns("F:G").Style.Font.Bold = true;
                worksheet.Columns("L").Style.NumberFormat.Format = "#0.00";
                //setting width of each column
                worksheet.Columns("A").Width = 12;
                worksheet.Columns("B").Width = 18;
                worksheet.Columns("C").Width = 12;
                worksheet.Columns("D").Width = 20;
                worksheet.Columns("E").Width = 12;
                worksheet.Columns("F").Width = 12;
                worksheet.Columns("G").Width = 12;
                worksheet.Columns("H").Width = 8;
                worksheet.Columns("I").Width = 10;
                worksheet.Columns("J").Width = 8;
                worksheet.Columns("K").Width = 11;
                worksheet.Columns("L").Width = 12;

                //align all rows except header horizontally left and vertically top and wrap text to true
                // here avoid setting verticle alignment to middle as the columns not wrapped to nex appears in the middle but the wrapped columns appears top
                var rngReport = worksheet.Range(firstColChar + (firstRow + 2).ToString() + ":" + lastColChar + (dataRow + 1).ToString());

                rngReport.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
                rngReport.Style.Alignment.Vertical = XLAlignmentVerticalValues.Top;
                worksheet.Columns(firstColChar + ":" + lastColChar).Style.Alignment.WrapText = true;
               
                //set excel sheet properties for printing 
                worksheet.PageSetup.PageOrientation = XLPageOrientation.Landscape;
                worksheet.PageSetup.PaperSize = XLPaperSize.LegalPaper;
                worksheet.PageSetup.Margins.Top = 0.5;
                worksheet.PageSetup.Margins.Left = 0.5;
                worksheet.PageSetup.Margins.Header = 0.5;
                worksheet.PageSetup.Margins.Right = 0.5;
                worksheet.PageSetup.Margins.Bottom = 0.5;
                worksheet.PageSetup.Margins.Footer = 0.5;
                worksheet.PageSetup.CenterHorizontally = true;
                worksheet.PageSetup.CenterVertically = true;
                worksheet.PageSetup.AlignHFWithMargins = true;
                worksheet.PageSetup.Footer.Center.AddText(XLHFPredefinedText.PageNumber, XLHFOccurrence.AllPages);
                worksheet.PageSetup.Footer.Center.AddText(" / ", XLHFOccurrence.AllPages);
                worksheet.PageSetup.Footer.Center.AddText(XLHFPredefinedText.NumberOfPages, XLHFOccurrence.AllPages);
                worksheet.PageSetup.Footer.Right.AddText(XLHFPredefinedText.Date);
                worksheet.PageSetup.Footer.Right.AddText(" ");
                worksheet.PageSetup.Footer.Right.AddText(XLHFPredefinedText.Time);

                //writting the report workbook to stream to trasmit to client
                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    data = stream.ToArray();
                };
                
            }
            return data;
        }
    }
}

3) Below is the Interface code "Angular_netcore.BusinessLayer.IReportService.cs"
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
namespace Angular_netcore.BusinessLayer
{
    public interface IReportService
    {
        byte[] GenerateReport();
    }
}

**Comment by igitur** [comment]
Here are the guideluines for a good code sample: https://stackoverflow.com/help/mcve

**Comment by igitur** [comment]
Also give me the link in the Google Play store for the app you're using to view the file.

**Comment by MSAppsDev** [comment]
Hi, Thanks for looking into this. This is the app by default comes with android devices especially Samsung to work with documents.
https://play.google.com/store/apps/developer?id=Hancom+Inc.&hl=en_US

please open the excel file that i attached  or any excel having numeric values created using ClosedXML library in this app to see the issue.

**Comment by igitur** [comment]
> Also give me the link in the Google Play store for the app you're using to view the file.

Link to the *APP*, not the developer.
