### ISSUE TITLE
How to make Excel treat all cells as text and avoid any automatic conversions

### ISSUE THREAD

**Issue by sdg002** [ClosedXML/ClosedXML#1142]
![issue](https://user-images.githubusercontent.com/20245330/52361898-3a3aa300-2a37-11e9-8b65-38faaf4749c7.png)
[Sample.XLSX](https://github.com/ClosedXML/ClosedXML/files/2837602/Sample.XLSX)

## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.94.2.0

**What is the current behavior?**

When writing to Excel using XLDataType.Text format,  
1)Excel is stripping the "+" sign from "+100.123"
2)Excel is converting a string like "10/01/2019"  to 43475
3)Excel is displaying a warning drop down icon on each of the cells 

**What is the expected behavior or new feature?**

I would like Excel to retain the original string as it is.
"+100.123" from C# should be seen as "+100.123" in Excel
"10/01/2019" from C# should be seen as  "10/01/2019"
No data conversion warning icons should appear in Excel.

Please note that in my scenario, I have no prior knowledge of the underlying data type. I have to treat all cells as plain text and hence using XLDataType.Text.

**Did this work in previous versions of our tool?  Which versions?**

Not sure. This is the first time I am trying out.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
        [TestMethod]
        public void DataTypesIssue()
        {
            string filename = DateTime.Now.ToString("ddd-HH-mm-ss") + ".XLSX";
            string file = System.IO.Path.Combine(Util.GetTempDir(), filename);
            using (var workbook = new XLWorkbook())
            {
                {
                    var worksheet = workbook.Worksheets.Add("Sample Sheet With data types");
                    worksheet.Cell("A1").Value = "Positive Number with plus sign";
                    worksheet.Cell("B1").Value = $"+100.123";
                    worksheet.Cell("B1").DataType = XLDataType.Text;

                    worksheet.Cell("A2").Value = "Positive Number without plus sign";
                    worksheet.Cell("B2").Value = $"100.123";
                    worksheet.Cell("B2").DataType = XLDataType.Text;

                    worksheet.Cell("A3").Value = "Negative Number";
                    worksheet.Cell("B3").Value = $"-100.123";
                    worksheet.Cell("B3").DataType = XLDataType.Text;
                    worksheet.ExpandColumns();
                    worksheet.ExpandRows();

                    worksheet.Cell("A4").Value = "Date example";
                    worksheet.Cell("B4").Value = $"10/01/2019";
                    worksheet.Cell("B4").DataType = XLDataType.Text;
                    worksheet.ExpandColumns();
                    worksheet.ExpandRows();

                }
                workbook.SaveAs(file);
            }
        }

```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by vbjay** [comment]
Use '

**Comment by sdg002** [comment]
Thanks for the quick response. Yes. Apostrophe works. And this has been mentioned in the Wiki. My fault!
![image](https://user-images.githubusercontent.com/20245330/52362378-5c80f080-2a38-11e9-9a78-80f4bc39bba6.png)

Is there anyway I get rid of the Error icons?

**Comment by igitur** [comment]
@sdg002 No, that's an Excel function and not something controlled by the workbook.

**Comment by sdg002** [comment]
@igitur 
Many thanks for confirming.
