### ISSUE TITLE
How to display table header in every starting column of the page while printing?

### ISSUE THREAD

**Issue by sarath3940** [ClosedXML/ClosedXML#1144]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

**Version of ClosedXML**

e.g. 0.92.1

**What is the current behavior?**

I have a table pushed to the excel sheet. If I wanted to print the sheet and the table exceeds one page, it continues to print on the next page, but the header is not displayed (on the next page).

**What is the expected behavior or new feature?**

I want the header of a table to repeat in every starting column of the page, until the records are completed. 

## Reproducibility

    //Declaring headers
    currentSheet.Cell("A1").Value = "Column A Header";
    currentSheet.Cell("B1").Value = "Column B Header";
    currentSheet.Cell("C1").Value = "Column C Header";

    // Insert Data through loop
    for (int i = 0; i < ARRAY.Count; i++)
                                {
                                 
                                        currentSheet.Cell("A" + (i)).Value = ARRAY[i].value1;
                                        currentSheet.Cell("C" + (i)).Value =ARRAY[i].value2;
                                        currentSheet.Cell("D" + (i)).Value = ARRAY[i].value3;
                                        currentSheet.Cell("E" + (i)).Value = ARRAY[i].value4;
                                        currentSheet.Cell("F" + (i)).Value = ARRAY[i].value5;
                                        currentSheet.Cell("H" + (i)).Value = ARRAY[i].value6;
                                        currentSheet.Cell("J" + (i)).Value = ARRAY[i].value7;
                                        currentSheet.Cell("L" + (i)).Value = ARRAY[i].value8;
                                        currentSheet.Cell("M" + (i)).Value = ARRAY[i].value9;
                                }

I am pushing the values into the cells as shown above.

"ARRAY" consists of the table values.
While printing if the number of columns exceeds the sheets limit, it continues to print in next page. But in the next page I want to repeat the header of the table.
![1](https://user-images.githubusercontent.com/37688535/52552943-03cea080-2e08-11e9-8fa2-4f5b53301895.png)
![2](https://user-images.githubusercontent.com/37688535/52552944-03cea080-2e08-11e9-961c-f1ab8bb698fc.png)

As shown in the above two images the header is displaying in the 1st page, but not in the second. I want the header to repeat in the second page as well. 

If there is a supporting feature, please let me know. 

Thank you.

**Comment by igitur** [comment]
Please look at https://github.com/ClosedXML/ClosedXML/wiki/Sheet-Tab

**Comment by sarath3940** [comment]
Thank you so much.

**Comment by sarath3940** [comment]
Hi. The previous solution helped me a lot. But, in my case there are more than five tables(i.e, five different table headers). "SetRowsToRepeatAtTop" is working if I used it once. What if I wanted to use it for all the tables.

**Explanation**

           Lets say I have 3 tables. 1st table has covered the whole first page(While printing), and continues in the second page( lets say the top 10 rows in the second page). The header that should be repeated for the second page should be the first tables' header. 
           After that the second table starts to display and continues to the third page(While printing). Now, the header that should be repeating is the second tables' header. For that, if I reuse the "SetRowsToRepeatAtTop" for overriding the "PageSetup", I can't see any header at all. 

All I want is to repeat the latest table header in the next page. I hope I explained my issue in an understandable way. 

Thank you.

**Comment by sarath3940** [comment]
Hi. The previous solution helped me a lot. But, in my case there are more than five tables(i.e, five different table headers). "SetRowsToRepeatAtTop" is working if I used it once. What if I wanted to use it for all the tables?

**Explanation**

  Lets say I have 3 tables. 1st table has covered the whole first page(While printing), and continues in the second page( lets say the top 10 rows in the second page). The header to be repeated for the second page should be the first tables' header. 
  After that the second table starts to display and continues to the third page(While printing). Now, the header that should be repeating is the second tables' header. For that, if I reuse the "SetRowsToRepeatAtTop" for overriding the "PageSetup", the previous settings are not applied(Off course that is the way it is supposed to work). Is there any alternate implementation for my requirement?

I want to print my page as shown in the below pics.(I did it manually)

![1](https://user-images.githubusercontent.com/37688535/52565855-08a64b00-2e2e-11e9-87f8-49d5da590b4a.png)
![2](https://user-images.githubusercontent.com/37688535/52565856-08a64b00-2e2e-11e9-9001-cb9d1ffc03bc.png)
![3](https://user-images.githubusercontent.com/37688535/52565857-08a64b00-2e2e-11e9-96ab-fbd0677926cd.png)

All I want is, to repeat the latest table header in the next page. I hope I explained my issue in an understandable way. 

Thank you.

**Comment by igitur** [comment]
Attach an Excel file that is already the way you want it. I will look into
it, but my spare cycles are limited at the moment.

**Comment by sarath3940** [comment]
Sure.  
[Book1.xlsx](https://github.com/ClosedXML/ClosedXML/files/2864728/Book1.xlsx)

This is how I need my excel to look while printing.

**Comment by igitur** [comment]
Your file doesn't contain anything that configures what to print as sheet headers.
![image](https://user-images.githubusercontent.com/145854/52789300-1cd78b80-306c-11e9-99d2-fe3576386133.png)

You do realise that ClosedXML cannot generate a file that Excel itself cannot do, right?

**Comment by sarath3940** [comment]
Yes. My bad. Thanks for the information.
