### ISSUE TITLE
Can't add comment in excel file

### ISSUE THREAD

**Issue by Umeshpatil0012** [ClosedXML/ClosedXML#1146]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**0.94.2.0**

**What is the current behavior?**
I have created code to add comment in excel sheet, code runs good but doesn't add any comment.

**What is the expected behavior or new feature?**
Add comment in excel sheet using closed xml

**Did this work in previous versions of our tool?  Which versions?**
Yes, i have checked but same issue happens. 0.75.0.0.

## Reproducibility
Just open the attached excel file using closed xml (version 0.94.2.0). Then add comment to this using below code

**Code to reproduce problem:**
```c#
Stream fileStream = null;
fileStream = new MemoryStream(File.ReadAllBytes(FilePath));
var _xlWorkBook = new ClosedXML.Excel.XLWorkbook(fileStream);
XLWorkbook xlWorkBook = _xlWorkBook .XLWorkBook;
workSheet = xlWorkBook.Worksheet(1);
workSheet.Cell("K8").Comment.AddNewLine().AddText("Test").SetBold();
workSheet.Cell("K8").Comment.Style.Size.SetAutomaticSize();
_xlWorkBook.Save();
```
-  I attached a sample spreadsheet. 
[Test.xlsx](https://github.com/ClosedXML/ClosedXML/files/2876163/Test.xlsx)

**Comment by igitur** [comment]
https://github.com/ClosedXML/ClosedXML/wiki/Comments-Visibility

**Comment by igitur** [comment]
And if I run your code, and hover over the cell, the comment shows:
![image](https://user-images.githubusercontent.com/145854/52960270-18c7a880-33a1-11e9-8ea5-89816585c726.png)

**Comment by Umeshpatil0012** [comment]
Thanks, for your instant support.
