### ISSUE TITLE
Clear Formats not working when changing text to number

### ISSUE THREAD

**Issue by bwiltfong** [ClosedXML/ClosedXML#1149]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.87.0

**What is the current behavior?**

Excel workbook opens with error, "We found an error with some content...Do you want us to recover as much as we can?..."

**What is the expected behavior or new feature?**

Need to change the cells that have numbers, but are formatted as text, to a number format.

This application works when I create a spreadsheet in Excel and make the numbers text. The attached spreadsheets are created by software using an ODBC connection to create them. The spreadsheet with error at the end of the file name is one that ran through this code.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```vb
    Private Sub ProcessSpreadsheet()
        Try
            Using workbook As New XLWorkbook("YourPath\55831_Week1_State.xlsx")
                Dim ws As IXLWorksheet = workbook.Worksheet(1)
                Dim c As IXLColumns

                c = ws.Columns(2, 2)

                Dim result = c.CellsUsed.Where(Function(w) IsNumeric(w.Value))

                For Each cell In result
                       cell.Clear(XLClearOptions.Formats)        ' In Excel, if I click the down arrow on Clear and then Clear Formats, the following line (SetDataType) will work. But the cell.Clear doesn't seem to be doing the same as in Excel.
                       cell.SetDataType(XLCellValues.Number)     ' This is causing the workbook to open with error but no exception is thrown.
                       cell.Style.NumberFormat.Format = ("#,##0")
                Next

                ws.Columns().AdjustToContents()

                workbook.Save()
            End Using
        Catch ex As Exception
            Console.WriteLine(ex.Message)
            Console.Read()
        End Try
    End Sub
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

[55831_Week1_State.xlsx](https://github.com/ClosedXML/ClosedXML/files/2894857/55831_Week1_State.xlsx)
[55831_Week1_State_Error.xlsx](https://github.com/ClosedXML/ClosedXML/files/2894858/55831_Week1_State_Error.xlsx)

**Comment by igitur** [comment]
Pleaee try with the latest version.

**Comment by bwiltfong** [comment]
I updated to version 0.94.2 and still have the same issue.  I tried XLClearOptions.AllFormats, XLClearOptions.NormalFormats, and XLClearOptions.ConditionalFormats. Here is my updated code:

    Private Sub ProcessSpreadsheet()
        Try
            Using workbook As New XLWorkbook("D:\test\ExcelNumerato\Temp\55831_Week1_State.xlsx")
                Dim ws As IXLWorksheet = workbook.Worksheet(1)
                Dim c As IXLColumns

                c = ws.Columns(2, 2)

                Dim result = c.CellsUsed.Where(Function(w) IsNumeric(w.Value))

                For Each cell In result
                    cell.Clear(XLClearOptions.AllFormats)
                    cell.SetDataType(XLDataType.Number)
                    cell.Style.NumberFormat.Format = ("#,##0")
                Next

                ws.Columns().AdjustToContents()

                workbook.Save()
            End Using
        Catch ex As Exception
            Console.WriteLine(ex.Message)
            Console.Read()
        End Try
    End Sub

**Comment by igitur** [comment]
I'm assuming the input spreadsheet is generated by some external system, because it is slightly malformed. You can verify this with the [OpenXML Productivity Tool](https://www.microsoft.com/en-us/download/details.aspx?id=30425). It also has the string values saved as inline strings, which is very rare, and this is causing ClosedXML to choke. Will submit a fix, but if you can get the input spreadsheet in a more standard format (get rid of the validation errors and use standard shared strings) it would help.

**Comment by bwiltfong** [comment]
Thank you for looking into this. Unfortunately for me, it is created by software that uses an ODBC connection to add data to it. I have no control with how it is creating it.
