### ISSUE TITLE
Reading _Xceed_ results in 컭

### ISSUE THREAD

**Issue by VDBBjorn** [ClosedXML/ClosedXML#1154]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

When having for example "_Xceed_Something" filled out in cell A1 of my excel, the resulting string read from this cell will be "컭Something". 

**What is the expected behavior or new feature?**

The resulting string should be "_Xceed_Something", as this is just a string value.

**Did this work in previous versions of our tool?  Which versions?**

I don't think so, but untested

## Reproducibility

When running the code below, the result will be "컭Something" instead of "_Xceed_Something".

**Code to reproduce problem:**
```c#
public void Main()
{
   var stream = new FileStream(@"path\to\your\XceedTest.xlsx", FileMode.Open);
   var workbook = new XLWorkbook(stream);
   var sheet = workbook.Worksheets.First();

    var cell = sheet.RowsUsed().First().Cell("A");
    Console.WriteLine(cell.GetString());
}
```
- [x] I attached a sample spreadsheet. 
[XceedTest.xlsx](https://github.com/ClosedXML/ClosedXML/files/2935000/XceedTest.xlsx)

**Comment by igitur** [comment]
Interesting.

When _saving_ string values, unicode characters that are not supported by XML are encoded with a `_x0000` format, where the last for characters represent the unicode hexidecimal code. ClosedXML uses the `System.Xml.XmlConvert` class' `DecodeName` and `EncodeName` for this decoding/encoding.

See https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/tests/XmlConvert/EncodeDecodeTests.cs for examples.

Usually the encoding is done with a lowercase `x`, but according to https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/XmlConvert.cs#L96 the uppercase `X` is also valid. 

That implies that `_Xceed` is a valid escaped unicode character (the `컭`), with `CEED` being the hexidecimal code for that character.

I'll prepare a fix to explicitly ignore upper case `_X`.

**Comment by igitur** [comment]
Obviously, the intermediate workaround for you is to avoid `_X` in your cell values.
