### ISSUE TITLE
File with invalid print titles cannot be opened

### ISSUE THREAD

**Issue by bwiltfong** [ClosedXML/ClosedXML#1156]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.94.2

**What is the current behavior?**
Cannot open one of my spreadsheets. Other spreadsheets open great.

**What is the expected behavior or new feature?**
Open this spreadsheet like the others.

**Did this work in previous versions of our tool?  Which versions?**
No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```vb
Private Function ValidWorksheet(SpreadsheetName As String, wsName As String) As Boolean
     Using workbook As New XLWorkbook(SpreadsheetName)    ' This is where the error occurs.
          If Not workbook.Worksheets.Contains(wsName) Then
               Console.WriteLine($"The worksheet ({wsName}) doesn't exist in {SpreadsheetName}.")

               Return False
          End If
     End Using

     Return True
End Function
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)
[BadSpreadsheet.xlsx](https://github.com/ClosedXML/ClosedXML/files/2946671/BadSpreadsheet.xlsx)

**Comment by igitur** [comment]
@Pankraty @b0bi79 

Have you ever seen defined names for print titles like these?
```xml
    <x:definedName name="_xlnm.Print_Titles" localSheetId="0">'MAIL PLAN'!$A$1</x:definedName>
    <x:definedName name="_xlnm.Print_Titles" localSheetId="1">'SC REPORT 15'!$A$1</x:definedName>
```

Our code expects column or row ranges, i.e. `$2:$4' or `$B:$D`, not specific cells. If I load the test workbook into Excel, I don't see any defined print titles, so I assume that this is a malformed range and that we should ignore it. Your opinion?

**Comment by igitur** [comment]
@bwiltfong How was this file generated?

**Comment by b0bi79** [comment]
I think this is a bug in the xlsx file.

**Comment by bwiltfong** [comment]
Hi Guys,

Thank you for looking into this issue.

I tried removing the named cells that referred to a single cell, and ClosedXML opened the file. For a temporary fix, I’m going to see if we even need to name those single cells.

Naming a single cell within Excel is possible, so my thought is that ClosedXML should be able to also.

We are using software that connects to Excel using an ODBC connection. To tell this software where to place the data within the Excel file, we have to name the cells.   If we are placing a single column of data, there wouldn’t be a range.

I hope this is helpful. Keep up the great work. You are awesome!

Bob Wiltfong
App/Dev
Freedom
T (630) 375-8596
