### ISSUE TITLE
XmlException: There are multiple root elements when opening a second time, xlsx with a comment and a button

### ISSUE THREAD

**Issue by erezwanderman** [ClosedXML/ClosedXML#1157]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.94.0, also on the latest "develop" branch in Git

**What is the current behavior?**

When opening a spreadsheet with a comment and a button, saving and, and opening again, it crashes with System.Xml.XmlException.

**What is the expected behavior or new feature?**

Open a second time without issues.

**Did this work in previous versions of our tool?  Which versions?**

Don't know

## Reproducibility
(a sample spreadsheet with this problem is attached)
1. Open Excel 2010
2. Add a comment (from the Review tab, "New Comment")
3. Add a button (from the Developer tab, Insert->"Button (Form Control)"
4. Save the spreadsheet as BaseFile.xlsx
5. Run the program provided below.
6. Observe that on the second call to "new XLWorkbook(tempFile)", the program crashes with the following exception:
`System.Xml.XmlException: There are multiple root elements. Line 23, position 19.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(XmlReader reader)
   at ClosedXML.Excel.XDocumentExtensions.Load(Stream stream)
   at ClosedXML.Excel.XLWorkbook.GetCommentVmlFile(WorksheetPart wsPart)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName)
   at ClosedXML.Excel.XLWorkbook.Load(String file)
   at ClosedXML.Excel.XLWorkbook..ctor(String file, XLEventTracking eventTracking)
   at ClosedXML.Excel.XLWorkbook..ctor(String file)
   at Bug.Program.Main(String[] args) in C:\Users\erezw\Source\Repos\ClosedXML\Bug\Program.cs:line 24`
**Code to reproduce problem:**
```c#
using ClosedXML.Excel;
using System;
using System.IO;

namespace Bug
{
    class Program
    {
        static void Main(string[] args)
        {
            string baseFile = "BaseFile.xlsx";
            string tempFile = "Temp.xlsx";
            File.Copy(baseFile, tempFile, true);
            XLWorkbook workbook;

            // First open, succeeds
            workbook = new XLWorkbook(tempFile);
            workbook.Save();

            try
            {
                // Second open, fails with
                //System.Xml.XmlException: There are multiple root elements. Line 23, position 19.
                workbook = new XLWorkbook(tempFile);
            }
            catch (System.Xml.XmlException ex)
            {
                Console.WriteLine("Here, a bug!" + ex.ToString());
                return;
            }
            catch (Exception)
            {
                Console.WriteLine("Another exception? This doesn't happen");
                return;
            }
            workbook.Save();
            Console.WriteLine("No bug");
        }
    }
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[BaseFile.xlsx](https://github.com/ClosedXML/ClosedXML/files/2952842/BaseFile.xlsx)

**Comment by UFuz** [comment]
Is this issue going to be reviewed? Experiencing the same error and can confirm trigger is comments field(s).
Appreciate a fix (at least to ignore/discard the comments and continue parsing the rest of the file).

**Comment by Pankraty** [comment]
@erezwanderman, @UFuz can you please check the artifacts from [this build](https://ci.appveyor.com/project/ClosedXML/closedxml/builds/24423171/job/ff0le38h40dx6yeb/artifacts), if the problem is fixed?

**Comment by UFuz** [comment]
I checked the DLL from the build - and it's working! Seems it also solved the issue #1203. So hoping to have it in upcoming official build (I need signed version).

**Comment by Pankraty** [comment]
Oh, great, thanks!

The signed version is [there](https://ci.appveyor.com/project/ClosedXML/closedxml/builds/24423171/job/pwph78ho3j32w7ef/artifacts) too, though it's better to wait for an official release, of course.

**Comment by erezwanderman** [comment]
Hi @Pankraty,
I checked the change, and it seems that now the code runs well!

**Comment by UFuz** [comment]
I don't know the planned release schedule for 0.95 - but if it will take weeks or months I would appreciate if you could release a fresh beta build accessible via nuget containing this bug fix.
