### ISSUE TITLE
Request support for CONCAT() function

### ISSUE THREAD

**Issue by dizzzan** [ClosedXML/ClosedXML#1165]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.94 & develop branch

**What is the current behavior?**

concat() is not supported

**What is the expected behavior or new feature?**

concat() is the replacement for concatenate() in Excel per Microsoft: https://support.office.com/en-us/article/concat-function-9b1a9a3f-94ff-41af-9736-694cbd6b4ca2
It accepts the same parameters and has the same functionality.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

Attempt to evaluate formula using CONCAT()

**Comment by Pankraty** [comment]
Pull requests are welcome! You can implement this looking to #1015 as an example.

**Comment by dizzzan** [comment]
Hi @Pankraty, I am working on an implementation. I was running in to an '_xlfn' prefix that is added to the function in the formula. Registering "_xlfn.CONCAT" in the CalcEngine seems to work, but I don't see any other functions being registered that way nor any mention in previous issues, etc. Am I missing something that you're aware of?

**Comment by Pankraty** [comment]
I guess you are working on the version of Excel that does not support this function yet: https://support.office.com/en-us/article/issue-an-xlfn-prefix-is-displayed-in-front-of-a-formula-882f1ef7-68fb-4fcd-8d54-9fbb77fd5025?ui=en-US&rs=en-US&ad=US

In ClosedXML I don't think we need this prefix.

**Comment by dizzzan** [comment]
Sorry, I should've been more clear: the function shows correctly (and executes correctly) in my Excel (tested Office365 and 2016 versions). But if I inspect the cell's formula in ClosedXML via Cell().FormulA1 it shows _xlfn.CONCAT.
I tried registering the function as such, including the prefix, in the CalcEngine and it works as I'd expect and I'm able to evaluate the formulas on my spreadsheet. However If I only register "CONCAT", evaluating still throws an ExceptionParseException (Unknown function: ClosedXML.Excel.CalcEngine.CellRangeReference).
I will work on a small reproducible example. Maybe I am missing something. Thanks for your help.

**Comment by Pankraty** [comment]
Interesting.
Office Online does support this function, and I am able to enter both `CONCAT` and `_xlfn.CONCAT`. If I open this workbook in Excel 2016 I see the formula as `_xlfn.CONCAT` and see the result too, but cannot do anything with it - if I edit the formula the value becomes `#NAME` immediately. So basically Excel displays pre-calculated value cached in a workbook.

Since the function is being stored with a prefix in the XLSX I suppose we can register it with this name `_xlfn.CONCAT`. Or, probably we can register the same function with three aliases (CONCATENATE, CONCAT, _xlfn.CONCAT).

[Concat.xlsx](https://github.com/ClosedXML/ClosedXML/files/3013670/Concat.xlsx)

**Comment by igitur** [comment]
@dizzzan Please update your original post (top comment) with all the required details, including code sample, as requested by the issue template.

**Comment by dizzzan** [comment]
> Interesting.
> Office Online does support this function, and I am able to enter both `CONCAT` and `_xlfn.CONCAT`. If I open this workbook in Excel 2016 I see the formula as `_xlfn.CONCAT` and see the result too, but cannot do anything with it - if I edit the formula the value becomes `#NAME` immediately. So basically Excel displays pre-calculated value cached in a workbook.
> 
> Since the function is being stored with a prefix in the XLSX I suppose we can register it with this name `_xlfn.CONCAT`. Or, probably we can register the same function with three aliases (CONCATENATE, CONCAT, _xlfn.CONCAT).
> 
> [Concat.xlsx](https://github.com/ClosedXML/ClosedXML/files/3013670/Concat.xlsx)



> Or, probably we can register the same function with three aliases (CONCATENATE, CONCAT, _xlfn.CONCAT).

That's precisely what I've done and it's working in my use case so far but I'm continuing to test.

**Comment by igitur** [comment]
@Pankraty Maybe we should treat `_xlfn` as the default "namespace" and hence ignore it? And yes, we can add a `CONCAT()` alias.

**Comment by Pankraty** [comment]
Good idea
