### ISSUE TITLE
Calculation failure in date cell

### ISSUE THREAD

**Issue by masashi68** [ClosedXML/ClosedXML#117]
Please fix calculation.

The following calculation fails
=IF(A1 = "","A","B")  
 A1  <-  Date cell

I propose the following corrections.

in  ClosedXml.Excel.CalcEngine.Expression

		public static implicit operator DateTime(Expression x)
		{
			// evaluate
			var v = x.Evaluate();

			// handle dates
			if (v is DateTime)
			{
				return (DateTime)v;
			}

			// handle doubles
			if (v is double || v is int)
			{
				return DateTime.FromOADate((double)x);
			}

			// !!!!!NEW CODE !!!!!
			if (v is string || (string)v == "")
			{
				return DateTime.MinValue;
			}
			// !!!!!NEW CODE !!!!!

			 // handle everything else
			  CultureInfo _ci = Thread.CurrentThread.CurrentCulture;
			  return (DateTime)Convert.ChangeType(v, typeof(DateTime), _ci);
		}

Thanks!

**Comment by masashi68** [comment]
[ClosedXmlTest.zip](https://github.com/ClosedXML/ClosedXML/files/626107/ClosedXmlTest.zip)

**Comment by igitur** [comment]
Thanks, but your changes break a lot of other tests. I will look into a different solution to the problem.

**Comment by masashi68** [comment]
Thanks!
I am looking forward to installing from nget.
