### ISSUE TITLE
GetDouble throws exception for empty cell instead of default value

### ISSUE THREAD

**Issue by GrupoSondar** [ClosedXML/ClosedXML#1177]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

When calling XLCell.GetDouble() on a empty cell a exception is thrown

**What is the expected behavior or new feature?**

GetDouble() should return type default (0.0D in this case)

**Did this work in previous versions of our tool?  Which versions?**

Haven't used previous versions

**Code to reproduce problem:**
```c#
public void Main()
{
            var filepath = "PATH_TO_FILE";
            var sheetname = "SHEET_NAME";

            var workBook = new XLWorkbook(filepath, XLEventTracking.Disabled);
            var workSheet = workBook.Worksheet(sheetname);
            var row = workSheet.Row(1);
            var value = row.Cell("A").GetDouble(); //Exception thrown here
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
This is by design. We deliberately want to return a `Double` value only if the cell contents is of `Double` type. You should check the `cell.DataType` or `cell.IsEmpty()` in order to determine whether you can use `cell.GetDouble()`.
