### ISSUE TITLE
XLWorkbook.SaveAs OutOfMemory Exception

### ISSUE THREAD

**Issue by parag-patil** [ClosedXML/ClosedXML#1180]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

Hi team,

I am using ClosedXML version 0.94. I am getting **System.OutOfMemoryException: 'Exception of type 'System.OutOfMemoryException' was thrown.'** at below statement.

```
        public static byte[] GetByteArray(XLWorkbook workBook)
        {
            MemoryStream memStream = new MemoryStream();
            {
                **workBook.SaveAs(memStream);** //Error at this line
                memStream.Position = 0;
            }
            return memStream.ToArray();
        }

I tried below too,
MemoryStream memStream = new MemoryStream();
            {
                SaveOptions saveOptions = new SaveOptions{
                    EvaluateFormulasBeforeSaving = true,
                    GenerateCalculationChain = false,
                    ValidatePackage = false
                };
                workBook.SaveAs(memStream, saveOptions);
                memStream.Position = 0;
            }
```
I am uploading excel file with 400K records (size 32 MB) but at the time of executing above statements it shows memory consumption more than 1 GB.

Detail stacktrace error,

```
   at DocumentFormat.OpenXml.Spreadsheet.Row.ElementFactory(Byte namespaceId, String name)
   at DocumentFormat.OpenXml.OpenXmlElement.ElementFactory(String prefix, String name, String namespaceUri)
   at DocumentFormat.OpenXml.OpenXmlElement.ElementFactory(XmlReader xmlReader)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.Populate(XmlReader xmlReader, OpenXmlLoadMode loadMode)
   at DocumentFormat.OpenXml.OpenXmlElement.Load(XmlReader xmlReader, OpenXmlLoadMode loadMode)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.Populate(XmlReader xmlReader, OpenXmlLoadMode loadMode)
   at DocumentFormat.OpenXml.OpenXmlElement.Load(XmlReader xmlReader, OpenXmlLoadMode loadMode)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.Populate(XmlReader xmlReader, OpenXmlLoadMode loadMode)
   at DocumentFormat.OpenXml.OpenXmlElement.Load(XmlReader xmlReader, OpenXmlLoadMode loadMode)
   at DocumentFormat.OpenXml.OpenXmlPartRootElement.LoadFromPart(OpenXmlPart openXmlPart, Stream partStream)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.LoadDomTree[T]()
   at DocumentFormat.OpenXml.Packaging.WorksheetPart.get_Worksheet()
   at ClosedXML.Excel.XLWorkbook.GenerateWorksheetPartContent(WorksheetPart worksheetPart, XLWorksheet xlWorksheet, Boolean evaluateFormulae, SaveContext context)
   at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.CreatePackage(Stream stream, Boolean newStream, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(Stream stream, SaveOptions options)
```

**Comment by Pankraty** [comment]
For the application not to fall reaching 1 GB of memory build it in 64-bits mode rather than 32-bits.

As for exhaustive memory consumption, let's see. You have 400K records but you did not specify how many columns are there. Shall we assume some reasonable number, say 20. Historically, ClosedXML represents each cell with data and/or formatting as a single instance of `XLCell`. The amount of memory allocated by each cell depends on how much data is stored in it, so it varies hugely, but in general, it takes approximately 180 bytes at average. There are, of course, entities other than `XLCell`s too, like, styles, rows, columns, ranges, etc., but most of the pressure is created by cells.

Let's count then. `400 000 * 20 * 180` gives us 1300-something megabytes allocated by `XLCell`s only. No wonder you reach 1 GB limit.

Bad news, I don't know how to significantly decrease memory consumed by ClosedXML without a complete remaking its architecture.

Good news, not that long ago your app would fail operating with just 50K-rows file (see #86) :)

**Comment by parag-patil** [comment]
Hi @Pankraty, thanks for your reply.

- I am already working on 64 bit application.
- My  excel has 7 columns.

Is there way to reduce the XLCell processing, I am not bothered about reading styles or formatting. I want to read only value (including formula if any), so it will speed up reading process and less memory consumption if want to ignore styles and formatting.

**Comment by CaptBli** [comment]
We ran into problems using ClosedXML with large amounts of rows.  So we moved to using ClosedXML where we had small amounts of data and to create the initial spreadsheet.  Then we save and close the doc.  Then use SAX to fill in the 1M+ records by 100 columns.  I would suggest that you follow that process as well.  ClosedXML works great for smaller amounts of data, just not so well when you get into the sizes you are talking about.

**Comment by Pankraty** [comment]
@parag-patil sorry, I was going to answer your question but then forgot.

Right now ClosedXML does not provide such possibility as to open the file ignoring all styles, conditional formats, and so on. On the other hand, if you switch to the OpenXML (the underlying library used by ClosedXML to operate with raw data) you'll be able to manipulate with large amounts of data but you will lose the ability to calculate formula values, so you'll have to rely on cached values stored in file which is not always safe.

I think it would be nice of ClosedXML to provide some kind of a lightweight API to open workbooks in a read-only mode, that loads necessary data on demand (for example, when you want to read data from a single worksheet there is no need to parse the rest (Count-1) of them). But I doubt this will be implemented in the near future. Does anybody want to try?

**Comment by parag-patil** [comment]
Hi Team,

I was just trying to check the memory usage and seems  XLWorkbook template = new XLWorkbook(templatePath,XLEventTracking.Disabled); statement is taking lot of time and memory. Please see below,

`public static XLWorkbook GetTemplate(string path)
        {
            string templatePath;
            if (path.Contains(":"))
            {
                templatePath = path; //Absolute Path
            }
            else
            {   //Relative Path
                string assemblyFolder = Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location);
                templatePath = Path.Combine(assemblyFolder, path);
            }
            **XLWorkbook template = new XLWorkbook(templatePath,XLEventTracking.Disabled);**
            return template;
        }`

Below is Memory usage snapshot.
![image](https://user-images.githubusercontent.com/20587574/56518377-26f68a00-64f4-11e9-9dbd-ceda1f95c7cf.png)

Above highlighted statement took almost 2 mins to read the file with 7 columns and 400000 rows.
![image](https://user-images.githubusercontent.com/20587574/56518421-41306800-64f4-11e9-8225-8e6d1b90d9a1.png)

**Comment by jholovacs** [comment]
why is this closed?  I'm running a ClosedXML report generation that is exceeding my box's 128GB of RAM.  That is insane.  The resultant file is like 30MB.

**Comment by igitur** [comment]
It's closed because it's vague and unhelpful. If you have a specific recommendation of where in ClosedXML we could improve memory usage, by all means advise us or submit a pull request.
