### ISSUE TITLE
Anyway to read excel and return json dynamically

### ISSUE THREAD

**Issue by parag-patil** [ClosedXML/ClosedXML#1181]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

Hi All,

I am trying to create service using .NET, that will read excel and will return json. 

Is there any optimized way to read excel and convert it to JSON? Like avoiding loops and using some inbuilt like FirstCell(), LastCellUsed(), UsedRow() etc....

**Comment by igitur** [comment]
I don't really have advice for you. I suggest trying Stackoverflow.com for questions like these.
