### ISSUE TITLE
Pivot Table range limitation

### ISSUE THREAD

**Issue by mlivingstonNE** [ClosedXML/ClosedXML#1182]
- [x] Bug
- [ ] Feature

Version 0.94.2

I have a simple application that creates an Excel file, 2 sheets, a table in 1 sheet and then a pivot table in the second sheet using the table as the data.
The table has a static column count of 10. The row count varies but is generally between 35,000 and 40,000. As seen in the code below, I use a row count to define the range. But each time I ran it, the Excel file generated the old error:  _"We found a problem with some content in [file name]. Do you want to recover..."_ 
The repair log:
_Removed Feature: PivotTable report from /pivotCache/pivotCacheDefinition1.xml part (PivotTable cache)
Removed Feature: PivotTable report from /xl/pivotTables/pivotTable.xml part (PivotTable view)
Removed Records: Workbook properties from /xl/workbook.xml part (Workbook)._

After a lot of trial and error by manually setting the range, I was able to determine that if the rows were less than or equal to 32,895, the pivot table was created correctly. Anything above that row count and the Excel file generated the errors.
I expected any field limitations in ClosedXML to match Excel’s limitations.
This is the first project in which I have attempted to create pivot tables so I cannot say if this worked under older version.
Code to reproduce:
```c#
        static void Main(string[] args)
        {
            String fileName = "DeliveryCompliace " + DateTime.Today.ToString("MMddyyyy") + ".xlsx";
            String runTime = DateTime.Now.ToString("MM/dd/yyyy HH:mm");
            String reportDate = DateTime.Today.ToLongDateString();
            
            // Create Workbook
            XLWorkbook wb = new XLWorkbook();
            // Create Worksheet
            IXLWorksheet ws = wb.Worksheets.Add("Data");

            
            // Fill table from stored procedure
            SqlConnection sqlConnection = new SqlConnection(Properties.Settings.Default.conString);
            SqlCommand sqlCommand = new SqlCommand("dbo.cex_DScanCompData", sqlConnection);
            sqlCommand.CommandType = CommandType.StoredProcedure;
            sqlCommand.Parameters.Add("@dDate", SqlDbType.DateTime).Value = reportDate;
            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(sqlCommand);
            DataTable dataTable = new DataTable();
            sqlDataAdapter.Fill(dataTable);

            // Insert Datatable data
            IXLTable table = ws.Cell(1, 1).InsertTable(dataTable, "Data", true);

            // Fix OrderTrackingID format in ws
            ws.Column(5).CellsUsed().Style.NumberFormat.Format = "#.000000";
            // Adjust column widths in ws
            ws.Columns().AdjustToContents();

            // Pivot Table
            // Add new worksheet
            IXLWorksheet ps = wb.Worksheets.Add("Report");

            // Create pivot table
            var totalRows = ws.LastRowUsed().RowNumber() - 5;
            var totalColumns = ws.LastColumnUsed().ColumnNumber();
            IXLPivotTable pt = ps.PivotTables.Add("PivotTable", ps.Cell(3, 1), ws.Range(1,1,totalRows,totalColumns)); // Max rows 32,895!!

            pt.RowLabels.Add("TerminalName").SetCollapsed();
            pt.RowLabels.Add("Driver").SetCollapsed();
            pt.RowLabels.Add("ConsCompany", "Client").SetCollapsed();

            pt.Values.Add("PkgCount").SetSummaryFormula(XLPivotSummary.Sum);
            pt.Values.Add("DScan").SetSummaryFormula(XLPivotSummary.Sum);
            pt.Values.Add("MScan").SetSummaryFormula(XLPivotSummary.Sum);
            pt.Values.Add("NScan").SetSummaryFormula(XLPivotSummary.Sum);

            //For testing purposes
            IXLWorksheet ws3 = wb.Worksheets.Add("Test");
            ws3.Cell("A1").Value = totalRows;
            ws3.Cell("A2").Value = totalColumns;

            // Save workbook
            wb.SaveAs(@"C:\Users\CEsolutions\Documents\Test2.xlsx");
        }
```
- [X] I attached a sample spreadsheet.  
[Test2.xlsx](https://github.com/ClosedXML/ClosedXML/files/3074698/Test2.xlsx)

**Comment by mlivingstonNE** [comment]
"mlivingstonNE opened this issue 4 days ago · 0 comments"  :(

**Comment by igitur** [comment]
@mlivingstonNE You see, I can't copy your code into a Console app and just run it to reproduce the error. I'm so tired of explaining that to people. Logged issues that make it easy for me to reproduce the error tend to get first attention. If you want it fixed sooner, download the source and debug it yourself. That's what open-source is for.

**Comment by mlivingstonNE** [comment]
If it were that simple for me, I would have done that and shared the findings.

**Comment by mlivingstonNE** [comment]
@igitur 

I could give you code that includes a datatable of 10 columns and around 36,000 rows if that will help. It would be one heck of a post but probably better as an attached file.

But, I have something that might help. I ran the application as designed which produces the files with the error. I made a copy of the file and let Excel remove the parts as described in my original post. I then created the pivot table as intended in my application. I then compared the XML code of the PivotCacheDefinition. I discovered a couple of things that might (and I stress MIGHT) be problematic:

1.  Differences between initial pivotCacheDefinition:

Original file:
<pivotCacheDefinition
xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
r:id="rId1" saveDate="1" refreshOnLoad="1"
xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main">

Updated file:
<pivotCacheDefinition
xmlns="http:..schemas.openxmlformats.org/spreadsheetml/2006/main"
xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
mc:Ignorable="xr"
xmlns:xr="http://schemas.microsoft.com/office/spreadsheetml/2014.revision"
r:id="rId1" refreshedBy="ML" refresedDate="43574.694935648149"
createdVersion="6" refreshedVersion="6" minRefreshableVersion="3"
recordCount="37996" xr:uid="80B66BA7-BF78-4395-B92A-1B21877C76A1">

2.  The original file included 37,696 shared items that are not used the pivot table, but are part of the data table. I don't believe this is causing the problems described, but it also seems like this would take up resources unnecessarily. In the copy of the Excel file where I created the pivot table through Excel, those shared items were defined but not listed.

3.  the **extLst** and child **ext** definitions are missing from the original Excel file and are present in the edited file. That code reads:

<extLst>
     <ext uri="{725AE2AE-9491-48be-B2B4-4EB974FC3084}"
     xmlns:x14="htpp://schemas.microsoft.com/office/spreadsheetml/2009/9/main">
          <x14:pivotCacheDefinition/>
     </ext>
</extLst>

I hope this helps some. I'm certainly no expert on pivot XML.

**Comment by mlivingstonNE** [comment]
Looks like the markups did not post...

**Comment by igitur** [comment]
- Generate the Excel file, but don't add the pivot table. 
- Attach that file
- Edit the code sample so that it opens that file, adds the pivot table, saves the file and reproduces the error.

**Comment by igitur** [comment]
I spent the last hour of my precious Sunday afternoon trying to replicate the error with my own data and pivot table and couldn't. This is why a reproducible test case is so important.

**Comment by mlivingstonNE** [comment]
[DeliveryCompliaceTest 04192019.xlsx](https://github.com/ClosedXML/ClosedXML/files/3104617/DeliveryCompliaceTest.04192019.xlsx)
The created file without attempting to create a pivot table.

**Comment by mlivingstonNE** [comment]
[DeliveryCompliaceTest 04192019.xlsx](https://github.com/ClosedXML/ClosedXML/files/3104641/DeliveryCompliaceTest.04192019.xlsx)
The file created without attempting to create a pivot table, then re-loading the file and attempting to create the pivot table. The same results:
_Removed Feature: PivotTable report from /pivotCache/pivotCacheDefinition1.xml part (PivotTable cache)
Removed Feature: PivotTable report from /xl/pivotTables/pivotTable.xml part (PivotTable view)
Removed Records: Workbook properties from /xl/workbook.xml part (Workbook)._

**Comment by mlivingstonNE** [comment]
The file from the same test app as above, but limited to 10,000 rows. The pivot tables is created without errors.
[DeliveryCompliaceLimitedTest 04192019.xlsx](https://github.com/ClosedXML/ClosedXML/files/3104650/DeliveryCompliaceLimitedTest.04192019.xlsx)

**Comment by mlivingstonNE** [comment]
I examined the pivotCacheDefinition1.xml of the sheet that failed and the rows are being mis-reported. The XML read:

x:cacheSource type="worksheet">
    x:worksheetSource ref="**A1:J29286**" sheet="Data" 
  /x:cacheSource

But should have reported the worksheetSource as ref ="**A1:J38077**". I edited the XML and saved the document and it opened without error.

**Comment by igitur** [comment]
> Edit the code sample so that it opens that file, adds the pivot table, saves the file and reproduces the error.

Remember to do this.

**Comment by igitur** [comment]
The issue is that in the pivot cache definition part the maximum number of unique items per PivotField allowed is 32,500. I will prepare a fix.

**Comment by mlivingstonNE** [comment]
@igitur , Thanks for sticking with this. I knew what the problem was, but not how to identify or fix it.

**Comment by Archana3103** [comment]
$SQlServerName = '<SERVER NAME>'
$Database = '<DATABASE NAME>'

$InputPatch = Split-Path -Parent $MyInvocation.MyCommand.Path
$Report = $InputPatch + "\Report.xlsx"

If(Test-Path -path ($InputPatch + "\Application.txt"))
{

    foreach($line in [System.IO.File]::ReadLines($InputPatch + "\Application.txt")) 
     { #Write-Host $line
     $xline =  $line.split(';')
     $AssignmentID = $xline[0]
     $worksheetname = $xline[1]
     $changeno = $xline[2]
       $ApplicationQuery = "select distinct
Vrs.netbios_name0 as 'ComputerName',
aa.ApplicationName,
--ae.descript as 'DeploymentType Name',

--Vrs.User_Domain0 + '\' + Vrs.User_Name0 as 'UserName',
aa.CollectionName as 'Target Collection',
ci2.LastComplianceMessageTime,
case when ae.AppEnforcementState = 1000 then 'Success'
when ae.AppEnforcementState = 1001 then 'Already Compliant'
when ae.AppEnforcementState = 1002 then 'Simulate Success'
when ae.AppEnforcementState = 2000 then 'In Progress'
when ae.AppEnforcementState = 2001 then 'Waiting for Content'
when ae.AppEnforcementState = 2002 then 'Installing'
when ae.AppEnforcementState = 2003 then 'Restart to Continue'
when ae.AppEnforcementState = 2004 then 'Waiting for maintenance window'
when ae.AppEnforcementState = 2005 then 'Waiting for schedule'
when ae.AppEnforcementState = 2006 then 'Downloading dependent content'
when ae.AppEnforcementState = 2007 then 'Installing dependent content'
when ae.AppEnforcementState = 2008 then 'Restart to complete'
when ae.AppEnforcementState = 2009 then 'Content downloaded'
when ae.AppEnforcementState = 2010 then 'Waiting for update'
when ae.AppEnforcementState = 2011 then 'Waiting for user session reconnect'
when ae.AppEnforcementState = 2012 then 'Waiting for user logoff'
when ae.AppEnforcementState = 2013 then 'Waiting for user logon'
when ae.AppEnforcementState = 2014 then 'Waiting to install'
when ae.AppEnforcementState = 2015 then 'Waiting retry'
when ae.AppEnforcementState = 2016 then 'Waiting for presentation mode'
when ae.AppEnforcementState = 2017 then 'Waiting for Orchestration'
when ae.AppEnforcementState = 2018 then 'Waiting for network'
when ae.AppEnforcementState = 2019 then 'Pending App-V Virtual Environment'
when ae.AppEnforcementState = 2020 then 'Updating App-V Virtual Environment'
when ae.AppEnforcementState = 3000 then 'Requirements not met'
when ae.AppEnforcementState = 3001 then 'Host platform not applicable'
when ae.AppEnforcementState = 4000 then 'Unknown'
when ae.AppEnforcementState = 5000 then 'Deployment failed'
when ae.AppEnforcementState = 5001 then 'Evaluation failed'
when ae.AppEnforcementState = 5002 then 'Deployment failed'
when ae.AppEnforcementState = 5003 then 'Failed to locate content'
when ae.AppEnforcementState = 5004 then 'Dependency installation failed'
when ae.AppEnforcementState = 5005 then 'Failed to download dependent content'
when ae.AppEnforcementState = 5006 then 'Conflicts with another application deployment'
when ae.AppEnforcementState = 5007 then 'Waiting retry'
when ae.AppEnforcementState = 5008 then 'Failed to uninstall superseded deployment type'
when ae.AppEnforcementState = 5009 then 'Failed to download superseded deployment type'
when ae.AppEnforcementState = 5010 then 'Failed to updating App-V Virtual Environment'
End as 'State Message'
from v_R_System_Valid Vrs
join vAppDTDeploymentResultsPerClient ae on ae.ResourceID=Vrs.ResourceID
join  v_CICurrentComplianceStatus ci2 on ci2.CI_ID=ae.CI_ID AND
ci2.ResourceID=Vrs.ResourceID
join v_ApplicationAssignment aa on ae.AssignmentID = aa.AssignmentID
where ae.AppEnforcementState is not null and aa.AssignmentID in ('$AssignmentID') order by [State Message] Desc"


$Sqlconnection = New-object System.Data.SqlClient.SqlConnection
$Sqlconnection.ConnectionString = "Server=$SQlServerName;Database=$Database;integrated security = True"


$sqlcmd = New-Object System.Data.SqlClient.SqlCommand
$sqlcmd.CommandText = $ApplicationQuery
$sqlcmd.Connection = $Sqlconnection

$sqladapter = New-Object System.Data.SqlClient.SqlDataAdapter
$sqladapter.SelectCommand = $sqlcmd
$dataset = new-object System.Data.Dataset

$sqladapter.Fill($dataset)
$Sqlconnection.Close()


$DataSetTable = $dataset.tables['Table']


$DataSetTable | Export-Excel -worksheetname $worksheetname -path "D:\Scripts\DeploymentReport\Report.xlsx"  -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors -AutoSize -BoldTopRow -FreezeTopRow -TableStyle Light13 
$excel = Open-ExcelPackage -Path "D:\Scripts\DeploymentReport\Report.xlsx"

Add-PivotTable -PivotTableName $worksheetname -SourceWorkSheet $excel.Workbook.Worksheets[$worksheetname] -Address $excel.Workbook.Worksheets[$worksheetname].Cells['G1'] -PivotRows "State Message" -PivotData @{"State Message"="Count"} -Verbose
Close-ExcelPackage $excel
}

}

I am looping through set of lines . It reads Assignment ID and puts into SQL query and fetech's the output to the excel sheet and creates its pivot table in the same sheet. Everything is perfect but when I open the Excel file its prompted me with 2 warnings.

"we found a problem with some content in the Report.xlsx. Do you want to recover as much as we can? if you trust the source of this workbook click YES"

Excel was able to open file by reparing ...
"Removed Feature: PivotTable report from /xl/pivotCache/pivotCacheDefinition1.xml part (PivotTable cache)
Removed Feature: PivotTable report from /xl/pivotCache/pivotCacheDefinition2.xml part (PivotTable cache)
Removed Feature: PivotTable report from /xl/pivotTables/pivotTable1.xml part (PivotTable view)
Removed Feature: PivotTable report from /xl/pivotTables/pivotTable2.xml part (PivotTable view)
Removed Records: Workbook properties from /xl/workbook.xml part (Workbook)"

 I would want Pivot to be retained in the same page.

**Comment by Archana3103** [comment]
I am really stuck. help to this issue with resolution would be much appreciated.

**Comment by Dzunisanu** [comment]
Update my DocumentFormat.OpenXml to latest solved the issue

**Comment by bassvel** [comment]
> DocumentFormat.OpenXml package

It didn't worked for me all: just wasted 1.5Gb on downloading everything that enable the OpenXml
