### ISSUE TITLE
Better treatment of half-baked properties (eg RichText, Hyperlink etc)

### ISSUE THREAD

**Issue by smilinger** [ClosedXML/ClosedXML#1184]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

**0.94.2**

in Powershell 5.1, Windows 10 x64

**What is the current behavior?**

If I enter a cell object in PowerShell command line to inspect its properties, the cell will turn into a hyperlink cell, and prevent the workbook to save. Save the workbook cause error below:
```
Exception calling "SaveAs" with "1" argument(s): "Value cannot be null.
Parameter name: source”
At line:4 char: 1
+ $wb.SaveAs("Desktop\Test.xlsx")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException
```
This is the InnerException stacktrace (from $error[0].Exception.InnerException.Stacktrace):
```
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at ClosedXML.Excel.XLHyperlink.get_InternalAddress()
   at ClosedXML.Excel.XLWorkbook.GenerateWorksheetPartContent(WorksheetPart worksheetPart, XLWorksheet xlWorksheet, Boolean evaluateFormulae, SaveContext context)
   at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at CallSite.Target(Closure , CallSite , Object , String )
```

**What is the expected behavior or new feature?**

Should save with no problem.

**Did this work in previous versions of our tool?  Which versions?**

same problem in 0.93.1

## Reproducibility

**Code to reproduce problem:**
```powershell
add-type -Path .nuget\packages\fastmember\1.3.0\lib\net45\FastMember.dll
add-type -path .nuget\packages\excelnumberformat\1.0.3\lib\net20\ExcelNumberFormat.dll
add-type -path .nuget\packages\documentformat.openxml\2.7.2\lib\net46\DocumentFormat.OpenXml.dll
add-type -path .nuget\packages\closedxml\0.94.2\lib\net46\ClosedXML.dll

$wb = New-Object ClosedXML.Excel.XLWorkbook
$sheet = $wb.AddWorksheet("Test")
$sheet.Cell("A1")  # This line will cause the following line throw error
$wb.SaveAs("Desktop\Test.xlsx")
$sheet.Cell("A1").Hyperlink = $null  # This line will somehow fix the error
$wb.SaveAs("Desktop\Test.xlsx")  # It's ok this time.
```

**Comment by igitur** [comment]
I have never tried to debug a .NET DLL from a PowerShell scripts. Have you? Since this is an open-source proejct and we rely on the community, can I ask you to try to debug this and try to find the cause of the problem? We'll then look at implementing a fix.

**Comment by smilinger** [comment]
Hi, I am not familiar with this project, this is what I found:

```c#
// at line: 69 of XLHyperlink_public.cs
        public String InternalAddress
        {
            get
            {
                if (IsExternal)
                    return null;
                if (String.IsNullOrEmpty(_internalAddress)) // I add this and solve the problem.
                    return null;
                if (_internalAddress.Contains('!')) // the _internalAddress is null when access from the powershell
                {
                    return _internalAddress[0] != '\''
                               ? String.Concat(
                                    _internalAddress
                                        .Substring(0, _internalAddress.IndexOf('!'))
                                        .EscapeSheetName(),
                                    '!',
                                    _internalAddress.Substring(_internalAddress.IndexOf('!') + 1))
                               : _internalAddress;
                }
                return String.Concat(
                    Worksheet.Name.EscapeSheetName(),
                    '!',
                    _internalAddress);
            }
            set
            {
                _internalAddress = value;
                IsExternal = false;
            }
        }
```

**Comment by igitur** [comment]
I see.

`$sheet.Cell("A1")` causes every property in `XLCell` to be evaluated and printed. Some properties, e.g. `cell.DataValidation`, `cell.RichText` and `cell.Hyperlink` shouldn't be touched unless you want to create those things. Unfortunately, if you touch the getter of `cell.Hyperlink` without setting further hyperlink properties, you end up with a half-baked hyperlink class, which causes the error upon saving. I can fix that.

But my suggestion is not to evaluate the full `XLCell`, but rather address its specific properties that you want.

**Comment by smilinger** [comment]
I know, it's not normal programming practice to evaluate every property of an object without purpose, but it's handy and normal practice to do that in powershell console when I am not familiar with the object and then decide what to do, which of course I will not do in real code. 
Also please consider the situation when you are debugging in Visual Studio and you are inspecting variables in the watch window, and it's very likely that you click a cell variable to expand it to see its properties, and the hyperlink property will be initialized with no value, hence cause errors, unless you manually reset the hyperlink to null.

Also further test shows that my fix above is not enough to address this issue.

**Comment by igitur** [comment]
Yes, I understand. Will fix it anyway. Why does your fix not address everything? What else is wrong?

**Comment by smilinger** [comment]
Because this is happening:

`Exception calling "SaveAs" with "1" argument(s):“Part /xl/worksheets/sheet1.xml, Path /x:worksheet[1]/x:hyperlinks[1]/x:hyperl
ink[1]: The attribute 'location' has invalid value ''. The attribute value cannot be empty.”
At line:1 char: 1
+ $wb.saveas("test.xlsx")
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ApplicationException`

**Comment by smilinger** [comment]
I also noticed that an empty comment is automatically created just like hyperlink, however this will not cause save problem.
