### ISSUE TITLE
ClosedXML AddConditionalFormat() Adds Quotes To Value In Excel (French)

### ISSUE THREAD

**Issue by CaptBli** [ClosedXML/ClosedXML#1187]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

I am using conditional formatting and it works great with my U.S. settings. When ClosedXML is used on European PCs, the **conditional formatting** when using numbers in the translated spreadsheets works great for Italian and German, but in French the conditional formatting is incorrect.  The numbers get converted to strings which when opened in Excel doesn't work.

The AddConditionalFormat().WhenEqualOrLessThan() methods do not work correctly when the locale is French. It adds quotes to the conditional statement. When I open it in Excel the Rule looks like:

Cell Value <= "-98.00002"

It is supposed to be:

Cell Value <= -98.00002

In the case of French localization, the extraneous quotes are added, but not the the Italian and German cases.

Following is my actual code:

```
ws.Range(r, 1, r, 2).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.General; 

__ws.Cell(r, 2).AddConditionalFormat().WhenEqualOrLessThan(-98.00002f). Font.SetFontColor(XLColor.LightGray);__

ws.SheetView.FreezeRows(2);
ws.Columns().AdjustToContents();
```

We posted this problem a long time ago and thought it was fixed.  It is definitely in the current builds.

**What is the expected behavior or new feature?**

We expect that the Conditional Format to be: Cell Value <= -98.00002

**Did this work in previous versions of our tool?  Which versions?**
The old code: 

```
private String GetQuoted(XLFormula formula)
{
String value = formula.Value;
Double num;
if ((!Double.TryParse(value, out num) && !formula.IsFormula) && value[0] != '\"' && !value.EndsWith("\""))
return String.Format("\"{0}\"", value.Replace("\"", "\"\""));

return value;
}
```

We made a modification to the code to make this work in the past.  The following code will fix the issue in older code. 

```
private String GetQuoted(XLFormula formula)
{
String value = formula.Value;
Double num;
if ((!Double.TryParse(value, NumberStyles.Any, CultureInfo.GetCultureInfo("en-US"), out num) && !formula.IsFormula) && value[0] != '\"' && !value.EndsWith("\""))
return String.Format("\"{0}\"", value.Replace("\"", "\"\""));
return value;
}
```

## Reproducibility

Creating any spreadsheet with a Conditional Format with language set to French will reproduce the issue.  

I know I might incur the wrath for not providing a way to replicate this.  You have to have your CultureInfo set to "fr-FR" and you can reproduce this problem with a Conditional Format that uses numbers.  The current build turns them into strings in the export.

I have provided code to fix it.  And the culprit can easily be seen in the code.  So... 

This example spreadsheet created with the French CultureInfo, shows the problem.  When you open it on any Culture in Excel it will exhibit the issue.
[FrenchSpreadsheet.xlsx](https://github.com/ClosedXML/ClosedXML/files/3090625/FrenchSpreadsheet.xlsx)

**Comment by Pankraty** [comment]
Sooo many words...

```
Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("fr-FR");
var wb = new XLWorkbook();
var ws = wb.AddWorksheet();
ws.FirstCell().AddConditionalFormat()
    .WhenEqualOrLessThan(-98.00002f).Fill.SetBackgroundColor(XLColor.Red);
ws.FirstCell().Value = 100;
wb.SaveAs("1187_fr-FR.xlsx");

Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("en-US");
wb.SaveAs("1187_en-US.xlsx");
```

en-US looks as expected:
![Uploading 1187_en-US.png…]()

fr-FR looks wrong as a numeric value has been quoted:
![Uploading 1187_fr-FR.png…]()
