### ISSUE TITLE
SaveAs() an unmodified XLWoorkbook throws an exception casting null to PatternValues

### ISSUE THREAD

**Issue by TheDon79** [ClosedXML/ClosedXML#1191]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.95.0 (3dcf1075b2b4a819713685d40814fc0ec33eca43)

**What is the current behavior?**

I get the following exception after simply open/load a file and then save the document to another file, for this particular file. 
```System.InvalidOperationException
  HResult=0x80131509
  Nachricht = Error in implicit conversion. Cannot convert null object.
  Quelle = DocumentFormat.OpenXml
  Stapelüberwachung:
   bei DocumentFormat.OpenXml.EnumValue`1.op_Implicit(EnumValue`1 xmlAttribute)
   bei ClosedXML.Excel.XLWorkbook.<>c__DisplayClass396_0.<ResolveFillWithPattern>b__0(Fill f) in D:\Projects\ClosedXml\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs: Zeile4214
   bei System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   bei ClosedXML.Excel.XLWorkbook.ResolveFillWithPattern(Fills fills, PatternValues patternValues) in D:\Projects\ClosedXml\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs: Zeile4213
   bei ClosedXML.Excel.XLWorkbook.ResolveFills(WorkbookStylesPart workbookStylesPart, Dictionary`2 sharedFills) in D:\Projects\ClosedXml\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs: Zeile4182
   bei ClosedXML.Excel.XLWorkbook.GenerateWorkbookStylesPartContent(WorkbookStylesPart workbookStylesPart, SaveContext context) in D:\Projects\ClosedXml\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs: Zeile3630
   bei ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options) in D:\Projects\ClosedXml\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs: Zeile265
   bei ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options) in D:\Projects\ClosedXml\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs: Zeile123
   bei ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options) in D:\Projects\ClosedXml\ClosedXML\ClosedXML\Excel\XLWorkbook.cs: Zeile464
   bei ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae) in D:\Projects\ClosedXml\ClosedXML\ClosedXML\Excel\XLWorkbook.cs: Zeile437
   bei ClosedXML.Excel.XLWorkbook.SaveAs(String file) in D:\Projects\ClosedXml\ClosedXML\ClosedXML\Excel\XLWorkbook.cs: Zeile426
   bei ClosedXmlBug.Program.Main(String[] args) in D:\Projects\ClosedXml\ClosedXmlBug\Program.cs: Zeile19
```

This is the offending code part in ClosedXML from `ClosedXML.Excel.XLWorkbook.ResolveFillWithPattern(...)` in the file `XLWorkbook_Save.cs`
``` c#
            if (fills.Elements<Fill>().Any(f =>
                f.PatternFill.PatternType == patternValues
                && f.PatternFill.ForegroundColor == null
                && f.PatternFill.BackgroundColor == null
                )) return;
```

The problem is the `f.PatternFill.PatternType` which is of type `EnumValue<PatternValues>`. If this property is `null` it cannot be converted to a `PatternValues` value.

I have solved it by replacing
```
f.PatternFill.PatternType == patternValues
```
with
```
(f.PatternFill.PatternType ?? PatternValues.None) == patternValues
```

Additionally:

If I simply load the file in LibreOffice Calc and save it as a new file, the new file can be loaded and saved with ClosedXML without a problem.

**What is the expected behavior or new feature?**

I expect that the `XLWorkbook.SaveAs()` method does not throw an exception.

**Did this work in previous versions of our tool?  Which versions?**

I don't know. It is the first time, I am using ClosedXML. At least, it does not work in the current stable (0.94.2) too.

## Reproducibility

**Code to reproduce problem:**
```c#
        static void Main(string[] args)
        {
            string lInFile = "test_in.xlsx";
            string lOutFile = "test_out.xlsx";

            using (var lWB = new XLWorkbook(lInFile))
                lWB.SaveAs(lOutFile);
        }
```
- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)
[issue1191.xlsx](https://github.com/ClosedXML/ClosedXML/files/3176488/issue1191.xlsx)

Add added the testfile here too.

**Comment by igitur** [comment]
> I am not able to share the problematic file with the public here on github because of business data.

Then produce a file with non-sensitive data. If I can't replicate it, I can't fix it.

**Comment by TheDon79** [comment]
I could get a simple testfile showing the problem.
[issue1191.xlsx](https://github.com/ClosedXML/ClosedXML/files/3107466/issue1191.xlsx)

**Comment by easuter** [comment]
@igitur this bug is still present in 0.95.4 and easily reproducible using the sample workbook that @TheDon79 uploaded:

![image](https://user-images.githubusercontent.com/4330134/161618194-046b0342-76a8-4f80-9b30-d2a4b6b14f2f.png)

What would be required to include his suggested fix in the next release?

**Comment by binn** [comment]
How has this simple bug still not been fixed yet?

**Comment by vbjay** [comment]
@binn 

This is a story of four people named Everybody, Somebody, Anybody, and Nobody. There was an important job to be done and Everybody was asked to do it. Everybody was sure Somebody would do it. Anybody could have done it, but Nobody did it. Somebody got angry about that because it was Everybody’s job. Everybody thought Anybody could do it, but Nobody realized that Everybody wouldn’t do it. It ended that Everybody blamed Somebody when Nobody did what Anybody could have done.

Instead of being an everybody, be a somebody.
