### ISSUE TITLE
Disallow table name that is also a valid address

### ISSUE THREAD

**Issue by MetalPhreak** [ClosedXML/ClosedXML#1192]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.94.2.0

**What is the current behavior?**

I am creating tables on worksheets using naming scheme of MonthYear (ie July2019). Works fine until I add a table for May2019. Excel opens the file with errors and repairs tableX.xml and changes display name to May2019_ 

It appears excel requires minimum of 8 characters for table names?

**What is the expected behavior or new feature?**

ClosedXML throws error if supplied name is less than 8 chars. 

**Did this work in previous versions of our tool?  Which versions?**

Not Sure.

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
            DataTable dtable = new DataTable();
            dtable.TableName = "May2019";
            dtable.Columns.Add("Dosage", typeof(int));
            dtable.Columns.Add("Drug", typeof(string));
            dtable.Columns.Add("Patient", typeof(string));
            dtable.Columns.Add("Date", typeof(DateTime));
            
            dtable.Rows.Add(25, "Indocin", "David", DateTime.Now);
            dtable.Rows.Add(50, "Enebrel", "Sam", DateTime.Now);
            dtable.Rows.Add(10, "Hydralazine", "Christoff", DateTime.Now);
            dtable.Rows.Add(21, "Combivent", "Janet", DateTime.Now);
            dtable.Rows.Add(100, "Dilantin", "Melanie", DateTime.Now);

            var wb = new XLWorkbook();
            var ws = wb.AddWorksheet("May2019"); //this is fine
            var table = ws.Cell(1, 1).InsertTable(dtable, "May2019");
            wb.SaveAs("test.xlsx");
}
```
- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)
[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/3105474/test.xlsx)

I've worked around the problem by just appending some data to the end of table names to guarantee >8 chars.

**Comment by Pankraty** [comment]
> It appears excel requires minimum of 8 characters for table names?

This is a wrong assumption, since Excel itself names tables like 'Table1' by default (6 characters).

The reason of the issue is that MAY2019 is treated as a cell address, somewhere far right in 2019th row.

If you change your naming schema to May_2019 it'll work fine.

**Comment by MetalPhreak** [comment]
Oh wow, I didn't think of that. You are 100% correct!

Thanks

**Comment by igitur** [comment]
Nice catch @Pankraty . 

But even so, ClosedXML should be throwing an appropriate exception. I recall that we do rigorous name validation for Pictures and I thought for Tables, but apparently not.
