### ISSUE TITLE
CurrentRegion for IXLRange

### ISSUE THREAD

**Issue by deltavision** [ClosedXML/ClosedXML#120]
I miss the command **CurrentRegion** for the IXLRange-Object.
In VBA, with CurrentRegion it es very easy and simple the find the size/border for a range of datas.

**Comment by igitur** [comment]
Please have a look at https://github.com/closedxml/closedxml/wiki/Simplifying-your-life

Some of those methods are somewhat analogous to `CurrentRegion` in VBA, although not completely.

**Comment by deltavision** [comment]
Thanks igitur for your input, but that doesnt help me. 
In my project I have on the same worksheet many tables but for me with unknown number of rows and columns. In VBA, I can take a Cell in the table and with CurrentRegion I geht the start and end of the table. 
eg. 


. | A | B | C | D | E |  F |  G |  H
-|---|---|--|---|---|---|----|--------
1|    |  x | x | x  |    |    |  x |  x
2|    |  x | x | x  |    |    |  x |  x
3|    |  x | x  | x |    |    |  x |  x
4|    |     |   |     |    |    |  x |  x

Datas from Table 1 are located in B1:D3 and  
Datas from Table 2 are located in G1: H4
Columns between are empty

VBA to geht Border/Size vom Table 1
firstRow =  Range("B1").CurrentRegion.Row
lastRow = firstRow + Range("B1").CurrentRegion.Rows.Count -1 

VBA to geht Border/Size vom Table 2
firstRow =  Range("G1").CurrentRegion.Row
lastRow = firstRow + Range("G1").CurrentRegion.Rows.Count -1 

(Same for columns)

With ClosedXml I can find out the last used row in the worksheet (Row 3)  but not in my table. Same for columns. Is there an easy way? In real world, my tables have some cells that are empty. So I cant search in the frist column for the first empty cell.

**Comment by igitur** [comment]
Please test this with the buidl at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.567/artifacts

This is currently implemented only for a single cell.

**Comment by deltavision** [comment]
I downloaded the DLL from the above link, but there is no CurrentRegion function on IXLCell

**Comment by igitur** [comment]
I can see it clearly. Double-check that you're referencing the correct dll.

![image](https://user-images.githubusercontent.com/145854/30687438-8d0c8c0a-9ebb-11e7-96b6-8964bb161755.png)

**Comment by deltavision** [comment]
Thanks a lot – works perfect.

 

(Sorry, I first had the old reference)

 

 

Von: Francois Botha [mailto:notifications@github.com] 
Gesendet: Mittwoch, 20. September 2017 21:04
An: ClosedXML/ClosedXML
Cc: deltavision; Author
Betreff: Re: [ClosedXML/ClosedXML] CurrentRegion for IXLRange (#120)

 

Please test this with the buidl at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.567/artifacts

This is currently implemented only for a single cell.

**Comment by igitur** [comment]
https://www.nuget.org/packages/ClosedXML/0.90.0-beta2 is released and should include the fix for this issue.
