### ISSUE TITLE
Could not load file or assembly "DocumentFormat.OpenXml, Version=2.7.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17" or one of its dependencies.

### ISSUE THREAD

**Issue by korneliuscode** [ClosedXML/ClosedXML#1200]
**Version of ClosedXML**

e.g. 0.94.2

**What is the current behavior?**

I use the nuget version 0.94.2., FastMember 1.4.1, ExcelNumberFormat 1.0.5, DocumentFormat.OpenXML 2.9.1
When deploying the app in release build and executing on a "fresh" PC I get the error message Could not load file or assembly "DocumentFormat.OpenXml, Version=2.7.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17" or one of its dependencies.
It seems something is tied to a particular version of OpenXml. The version that is in the bin folder is 2.9.1.2 as described in the nuget package manager.

**Did this work in previous versions of our tool?  Which versions?**

Didn't use earlier version

**Comment by igitur** [comment]
Can you upload a zip file somewhere of a reduced project that replicates the issue?

**Comment by korneliuscode** [comment]
I created a new project but the error does not occur. I have no idea where the difference is. I reverted to version 2.7.2 and v. 1.3.0. of FastMember to make it work again.
