### ISSUE TITLE
IXLPicture.BottomRightCell is always null?

### ISSUE THREAD

**Issue by tomRedox** [ClosedXML/ClosedXML#1206]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.94.2

**What is the current behavior?**
When looking at a list of pictures in a worksheet, the `BottomRightCell' for each image is null.

**What is the expected behavior or new feature?**
`BottomRightCell' should reference the cell the bottom right of the image intersects with

**Did this work in previous versions of our tool?  Which versions?**
Don't know

## Reproducibility

**Code to reproduce problem:**

Add the attached spreadsheet into the root of the project, set it to Content and Copy Always in the properties window.

```c#
public void Main()
{
            var importPath = Path.Combine(
                AppDomain.CurrentDomain.BaseDirectory,
                @"ExtractImageTestData.xlsx");

            var wb = new XLWorkbook(importPath);
            var workSheetName = "Sheet1";
            var xlWorksheet = wb.Worksheet(workSheetName);

            var pictures = xlWorksheet.Pictures;
            
            Console.WriteLine(pictures.Count);

            try
            {
                Console.WriteLine(pictures.ToList()[0].BottomRightCell.Address.ColumnLetter);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
}
```
- [ x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[ExtractImageTestData.xlsx](https://github.com/ClosedXML/ClosedXML/files/3167517/ExtractImageTestData.xlsx)

**Comment by igitur** [comment]
It's populated only if both the position and size is locked. I suppose your images are locked only at position or not at all?

**Comment by tomRedox** [comment]
Ah, that sounds like the problem then.  These are the image properties in Excel:

![image](https://user-images.githubusercontent.com/11335350/57547298-1ea4a880-7356-11e9-8925-66f88c1713a8.png)

Is this specific to ClosedXML, or would it be the case in OpenXML too?

**Comment by igitur** [comment]
It's an OpenXML thing. The bottom right cell's info just isn't stored in the file. Could theoretically calculate it, but you'd need a full renderer and be able to take into account cell widths and font sizes. I bet you won't even get the same result on Excel vs LibreOffice.

You have to select 'Move and size with cells', the first radio button.

**Comment by tomRedox** [comment]
@igitur thanks for the reply, that makes complete sense re needing a renderer.
