### ISSUE TITLE
Cannot open file with pivot table created from same-named columns

### ISSUE THREAD

**Issue by lahma** [ClosedXML/ClosedXML#1211]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.95.0-beta1 (tested also with develop)

**What is the current behavior?**

`System.ArgumentOutOfRangeException : The column 'Résultat ToxB2' does not appear in the source range.
Parameter name: sourceName` 

**What is the expected behavior or new feature?**

ClosedXML should be able to cope with pivoted source columns that have the same name. It seems that MS Excel adds running number to them to distinguish them apart.

**Did this work in previous versions of our tool?  Which versions?**

Yes, at least with 0.88 which I'm trying to upgrade from.

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
new XLWorkbook(File.OpenRead(@"c:\temp\test.xlsx"), XLEventTracking.Disabled);
}
```
- [x] I attached a sample spreadsheet. 

[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/3197052/test.xlsx)

**Comment by lahma** [comment]
This doesn't seem to be an issue with the latest NuGet release anymore.

**Comment by rklec** [comment]
Having a similar issue with v0.102.0 of ClosedXML, see https://github.com/ClosedXML/ClosedXML/issues/2130
