### ISSUE TITLE
Error with AutoFilter and Table

### ISSUE THREAD

**Issue by xeroiv** [ClosedXML/ClosedXML#1213]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

Error when opening file in Excel.  "We found a problem with some content in 'AddingDataTableAsWorksheet.xlsx'.  Repairs remove feature AutoFilter & Table from /xl/tables/table1.xml .  Repairing also remove the Table style.

**What is the expected behavior or new feature?**

Open the Excel file without error, and retains table style.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
        private void Main()
        {
            var wb = new XLWorkbook();

            var dataTable = GetTable("Information");

            // Add a DataTable as a worksheet
            var ws = wb.Worksheets.Add(dataTable);

            // Add filters
            ws.RangeUsed().SetAutoFilter().Column(1).AddFilter(10)
              .AddFilter(100)
              .AddFilter(50);

            // Sort the filtered list
            ws.AutoFilter.Sort(1);

            wb.SaveAs("AddingDataTableAsWorksheet.xlsx");

        }

        private DataTable GetTable(String tableName)
        {
            DataTable table = new DataTable();
            table.TableName = tableName;
            table.Columns.Add("Dosage", typeof(int));
            table.Columns.Add("Drug", typeof(string));
            table.Columns.Add("Patient", typeof(string));
            table.Columns.Add("Date", typeof(DateTime));

            table.Rows.Add(25, "Indocin", "David", DateTime.Now);
            table.Rows.Add(50, "Enebrel", "Sam", DateTime.Now);
            table.Rows.Add(10, "Hydralazine", "Christoff", DateTime.Now);
            table.Rows.Add(21, "Combivent", "Janet", DateTime.Now);
            table.Rows.Add(100, "Dilantin", "Melanie", DateTime.Now);
            return table;
        }
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by callsoft** [comment]
I just started getting this same error after updating to the latest version.  Did you ever figure out it?

I'm just calling `ws.RangeUsed().SetAutoFilter()` after creating a table which used to work and now doesn't.

```xml
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
    <logFileName>error118600_01.xml</logFileName>
    <summary>Errors were detected in file 'C:\Users\user\Downloads\Bulk Import Template .xlsx'</summary>
    <additionalInfo>
        <info>Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.</info>
    </additionalInfo>
    <removedFeatures>
        <removedFeature>Removed Feature: AutoFilter from /xl/tables/table1.xml part (Table)</removedFeature>
        <removedFeature>Removed Feature: Table from /xl/tables/table1.xml part (Table)</removedFeature>
        <removedFeature>Removed Feature: AutoFilter from /xl/tables/table2.xml part (Table)</removedFeature>
        <removedFeature>Removed Feature: Table from /xl/tables/table2.xml part (Table)</removedFeature>
    </removedFeatures>
</recoveryLog>
```

**Comment by igitur** [comment]
So is this a regression from 0.94.2? @xeroiv 's report says it didn't work in previous versions either.

**Comment by igitur** [comment]
@callsoft The sample code that @xeroiv provided fails in 0.94.2, so this isn't a regression and if you suddenly started receiving this error, it's probably a different bug.

**Comment by igitur** [comment]
@xeroiv , you cannot add a filter to a range if there is already a table in that same range. For purposes, use:

```c#
            ws.Tables.First()
                .AutoFilter
                .Column(1).AddFilter(10)
                .AddFilter(100)
                .AddFilter(50);
```

However, I submitted a PR to explicitly throw an exception if you have overlapping autofilter and table ranges.

**Comment by callsoft** [comment]
@igitur In my case the older version 0.94.2 did not cause a problem for whatever reason when adding a filter to a range overlapping a table range.  

I changed my code to add the autofilter to the Table rather than RangeUsed as you suggested and that fixed it.  Thanks!
