### ISSUE TITLE
How to set width for range

### ISSUE THREAD

**Issue by rshivarkar** [ClosedXML/ClosedXML#1214]
What is equivalent of below code in Microsoft.Office.Interop.Excel for ClosedXML.
code in Microsoft.Office.Interop.Excel – 
**_Excel.Range rngCurrent;
 rngCurrent = dealSheet.get_Range("A1", "K27");
rngCurrent.ColumnWidth = 22;**

Code in ClosedXML:

IXLRange rngCurrent1;
 rngCurrent1 = dealSheet.Range("A1", "K27");
//Question is how to set width here?

**Comment by raymordy** [comment]
You cant apply a width to a range you need to do it to the columns like so:

var workBook = new XLWorkbook();
var workSheet = workBook.Worksheets.Add("Width Examples");

 workSheet.Columns("A:K").Width = 22;

**Comment by igitur** [comment]
@raymordy is correct.
