### ISSUE TITLE
SetFormulaA1 turns entered formula lowercase, causing errors when using worksheet names.

### ISSUE THREAD

**Issue by jonekcode** [ClosedXML/ClosedXML#1216]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

Entered allcaps formula is turned into lowercase.

**What is the expected behavior or new feature?**

No enforced lowercase formatting.

**Did this work in previous versions of our tool?  Which versions?**

No idea.

## Reproducibility

Entered formula using code below:

`secondPage.Cell("B14").SetFormulaA1($"PLAN.B17/PLAN.K17");`

Results in cell having this value:

`=plan.b17/plan.b17`

Which is an issue, because the worksheet is called PLAN in allcaps.

**Code to reproduce problem:**
```c#
var workbook = new XLWorkbook("Any workbook with 2 worksheets");

var secondPage = workbook.Worksheets.ElementAt(1);

secondPage.Cell("B14").SetFormulaA1($"PLAN.B17/PLAN.K17");
```

**Comment by jonekcode** [comment]
Apparently not only that, but any formula that uses worksheet name doesn't work and ends up being displayed as #NAME?.

Clicking on the cell in any excel editor, adding extra space at the end or re-typing any character fixes the formula.

**Comment by igitur** [comment]
Insufficient code sample.
