### ISSUE TITLE
INDEX function not recognized when access from another cell

### ISSUE THREAD

**Issue by mms92** [ClosedXML/ClosedXML#1218]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.0-beta1

**What is the current behavior?**

when another cell in a workwook access a cell with INDEX function , the INDEX function is not recognized and error is returned : "Unknown function: INDEX"

without that cell access , the INDEX function is correctly recognized and return correct value

**What is the expected behavior or new feature?**

should return the correct value even when the cell is accessed somewhere else

**Did this work in previous versions of our tool?  Which versions?**

in 0.94.2, i believe the same problem occurs but a different error is thrown : 
'Unknown function: ClosedXML.Excel.CalcEngine.CellRangeReference'

maybe i'm mistaken but a simple sum with a cell range work

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
  var wb = new XLWorkbook(@"bug_ClosedXML.xlsx");
  var ws = wb.Worksheet(1);
  var cellA = ws.Cell("L10");
  var cellB = ws.Cell("L11");
  Console.WriteLine(cellA.Value);
  cellB.FormulaA1 = "L10";
  Console.WriteLine(cellA.Value);
}
```
- [ [bug_ClosedXML.xlsx](https://github.com/ClosedXML/ClosedXML/files/3223670/bug_ClosedXML.xlsx)] I attached a sample spreadsheet

**Comment by igitur** [comment]
Many functions are still unsupported. We hope to get community contributions to help with this. But this is an important function, so hopefully I'll be able to look at it soon.

**Comment by igitur** [comment]
@pankraty fyi If I remember correctly, this the only, or one of very few, functions that have overloaded implementations in Excel.

**Comment by mms92** [comment]
this function IS supported, but in a way or another, having a cell accessing it's result make the interpreter to loose it

**Comment by igitur** [comment]
What makes you say that the formula is supported?

**Comment by mms92** [comment]
execute the code i gave you , only when the cell ( cell A ) containing INDEX function is referenced then ClosedXML interpreter don't recognise it , but as long as cell A is not referenced , the code work perfectly

**Comment by igitur** [comment]
The INDEX formula is definitely not implemented.

![image](https://user-images.githubusercontent.com/145854/58466971-0d6fe000-813b-11e9-9652-30b7fe583c9d.png)

What you're seeing in the first `Console.WriteLine` is the cached value, which is stored in the file. The cached value expires when you change any of the cells' values. Therefore, upon the 2nd `Console.WriteLine`, the formula is evaluated for the first time, and fails.

**Comment by mms92** [comment]
well , fuck

**Comment by igitur** [comment]
Post code example of what you mean.

**Comment by mms92** [comment]
the code is the same , you just need to edit the excel sheet so that a cell have the formula "=L10" in it
