### ISSUE TITLE
Contents of merged cells are not cleared if they are filled after the merge

### ISSUE THREAD

**Issue by Pankraty** [ClosedXML/ClosedXML#1229]
Huh. I've rebased my sparklines PR and several tests fail. One of them fails due to this bug

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

`develop`, after #1224 is merged

**What is the current behavior?**

```
ws1.Range("A2:A4").Merge().SetValue("Linear, Colorful 1, All markers, SameForAll scale");
```

This piece of code assigns a value to cells A2, A3 and A4. Previously, we would clear cells A3 and A4 during the loading. We could also do the merge _after_ the filling:
```
ws1.Range("A2:A4").SetValue("Linear, Colorful 1, All markers, SameForAll scale").Merge();
```
In both cases, A3 and A4 would end up empty.

But now, with the optimized loading, they have the value. We can even unmerge them in Excel:
![image](https://user-images.githubusercontent.com/19576939/58983319-9a740280-87e7-11e9-9faa-ae60a8273338.png)

**What is the expected behavior or new feature?**

Merged cells (except the first one) must remain empty no matter if we merge them after filling the value or the opposite - fill after they've been merged.
This is true for styling too: we should exclude merged cells from style propagation unless the entire merged range is affected. _(I have to provide more sufficient code sample for this, I know)_

**Did this work in previous versions of our tool?  Which versions?**

Yes, between #1031 and #1224 

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
            var workbook = new XLWorkbook();
            var ws1 = workbook.AddWorksheet();
            ws1.Range("A2:A4").Merge().SetValue("Test");
           Console.WriteLine(ws1.Cell("A2").Value);// Should be Test
           Console.WriteLine(ws1.Cell("A3").Value);// Should be empty. Actual: Test
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[SampleSparklines.xlsx](https://github.com/ClosedXML/ClosedXML/files/3258715/SampleSparklines.xlsx)
[SampleSparklines_Before1224.xlsx](https://github.com/ClosedXML/ClosedXML/files/3258748/SampleSparklines_Before1224.xlsx)

**Comment by Pankraty** [comment]
Another sample showing that this is a serious bug, not just inaccuracy:
```
var workbook = new XLWorkbook();
var ws1 = workbook.AddWorksheet();
ws1.Range("A2:A4").Merge().SetValue(1);
ws1.Cell("B1").FormulaA1 = "SUM(A:A)";
Console.WriteLine(ws1.Cell("B1").Value);// Should be 1. Actual 3
```

**Comment by igitur** [comment]
I have a fix ready for this.

But an additional thought has come to me. If we merge `A2:A4`, should we maybe not remove `A3` and `A4` from `Worksheet.Internals.CellsCollection`? I don't see any need for those cell entries any more.

**Comment by igitur** [comment]
Hmm, I see there is a specific test `UnmergedCellsPreserveStyle()` to ensure that this doesn't happen.
