### ISSUE TITLE
input string is not in a correct format

### ISSUE THREAD

**Issue by dbierbaum** [ClosedXML/ClosedXML#1244]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

I can open this file with Excel with no problems. I can also open it with SpreadsheetDocument spreadsheetDocument = SpreadsheetDocument.Open("TaxPreparation2.xlsm", false); without any errors. However, when I try to open it with ClosedXML I get the exception:

System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at ClosedXML.Excel.XLWorkbook.GetPtValue(String value)
   at ClosedXML.Excel.XLWorkbook.LoadShapeProperties[T](IXLDrawing`1 xlDrawing, XElement shape)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream)

**What is the expected behavior or new feature?**

open the file with no exceptions. i don't have any control over the file creation and I can't make manual edits with Excel before our app processes it so I'm hoping there is a code-based solution to this issue.

**Did this work in previous versions of our tool?  Which versions?**

This is the only version of the tool I have used

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
   var excelWorkbook = new XLWorkbook("TaxPreparation2.xlsm");
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

Note: the file extension was originally XLSM but I had to rename it to ZIP for github to accept it
[TaxPreparation2.zip](https://github.com/ClosedXML/ClosedXML/files/3364138/TaxPreparation2.zip)

**Comment by dbierbaum** [comment]
In case it helps, I debugged the source code and the issue is the value is "242px" but knownUnits only contains "pt", "in", "mm". So it sounds like we just need to add "px" to knownUnits and it will be removed from the value and parse correctly. I'm not sure what the numeric value for "px" should be in that dictionary though...

**Comment by Pankraty** [comment]
> I can open this file with Excel with no problems.

What version of Excel do you use? Excel 2016 claims the file is invalid. If I repair it with Excel, there is no more "242px" in it, and ClosedXML opens the repaired file with no issues.

**Comment by dbierbaum** [comment]
I apologize, I use "Excel" and "Open Office Calc" interchangeably because they normally behave the same, however it appears in this case they do not. Open Office opens the file with no problems but when I just tried actual Excel I saw the same behavior you did.

So from this I gather it would not be appropriate to add "px" to the list of knownUnits. However, since Open Office apparently ignores this error I wonder if ClosedXML could as well, rather then failing to open the file? 

I'm mainly asking in hopes that we can continue to use the official nuget package rather then a hacked version of the library to work around this, but this issue would definitely be a considered a feature request rather than a bug at this point.

Thank you for your time!

**Comment by Pankraty** [comment]
Turned out, the error Excel found had no relation to "px" in the comment style, there is something wrong with named ranges.

Either way, both Excel and LibreOffice do not accept `px` as a valid unit so I think it would be wrong to add it to the know units list (keeping aside, we would not be able to specify a correct conversion factor). Instead, I propose to ignore the values that cannot be parsed.
