### ISSUE TITLE
NU1605 package downgrade warning/error when System.IO.FileSystem 4.3.0 also installed

### ISSUE THREAD

**Issue by Arkiliknam** [ClosedXML/ClosedXML#1249]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.94.2 and 0.95.0-beta1

**What is the current behavior?**

When used in a project with NuGet references to System.IO.FileSystem 4.3.0, causes NuGet package warning nu1605 which is treated as error by default and causes build to fail.

**What is the expected behavior or new feature?**

To build without NuGet downgrade. We can overcome this by changing default behaviour of build when nu1605 is encountered, but would prefer not to.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

Install ClosedXML in a project. Install System.IO.FileSystem 4.3.0 in project. Attempt to build using dotnet.exe.

## UPDATE
Sorry for the lack of Code Sample. I went through this and it turns out it's when a specific combination of nuget packages are installed together, specifically ClosedXML and Dapper. See Code Sample below for project setup.

### Code Sample
A CSPROJ file with the following PackageReference set up. This is all you should need. When you build it, you will get the warning message which is treated as an error by default.
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.94.2" />
    <PackageReference Include="Dapper" Version="1.60.6" />
  </ItemGroup>
</Project>
```

### Build Errors

`C:\demo\ClosedXmlStandard.csproj : error NU1605: Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version.
C:\demo\ClosedXmlStandard.csproj : error NU1605:  ClosedXmlStandard -> ClosedXML 0.94.2 -> DocumentFormat.OpenXml 2.7.2 -> System.IO.Packaging 4.0.0 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.IO.FileSystem.Primitives (>= 4.3.0)
C:\demo\ClosedXmlStandard.csproj : error NU1605:  ClosedXmlStandard -> ClosedXML 0.94.2 -> DocumentFormat.OpenXml 2.7.2 -> System.IO.Packaging 4.0.0 -> System.IO.FileSystem.Primitives (>= 4.0.1)`

### Resolution
The inclusion of:

`<PackageReference Include="System.IO.FileSystem" Version="4.3.0" />`

in the package reference section of the project resolves this issue.

**Comment by igitur** [comment]
Invalid code sample.

**Comment by Arkiliknam** [comment]
> Invalid code sample.

That's because this is not a code issue. It's a build issue.

**Comment by igitur** [comment]
And I need some reproducible test case. It's your responsibility to provide that. I'm not sacrificing my previous free time trying to figure out how you ended up with a problem. Upload a minimal project to Github if you must. But I need something that reproduces the error. The issue template was quite clear about that.

**Comment by Arkiliknam** [comment]
@igitur , apologies for not providing the sample. I made a sample project to demonstrate the issue and updated the issue. Turns out it's a specific combination of nuget package references which cause this. For me, Dapper and ClosedXML. Also, including a packageReference to FileSystem resolves the issue.
