### ISSUE TITLE
Screws up references from second sheet to first sheet when first sheet is updated

### ISSUE THREAD

**Issue by mowmoth** [ClosedXML/ClosedXML#125]
I export data to a new file, creating Sheet1. Open the file in Excel, add a second sheet and reference the first sheet like this ='Sheeet1'!K2 which works fine. Then I call my update method, which deletes all data from Sheet1 (not the sheet itself) and writes new data to the same place. Even tried this with the same data. Open the file again and the reference now says ='Sheet1'!K-4 and #NAME?.

Edit: This doesn't make it any less odd, but the reference row after the update is substraced by 6 for some reason (e.g. 1 -> -5, 10 -> 4), which is exactly the amount of data rows in Sheet1

Since the data on the first sheet is formatted as a table I have to call worksheet.Table("table").Delete, which requires a XLShiftDeletedCells as parameter. I had it set to ShiftCellsUp which resulted in the changed references. However using ShiftCellsLeft throws an exception. Apparantly Excel can handle negative row numbers but not negative (?) column letters. Is there any reason, as to why the surrounding cells have to be shifted in the first place?

**Comment by igitur** [comment]
Please post a small code sample to reproduce the issue.

**Comment by mowmoth** [comment]
This is called on the exported data both during the initial creation of the file, as well as when a sheet is updated:

         private void InsertTable(IXLWorksheet ws)
        {
            var table = ws.RangeUsed().CreateTable("Table");
            table.Theme = XLTableTheme.TableStyleMedium9;
            ws.ColumnsUsed().AdjustToContents();
        }


And in the Update() method:

    ws.RangeUsed().Clear(XLClearOptions.ContentsAndFormats);
    ws.Table("Table").Delete(XLShiftDeletedCells.ShiftCellsUp);            
    Tables.Remove("Table");


I since removed the Delete() method and it seems to work now, as RangeUsed().Clear seems to get rid of the table as well. I was under the impression you needed to call Delete() but that turned out not to be the case. I'm still curious though why you would need to shift the surrounding cells when deleting a table.
