### ISSUE TITLE
Referencing Closed XML from Blazor

### ISSUE THREAD

**Issue by PhilPJL** [ClosedXML/ClosedXML#1251]
If I add ClosedXML to a Blazor app, linking will fail with an error message like: "The command 'dotnet' ...     ... exited with error code -532462766".
This is due a bug in Blazor [https://github.com/aspnet/AspNetCore/issues/11887](https://github.com/aspnet/AspNetCore/issues/11887) but this isn't scheduled to be fixed soon.

I'm using 

- Closed XML 0.95.0-beta1 and 0.94.2
- Visual Studio 2019 16.2.0 Preview 3

The issue can be worked around if all referenced packages support .NET Standard 2.
For example if I only add a reference to OpenXML 2.9.1 to a new Blazor app I get the same issue, but if I update to OpenXML 2.10.0-beta2 the issue goes away because 2.10 supports .NET Standard 2.

I've tried updating all of the components referenced by ClosedXML to their latest versions but the linker issue still exists.  

Is it possible to ensure all components referenced by ClosedXML support .NET Standard 2?

**Comment by igitur** [comment]
Which components do not reference netstandard20?

**Comment by PhilPJL** [comment]
I may be making a wrong assumption about .NET Standard 2 so it's better if I demonstrate.  If I add OpenXML 2.9.1 to a Blazor app I get this

![image](https://user-images.githubusercontent.com/271656/61189278-14b76280-a683-11e9-902b-cae622b5a4bd.png)

and then the app won't link due (I'm assuming) to the bug referenced earlier.

If I instead add OpenXML 2.10.0-beta2 I get
![image](https://user-images.githubusercontent.com/271656/61189291-3d3f5c80-a683-11e9-889f-ce76ddc86a0e.png)

and then the app does link successfully.

The same problem with Nethereum.Web3 which references Newtonsoft.JSON 10.0.3.  Here if I explicitly reference Newtonsoft.JSON 12 this fixes the issue.

When referencing ClosedXML the list of dependencies is a lot longer.  I wasn't able to work around the issue by updating FastMember 1.3 -> 1.5, Open XML -> 2.10.0 and ExcelNumberFormat 1.0.3 -> 1.0.7.

**Comment by PhilPJL** [comment]
@igitur I suspect the problem is the dependency on system.drawing.common.  What's the possibility of eliminating that dependency?

**Comment by igitur** [comment]
`System.Drawing.Common` is used to determine the width of text in a cell (given their font, size, etc) and hence to adjust the width of a column when calling `.AdjustToContents()`. Therefore there is no possibility of eliminating the dependency.

I'll repeat my question: Which components do not reference netstandard20?

**Comment by PhilPJL** [comment]
I'll close this issue since it's not something you can fix.
The issue is that System.Drawing.Common in Nuget says it supports .NET Standard 2.0 with no dependencies. It doesn't have any managed dependencies but does have native dependencies [https://github.com/mono/mono/issues/15806](https://github.com/mono/mono/issues/15806).  This causes Blazor to fail to link when I add ClosedXML (orany other package which references System.Drawing.Common).
