### ISSUE TITLE
concatenate() regression

### ISSUE THREAD

**Issue by dizzzan** [ClosedXML/ClosedXML#1264]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

develop branch, broken in #1166

**What is the current behavior?**

CONCATENATE function throws CellValueException when passed a list of single cells (e.g. CONCATENATE(A1, B1)

**What is the expected behavior or new feature?**

Concatenation of cells should evaluate as it does in Excel.

In Excel, concatenate() on a range will sometimes return a value in the range, but I don't understand the logic. For instance, concatenate(A1:C1) returns B1 value, but A1:B2 throws  #VALUE! (see attached)

**Did this work in previous versions of our tool?  Which versions?**

Yes, 0.94.2

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
     	using (var xls = new XLWorkbook())
	{
		var sheet = xls.AddWorksheet();
		sheet.Cell("A1").Value = "Hello";
		sheet.Cell("B1").Value = "World";
		
		Console.WriteLine(sheet.Evaluate("=CONCATENATE(\"Hello\", \"World\")"));
		Console.WriteLine(sheet.Evaluate("=CONCATENATE(A1, B1)")); // throws, incorrectly
		Console.WriteLine(sheet.Evaluate("=CONCATENATE(A1:B1)")); // throws, correctly
		
		Console.WriteLine(sheet.Evaluate("=CONCAT(\"Hello\", \"World\")"));
		Console.WriteLine(sheet.Evaluate("=CONCAT(A1, B1)"));
		Console.WriteLine(sheet.Evaluate("=CONCAT(A1:B1)"));
	
	}

}
```
- [ x ] I attached a sample spreadsheet.  (You can drag files on to this issue)

[concat examples.xlsx](https://github.com/ClosedXML/ClosedXML/files/3453973/concat.examples.xlsx)

**Comment by igitur** [comment]
Thanks for following the issue template. Makes it a lot easier to fix.
