### ISSUE TITLE
How to insert Datable values using WorkBook.Cell.Range

### ISSUE THREAD

**Issue by juliep10** [ClosedXML/ClosedXML#1265]
Hi,
I am having values in Datatable Object.
Dim ar1(dt.Rows.Count, iStartCol - 3) As String

 **ws.Range(ws.Cell(iSTARTROW, 2),
                     ws.Cell(iSTARTROW + dt.Rows.Count, iStartCol - 1)
                    ).Value = ar1**
Below are the run time values of passed objects to above code.
iSTARTROW=60
iSTARTROW + dt.Rows.Count=110
iStartCol=17

 I am getting Error: Object reference not set to an instance of an object. PFA image for ar1 object value. Please let me know how it will work.
![Code](https://user-images.githubusercontent.com/52920838/62450136-5c647200-b789-11e9-88cc-fc9b726713f0.PNG)

**Comment by juliep10** [comment]
> Hi,
> I am having values in Datatable Object.
> Dim ar1(dt.Rows.Count, iStartCol - 3) As String
> 
> **ws.Range(ws.Cell(iSTARTROW, 2), ws.Cell(iSTARTROW + dt.Rows.Count, iStartCol - 1) ).Value = ar1**
> Below are the run time values of passed objects to above code.
> iSTARTROW=60
> iSTARTROW + dt.Rows.Count=110
> iStartCol=17
> 
> I am getting Error: Object reference not set to an instance of an object. PFA image for ar1 object value. Please let me know how it will work.
> ![Code](https://user-images.githubusercontent.com/52920838/62450136-5c647200-b789-11e9-88cc-fc9b726713f0.PNG)

Please Reply back to me.IT's very urgent.

**Comment by igitur** [comment]
Complete the [full issue template](https://github.com/ClosedXML/ClosedXML/blob/develop/.github/ISSUE_TEMPLATE.md), as requested.
