### ISSUE TITLE
.AdjustToContents() not working in case applying to Japanese

### ISSUE THREAD

**Issue by EllenEast** [ClosedXML/ClosedXML#1272]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

.AdjustToContents() not working in case applying to Japanese

**What is the expected behavior or new feature?**

.AdjustToContents()  works fine in case applying to Japanese as well as to English

**Did this work in previous versions of our tool?  Which versions?**

No

**Code to reproduce problem:**
```c#
public void Main()
{
    var wb = new XLWorkbook();
    var ws = wb.AddWorksheet("test");

    // In case applying to English
    // ws.Cell(1, 1).Value = "Hey! Your thumb is in my soup!";
    // ws.Cell(1, 2).Value = "Don't worry, sir. Your soup wasn't that hot.";

    // In case applying to Japanese
    ws.Cell(1, 1).Value = "ちょっと！あなたの親指が私のスープに入ってるんだけど！";
    ws.Cell(1, 2).Value = "大丈夫です。スープはそんなに熱くありません。";

    ws.Columns(1, 2).AdjustToContents();
    wb.SaveAs(@"D:\temp\test.xlsx");
}
```

It works fine in case applying to English.
![AdjustToContents_English](https://user-images.githubusercontent.com/40677109/63401808-aa2cdb80-c413-11e9-838a-8cbc525bdd1e.png)

It doesn't work fine in case applying to Japanese.
![AdjustToContents_Japanese](https://user-images.githubusercontent.com/40677109/63401818-aef18f80-c413-11e9-8235-1169aa837af3.png)

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

Thank you for your great efforts.

**Comment by igitur** [comment]
The default font for a new workbook is `Calibri` and as far as I know that font doesn't support the Japanese characters. Have you tried explicitly setting the cells to a font that supports Japanese characters, e.g. `MS Gothic` ?

**Comment by EllenEast** [comment]
Thank you for your reply and advice.

As you say, setting the cells to a Japanese font "游ゴシック" or "Yu Gothic", which is the default font of workbooks of Excel 2016 of Japanese version, before using AdjustToContents() has solved the problem. Thank you very much again!
```c#
//ws.Style.Font.FontName = "Yu Gothic";
ws.Style.Font.FontName = "游ゴシック";
```
![AdjustToContents_Japanese2](https://user-images.githubusercontent.com/40677109/63504506-afba1c80-c50c-11e9-93fb-99205d412d7f.png)

By the way, I don't know why but setting the cells to "ＭＳ ゴシック" or "MS Gothic" does not work fine very much.
```c#
//ws.Style.Font.FontName = "MS Gothic";
ws.Style.Font.FontName = "ＭＳ ゴシック";
```
![AdjustToContents_Japanese3](https://user-images.githubusercontent.com/40677109/63504655-f60f7b80-c50c-11e9-9b14-8017d32f8963.png)

But it seems many other Japanese fonts work fine. So I think this problem  may be ignorable.

**Comment by igitur** [comment]
Glad it's solved.
