### ISSUE TITLE
Date formatting does not support AM/PM designation from C# format

### ISSUE THREAD

**Issue by kendallb** [ClosedXML/ClosedXML#1273]
## Read and complete the full issue template

- [x] Bug

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95 beta2

**What is the current behavior?**

If you set a date format for a cell to this:

M/d/yyyy h:mm:ss tt

it simply returns the format string when you call GetFormattedString() on the cell. If you load the Excel the date is formatted like so:

10/16/2017 15:05:00 tt

rather than the correct value of:

10/16/2017  3:05:00 PM

**What is the expected behavior?**

It should convert to the format to the AM/PM format style used by Excel, and correctly format it both in the resulting Excel file and when you call GetFormattedString().

**Did this work in previous versions of our tool?  Which versions?**

Yes

Not sure which version, it was broke in 0.90.0 so I suspect a version prior to that. My unit test used to pass, but now it does not.

## Reproducibility

Please see:

https://github.com/kendallb/ExcelHelper/blob/master/src/ExcelHelper.Tests/ExcelWriterTests.cs

uncomment line 127 and run run WriteCellTest(). It will fail. Attached is the Excel file generated for the test, but you can also generate it to a temp directory by defining WRITE_TEST_FILE when you build the code.

[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/3526733/test.xlsx)

**Comment by igitur** [comment]
ClosedXML now uses https://github.com/andersnm/ExcelNumberFormat for formatting of numbers. Please check first whether this is a shortcoming of that library or whether it's ClosedXML-specific. If the issue is in ExcelNumberFormat, please log an issue there.

**Comment by kendallb** [comment]
Could be an issue in that library. I know the last version I was using that was working was using ExcelNumberFormat also. I could try back leveling that library to see if it changes anything related to this.

**Comment by igitur** [comment]
Have you upgraded ExcelNumberFormat to its latest version?

**Comment by kendallb** [comment]
Yes I upgraded all the packages at the same time.

**Comment by Pankraty** [comment]
`tt` is a valid format specifier in .Net (https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings) but not in Excel (https://support.office.com/en-us/article/review-guidelines-for-customizing-a-number-format-c0a1d1fa-d3f4-4018-96b7-9c9354dd99f5). Excel uses `AM/PM` in the format string, and if you specify `tt` in Excel it will output it as-is:

![image](https://user-images.githubusercontent.com/19576939/76427838-4d503d00-63c6-11ea-8f46-d42ea48cdb31.png)

So the current behavior of ClosedXML (thanks to ExcelNumberFormat) is more correct than it was before.

**Comment by kendallb** [comment]
Please do not close a ticket when you clearly do not understand the context! The whole point of this function is to convert formatting from .net style to excel style, so the tt format which is valid in .net needs to be converted to the AM/PM style as this bug report says.

**Comment by igitur** [comment]
Sorry @kendallb , I disagree. The function's purpose was never to support .NET format strings. It was always a way to format cells according to Excel format strings. The dependency on ExcelNumberFormat was later added in order to support the `IXLCell.GetFormattedString()` method.

**Comment by kendallb** [comment]
Well it's still broken even if we want to use Excel format strings because it does not get the AM/PM format correct (it leaves it in 24 hour format). Changing the format string to:

M/d/yyyy h:mm:ss AM/PM

produces the following failure:

Expected:<10/16/2017 3:05:00 PM>. Actual:<10/16/2017 15:05:00 PM>.

**Comment by Pankraty** [comment]
> Expected:<10/16/2017 3:05:00 PM>. Actual:<10/16/2017 15:05:00 PM>.

This has been fixed in ExcelNumberFormat 1.0.8. In the scope of #1364 we are going to upgrade the dependency to 1.0.9 (or even 1.0.10 if it is released) and that problem will be gone.

**Comment by kendallb** [comment]
I will update my project and see if that resolves it.

**Comment by kendallb** [comment]
That does fix the AM/PM issue so my project is updated.
