### ISSUE TITLE
Long date formatting produces incorrect result in GetFormattedString()

### ISSUE THREAD

**Issue by kendallb** [ClosedXML/ClosedXML#1274]
## Read and complete the full issue template

- [x] Bug

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95 beta2

**What is the current behavior?**

If you set a date format for a cell to this:

dddd, MMMM d, yyyy

when you call GetFormattedString() on the cell it drops all the commas. If you load the Excel the date is formatted like so:

Monday, October 16, 2017

but GetFormattedString() returns this:

Monday October 16 2017

**What is the expected behavior?**

It should not drop the commas.

**Did this work in previous versions of our tool?  Which versions?**

Yes, it worked correctly in 0.90 and I noticed in broken in 0.94.2 and 0.95 beta2.

## Reproducibility

Please see:

https://github.com/kendallb/ExcelHelper/blob/master/src/ExcelHelper.Tests/ExcelWriterTests.cs

uncomment line 135 and run run WriteCellTest(). It will fail. Attached is the Excel file generated for the test, but you can also generate it to a temp directory by defining WRITE_TEST_FILE when you build the code.

[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/3526760/test.xlsx)

**Comment by igitur** [comment]
ClosedXML now uses https://github.com/andersnm/ExcelNumberFormat for formatting of numbers. Please check first whether this is a shortcoming of that library or whether it's ClosedXML-specific. If the issue is in ExcelNumberFormat, please log an issue there.

**Comment by andersnm** [comment]
Yes, this is a bug in ExcelNumberFormat

https://github.com/andersnm/ExcelNumberFormat/issues/22
