### ISSUE TITLE
Reading a file many times using "using(var ~)" causes a memory leak.

### ISSUE THREAD

**Issue by ShinoharaTa** [ClosedXML/ClosedXML#1276]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.94.2

**What is the current behavior?**

Opening a file many times causes a memory leak and an exception occurs.
Exception "OutOfMemoryException." occurs.

**What is the expected behavior or new feature?**

Complete this.

**Did this work in previous versions of our tool?  Which versions?**

Not checked.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // test.xlsx is in styled cells and 20,000 Records.
    // Filesize in about 30MBytes.
    using (var workbook = new XLWorkbook("test.xlsx"))
    {
        // not process
    }

    using (var workbook = new XLWorkbook("test.xlsx"))
    {
        // not process
    }

    using (var workbook = new XLWorkbook("test.xlsx"))
    {
        // not process
    }
    // Repeat this
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by Pankraty** [comment]
You forgot to attach the file.

**Comment by ShinoharaTa** [comment]
[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/3529557/test.xlsx)

This file.
It's cells value is changed test string.
Cell styles is not changed.

**Comment by Pankraty** [comment]
@ShinoharaTa please check the binaries from there https://ci.appveyor.com/project/ClosedXML/closedxml/builds/26882694/job/3jqmmvo30ls7o50j/artifacts

Does it solve your issue?

**Comment by ShinoharaTa** [comment]
I'll check in Japan time tomorrow around 10:00.
Then contact the result here.

**Comment by ShinoharaTa** [comment]
Looks good.
Right now, I checked result OK.
Thank you for your support. I am grateful to you.
