### ISSUE TITLE
new XLWorkbook(ExcelFileFullName) hangs with certain file

### ISSUE THREAD

**Issue by Karluzo** [ClosedXML/ClosedXML#1277]
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

the command
`_wb = new XLWorkbook(ExcelFileFullName)`

hangs with certain XLSM file. The file can be opened normally in Excel with no warning or problem.

**What is the expected behavior or new feature?**

Fix or workaround

**Did this work in previous versions of our tool?  Which versions?**

Never checked this.

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
      var _wb = new XLWorkbook(ExcelFileFullName)}
}
```

[Strkodrviny3.xlsx](https://github.com/ClosedXML/ClosedXML/files/3529776/Strkodrviny3.xlsx)

**Comment by igitur** [comment]
I can't reproduce this. Try the latest beta version, please.

**Comment by Karluzo** [comment]
Compiled 0.95.0 from GitHub, When I copy ClosedXML.dll 0.95.0 to my project, it works. When I compile it with NuGet version, it hangs. Using .NET 4.5.1 in that procject, so I have copied the net40 dll build.

**Comment by igitur** [comment]
Still can't reproduce. I tried a .NET 4.5.1 project referencing ClosedXML 0.95.0-beta2 from NuGet. Please set up a minimal project from scratch in a Github repo to illlustrate the problem.

**Comment by Karluzo** [comment]
I see, I did not try the beta from NuGet, the problem shows only in 0.94.2 version.

**Comment by Karluzo** [comment]
In 0.95.0-beta2 in ClosedXML.Excel.XLWorkbook.CreateParts (Save) I get "Error generating comments".

**Comment by igitur** [comment]
That's unrelated to your original report, so create a new issue please.
