### ISSUE TITLE
SQLite

### ISSUE THREAD

**Issue by 73sergey73** [ClosedXML/ClosedXML#1279]
Hey. How can I get all the data in Excel from a SQLite database? According to the finished template!

**Comment by Pankraty** [comment]
Try this
![image](https://user-images.githubusercontent.com/19576939/63640963-c5b81080-c6b7-11e9-8254-a10b121c1ab3.png)
This will require installing ODBC driver for SQLite though and finishing the template accordingly.

**Comment by b0bi79** [comment]
You can also use [ClosedXML.Report](https://github.com/ClosedXML/ClosedXML.Report) library.
