### ISSUE TITLE
Throws "Error generating comments" when containing any vml elements

### ISSUE THREAD

**Issue by f45t** [ClosedXML/ClosedXML#1285]
We ran in an error introduced in the following commit:

https://github.com/ClosedXML/ClosedXML/commit/4a9276186543064856ded6998b452e3e4f5d4c59

If you use a template with a contained VML element, e.g. a Button it fails in

ClosedXML/Excel/XLWorkbook_Save.cs

at

if (worksheetHasComments != hasAnyVmlElements)
  throw new ApplicationException("Error generating comments");

I attached a sample spreadsheet to reproduce this behavior.

[ClosedXmlErrorExample.zip](https://github.com/ClosedXML/ClosedXML/files/3584357/ClosedXmlErrorExample.zip)

**Comment by Project579** [comment]
I would like to bump this issue as this exception prevents me from using CloseXML at all.

**Comment by igitur** [comment]
Sorry, I don't understand. What do you mean by "bump this issue"?

**Comment by Project579** [comment]
The last update was some time ago, thought it was never going to be resolved.
