### ISSUE TITLE
Query Sheets 

### ISSUE THREAD

**Issue by KingMarney** [ClosedXML/ClosedXML#129]
More of a question in issue. Can you query the table getting the row number. Then apply a format to the row number and define columns.

**Comment by igitur** [comment]
Sorry, I don't really understand. Do you want to apply a conditional format based on the row number in a table?

Or create a mockup in Excel and attach - to illustrate what you want.

**Comment by KingMarney** [comment]
I wanted to search the xlworksheet. Example search B1all cells containing X
then add background to those cells

**Comment by KingMarney** [comment]
![image](https://cloud.githubusercontent.com/assets/2945887/21266018/39324b62-c372-11e6-8027-da39853e8a76.png)

**Comment by vbjay** [comment]
Apply conditional formatting. You don't do the searching, excel does.

**Comment by KingMarney** [comment]
I have added the conditional formatting to the cells. But the upload from the size take too long. I would think that programming the format of all existing cell for desc, the upload speed and add some time to program.  

![image](https://cloud.githubusercontent.com/assets/2945887/21316022/e4fef632-c5cc-11e6-820e-b5f9077a4fbd.png)

Lets look that this example Search or Find "3" in column "A" highlight the row next adjacent rows for a range.

**Comment by jahav** [comment]
Closing, stale.
