### ISSUE TITLE
AllowNone() property missing in version 0.94.2 build version

### ISSUE THREAD

**Issue by juliep10** [ClosedXML/ClosedXML#1295]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.94.2

**What is the current behavior?**
AllowNone() property missing in version 0.94.2 build version

**What is the expected behavior or new feature?**
How to make excel sheet non editable so that user cannot do any modification.

**Did this work in previous versions of our tool?  Which versions?**

Yes- 0.95.0-beta1

## Reproducibility
 Yes, Not working in 0.94.2 version.

```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Full code sample required as *always*.

**Comment by juliep10** [comment]
With 0.95.0-beta1 build version i am able to get the below property.
Dim Prtc As IXLSheetProtection = ws.Protection()
        Prtc.AllowNone()

but when i am using 0.84.3 build version i am not able to get this property.

**Comment by Pankraty** [comment]
In 0.95.* `IXLSheetProtection` has been completely refactored (see #1038 and release notes for 0.95-beta1 https://github.com/ClosedXML/ClosedXML/releases/tag/0.95.0-beta1). No surprise, this API does not work in 0.94.2 or 0.84.3 - it simply did not exist at that time.
