### ISSUE TITLE
Why are all number types converted into double?

### ISSUE THREAD

**Issue by monoblaine** [ClosedXML/ClosedXML#130]
In PR #47 there's an interesting change in line [269](https://github.com/ClosedXML/ClosedXML/pull/47/files#diff-3b8a562c15b0aca901df66d96df87e10R269)

```cs
_dataType = XLCellValues.Number;
_cellValue = ((Double)Convert.ChangeType(value, typeof (Double))).ToInvariantString();
```

A similar issue is present in lines [346](https://github.com/ClosedXML/ClosedXML/pull/47/files#diff-3b8a562c15b0aca901df66d96df87e10R346), [424](https://github.com/ClosedXML/ClosedXML/pull/47/files#diff-3b8a562c15b0aca901df66d96df87e10R424) and [858](https://github.com/ClosedXML/ClosedXML/pull/47/files#diff-3b8a562c15b0aca901df66d96df87e10R858) (maybe some more)

Why does the value of a cell get converted into `double` if the data type of the cell is `XLCellValues.Number`? For instance, converting a decimal number to double may lead to accuracy problems.

**Comment by vbjay** [comment]
.Net may have decimal. However, what does Excel support?

**Comment by vbjay** [comment]
https://blogs.office.com/2008/04/10/understanding-floating-point-precision-aka-why-does-excel-give-me-seemingly-wrong-answers/.
.Net double is IEEE 754 complient.

**Comment by monoblaine** [comment]
So, it's safe to assume that an Excel number is equal to a c# double value. Thanks for the clarification @vbjay!
