### ISSUE TITLE
[How to]Get Rows.Height from ClosedXML

### ISSUE THREAD

**Issue by shun198914** [ClosedXML/ClosedXML#1302]
I'm Shun.
I want to get the Worksheet Rows.Height use ClosedXML. 
but I can't get it because the property is readonly.

Please let me know how to get Rows.Height use ClosedXML.

**Code to reproduce problem:**
```VB.NET
Dim xlspath = "C:\test.xlsx"
Using objRestWorkbook = New XLWorkbook(xlspath)

    Dim objTemplateSheet As IXLWorksheet = objRestWorkbook.Worksheet("Template")
    Dim newArray As New ArrayList

    For row = 1 To objTemplateSheet.Rows.Count
          newArray.Add(objTemplateSheet(row).Height)
    Next row

End Using
```

**Comment by Pankraty** [comment]
> I want to get the Worksheet Rows.Height use ClosedXML.
but I can't get it because the property is readonly.

Did you mean it is write-only? IXLRows is write-only indeed, because rows in the collection may have different heights. But each separate IXLRow in the collection has property Height which is available for both reading and writing.

**Comment by shun198914** [comment]
Hi Pankraty
Thank you. I understand your advice!
