### ISSUE TITLE
When an Id of a first sheet is 2

### ISSUE THREAD

**Issue by yooontheearth** [ClosedXML/ClosedXML#131]
Hi,

I found this behavior.  Suppose I have a following file which has only one sheet and its id is 2.
[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/665583/test.xlsx)

Then run the code below which just opens a file and get a first sheet then saves it as other file.
```
using (var wb = new XLWorkbook("test.xlsx"))
{
  var sheet = wb.Worksheet(1);
  wb.SaveAs("test saved.xlsx");
}
```

When you open the saved file, it gives me "Your excel file is broken and will be repaired" message. Then I checked the saved file's \xl\workbook.xml and I found the following duplicated tags. 

```
<x:sheets>
<x:sheet name="sheet name" sheetId="2" r:id="rId2" />
<x:sheet name="sheet name" sheetId="2" r:id="rId1" />
</x:sheets>
```

If I change the sheetId to 1 before running the code above, it doesn't give the error I mentioned.

**Comment by igitur** [comment]
#127 fixes this.

**Comment by yooontheearth** [comment]
Oh that's good to know. Thanks
