### ISSUE TITLE
ClosedXML has a hard reference to OpenXML. If added to an existing project that doesn't have AutoGenerateBindingRedirects set to true results in a runtime error if OpenXML is updated.

### ISSUE THREAD

**Issue by MarkStega** [ClosedXML/ClosedXML#1310]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug (Documentation lacking)
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

Adding ClosedXML to an existing project that doesn't have
```
<autogeneratebindingredirects>true</autogeneratebindingredirects>
```
will result in a runtime failure if OpenXML has been upgraded to a newer version than 2.7.2

**What is the expected behavior or new feature?**

The need to have autogeneratebindingredirects set to true to allow the explicit reference to OpenXML 2.7.2 to be resolved by later versions needs to be documented.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
//
// This project demonstrates the hard reference to Open XML2.7.2
// ClosedXML was added to an existing project that did not have generated binding redirects
// Build, run, and fail due to the lack of OXML 2.7.2
//
//  To fix:
//  1) Add the setting <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
//  2) Delete bin directory
//  3) Build, run, succeed due to the binding redirects that get added to the .exe.config
//

namespace BrokenClosedXML
{
    class Program
    {
        private static void Main(string[] args)
        {
            using (var wb = new ClosedXML.Excel.XLWorkbook())
            {
                var ws = wb.AddWorksheet("sheet1");
                ws.Cell("A1").Value = 100;

                wb.SaveAs(@"c:\temp\test.xlsx");
            }
        }
    }
}
```
The project file
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{0773A8CF-5834-42D2-9A27-BC13BD11F591}</ProjectGuid>
    <OutputType>Exe</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>BrokenClosedXML</RootNamespace>
    <AssemblyName>BrokenClosedXML</AssemblyName>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <TargetFrameworkProfile />
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="ClosedXML, Version=0.94.2.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\ClosedXML.0.94.2\lib\net46\ClosedXML.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="DocumentFormat.OpenXml, Version=2.9.1.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17, processorArchitecture=MSIL">
      <HintPath>..\packages\DocumentFormat.OpenXml.2.9.1\lib\net46\DocumentFormat.OpenXml.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="ExcelNumberFormat, Version=1.0.7.0, Culture=neutral, PublicKeyToken=23c6f5d73be07eca, processorArchitecture=MSIL">
      <HintPath>..\packages\ExcelNumberFormat.1.0.7\lib\net20\ExcelNumberFormat.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="FastMember, Version=1.5.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\FastMember.1.5.0\lib\net461\FastMember.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.IO.FileSystem.Primitives">
      <HintPath>..\packages\System.IO.FileSystem.Primitives.4.3.0\lib\net46\System.IO.FileSystem.Primitives.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System.IO.Packaging, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\packages\System.IO.Packaging.4.6.0\lib\net46\System.IO.Packaging.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
    <None Include="packages.config" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>
```
What is needed in that first property group is
```
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
```
With that added the resulting .exe.config has the binding redirects to allow a later version of OpenXML to be resolved to the hardcoded request for OpenXML 2.7.2 as shown here:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="ExcelNumberFormat" publicKeyToken="23c6f5d73be07eca" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.0.7.0" newVersion="1.0.7.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="DocumentFormat.OpenXml" publicKeyToken="8fb06cb64d019a17" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.10.0.0" newVersion="2.10.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by igitur** [comment]
Ok, so from what I understand here is that no fix is required in ClosedXML. You just want the `AutoGenerateBindingRedirects` documented?

**Comment by MarkStega** [comment]
Correct - I had this issue occur to me in a real life project and it took me forever to understand the issue.
I believe that there may be an alternative in that ClosedXML itself might be built in a way that just indicated that OpenXML has to be 2.7.2 or higher, but frankly, I don't know how to do that.

**Comment by igitur** [comment]
Since when does bindings not auto-generate by default? I've never used anything higher than .NET 4.7.2 and have never had the problem. So is it an issue with .NET 4.8 or due to something else?

Where exactly do you suggest to add the documentation? In the README or on the Wiki, under FAQs maybe? In fact, you can help out by submitting a pull request with your suggestion. Thanks

**Comment by Dattel** [comment]
Currently i'm faced with the same issue using .net 4.7.2 on a web-application on IIS.... 
So is there any chance, that ClosedXML will reference the newer OpenXML version in near future?
I fear of changing AutoGenerateBindingRedirects on that project because my project consists of multiple projects. Or is that the only solution?

**Comment by igitur** [comment]
@Dattel No, we'll keep referencing the minimum required version that we need. You can add a manual binding redirect for OpenXML only, if you need to.

**Comment by MarkStega** [comment]
It was due to adding ClosedXML into a project that was started almost 8 years ago that went from VS2012 to VS2013 to VS2015 to VS2017 to VS2019 with at least that number of .NET framework versions. The origin of the project is lost to time. But I did find that the addition of AutoBindingRedirects as a default in a project was with .NET 4.5.1 and VS2013 which were released in
 October 2013. About 10 of the 24 projects in my solution do not have the redirects enabled and I was unfortunate in that the report writer project that uses ClosedXML was one of those.

I'll take a shot at the documentation and generate a PR but it likely won't be until Monday.

**Comment by igitur** [comment]
@MarkStega I would still like to replicate your issue first, and with the files you have given, I can't. You have omitted crucial files anyway, e.g. `app.config`. Can you zip your entire project and upload here. Exclude the `bin` and `obj` folders.

**Comment by MarkStega** [comment]
[BrokenClosedXML.zip](https://github.com/ClosedXML/ClosedXML/files/3854625/BrokenClosedXML.zip)

**Comment by Maritims** [comment]
I too recently experienced this issue and spent some time attempting to figure out who the culprit was. I checked the dependency list of ClosedXML in nuget and found that it requires >=2.7.2 of DocumentFormat.OpenXml, but I'll receive a FileLoadException if I upgrade DocumentFormat.OpenXml.

How is one supposed to know that a binding redirect is required for ClosedXML to work if the project references a newer version of DocumentFormat.OpenXml?

**Comment by igitur** [comment]
Binding redirects is a standard requirement of .NET for allowing version upgrade of strongly typed assemblies. How is one supposed to know? Probably via the Microsoft .NET documentation.
