### ISSUE TITLE
Not all named ranges are found/accessible

### ISSUE THREAD

**Issue by genehemias** [ClosedXML/ClosedXML#1312]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.94.2.0

**What is the current behavior?**

Accessing an existing .xlsx file having 2 named ranges (one created with Excel's "Formulas -> Define Name" feature, the other created by manually providing a name in Excel's Name Box), ClosedXML.Excel.XLWorkbook.NamedRanges only contains the first named range. The manually-named range is not in the NamedRanges collection, but is visible in Excel's Name Manager.

**What is the expected behavior or new feature?**

All named ranges should be accessible via XLWorkbook.NamedRanges

**Did this work in previous versions of our tool?  Which versions?**

unknown

## Reproducibility

**Code to reproduce problem:**
```c#
using ClosedXML.Excel;
public void Main()
{
    XLWorkbook wkbk = new XLWorkbook("./namedRangeTest.xlsx");
    foreach (IXLNamedRange namedRange in wkbk.NamedRanges)
    {
        Console.Writeline($"{namedRange.Name} = {namedRange.RefersTo}");
        //expectation: 2 named ranges should be found
        //actual: only one named range is found
    }
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[namedRangeTest.xlsx](https://github.com/ClosedXML/ClosedXML/files/3881357/namedRangeTest.xlsx)

**Comment by Pankraty** [comment]
Named ranges in may have either a workbook or a worksheet scope. In Excel, they are displayed all together, but in ClosedXML they are presented separately.

So if you change your code like this 
```
foreach (IXLNamedRange namedRange in wkbk.NamedRanges)
{
    Console.WriteLine($"{namedRange.Name} = {namedRange.RefersTo}");
}

foreach (var wsNamedRange in wkbk.Worksheets.SelectMany(ws => ws.NamedRanges))
{
    Console.WriteLine($"{wsNamedRange.Name} = {wsNamedRange.RefersTo}");
}
```
\- you'll get the desired result:

```
formulatest = Sheet1!$A$1:$A$3
dynamic = Sheet1!$C$1:$D$4
```

**Comment by Pankraty** [comment]
By the way, a special thank you for following the issue template!
