### ISSUE TITLE
When a cell's text begins with a new line code and Japanese Kanji

### ISSUE THREAD

**Issue by yooontheearth** [ClosedXML/ClosedXML#132]
Hi,

The following file has a cell whose text begins with a new line code and Japanese Kanji. 
[test new line.xlsx](https://github.com/ClosedXML/ClosedXML/files/665602/test.new.line.xlsx)

Then run the code below which just opens a file and saves it as other file.
```
using (var wb = new XLWorkbook("test new line.xlsx"))
{
  wb.SaveAs("test saved.xlsx");
}
```

When you open the saved file, it gives "Your excel file is broken and will be repaired" message. Then repairing process removes the new line code at the beginning.

If I remove the new line code at the beginning of the cell  before running the code above, it doesn't give the error I mentioned.

**Comment by igitur** [comment]
Ok, will look into it.

**Comment by igitur** [comment]
The problem isn't the newlines, but some additional text, called a phonetic run. See this image:
![image](https://cloud.githubusercontent.com/assets/145854/21643178/9844e458-d28f-11e6-985c-422e315df88d.png)

According to https://msdn.microsoft.com/it-it/library/documentformat.openxml.spreadsheet.phoneticproperties(v=office.14).aspx  :
```
This element represents a collection of phonetic properties that affect the display of phonetic text for this String Item (si).
Phonetic text is used to give hints as to the pronunciation of an East Asian language, and the hints are displayed as text within the spreadsheet cells across the top portion of the cell. Since the phonetic hints are text, every phonetic hint is expressed as a phonetic run (rPh), and these properties specify how to display that phonetic run.
```
Of course I don't understand Japanese, so I'm relying on you to tell me whether you really did intend for that phonetic text to be included. ClosedXML doesn't have support for this yet, but I should be able to get it to at least generate a valid file.

**Comment by yooontheearth** [comment]
Oh it's interesting. I didn't know about the phonetic run. I didn't intend to include it on purpose but it muse be it's automatically included when I type Japanese Kanji on excel. It's because to type Japanese Kanji, you need to type Japanese Hiragana or Japanese Katakana first then transform to Japanese Kanji with an input method editor (aka IME), and the phonetic run seems to take Japanese Hiragana for itself.

The picture you posted is "kanji" in Katakana form, and the Japanese Kanji I typed on the excel file is "kanji" in Kanji form. 

Hope this clears a little bit how Japanese language works ;)

**Comment by igitur** [comment]
Are you able to remove the kanji from the Excel file and if so, does that solve your problem? Eventually, we'll have to implement the phonetic runs, but I consider this lower priority than our other future enhancements.

**Comment by yooontheearth** [comment]
Nah, that's not possible in Japanese language not using Kanji since it's one of the fundamental parts of the language. Anyway, if you don't have time for fixing it for now, it's alright because I know how to avoid the error message as I reported in the first comment.

**Comment by jahav** [comment]
The root cause seems to be that tag `t` is missing attribute `xml:space="preserve"`.
The phonetic run uses sb=1 eb=3 (start index = 1, end index = 3). The problem is that kaji text has only two glyphs (when stripped of whitespaces), so end index 3 is out-of-bounds.

When I either
* add the attribute `xml:space="preserve"`
* change end index to 2

Excel loads the file. The phonetic runs are displayed only when changed to japanese, so for different locale are not displayed.
