### ISSUE TITLE
Insert "True" "False" as cell value written as "TRUE" "FALSE"

### ISSUE THREAD

**Issue by dojo90** [ClosedXML/ClosedXML#1322]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.94.2

**What is the current behavior?**

![grafik](https://user-images.githubusercontent.com/17551597/70913766-ef09fd00-2016-11ea-9fe4-e7156b8f208e.png)

**What is the expected behavior or new feature?**

Complete this.
![grafik](https://user-images.githubusercontent.com/17551597/70913810-077a1780-2017-11ea-8d0b-b3b3ba2da5f9.png)

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

I have a template Excel file, where I just add new rows/values. When the values are added and the workbook is saved, the value and format is wrong.

**Code to reproduce problem:**
```c#
sheet.Row(index).Cell(10).Value = "False";
sheet.Row(index).Cell(10).Value = false;
```

[HMITags.xlsx](https://github.com/ClosedXML/ClosedXML/files/3968440/HMITags.xlsx)

**Comment by igitur** [comment]
`.Value` tries to guess the variable type. In your case the value is a valid Boolean value. 

If you don't want the value to be parsed as a Boolean value, but rather as a string value, you have 2 options:

- `sheet.Row(index).Cell(10).Value = "'False";` (notice the single quote character that I added before `False`) 
or 
- `sheet.Row(index).Cell(10).SetValue("False");`

**Comment by igitur** [comment]
More info at https://github.com/ClosedXML/ClosedXML/wiki/Cell-Values

**Comment by dojo90** [comment]
Thanks for your fast reply! 🙂👍
Maybe you should add some information on the method to get the info on `IntelliSense`.

**Comment by igitur** [comment]
Good idea. I'm on holiday, but maybe you can contribute back to the project
by enhancing the documentation? Please submit a pull request.
