### ISSUE TITLE
Unable to use % in formula

### ISSUE THREAD

**Issue by SfWt** [ClosedXML/ClosedXML#1324]
- [x] Bug
- [ ] Feature

Version of ClosedXML: 0.94.2.0

A formula like "=A1*A2%" in an Excel cell results in an exception: "ClosedXML.Excel.CalcEngine.ExpressionParseException: Identifier expected. at ClosedXML.Excel.CalcEngine.CalcEngine.Throw(String msg)".

I'm using a code similar to the following, where rawData is of type byte[] containing the Excel file:

```C#
using (var s = new MemoryStream(rawData))
{
    XLWorkbook wb = new XLWorkbook(s);
    var sheet = wb.Worksheet(sheetName);
    var table = sheet.RangeUsed(XLCellsUsedOptions.AllContents).AsTable();
    var dt = table.AsNativeDataTable();

    foreach (DataRow row in dt.Rows)
        Console.WriteLine($"{string.Join(", ", row.ItemArray)}");
}
```

As far as I understand the percentage character (%) can be used in normal cells, so it should also work within formulars, shouldn't it?

Attached file can be used to reproduce the behaviour.

[formular_percent_crash.xlsx](https://github.com/ClosedXML/ClosedXML/files/3972930/formular_percent_crash.xlsx)

**Comment by SfWt** [comment]
I did some testing with current development version (0.95.0) and the Excel file above can be loaded successfully. 

But the same error (Identifier expected) is still coming up if the file contains a formula like "=Sheet1!A3" on a second sheet referencing the cell with the %-formula (A3 on sheet1). If I now remove the % from sheet1 formula, the sheet will be parsed, but cell A3 of sheet1 contains a value of 0 instead of 3276 (which is the result of the formula without %). Removing the reference from sheet2 finally results in the correct value of 3276.

[formular_percent_ref_crash.xlsx](https://github.com/ClosedXML/ClosedXML/files/3973490/formular_percent_ref_crash.xlsx)

**Comment by Pankraty** [comment]
Excel treats `%` in formulas as `/100` (`=1234%%` == `0.1234`).

We have to introduce a new operator, I suppose.
