### ISSUE TITLE
Sorted AutoFilter column throws System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by mathlang** [ClosedXML/ClosedXML#1325]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

v0.94.2

**What is the current behavior?**

When saving an Excel file with sorted AutoFilter columns, a System.ArgumentOutOfRangeException is thrown

I have tracked down the bug to ClosedXML\Excel\XLWorkbook_Save.cs:6214:

```
var sortState = new SortState
{
    Reference =
        filterRange.Range(filterRange.FirstCell().CellBelow(), filterRange.LastCell()).RangeAddress.
            ToString()
};
```

This fails if filterRange only contains one row because CellBelow() will place you outside of the range.

**What is the expected behavior or new feature?**

The document should be saved without throwing an exception

**Did this work in previous versions of our tool?  Which versions?**

Unknown

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**

```
static void Main(string[] args)
        {
            using (var wb = new XLWorkbook(@"C:\temp\FilterTest.xlsx"))
            {
                wb.Save();
            }
        }
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[FilterTest.xlsx](https://github.com/ClosedXML/ClosedXML/files/3976700/FilterTest.xlsx)

**Comment by igitur** [comment]
Fixed in #1326
