### ISSUE TITLE
Adding VLookup and IFERROR formula

### ISSUE THREAD

**Issue by jfred82** [ClosedXML/ClosedXML#1329]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ x] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.87.1

**What is the current behavior?**
Gives a cell.Value error when trying to use the formula

**What is the expected behavior or new feature?**
To be able to get a values of the cell when calling it 

**Did this work in previous versions of our tool?  Which versions?**

Yes

Example of formula recieving error.

=IFERROR(VLOOKUP(A15,'Rack Assembly Sort'!$A$4:$P$500,16,FALSE),"")

First time opening an issue so hope this is the right place to do it.

**Comment by igitur** [comment]
Please try with the latest version of ClosedXML. If you still have a problem, log a new issue and follow the instructions carefully. You didn't give a good code sample above. My instructions were clear in the issue template.
