### ISSUE TITLE
XLTable.FieldNames Dictionary doesn't Refresh Keys

### ISSUE THREAD

**Issue by BenKmann** [ClosedXML/ClosedXML#133]
I run into a little Problem.
I use the Following code to find a Column and Rename it:
`IXLTable table = cobraIdRange.AsTable();`
`var testfield = cobraIdTable.Fields.First(field => field.Name.Equals("Test", StringComparison.OrdinalIgnoreCase));`
`testfield.Name = "OtherName";`

When i iterate over the Rows 
`foreach (IXLTableRow tableRow in table.DataRange.Rows()){`
`   tableRow.Field("OtherName");`

throws an Exception, because the Keys in the FieldNames Dictionary of the XLTable has still the old ColumnName "Test". But the Field it contains has the new Name "OtherName".

I Refresh the Dictionary now with
`table = table.AsTable();`

Do i use it wrong, or should the Dictionary refresh itself, when the Name Property of a Field is changed.
[Edit] Would be nice to have access to the FieldNames Dictionary.

**Comment by igitur** [comment]
Please test whether this is still a problem with 0.89.0-beta1.

**Comment by Pankraty** [comment]
Tested on the attached example
```
using var wb = new XLWorkbook(@"133.xlsx");
var ws = wb.Worksheets.First();
IXLTable table = ws.Tables.First();
var testfield = table.Fields.First(field => field.Name.Equals("Test", StringComparison.OrdinalIgnoreCase));
testfield.Name = "OtherName";

foreach (IXLTableRow tableRow in table.DataRange.Rows())
{
    Console.WriteLine(tableRow.Field("OtherName").Value);
}

```
Works fine. Closing.

[133.xlsx](https://github.com/ClosedXML/ClosedXML/files/5245152/133.xlsx)
