### ISSUE TITLE
Errors: while creating report: Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by juliep10** [ClosedXML/ClosedXML#1332]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML** 0.94.2.0

**What is the current behavior?**

Complete this.

**What is the expected behavior or new feature?**

Working for 350 records. If records in data table is more than 400 it's throwing error.

**Did this work in previous versions of our tool?  Which versions?**

NA

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```Vb.net
 Tried below code but still not working
 workbook = New XLWorkbook(MS, XLEventTracking.Disabled)
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
@juliep10 This isn't your first time submitting an issue. You should know how it works and what information we expect by now.
