### ISSUE TITLE
closed xml error exception of type 'system.outofmemoryexception' was thrown while export to excel

### ISSUE THREAD

**Issue by juliep10** [ClosedXML/ClosedXML#1333]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

v4.0.30319

**What is the current behavior?**

Working but excel is generating for less than 400 records

**What is the expected behavior or new feature?**

Excel should create for more than 400 records 

**Did this work in previous versions of our tool?  Which versions?**

Not sure for more than 400 records

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
VB.net
I tried below code to avoid memory issue but still it's not working
workbook = New XLWorkbook(MS, XLEventTracking.Disabled)
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)
I am creating file so no template.

**Comment by igitur** [comment]
Read the instructions in the issue template.

**Comment by juliep10** [comment]
I have no Template. I already read the instruction.  Please let me the solution.

**Comment by Pankraty** [comment]
The solution will start from
1. Create the issue that describes what and how you are trying to do
2. Include a code sample that reproduces the problem, that can be compiled being copy-pasted to Program.cs of a console app having ClosedXml installed
3. Specify the actual version of ClosedXML you use (4.* does not even exist, we are on 0.95 now) 
4. Attach xlsx file you managed to generate

It is impossible to figure out next steps until these ones are completed.
