### ISSUE TITLE
closed xml error exception of type 'system.outofmemoryexception' was thrown while export to excel

### ISSUE THREAD

**Issue by juliep10** [ClosedXML/ClosedXML#1334]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

 0.94.2

**What is the current behavior?**

Working but excel is generating for less than 400 records

**What is the expected behavior or new feature?**

Excel should create for more than 400 records which are in data table

**Did this work in previous versions of our tool?  Which versions?**

No. It seems in all version it's not working.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
Vb.net
```
Protected Overrides Sub OnCreate()
  Protected workbook As Object
      Protected ws As Object
    Dim iCurrRow As Integer = 1000
Dim iCurrRow As Integer =5
 Protected sTEMPLATEFILE As String = "C:/tpl_TSR.xlsx"
 Dim dtTests As New Data.DataTable

  If sFormat.Equals("xlsx") Then
            Using fs = New FileStream(pPage.Server.MapPath(sTEMPLATEFILE), FileMode.Open, FileAccess.Read)
                fs.CopyTo(MS)
            End Using
            MS.Seek(0, SeekOrigin.Begin)

            Using dSpreadsheet = SpreadsheetDocument.Open(MS, True)
                For Each wsPars As Object In dSpreadsheet.WorkbookPart.WorksheetParts
                    For Each VmlDrawingPart In wsPars.VmlDrawingParts
                        Dim Text As String
                        Using tr = New StreamReader(VmlDrawingPart.GetStream(FileMode.Open))
                            Text = tr.ReadToEnd()
                        End Using

                        Using tw = New StreamWriter(VmlDrawingPart.GetStream())
                            tw.Write(Text.Replace("<br>", "    ").Replace("<br />", "    "))
                        End Using
                    Next
                Next
            End Using

            MS.Seek(0, SeekOrigin.Begin)
            workbook = New XLWorkbook(MS, XLEventTracking.Disabled)
  If sTEMPLATEFILE.Equals("tpl_TSR.xlsm") Then
                ws = workbook.Worksheet("Test Status")
            End If

' Count of dtTests.Rows > 500
    For Each row As Data.DataRow In dtTests.Rows 
 iCurrRow += 1
            ws.Row(iCurrRow).InsertRowsBelow(iCurrRow + 1)
    End If

 End If
End Sub
```
- [ ] I attached 
[tpl_TSR.xlsx](https://github.com/ClosedXML/ClosedXML/files/4075158/tpl_TSR.xlsx)

a sample spreadsheet.  (You can drag files on to this issue)

**Comment by juliep10** [comment]
Hi any help on performance issue of closedxml when generating excel report

**Comment by Pankraty** [comment]
As I already wrote in #1333,

1. Create the issue that describes what and how you are trying to do
2. Include a code sample that reproduces the problem, that can be compiled being copy-pasted to Program.cs of a console app having ClosedXml installed
3. Specify the actual version of ClosedXML you use (4.* does not even exist, we are on 0.95 now) 
4. Attach xlsx file you managed to generate

You've fulfilled steps 3 and 4 but I am still not able to run your code sample to reproduce the issue and I still do not understand what "Working but excel is generating for less than 400 records" means.

**Comment by igitur** [comment]
In my next life I will have @Pankraty 's patience.

**Comment by Pankraty** [comment]
```
    For Each row As Data.DataRow In dtTests.Rows 
 iCurrRow += 1
            ws.Row(iCurrRow).InsertRowsBelow(iCurrRow + 1)
    End If
```

@juliep10 I do not know what you are trying to achieve but this block seems wrong to me. Essentially, you insert 2 rows below row number 1, then insert 3 rows below row number 2, and so on. In the end, you insert 501 rows below row number 500; the total number of rows inserted is ~125K which probably is not what you need.

Insert the desired number of rows before the loop and then fill them with data, it will solve your issues.

Regardless, I see performance degradation: in the beginning, it takes 7-10 ms to insert rows, on the 500th iteration it is more than 1000. Will check if it can be improved.

**Comment by Pankraty** [comment]
> Will check if it can be improved.

Nah, it is hopeless. At any given step `N` there are `(N-1)² - N` rows below the current row, each containing 6 cells, and they all have to be shifted. The overall complexity is `O(N³)` and for 500 rows there will be ~375M cell shifts. Any optimizations we could make would not beat the cubic complexity.
