### ISSUE TITLE
Saved file is corrupted when header contians image

### ISSUE THREAD

**Issue by belidzs** [ClosedXML/ClosedXML#1336]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

When I open an existing Excel file with an image in the header, then add another image to the workbook before saving, the saved Excel file will be corrupted and won't open in Excel anymore.

**What is the expected behavior or new feature?**

The produced Excel file should not be corrupt.

**Did this work in previous versions of our tool?  Which versions?**

I have not used previous versions.

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
            var wb = new XLWorkbook("a.xlsx");
            wb.Worksheet(1).AddPicture("Clipboard02.png");
            wb.SaveAs("b.xlsx");
            Process.Start("b.xlsx");
}
```

Both `a.xlsx` and `Clipboard02.png` are attached.

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[a.xlsx](https://github.com/ClosedXML/ClosedXML/files/4080533/a.xlsx)
![Clipboard02](https://user-images.githubusercontent.com/7085801/72663177-b5e6f300-39ef-11ea-9f95-2d558c8b2883.png)

**Comment by igitur** [comment]
Your file contains a header image. Images in headers and footers are not supported by ClosedXML yet. The result is a corrupt file.

**Comment by belidzs** [comment]
Ah I see. 

Until this feature is implemented is it possible to at least throw an exception when the user tries to open an incompatible file? It would probably save some headache for others.

If this is not possible (for instance because you have to actually implement the whole feature to be able to detect images in header and footer) it would be nice if the documentation would reflect this limitation.

**Comment by igitur** [comment]
Implementing an exception is half the work of implementing the feature.

Yes, the documentation can reflect this shortcoming. Please submit a pull request. Let me know if you need help.
