### ISSUE TITLE
How I can copy range values without formulas?

### ISSUE THREAD

**Issue by b0bi79** [ClosedXML/ClosedXML#134]
I want to copy range values with cell formatting (exclude formulas) to another sheet. When I use code `rangeTarget.Cell(1, 1).Value = rangeSrc`, then the copied cells with formulas. It may be possible to remove the formula and keep the values of the cells?

**Comment by b0bi79** [comment]
```
                Range.CellsUsed(i=>i.HasFormula)
                    .ForEach(c => c.Value=c.Value);
```

**Comment by igitur** [comment]
I think we should extend the API to provide a friendlier approach to this.

**Comment by jahav** [comment]
Closing. There is a solution and I am generally not in favor of adding new API unless there is a clear use case or it can't be done another way. Resources will be better spent elsewhere.
