### ISSUE TITLE
What method will be working faster? 

### ISSUE THREAD

**Issue by lidazaikova** [ClosedXML/ClosedXML#1341]
I am trying to fill Worksheet with range A1:D9 with 4 pictures from other worksheet using Range.CopyTo method.
I need to repeat this action about 1000 and more times for each worksheet.
Now it takes 76 minutes for 1000 items. How can I make this operation faster? Will InsertTable work faster for Range.AsTable ?

**Comment by igitur** [comment]
Complete the full issue template, including code sample and we might be able to identify a bottleneck.
