### ISSUE TITLE
Can you Quickly Get the Worksheet Names?

### ISSUE THREAD

**Issue by ll9** [ClosedXML/ClosedXML#1345]
**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x] Feature

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

When I want to get all names of the WorkSheets I create a `new XLWorkbook` and then iterate over the worksheets to get their names. My Excel File is rather big and it takes some time to create a `XLWorkbook` just for reading the sheetnames. I wonder if there is a way to just read the sheetnames without loading the whole content for better performance.

**What is the expected behavior or new feature?**

Get all sheetnames without reading all of their content (quick access).

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
    var names = new List<string>();
    // Takes some time to load just to get sheet names...
    using (var wb = new XLWorkbook("File.xlsx"))
    {
        foreach (var sheet in wb.Worksheets)
        {
            names.Add(sheet.Name);
        }
    }
}
```

**Comment by igitur** [comment]
No, you have to load the `XLWorkbook` in order to get the sheet names. If you're looking for something quicker, you can try the EPPlus library or work directly with the underlying OpenXML.

**Comment by Pankraty** [comment]
ClosedXML initializes everything on opening the workbook, this is by design and is not easy to change. If reading worksheet names is all you need then I suggest using a low level OpenXML API

**Comment by Pankraty** [comment]
@igitur was faster again :D

**Comment by igitur** [comment]
> @igitur was faster again :D

Only because my day job's project is running unit tests for 15min and I'm idling while monitoring my Gmail inbox ;-)

**Comment by ll9** [comment]
Thanks you have pointed me towards the right direction. I have used OpenXML in order to acchieve my goal (takes 200ms compared to loading the whole workbook with closedXML). Here is the code for for anyone who is interested:

```c#
        private static List<string> GetNamesNative()
        {
            var names = new List<string>();

            using (var spreadSheetDocument = SpreadsheetDocument.Open(Path, false))
            {
                int sheetIndex = 0;
                foreach (var worksheetpart in spreadSheetDocument.WorkbookPart.WorksheetParts)
                {
                    string sheetName = spreadSheetDocument.WorkbookPart.Workbook.Descendants<Sheet>().ElementAt(sheetIndex).Name;
                    names.Add(sheetName);

                    sheetIndex++;
                }
            }

            return names;
        }
```
