### ISSUE TITLE
Generated linked date cell data is invalid

### ISSUE THREAD

**Issue by zolichev** [ClosedXML/ClosedXML#1346]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.94.2

**What is the current behavior?**

The date cell is linked to another date cell named "_Period1".

A date cell in source file created by Excel:
```xml
			<c r="B3" s="83">
				<f>_Period1</f>
				<v>43831</v>
			</c>
```
Same cell in generated file:
```xml
			<x:c r="B3" s="142" t="d">
				<x:f>_Period1</x:f>
				<x:v>02/01/2019 00:00:00</x:v>
			</x:c>
```

Error in type: "t="d""

**What is the expected behavior or new feature?**

cell in generated file:
```xml
			<x:c r="B3" s="142" t="d">
				<x:f>_Period1</x:f>
				<x:v>43831</x:v>
			</x:c>
```
or maybe:
```xml
			<x:c r="B3" s="142">
				<x:f>_Period1</x:f>
				<x:v>43831</x:v>
			</x:c>
```

**Did this work in previous versions of our tool?  Which versions?**

Don't know.

## Reproducibility
Create 2 date cell second of them linked to first. Fill first cell via ClosedXML by date value. Try to save with SaveOption { ValidatePackage = true}. Got a error about invalid type (t="d"). Try to open generated file in Excel - got the similar error.

**Comment by igitur** [comment]
Insufficient code sample
