### ISSUE TITLE
How to handle StackOverflowException in ClosedXML

### ISSUE THREAD

**Issue by Umeshpatil0012** [ClosedXML/ClosedXML#1347]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**
0.94.2.0

**What is the current behavior?**
I have written code to check cell formula of excel cell in C# ClosedXML. Everything works fine, but only problem is, if the checked cell formula contains self cell then it gives StackOverflowException and this exception stops my service.

**What is the expected behavior or new feature?**
Please Handle StackOverflowException for self formulated cell.

**Did this work in previous versions of our tool?  Which versions?**
No

## Reproducibility

**Code to reproduce problem:**
```c#
var _xlWorkBook = new ClosedXML.Excel.XLWorkbook(fileStream);
var workSheet = xlWorkBook.Worksheet(1);
var row = workSheet.Row(2);
string cellValue = row.Cell(2).Value.ToString();
```
-
[Test File.xlsx](https://github.com/ClosedXML/ClosedXML/files/4179529/Test.File.xlsx)
 [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
I cannot reproduce your problem using the latest version (v0.95.0-beta2).

![image](https://user-images.githubusercontent.com/145854/74160435-14d20d80-4c26-11ea-91da-014ff67ccaa4.png)

**Comment by Umeshpatil0012** [comment]
Can you please try it 0.94.2.0 this version.

**Comment by igitur** [comment]
What would be the point of that?

**Comment by mathlang** [comment]
I think this is what he was trying to report. There is no point in creating such a workbook but we could receive it from an external source and you can't recover from a StackOverflowException.

```
var _xlWorkBook = new ClosedXML.Excel.XLWorkbook();
var workSheet = _xlWorkBook.AddWorksheet("Test");
var row = workSheet.Row(2);
var cell = row.Cell(2);
cell.FormulaA1 = "=B2";
string cellValue = cell.Value.ToString();
```

**Comment by Pankraty** [comment]
The thing is, it has already been fixed, as @igitur showed.

**Comment by mathlang** [comment]
It is not fixed. Try the code I posted with 0.95.9-beta2. The original test code posted in the issue, that @igitur tested, was wrong.

**Comment by Pankraty** [comment]
Ok, thanks, will check in the morning

**Comment by Pankraty** [comment]
We even have a test for this: https://github.com/ClosedXML/ClosedXML/blob/develop/ClosedXML_Tests/Excel/Cells/XLCellTests.cs#L977

It does not have `[Test]` attribute though and we did not know it fails 😕
