### ISSUE TITLE
Copying range into Cell.Value is working slower than copying all cells from range with for-cycle

### ISSUE THREAD

**Issue by lidazaikova** [ClosedXML/ClosedXML#1348]
Hi!

I was making Excel - file. I had a template - a range A1:D9. And I need to copy this range into another worksheet many times. From 10 to 400 (maybe til 1000)

It was copying like this (my predesestor wrote this code)
```
protected override void CopyStructureFromTemplate() {
            var firstTableCell = WsFromCopy.Cell(1, 1);
            var lastTableCell = WsFromCopy.Cell(RowCount, ColumnCount);
            var rangeToCopy = WsFromCopy.Range(firstTableCell.Address, lastTableCell.Address);

            for (int i = 0; i < LabelCount; i++) {
                WsToCopy.Cell(RowCount * i + 1, 1).Value = rangeToCopy;
            }
        }
```
When LabelCount is 10 only this method worked about 30seconds. When 100  - about 76 minutes. Time was growing exponentially.
I changed it this way
```
protected override void CopyStructureFromTemplate() {
	            var firstTableCell = WsFromCopy.Cell(1, 1);
	            var lastTableCell = WsFromCopy.Cell(RowCount, ColumnCount);
	            var rangeToCopy = WsFromCopy.Range(firstTableCell.Address, lastTableCell.Address);
				
				
	            for (int i = 0; i < LabelCount; i++) {
	            	int rowIterator = RowCount * i;
	            	var firstCellOfRow = WsToCopy.Cell(rowIterator+1,1);
	          
					for (int col=1; col<=ColumnCount; col++) {
						for (int j=1; j<=RowCount; j++) {
							WsToCopy.Cell(rowIterator+j, col).Value = rangeToCopy.Cell(j, col).Value;
							WsToCopy.Cell(rowIterator+j, col).Style = rangeToCopy.Cell(j, col).Style;
							
						}
					}
					
	            }
        	
        }
```
This code has worked on LabelCount = 100 for a few seconds
2 CS-classes below
Thank u for perfomance feedback

I also tried Range.CopyTo() and InsertRowsBelow(Range.Rows()) but I didnt get necessary results
[12.02.2020-19_10056-_ver28.xlsx](https://github.com/ClosedXML/ClosedXML/files/4189102/12.02.2020-19_10056-_ver28.xlsx)
[AnSportmasterLabelGenerator.txt](https://github.com/ClosedXML/ClosedXML/files/4189111/AnSportmasterLabelGenerator.txt)
[AnBaseLabelGenerator.txt](https://github.com/ClosedXML/ClosedXML/files/4189112/AnBaseLabelGenerator.txt)

**Comment by vbjay** [comment]
Make sure you aren't copying full Excel rows and just used columns and
rows. Read wiki on ...used helpers and such.

**Comment by igitur** [comment]
@lidazaikova As I mentioned in https://github.com/ClosedXML/ClosedXML/issues/1341#issuecomment-579899542 , we expect you to complete the full issue template and provide a code sample that I can paste into a console application. I don't have the time to refactor your code sample into something that I can run.

**Comment by lidazaikova** [comment]
I will provide console app soon. I found that Worksheet.Range(x,y,x1,y1).Row(1).Merge() also decrease perfomance of this code. I used perfomance recomendations by disabling triggers and I also create ranges only with digit indexes not with letter's address. Are there any hacks for merging text cells? I need to merge 2 cell in row but about 1000-5000 times

**Comment by lidazaikova** [comment]
https://stackoverflow.com/questions/37873567/performance-of-merging-column-in-excel-using-c-sharp-closed-xml this ticket helped me to impove merging perfomance. 52000 Excel with about 15000 pics took about 15 minutes instead of 1.5-2 hours. I also owe u a console app

**Comment by Pankraty** [comment]
The code I came up with:

```
var RowCount = 10;
var ColumnCount = 4;
var LabelCount = 0;
var sw = new Stopwatch();

do
{
    sw.Start();
    using (var wb = new XLWorkbook(@"e:\ClosedXMl\1348.xlsx"))
    {
        var ws1 = wb.Worksheets.First();
        var ws2 = wb.AddWorksheet();
        var firstTableCell = ws1.Cell(1, 1);
        var lastTableCell = ws1.Cell(RowCount, ColumnCount);
        var rangeToCopy = ws1.Range(firstTableCell.Address, lastTableCell.Address);

        for (int i = 0; i < LabelCount; i++)
        {
            ws2.Cell(RowCount * i + 1, 1).Value = rangeToCopy;
        }

        Console.WriteLine($"{LabelCount}\t{sw.ElapsedMilliseconds}");
    }

    if (LabelCount == 0)
        LabelCount = 1;
    else
        LabelCount *= 2;

} while (LabelCount < 50000);


Console.WriteLine("Press any key to continue");
Console.ReadKey();
```

On the latest `develop` branch the dependency looks close to linear while on 0.94.2 it was exponential indeed.

![image](https://user-images.githubusercontent.com/19576939/75243027-9dce7480-57e2-11ea-9541-9edd1551e774.png)

So I encourage you to try the latest build - it must solve your issue.

**Comment by lidazaikova** [comment]
Thank u! we've got latest build and we're testing it now.
