### ISSUE TITLE
Project Dependencies

### ISSUE THREAD

**Issue by carloserodriguez2000** [ClosedXML/ClosedXML#1349]
I have a project that uses other packages that refer to the latest "DocumentFormat.OpenXm".
  It looks like your configuration is still using version 2.7.2.0.
  The latest version is 2.10.0.0.

I get warnings because the compiler tries to resolve the discrepancies among all the packages in a project. and the it has to include both to maintain compatibility or automatically "Binding Redirects" To higher version.

Thanks

  Thanks for this wonderful tool.

**Current configuration is using**:
```
 <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="2.7.2" />


```

Please consider updating to latest package:
`    <PackageReference Include="DocumentFormat.OpenXml" Version="2.10.0.0" />
`

**Comment by igitur** [comment]
You can use a higher version of DocumentFormat.OpenXml with ClosedXML if you need to align with other dependencies.
