### ISSUE TITLE
Generated XLSX is invalid

### ISSUE THREAD

**Issue by Alt-WN** [ClosedXML/ClosedXML#135]
I use ClosedXML version **0.85.0.0**. I have Excel 2016 document which seems to be valid. It can be opened and saved smoothly in Excel 2016. It contains no data. I use ClosedXML to open and save it but generated file is invalid. Excel reports that it has invalid structure and needs to be fixed. Here is the code to open and save:
`XLWorkbook workbook = new ClosedXML.Excel.XLWorkbook("aa.xlsx");`
`workbook.SaveAs("bb.xlsx");`
The file bb.xlsx produced in ClosedXML version **0.80.0.0** was correct, while after upgrading to **0.85.0.0** it is incorrect.
Please find attached source Excel document:
[aa.xlsx](https://github.com/ClosedXML/ClosedXML/files/671435/aa.xlsx)
 file aa.xlsx.

**Comment by katarn0** [comment]
Alt-WN,

I just tested your file and got this error: "We found a problem with some content in 'bb.xlsx'.  Do you want us to try to recover as much as we can?  If you trust the source of this workbook, click Yes."

On clicking Yes, there is a second worksheet "Recovered_Sheet1".

On further review, I looked at the size of your aa.xlsx file and a new blank Excel file I created.  For me a blank Excel file should be 8 KB's and your aa.xlsx file is 9 KB's.

From all of this, it seems that your saved aa.xlsx file has a hidden unrecovered sheet.

**Comment by igitur** [comment]
#127 fixes this.

**Comment by igitur** [comment]
Please test with the latest 0.86 release. https://github.com/ClosedXML/ClosedXML/releases/tag/0.86.0

**Comment by Alt-WN** [comment]
I have tested 0.86. It works correct! Thanks.

Regards,
Alt-WN

**Comment by Alt-WN** [comment]
Hello,
I have tested 0.86 release. It generates correct xlsx. Thanks.

Regards,
Alt-WN Waldemar Nowak

**Comment by Alt-WN** [comment]
I am sorry, I didn’t know that email response will also go to github issues tracker automatically. Please delete one of my duplicated comments about confirmation of fixing bug.

Regards,
Alt-WN Waldemar Nowak

**Comment by jsmunroe** [comment]
This is for people who find this in a search who are calling SaveAs to a MemoryStream and then using GetBuffer to get an array of bytes. Use ToArray on the stream instead of GetBuffer.
