### ISSUE TITLE
NumberFormat export bug

### ISSUE THREAD

**Issue by Platonenkov** [ClosedXML/ClosedXML#1354]
- [x] Bug

**Version of ClosedXML**

e.g. 0.94.2

**What is the current behavior?**
Comma appears after number when changing data format

**What is the expected behavior or new feature?**

I want to change the format of the number at unloading, if the number after the comma has 3 digits - output 2, if 1 character - output 1, if the number is not fractional - do not output 0 after the comma

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
                using (XLWorkbook wb = new XLWorkbook())
            {
                var ws = wb.Worksheets.Add("Test");

                ws.Cell(1, 2).Value = 3;           // value in file - 3, - it ok, but without comma
                ws.Cell(1, 3).Value = 3.1;        // value in file - 3,1
                ws.Cell(1, 4).Value = 3.12;     // value in file - 3,12
                ws.Cell(1, 5).Value = 3.1278; // value in file - 3.13
                ws.Range(1, 2, 1, 5).Style.NumberFormat.SetFormat("0.##");
                //ws.Range(1, 2, 1, 5).Style.NumberFormat.Format = "0.##"; //same resalt

                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", downloadName);
                }
            }


}
```
[testBook.xlsx](https://github.com/ClosedXML/ClosedXML/files/4271065/testBook.xlsx)

**Comment by mathlang** [comment]
This matches the behavior of the Excel application. 0.## custom format will display a decimal period (or comma depending on region) even for integer numbers. What is the bug exactly?

**Comment by Platonenkov** [comment]
Ok.
What should I write to get the desired view? or it is impossible?

**Comment by igitur** [comment]
Please post examples of what you want and what is currently produced.

**Comment by Platonenkov** [comment]
ok.
I set the values of some cells.
#### example:
I need two numbers after the point, but only if they are there
| Values | How it now| How it must be |
|:----------------:|:----------------:|:----------------:|
| 0.5 | :negative_squared_cross_mark:0.50| 0.5|
| 0.56 | 0.56| 0.56|
| 0.568 | 0.57| 0.57|
| 0.5689 | 0.57| 0.57|
| 1 |:negative_squared_cross_mark: 1.00| 1|

or
I need five numbers after the point, but only if they are there
| Values | How it now| How it must be |
|:----------------:|:----------------:|:----------------:|
| 0.5 | :negative_squared_cross_mark:0.50000| 0.5|
| 0.56 |  :negative_squared_cross_mark:0.56000| 0.56|
| 0.568 |  :negative_squared_cross_mark:0.56800| 0.568|
| 0.5689 |  :negative_squared_cross_mark:0.56890| 0.5689|
| 1 |:negative_squared_cross_mark:1.00000| 1|

**Comment by igitur** [comment]
Replicate what you want in Excel, save the file and attach it here.

**Comment by Platonenkov** [comment]
here in column Ok is valid result, but it with formula, can I do it with format ?
 
[example.xlsx](https://github.com/ClosedXML/ClosedXML/files/4275003/example.xlsx)

**Comment by igitur** [comment]
> can I do it with format ?

I don't know. 

But if you can do it in Excel and upload the file, we can try to implement in ClosedXML.

**Comment by mathlang** [comment]
I don't think you can do it with Format. Consider using Round formula.
