### ISSUE TITLE
delete column will change formula

### ISSUE THREAD

**Issue by fnrlv0904** [ClosedXML/ClosedXML#1355]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.87.1 & 0.94.2

**What is the current behavior?**

formula be changed after delete column.

**What is the expected behavior or new feature?**

copy sheet to new workbook and delete a column of sheet and keep all others data.

**Did this work in previous versions of our tool?  Which versions?**

Yes,  both 0.87.1 & 0.94.2.  (I did not use other versions.

## Reproducibility

when I delete column A2, the formula DE**C2**HEX([@Value],4) in column B will be changed to DE**B2**HEX([@Value],4)

**Code to reproduce problem:**
```c#
public void Main()
{
            XLWorkbook wb_src = new XLWorkbook(dir);
            XLWorkbook wb = new XLWorkbook();

            foreach (var item in wb_src.Worksheets)
            {
                wb_src.Worksheet(item.Name).CopyTo(wb, item.Name);
            }

            wb.Worksheet(1).Column(1).Delete();
}


```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)
[workBook.xlsx](https://github.com/ClosedXML/ClosedXML/files/4273320/workBook.xlsx)

**Comment by fnrlv0904** [comment]
my excel version is 2010

**Comment by Pankraty** [comment]
Same happens with functions like `ATAN2`, `DAYS360`, etc. - ones that contain a combination treated as a cell reference (`DEC2`, `TAN2`, `AYS360`)
