### ISSUE TITLE
Save workbook exception

### ISSUE THREAD

**Issue by b0bi79** [ClosedXML/ClosedXML#136]
I have a xlsx file that I created using MS Excel. If I load the file into XLWorkbook and immediately save it with SaveAs I get an error.

File is: 
[4.xlsx](https://github.com/ClosedXML/ClosedXML/files/684725/4.xlsx)

**Comment by igitur** [comment]
The Russian is creating some problems. ClosedXML looks for a "Normal" font to determine the default style. In your workbook it is "Обычный". I'll have to look around for another way to determine the default style.
