### ISSUE TITLE
Cannot clear a cell in certain XLSX files

### ISSUE THREAD

**Issue by tarockx** [ClosedXML/ClosedXML#1361]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
Tested both 0.94.2 and 0.95.0-beta2

**What is the current behavior?**

This issue might be related to [this other issue I opened some time ago](https://github.com/ClosedXML/ClosedXML/issues/1330), since it happens with the same kind of files. As a reminder of our discussion in the other thread, these are the XLSX files generated by the Microsoft Reporting Services engine (so files generated from Sequel Service Reporting Services or the Report Viewer C# library, both official Microsoft products).

I have an XLSX file (attached as [test.xlsx](https://github.com/ClosedXML/ClosedXML/files/4019408/test.xlsx) , same file as in the other issue). 

In this file, I cannot clear (set an empty/null value) a cell. If I set an actual value to it it works, but setting an empty string doesn't, the cell remains with filled the old value.

**What is the expected behavior or new feature?**

Cell should be emptied when assigning null or empty string to its value

## Reproducibility
This code will reproduce the issue in the attached file. It should empty the first cell, but it doesn't.

```c#
static void Main(string[] args)
{
    using (var ms = new MemoryStream(File.ReadAllBytes("test.xlsx")))
    {
        using (var workbook = new XLWorkbook(ms))
        {
            var ws = workbook.Worksheets.First();
            var cell = ws.Cell(1, 1);
            cell.Value = "";

            workbook.SaveAs("test_out.xlsx");
        }

    }
}
```

- [x] I attached a [sample spreadsheet](https://github.com/ClosedXML/ClosedXML/files/4019408/test.xlsx)

**Comment by igitur** [comment]
Yes, I believe it's related to the other. Again, we don't have explicit support for inline (as opposed to shared) rich text yet. 

If you really just want to clear the cell's value, try `cell.Clear()`.

**Comment by tarockx** [comment]
Hi igitur, thanks for your quick reply.
The problem with using .Clear() is that I also lose the cell's style.
I tried with `cell.Clear(XLClearOptions.AllContents);` but that doesn't work, it keeps the old value.
Is there a possible workaround for this? Maybe a way to deep-copy the cell's style and then re-applying it after clearing it?

As for the issue in general, I hate to ask this, as a developer myself I know it's annoying, but do you have even a vague ETA on when (or even "if") this kind of files will be supported?

Thanks again for your effort and have a nice day

**Comment by Pankraty** [comment]
> Maybe a way to deep-copy the cell's style and then re-applying it after clearing it?

In fact, cell.Style works as a deep copy so you can try to simply store it in a variable before the clearing and reapply after that. Though it of course is a mare workaround.
