### ISSUE TITLE
Named constants throw exception.

### ISSUE THREAD

**Issue by b0bi79** [ClosedXML/ClosedXML#137]
If I assign via MS Excel for RefersTo of named range does not range address but the value and load the file into XLWorkbook, I get an exception when trying to calculate the value of a cell referring to this range.
![image](https://cloud.githubusercontent.com/assets/1150085/21466202/af6d6aa4-c9d1-11e6-9117-743c1ccaca7e.png)
Example xlsx: 
[7_vars.xlsx](https://github.com/ClosedXML/ClosedXML/files/684721/7_vars.xlsx)

**Comment by igitur** [comment]
Yes, named constants and named formulas are not supported yet. Only named ranges are supported so far.
