### ISSUE TITLE
Printing and Margins

### ISSUE THREAD

**Issue by jonlegras** [ClosedXML/ClosedXML#1372]
I can't find a solution to this anywhere, and I think it's perhaps a 'bug' in excel rather than in ClosedXML - I have previously used Excel Interop, but it's so slow, hence I'm trying to use ClosedXML, but that interop seemed to have exactly the same problem.

Using ClosedXML 0.94.2 and Excel 2016.

The problem is this:
I want to set the margins in my excel document ready for printing.

I can use 
sheet.PageSetup.Margins.Top = 1;
sheet.PageSetup.Margins.Bottom= 1;
sheet.PageSetup.Margins.Left= 1;
sheet.PageSetup.Margins.Right= 1;
etc
This replicates what is seen on screen in excel, setting the margins to 1cm.
But..
Do this and check the margins on your sheet, they won't be set to 1 cm.

It seems the margins are expected to be in inches, so you need to convert.
Using interop it seems to be required in points - not sure why it's different - but there's a set of functions in interop - CentimetersToPoints and InchesToPoint, so you'd have something like this:
sheet.PageSetup.Margins.Top = Excel.CentimetersToPoints(1);

Is there something I'm missing?, e.g. an option to set the units of measure to cm?
Is there a convert to points function that I can't find?

As I mentioned, I seem to have worked around this by using
sheet.PageSetup.Margins.Top = ToInches(1);
where ToInches is my own function, but I can see a situation where this will stop working because an existing sheet (or different version) will be set to inches to something.

**Comment by igitur** [comment]
Please complete the issue template that we set up.
