### ISSUE TITLE
"Error generating comments" with embedded emf graphic file

### ISSUE THREAD

**Issue by TechInterMezzo** [ClosedXML/ClosedXML#1374]
I get an exception with "Error generating comments" at the following line:

https://github.com/ClosedXML/ClosedXML/blob/develop/ClosedXML/Excel/XLWorkbook_Save.cs#L325

The culprit seems to be at the line above.

`if (worksheetHasComments != hasAnyVmlElements)`

hasAnyVmlElements is true because of the embedded vector graphics. But I don't have any comments, so worksheetHasComments is false and the exception is thrown.

**Comment by Pankraty** [comment]
Duplicates #1285. This issue has been fixed and the PR is awaiting review.
