### ISSUE TITLE
Changing SpreadsheetDocumentType

### ISSUE THREAD

**Issue by TechInterMezzo** [ClosedXML/ClosedXML#1375]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

**Version of ClosedXML**

develop branch

**What is the current behavior?**

If you open an xltx file you can only save it as xltx.
The SpreadsheetDocumentType doesn't get changed and is a private field in the workbook class.

**What is the expected behavior or new feature?**

You should be able to open an xltx file and save it as xlsx.

**Did this work in previous versions of our tool?  Which versions?**

No

**Comment by Pankraty** [comment]
You missed this part:

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by TechInterMezzo** [comment]
Try this code and then try to open the Test.xlsx file afterwards. Excel will show an error.

```
public void Main()
{
            using (var wb = new XLWorkbook())
            {
                wb.AddWorksheet();
                wb.SaveAs("Test.xltx");
            }
            using (var wb = new XLWorkbook("Test.xltx"))
            {
                wb.SaveAs("Test.xlsx");
            }
}
```

**Comment by TechInterMezzo** [comment]
I did some debugging and I think I found something that you should be aware of:

https://github.com/ClosedXML/ClosedXML/blob/develop/ClosedXML/Excel/XLWorkbook.cs#L530

```
                using (var fileStream = new FileStream(_originalFile, FileMode.Open, FileAccess.Read))
                {
                    CopyStream(fileStream, stream);
                }
                CreatePackage(stream, false, _spreadsheetDocumentType, options);
```

https://github.com/ClosedXML/ClosedXML/blob/develop/ClosedXML/Excel/XLWorkbook_Save.cs#L130

```
private void CreatePackage(Stream stream, bool newStream, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
        {
            var package = newStream
                ? SpreadsheetDocument.Create(stream, spreadsheetDocumentType)
                : SpreadsheetDocument.Open(stream, true);
```

Even if I would be able to change the field _spreadsheetDocumentType, it would be ignored. The field would only be used by SpreadsheetDocument.Create. But you copy the content of the original stream and use SpreadsheetDocument.Open.
