### ISSUE TITLE
Formula "=LOOKUP(2,1/(A:A<>""),A:A)" generates exception in 0.94.2 (but works in 0.95.0-beta2)

### ISSUE THREAD

**Issue by Zorgle** [ClosedXML/ClosedXML#1380]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [ ] Feature
- [x] Bug

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.94.2

**What is the current behavior?**

The release version throws an exception (I'll paste in below my precomposed email email with details and data).

**What is the expected behavior or new feature?**

I had expected it to return a value and not throw an exception.

**Did this work in previous versions of our tool?  Which versions?**

I don't know. 
However it does work in prerelease 0.95.0-beta2, so this suggests that it has been fixed. So this may not be a helpful issue, and may get closed quickly, but that's okay.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

ClosedXML 0.94.2 (latest stable)

A1: "Latest"
A2: 1
A3: 1
A4: 34.3
B1: =LOOKUP(2,1/(A:A<>""),A:A)

**Code to reproduce problem:**
```c#
        static void Main(string[] args)
        {
            string filepath = @"c:\temp\test.xlsx";

            using (var stream = File.Open(filepath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
            {
                using (var wkbk = new XLWorkbook(stream, XLEventTracking.Enabled))
                {
                    var wksht = wkbk.Worksheet(1);
                    var cell = wksht.Cell("B1");
                    var value = cell.GetString();

                }
            }
        }
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

When I try to call Cell.GetString(), or Cell.GetValue\<string\>(), on B1, I get an exception
```
System.FormatException
  HResult=0x80131537
  Message=Cannot convert Sheet1!B1's value to System.String
  Source=ClosedXML
  StackTrace:
   at ClosedXML.Excel.XLCell.GetValue[T]()
   at ClosedXML.Excel.XLCell.GetString()
   at TestLookup.Program.Main(String[] args)
```

If I use Cell.GetValue\<double\>() instead, I get a similar exception except 
```
Message=Cannot convert Sheet1!B1's value to System.Double
```

I am able to successfully access Cell.CachedValue, which gives me "34.299999999999997"

I also tried the latest prerelease 0.95.0-beta2, and it works.

So I am guessing that this is a formula parsing limitation or bug that was fixed between 0.94.2 and the latest prerelease, in which case this report may not be of use to you.

So I think I could either
 A) Stick with the latest release, and call GetValue inside an exception handler, and fall back to CachedValue if it fails -- does that sound like a reasonable tactic?
 B) Use the pre-release code

Any particular advice on choosing between these?

**Comment by mathlang** [comment]
So... it's been fixed? Just use 0.95 beta if you need the functionality now.

**Comment by Zorgle** [comment]
So you're saying I should use option (B) of my list above, right? That's reasonable safe to use in production code then?

**Comment by mathlang** [comment]
You need to weigh your different options. You can use workarounds on the release version, use the beta version, fork the release and cherry pick the particular fix you need, implement your own fixes, etc.

Personally I use a fork with all the latest bug fixes, adding my own fixes that have not been merged yet. 

That's the beauty of open source software!
