### ISSUE TITLE
XLCell.GetFormattedString does not respect the current culture

### ISSUE THREAD

**Issue by seritools** [ClosedXML/ClosedXML#1382]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [x] Feature

 (it depends)

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

`XLCell.GetFormattedString()` does not respect the current culture.

Looking through the source code, it seems that this code is called, which always formats with  `InvariantCulture`:

https://github.com/ClosedXML/ClosedXML/blob/a2f9074682574f5afd26f6744b4fc4fdbbbc97b5/ClosedXML/Extensions/FormatExtensions.cs#L15

**What is the expected behavior or new feature?**

Would it be possible to have this use the current culture instead? (Dunno if this is/should be supported and in scope)

## Reproducibility

Really just a call to `row.Cell(i).GetFormattedString();` on any cell that has a number format on it that may differ between regions/cultures (like decimal numbers)

**Comment by Pankraty** [comment]
I think it duplicates #1367. We'll get to this after 0.95 is released. @igitur am I right?

**Comment by igitur** [comment]
> I think it duplicates #1367. We'll get to this after 0.95 is released. @igitur am I right?

Correct.

**Comment by seritools** [comment]
Ohh, very nice! Managed to overlook that one.
