### ISSUE TITLE
Active tab is not set correctly on inserting sheet at the front

### ISSUE THREAD

**Issue by ChristophHornung** [ClosedXML/ClosedXML#1383]
**Do you want to request a *feature* or report a *bug*?**
- [X] Bug
- [ ] Feature

**Version of ClosedXML**

0.94.2 and latest build

**What is the current behavior?**

Given a new empty excel file with one sheet.

Execute the following code:

`this.worksheet = this.workbook.Worksheets.Add("NewFrontSheet", 1);`

Afterwards open the file in Excel. Note that both the first and second sheet are selected and the first sheet is active.

![image](https://user-images.githubusercontent.com/18534790/77944550-724a1880-72bf-11ea-9665-b35168c1c931.png)

If the sheet is added in position 2 note that the result will have only one sheet active and selected.

![image](https://user-images.githubusercontent.com/18534790/77944685-ac1b1f00-72bf-11ea-911f-249814374dc6.png)

**What is the expected behavior or new feature?**

The active worksheet should correctly be kept when adding a new sheet in first position.

**Did this work in previous versions of our tool?  Which versions?**

unknown

## Reproducibility

**Code to reproduce problem:**
```c#
class Program
	{
		private XLWorkbook workbook;
		private IXLWorksheet worksheet;

		static void Main(string[] args)
		{
			Program p = new Program();
			p.Test();
		}

		private void Test()
		{
			this.workbook = new XLWorkbook(@"T:\tmp\test.xlsx");
			this.worksheet = this.workbook.Worksheets.Add("NewFrontSheet", 1);
			this.workbook.Save();
		}
	}


```
[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/4404514/test.xlsx)
[result.xlsx](https://github.com/ClosedXML/ClosedXML/files/4404518/result.xlsx)

I assume this is an issue with how workbookView.activeTab is handled, since TabActive does return false for the single sheet directly after new XLWorkbook(..). The initial value in workbook.xml is not set (should default to 0). 

I hope this helps.

**Comment by Pankraty** [comment]
@_all you see what happens when the issue template is thoroughly filled? :D

**Comment by ChristophHornung** [comment]
I don't think #1384 fully resolves the general issue. Note that "IsActive" still returns false for the test.xlsx. From what I see "IsActive" should be set to the 1st tab if workbook.activeTab is not set (since according to the documentation the default value is 0) when loading the xlsx.

So another bug would occur in my opinion when after adding 'NewFrontSheet' it is set as TabSelected. This would result in it being also TabActive when saving while the correct behavior should be that the prior active tab should remain active.

**Comment by ChristophHornung** [comment]
To reproduce simply change the test method to

```C#
private void Test()
		{
			this.workbook = new XLWorkbook(@"T:\tmp\test.xlsx");
			this.worksheet = this.workbook.Worksheets.Add("NewFrontSheet", 1);
			this.worksheet.TabSelected = true;
			this.workbook.Save();
		}
```

Afterwards NewFrontSheet is the active tab
![image](https://user-images.githubusercontent.com/18534790/78002947-3901bf00-7338-11ea-9d04-920c338740da.png)

When changing the position to 2 the initial sheet remains active
'this.worksheet = this.workbook.Worksheets.Add("NewFrontSheet", 2);'

![image](https://user-images.githubusercontent.com/18534790/78003025-559df700-7338-11ea-80ff-d959cad9ce4e.png)

**Comment by ChristophHornung** [comment]
@Pankraty @igitur Should I open a separate issue now that this one is closed?

**Comment by Pankraty** [comment]
@ChristophHornung I think the main reason is that your file does not have any tab marked as active. How did you get such file? When I try to reproduce the issue on a fresh file there is always an active tab present. Moreover, if I manually remove `activeTab="1"` from the inner XML and open the file in Excel the first worksheet (index 0) becomes active - even though it was hidden before. 

So I think it is best to specify the active tab explicitly if it is not set.

**Comment by ChristophHornung** [comment]
@Pankraty test.xlsx was just "open excel (excel from office 365) - create new file (empty) - save"

**Comment by ChristophHornung** [comment]
@Pankraty Even if I open a new empty file and add an additional sheet and then re-select the first one the workbookview.activeTab is still unset.
[TwoSheetsFirstSelected.xlsx](https://github.com/ClosedXML/ClosedXML/files/4413336/TwoSheetsFirstSelected.xlsx)

**Comment by Pankraty** [comment]
Can you please check if the artifacts from [this build](https://ci.appveyor.com/project/ClosedXML/closedxml/builds/31870238/job/i6olny218kkkndmv/artifacts) fix the issue?

**Comment by ChristophHornung** [comment]
@Pankraty If I select the second sheet activeTab is set to '1'. 
[TwoSheetsSecondSelected.xlsx](https://github.com/ClosedXML/ClosedXML/files/4413347/TwoSheetsSecondSelected.xlsx)

**Comment by ChristophHornung** [comment]
@Pankraty Yes, that fixes the problem I am seeing. Thanks a lot! ✨
