### ISSUE TITLE
Workbook Connection lost

### ISSUE THREAD

**Issue by Muschti** [ClosedXML/ClosedXML#139]
first at all, thanks for the great work provided with ClosedXML. 

We fill in a 3rd party application a DataTable and update in this way Excel sheets. we use only a small part of the ClosedXML (address the cell, then insertTable where we pass our dataTable). in the predefined Excel (kind of a template) we prepare usually different worksheets containing data, graphs, pivots etc. not to our problem: when we create a worksheet with a connection to an other MSSQL DB, we loose this connection after "pasting" the data with ClosedXML. means the bottom section "locations where connections are used...." is empty and the table in the other workbook is of course no more updating. the manipulated data table is updated with the correct data. anyone else facing the same problem or is there a setup/trick we are missing? Thanks in advance for a good hint.

the connection we are loosing:
![27-12-2016 14-23-01](https://cloud.githubusercontent.com/assets/24792280/21500739/49778068-cc42-11e6-9b0c-74abb39100fe.jpg)

the different worksheets in Excel (we only insert data in RawData sheet with ClosedXML):
![27-12-2016 14-23-43](https://cloud.githubusercontent.com/assets/24792280/21500754/6913a15e-cc42-11e6-864d-59a7c67aab4d.jpg)

we were using in the past version 0.75 with .net FrameWork 2. here we "just" lost the connection. while trying to fix we updated to the newest ClosedXML Version 0.85 and .net FrameWork 4. the loss of the connection still goes on and besides that Excel started to "recover" Worksheets even if there was no data inserted on this worksheet or as well the sheet RawData which was working fine before. hope the explanations are more or less clear, not that easy to explain properly...

**Comment by igitur** [comment]
Worksheet connections are not supported yet. Hopefully one day, they will be supported. You just have to be patient with this.

Regarding the corrupt file, please post a code sample to illustrate how you end up with a corrupt file.

**Comment by Muschti** [comment]
Thanks for the answer. i will try to post an example during the next days.

**Comment by igitur** [comment]
Please test with the latest 0.86 release. https://github.com/ClosedXML/ClosedXML/releases/tag/0.86.0

**Comment by Muschti** [comment]
tested with 0.86 and at the moment i can't reproduce the corrupt Excel file anymore. so it seems the insert of data is running ok. thanks for the fix. 
the "Problem" or unsupported part of the work book connections of course is still there. do you have any idea about a "roadmap/date" when this could be available? or should i search for an alternative?

in each case, thx for the fast response

**Comment by igitur** [comment]
Thanks for letting me know. No, we don't have a roadmap. We work on issues as we get the time. You're welcome to try adding the support for workbook connections yourself and submitting a pull request.

**Comment by Muschti** [comment]
unfortunately i'm not that experienced in this field. i think i would mess up more then help but if i have a solution or workaround, of course i let you know
