### ISSUE TITLE
NullReferenceException in CellRangeReference.GetEnumerator()

### ISSUE THREAD

**Issue by StefanLFFM** [ClosedXML/ClosedXML#1390]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.95

**What is the current behavior?**

Calling Workbook.SaveTo(Stream) results in the exception mentioned above. The call to

Range.Worksheet.LastCellUsed()

in 

CellRangeReference.GetEnumerator() 

returns null.

**Did this work in previous versions of our tool?  Which versions?**

Yes / v0.94

## Reproducibility
 
Unfortunately I cannot provide the workbook that causes this issue. If necessary I can try to reproduce the behaviour with a file I can share. This might be difficult as the workbook is quite complex, so I would need some directions as to what might be the cause of this. The full callstack is attached.

[callstack.txt](https://github.com/ClosedXML/ClosedXML/files/4437882/callstack.txt)

**Comment by igitur** [comment]
We really need a minimal test case in order to reproduce the issue. Sorry, the call stack isn't enough.

**Comment by Pankraty** [comment]
**Repro**
```
[Test]
public void CanCalculate_WhenSheetISEmpty()
{
    var wb = new XLWorkbook();
    var sheet1 = wb.AddWorksheet("Sheet1");
    var sheet2 = wb.AddWorksheet("Sheet2");

    var cell = sheet1.FirstCell();
    cell.FormulaA1 = "=SUMIFS(Sheet2!B:B, Sheet2!C:C, 1)";

    Assert.AreEqual(0, cell.Value);
}
```

**Comment by StefanLFFM** [comment]
Is there any way to work around this issue? I can't use v94 because of [1157](https://github.com/ClosedXML/ClosedXML/issues/1157) and now I can't use v95 because of this.

**Comment by igitur** [comment]
@StefanLFFM Are you sure this worked in v0.94.2 ?

**Comment by StefanLFFM** [comment]
@igitur Yes I am sure. I was able to save the workbook without any problems but then the created file was corrupted due to the aforementioned issue.

**Comment by igitur** [comment]
Saving the file is different to the test case that @Pankraty generously created on your behalf. The test case fails even on 0.94. I don't think this is a regression, so the fix will go in for 0.96.

**Comment by StefanLFFM** [comment]
@igitur @Pankraty I tested your changes with my file. The problem with CellRangeReference.GetEnumerator() appears to be fixed. However the code now crashes in MathTrig.SumIf . Since p[0] is of type "ErrorExpression" in my case the foreach over "range" causes a NullReferenceException.

**Comment by igitur** [comment]
@StefanLFFM Please open a new issue and complete the issue template very thoroughly.
