### ISSUE TITLE
Remove my name from wiki

### ISSUE THREAD

**Issue by KnapSac** [ClosedXML/ClosedXML#1393]
Hi, 

Not sure whether this is the correct place, but I'm not really sure where else to place this. I saw I'm still mentioned at the top of the wiki homepage. As you have probably noticed, I haven't contributed anything in quite a few months. This is due to the fact that I've started my Bachelors degree, which takes up most of my time. Additionally, I've lost interest in contributing to this project at the moment. Maybe I'll return to this project at some point in the future, but I won't make any promises. So my question is: could you please remove my name from the wiki? Maybe I still have access to the Read The Docs backend, I don't know, but please feel free to revoke my access. If there is anything you need to know in regards to the new wiki, please let me know.

**Comment by igitur** [comment]
Ok, thanks for you contribution. It's given us a good base. I'll finalise this soon.
