### ISSUE TITLE
Workbook generated using closedxml, throwing error (Couldn't find 'xl/worksheets/sheet1.xml' ) while trying to read from other software

### ISSUE THREAD

**Issue by bhaskar2583** [ClosedXML/ClosedXML#140]
Workbook generated using closedxml, throwing error Couldn't find 'xl/worksheets/sheet1.xml' when we tried to read the file from another tool. However the same file has been working fine once we open the file in excel and save the file with/without any changes.

During the troubleshoot, I observed, Closed XML generating the first worksheet file name as sheet.xml at 'xl/worksheets/sheet.xml'.  It should generate as 'sheet1.xml'.

Once we are open the file in excel and saving back, excel is overriding the name of the file to sheet1.xml. The tool we are using seems to be looking for the 'sheet1.xml' name causing the issue.

**Comment by igitur** [comment]
Please post a code sample to illustrate the problem.

**Comment by igitur** [comment]
Also, using `sheet.xml` instead of `sheet1.xml` should not make the file corrupt.

**Comment by bhaskar2583** [comment]
Iam using the simple example provided in the tutorials.
public void Create(String filePath)
        {
            var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("Sample Sheet");
            worksheet.Cell("A1").Value = "Hello World!";
            workbook.SaveAs(filePath);
        }
when we run the above sample code, the xlsx file that was generated is having the issue when we try to use the same file in other softwares. As per my observation the reason is due to the "sheet.xml" file.

ClosedXML generating the first sheet as "sheet.xml" where as It should generate as "sheet1.xml".

To check the issue, please save the attached xlsx file extension to zip and extract it.  Later goto the path "PROCEDURE VISIT_2\xl\worksheets". You will find "sheet.xml"

Now open the xlsx file in excel and save it. Again change the extension to zip and extract the file. Goto the same path as mentioned above and you will find the "sheet1.xml". It seems it is the standard name for the sheet. 

The excel files that are geenerated with closedxml are missing this. Even the workbooks that are having multiple sheets are creating as (sheet.xml, sheet2.xml, sheet3.xml etc..). 

Hope this would helps. Please let me know.

[PROCEDURE VISIT_2.xlsx](https://github.com/ClosedXML/ClosedXML/files/685294/PROCEDURE.VISIT_2.xlsx)

**Comment by bhaskar2583** [comment]
There is nothing like file correct. Only the issue is with the generating xml file name for sheet1.

**Comment by igitur** [comment]
Please grab the latest code from the `develop` branch in the git repo and see if it solves your problem.

**Comment by igitur** [comment]
Please test with the latest 0.86 release. https://github.com/ClosedXML/ClosedXML/releases/tag/0.86.0

**Comment by igitur** [comment]
Reopen the issue if you still experience it with v0.86 or higher.

**Comment by huezodaniel** [comment]
Hi all, i am having the same issue trying to read from a file generated by ClosedXML library using SheetsJS on javascript. Seems that something happens because i can see the sheetNames but i can not get any info from the sheets. Any luck?

**Comment by igitur** [comment]
@huezodaniel Please log with SheetJS.
