### ISSUE TITLE
Non empty sheet is classified as empty.

### ISSUE THREAD

**Issue by NguyenTam** [ClosedXML/ClosedXML#1401]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**

e.g. 0.95

**What is the current behavior?**
ClosedXML sheet.IsEmpty() returned true, even some sheets are not empty.

**Did this work in previous versions of our tool?  Which versions?**
Yes

## Reproducibility

Here is my repository to reproduce bug:  https://github.com/NguyenTam/closedxml_test_sheet_methods

**Code to reproduce problem:**
```c#
namespace closedxml_empty_sheet_test
{
    class Program
    {
        static void Main(string[] args)
        {
            ClosedXML.Excel.XLWorkbook workbook = null;
            workbook = new ClosedXML.Excel.XLWorkbook("../../WaterPumpSystem.xlsx");
            foreach (var sheet in workbook.Worksheets)
            {
                if (sheet.IsEmpty())
                {
                    System.Console.WriteLine(sheet.Name + " is empty");
                }
                else
                {
                    System.Console.WriteLine(sheet.Name + " is NOT empty");
                }
            }
        }
    }
}

```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[WaterPumpSystem.xlsx](https://github.com/ClosedXML/ClosedXML/files/4515151/WaterPumpSystem.xlsx)

**Comment by igitur** [comment]
Fixed in #1399

**Comment by igitur** [comment]
v0.95.1 has been deployed to NuGet. Please test and let me know if this solves your problem.

**Comment by NguyenTam** [comment]
Upgrading from 0.95.0 to 0.95.1 solved this problem (tested). Thanks
