### ISSUE TITLE
Getting this exp "Specified argument was out of the range of valid values." while opening an excel file

### ISSUE THREAD

**Issue by claudiobottari** [ClosedXML/ClosedXML#141]
I have these files that contais some text in the footer (about 200 chars) and when I execute:

wb = new XLWorkbook(fileStream);

I get this exception:

Specified argument was out of the range of valid values.
Parameter name: Headers and Footers cannot be longer than 255 characters (including style markups)

Headers and Footers cannot be longer than 255 characters (including style markups)

   at ClosedXML.Excel.XLHeaderFooter.GetText(XLHFOccurrence occurrence)
   at ClosedXML.Excel.XLHeaderFooter.SetAsInitial()
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream)

I see that I get modify the footer with ClosedXML but not without opening it first... kinda stuck. Anybody got the same issue?

**Comment by igitur** [comment]
Please attach an example file.

**Comment by claudiobottari** [comment]
Sadly I can't publish it :/

I tried to replicate the problem but obviously Excel won't save and header/footer that exceeds 255 chars. I'll try again later with some other tool...

**Comment by igitur** [comment]
Can't you remove all confidential information when generating the file and then upload it?

**Comment by igitur** [comment]
Looking more at your problem, I think it's fairly obvious that your header or footer is too long. I think the error message is quite clear:

`Headers and footers cannot be longer than 255 characters (including style markups)`

Notice the `including style markups`. The style markups are added by ClosedXML itself and configures the font.  Your header/footer should be short enough that when the style markups are added, it should still be less than 255 characters.
