### ISSUE TITLE
Bad performance when setting borders

### ISSUE THREAD

**Issue by ANahr** [ClosedXML/ClosedXML#1416]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug/Performance
- [ ] Feature

**Version of ClosedXML**

0.95.2

**What is the current behavior?**

Setting border styles is extremely slow when the amount is non-trivial.
In the attached example ClosedXml takes more than 2:30 min to set the borders

**What is the expected behavior or new feature?**

Setting the same borders in Excel takes only a fraction of a second. I would expect ClosedXml to offer similar performance or at least performance in the same ballpark.

## Reproducibility

**Code to reproduce problem:**
```c#
using System;
using System.Diagnostics;
using ClosedXML.Excel;

namespace ExportExcelClosedXML
{
    class BorderPerf
    {
        static void Main()
        {
            Stopwatch watch = new Stopwatch();
            Stopwatch watch2 = new Stopwatch();
            watch.Start();

            var workbook = new XLWorkbook();
            var ws = workbook.Worksheets.Add("Table");

            watch2.Start();


            // The following block takes more than 2:30 min
            {
                var rngTable2 = ws.Range("B1:CU10000");

                var border = rngTable2.Style.Border;

                border.OutsideBorder = XLBorderStyleValues.Medium;
                border.OutsideBorderColor = XLColor.Black;

                border.InsideBorder = XLBorderStyleValues.Medium;
                border.InsideBorderColor = XLColor.Black;
            }

            watch2.Stop();

            workbook.SaveAs("TestClosedXML.xlsx");

            watch.Stop();
            Console.WriteLine("Total: " + watch.Elapsed);
            Console.WriteLine("Styles: " + watch2.Elapsed);
            Console.ReadLine();
        }
    }
}
```

**Comment by Pankraty** [comment]
> I would expect ClosedXml to offer similar performance or at least performance in the same ballpark.

This is a really strange assumption, considering the difference in budgets, team sizes, and overall product maturity :)

Anyway, I've managed to improve this from 2:33 to approximately 0:09.

**Comment by ANahr** [comment]
> I would expect ClosedXml to offer similar performance or at least performance in the same ballpark.
> 
> This is a really strange assumption, considering the difference in budgets, team sizes, and overall product maturity :)
> Anyway, I've managed to improve this from 2:33 to approximately 0:09.

Sorry if that sounded too harsh ;)
Very nice improvement in a very short time.

Actually I've been trying something to circumvent the problem meanwhile. However that "feels" pretty "hackish", but only needs 2.5 secs :)
```c#
            // Takes about 0:02.5 sec
            {
                var rngTable2 = ws.Range("B1:CU10000");

                IXLCell reference = rngTable2.FirstCell();
                reference.Style.Border.OutsideBorder = XLBorderStyleValues.Medium;
                reference.Style.Border.OutsideBorderColor = XLColor.Black;
                var newStyle = reference.Style;

                rngTable2.Style.Border = newStyle.Border;
            }
```

**Comment by Pankraty** [comment]
Good job! It cannot be used as a generic solution but if it solves your problem - that's great.

**Comment by ANahr** [comment]
However I fear that this might break in the future because it somewhat depends on implementation details.

**Comment by Pankraty** [comment]
No worries, this is a valid code, relying on a public API and the behavior we're going to keep. You can use it safely.
