### ISSUE TITLE
Insert row performance

### ISSUE THREAD

**Issue by peetn** [ClosedXML/ClosedXML#1419]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.2

**What is the current behavior?**

Inserting a single row takes about 3 seconds on average. Initial insert typically takes 4 to 5 seconds, even had cases of > 6s.
Inserting multiple rows at once takes about the same duration.
I'm opening my workbook with [XLEventTracking.Disabled](https://github.com/ClosedXML/ClosedXML/wiki/Turning-off-events).
I tried with `XLEventTracking.Enabled` as well but saw not much difference. All results attached are with `XLEventTracking.Disabled`.
During the execution of the code (isolated sample in attachment), the computer's fan is working really hard, indicating heavy load I assume.
My file was not big (X24 is last cell used including formatting).
Inserting 106 rows took 5'40", on average about 3 seconds. 
Attachmens below:
- Stopwatch output attached in txt file.
- Input file attached (SampleFile.xlsx).
- Output file (= updated input file including rows) attached (SampleFile_output.xlsx)

**What is the expected behavior or new feature?**

ClosedXML is super fast, I understand that inserting (and deleting) rows impact performance because of formula recalculation. But apparently [it should be faster than 3s](https://github.com/ClosedXML/ClosedXML/issues/240#issuecomment-621768846).

**Did this work in previous versions of our tool?  Which versions?**

I guess not, I remember to Clear() rows instead of deleting them because Clear() took 0 seconds, and deleting also took very long.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
    class Program
    {
        private static Stopwatch overallStopwatch = new Stopwatch();

        static void Main(string[] args)
        {
            List<string> names = new List<string>() { "Id", "IsDeleted", "MasterRecordId", "Name", "Type", "TypeId", "Type.Name", "OldId", "Old.External_Id", "MyStreet", "MyCity", "MyState", "MyPostalCode", "MyCountry", "MyLatitude", "MyLongitude", "MyGeocodeAccuracy", "DemoStreet", "DemoCity", "DemoState", "DemoPostalCode", "DemoCountry", "DemoLatitude", "DemoLongitude", "DemoGeocodeAccuracy", "Phone", "Fax", "WorkNumber", "Website", "Photo", "ABC", "Industry", "AR", "NOE", "Fakeship", "TS", "Description", "AZERTY", "QUERTY", "FakeId", "Fake.Username", "Fake.Email", "Fake.FederationIdentifier", "CreatedDate", "CreatedById", "LastModifiedDate", "LastModifiedById", "SystemMod", "ActivityDate", "ViewedDate", "ReferencedDate", "IsPortal", "saw", "sawid", "WorkSource", "sDesc", "Mobile", "Email", "aNumber", "aForm", "aDate", "aLanguage", "External_a_ID", "arisk", "ascore", "bscore", "Turn", "abcCode", "abcDescription", "thatNumber", "thaterror", "Top", "Down", "ccount", "sw", "crrr", "cfff", "off", "paper", "OCR", "CAMT", "werken", "werkenenzo", "niets", "iets", "fiets", "wat", "dat", "nat", "zat", "klad", "bad", "rat", "blad", "krat", "Status", "wrat", "spat", "plat", "patat", "My_City", "My_PreviousName", "My_Country", "My_Manager", "My_Managerr.Username", "My_Managerr.Email", "My_Managerr.id", "My_Description", "My_Documents_Folder", "My_Func", "My_Phone", "My_family", "My_car", "My_Fake", "My_Partner", "My_pct", "My_Grade", "My_Region", "My_State", "My_Street", "My_shop", "My_Zip" };

            string filePath = "SampleFile.xlsx";
            string sheetName = "Dummy";
            int headerRow = 1;
            using (XLWorkbook xLWorkbook = new XLWorkbook(filePath, XLEventTracking.Enabled))
            {
                IXLWorksheet sourceWorksheet = xLWorkbook.Worksheets.FirstOrDefault(x => x.Name == sheetName) ?? throw new Exception("Excel Sheet does not exist");
                IXLWorksheet targetWorksheet = sourceWorksheet.CopyTo("target", sourceWorksheet.Position + 1);

                // Speeds up performance!
                // Build table of contents of all non-header rows by 'Name' for quick row retrieval
                Dictionary<string, IXLCell> tableOfContents = new Dictionary<string, IXLCell>();
                targetWorksheet.Column(1).Cells(x => x.Address.RowNumber > headerRow && x.CachedValue != null).ToList().ForEach(x =>
                {
                    if (!tableOfContents.ContainsKey(x.CachedValue.ToString()))
                    {
                        tableOfContents[x.CachedValue.ToString()] = x;
                    }
                });

                Console.WriteLine($"Starting... (last cell used: {sourceWorksheet.LastCellUsed(includeFormats: true).Address.ToString()})");
                IXLCell firstCellOfLastProcessedRow = targetWorksheet.Cell(headerRow, 1);
                int insertCount = 0;
                foreach (string name in names)
                {
                    #region Process data row
                    IXLCell firstCellOfCurrentRow = tableOfContents.ContainsKey(name) ? tableOfContents[name] : null;
                    if (firstCellOfCurrentRow == null)
                    {
                        firstCellOfCurrentRow = InsertFormattedRowBelow(firstCellOfLastProcessedRow);
                        insertCount++;
                        firstCellOfCurrentRow.Value = name;
                    }
                    firstCellOfLastProcessedRow = firstCellOfCurrentRow;
                    #endregion Process data row
                }
                Console.WriteLine($"Finished... rows inserted: {insertCount} - total duration: {overallStopwatch.Elapsed}");

                xLWorkbook.Save();
            }
        }

        private static IXLCell InsertFormattedRowBelow(IXLCell startCell)
        {
            while (startCell.IsMerged() && (startCell.CachedValue != null && startCell.CachedValue.ToString() != string.Empty))
            {
                startCell = startCell.CellBelow();
            }

            // We will just work on the next row if it is not used
            IXLRow firstOfNewRows = startCell.WorksheetRow().RowBelow();
            if (firstOfNewRows.CellsUsed().Any())
            {
                // If used, insert one instead
                Stopwatch stopwatch = new Stopwatch();
                stopwatch.Start();
                overallStopwatch.Start();
                Console.Write("Insert row: ");
                firstOfNewRows = startCell.WorksheetRow().InsertRowsBelow(1).First();
                overallStopwatch.Stop();
                stopwatch.Stop();
                Console.WriteLine(stopwatch.Elapsed);
            }
            return firstOfNewRows.FirstCell();
        }
    }
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[performance_output.txt](https://github.com/ClosedXML/ClosedXML/files/4562638/performance_output.txt)
[SampleFile.xlsx](https://github.com/ClosedXML/ClosedXML/files/4562645/SampleFile.xlsx)
[SampleFile_output.xlsx](https://github.com/ClosedXML/ClosedXML/files/4562649/SampleFile_output.xlsx)

**Comment by igitur** [comment]
Was this as slow in 0.94.2?

**Comment by peetn** [comment]
Update: I think I found the issue.
Inserts only take `00:00:00.0061641` seconds when I remove the dictionary from the code.
That I used to find cells quicker. But I found a way to fast retrieve cells without dictionary by specifying the exact column and searching CellsUsed(lambda) instead of Cells(lamba).

Mea culpa.
Now it is flying!

**Comment by Pankraty** [comment]
So you basically instantiated one million cells from the column A when building a table of contents, and their shifting took around 3 seconds?

**Comment by igitur** [comment]
Another example of why we require MINIMAL code samples, excluding hacks and workarounds.
