### ISSUE TITLE
Support GetValue<T> where T as nullable int

### ISSUE THREAD

**Issue by Andrioden** [ClosedXML/ClosedXML#1430]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

**Version of ClosedXML**
0.95.2

**What is the current behavior?**
``` c#
int? value = Sheet.Cell(0, 0).GetValue<int?>();
// Throw System.FormatException "Cannot convert 'Car loans'!C4's value to System.Nullable`1[System.Int32]"Message [string]:"
```

**What is the expected behavior or new feature?**
``` c#
int? value = Sheet.Cell(0, 0).GetValue<int?>();
// value == null if empty, and the number otherwise
```

**Did this work in previous versions of our tool?  Which versions?**
I assume not

**Comment by igitur** [comment]
cc @Pankraty 

This is a good idea. In the meantime you can use `cell.TryGetValue<int>()` and handle the rest if it returns `false`.

I'll  add support for nullable types, but we have to think about some edge cases. 

Your opinion on these:
`cell.SetValue(2.5).GetValue<double?>() == 2.5`
`cell.SetValue("2.5").GetValue<double?>() == 2.5`
`cell.SetValue("2.5").GetValue<int?>() == 3`
`cell.Clear().GetValue<int?>() == null`
`cell.SetValue("text").GetValue<int?>()`  throws exception as always, or alternatively `== null`.

**Comment by Andrioden** [comment]
I would expect 

`cell.SetValue("2.5").GetValue<int?>() == 3`
and
`cell.SetValue("text").GetValue<int?>()`

To throw an exception. Otherwise all .GetValue() calls should never throw an exception. However, i have not used your library that much so its not clear what your balance between "Just return something" and "throw exception agressivly" is.

**Comment by Andrioden** [comment]
Okei, then it certainly makes sense that

`cell.SetValue("2.5").GetValue<int?>() == 3`
