### ISSUE TITLE
System.InvalidCastException when evaluating formula "IF(COUNTIF(N14:N15, 1) > 0, 1, 0)"

### ISSUE THREAD

**Issue by timka3115** [ClosedXML/ClosedXML#1431]
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.95.2

**What is the current behavior?**

I'm getting "System.InvalidCastException: 'Unable to cast object of type 'System.Double' to type 'System.String'.'" exception when tried to evaluate the following formula ""IF(COUNTIF(N14:N15, 1) > 0, 1, 0)"" using method XLWorkbook.RecalculateAllFormulas()

**What is the expected behavior or new feature?**

Method XLWorkbook.RecalculateAllFormulas() should works as expected and don't throw any exceptions.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
    var workbook = new XLWorkbook(pathToExcelFile);
    workbook.RecalculateAllFormulas();
}
```
- [x] I attached a sample spreadsheet.
[calculate_formula_test.xlsx](https://github.com/ClosedXML/ClosedXML/files/4633891/calculate_formula_test.xlsx)

**Comment by igitur** [comment]
Is it the IF() or the COUNTIF function that raises the error? Please investigate and let me know. Thanks

**Comment by timka3115** [comment]
It is COUNTIF
![COUNTIF](https://user-images.githubusercontent.com/5507155/82044120-6bcc0080-96b5-11ea-9041-ef16ffcc9d74.PNG)
