### ISSUE TITLE
Object reference not set when saving a workbook

### ISSUE THREAD

**Issue by jonlegras** [ClosedXML/ClosedXML#1435]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.2

**What is the current behavior?**

Object reference not set to an instance of an object when saving a workbook.

I have 2 similar workbooks that I am trying to access using ClosedXML.
The first opens correctly, I can edit it and save it.
The second open correctly, I appear to be able to edit it, but when I save it, I get an object reference error, but I can't see why - I assume there's something specific about this workbook that is causing the error within ClosedXML, but I can't see where its coming from.
I can open both sheets without problems in Excel - the problem is when I try to use ClosedXML.

I am attaching the second sheet which is causing the problems - not this sheet was supplied to me and I need to update it using code, its a fairly complex workbook, with hidden sheets.

[SPECCARD.xlsx](https://github.com/ClosedXML/ClosedXML/files/4645398/SPECCARD.xlsx)

**What is the expected behavior or new feature?**

Should just save.

**Did this work in previous versions of our tool?  Which versions?**

No/v0.94.2

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**

```c#
      public void DoSheets()
        {
            string specCardPath = IO.Path.Combine(@"C:\Tests", "ClosedXML");
            string specCardBase = "SPECCARD";

            string FullInFile = IO.Path.Combine(specCardPath, specCardBase) + ".xlsx";
            string FullOutFileTemp = IO.Path.Combine(specCardPath, "Done", "XXXXXX") + "123456" + ".xlsx";

            if (IO.File.Exists(FullOutFileTemp)) IO.File.Delete(FullOutFileTemp);
            IO.File.Copy(FullInFile, FullOutFileTemp);

            IXLRange range;
            IXLRow row;
            IXLColumn col;
            IXLCell cell;

            XLWorkbook wkb = new XLWorkbook(FullOutFileTemp);
            IXLWorksheet wks;

            foreach (var sheet in wkb.Worksheets)
            {
                string currentSheet = sheet.Name.ToUpper().PadRight(4).Substring(0, 4);

                Console.WriteLine("{0} - {1}", currentSheet, sheet.Name);
            }

            bool Saved = false;
            try
            {
                wkb.Save(false);
                wkb.SaveAs(FullOutFileTemp);
                Saved = true;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Unable to save excel document\r\n\r\n" + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                Console.WriteLine(ex.Message);
            }

        }
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Your code is not a minimal sample. And I can't even run it. Paste *minimal* code that fully reproduces the problem.

**Comment by igitur** [comment]
I'll reopen when the code sample follows the requested standards.

**Comment by jonlegras** [comment]
using System;
using IO = System.IO;

using ClosedXML.Excel;

namespace ClosedXMLSaveTest
{
    class Program
    {
        static void Main(string[] args)
        {
            DoSheets();
        }

        static void DoSheets()
        {
            string specCardPath = IO.Path.Combine(@"C:\Tests", "ClosedXML");
            string specCardBase = "SPECCARD";
            string FullInFile = IO.Path.Combine(specCardPath, specCardBase) + ".xlsx";
            string FullOutFileTemp = IO.Path.Combine(specCardPath, "Done", "XXXXXX") + "123456" + ".xlsx";

            if (IO.File.Exists(FullOutFileTemp)) IO.File.Delete(FullOutFileTemp);
            IO.File.Copy(FullInFile, FullOutFileTemp);

            IXLRange range;
            IXLRow row;
            IXLColumn col;
            IXLCell cell;

            XLWorkbook wkb = new XLWorkbook(FullOutFileTemp);
            IXLWorksheet wks;

            foreach (var sheet in wkb.Worksheets)
            {
                string currentSheet = sheet.Name.ToUpper().PadRight(4).Substring(0, 4);
                Console.WriteLine("{0} - {1}", currentSheet, sheet.Name);
            }
            
            try
            {
                wkb.Save(false);                                
            }
            catch (Exception ex)
            {                
                Console.WriteLine(ex.Message);
            }
        }
    }
}

**Comment by jonlegras** [comment]
I am attaching an updated bit of code, full console app rather than a snippet.

using System;
using IO = System.IO;

using ClosedXML.Excel;

namespace ClosedXMLSaveTest
{
    class Program
    {
        static void Main(string[] args)
        {
            DoSheets();
        }

        static void DoSheets()
        {
            string specCardPath = IO.Path.Combine(@"C:\Tests", "ClosedXML");
            string specCardBase = "SPECCARD";
            string FullInFile = IO.Path.Combine(specCardPath, specCardBase) + ".xlsx";
            string FullOutFileTemp = IO.Path.Combine(specCardPath, "Done", "XXXXXX") + "123456" + ".xlsx";

            if (IO.File.Exists(FullOutFileTemp)) IO.File.Delete(FullOutFileTemp);
            IO.File.Copy(FullInFile, FullOutFileTemp);

            IXLRange range;
            IXLRow row;
            IXLColumn col;
            IXLCell cell;

            XLWorkbook wkb = new XLWorkbook(FullOutFileTemp);
            IXLWorksheet wks;

            foreach (var sheet in wkb.Worksheets)
            {
                string currentSheet = sheet.Name.ToUpper().PadRight(4).Substring(0, 4);
                Console.WriteLine("{0} - {1}", currentSheet, sheet.Name);
            }
            
            try
            {
                wkb.Save(false);                                
            }
            catch (Exception ex)
            {                
                Console.WriteLine(ex.Message);
            }
        }
    }
}

**Comment by igitur** [comment]
```
  string specCardPath = IO.Path.Combine(@"C:\Tests", "ClosedXML");
        string specCardBase = "SPECCARD";
        string FullInFile = IO.Path.Combine(specCardPath, specCardBase) + ".xlsx";
        string FullOutFileTemp = IO.Path.Combine(specCardPath, "Done", "XXXXXX") + "123456" + ".xlsx";

        if (IO.File.Exists(FullOutFileTemp)) IO.File.Delete(FullOutFileTemp);
        IO.File.Copy(FullInFile, FullOutFileTemp);

        IXLRange range;
        IXLRow row;
        IXLColumn col;
        IXLCell cell;
```

I don't need all of that.

**Comment by jonlegras** [comment]
Do you have any idea why ClosedXML won't save the sheet i attached and gives an undefined object error?

**Comment by igitur** [comment]
I traced it to a ClosedXML bug in the print areas, specifically on the PRODUCT sheet. Until this is fixed, you'll have to remove the print areas from your file.

**Comment by jonlegras** [comment]
Ok I've tried that - selected that sheet, removed print areas (in excel) and saved the sheet,
When I now run my application,  it errors on the save command with 'the given key was not present in the dictionary'
I can see that this error has been reported by someone else some time again with an older version of closedxml.
Any thoughts?
TIA.

**Comment by jonlegras** [comment]
[SPECCARD-NEW.xlsx](https://github.com/ClosedXML/ClosedXML/files/5124897/SPECCARD-NEW.xlsx)

The attached file should have the print areas cleared, but errors when I try to save it - given key not present.
