### ISSUE TITLE
Can't compare files in Spreadsheet Compare created with ClosedXML

### ISSUE THREAD

**Issue by dontbyte** [ClosedXML/ClosedXML#1436]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
0.95.1

**What is the current behavior?**
_Spreadsheet Compare 2013_ error "Error opening workbook. Attempted to read past the end of the stream." when trying to compare files created with ClosedXML.

**Did this work in previous versions of our tool?  Which versions?**
No

## Reproducibility
Create at least one file with ClosedXML and try to compare it with another file using Spreadsheet Compare (installed by default to `C:\Program Files (x86)\Microsoft Office\Office16\DCF\SPREADSHEETCOMPARE.EXE`). Software will crash instantly with the error above.

**Code to reproduce problem:**
```c#
public void Main()
{
            var _ExcelWb = @"C:\Temp\Mappe1.xlsx";
            var _ClosedXmlWb = @"C:\Temp\NewMappe1.xlsx";
            var _FilesToCompare = @"C:\Temp\FilesToCompare.txt";
            var _SSCPath = @"C:\Program Files (x86)\Microsoft Office\Office16\DCF\SPREADSHEETCOMPARE.EXE";

            var _Workbook = new XLWorkbook(_ExcelWb);
            var _Sheet = _Workbook.AddWorksheet("NewSheet");
            _Workbook.SaveAs(_ClosedXmlWb);

            File.WriteAllLines(_FilesToCompare, new List<string>() { _ExcelWb, _ClosedXmlWb });
            System.Diagnostics.Process.Start(_SSCPath, _FilesToCompare);
}
```

Source file to compare to (created with Excel): 
[Mappe1.xlsx](https://github.com/ClosedXML/ClosedXML/files/4656182/Mappe1.xlsx)

**Comment by dontbyte** [comment]
I figured out that it's because of the namespace in the worksheet files.

As soon as I replace 
`xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main"` 
with 
`xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"`
and therefor remove all `x:` prefixes it works perfectly fine.

**Comment by igitur** [comment]
Sounds like a bug in that Spreadsheet Compare then?

**Comment by igitur** [comment]
After reading the read on the OpenXml SDK issue, it's clear that this isn't a ClosedXML issue.

**Comment by dontbyte** [comment]
Spreadsheet Compare issue [#86 ](https://sourceforge.net/p/spreadshcompare/bugs/86/)"Can't compare files when using namespace prefix in sheet xml file(s)"
