### ISSUE TITLE
XLWorksheet.Rows() performance is not good if document has >100к rows

### ISSUE THREAD

**Issue by timka3115** [ClosedXML/ClosedXML#1438]
**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x] Feature

**Version of ClosedXML**
Current

**What is the current behavior?**
XLWorksheet.Rows() method works too slowly (3 sec, Intel Core i7) if I open excel file with >100 000 rows 

**What is the expected behavior or new feature?**

Method Rows() should works much faster

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

This is current implementation of XLWorksheet.Rows() method:

```c#
public IXLRows Rows()
        {
            var retVal = new XLRows(this, StyleValue);
            var rowList = new List<Int32>();

            if (Internals.CellsCollection.Count > 0)
                rowList.AddRange(Internals.CellsCollection.RowsUsed.Keys);

            if (Internals.RowsCollection.Count > 0)
                rowList.AddRange(Internals.RowsCollection.Keys.Where(r => !rowList.Contains(r)));

            foreach (int r in rowList)
                retVal.Add(Row(r));

            return retVal;
        }
```

Notice that `rowList` is a `List` and we use `Contains()` in the lambda expression:
`rowList.AddRange(Internals.RowsCollection.Keys.Where(r => !rowList.Contains(r)));`
Obviously that if `rowList` will have 100 000 items or more than `Contains` is very slow. 
It's better for large `Internals.RowsCollection.Keys` collection to declare variable `rowList` as `Dictionary`, not `List`. In this case `rowList.Contains` we will replace to `rowList.ContainsKey` and it will work much faster.

**Comment by igitur** [comment]
Thanks. Sounds like a promising suggestion. Please prepare a pull request.

**Comment by igitur** [comment]
Also consider `HashSet<Int32>`, which might be even better than a dictionary.
