### ISSUE TITLE
exception: `System.IndexOutOfRangeException`

### ISSUE THREAD

**Issue by jupe** [ClosedXML/ClosedXML#144]
Loading xlsx file causes exception:

```
Debug: Open excel file: D:\examples\MITTAPOYTAKIRJA.xlsx
Warn: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at ClosedXML.Excel.XLWorkbook.GetFormula(String value)
   at ClosedXML.Excel.XLWorkbook.LoadConditionalFormatting(ConditionalFormatting conditionalFormatting, XLWorksheet ws, Dictionary`2 differentialFormats)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName)
   at ClosedXML.Excel.XLWorkbook.Load(String file)
   at ClosedXML.Excel.XLWorkbook..ctor(String file, XLEventTracking eventTracking)
   at ClosedXML.Excel.XLWorkbook..ctor(String file)
```

Loading another kind of excel file seems to work, so this is just some corner case. File was originally created with microsoft excel, and converted to xlsx file with Libre Office (Versio: 5.1.6.2).

**Comment by igitur** [comment]
Which version of ClosedXML are you using?

**Comment by jupe** [comment]
0.85 and also 0.86 seems to reproduce exception as well..

**Comment by igitur** [comment]
Please attach the problematic file.

**Comment by jupe** [comment]
I would like to, unfortunately that file contains secret content.. I could try to create new file which reproduce this exception later this week..

**Comment by igitur** [comment]
Ok, I understand. Looking at the stack trace, it looks like something to do with conditional formatting.

**Comment by jupe** [comment]
This looks reproduce exception:
[issue_#144.zip](https://github.com/ClosedXML/ClosedXML/files/696532/issue_.144.zip)

**Comment by igitur** [comment]
Please check out https://github.com/igitur/ClosedXML/tree/issue144-load-conditionalformating and see if this code base solves your issue.

**Comment by bwiltfong** [comment]
[Rewards+_Cycle3_Week1_SC15_Report.xlsx](https://github.com/ClosedXML/ClosedXML/files/2946440/Rewards%2B_Cycle3_Week1_SC15_Report.xlsx)
I am receiving the same error on open.

**Comment by igitur** [comment]
@bwiltfong Log a new issue please.

**Comment by pmathbliss** [comment]
Make sure your DataTable has columns. I was trying to insert an empty table.

` if (table.Columns.Count == 0)
  {
       table.Columns.Add(new DataColumn("No Data"));
  }`
