### ISSUE TITLE
FirstRowUsed is calling LastRowUsed

### ISSUE THREAD

**Issue by lorenz-haenggi-axa** [ClosedXML/ClosedXML#1443]
description:
in XLWorksheet I had the issue in release 0.95.2 that FirstRowUsed is calling LastRowUsed
this is very bad and results in a null response at the end.

release 0.95.2

refernce to code
https://github.com/ClosedXML/ClosedXML/blob/6bc5cb51d14810a7d599f3c2095bf82d17964cb0/ClosedXML/Excel/XLWorksheet.cs#L270

**Comment by igitur** [comment]
Fill out the full template.
