### ISSUE TITLE
Upgrade from 0.94.2 to 0.95.3

### ISSUE THREAD

**Issue by sterenas** [ClosedXML/ClosedXML#1449]
Using ClosedXML 0.94.2 within a VB.NET project in VS 2019, no issues.
NuGet Packages shows 0.95.3 is available.  If I try to upgrade, it wants to install Microsoft .CSharp..4.7.0 (upgraded several times in the past and this wasn't a requirement).
I fear if I install Microsoft.CSharp, it'll add a bunch of dependencies to my project.
Is this a bug or something new and required to keep upgrading to future versions?
Thanks!
Sergio

**Comment by igitur** [comment]
`Microsoft.CSharp` is required to support the `dynamic` keyword. What target framework are you building on? And does it indeed add additional dependencies, or are you just fearing it will do. Which dependencies?

Next time, please populate the issue template that we created with lots of effort.

**Comment by sterenas** [comment]
Thanks! I was fearing it'd add several references but it doesn't.  Tested it already.
Targeting .net 4.7.2
Sorry about not filling the template. Will do next time.
