### ISSUE TITLE
System.ApplicationException in ClosedXML

### ISSUE THREAD

**Issue by hflores01** [ClosedXML/ClosedXML#145]
When I run the next code:

            DataTable datos = _procedimientosService.ObtenerDatosParaExcel(sql); //return a DataTable
            datos.TableName = "REPORT";
            using (XLWorkbook wb = new XLWorkbook(XLEventTracking.Disabled))
            {

                wb.Worksheets.Add(datos);
                wb.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                wb.Style.Font.Bold = true;

                Response.Clear();
                Response.Buffer = true;
                Response.Charset = "";
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment;filename= REPORT_EXCEL.xlsx");

                using (MemoryStream MyMemoryStream = new MemoryStream())
                {
                    wb.SaveAs(MyMemoryStream); // The error occurs here
                    MyMemoryStream.WriteTo(Response.OutputStream);
                    Response.Flush();
                    Response.End();
                }
            }

I have errors:

The attribute 'width' has invalid value '5.720625'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[1]

The attribute 'width' has invalid value '10.680625'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[2]

The attribute 'width' has invalid value '54.300625'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[3]

The attribute 'width' has invalid value '5.560625'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[4]

The attribute 'width' has invalid value '7.590625'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[5]

The attribute 'left' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]

The attribute 'right' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]

The attribute 'top' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]

The attribute 'footer' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]

please help me.

**Comment by vbjay** [comment]
Make sure you are using the latest package.

**Comment by igitur** [comment]
Please try `wb.SaveAs(MyMemoryStream, false);` and let me know whether it works and whether the file that it generates is a valid file. If you're able to attach the file, that would help too.

The `false` parameter disables validation when saving the Excel package.

**Comment by hflores01** [comment]
Hi, I changed to

                using (MemoryStream MyMemoryStream = new MemoryStream())
                {
                    wb.SaveAs(MyMemoryStream, false);
                    MyMemoryStream.WriteTo(Response.OutputStream);
                    Response.Flush();
                    Response.End();
                }
Now there is no error (exception), but not download the excel file.

I use the version 0.86.0.0

Thanks a lot.

**Comment by igitur** [comment]
If you open the file in Excel, does Excel complain about anything?

**Comment by hflores01** [comment]
no download anything.

**Comment by hflores01** [comment]
I calling from cshtml file:

            var url;
            url = '@Url.Action("ExportarExcel", "Reportes")';
            var filtroData = JSON.stringify({ 'columnas': columnas, 'filtro': filtro });
            $.ajax({
                contentType: 'application/json;  charset=utf-8',
                data: filtroData,
                type: 'POST',
                url: url
            });

**Comment by igitur** [comment]
Save it to file directly then and check in Excel:
`wb.SaveAs("c:\test.xlsx", false);`

**Comment by hflores01** [comment]
I changed to:
                using (MemoryStream MyMemoryStream = new MemoryStream())
                {
                    wb.SaveAs("c:\test.xlsx", false);
                    MyMemoryStream.WriteTo(Response.OutputStream);
                    Response.Flush();
                    Response.End();
                }
but now return the nex exception:

Invalid characters in the path.

   en System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   en System.IO.Path.GetDirectoryName(String path)
   en ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate) en C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:línea 473
   en Juris.WebApp.Controllers.ReportesController.ExportarExcel(Dictionary`2 columnas, FiltroReporteProcesoCartera filtro) en d:\ALGORITMOS\JUDIS_NOVUS_21122015\APLICACION_21122015\Juris.WebApp\Controllers\ReportesController.cs:línea 263
   en lambda_method(Closure , ControllerBase , Object[] )
   en System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   en System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   en System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.ActionInvocation.InvokeSynchronousActionMethod()
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   en System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()

thanks a lot.

**Comment by igitur** [comment]
I mean `wb.SaveAs(@"c:\test.xlsx", false);`

**Comment by hflores01** [comment]
return:

{"Workbooks need at least one worksheet."}

   en ClosedXML.Excel.XLWorkbook.checkForWorksheetsPresent() en C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:línea 517
   en ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate) en C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:línea 472
   en Juris.WebApp.Controllers.ReportesController.ExportarExcel(Dictionary`2 columnas, FiltroReporteProcesoCartera filtro) en d:\ALGORITMOS\JUDIS_NOVUS_21122015\APLICACION_21122015\Juris.WebApp\Controllers\ReportesController.cs:línea 263
   en lambda_method(Closure , ControllerBase , Object[] )
   en System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   en System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   en System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.ActionInvocation.InvokeSynchronousActionMethod()
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   en System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()

**Comment by igitur** [comment]
You should be creating at least one worksheet.

**Comment by hflores01** [comment]
now i changed to:

                using (MemoryStream MyMemoryStream = new MemoryStream())
                {
                    wb.Worksheets.Add("Sample").Cell(1, 1).SetValue("Hello World");
                    wb.SaveAs(@"C:\help\test.xlsx", false);
                    MyMemoryStream.WriteTo(Response.OutputStream);
                    Response.Flush();
                    Response.End();
                }

            return RedirectToAction("Procesos", "Reportes");

And this work, create the file excel, but no show it downloading and not redirect.

thanks a lot.

**Comment by igitur** [comment]
The file will be saved at C:\help\test.xlsx on your web server.

**Comment by igitur** [comment]
I'll reopen the issue when you attach the corrupt file. Until then I can't really help.

**Comment by admalledd** [comment]
I am having nearly the same problem

~~~

System.ApplicationException: The attribute 'width' has invalid value '496.850625'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[3]
   at ClosedXML.Excel.XLWorkbook.Validate(SpreadsheetDocument package) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:line 90
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, Boolean validate) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:line 105
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:line 479
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:line 461
   at TestCodeSnippets.Program.Main(String[] args) in D:\SourceCode\OneOffs\TestCodeSnippets\TestCodeSnippets\Program.cs:line 26

~~~

~~~

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestCodeSnippets
{
    class Program
    {
        static void Main(string[] args)
        {
            var wb = new ClosedXML.Excel.XLWorkbook();
            var ws = wb.Worksheets.Add("Something");
            ws.Cell("A1").Value = "DataType";
            ws.Cell("B1").Value = "DataSource";
            ws.Cell("C1").Value = "DataMessage";
            ws.Cell("A2").Value = "Error";
            ws.Cell("B2").Value = "Unittests.Apps.FIBase.Log.SaveAsExcel()";
            ws.Cell("C2").Value = @"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.";

            ws.Columns().AdjustToContents(); //Expected that this would not generate invalid column widths
            try
            {
                wb.SaveAs("SomeTestFilename.xlsx", false); //To get the "working" file as per above
                wb.SaveAs("SomeTestFilename.xlsx"); //Exception is thrown here
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                throw;
            }
        }
    }
}


~~~

[SomeTestFilename.xlsx](https://github.com/ClosedXML/ClosedXML/files/720665/SomeTestFilename.xlsx)


I hope attaching said file works this time...

I am uncertain if this has always been a lurking problem in the code that found this originally for me though, it is only recently that we have had some fields put in a decent amount of text into a cell. (Original code was also via a DataTable, reproduction above using the `AdjustToContents()` is the same in the end though)

**Comment by farlop** [comment]
Today I've face the same issue. Downgrading to 0.85.0 is a good workaround.

**Comment by igitur** [comment]
@farlop , @admalledd Refer to discussion in #152 .

**Comment by admalledd** [comment]
@igitur: I don't believe that is 100% a match for this bug. Just a similarity in exception message. Note that it legitimately is over the max width (496 vs 255).

My systems are already on en-us, and setting specifically `Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;` or such does nothing to change the exception.

**Comment by igitur** [comment]
@admalledd OK, please open a new issue for it.
