### ISSUE TITLE
Insight into what my problem is.

### ISSUE THREAD

**Issue by dsanborn33** [ClosedXML/ClosedXML#1453]
Question
Looking for insight.
I am using an template that I fill out with data. Right now that is all I am doing, no styling or anything other than put in data. The only thing different about this template is the column A and B are merged cells and I am putting the data in column B (and other columns). When I open the workbook I am getting an error that I have not seen before. Excel: We have problem with some of the content of the workbook, If you trust it we can try to repair it. Click Yes and the workbook is displayed with the data and an error messages says: Repaired Records: Table Style from /xl/styles.xml part (Styles) and clicking on the error message you get:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error163640_05.xml</logFileName><summary>Errors were detected in file 'C:\iaArtifact\PoamBuilt\poam 2\uNTxxx20200603.xlsx'</summary><repairedRecords><repairedRecord>Repaired Records: Table Style from /xl/styles.xml part (Styles)</repairedRecord></repairedRecords></recoveryLog>
Looking at the file /xl/styles.xml I have no understanding that I am seeing and the before and after the repair looks the same (big file).
Any insight what is going on? Or how I can fix it? Like I said I have not had this problem before.
Thanks!
David Sanborn

## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**

Complete this.

**What is the expected behavior or new feature?**

Complete this.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by Pankraty** [comment]
Without a code sample and attached workbook it is quite hard to figure out what is wrong. I don't know, try not to fill cells in column B and see what happens.
