### ISSUE TITLE
Returning an IEnumerable from a method that reads and disposes the XLWorkbook does not return data

### ISSUE THREAD

**Issue by miguellira** [ClosedXML/ClosedXML#1455]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.999.2061

**What is the current behavior?**

When returning an ```IEnumerable``` from a method that reads and disposes the ```XLWorkbook``` the data is not returned.

The works arounds are:
1. Remove the `using` statement and return the `IEnumerable` as is
2. Call `.ToList()` prior to returning.
3. Continue using version `0.94.2`

**NOTE:** If this is by design, please disregard and/or update your documents for proper guidance. Thanks!

**What is the expected behavior or new feature?**

Either the data should be returned, or proper guidance given when using the `using` statement.

**Is this a regression from the previous version?**

Yes. This worked fine under `0.94.2`.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using ClosedXML.Excel;

namespace Muppets
{
    class Program
    {
        static void Main(string[] args)
        {
            var muppets = GetMuppets();

            foreach(var muppet in muppets)
            {
                Console.WriteLine(muppet);
            }

            Console.WriteLine("Done!");
        }

        private static IEnumerable<string> GetMuppets()
        {
            // NOTE: Removing the 'using' statement works
            using var workbook = new XLWorkbook("Muppets.xlsx");

            var muppets = workbook.Worksheets.Single().RangeUsed().AsTable().DataRange.Rows()
                .Select(row => row.Field(0).GetString());
            // NOTE: Adding .ToList() also works

            return muppets;
        }
    }
}

```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Muppets.xlsx](https://github.com/ClosedXML/ClosedXML/files/4731484/Muppets.xlsx)

**Comment by Pankraty** [comment]
This is a valid behavior of IEnumerable, known as deferred execution. Replace reading from XLWorkbook with reading from a text file and you'll get exactly the same result: materializing collection after the stream is closed will cause the exception. 
If this worked in 0.94 then only due to a bug in that version: workbook disposal didn't properly clean up resources.

**Comment by miguellira** [comment]
@Pankraty Thanks for the quick response. I am familiar with deferred execution and LINQ in general. However, to be clear materializing the collection after the stream is closed does **not** raise an exception. If you run the example I provided you will see that the `IEnumerable` is indeed returned and is of the expected size, however, the call to GetString() returns null or an empty string.

I don't see a reason to re-open this issue. Another user encountering the same problem can/would hopefully search closed issues, however, it may be wise to update the wiki page with a footnote and/or guidance. Thanks again for your work!
