### ISSUE TITLE
createSafeSheetName method

### ISSUE THREAD

**Issue by NikitaEgorov** [ClosedXML/ClosedXML#1456]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**What is the current behavior?**

"Worksheet names cannot contain any of the following characters: "

**What is the expected behavior or new feature?**
Please add `createSafeSheetName` like POI
https://github.com/apache/poi/blob/f509d1deae86866ed531f10f2eba7db17e098473/src/java/org/apache/poi/ss/util/WorkbookUtil.java#L67

**Comment by makeProjectGreatAgain** [comment]
implemented in PR #1467
