### ISSUE TITLE
The Ranges.RemoveAll method of NamedRange not work.

### ISSUE THREAD

**Issue by b0bi79** [ClosedXML/ClosedXML#1457]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.95.3

**What is the current behavior?**

Trying to remove all Regions of NamedRange or delete a specific region does not clear the list of regions.

**What is the expected behavior or new feature?**

The list of regions should be cleared.

## Reproducibility

**Code to reproduce problem:**
```c#
        [Test]
        public void RemoveAllNamesRangesTest()
        {
            using (var wb = new XLWorkbook())
            {
                var ws1 = wb.Worksheets.Add("Sheet 1");

                ws1.Range("A1:D1").AddToNamed("Named range 1", XLScope.Worksheet);

                var nr = ws1.NamedRanges.First();
                nr.Ranges.RemoveAll();
                Assert.AreEqual(0, nr.Ranges.Count);
            }
        }
```

**Comment by igitur** [comment]
Yes, there's a bit of a design flaw here. You should treat `nr.Ranges` as if it returns a read-only list of ranges. Try `nr.Clear()` if you truly want to clear the named range's ranges.

**Comment by b0bi79** [comment]
Need use SetRefersTo to change Ranges of NamedRange
