### ISSUE TITLE
Support OpenDocument Spreadsheet (.ods)

### ISSUE THREAD

**Issue by taicomjp** [ClosedXML/ClosedXML#1458]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x] Feature
- [ ] Question

**What is the expected behavior or new feature?**

Add supported import/export OpenDocument Spreadsheet (.ods)

**Comment by igitur** [comment]
ClosedXML is a wrapper around OpenXML. ODS is a very different format and it's not our goal to support this.
