### ISSUE TITLE
Difference in workbook.SaveAs(stream) and workbook.SaveAs(filename)

### ISSUE THREAD

**Issue by SymaxBrian** [ClosedXML/ClosedXML#1468]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [X ] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.3

**What is the current behavior?**

When saving a workbook to a file (workbook.SaveAs("filename.xlsx")) the ClosedXML works perfectly. You can retrieve the file and present it to an MVC controller as a MemoryStream to be downloaded. Also opening the file from disk does not have any issues. But I don't wan't to store all the exported files. 
That's where workbook.SaveAs(stream) comes in. However if I present the stream to the MVC controller it gets a corrupted file when the returntype is FileStreamResult or when the returntype is FileContentResult it will not dowload at all. 

**What is the expected behavior or new feature?**

My expectation would be that there is no difference between the generation of the workbook to a file or a stream.

**Is this a regression from the previous version?**

UKNOWN

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Below you see the example. It are methods for a MVC controller class. There are three get methods.
1. Working version which saves the file first and then retrieves it and converts it to a stream. (returntype FileStreamResult)
2. Not downloading version which saves the workbook to a stream (returntype FileStreamResult)
3. Downloading corrupted file version which saves the workbook to a stream and has a different returntype (returntype FileContentResult)

They all use the most simple workbook example "Hello world" which I got from the ClosedXML wiki.

Any help with this issue would be greatly appreciated.

**Code to reproduce problem:**
```c#
        [HttpGet]
        [Route("/export/working")]
        public FileStreamResult WorkingExport()
        {
            var stream = ExportExcelWorking();

            return File(stream, "application/x-xls", "FileName.xlsx");
        }

        [HttpGet]
        [Route("/export/notdownloading")]
        public FileStreamResult NotDownloadingExport()
        {
            var stream = ExportExcelNotWorking();

            return File(stream, "application/x-xls", "FileName.xlsx");
        }

        [HttpGet]
        [Route("/export/corruptedfile")]
        public FileContentResult CorruptedExport()
        {
            var stream = ExportExcelNotWorking();

            return File(stream.GetBuffer(), "application/x-xls", "FileName.xlsx");
        }

        private MemoryStream ExportExcelWorking()
        {
            var workbook = GetWorkbook();

            var filename = "C:/Temp/FileName.xlsx";
            workbook.SaveAs(filename);
            var byteArray = System.IO.File.ReadAllBytes(filename);
            var stream = new MemoryStream(byteArray);

            return stream;
        }

        private MemoryStream ExportExcelNotWorking()
        {
            var workbook = GetWorkbook();

            var stream = new MemoryStream();
            workbook.SaveAs(stream);

            return stream;
        }

        private XLWorkbook GetWorkbook()
        {
            var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("Sample Sheet");
            worksheet.Cell("A1").Value = "Hello World!";

            return workbook;
        }
```

- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Corrupted.xlsx](https://github.com/ClosedXML/ClosedXML/files/4856960/Corrupted.xlsx)
[Working.xlsx](https://github.com/ClosedXML/ClosedXML/files/4856961/Working.xlsx)

**Comment by igitur** [comment]
`.GetBuffer()` doesn't return all the bytes. And if you have to ensure that your stream position is 0. So this is all general .NET issues, not relevant to ClosedXML, but anyway, this should work:

```c#
        private FileStreamResult Deliver(XLWorkbook workbook, string fileName, string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
        {
            var memoryStream = new MemoryStream();

            workbook.SaveAs(memoryStream);
            memoryStream.Seek(0, SeekOrigin.Begin);

            return File(memoryStream, contentType, fileName);
        }

        [HttpGet]
        public FileStreamResult Export()
        {
            var workbook = GetWorkbook();
            return Deliver(workbook, "filename.xlsx");
        }
```

**Comment by SymaxBrian** [comment]
Hi @igitur ,

My apologies. I lacked knowledge about this. And probably why I assumed it was related to ClosedXML. Thank you for responding. The code you suggested works like a charm.

Regards

**Comment by igitur** [comment]
You can also use the extension methods provided in https://github.com/ClosedXML/ClosedXML.Extensions.Mvc . I've just upgraded it to work with ASP.NET Core v3.
