### ISSUE TITLE
When saving a document with cell, staring with apostrophe ( ' ), this symbol is trimmed

### ISSUE THREAD

**Issue by tsurrdurr** [ClosedXML/ClosedXML#147]
Found an issue that occurs with all cells that contain values that start with an apostrophe sign. If you execute code:
```
string path = @"C:\temp\samplefile.xlsx";
        private void WriteXls()
        {
            var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("Sample");
            worksheet.Cell("A1").Value = @"'sample'";
            workbook.SaveAs(path);
        }
```
the cell value in .xlsx file looks like:
![snap](https://cloud.githubusercontent.com/assets/17877463/21811474/dc91ef90-d760-11e6-91e5-8905d9e04854.PNG)
So it's not the issue when excel just hides this symbol in the table, but shows in formula field.
Same problem persists on reading from .xlsx file, the apostrophe is lost.
But it only works for the first apostrophe in the cell.
I could work around writing issue using something like:
```
 string cellValue = @"'sample'";
            if(cellValue.StartsWith("'"))
            {
                cellValue = "'" + cellValue;
            }
            worksheet.Cell("A1").Value = cellValue;
```
but reading these values is a little trickier.
Please tell me if this is intended or a bug. Thanks.

**Comment by igitur** [comment]
This is by design. See https://github.com/ClosedXML/ClosedXML/wiki/Cell-Values for forcing values to be treated as text.

**Comment by igitur** [comment]
We could possibly disable the feature for string values, as they don't need to be forced to strings again.

**Comment by igitur** [comment]
@Pyropace , @vbjay Your opinion on excluding the feature for strings? It would be a breaking change, though.

**Comment by igitur** [comment]
Use 
```c#
worksheet.Cell("A1").SetValue(@"'sample'");
```
if you want to include the leading quotation mark. The test to force the parameter to string isn't done in this case.

**Comment by tsurrdurr** [comment]
Thanks, that works. I looked into the wiki further and got reading issue also solved by using:
`string sample = worksheet.Cell("A1").GetString(); `
I should've looked more carefully into the documentation. Thanks!
