### ISSUE TITLE
workBook doesn't work with big file (like 25 mb)

### ISSUE THREAD

**Issue by camilo2020pipe** [ClosedXML/ClosedXML#1480]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [ x] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x ] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**

the XLWorkbook doesn't intance

**What is the expected behavior or new feature?**

i have to convert this data in a datatable

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
![Errormio](https://user-images.githubusercontent.com/68619125/88113026-997e6b80-cb76-11ea-8834-34229e352746.png)

 using (XLWorkbook workBook = new XLWorkbook(path))
                {
                    //Read the first Sheet from Excel file.
                    IXLWorksheet workSheet = workBook.Worksheet(worksheet);

                    //Create a new DataTable.

                    //Loop through the Worksheet rows.
                    bool firstRow = true;
                    foreach (IXLRow row in workSheet.Rows())
                    {


                        //Use the first row to add columns to DataTable.
                        if (firstRow)
                        {
                            foreach (IXLCell cell in row.Cells())
                            {
                                if (!string.IsNullOrEmpty(cell.Value.ToString()))
                                {
                                    if (clsUtils.IsContain(cell.Address.ToString()) == true)
                                    {
                                        dt.Columns.Add(cell.Value.ToString());
                                    }
                                }
                                else
                                {
                                    break;
                                }
                            }
                            firstRow = false;
                        }
                        else
                        {
                            int i = 0;
                            DataRow toInsert = dt.NewRow();
                            foreach (IXLCell cell in row.Cells(1, dt.Columns.Count))
                            {
                                try
                                {
                                    toInsert[i] = cell.Value.ToString();
                                }
                                catch
                                {

                                }
                                i++;
                            }
                            dt.Rows.Add(toInsert);
                        }

                    }
                    return dt;
                }- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
It's unclear what exactly is the problem, probably something with conversion of large workbook to DataTable. No explanation what is actually wrong (exception, slow...). 25MB workbook likely means hundreds of MBs/possibly GB of uncompressed XML.

> `What is the current behavior?` the XLWorkbook doesn't intance
> What is the expected behavior or new feature? i have to convert this data in a datatable
> The code is uncompilable piece of code without sample worksheet.

Not reproducible, closing.
