### ISSUE TITLE
[Question] How can I resize a table?

### ISSUE THREAD

**Issue by giuliohome** [ClosedXML/ClosedXML#1481]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [ ] Feature
- [ x] Question

**Did you test against the latest CI build?**
- [x ] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

Latest version on .NET Framework

**What is the current behavior?**

Well this is a question about something I don't know how to do in ClosedXML.
So, let's say I have a xlsx with one sheet and one table in it from A1 to AA1234 plus other columns till AK and I want to resize the table (exactly like the resize table ribbon under the design toolbar) from A1 to AK1234

**What is the expected behavior or new feature?**

As an answer to my question I would like to know if I can combine some commands from ClosedXML such to get the desired transformation described above.

**Is this a regression from the previous version?**

I don't know but I guess the answer to my question is not different from the previous to the latest version. So I would say no.

## Reproducibility

I'm sorry I don't have a code sample because this is a question asking for a code sample indeed and it is not a bug report.

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

Kind regards and thank  you very much for this awesome library that I use very often.

**Comment by igitur** [comment]
The `ClosedXML.Excel.XLTable.Resize(IXLRange)` method should be what you want. There's also a sample class in the Examples project.

**Comment by giuliohome** [comment]
Thank you very much for the prompt and very useful reply!

**Comment by giuliohome** [comment]
FYI
this code seems to work  fine for me:

```csharp
wb.Save();
var table = ws.Tables.First();
table.Resize(ws.FirstCellUsed(), ws.LastCellUsed());
wb.Save();
```
