### ISSUE TITLE
accessing rows using elementAt is extremely slow on large spreadsheets

### ISSUE THREAD

**Issue by NickPerezCarletonUniversity** [ClosedXML/ClosedXML#1482]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [X] Yes
- [ ] No

**Version of ClosedXML**
0.95.3

**What is the current behavior?**
On a spreadsheet with 80,000 + rows, I called this:
var cell = worksheet.Rows().ElementAt(i).Cell(1).Value?.ToString().Trim();
the access time is about 3 seconds.

**What is the expected behavior or new feature?**
For it to take much less time. Instead, I had to use a foreach loop.

**Is this a regression from the previous version?**
Yes, I saw it happening in 0.94.2 as well.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

        public void TestSpreadsheet()
        {
            using (var workBook = new XLWorkbook("C:/test spreadsheet.xlsx"))
            {
                var worksheet = workBook.Worksheets.ElementAt(0);
                var row = worksheet.Rows().ElementAt(1);
                var cell = row.Cell(0).Value?.ToString().Trim();
            }
        }

**Comment by vbjay** [comment]
https://github.com/ClosedXML/ClosedXML/wiki/Selecting-Rows

That's because you are using linq to iterate till you get to the xth row.
Don't do that.

**Comment by igitur** [comment]
@vbjay is correct. You're instantiating a collection of all rows on every iteration. Instead you should be using `worksheet.Row(i + 1)`. 

Keep in mind `.Row(i)` is based on offset 1 and `.ElementAt(i)` is based on offset 0.

**Comment by NickPerezCarletonUniversity** [comment]
Keep in mind... "the access time is about 3 seconds" just to access **one row**. Even with using Linq that is way, way too slow. I can iterate through all the rows using "foreach" in a fraction of a second. It shouldn't take more than a fraction of a second to access a single row using ElementAt, even if the spreadsheet had millions of rows. This is obviously an implementation issue with the underlying data structure that was used to hold the rows. If the method is that slow, it should be either removed or the underlying problem fixed. As a developer, I am not going to go through the ClosedXML documentation to search for something as simple as accessing a row. The issue was only realized once large spreadsheets were introduced into the system, and it caused huge delays in response time and diagnosing the issue. A library with hundreds of thousands of downloads shouldn't have a fatal flaw like this overlooked.

**Comment by vbjay** [comment]
That's because the objects have to be spun up. There are a ton of internal
objects for cells and rows  What is the problem with using row or rows?

**Comment by Pankraty** [comment]
I agree with @NickPerezCarletonUniversity, `.Rows()` could have been working faster. It seems, we have a quadratic complexity here:
Repro:
```
var number = 1000;
for (int i = 0; i < 10; i++)
{
    using var ms = new MemoryStream();
    var data = Enumerable.Range(0, number).Select(i => Guid.NewGuid());
    var wb = new XLWorkbook();
    wb.AddWorksheet().FirstCell().InsertData(data);
    wb.SaveAs(ms);

    using var workBook = new XLWorkbook(ms);
    var sw = new Stopwatch();
    sw.Start();
    var worksheet = workBook.Worksheets.ElementAt(0);
    var row = worksheet.Rows().ElementAt(1);
    var cell = row.Cell(1).Value?.ToString().Trim();
    Console.WriteLine($"{number}\t{sw.ElapsedMilliseconds}");
    number *= 2;
}
```
Output:
```
1000    3
2000    3
4000    10
8000    42
16000   174
32000   757
64000   2759
128000  10737
256000  45718
512000  188466
```

**Comment by vbjay** [comment]
Rows(...)

NOT
Rows().ElementAt(....)

Get it?

**Comment by NickPerezCarletonUniversity** [comment]
thanks @Pankraty for understanding the issue at hand.
