### ISSUE TITLE
Error: Row number must be between 1 and 1048576 (Parameter 'cellAddressInRange')

### ISSUE THREAD

**Issue by hectorg83** [ClosedXML/ClosedXML#1484]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**

Error: Row number must be between 1 and 1048576 (Parameter 'cellAddressInRange')

ClosedXML.Excel.XLRangeBase.Cell(ref XLAddress cellAddressInRange)
ClosedXML.Excel.XLRangeBase.Cell(int row, int column)
WebGestionCore.Web.Extensions.ActionResults.ExcelResult.CreateExcelFile(string name, IEnumerable<object> data) in ExcelResult.cs
+
                    var cell = worksheet.Cell(row, col++);

**What is the expected behavior or new feature?**

File excel with all data.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**

        private MemoryStream CreateExcelFile(string name, IEnumerable<object> data)
        {
            var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add(name);

            var row = 1;
            var col = 1;

            var type = data.First().GetType();
            var props = type.GetProperties();

            foreach (var prop in props)
            {
                var cell = worksheet.Cell(row, col++);
                cell.Value = prop.Name;
                cell.Style.Font.Bold = true;
                cell.Style.Font.FontColor = XLColor.Blue;
            }

            foreach (var elem in data)
            {
                row++;
                col = 1;
                foreach (var prop in props)
                {
                    var cell = worksheet.Cell(row, col++);
                    cell.Value = prop.GetValue(elem, null);
                }

            }

            worksheet.Columns().AdjustToContents();

            MemoryStream memoryStream = new MemoryStream();
            workbook.SaveAs(memoryStream);
            return memoryStream;
        }

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
The maximum number of rows in a sheet is 1 048 576. You'll have to split your data over multiple sheets.

**Comment by hectorg83** [comment]
I have splitted my data into several sheets and it works. 

Thank you very much.
