### ISSUE TITLE
Getting Invalid file without doing any action

### ISSUE THREAD

**Issue by Mehdib64** [ClosedXML/ClosedXML#1489]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [X ] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML** 0.95.3

e.g. 0.95.3

**What is the current behavior?**

I tried using ClosedXML to open and edit an excel file. However, even when I do nothing and only open and save the file, I get the warning message from Excel that the generated file is invalid(the warning stops whole the procedure I wanted to automate)
**What is the expected behavior or new feature?**

Complete this.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
        private void OpenCloseOnly()
        {
            var wb = new ClosedXML.Excel.XLWorkbook(this.CurrentPeriodFile);
            var ws = wb.Worksheet("Setup");


            

            wb.Save();

        }
```

- [ N] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Follow *all* the steps of the issue template please.
