### ISSUE TITLE
Please Help.  Trying to Save an Excel xlsm spreadsheet.

### ISSUE THREAD

**Issue by wej0901** [ClosedXML/ClosedXML#1497]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [ ] Feature
- [x ] Question

**Did you test against the latest CI build?**
- [x ] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.3

**What is the current behavior?**

When trying to writing and then save to an excel spreadsheet that contains vba macros closedxml is throwing an exception error
with the ClosedXML.Excel.CalcEngine.  I tried turning the CalculateMode to auto and manual and neither one prevents the exception.  

**What is the expected behavior or new feature?**

The expected behavior is that the spreadsheet is saved without throwing an exception.  

**Is this a regression from the previous version?**

I don't know.

## Reproducibility

The code snippet is pretty simple.  It's just xlworkbook.save()

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by vbjay** [comment]
Do you want us to read your code with ESP?  My mind to your computer....
Do a PC mind meld.  We have an issue template with a section that talks
about sample code. Full out the issue completely.

**Comment by vbjay** [comment]
You also mention an exception but fail to provide its details.

**Comment by kenleese** [comment]
@wej0901 was the "Excel spreadsheet that contains VBA macros"  initially created using ClosedXML or is your code reading an existing spreadsheet created elsewhere? If created elsewhere, in addition to the sample code (which ideally should be a complete sample, runnable as a console application), can you also provide an appropriate sample Excel workbook?

**Comment by igitur** [comment]
Closing for now. Will reopen when issue template is completed thoroughly.
