### ISSUE TITLE
sheet.Evaluate("COUNTIF......

### ISSUE THREAD

**Issue by DawnF** [ClosedXML/ClosedXML#150]
I cannot seem to get the Evaluate function to evaluate a formula of COUNTIF despite saying it is a supported formula.  My code gets the sheet and then calls this sheet.Evaluate("COUNTIF("G1:G500", /"x/")");

I've tried various things but I cannot seem to get it to work.  Can anyone help?

**Comment by igitur** [comment]
You're right. There's definitely a bug. I also didn't know that we don't have unit tests to cover this function (and some others). 

Will fix soon.

**Comment by DawnF** [comment]
I am currently developing an application and considering whether or not to move to EPPlus instead.  I really like ClosedXML, but I am concerned regarding hitting something like this and the time to resolve it (either by you or by downloading the open source code and attempting to do it myself!). Can you give me any kind of timeframe as to when this might be resolved to aide my decision please?

**Comment by igitur** [comment]
I generally dislike committing to a timeframe, but I should be able to fix this within the next week.

**Comment by DawnF** [comment]
Thank you, I really appreciate that, and the fast response.

**Comment by igitur** [comment]
The PR has been merged into the `develop` branch. I'd appreciate it if you could pull the `develop` branch and check that it solves your issue. Thanks.
