### ISSUE TITLE
Is absolute path stored in the document?

### ISSUE THREAD

**Issue by pekspro** [ClosedXML/ClosedXML#1502]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

Tried both 0.95.999.2099 and 0.95.3

**What is the current behavior?**

If you open a created file in Excel, select File > Info it will warn you that the absolute path is stored in the document.

![image](https://user-images.githubusercontent.com/3163293/90972058-3f2a4f00-e516-11ea-80aa-58e96d632ffc.png)

**What is the expected behavior or new feature?**

I would prefer that the path is not stored in the document. In Excel it is possible to remove this value so it is probably not necessary.

**Is this a regression from the previous version?**

I tried some previous versions, version 0.94.0 for instance, with the same result.

## Reproducibility

**Code to reproduce problem:**
```c#
        static void Main(string[] args)
        {
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Sheet1");
             
                workbook.SaveAs("HelloWorld.xlsx");
            }
        }

```

**Comment by brogowski** [comment]
Hi, I can pick it up.

Do you want it enabled by default or only by passing **SaveOptions** explicitly?

**Comment by Pankraty** [comment]
Better disable by default, else it will be a breaking change. Besides, it would require updating all reference files in tests.
