### ISSUE TITLE
DateTime Datatype for a cell not properly recognized 

### ISSUE THREAD

**Issue by snehal-deshpande** [ClosedXML/ClosedXML#1503]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.95.999.2073
e.g. 0.95.3

**What is the current behavior?**
I have configured DateTime datatype for few cells of an Excel sheet through UI. I have added few entries of datetime. 
If I read the cell's datatype pragmatically then I get datatype as Text not DateTime.  
Complete this.

**What is the expected behavior or new feature?**
If I configure and add DateTime entries then through API I should get cell datatype as DateTime.
Complete this.

**Is this a regression from the previous version?**
No
Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
   string fileName = @"<File Name>";
   var xlworkBook = new XLWorkbook(fileName);
   if (xlworkBook != null)
   {
       var sheet1 = xlworkBook.Worksheet("Sheet1");
       if (sheet1 != null)
       {
       var rows = sheet1.RangeUsed().RowsUsed().Skip(1);
       foreach (var row in rows)
       {
       var rowCell = row.Cell(1);
       var cellDataType = rowCell.DataType;

       Debug.WriteLine("Cell Position: " + rowCell.Address.ToString() +
                                ", Cell Datatype: " + rowCell.DataType.ToString()
                                );  
       }
   }
   }
}
```

- [x
[CellDataTimeProblem.xlsx](https://github.com/ClosedXML/ClosedXML/files/5116013/CellDataTimeProblem.xlsx)
] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
You entered your dates as text. They aren't real dates.

![image](https://user-images.githubusercontent.com/145854/91540152-aaab5c80-e91a-11ea-87e3-e7f124dcc95b.png)

**Comment by snehal-deshpande** [comment]
Hi Igitur,
Please find attached image captured in Excel which say the cell C4 has Date format with value 24/8/2020.
From ClosedXML API I expect the datatype as Datetime not Text as I see it in MS Excel. 
Please suggest what I am doing wrong here. 
![DateTimeProblem](https://user-images.githubusercontent.com/67730552/91684845-408ef380-eb76-11ea-929b-a33a7e5cd61d.jpg)
--

**Comment by igitur** [comment]
Your screenshot shows the number format, which in ClosedXML can be found under `cell.Style.NumberFormat`. This is not the same as the data type. It is similar to regular C# where you have variables of different types and you can apply a `String.Format()` to them.

If you want to format your dates in a particular way, you have to ensure that you store them as dates, not strings.
