### ISSUE TITLE
Percentage Value Data Type

### ISSUE THREAD

**Issue by UGRCAN** [ClosedXML/ClosedXML#1505]
**Do you want to request a *feature* or report a *bug*?**
- [x ] Question

**Did you test against the latest CI build?**
- [x] Yes

**Version of ClosedXML**

e.g. 0.80.0

**What is the current behavior?**

When I try to set the double typed number with a percent expression it changes the value.

## Reproducibility

**Code to reproduce problem:**
```c#
lossTreeWorkSheet.Cell("F26").Style.NumberFormat.Format ="0.00%";
                lossTreeWorkSheet.Cell("F26" ).Value = 0.24 ;
```
Expected 0,24%
Output is 24.00%

Sample Cell
![Captures](https://user-images.githubusercontent.com/20906601/91276043-a439ab00-e789-11ea-8dfa-c508f201b410.PNG)

- [ x] I attached a sample spreadsheet.

**Comment by igitur** [comment]
0.24 is indeed = 24%, so this is the expected behaviour. If you want 0.24%, then you should set `.Value` to 0.0024.
