### ISSUE TITLE
Text in cell converted to number when using XLDataType.Text

### ISSUE THREAD

**Issue by janid1967** [ClosedXML/ClosedXML#1509]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**

When inserting the string 002 into a cell, the value show as 2 in cell. 
The cell is formatted with XLDataType.Text

**What is the expected behavior or new feature?**

I expect value show as 002 in cell

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
        private void InsertTextInCell(IXLRow row)
        {
            row.Cell(1).Value = "002";
            row.Cell(1).DataType = XLDataType.Text;
        }
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[CellAsTextBug.xlsx](https://github.com/ClosedXML/ClosedXML/files/5164581/CellAsTextBug.xlsx)

**Comment by vbjay** [comment]
Set the format

**Comment by janid1967** [comment]
> Set the format

Can you provide sample code?

**Comment by igitur** [comment]
When you do `row.Cell(1).Value = "002"` ClosedXML tries to guess the best data type, in this case it realises that it's a numeric value. The internal value is then set to `2` (not a string). Then when you do `row.Cell(1).DataType = XLDataType.Text;` you set it back to a string, in which case the `2` becomes `"2"`. 

You have 2 options:

`row.Cell(1).SetValue("002");` which sets the value to `"002"` without further deductions. The value is then a string.
or
```c#
row.Cell(1).Value = "002";
row.Cell(1).Style.NumberFormat.Format = "000";
```
in which case the underlying fromat is guessed to be numeric, but the display format is changed to 3 digits.

See our wiki:
https://github.com/ClosedXML/ClosedXML/wiki/Text-with-numbers-are-getting-converted-to-numbers
https://github.com/ClosedXML/ClosedXML/wiki/Styles-NumberFormat
