### ISSUE TITLE
Error in ImportStream

### ISSUE THREAD

**Issue by DawnF** [ClosedXML/ClosedXML#151]
Just updated to the latest version 0.86 and this code (which previously worked) is now failing.

_workbook = new XLWorkbook(interfaceFileImportControl.ImportStream);

The ImportStream has error message

'(interfaceFileImportControl.ImportStream).ReadTimeout' threw an exception of type 'System.InvalidOperationException'

Please can you help!

**Comment by igitur** [comment]
`ReadTimeout` isn't used anywhere in ClosedXML, so double check that there aren't any locks on your stream.

**Comment by DawnF** [comment]
Perhaps the stream isn't the issue.  Basically when I upgrade from 0.85 to 0.86 that line 

_workbook = new XLWorkbook(interfaceFileImportControl.ImportStream);

throws an object not set to an instance of an object error.  The same exact line works fine with the previous version.  Thanks in advance for your help.

**Comment by DawnF** [comment]
Hi there, if it helps, I've debugged and found the issue to be with this line.....
source = ws.Workbook.Range(pivotTableCacheDefinitionPart.PivotCacheDefinition.CacheSource.WorksheetSource.Name.Value);

in the class XLWorkbook_Load and procedure LoadSpreadsheetDocument.

If I can resolve I will.  Is there a way I can contribute if I resolve things?  Fairly soon I will be making a decision on whether or not to continue down this path and if I do, it would be great if I know how I can feed back any issues but also the resolutions?

Thanks

**Comment by igitur** [comment]
Remove any sensitive information and attach the problematic workbook, please.

**Comment by DawnF** [comment]
Its not the workbook.  Its this bit of code
if (pivotTableCacheDefinitionPart.PivotCacheDefinition != null
                            && pivotTableCacheDefinitionPart.PivotCacheDefinition.CacheSource != null
                            && pivotTableCacheDefinitionPart.PivotCacheDefinition.CacheSource.WorksheetSource != null
                            && pivotTableCacheDefinitionPart.PivotCacheDefinition.CacheSource.WorksheetSource.Name != null)
                        {
                            // TODO: Implement other sources besides worksheetSource (e.g. Table source?)
                            source = ws.Workbook.Range(pivotTableCacheDefinitionPart.PivotCacheDefinition.CacheSource.WorksheetSource.Name.Value);
                        }

Name is null so it fails.

For now I've added in an extra check so it now looks like

if (pivotTableCacheDefinitionPart.PivotCacheDefinition != null
                            && pivotTableCacheDefinitionPart.PivotCacheDefinition.CacheSource != null
                            && pivotTableCacheDefinitionPart.PivotCacheDefinition.CacheSource.WorksheetSource != null
                            && pivotTableCacheDefinitionPart.PivotCacheDefinition.CacheSource.WorksheetSource.Name != null)
                        {
                            // TODO: Implement other sources besides worksheetSource (e.g. Table source?)
                            source = ws.Workbook.Range(pivotTableCacheDefinitionPart.PivotCacheDefinition.CacheSource.WorksheetSource.Name.Value);
                        }

however, since I'm not sure what that is doing and whether or not there is a bigger issue with pivotTableCacheDefinitionPart.PivotCacheDefinition.CacheSource.WorksheetSource.Name being null or not, you may wish to take a look.

It doesn't seem to have affected my workbook - I have a pivot table in my template and its still there once I've read it in and saved it back out to the server.

I hope this is helpful.

**Comment by igitur** [comment]
I'd appreciate it if you can attach the workbook so that I can do a thorough investigations. Also, pivot tables are still very much experimental, so I expect lots of bugs to appear.

**Comment by DawnF** [comment]
OK will see what I can do - its highly sensitive information, so I will need to be careful here.  I think using pivot tables is causing my issue with COUNTIF.  The count if is counting a column, which is based on a formuala, using values from a PIVOT TABLE.  I note when I step through that It is going right back to the pivot table and has this formula 
GETPIVOTDATA("Sum of Error",$A$18,"Business Day",DATE(2016,11,1),"Pooled Fund","Global Equity Pooled Fund")

I think I'm going to have to look at alternative methods of doing this as I cannot get rid of the pivot table as the data is dynamic based on user entry and I then need to import that data!

**Comment by igitur** [comment]
See if #179  fixes your issue. If not, please reopen and provide sample file.
