### ISSUE TITLE
ClosedXML.dll not signed on NuGet!

### ISSUE THREAD

**Issue by BenTheBest69** [ClosedXML/ClosedXML#1513]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.3

**What is the current behavior?**

Complete this.

**What is the expected behavior or new feature?**

When using Nuget for a project, the ClosedXML.dll file is not signed which prevent me to load it from our system.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

No code needed, just look at what's deployed on Nuget.

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
https://www.nuget.org/packages/ClosedXML.Signed/
