### ISSUE TITLE
Single cells should not be marked as "merged"

### ISSUE THREAD

**Issue by crypto-rsa** [ClosedXML/ClosedXML#1517]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No (but checked recent changes in the related code)

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

When `Merge()` is called on a single-cell range, ClosedXML adds the "range" (a cell, really) to the list of merged areas in the worksheet, which then prevents method `AdjustToContents` to account for the cell's width.

**What is the expected behavior or new feature?**

Single-cell ranges should not be marked as merged.

**Is this a regression from the previous version?**

I don't think so.

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
            var wb = new XLWorkbook();
            var sheet = wb.AddWorksheet();

            sheet.Cells("A1").Value = "Very long cell content";
            sheet.Cell("A2").Value = "Short content";
            // when the following line is commented out, AdjustToContents() properly accounts for the width of A1
            sheet.Range(1, 1, 1, 1).Merge();
            sheet.Columns().AdjustToContents();
}
```

**Comment by igitur** [comment]
Should we throw an exception when someone tries to merge a single cell range, or should we just silently ignore it? @pankraty ?

**Comment by crypto-rsa** [comment]
From a perspective of a library user, I'd vote for ignoring the call. Otherwise you force the users to handle the case explicitly which adds unnecessary noise to their code. It's a similar case as with calling `System.IO.File.Delete` with nonexistent file name.

**Comment by Pankraty** [comment]
I think merging a single cell is a legitimate (however useless) operation and we should just ignore it.

**Comment by crypto-rsa** [comment]
Thank you! Any idea when the next version will come out?
