### ISSUE TITLE
Sorting/Filter options are disabled when row selection or column selection

### ISSUE THREAD

**Issue by suribalu** [ClosedXML/ClosedXML#1532]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**

Filter/Sorting options are disabled, when row or column selection in excel (.XLSX)

**What is the expected behavior or new feature?**

Filter/Sorting options should not disable, when row or column selection in excel (.XLSX)

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
private static byte[] ExportToExcel(DataTable dtExcel)
{
     byte[] returnBytes;
     using (XLWorkbook workbook = new XLWorkbook())
     {
         workbook.Worksheets.Add(dtExcel, "sheetName1");
         using (MemoryStream ms = new MemoryStream())
         {
             workbook.SaveAs(ms);
             returnBytes = ms.ToArray();
         }
     }
     return returnBytes;
 }
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Testing-Filter-Sorting-Disabled.xlsx](https://github.com/ClosedXML/ClosedXML/files/5277913/Testing-Filter-Sorting-Disabled.xlsx)

**Comment by suribalu** [comment]
Is there any update

**Comment by Pankraty** [comment]
@suribalu I don't see how the code sample relates to the issue you've described. It works fine for me.

**Comment by Pankraty** [comment]
Nor do I understand what's wrong with the attached file - it sorts and filters perfectly.
![image](https://user-images.githubusercontent.com/19576939/95079240-62583900-0727-11eb-9ec4-4ae1107d0849.png)

**Comment by suribalu** [comment]
1. Please select any one of row and check sort/filter options are enabled or not?

Example : select 5th row, not 1st row

**Comment by Pankraty** [comment]
![2020-10-05_16h41_12](https://user-images.githubusercontent.com/19576939/95080797-b2d09600-0729-11eb-8317-4d098e4667dc.gif)

**Comment by suribalu** [comment]
![image](https://user-images.githubusercontent.com/26923892/95081304-ede3c100-074b-11eb-9dc0-36d9fbf32556.png)

**Comment by suribalu** [comment]
please try it once, correct me if i am wrong.

**Comment by suribalu** [comment]
![image](https://user-images.githubusercontent.com/26923892/95081911-d6590800-074c-11eb-978c-78fe104cf035.png)

**Comment by suribalu** [comment]
![image](https://user-images.githubusercontent.com/26923892/95082011-00aac580-074d-11eb-8706-d6fa9fc272a8.png)

**Comment by Pankraty** [comment]
This has nothing to do with ClosedXML - it's an Excel standard behavior. To make sure, create a new workbook in Excel, add a table and select a row - the Sort & Filter button will be disabled. 
![image](https://user-images.githubusercontent.com/19576939/95082279-deed1680-072b-11eb-9421-f07ab95bf7c2.png)

**Comment by suribalu** [comment]
it is not a excel standard behavior. Closed XML doesn't support this. I tried with other library it works as expecting 
![image](https://user-images.githubusercontent.com/26923892/95082714-0a80f880-074e-11eb-9bd8-070f7d6c0620.png)

**Comment by suribalu** [comment]
1. It should not be disabled, when row selected. 
2. It should not be disabled, when column selected.
3. It should not be disabled, when select all the worksheet (CTRL+A)

**Comment by Pankraty** [comment]
Provide the code sample that illustrates the issue and I'll reopen it.

**Comment by suribalu** [comment]
When using this library (OfficeOpenXml), expected things are working fine.

private static byte[] ExportToExcel(DataTable dtExcel)
{
     byte[] returnBytes;
     using (XLWorkbook workbook = new XLWorkbook())
     {
         workbook.Worksheets.Add(dtExcel, "sheetName1");
         using (MemoryStream ms = new MemoryStream())
         {
             workbook.SaveAs(ms);
             returnBytes = ms.ToArray();
         }
     }
     return returnBytes;
 }

**Comment by suribalu** [comment]
When using this library (OfficeOpenXml), expected things are working fine.

Already i have provided the code in **Code to reproduce problem** section
