### ISSUE TITLE
Thousands of System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by yarecky1** [ClosedXML/ClosedXML#1545]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.95.3

**What is the current behavior?**

I have thousands of: 
```
System.MissingMethodException: Method not found: 'System.String ExcelNumberFormat.NumberFormat.Format(System.Object, System.Globalization.CultureInfo)'.
   at ClosedXML.Extensions.FormatExtensions.ToExcelFormat(Object o, String format)
   at ClosedXML.Excel.XLCell.GetFormattedString()
```
...so many that they don't fit in entire ImmediateWindow in Visual Studio.

These thousands of exceptions slow down dramatically entire process of building excel file.
I see also you swallow 2 exceptions here.
```
public string GetFormattedString()
{
    var format = GetFormat();
    try
    {
        return Value.ToExcelFormat(format);
    }
    catch { }

    try
    {
        return CachedValue.ToExcelFormat(format);
    }
    catch { }

    return _cellValue;
}
``` 

**What is the expected behavior or new feature?**

To fix the bug?

**Is this a regression from the previous version?**

Yes.

## Reproducibility

No code. Please just fix it.

**Comment by Pankraty** [comment]
Let's start by providing a reproducible example, shall we?

**Comment by yarecky1** [comment]
In worksheet I have several cells with template strings like `{id1}` or just `id2`.
```c#
internal void Test()
{
    var path = Path.GetFullPath(AppDomain.CurrentDomain.BaseDirectory + @"Resources\Test.xltx");

    using (var source = new XLWorkbook(path, XLEventTracking.Disabled))
    {
        source.Worksheet("TEST").Search("{id1}").Value = "TEST1";
        source.Worksheet("TEST").Search("id2").Value = "TEST2";
    }
}
```
One code line `source...` generates 6 `MissingMethodException`.

File: [Test.xlsx](https://github.com/ClosedXML/ClosedXML/files/5397285/Test.xlsx)
I use xltx instead of xlsx - to be able to attach it here, I changed the extension.

**Comment by igitur** [comment]
> No code. Please just fix it.

Wow.

**Comment by yarecky1** [comment]
>> No code. Please just fix it.

> Wow.

Swallowing exception...

**Comment by Netclick19** [comment]
Hi,
I've the same issue.

I got the exception using your sample too.

var workbook = new XLWorkbook();
var ws = workbook.Worksheets.Add("Style NumberFormat");

var co = 2;
var ro = 1;

// Using a custom format
ws.Cell(++ro, co).Value = "123456.789";
ws.Cell(ro, co).Style.NumberFormat.Format = "$ #,##0.00";

ws.Cell(++ro, co).Value = "12.345";
ws.Cell(ro, co).Style.NumberFormat.Format = "0000";

// Using a OpenXML's predefined formats
ws.Cell(++ro, co).Value = "12.345";
ws.Cell(ro, co).Style.NumberFormat.NumberFormatId = 3;

// Use XLPredefinedFormat enum
ws.Cell(++ro, co).Value = "123456789123";
ws.Cell(ro, co).Style.NumberFormat.SetNumberFormatId((int)XLPredefinedFormat.Number.Integer);

ws.Column(co).AdjustToContents();

workbook.SaveAs("StylesNumberFormat.xlsx");

How can I solve it?

Thank you for your support.

**Comment by Netclick19** [comment]
I'got the same problem.

I've just uninstalled the package and reinstall it... then it works well.

**Comment by igitur** [comment]
I can't reproduce the problem.
```c#
using (var wb = new XLWorkbook("test.xlsx", XLEventTracking.Disabled))
{
    wb.Worksheet("TEST").Search("{id1}").Value = "TEST1";
    wb.Worksheet("TEST").Search("id2").Value = "TEST2";

    wb.SaveAs("test2.xlsx");
}
```

Then I get this file:
[test2.xlsx](https://github.com/ClosedXML/ClosedXML/files/5797456/test2.xlsx)

**Comment by Pitterling** [comment]
That’s probably caused by ExcelNumberFormat version 1.1.0 
see #1590 and referenced excelnumberformat issue
