### ISSUE TITLE
Attach PDF files (or other file types)

### ISSUE THREAD

**Issue by hieplenet** [ClosedXML/ClosedXML#1555]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [ ] Feature
- [ x] Question

**Did you test against the latest CI build?**
- [ x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**

I know that ClosedXML already support add picture. I wonder how can I just add another file type like .pdf or similar?

**Comment by igitur** [comment]
No, this isn't possible.
