### ISSUE TITLE
Unable to set cell value to 01/01/1753 00:00:00

### ISSUE THREAD

**Issue by shaistasohail** [ClosedXML/ClosedXML#1563]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.3

**What is the current behavior?**

wb.Worksheets.Add(dt) throws an exception "Unable to set cell value to 01/01/1753 00:00:00" if the datatable dt has date values 01/01/1753 00:00:00

**What is the expected behavior or new feature?**

This is a valid date and Excel allows this date in cells. ClosedXML should not throw an error on this date.

**Is this a regression from the previous version?**

I don't know because I have not used any previous version.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
        public static string DataTableToExcel(System.Data.DataTable dt, string filePath)
        {
            XLWorkbook wb = new XLWorkbook();
                        wb.Worksheets.Add(dt);

            string fileName = Path.GetFileNameWithoutExtension(Path.GetTempFileName()) + ".xlsx";
            string fullPath = Path.Combine(filePath, fileName);
            wb.SaveAs(fullPath);

            return fileName;
        }
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Please attach a sample spreadsheet that contains this date as a real date
(not text).

**Comment by shaistasohail** [comment]
My apologies. Excel does not support any date lower than 1/1/1900. It just treats it as a string. I am closing this case. Thanks for your support.
