### ISSUE TITLE
Picture names cannot be more than 31 characters

### ISSUE THREAD

**Issue by JuliaTitova77** [ClosedXML/ClosedXML#1564]
## Read and complete the full issue template
I have WPF app Core.
When try to load excel file like workbook = XLWorkBook(filename) appears error = Picture names cannot be more than 31 characters, but filename.Length <=31. What's happend?
System.ArgumentException
  HResult=0x80070057
  Сообщение = Picture names cannot be more than 31 characters
  Источник = ClosedXML
  Трассировка стека:
   в ClosedXML.Excel.Drawings.XLPicture.SetName(String value)
   в ClosedXML.Excel.XLWorkbook.LoadDrawings(WorksheetPart wsPart, IXLWorksheet ws)
   в ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   в ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName)
   в ClosedXML.Excel.XLWorkbook..ctor(String file)
  
   var wb = new XLWorkbook(inFilePath);<--- here get exception
Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**

Complete this.

**What is the expected behavior or new feature?**

Complete this.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 
With v0.94.2 the same error. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    string XLSXfile = "";
    if (_filename.Length >= 31)
            {                              
                string sourceDir = @"c:\test";

                if (!Directory.Exists(sourceDir))
                {
                    Directory.CreateDirectory(sourceDir); 
                }
                if (!File.Exists(XLSXfile))
                {
                    //File.Delete(XLSXfile);
                    XLSXfile = "copy" + Path.GetExtension(_filename);
                    XLSXfile = Path.Combine(sourceDir, XLSXfile);
                    File.Copy(_filename, XLSXfile);
                    FileInfo info = new FileInfo(XLSXfile);
                    int len = info.FullName.Length;                    
                    
                }
              
            }
         

            //</ init >

            lblStatus.Content = "load " + Path.GetFileName(_filename) + "..";
           
            try
            {

                //----< open_Excel >----
            

                FileInfo fileInf = new FileInfo(XLSXfile);
                int len = fileInf.FullName.Length;
                using (_workbook = new XLWorkbook(XLSXfile)) // <--and the problem here: the file is failed to load and get the error 
                //even    though the file name length is less than 31"Picture names cannot be more than 31 characters"
                {
                    var name = _worksheet.NamedRanges;
                    _worksheet = _workbook.Worksheet(1);
                }

                //----</ open_Excel >----
           
                
            }

            catch (Exception ex)

            {
                MessageBox.Show(ex.Message);               

            }
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Incomplete issue template

**Comment by JuliaTitova77** [comment]
System.ArgumentException
  HResult=0x80070057
  Сообщение = Picture names cannot be more than 31 characters
  Источник = ClosedXML
  Трассировка стека:
   в ClosedXML.Excel.Drawings.XLPicture.SetName(String value)
   в ClosedXML.Excel.XLWorkbook.LoadDrawings(WorksheetPart wsPart, IXLWorksheet ws)
   в ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   в ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName)
   в ClosedXML.Excel.XLWorkbook..ctor(String file)
   в B2Bconsole.Program.Main(String[] args) в C:\Users\julia\source\repos\B2B\B2Bconsole\Program1.cs:строка 86
   var wb = new XLWorkbook(inFilePath);

**Comment by igitur** [comment]
![image](https://user-images.githubusercontent.com/145854/99180644-a1b77380-2730-11eb-8295-8b5da3f1ff0b.png)

I don't see your attached spreadsheet.
