### ISSUE TITLE
The Property Properties.Modified is not read when loading a Workbook

### ISSUE THREAD

**Issue by rominator1983** [ClosedXML/ClosedXML#1568]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [X] No=> No need. I checked the code

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.
=> No need. I checked the code

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**

When I load a XLWorkbook the property "Modified" is DateTime.MinValue instead of the documents value.

**What is the expected behavior or new feature?**

The property "Modified" should have the value of the document.
This can be solved in XLWorkbook_Load in SetProperties by adding the following code:
```
            if (p.Modified != null)
                Properties.Modified = p.Modified.Value;
```
**Is this a regression from the previous version?**

I don't think so.

**Code to reproduce problem:**
```c#
[Test]
public void ModifiedRepro ()
{
  // NOTE: arrange
  var now = DateTime.Now;
  using (var workBookForSave = new XLWorkbook ())
  {
    workBookForSave.AddWorksheet ();
    workBookForSave.Properties.Modified = now;
    workBookForSave.SaveAs ("C:\\temp\\bla.xlsx");
  }

  // NOTE: act
  using (var workBookForLoad = new XLWorkbook ("C:\\temp\\bla.xlsx"))
  {
    var modified = workBookForLoad.Properties.Modified;

    // NOTE: assert
    /* this fails with:
      Message: 
        Expected: 2020-11-19 15:35:22.2226398
        But was:  0001-01-01 00:00:00
    */
    Assert.That (modified, Is.EqualTo (now));
  }
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by rominator1983** [comment]
one thing I forgot. Saving seems to work without any problem. The code there looks fine to me.

**Comment by igitur** [comment]
Thanks. Would you mind submitting a PR. Looks like you did most of the work already.

**Comment by rominator1983** [comment]
Fine. It seems that that part is not tested. But I will double check that before doing the PR.
If you would in the meantime be so kind to include the PR https://github.com/ClosedXML/ClosedXML/pull/1475 ?  ;-)

This would be a huge help as now I am building ClosedXml on a repository for myself which is quite cumbersome.

**Comment by rominator1983** [comment]
Here is the PR: https://github.com/ClosedXML/ClosedXML/pull/1569

**Comment by rominator1983** [comment]
there you go
