### ISSUE TITLE
Used by another process when loading workbook

### ISSUE THREAD

**Issue by shaggygi** [ClosedXML/ClosedXML#1572]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.1

**What is the current behavior?**

Complete this.
Get a file process in use exception when trying to load a workbook.  Is there a way to read only and not get the exception when the files is opened in Excel the same to reading.

**What is the expected behavior or new feature?**

Complete this.
Trying to read the contents of file.  Not writing.

**Is this a regression from the previous version?**

Not sure

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    string filePath = @"C:\MyFile.xslx"
    using (var workbook = new XLWorkbook(filePath))
    {
    }
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
In that regard ClosedXML can do only what OpenXML allows it to do. So please raise the issue with the OpenXML team and if you have a working solution there then we can investigate how ClosedXML can implement that.

**Comment by Pankraty** [comment]
No, this can actually be worked around easily:
```
using var stream = File.Open(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
var wb = new XLWorkbook(stream);
Console.WriteLine(wb.Worksheet(1).FirstCell().Value);
```

**Comment by shaggygi** [comment]
@Pankraty That's exactly what I needed.  Thank you so much 👍
