### ISSUE TITLE
ClosedXML + OpenXML 2.12 generate non valid excel (OpenXML 2.11.3 is ok) - adding <x:v>

### ISSUE THREAD

**Issue by Pitterling** [ClosedXML/ClosedXML#1583]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [x] Question
 
I filed a bug at OpenXML:
[Issue after upgrade from 2.11.3 to v2.12.0 - generated excel is not valid](https://github.com/OfficeDev/Open-XML-SDK/issues/829)
Not sure if this can be caused by ClosedXML or if this is introduced by OpenXML 2.12 

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**
0.95.4

**What is the current behavior?**
Using OpenXML 2.11.3 is ok. Issue only occurs after OpenXML upgrade to v2.12.0.

the broken version has additional properties 
`<x:v>xxx</x:v>` following formulars

similiar like:
```
<x:f>Param.DateRange</x:f><x:v>23-Jun-2011 06:00 - 06:00 (0:00 h)</x:v></x:c>
<x:f>SUBTOTAL($D3,IOSTAT[busy '[%']])</x:f><x:v>0</x:v></x:c>
```

**What is the expected behavior or new feature?**
valid xml. Just want to know if this is a pure OpenXML issue, or if this could be related to a combination of ClosedXML functionality which is now handled newly by OpenXML ?

**Is this a regression from the previous version?**

## Reproducibility

**Code to reproduce problem:**
```c#
using ClosedXML.Excel;

namespace ClosedXML_OpenXML
{
    class Program
    {
        static void Main(string[] args)
        {
            using var templateWorkbook = new XLWorkbook(@"template.xlsx");

            templateWorkbook.SaveAs(@"SavedWorkbook.xlsx");

        }
    }
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[template.xlsx](https://github.com/ClosedXML/ClosedXML/files/5721141/template.xlsx)

**Comment by vbjay** [comment]
You failed to provide for the Reproducibility section.

**Comment by Pitterling** [comment]
striped down as much as possible .. also used latest ClosedXML version .. issue still exist

**Comment by Pitterling** [comment]
Any change to get the generated SDK code as requested from the OpenXML ticket "Please provide the SDK code that is used to generate this." ?

**Comment by igitur** [comment]
Refer to https://github.com/OfficeDev/Open-XML-SDK/pull/774#issuecomment-757482273

**Comment by Pitterling** [comment]
Thy igitur. Just for my knowledge .. would it be possible at all to extract the generated SDK code somehow from ClosedXML?

**Comment by igitur** [comment]
You can use the OpenXML SDK Tools ( https://www.microsoft.com/en-us/download/details.aspx?id=30425 ) to generate the SDK code, but that would still not have highlighted the issue in this case.

**Comment by twsouthwick** [comment]
This should now be fixed in v2.12.1 available on NuGet. Thanks for the report! I'm very surprised we had no tests to cover the property being set to null scenario. We now have a regression test for that :)

**Comment by igitur** [comment]
> I'm very surprised we had no tests to cover the property being set to null scenario. We now have a regression test for that :)

It happens.

**Comment by Pitterling** [comment]
Thx igitur

regarding the SDK tools .. this will only generate the code how to get to my excel file. I was more asking if there is way to get from ClosedXML the "underthehood" generated SDK coding, as ClosedXML is only a wrapper around OpenXML ...

**Comment by igitur** [comment]
What you're asking for is basically the ClosedXML source code itself.
