### ISSUE TITLE
Read CSV using stream

### ISSUE THREAD

**Issue by somasundar1997** [ClosedXML/ClosedXML#1587]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version: 0.95.4**

**What is the current behavior?**

System.IO.FileFormatException: File contains corrupted data.\r\n   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.FindPosition(Stream archiveStream)\r\n   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)\r\n   at MS.Internal.IO.Zip.ZipArchive..ctor(Stream archiveStream, FileMode mode, FileAccess access, Boolean streaming, Boolean ownStream)\r\n   at MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access, Boolean streaming)\r\n   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)\r\n   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)\r\n   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.OpenCore(Stream stream, Boolean readWriteMode)\r\n   at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(Stream stream, Boolean isEditable, OpenSettings openSettings)\r\n   at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)\r\n   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream, XLEventTracking eventTracking)\r\n   at Procedure_Package.Controllers.ImportController.<Excel>d__0.MoveNext() in 

**What is the expected behavior or new feature?**

read a csv file using fileinput stream from web api

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
   var Files = HttpContext.Current.Request.Files[0];
   using (XLWorkbook MyWorkBook = new XLWorkbook(Files.InputStream;))
   {
       IXLWorksheet sheet = MyWorkBook.Worksheet(1);
       return "Success";
   }
}
```

**Comment by igitur** [comment]
> System.IO.FileFormatException: File contains corrupted data

The stream data is corrupt. 

Are you sure that you are at position 0 of your stream? If not, move to position 0, or try copying over the stream to a new instance of `MemoryStream` and pass that into the `XLWorkbook` constructor.

**Comment by somasundar1997** [comment]
it works file when I try to upload a **.xlsx** file 
it returns **System.IO.FileFormatException: File contains corrupted data** only when I try to upload a **.csv** file
I also tried copying over the stream to a new instance of **MemoryStream**  it does not work for **.csv** file returns the same error

**Comment by igitur** [comment]
ClosedXML does not support .csv files.

**Comment by somasundar1997** [comment]
is there any possibility bringing it in future

**Comment by igitur** [comment]
ClosedXML is a wrapper around OpenXML, so we can support only what the OpenXML project supports. It's unlikely that they'll support .csv files. I recommend using https://joshclose.github.io/CsvHelper/ for reading .csv files.

**Comment by somasundar1997** [comment]
ok, Thankyou

> ClosedXML is a wrapper around OpenXML, so we can support only what the OpenXML project supports. It's unlikely that they'll support .csv files. I recommend using https://joshclose.github.io/CsvHelper/ for reading .csv files.

ok, Thankyou
