### ISSUE TITLE
On read failure ClosedXML may keep a lock on the file

### ISSUE THREAD

**Issue by HalHaynes** [ClosedXML/ClosedXML#1589]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

In my demo application, running within Visual Studio 2019, I am reading data from multiple Excel workbooks (no writing is involved). After I read each file into an XLWorkbook and extract the data I require, I move the file to a "done" directory on my Windows 10 machine using System.IO.File.Move().

For resiliency, I construct the XLWorkbook objects in a try block in anticipation of failed reads--from a corrupted file, perhaps. After logging the error, I still move the file to the "done" directory.

I simulated corrupted files by renaming a text file, a Word document, and a PDF, giving them an .xlsx extension.

When I run my code, the XLWorkbook constructor throws an exception for each of the fake workbooks, as expected, and the `workbook` variable remains null, as expected. The exceptions:

* Word document: DocumentFormat.OpenXml.Packaging.OpenXmlPackageException, message "The specified package is not valid."
* Text file: System.IO.InvalidDataException, message "End of Central Directory record could not be found."
* PDF: System.IO.InvalidDataException, message "End of Central Directory record could not be found."

After this:
* The move of the real Excel files to the "done" directory is successful.
* The move of the Word file to the "done" directory is *also* successful.
* However, for the text file and the PDF, the File.Move invocation fails with System.IO.IOException, "The process cannot access the file because it is being used by another process."

Once this has happened, I cannot even move the file manually in Windows Explorer. This condition persists until I close Visual Studio.

**What is the expected behavior or new feature?**
I expect ClosedXML to unlock a bad file before it throws an exception, and I expect to be able to move the file afterwards.

**Is this a regression from the previous version?**
No, this is new development work, with 0.95.4 installed.

## Reproducibility
**Code to reproduce problem:**
```c#
using System;
using System.Diagnostics;
using System.IO;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Drawing;
using Path = System.IO.Path;

namespace ClosedXmlFileLoclDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("ClosedXML Test");

            Test("GoodWorkbook.xlsx");
            Test("WordDocWithFakeExtension.xlsx");
            Test("PdfWithFakeExtension.xlsx");
            Test("TextFileWithFakeExtension.xlsx");
            Test("AnotherGoodWorkbook.xlsx");
        }

        private static void Test(string fileName)
        {
            string sourceRoot = @"c:\test";
            string destinationRoot = @"c:\test\done";
            
            string sourcePath = Path.Combine(sourceRoot, fileName);
            string destinationPath = Path.Combine(destinationRoot, fileName);

            Console.WriteLine($"\r\n>>> Processing {sourcePath} <<<");
            Console.WriteLine($"A file {(File.Exists(sourcePath) ? "exists" : "doesn't exist")} at {sourcePath}.");
            Console.WriteLine("Let's try to read it into an IXLWorkbook.");

            IXLWorkbook workbook = null;
            try
            {
                workbook = new XLWorkbook(sourcePath);
                Console.WriteLine("The workbook read didn't throw an exception.");
                Console.WriteLine($"The value of the variable 'workbook' is {(workbook == null ? "null" : "not null")}.");
            }
            catch(Exception e)
            {
                Console.WriteLine($"The workbook read threw an exception of type {e.GetType()}.");
                Console.WriteLine($"The exception message was: '{e.Message}'.");
                Console.WriteLine($"As for the variable 'workbook', its value is {(workbook == null ? "still null" : "not null")}.");
            }

            Console.WriteLine("Let's move the file to the Done folder.");
            try
            {
                File.Move(sourcePath, destinationPath);
                Console.WriteLine($"The file move didn't throw an exception.");
                Console.WriteLine($"After the move, a file {(File.Exists(sourcePath) ? "exists" : "doesn't exist")} at {sourcePath}.");
                Console.WriteLine($"After the move, a file {(File.Exists(destinationPath) ? "exists" : "doesn't exist")} at {destinationPath}.");
            }
            catch (Exception e)
            {
                Console.WriteLine($"The file move threw an exception of type {e.GetType()}.");
                Console.WriteLine($"The exception message was: '{e.Message}'.");
                Console.WriteLine($"After the move, a file {(File.Exists(sourcePath) ? "exists" : "doesn't exist")} at {sourcePath}.");
                Console.WriteLine($"After the move, a file {(File.Exists(destinationPath) ? "exists" : "doesn't exist")} at {destinationPath}.");
            }
        }
    }
}
```

**Console output:**
```
ClosedXML Test

>>> Processing c:\test\GoodWorkbook.xlsx <<<
A file exists at c:\test\GoodWorkbook.xlsx.
Let's try to read it into an IXLWorkbook.
The workbook read didn't throw an exception.
The value of the variable 'workbook' is not null.
Let's move the file to the Done folder.
The file move didn't throw an exception.
After the move, a file doesn't exist at c:\test\GoodWorkbook.xlsx.
After the move, a file exists at c:\test\done\GoodWorkbook.xlsx.

>>> Processing c:\test\WordDocWithFakeExtension.xlsx <<<
A file exists at c:\test\WordDocWithFakeExtension.xlsx.
Let's try to read it into an IXLWorkbook.
The workbook read threw an exception of type DocumentFormat.OpenXml.Packaging.OpenXmlPackageException.
The exception message was: 'The specified package is not valid.'.
As for the variable 'workbook', its value is still null.
Let's move the file to the Done folder.
The file move didn't throw an exception.
After the move, a file doesn't exist at c:\test\WordDocWithFakeExtension.xlsx.
After the move, a file exists at c:\test\done\WordDocWithFakeExtension.xlsx.

>>> Processing c:\test\PdfWithFakeExtension.xlsx <<<
A file exists at c:\test\PdfWithFakeExtension.xlsx.
Let's try to read it into an IXLWorkbook.
The workbook read threw an exception of type System.IO.InvalidDataException.
The exception message was: 'End of Central Directory record could not be found.'.
As for the variable 'workbook', its value is still null.
Let's move the file to the Done folder.
The file move threw an exception of type System.IO.IOException.
The exception message was: 'The process cannot access the file because it is being used by another process.'.
After the move, a file exists at c:\test\PdfWithFakeExtension.xlsx.
After the move, a file doesn't exist at c:\test\done\PdfWithFakeExtension.xlsx.

>>> Processing c:\test\TextFileWithFakeExtension.xlsx <<<
A file exists at c:\test\TextFileWithFakeExtension.xlsx.
Let's try to read it into an IXLWorkbook.
The workbook read threw an exception of type System.IO.InvalidDataException.
The exception message was: 'End of Central Directory record could not be found.'.
As for the variable 'workbook', its value is still null.
Let's move the file to the Done folder.
The file move threw an exception of type System.IO.IOException.
The exception message was: 'The process cannot access the file because it is being used by another process.'.
After the move, a file exists at c:\test\TextFileWithFakeExtension.xlsx.
After the move, a file doesn't exist at c:\test\done\TextFileWithFakeExtension.xlsx.

>>> Processing c:\test\AnotherGoodWorkbook.xlsx <<<
A file exists at c:\test\AnotherGoodWorkbook.xlsx.
Let's try to read it into an IXLWorkbook.
The workbook read didn't throw an exception.
The value of the variable 'workbook' is not null.
Let's move the file to the Done folder.
The file move didn't throw an exception.
After the move, a file doesn't exist at c:\test\AnotherGoodWorkbook.xlsx.
After the move, a file exists at c:\test\done\AnotherGoodWorkbook.xlsx.
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[GoodWorkbook.xlsx](https://github.com/ClosedXML/ClosedXML/files/5782745/GoodWorkbook.xlsx)
[PdfWithFakeExtension.xlsx](https://github.com/ClosedXML/ClosedXML/files/5782747/PdfWithFakeExtension.xlsx)
[TextFileWithFakeExtension.xlsx](https://github.com/ClosedXML/ClosedXML/files/5782748/TextFileWithFakeExtension.xlsx)
[WordDocWithFakeExtension.xlsx](https://github.com/ClosedXML/ClosedXML/files/5782749/WordDocWithFakeExtension.xlsx)
[AnotherGoodWorkbook.xlsx](https://github.com/ClosedXML/ClosedXML/files/5782750/AnotherGoodWorkbook.xlsx)

**Comment by igitur** [comment]
`XLWorkbook` implements `IDisposable`. Therefore you should be using a `using` block or manually calling `workbook.Dispose()` to release all resources. Please try that and let me know if it solves the problem. It's possible that if the exception occurs in the `XLWorkbook` constructor that the resources aren't cleaned up properly.

**Comment by HalHaynes** [comment]
> `XLWorkbook` implements `IDisposable`. Therefore you should be using a `using` block or manually calling `workbook.Dispose()` to release all resources. Please try that and let me know if it solves the problem. It's possible that if the exception occurs in the `XLWorkbook` constructor that the resources aren't cleaned up properly.

As I noted, the value of the variable `workbook` is never set in these cases, so there's nothing to call Dispose() on.

I don't see where I would use `using`. I'm declaring `workbook` and setting it to null before the first try block because I need to be able to access it after the first try block after setting it to an XLWorkbook within the first try block I need to access it beneath the try block. If I were to use `using` inside the try block, I'd have

```
            IXLWorkbook workbook = null;
            try
            {
                using (workbook = new XLWorkbook(sourcePath))
                {
                    Console.WriteLine("The workbook read didn't throw an exception.");
                    Console.WriteLine(
                        $"The value of the variable 'workbook' is {(workbook == null ? "null" : "not null")}.");
                }
            }
```
and the object would have been disposed of by the time I got to the code that was meant to work with it (which I omitted here, but it comes between the first try-catch and the attempt to move the file).

Of course, I can't have `using (IXLWorkbook workbook = null)` before the try block because then I can't assign to it within the try block.

This works fine when I happen to use a different kind of Office file (the Word document, which it recognizes as involving OpenXML and treats accordingly). In addition, if my failure to use `using` or `Dispose()` were the problem, I'd expect the same failure with the real Excel files and the renamed Word document.

Unlike Office Interop, ClosedXML doesn't maintain an open file during the entirety of the code's interaction with it. It opens it, reads it, and closes it, and presents the application with local data to be read and manipulated. (Saving it is an independent connect/write/disconnect operation.) At least, for an Excel or Word file, I can tell ClosedXML isn't maintaining a lock precisely because I *am* able to move the file. But it's failing to unlock in the other cases. There's no reason for it to maintain its lock on the file in *any* case, regardless of whether it was able to interpret what it read from the file.

**Comment by igitur** [comment]
I can replicate it. The file is locked deep inside the `System.IO.Packaging` package and there's nothing I can do to solve it. I logged a bug report at https://github.com/dotnet/runtime/issues/46791.

**Comment by igitur** [comment]
As a workaround, you can try instantiating your own instance of `FileStream` and pass that stream to the `XLWorkbook` constructor. In the `finally` block of the `try/catch/finally`, dispose of the stream manually.

**Comment by HalHaynes** [comment]
> I can replicate it. The file is locked deep inside the `System.IO.Packaging` package and there's nothing I can do to solve it. I logged a bug report at [dotnet/runtime#46791](https://github.com/dotnet/runtime/issues/46791).

Thanks for doing that. I'll keep track of what's going on there.

**Comment by HalHaynes** [comment]
> I can replicate it. The file is locked deep inside the `System.IO.Packaging` package and there's nothing I can do to solve it. I logged a bug report at [dotnet/runtime#46791](https://github.com/dotnet/runtime/issues/46791).

Thanks for doing that. I'll keep track of what's going on there.

**Comment by HalHaynes** [comment]
> As a workaround, you can try instantiating your own instance of `FileStream` and pass that stream to the `XLWorkbook` constructor. In the `finally` block of the `try/catch/finally`, dispose of the stream manually.

I wondered whether that would work, thanks. I'll give it a try. Although--even though that would allow me always to unlock the file, would that possibly then lead ClosedXML to being unable to release the FileStream, creating a leak?

**Comment by HalHaynes** [comment]
I tried the work-around, using the XLWorkbook constructor that takes a Stream argument rather than a path, and it worked. This suggests to me, though, that ClosedXML could apply the same work-around internally.

**Comment by igitur** [comment]
ClosedXML depends on OpenXML which depends on System.IO.Packaging. If any workarounds should be included, it should be as close to System.IO.Packaging as possible, which is OpenXML.
