### ISSUE TITLE
ExcelNumberFormat 1.1.0 - Method not found 'System.String ExcelNumberFormat.NumberFormat.Format(System.Object, System.Globalization.CultureInfo)'

### ISSUE THREAD

**Issue by Pitterling** [ClosedXML/ClosedXML#1590]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.92.1 (stuck to this version because of Pivot functionality)

**What is the current behavior?**

Updating ExcelNumberFormat from 1.0.10 to 1.1.0 is throwing this exception

Method not found: 'System.String ExcelNumberFormat.NumberFormat.Format(System.Object, System.Globalization.CultureInfo)'

at ClosedXML.Extensions.FormatExtensions.ToExcelFormat(Object o, String format)
at ClosedXML.Excel.XLCell.GetFormattedString()
at ClosedXML.Excel.XLColumn.AdjustToContents(Int32 startRow, Int32 endRow, Double minWidth, Double maxWidth)
at ClosedXML.Excel.XLColumn.AdjustToContents(Int32 startRow, Int32 endRow)
at ClosedXML.Excel.XLColumns.<>c__DisplayClass18_0.<AdjustToContents>b__0(XLColumn c)
at System.Collections.Generic.List`1.ForEach(Action`1 action)
at ClosedXML.Excel.XLColumns.AdjustToContents(Int32 startRow, Int32 endRow)

**What is the expected behavior or new feature?**
No Exception like in version 1.0.10

**Is this a regression from the previous version?**
No, probably a regression for ExcelNumberFormat ?

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
// working on this 
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Please log this with the ExcelNumberFormat project.

**Comment by Pitterling** [comment]
will do, but i'm not using ExcelNumberFormat .. this is all coming from ClosedXML ... seems like you're trying to get this method dynamically ?

**Comment by Pitterling** [comment]
https://github.com/andersnm/ExcelNumberFormat/issues/31 
additional parameter isDate1904 introduced changing public function ..
