### ISSUE TITLE
Slow performance for AdjustToContents() on large row numers

### ISSUE THREAD

**Issue by Netclick19** [ClosedXML/ClosedXML#1594]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.95.4

**What is the current behavior?**
If I execute the code worksheet.Columns().AdjustToContents() with 10'000 rows it takes more than 20 minutes (I stopped it).

**What is the expected behavior or new feature?**
It should takes about an half seconds (as Excel does).

**Is this a regression from the previous version?**
I don't know.

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
            var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("Dati");

            DataGenerationWithBigData();

            worksheet.Columns().AdjustToContents();

            worksheet.PageSetup.PageOrientation = XLPageOrientation.Portrait;
            worksheet.PageSetup.PaperSize = XLPaperSize.A4Paper;

            workbook.CalculateMode = XLCalculateMode.Auto;

            workbook.SaveAs(workbookFile);
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by Pankraty** [comment]
> It should takes about an half seconds (as Excel does).

I wish it also had the same budget and the team size as Excel has :-D

I was about to profile the sample you provided but it does not build.

>  Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be minimal complete and verifiable.

No luck this time

**Comment by Netclick19** [comment]
Hi,
you can use everything you want method to create a large amount of data for the DataGenerationWithBigData method.

`public static void DataGenerationWithBigData(){
  for(var i = 0; i < 15000; i++){
     for(var l = 0; l < 25; l++){
         worksheet.Cell(ColumnIndexToColumnLetter(column) + i).Value = "X";
     }
  }
}

public static string ColumnIndexToColumnLetter(int colIndex)
{
      int div = colIndex;
      string colLetter = String.Empty;
      int mod = 0;

            while (div > 0)
            {
                mod = (div - 1) % 26;
                colLetter = (char)(65 + mod) + colLetter;
                div = ((div - mod) / 26);
            }
            return colLetter;
}`

**Comment by Pitterling** [comment]
@Netclick19 .. you know you could limit that by yourself ..

```c#
//startRow=1, endRow=100
.Columns().AdjustToContents(1,100);
```

**Comment by Netclick19** [comment]
Thank you for your hint, but this doesn't solve my problem to have all columns fit to content.

**Comment by xxbigbacon** [comment]
I am running into this as well, was this ever resolved? trying to adjust columns 1 to 35 of 1200 rows takes over 7 minutes! pulling my hair out wondering my data can get pulled from SQL and dumped in the worksheet in like 30 seconds yet the file wasn't ready for another 7.

**Comment by Pitterling** [comment]
Did you try to limit the number of rows?

//startRow=1, endRow=100
.Columns().AdjustToContents(1,100);

Also, which ExcelNumberFormat version are you using?
The latest version leads to performance issues due to exceptions.

**Comment by rtek1000** [comment]
Is there any way to know how many columns were written? Or does the code have to programmatically count the interaction of each column?

I used this routine to trigger a progress bar and it was satisfactory (about 70 columns, 5000 rows, the progress bar value is unity in my code, from 0.00 to 1.00):

```C++
				updateProgressBar(0)
				
				Dim i As Integer = 0
				
				For i = 1 To col_max 
					sheet1.Columns().AdjustToContents(i, i)
					
					updateProgressBar(i / col_max)
					
					Sleep(0)
				Next

```

**Comment by kuklei** [comment]
Why is this issue closed? I still get a very high generation time in the case where there are 5k Rows with 23 cols (the last col as sum of all the previous cols) and the last row as the total of each column. Looks like this procedure needs to calculate the formulas to evaluate the width and it takes more than 1 min to only a call to AdjustToContents. Using 0.96.0 version from NuGet and this is the offending line ws.Columns(7, 23).AdjustToContents(sumRowNr, sumRowNr); //adjust only based on the last row content

**Comment by jahav** [comment]
@kuklei The [code](https://gist.github.com/jahav/a9c7b694b695875f455aa3698f9439d6) I cobbled up from comments of the ticket ran in a ~7 second on my computer. 

Not great, but enough to solve 20 minute issue.
> If I execute the code worksheet.Columns().AdjustToContents() with 10'000 rows it takes more than 20 minutes (I stopped it).

**Comment by Flithor** [comment]
The hell code has tried to render each text of cells in range!
NO DEDUPLICATION!
https://github.com/ClosedXML/ClosedXML/blob/bbeb9617a0bc51c3823773e691e601857ca9486b/ClosedXML/Excel/Columns/XLColumn.cs#L172-L351

**Comment by SirMeowington** [comment]
I just want to add that the AdjustToContents() method still takes a seemingly exorbitant amount of time. 10,000 rows with 32 columns (most of them populated with varying lengths of text) takes the AdjustToContents() method approximately 1 minute 17 seconds, or 130 rows per second. 250,000 rows took 31 minutes 15 seconds (133 rows per second).

This was measured by a System.Diagnostics.Stopwatch object that was started immediately before and stopped immediately after the AdjustToContents() method was called.

```
using (XLWorkbook wb = new())
{
     IXLWorksheet employeeSheet = wb.Worksheets.Add("Employee");
     IXLRange employeeDataRange = employeeSheet.Cell(1, 1).InsertTable(resultsFile.EmployeeRecords); //EmployeeRecords is an IEnumerable<T> collection which only takes a couple seconds for the InsertTable() method to handle.
     Stopwatch sw = new();
     sw.Start();
     employeeSheet.Columns().AdjustToContents();
     sw.Stop();
     wb.SaveAs("TestBook.xlsx");
}
```

In case it's helpful:
Visual Studio 2022
.NET 6.0
ClosedXML v0.100.3
ExcelNumberFormat v1.1.0
OS: Windows Server 2019
CPU: Dual 3.00 GHz Intel Xeon(R) Gold 6284R
RAM: 64 GB
HDD: Solid state

**Comment by khellang** [comment]
We have the following code to generate a data export worksheet:

```csharp
protected void GenerateWorksheet(IReadOnlyCollection<object> entities, IXLWorksheet worksheet) {
	var table = new DataTable();

	var properties = GetEntityProperties(entities);
	var fields = Configuration.Fields;

	foreach (var field in fields) {
		var propertyType = properties.TryGetValue(field.Id, out var property)
			? property.PropertyType
			: typeof(string);
		var name = field.Name.Translate();
		if (table.Columns.Contains(name)) {
			name += $" ({field.Id})";
		}
		table.Columns.Add(name, propertyType.GetUnderlyingType());
	}

	foreach (var entity in entities) {
		var row = table.NewRow();
		FillRow(row, entity, fields, properties);
		table.Rows.Add(row);
	}

	if (worksheet.Tables.TryGetTable("exportdata", out var existingTable)) {
		existingTable.ReplaceData(table, propagateExtraColumns: true);
	} else {
		worksheet.Clear();
		worksheet.FirstCell().InsertTable(table, "exportdata");
	}

	worksheet.Columns().AdjustToContents();
}
```

When running this method the `AdjustToContents` call takes 60-70% of the entire report generation:

![image](https://github.com/ClosedXML/ClosedXML/assets/582487/5d63b4bc-83a6-432e-bbe7-e6aabb854aaa)

This is a really simple export of exclusively ASCII data and no custom fonts or anything. Is there no way to cache such common glyph boxes? To speed it up a little?

**Comment by PriscilaMASE** [comment]
I know this issue is closed, but this line of code: 
worksheet.Columns(1, 25).AdjustToContents(); 
with 350 rows is taking 5 seconds to complete, doesn´t seem like much, but the whole function takes about 7 seconds:/
