### ISSUE TITLE
NoValueAvailableException thrown during SumProduct

### ISSUE THREAD

**Issue by Jonathan--V** [ClosedXML/ClosedXML#1597]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

Where could I find step-by-step instructions on how to do this?

**Version of ClosedXML**

0.95.4.0

**What is the current behavior?**

In certain files (example included), SumProduct will throw an exception on line 444-445 of MathTrig.cs: `if (p.Any(param => !(param is IEnumerable)))`. The exception will be caught within ClosedXML if the value is accessed via the IXLCell.GetFormattedString() method, but it will not be caught when accessed directly through the IXL Cell.Value property.

**What is the expected behavior or new feature?**

No exception is thrown and the value is obtained.

**Is this a regression from the previous version?**

No (tested against  v0.94.2).

## Reproducibility

**Code to reproduce problem:**
```c#
using System.Diagnostics;
using ClosedXML.Excel;

namespace ClosedXmlIssues
{
    public static class ReadCellsInSumProductFile
    {
        public static void Main()
        {
            string sumProductFilename = @"C:\ClosedXML and ExcelNumberFormat\Exception in reading SumProduct.xlsx";
            XLWorkbook workbook = new XLWorkbook(sumProductFilename);

            foreach (IXLCell cell in workbook.Worksheet(1).Cells())
            {
                Debug.WriteLine($"{cell.Address}: {cell.GetFormattedString()}");
                Debug.WriteLine($"{cell.Address}: {cell.Value}");
            }
        }
    }
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Exception in reading SumProduct.xlsx](https://github.com/ClosedXML/ClosedXML/files/5848735/Exception.in.reading.SumProduct.xlsx)

**Comment by jbrou015** [comment]
I am having the same issue.
My formula is: SUMPRODUCT((F149:F160+G149:G160),H149:H160)

Anything you can do?
@Jonathan--V did you find a solution or workaround?

**Comment by Jonathan--V** [comment]
Unfortunately, I've not found any solution or workaround, no. I just catch the exception and treat the cells as empty, which is not even close to a workaround.

**Comment by igitur** [comment]
>   [Exception in reading SumProduct.xlsx](https://github.com/ClosedXML/ClosedXML/files/5848735/Exception.in.reading.SumProduct.xlsx)

The formula in B2 is `=SUMPRODUCT(A1:A2/A2,A1:A2)`. ClosedXML doesn't support scalar operators on ranges as in your `A1:A2/A2`.

**Comment by igitur** [comment]
> My formula is: SUMPRODUCT((F149:F160+G149:G160),H149:H160). So basically I am adding 2 columns before multiplying the columns with another column.

Again, not supported. Don't try to be fancy with your formulas if you want them to work in ClosedXML. K.I.S.S.

**Comment by Jonathan--V** [comment]
@igitur I don't have control over the workbooks I need to read - I can only control the reading mechanism. 

Given that scalar operators on ranges is supported by Excel, is it not a bug that ClosedXml throws an exception when reading a valid Excel file? Is this something you expect to support in the future?

**Comment by igitur** [comment]
This is an open-source project and we rely on community contributions. If you feel this is important, please put in the effort and submit a pull request. I don't see myself having the capacity to spend time on this soon. Day job and toddler taking up too much time.
