### ISSUE TITLE
Formula does not contain @ but is showing up in Excel with @

### ISSUE THREAD

**Issue by MikeRensing** [ClosedXML/ClosedXML#1600]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.4

**What is the current behavior?**

I am writing a formula using ClosedXML, and have assigned it to a cell using both FormualA1 and FormulaR1C1 methods. Both have the same result. This is a simplified sample of the code. It is currently looping through the data in a table, so the references to cell change based on the row:
`
                string cellToFill = "L3"
                string categoryCell = "I3";
                string subCategoryCell = "J3";
                string codeCell = "K3";
                string formula = "=IF(NOT(" + categoryCell + "=\"\"),CONCAT(" + categoryCell + ",IF(" + categoryCell + "=\"E\",\".\",\"\")," + subCategoryCell + "," + codeCell + ",),\"\")"; ;//"=IF(NOT(" + categoryCell + "=\"\"),CONCAT(" + categoryCell + ",IF(" + categoryCell + "=\"E\",\".\",\"\")," + subCategoryCell + "," + codeCell + ",),\"\")";
                scheduleWorksheet.Cell(cellToFill).FormulaA1 = formula;
![ExcelFormula](https://user-images.githubusercontent.com/43816770/106396262-e02a0980-63d4-11eb-9b19-97cf5e750591.png)
[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/5900538/test.xlsx)
![VSFormula](https://user-images.githubusercontent.com/43816770/106396265-e0c2a000-63d4-11eb-9db5-ebcd6864776a.png)

`
Currently cell L3 is filled with =@IF(NOT(I3=""),CONCAT(I3,IF(I3="E",".",""),J3,K3,),"")
I would expect it to be filled with =IF(NOT(I3=""),CONCAT(I3,IF(I3="E",".",""),J3,K3,),"")

**What is the expected behavior or new feature?**

Cell L3 should contain the formula =IF(NOT(I3=""),CONCAT(I3,IF(I3="E",".",""),J3,K3,),"")

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
static void Main(string[] args)
        {
            DataTable dataTable = GetSampleDataTable();
            XLWorkbook excelFile = new XLWorkbook();
            IXLWorksheet scheduleWorksheet = excelFile.AddWorksheet("FF&E Schedule");
            IXLWorksheet pickListWorksheet = excelFile.AddWorksheet("Pick Lists");

            DataTable categoryTable = GetCategories();
            var excelCategoryTable = pickListWorksheet.Cell(1, 1).InsertTable(categoryTable.AsEnumerable());
            excelCategoryTable.Name = "Categories";

            DataTable subCategoryTable = GetSubCategories();
            var excelSubCategoryTable = pickListWorksheet.Cell(1, 2).InsertTable(subCategoryTable.AsEnumerable());
            excelSubCategoryTable.Name = "Sub Categories";

            DataTable codeTable = GetCodes();
            var excelCodeTable = pickListWorksheet.Cell(1, 3).InsertTable(codeTable.AsEnumerable());
            excelCodeTable.Name = "Codes";

            int columns = dataTable.Columns.Count;

            scheduleWorksheet.Cell(1, 1).Value = "FF&E Revit Data";
            scheduleWorksheet.Range(1, 1, 1, columns).Merge().AddToNamed("Titles");
            IXLTable tableDataFromRevit = scheduleWorksheet.Cell(2, 1).InsertTable(dataTable.AsEnumerable());
            tableDataFromRevit.Name = "FF&E Data";

            var titlesStyle = excelFile.Style;
            titlesStyle.Font.Bold = true;
            titlesStyle.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
            titlesStyle.Fill.BackgroundColor = XLColor.AirForceBlue;

            excelFile.NamedRanges.NamedRange("Titles").Ranges.Style = titlesStyle;

            //search for column name
            int catColumnNumber = LetterNumber(GetColumnName(tableDataFromRevit, "Category"));
            int subCatColumnNumber = LetterNumber(GetColumnName(tableDataFromRevit, "Sub Category"));
            int codeColumnNumber = LetterNumber(GetColumnName(tableDataFromRevit, "Code"));

            var temp = pickListWorksheet.Table("Codes").DataRange;

            //Set validation for columns
            scheduleWorksheet.Column(catColumnNumber).SetDataValidation().List(pickListWorksheet.Table("Categories").DataRange, true);
            scheduleWorksheet.Column(subCatColumnNumber).SetDataValidation().List(pickListWorksheet.Table("Sub Categories").DataRange, true);
            scheduleWorksheet.Column(codeColumnNumber).SetDataValidation().List(pickListWorksheet.Table("Codes").DataRange, true);

            //fill in fomulas
            var firstRow = tableDataFromRevit.DataRange.RangeAddress.FirstAddress.RowNumber;
            var lastRow = tableDataFromRevit.DataRange.RangeAddress.LastAddress.RowNumber;
            string catAbbreviationColumn = GetColumnName(tableDataFromRevit, "Category Abbreviation");
            string subCatAbbreviationColumn = GetColumnName(tableDataFromRevit, "SubCategory Abbreviation");
            string codeAbbreviationColumn = GetColumnName(tableDataFromRevit, "Code Abbreviation");

            string catColumn = GetColumnName(tableDataFromRevit, "Category");
            string subCatColumn = GetColumnName(tableDataFromRevit, "Sub Category");
            string codeColumn = GetColumnName(tableDataFromRevit, "Code");
            string baseIDColumn = GetColumnName(tableDataFromRevit, "BaseID");
            string keynoteColumn = GetColumnName(tableDataFromRevit, "Keynote");
            //Set Category Forumla
            for (int i = firstRow; i < lastRow + 1; i++)
            {
                string currentCell = catColumn + i.ToString();
                string formula = "=IF(" + currentCell + "=\"Furniture\", \"F\", IF(" + currentCell + "=\"Fixture\", \"X\", IF(" + currentCell + "=\"Equipment\", \"E\", \"\")))";
                string cellToFill = catAbbreviationColumn + i.ToString();
                scheduleWorksheet.Cell(cellToFill).FormulaA1 = formula;
            }
            //Seyt Subcategory Formula
            for (int i = firstRow; i < lastRow + 1; i++)
            {
                string currentCell = subCatColumn + i.ToString();
                string formula = "=IF(" + currentCell + "=\"Clinical\", \"C\", IF(" + currentCell + "=\"Information Technology\", \"T\", IF(" + currentCell + "=\"Kitchen\", \"K\", \"\")))";
                string cellToFill = subCatAbbreviationColumn + i.ToString();
                scheduleWorksheet.Cell(cellToFill).FormulaA1 = formula;
            }
            //Set Code formula
            for (int i = firstRow; i < lastRow + 1; i++)
            {
                string currentCell = codeColumn + i.ToString();
                string formula = "=IF(" + currentCell + "=\"Table\", \"T\", IF(" + currentCell + "= \"Seating\", \"S\", IF(" + currentCell + "= \"System\", \"Y\", IF(" + currentCell + "= \"Storage\", \"R\", IF(" + currentCell + "= \"Demountable Partitions\", \"P\", IF(" + currentCell + "= \"Miscelaneous\", \"M\", IF(" + currentCell + "= \"Wall\", \"W\", IF(" + currentCell + "= \"Ceiling\", \"C\", IF(" + currentCell + "= \"Floor\", \"L\", IF(" + currentCell + "= \"Integrated\", \"K\", IF(" + currentCell + "= \"Cart\", \"A\", \"\")))))))))))";
                string cellToFill = codeAbbreviationColumn + i.ToString();
                scheduleWorksheet.Cell(cellToFill).FormulaA1 = formula;
            }
            //Set BaseID forumla
            for (int i = firstRow; i < lastRow + 1; i++)
            {
                string cellToFill = baseIDColumn + i.ToString();
                string categoryCell = catAbbreviationColumn + i.ToString();
                string subCategoryCell = subCatAbbreviationColumn + i.ToString();
                string codeCell = codeAbbreviationColumn + i.ToString();
                string formula = "=IF(NOT(" + categoryCell + "=\"\"),CONCAT(" + categoryCell + ",IF(" + categoryCell + "=\"E\",\".\",\"\")," + subCategoryCell + "," + codeCell + ",),\"\")"; ;//"=IF(NOT(" + categoryCell + "=\"\"),CONCAT(" + categoryCell + ",IF(" + categoryCell + "=\"E\",\".\",\"\")," + subCategoryCell + "," + codeCell + ",),\"\")";
                scheduleWorksheet.Cell(cellToFill).FormulaA1 = formula;
            }
            //Set Keynote ID
            for (int i = firstRow; i < lastRow + 1; i++)
            {
                string cellToFill = keynoteColumn + i.ToString();
                string baseIDCell = baseIDColumn + i.ToString();
                string formula = "=IF(NOT(" + baseIDCell + " = \"\"), " + baseIDCell + " & \"-\" & TEXT(COUNTIF($" + baseIDColumn + "$3:" + baseIDCell + ", " + baseIDCell + ") -1, \"000\"), \"\")";
                scheduleWorksheet.Cell(cellToFill).FormulaA1 = formula;
            }

            //Adjust columns width
            scheduleWorksheet.Columns().AdjustToContents();

            //Save the file
            excelFile.SaveAs(@"C:\test.xlsx");
        }

        private static DataTable GetSampleDataTable()
        {
            DataTable dataTable = new DataTable();
            dataTable.Clear();
            dataTable.Columns.Add("Count", typeof(string));
            dataTable.Columns.Add("Keynote", typeof(string));
            dataTable.Columns.Add("Family", typeof(string));
            dataTable.Columns.Add("Type", typeof(string));
            dataTable.Columns.Add("FF&E Category", typeof(string));
            dataTable.Columns.Add("Sub Category", typeof(string));
            dataTable.Columns.Add("Code", typeof(string));


            List<string> dataRow1 = new List<string>();
            dataRow1.Add("1");
            dataRow1.Add("10-8000B-002");
            dataRow1.Add("104400-Fire Extinquisher-Bracket Mounted");
            dataRow1.Add("104400-Fire Extinquisher-Bracket Mounted");
            dataRow1.Add("");
            dataRow1.Add("");
            dataRow1.Add("");

            List<string> dataRow2 = new List<string>();
            dataRow2.Add("1");
            dataRow2.Add("");
            dataRow2.Add("Space Planning - Rectangle");
            dataRow2.Add("Space Planning - Rectangle");
            dataRow2.Add("");
            dataRow2.Add("");
            dataRow2.Add("");

            object[] o = dataRow1.ToArray();
            dataTable.Rows.Add(o);
            o = dataRow2.ToArray();
            dataTable.Rows.Add(o);

            dataTable.Columns.Add("Category Abbreviation", typeof(string));
            dataTable.Columns.Add("SubCategory Abbreviation", typeof(string));
            dataTable.Columns.Add("Code Abbreviation", typeof(string));
            dataTable.Columns.Add("BaseID", typeof(string));

            dataTable.Columns.Add("Description", typeof(string));
            dataTable.Columns["Description"].SetOrdinal(2);

            return dataTable;
        }
        private static int LetterNumber(string letter)
        {
            int number = char.ToUpper(letter[0]) - 64;
            return number;
        }
        private static string GetColumnName(IXLTable table, string columnHeader)
        {
            var cell = table.HeadersRow().CellsUsed(c => c.Value.ToString().Contains(columnHeader)).FirstOrDefault();
            if (cell != null)
            {
                return cell.WorksheetColumn().ColumnLetter();
            }
            return null;
        }
        private static DataTable GetCategories()
        {
            DataTable table = new DataTable();
            table.Columns.Add("FF&E Category", typeof(string));

            table.Rows.Add("Furniture");
            table.Rows.Add("Fixture");
            table.Rows.Add("Equipment");

            return table;
        }
        private static DataTable GetSubCategories()
        {
            DataTable table = new DataTable();
            table.Columns.Add("Equipment Subcategory", typeof(string));

            table.Rows.Add("Clinical");
            table.Rows.Add("Information Technology");
            table.Rows.Add("Kitchen");

            return table;
        }
        private static DataTable GetCodes()
        {
            DataTable table = new DataTable();
            table.Columns.Add("Codes", typeof(string));

            table.Rows.Add("Table");
            table.Rows.Add("Seating");
            table.Rows.Add("System");
            table.Rows.Add("Storage");
            table.Rows.Add("Cart");
            table.Rows.Add("Demountable Partitions");
            table.Rows.Add("Miscelaneous");
            table.Rows.Add("Wall");
            table.Rows.Add("Ceiling");
            table.Rows.Add("Floor");
            table.Rows.Add("Integrated");

            return table;
        }
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
This is an Excel 365 feature. https://superuser.com/a/1471047

**Comment by MikeRensing** [comment]
Thank you for the clarification. Do you know why the formula would return #NAME? until I click in the cell and click either yes or no from the notification Excel provides(showing in the screen shot above)? This is what I am trying to eliminate, and I thought it was dur to the @ symbol.  The last column (BaseID) is the only one that Excel added the @ to when creating the file. If I manually add the @ to all the formulas, it shows up, but just the BaseID column is the one that has issues.

**Comment by igitur** [comment]
Difficult to say. You'll have to produce a truly *minimal* code sample. As in super stripped down absolutely only the essential code that reproduces the problem.

**Comment by MikeRensing** [comment]
Hrere is a striped down version. There is a data table of 4 columns, 3 of which have data and the forth concatenates the other 3. It shows the same behavior of displaying #NAME?
`
static void Main(string[] args)
        {
            //Setup data for testing
            DataTable dataTable = GetSampleDataTable();
            XLWorkbook excelFile = new XLWorkbook();
            IXLWorksheet scheduleWorksheet = excelFile.AddWorksheet("FF&E Schedule");

            IXLTable tableDataFromRevit = scheduleWorksheet.Cell(1, 1).InsertTable(dataTable.AsEnumerable());
            tableDataFromRevit.Name = "FF&E Data";

            var firstRow = tableDataFromRevit.DataRange.RangeAddress.FirstAddress.RowNumber;
            var lastRow = tableDataFromRevit.DataRange.RangeAddress.LastAddress.RowNumber;

            //fill in fomulas

            string catAbbreviationColumn = GetColumnName(tableDataFromRevit, "Category Abbreviation");
            string subCatAbbreviationColumn = GetColumnName(tableDataFromRevit, "SubCategory Abbreviation");
            string codeAbbreviationColumn = GetColumnName(tableDataFromRevit, "Code Abbreviation");

            string baseIDColumn = GetColumnName(tableDataFromRevit, "BaseID");
            string keynoteColumn = GetColumnName(tableDataFromRevit, "Keynote");
            //Set BaseID forumla
            for (int i = firstRow; i < lastRow + 1; i++)
            {
                string cellToFill = baseIDColumn + i.ToString();
                string categoryCell = catAbbreviationColumn + i.ToString();
                string subCategoryCell = subCatAbbreviationColumn + i.ToString();
                string codeCell = codeAbbreviationColumn + i.ToString();
                string formula = "=IF(NOT(" + categoryCell + "=\"\"),CONCAT(" + categoryCell + ",IF(" + categoryCell + "=\"E\",\".\",\"\")," + subCategoryCell + "," + codeCell + ",),\"\")";
                scheduleWorksheet.Cell(cellToFill).FormulaA1 = formula;
            }

            //Save the file
            excelFile.SaveAs(@"C:\Users\mrensing\OneDrive - GBBN Architects Inc\Desktop\test.xlsx");
        }

        private static DataTable GetSampleDataTable()
        {
            DataTable dataTable = new DataTable();
            dataTable.Clear();

            dataTable.Columns.Add("Category Abbreviation", typeof(string));
            dataTable.Columns.Add("SubCategory Abbreviation", typeof(string));
            dataTable.Columns.Add("Code Abbreviation", typeof(string));
            dataTable.Columns.Add("BaseID", typeof(string));


            List<string> dataRow1 = new List<string>();
            dataRow1.Add("F");
            dataRow1.Add("");
            dataRow1.Add("T");
            dataRow1.Add("");

            List<string> dataRow2 = new List<string>();
            dataRow2.Add("E");
            dataRow2.Add("C");
            dataRow2.Add("W");
            dataRow2.Add("");

            object[] o = dataRow1.ToArray();
            dataTable.Rows.Add(o);
            o = dataRow2.ToArray();
            dataTable.Rows.Add(o);

            return dataTable;
        }
        private static string GetColumnName(IXLTable table, string columnHeader)
        {
            var cell = table.HeadersRow().CellsUsed(c => c.Value.ToString().Contains(columnHeader)).FirstOrDefault();
            if (cell != null)
            {
                return cell.WorksheetColumn().ColumnLetter();
            }
            return null;
        }
    }
[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/5904263/test.xlsx)

`

**Comment by igitur** [comment]
Formulas like `CONCAT` are called "Future Functions" by the Excel team. Future functions have to be prefixed by `_xlfn.`. So replace your `CONCAT` with `_xlfn.CONCAT`.

Read more about future functions at https://libxlsxwriter.github.io/working_with_formulas.html

**Comment by Komarulon** [comment]
Just wondering, is there anything for this for XLOOKUP? I realize XLOOKUP is a more recent feature so this might not exist. I'm getting the same described issue, but with XLOOKUP, which is not in the libxlsxwriter doc or on the MS site here https://docs.microsoft.com/en-us/openspecs/office_standards/ms-xlsx/5d1b6d44-6fc1-4ecd-8fef-0b27406cc2bf
