### ISSUE TITLE
Filter out duplicate cells from List.

### ISSUE THREAD

**Issue by badbyt3** [ClosedXML/ClosedXML#1608]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [x ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.95.4
e.g. 0.95.3

**What is the current behavior?**
I have column whose cells I have  stored in a list and I'd want to use the Distinct operator on them in order to sort the duplicates.
In my codes I use hashtables but that didn't help.
Complete this.

**What is the expected behavior or new feature?**

Complete this.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
    List<IXLCell> cells = worksheet.FirstColumn().Cells().ToList().Distinct().ToList();
    HashSet<IXLCell> hashList = new HashSet<IXLCell>(cells);
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by vbjay** [comment]
They are not distinct cells. You have to use the value in the cell.

**Comment by vbjay** [comment]
Also use the ...used items so you don't get all cells of the column. You
want the cells in the used range.

**Comment by badbyt3** [comment]
That  is correct, I have to use the value in the cell.
I have the list of cells as mentioned above, and how can I use the "Distinct" function onto a list of IXLCell?

**Comment by vbjay** [comment]
Use a lookup.

...Tolookup or group by

**Comment by badbyt3** [comment]
Like..

**Comment by igitur** [comment]
The ClosedXML Github issues are for ClosedXML-specific questions. StackOverflow is a better place to ask for general programming help. That said, try something like this:

`worksheet.FirstColumn().CellsUsed().Select(c => c.Value).Distinct().ToList();`

**Comment by badbyt3** [comment]
worksheet.FirstColumn().CellsUsed().Select(c => c.Value).Distinct().ToList() <== returns a List<Object>() and making it .ToList<string>() gives me the error message: 
error CS1929: 'IEnumerable<object>' does not contain a definition for 'ToList' and the best extension method overload 'Enumerable.ToList<string>(IEnumerable<string>)' requires a receiver of type 'IEnumerable<string>'

**Comment by igitur** [comment]
Please use Stackoverflow.com for general programming help.
