### ISSUE TITLE
Value cannot be null. Parameter name: source while reading an excel file using closed xml

### ISSUE THREAD

**Issue by subinmunnuttil** [ClosedXML/ClosedXML#1610]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
 [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.3.0

**What is the current behavior?**

I am getting a weird exception while reading an excel using closed xml. It was working fine for most of the excels but for some excels I am getting an exception:Value cannot be null. Parameter name: source.
I am getting this exception when tries to open the file in my first line itself

using (XLWorkbook workBook = new XLWorkbook(path)) { } .

**What is the expected behavior or new feature?**

When tries to read the excel content using new XLWorkbook(path) , it should read the content rather than throwing above error

**Is this a regression from the previous version?**

same issue there too

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
     try
            {
                using (XLWorkbook workBook = new XLWorkbook(path))
                { }
            }
            catch(Exception e)
            {
                throw new Exception( e.Message.ToString());
            }
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Please attach your workbook.

**Comment by subinmunnuttil** [comment]
I can not attach the excel which is causing the issue as such because it contains business sensitive data. If you open the workbook and as soon as you make any changes on any fields it become a valid one .Workbook is prepared by an another application ,it is not manually prepared one .So i really fear whether any parameter/headers/content types in the workbook is causing the issue .Can you suggest any solution if that is the case.

**Comment by igitur** [comment]
Then I'm unable to help you, sorry. Try download the ClosedXML source code and find the bug and submit a pull request with a fix.
