### ISSUE TITLE
Some pictures caused System.ArgumentException

### ISSUE THREAD

**Issue by masanori840816** [ClosedXML/ClosedXML#1621]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

NuGet 0.95.4

**What is the current behavior?**

1. I created a file by using template of Microsoft Excel.
2. When I tried to copy pictures by IXLPicture.CopyTo, I got an exception like below.

```
Unhandled exception. System.ArgumentException: The picture format in the stream and the parameter don't match
   at ClosedXML.Excel.Drawings.XLPicture..ctor(IXLWorksheet worksheet, Stream stream, XLPictureFormat format)
   at ClosedXML.Excel.Drawings.XLPictures.Add(Stream stream, XLPictureFormat format)
   at ClosedXML.Excel.Drawings.XLPictures.Add(Stream stream, XLPictureFormat format, String name)
   at ClosedXML.Excel.XLWorksheet.AddPicture(Stream stream, XLPictureFormat format, String name)
   at ClosedXML.Excel.Drawings.XLPicture.CopyTo(XLWorksheet targetSheet)
   at ClosedXML.Excel.Drawings.XLPicture.CopyTo(IXLWorksheet targetSheet)
   at CopySheetSample.Program.Main(String[] args) in C:\Users\example\OneDrive\Documents\workspace\5_0_101\CopySheetSample\Program.cs:line 25
```

* When I saved the problematic picture and added it manually, no exceptions were occurred.
* The problematic picture's format(IXLPicture.Format) was "Bmp"

**What is the expected behavior or new feature?**

No exceptions will be occurred or skip copying the problematic pictures

**Is this a regression from the previous version?**

No. I got the same exception when I use v0.95.3.

## Reproducibility
**Code to reproduce problem:**
```c#
using System;
using System.IO;
using ClosedXML.Excel;
using ClosedXML.Excel.Drawings;

namespace CopySheetSample
{
    class Program
    {
        static void Main(string[] args)
        {
            byte[] fileData;
            using(XLWorkbook bookFrom = new XLWorkbook(@"C:\Users\example\Desktop\sample.xlsx"))
            {
                using(MemoryStream streamTo = new MemoryStream())
                {
                    using(XLWorkbook bookTo = new XLWorkbook())
                    {
                        foreach(IXLWorksheet sheetFrom in bookFrom.Worksheets)
                        {
                            IXLWorksheet sheetTo = bookTo.Worksheets.Add(sheetFrom.Name);
                            foreach(IXLPicture picture in sheetFrom.Pictures)
                            {
                                Console.WriteLine(picture.Format);
                                picture.CopyTo(sheetTo);
                            }
                        }
                        bookTo.SaveAs(streamTo);
                    }
                    fileData = streamTo.ToArray();
                }
            }
            using(var stream = new FileStream(@"C:\Users\example\Desktop\Sample_" + DateTime.Now.ToString("yyyyMMddHHmmssfff") + ".xlsx", FileMode.Create))
            {
                stream.Write(fileData, 0, fileData.Length);
            }
        }
    }
}
```

- [ x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[sample.xlsx](https://github.com/ClosedXML/ClosedXML/files/6026790/sample.xlsx)

**Comment by igitur** [comment]
It seems internally Microsoft has 2 versions of the Bmp format: `Bmp` and `MemoryBmp`. See https://docs.microsoft.com/en-us/dotnet/api/system.drawing.imaging.imageformat?view=netframework-4.7.2#properties

I will submit a PR to treat these 2 formats as equal.

**Comment by igitur** [comment]
It's more complicated than my initial comment. Your picture in the file is actually an `.emf` file. When the .NET Framework loads it, the framework reports its image format as `MemoryBmp`, which is weird. I'll have to investigate more later.
