### ISSUE TITLE
Images Removed when saving .xlsm file

### ISSUE THREAD

**Issue by gshkvinod** [ClosedXML/ClosedXML#1625]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [X] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

i have created an application which opens the ".xlsm" which has different sheets and few images as objects with macros assigned to these objects and after the operations are done and saved. Now re-opening the file the few image objects are removed also the macros are removed.
[Test.zip](https://github.com/ClosedXML/ClosedXML/files/6048552/Test.zip)

 

**What is the expected behavior or new feature?**

The image objects should not be removed and also the macros should not be removed from the objects that were assigned to

## Reproducibility

**Code to reproduce problem:**

using ClosedExcel = ClosedXML.Excel;

public void Main()
{
var wb = new ClosedExcel.XLWorkbook(@"C: \Users\vinod\Desktop\test\Test_closedxml.xlsm", ClosedExcel.XLEventTracking.Disabled);
            wb.Save();
}

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by vbjay** [comment]
Open the xlsm in excel and then save as an xlsx. See what happens to the
macros.

**Comment by gshkvinod** [comment]
Hi There,

This behaviour is expected when we save xlsm to xlsx. But here I was tring
to open xlsm and save it in xlsm even then the macros are getting
disappeared

Thanks,
Vinod

**Comment by dustyjuicebox** [comment]
Hi, 
Chiming in to confirm this is an issue I am having too. I'm trying to use a prexisting file with images and related macros but when the template gets saved by ClosedXml the macros no longer work.

**Comment by vbjay** [comment]
Is it saving an xlsx or am xlsm?

**Comment by dustyjuicebox** [comment]
The template is an xlsm that gets opened then I save it under a different name as an xlsm as well. I double checked and file type also shows as xlsm in windows explorer.

**Comment by vbjay** [comment]
The file extension may be xlsm but is it saving as an xlsm?  Doubtful.

**Comment by dustyjuicebox** [comment]
I can open the saved file in excel and access macros through the developer tab. It is certainly an xlsm and pulling the VBA in the template. The macros all break however because the referenced images they use are missing.

**Comment by igitur** [comment]
The OP didn't complete the issue template correctly. I'm closing this issue.

@dustyjuicebox Please open a new issue and complete the issue template fully.

**Comment by igitur** [comment]
@gshkvinod Please open a new issue and follow the issue template *exactly*.

**Comment by heldersantovisma** [comment]
Also having the same problem, @gshkvinod did you opened a new ticket as requested ?
