### ISSUE TITLE
Get valid results from formulas which could not be evaluated where Excel shows a calculation error.

### ISSUE THREAD

**Issue by sascha-ng** [ClosedXML/ClosedXML#1642]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

When a formula could not be calculated (because I multiply a number with random text for example) I get different results in ClosedXML and Excel itself.
To show what I mean I created a simple Excel file which creates the sum of 3 values (A1-A3) where the first value will be multiplied by a factor. In case the factor is not a number Excel shows me that there is an issue within the calculation.
ClosedXML instead seems to make the calculation anyways but expects 0 for all calculations which has failed.
In this example I get the sum of the two static values.

![closedxml_caldiff](https://user-images.githubusercontent.com/79875016/112004947-929f6280-8b22-11eb-9712-87a17f76fe57.png)

**What is the expected behavior or new feature?**

When formula calculation fails I expect some kind of exception or at least a cell property where I can see that calulations could not be successfully done.

**Is this a regression from the previous version?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

**Code to reproduce problem:**
```c#
public void Main()
{
    worksheet.Cell("F1").SetValue("xxx");

    worksheet.Cell("B4").InvalidateFormula();
    workbook.RecalculateAllFormulas();

    var value = worksheet.Cell("B4").Value;
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/6182868/test.xlsx)

**Comment by igitur** [comment]
Please try the CI build at https://ci.appveyor.com/project/ClosedXML/closedxml/builds/37851782/artifacts and tell me if that solves the problem.

**Comment by sascha-ng** [comment]
Now after

`.RecalculateAllFormulas();`

I got the following exception:

`Unable to convert value to the desired type.
Unable to coerce Expression value to type `Double`
bei ClosedXML.Excel.CalcEngine.Exceptions.CellValueException.CatchTypeConversionExceptions[T](Func`1 func)
bei ClosedXML.Excel.XLCell.RecalculateFormula(String fA1)
bei ClosedXML.Excel.XLCell.Evaluate(Boolean force)
bei ClosedXML.Excel.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action)
bei ClosedXML.Excel.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action)`

**Comment by igitur** [comment]
That is the correct behaviour.

**Comment by igitur** [comment]
There is a separate issue at #1404 where we consider returning an error type instead of raising an exception when one of the cell's formula evaluation fails.
