### ISSUE TITLE
Upgrade to ExcelNumberFormat 1.1.0 has caused the ClosedXML AdjustColumnWidths method to misbehave

### ISSUE THREAD

**Issue by sekuether21** [ClosedXML/ClosedXML#1651]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

AdjustColumnWidths is not behaving appropriately since upgrading to ExcelNumberFormat 1.1.0.  Some columns are wider than the data in the columns and some are narrower.

**What is the expected behavior or new feature?**

AdjustColumnWidths should behave appropriately - setting all columns to the width of the data in the column.  This worked perfectly with ExcelNumberFormat 1.0.10, but fails since upgrading.

**Is this a regression from the previous version?**

Tested regression version of ExcelNumberFormat 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
private static void Main(string[] args)
{
XLWorkbook wb = new XLWorkbook();
IXLWorksheet ws = wb.Worksheets.Add();

ws.Row(1).Style.Font.Bold = true;
ws.Column(1).Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Right);
ws.Column(2).Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Right);
ws.Column(3).Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Right);
ws.Cell(1, 1).SetValue("Date");
ws.Cell(2, 1).SetValue(DateTime.Now.Date);
ws.Cell(3, 1).SetValue(DateTime.Now.Date.AddDays(7));
ws.Cell(1, 2).SetValue($"First{Environment.NewLine}Amount");
ws.Cell(2, 2).SetValue(123456.78).Style.NumberFormat.Format = "[$$-en-US] #,##0.00";
ws.Cell(3, 2).SetValue(12345678).Style.NumberFormat.Format = "[$$-en-US] #,##0.00";
ws.Cell(1, 3).SetValue($"Second{Environment.NewLine}Amount");
ws.Cell(2, 3).SetValue(1.23).Style.NumberFormat.Format = "[$$-en-US] #,##0.00";
ws.Cell(3, 3).SetValue(123).Style.NumberFormat.Format = "[$$-en-US] #,##0.00";
ws.Cell(1, 4).SetValue("Text");
ws.Cell(2, 4).SetValue("Go");
ws.Cell(3, 4).SetValue("Go Go Go");

ws.Columns().AdjustToContents();

wb.SaveAs(@"c:\temp\test.xlsx");
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
![AdjustColumnWidths bad](https://user-images.githubusercontent.com/82116000/113932822-80c3ed80-97b9-11eb-9b93-792c419afa5f.jpg)
[test with new ExcelNumberFormat.xlsx](https://github.com/ClosedXML/ClosedXML/files/6274423/test.with.new.ExcelNumberFormat.xlsx)
[test with old ExcelNumberFormat.xlsx](https://github.com/ClosedXML/ClosedXML/files/6274424/test.with.old.ExcelNumberFormat.xlsx)

**Comment by igitur** [comment]
For each cell, the `cell.GetFormattedString()` method is called to determine the width of the cell. That method uses ExcelNumberFormat. Please assist by identifying the cells which have different resulting values of `cell.GetFormattedString()` using the old and new version of ExcelNumberFormat.

**Comment by sekuether21** [comment]
Here you go.  It looks like cell.GetFormattedString() method is not returning the formatted string with ExcelNumberFormat 1.1.0 where with version 1.0.10 it was.

Using ExcelNumberFormat 1.0.10:
***@***.***D72C55.4BD82DE0]

Using ExcelNumberFormat 1.1.0:
***@***.***D72C55.4BD82DE0]

Thanks, SK

Scott Kuether
Application Developer
p. 314.335.1289 | m. 314.884.0735 | ***@***.******@***.***>

U.S. Bancorp Community Development Corporation　
1307 Washington Ave., Suite 300 | St. Louis, MO 63103 | usbank.com/cdc<www.usbank.com/cdc　>　

Tax Credit Investments | Community Lending | Syndications



From: Francois Botha ***@***.***>
Sent: Thursday, April 8, 2021 3:00 AM
To: ClosedXML/ClosedXML ***@***.***>
Cc: Kuether, Scott E ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ClosedXML/ClosedXML] Upgrade to ExcelNumberFormat 1.1.0 has caused the ClosedXML AdjustColumnWidths method to misbehave (#1651)

[WARNING] Use caution when opening attachments or links from unknown senders.


For each cell, the cell.GetFormattedString() method is called to determine the width of the cell. That method uses ExcelNumberFormat. Please assist by identifying the cells which have different resulting values of cell.GetFormattedString() using the old and new version of ExcelNumberFormat.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ClosedXML_ClosedXML_issues_1651-23issuecomment-2D815544471&d=DwMCaQ&c=1hIq-C3ayh4zm6RZ7m4R2A&r=vYPHq1wFNoVUkJ5dBm-yFcC0pvcv-xIi8lxn5paL_oU&m=QAhPP5JLcUlRW5ylDu_UagN-W7rx5RQTOdyr_BflbOE&s=kS9x3kpj-fJ6YRkJdQxR6cNj4n2Qpj8t1W927GRlhKU&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ATSP3IEGWUTBMXMPL3FIHSDTHVPBLANCNFSM42RQTMWQ&d=DwMCaQ&c=1hIq-C3ayh4zm6RZ7m4R2A&r=vYPHq1wFNoVUkJ5dBm-yFcC0pvcv-xIi8lxn5paL_oU&m=QAhPP5JLcUlRW5ylDu_UagN-W7rx5RQTOdyr_BflbOE&s=a8KEQnyJlj6qnWmBDqKQfwRmTc6GNdagZRfkY-NgpII&e=>.


U.S. BANCORP made the following annotations
---------------------------------------------------------------------
Electronic Privacy Notice. This e-mail, and any attachments, contains information that is, or may be, covered by electronic communications privacy laws, and is also confidential and proprietary in nature. If you are not the intended recipient, please be advised that you are legally prohibited from retaining, using, copying, distributing, or otherwise disclosing this information in any manner. Instead, please reply to the sender that you have received this communication in error, and then immediately delete it. Thank you in advance for your cooperation.

---------------------------------------------------------------------

**Comment by igitur** [comment]
> Here you go. It looks like cell.GetFormattedString() method is not returning the formatted string with ExcelNumberFormat 1.1.0 where with version 1.0.10 it was. Using ExcelNumberFormat 1.0.10: ***@***.***D72C55.4BD82DE0] Using ExcelNumberFormat 1.1.0: ***@***.***D72C55.4BD82DE0] 

Please use the web interface to reply. It looks like your company mail server is mangling some of the values in your response.

**Comment by sekuether21** [comment]
Here you go. It looks like cell.GetFormattedString() method is not returning the formatted string with ExcelNumberFormat 1.1.0 where with version 1.0.10 it was. 

Using ExcelNumberFormat 1.0.10:
![test with old ExcelNumberFormat](https://user-images.githubusercontent.com/82116000/114048379-20cc5600-9850-11eb-886e-cbab6773a02b.jpg)

Using ExcelNumberFormat 1.1.0:
![test with new ExcelNumberFormat](https://user-images.githubusercontent.com/82116000/114048524-45c0c900-9850-11eb-9f03-955d866fc75e.jpg)

**Comment by igitur** [comment]
I think this is caused by https://github.com/andersnm/ExcelNumberFormat/issues/31
