### ISSUE TITLE
Help page - sample color display

### ISSUE THREAD

**Issue by surpavan** [ClosedXML/ClosedXML#1655]
Not related to code, but to the documentation.

The predefined colors are mentioned in below page, but is it possible to add color sample in page  beside it, so that we can know what color it is instead of googling again with the color name.

https://github.com/ClosedXML/ClosedXML/wiki/ClosedXML-Predefined-Colors

**Comment by igitur** [comment]
Fixed.

**Comment by surpavan** [comment]
Awesome.  Thank you for the very quick action.
