### ISSUE TITLE
Cannot add New Line

### ISSUE THREAD

**Issue by rusith** [ClosedXML/ClosedXML#166]
I need to add a new line inside a cell value. when i add \n in the value the cell is not wrapping

**Comment by igitur** [comment]
See the example code in https://github.com/ClosedXML/ClosedXML/blob/bb029cebaf02bf74b810cd10e1fc026710c1e3a6/ClosedXML_Examples/Misc/AdjustToContents.cs#L99 for how to add a new line. You should be using the cell's rich text.
