### ISSUE TITLE
Text separated with comma become datetime string in Excel file

### ISSUE THREAD

**Issue by jimmykzm94** [ClosedXML/ClosedXML#1667]
Hi. Thanks for the ClosedXML library.

I am working on array data separated with comma, and storing the text to worksheet:
```
worksheet.Cell(rowIndex, columnIndex).Value = "1,2,3";
```
When I look at generated Excel file, it is in datetime string which is "1/2/2003".

May I ask if this is a bug or expected result?

**Comment by igitur** [comment]
When you use `IXLCell.Value` ClosedXML tries to guess the data type. In your case `"1,2,3"` is a valid DateTime value.

```
Microsoft (R) Visual C# Interactive Compiler version 3.9.0-6.21160.10 ()
Loading context from 'CSharpInteractive.rsp'.
Type "#help" for more information.
> DateTime.Parse("1,2,3")
[2001-02-03 00:00:00]
```

See https://github.com/ClosedXML/ClosedXML/wiki/Text-with-numbers-are-getting-converted-to-numbers if you want to force text.
