### ISSUE TITLE
Documentation issue - sheet protection examples in wiki use old style protection

### ISSUE THREAD

**Issue by PumpkinVision** [ClosedXML/ClosedXML#1668]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.4

**What is the current behavior?**

This is not an issue with the library. It is just an issue with the wiki documentation that is part of the github project. The example code illustrates sheet protection using old style methods such as "SetFormatCells()", whereas it appears that the new style is:

IXLSheetProtection protection = coreSheet.Protect(worksheetPassword);
protection.AllowedElements = XLSheetProtectionElements.FormatCells | XLSheetProtectionElements.FormatColumns;

Sheet protection is illustrated in the wiki at the following links:
[https://github.com/ClosedXML/ClosedXML/wiki/Sheet-Protection](https://github.com/ClosedXML/ClosedXML/wiki/Sheet-Protection)
[https://github.com/ClosedXML/ClosedXML/wiki/Comments-Style-Protection](https://github.com/ClosedXML/ClosedXML/wiki/Comments-Style-Protection)

**What is the expected behavior or new feature?**

The examples would be beneficial if they illustrated the new style of protection. When I updated all of my nuget packages, it took me some time to figure out the new style so that I could build my project. Having originally learned from the wiki examples, it would have helped me to have had those examples updated.

**Is this a regression from the previous version?**

It's a regression for the documentation insofar as the examples used to be accurate for the latest build but now are not.

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
This now compiles:
```c#
IXLSheetProtection protection = coreSheet.Protect(worksheetPassword);
protection.AllowedElements =
    XLSheetProtectionElements.FormatCells |
    XLSheetProtectionElements.FormatColumns |
    XLSheetProtectionElements.FormatRows |
    XLSheetProtectionElements.SelectUnlockedCells |
    XLSheetProtectionElements.SelectLockedCells |
    XLSheetProtectionElements.Sort;
```

This used to compile but no longer does:
```c#
IXLSheetProtection protection = coreSheet.Protect(worksheetPassword)
                                                .SetFormatCells()
                                                .SetFormatColumns()
                                                .SetFormatRows()
                                                .SetSelectUnlockedCells()
                                                .SetSelectLockedCells()
                                                .SetSort();
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by Pankraty** [comment]
Thanks! Both samples updated.
