### ISSUE TITLE
Create file in memory

### ISSUE THREAD

**Issue by feldrim** [ClosedXML/ClosedXML#167]
I want to create a report using an `ExcelHelper` class with ClosedXML. Now I save it in the `TEMP` folder, then open it via `Process.Start(path)`. Yes, it is not the ideal solution but a workaround. I'd like to save it on a filestream (which I can), then execute Excel using the fs (which I cannot). I don't want to use `Interop.Excel`, because that's why I use ClosedXML.

**Comment by vbjay** [comment]
You don't point excel to the filestream. You point it at the path the
filestream points to. The filestream can point anywhere.

**Comment by feldrim** [comment]
Well, I can use `workbook.SaveAs(fs)` but I don't know how can I use it without saving it on TEMP or any other folder. So it is pointless. 

I worked as a system administrator for a while. I wrote vbs scripts, batch files and powershell scripts that reports to Excel. They execute Excel with an empty workbook and append data on the runtime. For example I ping the machines and retrieved information I need from them this way. But I couldn't manage finding a way to do this with `XlWorkbook` object.

**Comment by igitur** [comment]
Your vbs scripts probably did that via Interop. And at the end I supported files got saved too? 

I don't know what you want to achieve, but you can save to a file or any stream, which can be a MemoryStream for example.

**Comment by feldrim** [comment]
Propably they did, I couldn't remember. Those are still used in my old workplace. Well, assume it as a report created by a result of SQL query. The data is taken by an SQL query and converted to a datatable object by a service, then sent to the client to show in a data grid. When the user clicks report it must be created as a new file which forces the user to save it -if he/she wants of course- as a new file. If they just need to copy the data from there to somewhere else they could just do a university combo and paste it somewhere needed. With the way I use, I have a `randomName.xlsx` saved in `TEMP` folder. After a while `TEMP` folder will be full of unused Excel files. I'm thinking of deleting all the Excel files in `TEMP` on window exit event. I cant just trigger Excel.exe with the file i created with my `ExcelHelper` methods using ClosedXML. Since I can't do it with ClosedXML I tried it with `Interop.Excel`, somehow it didn't work too. I'm still working on it. Alternatively I'm thinking about using OLEDB object for excel but it's a really bad code smell: Two different libraries doing almost the same job.

**Comment by igitur** [comment]
Hope you succeed.

**Comment by vbjay** [comment]
Store the created random file paths in temp in a list. When you want to
clean up, iterate over the list and try to delete the file. If the file is
open you will get an exception. Ignore the exception. Remove the
successfully deleted files from the list.

**Comment by feldrim** [comment]
I created a random-named Excel file with each action and open it using 'Process.Start(path)'.  Immediately after that, I created a `while(!success)` loop with a try -  catch. In try I wrote `File.Delete(path)` and catch the `IOException`. So that when the user closed the Excel window, it deletes the file from temp. This is not the best way because it needs file write, read and delete actions, which requires so many system calls. This is the bottleneck of the process. That's why I want to send the filestream into Excel through ClosedXML.

**Comment by vbjay** [comment]
That is a dumb way to do that. You have a loop that is processing and
creating an exception each time.

Your process should be

List<string> cleanup = new...

When you create excel report

Cleanup.add(path to excel file)

When you close window.

List<string> tmp = new...
foreach (string f in cleanup)
{
Try
{
//Delete file
// Add f to tmp

}
Catch..{}

Cleanup=cleanup.except(tmp)

**Comment by vbjay** [comment]
The other thing you can do is watch for the process to quit.
https://msdn.microsoft.com/en-us/library/fb4aw7b8(v=vs.110).aspx

**Comment by igitur** [comment]
There's nothing wrong with using Interop to check whether the file is currently open in Excel.

**Comment by vbjay** [comment]
That too. I was more focused on the fact he was looping through and waiting
for a non exception to quit the loop.
