### ISSUE TITLE
Error: referenced assembly 'closedxml' does not have a strong name with latest nuget package

### ISSUE THREAD

**Issue by Swordancer** [ClosedXML/ClosedXML#1677]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Did you test against the latest CI build?**
- [x] No

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

I got an error:
>referenced assembly 'closedxml' does not have a strong name

**What is the expected behavior or new feature?**

I was forced to use StrongNamer nuget package to use this one. I belive it should have a strong name as all other nuget packages.

**Is this a regression from the previous version?**

I didn't checked older minor version of nuget packages, just 0.95.3 as I already got a temporary solution. 

## Reproducibility
Just install nuget packege to project that has signed assembly. I don't have any problem with other packages.

**Comment by igitur** [comment]
You could have used https://www.nuget.org/packages/ClosedXML.Signed/ 

But from v0.96 the standard https://www.nuget.org/packages/ClosedXML/ package will be signed as well.
