### ISSUE TITLE
Opening Excel with notes thorws exception - System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by WicSan** [ClosedXML/ClosedXML#1678]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**
0.95.4 NuGet package.

**What is the current behavior?**
I have an Excel with formatted notes (with margins: 2.3mm, 1.3mm, 0, 1.3mm) in certain cells. When i try to open the attached Excel the following exception is thrown: 
```c#
Unhandled exception. System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at ClosedXML.Excel.XLWorkbook.GetInsetValue(String value)
   at ClosedXML.Excel.XLWorkbook.LoadTextBoxInset[T](IXLDrawing`1 xlDrawing, XAttribute attInset)
   at ClosedXML.Excel.XLWorkbook.LoadTextBox[T](IXLDrawing`1 xlDrawing, XElement textBox)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName)
   at ClosedXML.Excel.XLWorkbook.Load(String file)
   at ClosedXML.Excel.XLWorkbook..ctor(String file, XLEventTracking eventTracking)
   at ClosedXML.Excel.XLWorkbook..ctor(String file)
   at ClosedXMLTest.Program.Main(String[] args) in C:\Users\TAAWISAB\source\repos\ClosedXMLTest\Program.cs:line 10
```

**What is the expected behavior or new feature?**
The excel should open without throwing an exception

**Is this a regression from the previous version?**
No

## Reproducibility
Excel file: [test.xlsx](https://github.com/ClosedXML/ClosedXML/files/6656516/test.xlsx)

**Code to reproduce problem:**
```c#
public static void Main(string[] args)
{
    using var wb = new XLWorkbook("test.xlsx");
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by neumannalex** [comment]
I am running into the same issue. When looking at a Textbox definition like <v:textbox style='mso-direction-alt:auto' inset="2.16pt,1.8pt,0,0"> it seams that at least this line has to be fixed: [https://github.com/ClosedXML/ClosedXML/blob/ce7fb695a70d2e870078db4efe143a9e90ac7ad2/ClosedXML/Excel/XLWorkbook_Load.cs#L1367]

**Comment by jbb3141afs** [comment]
Confirmed. As of July 24th, 2023, I am receiving this error when simply opening a spreadsheet with ClosedXML that contains a Comment or Note.

**Comment by TheMonolithDestroyer** [comment]
The solution is:
private double GetInsetValue(string value)
{
    String v = value.Trim();
    if (v.EndsWith("pt"))
        return Double.Parse(v.Substring(0, v.Length - 2), CultureInfo.InvariantCulture) / 72.0;
    else
        return Double.Parse(v, CultureInfo.InvariantCulture);
}

**Comment by TheMonolithDestroyer** [comment]
```
private double GetInsetValue(string value)
{
    string v = value.Trim();
    if (v.EndsWith("pt"))
        return Double.Parse(v.Substring(0, v.Length - 2), CultureInfo.InvariantCulture) / 72.0;
    else if (v.EndsWith("mm"))
        return Double.Parse(v.Substring(0, v.Length - 2), CultureInfo.InvariantCulture) / 25.4;
    else
        return Double.Parse(v, CultureInfo.InvariantCulture);
}
```
