### ISSUE TITLE
Style.NumberFormat.Format - throws {"An item with the same key has already been added. Key: 171"}

### ISSUE THREAD

**Issue by Pitterling** [ClosedXML/ClosedXML#1679]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.95.4

**What is the current behavior?**
 
range.Style.NumberFormat.Format = "#,##0.00;-#,##0.00;0;@";    // <-- causing Exception
range.Style.NumberFormat.NumberFormatId = 40;                       // <-- works

```console
System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added. Key: 171
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at ClosedXML.Excel.XLWorkbook.GenerateWorkbookStylesPartContent(WorkbookStylesPart workbookStylesPart, SaveContext context)
   at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file)
   at ClosedXML_FormatBug.Program.Main(String[] args) in C:\xxx\ClosedXML-FormatBug\Program.cs:line 25
```

**What is the expected behavior or new feature?**

No Exception.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
            using (var templateWorkbook = new XLWorkbook("template.xlsx")) { 
            
                var templateWorksheet = templateWorkbook.Worksheet("SourceData");
                var templateListObject = templateWorksheet.Table("SourceDataTable");

                var counterHeaderCell = templateListObject.Field("Counter").HeaderCell;

                var counterRange = templateWorksheet.Range(counterHeaderCell, templateListObject.LastCellUsed());
                counterRange.Select();

                counterRange.Style.NumberFormat.Format = "#,##0.00;-#,##0.00;0;@";    // <-- causing Exception
                //counterRange.Style.NumberFormat.NumberFormatId = 40; // <-- will work

                templateWorksheet.Columns().AdjustToContents(1, 5);

                templateWorkbook.SaveAs("ClosedXML-Format-Bug.xlsx");
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[template.xlsx](https://github.com/ClosedXML/ClosedXML/files/6656973/template.xlsx)

**Comment by KentMiller** [comment]
I am also seeing this error in version 0.95.4 and 0.96.0. It also happens when setting custom Number format on individual cells.

**Comment by Pitterling** [comment]
@jahav any chance to get this addressed in one of the next releases?

**Comment by jahav** [comment]
@Pitterling I made a PR with potential fix. I am not very familiar with this particular corner, but it shouldn't throw an exception (hopefully). Feel free to try it out: https://github.com/ClosedXML/ClosedXML/wiki/Development-Builds

It should work if you don't touch table header cells (likely due to #1941), use range that doesn't touch headers, for the `var counterRange = templateWorksheet.Range("2:2");`

**Comment by jahav** [comment]
I also added some info about the feature to the documentation: https://closedxml.readthedocs.io/en/latest/features/cell-format.html#number-format

I have to get used to improving the docs.

**Comment by Pitterling** [comment]
@jahav Please reopen. I tried your fix, but still getting the same error.

I slightly adjusted my example from above and set the number format only to the data cell.

```c#
            var counterRange = templateListObject.Field("Counter").DataCells;
            counterRange.Select();

            counterRange.Style.NumberFormat.Format = "#,##0.00;-#,##0.00;0;@";
```

**Comment by jahav** [comment]
It does work for me (the counter column *AN* has requested format and there is no exception). Are you sure you are using dev build? Try it on develop branch in the ClosedXML.Sandbox project.

I have a different locale, so thousands separator (coma, see ECMA-376 18.8.31) is displayed as a space, but that is just Excel translating everything before showing it to the user (the styles.xml in the file is as it should be).

![image](https://user-images.githubusercontent.com/7634052/210193574-62a3edc8-d58e-47d1-8d15-f9fe16215955.png)

```csharp
            using (var templateWorkbook = new XLWorkbook(@"c:\Temp\1679\template.xlsx"))
            {
                var templateWorksheet = templateWorkbook.Worksheet("SourceData");
                var templateListObject = templateWorksheet.Table("SourceDataTable");
                var counterRange = templateListObject.Field("Counter").DataCells;
                counterRange.Select();
                counterRange.Style.NumberFormat.Format = "#,##0.00;-#,##0.00;0;@";
                templateWorksheet.Columns().AdjustToContents(1, 5);
                templateWorkbook.SaveAs(@"c:\Temp\1679\ClosedXML-Format-Bug.xlsx");
            }
```

**Comment by Pitterling** [comment]
seems like nuget package cache is not updating the files in if package name/number is identical. Obviously i had an older -preview.nupkg in use. After cleaning this up and using the latest ClosedXML.dll it works.

Thanks !!
