### ISSUE TITLE
Disabling Autofilter 

### ISSUE THREAD

**Issue by feldrim** [ClosedXML/ClosedXML#168]
You can turn off the autofilter in three ways:
1. worksheet.AutoFilterRange.SetAutoFilter(false)
2. worksheet.AutoFilterRange = null
3. Pick any range in the worksheet and call range.SetAutoFilter(false);

`XLWorksheet` doesn't have a property called `AutoFilterRange`. And `SetAutoFilter` method does not have an overload that gets a boolean parameter. So these three ways described above are not usable.

**Comment by igitur** [comment]
You can use `ws.AutoFilter.Clear();`

I'll update the documentation.

**Comment by igitur** [comment]
I added the requested overload in #497

**Comment by igitur** [comment]
https://www.nuget.org/packages/ClosedXML/0.90.0-beta2 is released and should include the fix for this issue.
