### ISSUE TITLE
Cannot set XLDataType to a blank cell

### ISSUE THREAD

**Issue by JoshuaGarrison27** [ClosedXML/ClosedXML#1680]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

I am trying to programmatically create a template for my users to use to input a large data set into our system. I am setting the DataType of a column to Date however, on creation, it shows that the column is 'General'. When I select a date from the drop down (1), it converts it to the number representation (2).

![image](https://user-images.githubusercontent.com/1706923/122112997-84927280-cdef-11eb-8ec9-8698f31e8b14.png)

**What is the expected behavior or new feature?**

I expect after I select a date from the dropdown, it would remain a date and not convert it to a number.

**Is this a regression from the previous version?**

No, checked against 0.94.2 and experience the same issue.

## Reproducibility

**Code to reproduce problem:**
```c#
public static XLWorkbook GetPowerScreenTemplate()
        {
            var workbook = new XLWorkbook();
            var sheet = workbook.Worksheets.Add("PowerScreen");
            var sheet2 = workbook.Worksheets.Add("Data");

            var dateRange = sheet.Range(workbook.Worksheet(1).Cell(2, 3).Address, workbook.Worksheet(1).Cell(1000, 3).Address);
            dateRange.SetDataType(XLDataType.DateTime);

            sheet.Cell(1, 1).SetValue("Serial");
            sheet.Cell(1, 2).SetValue("Plant");
            sheet.Cell(1, 3).SetValue("Week");
            sheet.Cell(1, 4).SetValue("Note");
            sheet.Cell(1, 5).SetValue("ValidationNotes");

            var rowsMonday = 2;
            for(var day = DateTime.Today; day.Date < DateTime.Today.AddYears(1); day = day.AddDays(1))
            {
                if(day.DayOfWeek == DayOfWeek.Monday)
                {
                    sheet2.Cell(rowsMonday, 3).SetDataType(XLDataType.DateTime);
                    sheet2.Cell(rowsMonday, 3).SetValue(day);
                    rowsMonday++;
                }
            }
            var mondayRange = workbook.Worksheet(2).Range(workbook.Worksheet(2).Cell(2, 3).Address, workbook.Worksheet(2).Cell(rowsMonday, 3).Address);

            workbook.Worksheet(1).Column(3).SetDataValidation().List(mondayRange, true);
            workbook.Worksheet(1).Column(3).SetDataValidation().IgnoreBlanks = true;
            workbook.Worksheet(1).Column(3).SetDataValidation().InCellDropdown = true;

            return workbook;
        }
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[PowerScreenTemplate.xlsx](https://github.com/ClosedXML/ClosedXML/files/6658244/PowerScreenTemplate.xlsx)

## Work-around
The only work around that I have found for now is to give the cell a default value of DateTime.Today or something so that it has something to format and then it will work without issues. However, i want have a blank cell for someone to update.

**Comment by igitur** [comment]
What you see in Excel is the number format, which, in ClosedXML, is accessible via cell.Style.NumberFormat.

DataType is a property that's much more closer tied to the cell's value. You can't edit this in Excel directly, but we expose it.

**Comment by JoshuaGarrison27** [comment]
Cool. So you think if I set the style format, I can get it to work? I already left work today but I can try it first thing in the morning!

**Comment by JoshuaGarrison27** [comment]
Perfect. Thank you @igitur for your help! That worked perfectly!
