### ISSUE TITLE
Header/Footer Text Formatting 

### ISSUE THREAD

**Issue by feldrim** [ClosedXML/ClosedXML#169]
I use mostly Arial in my reports created with ClosedXML. But the header and the footer text is Calibri by default and I can't change it beforehand. A `Worksheet.PageSetup.Margin.Header.FormatText(string fontName, double fontSize)` would be a good improvement. Or maybe it can be a property setter in items, so that each can be formatted adding to defined property for header / footer.

**Comment by igitur** [comment]
```c#
            using (var wb = new XLWorkbook())
            {
                var ws = wb.AddWorksheet("Sheet1");
                ws.PageSetup.Header.Center.AddText("Test").SetFontName("Arial");
            }
```

**Comment by igitur** [comment]
Also look at the wiki page for other options: https://github.com/ClosedXML/ClosedXML/wiki/Headers-and-Footers-Tab
