### ISSUE TITLE
Program Hangs upon opening the workbook

### ISSUE THREAD

**Issue by Geral3** [ClosedXML/ClosedXML#1699]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

Once I try to open a Excel file in ClosedXML the program hangs and the memory being used by the application just continuingly rises.

**What is the expected behavior or new feature?**

Open the existing workbook and open the existing worksheet so I can write to the file.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public IXLWorkbook openExcel()
{
    IXLWorkbook workbook = new XLWorkbook(path2.Text.ToString());
    /*if (!workbook.TryGetWorksheet("Addepar Query", out ws))
    {
        MessageBox.Show("Worksheet 'Addepar Querry' not found in the workbook");
    }*/
    workbook.Worksheet(3);
    return workbook;
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)
 I can not attach an example as it has sensitive information. The spreadsheet consist of multiple columns and rows of data which I would like to write on. It also has a worksheet that has links to the bloomberg api but it is not on the specified worksheet.

**Comment by jahav** [comment]
Closing. Not reproducible, stale.

There have been several significant improvements in performance after this issue has been written. Key ones were improvements to internal structure and load of files through streaming. Rough summaries of improvements are written on release pages.

Copy of text from front page:

#### Load

| Description                                                        |  Rows     | Columns | Time to load data | Used memory |
|--------------------------------------------------------------------|-----------|---------|-------------------|-------------|
| Load mixed workbook (10 text/5 number columns). |   250 000 |      15 |        15.648 sec |     236 MiB |
| Text only workbook.                                                | 1 000 000 |      10 |       49.046 sec  |     801 MiB |

Load tests used files created during save test.

#### Save

| Description                  |     Rows  |           Columns      | Time/Memory to insert data | Save workbook | Total time/memory | 
|------------------------------|-----------|------------------------|----------------------------|------------------------------|---|
| Mixed (text/number) workbook.<br>[Gist](https://gist.github.com/jahav/bdc5fe3c90f25544ca6ae1394bbe3561) |   250 000 | 15 | 1.619 sec / 117 MiB |  6.343 sec |  7.962 sec /  477 MiB |
| Text only workbook. [Gist](https://gist.github.com/jahav/257bb2ffd5ab7adfded7e669290d8151)              | 1 000 000 | 10 | 6.302 sec / 402 MiB  | 17.134 sec | 23.436 sec / 1880 MiB |
