### ISSUE TITLE
IF changes reference argument to single cell (improper use of implicit intersection)

### ISSUE THREAD

**Issue by Shad0wlife** [ClosedXML/ClosedXML#1707]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

When trying to evaluate a Cell that has a SumIfs Formula in it, which has the sum_range parameter (= the first parameter) given as another expression (eg. an IF), the evaluation fails with a NullReferenceException, as the sum_range parameter cannot be cast to an IEnumerable.

(This cast: https://github.com/ClosedXML/ClosedXML/blob/ce7fb695a70d2e870078db4efe143a9e90ac7ad2/ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs#L387)

**What is the expected behavior or new feature?**

If the sum_range Parameter is an other Expression, evaluate that expression(-chain) first before using the result as an IEnumerable.

Possible solution is to check whether the first parameter is a FunctionExpression (which is not an IEnumerable like an XObjectExpression, but may eventually yield one!) and throw a userfriendly exception, if the evaluation chain does not return an XObjectExpression.
EDIT: Ok, So the Evaluation will also evaluate the nested expressions and evaluating a Range expression will return its first Cell. So there might be some tweaking required. Maybe Evaluating XObjectExpressions containing a Range with more than 1 Cell don't return `((IValueObject)_value).GetValue();` but only the `_value`?

**Is this a regression from the previous version?**

No.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
/// <summary>
/// Self contained reproduction of SumIfs failing when the first parameter is an Expression instead of a Range
/// This Issue is will probably happen with multiple other Formulas, like regular SumIf
/// </summary>
/// <param name="args"></param>
static void Main(string[] args)
{
    XLWorkbook testWB = new XLWorkbook();

    IXLWorksheet testWS = testWB.AddWorksheet("TEST");

    //Set Up data
    testWS.Cell(1, 1).InsertData(new List<int>() { 1, 2, 3, 4, 5 });
    testWS.Cell(1, 2).InsertData(new List<int>() { 6, 7, 8, 9, 0 });
    testWS.Cell(1, 3).InsertData(new List<int>() { 1, 1, 0, 1, 0 });

    const string filterDummy = "FilterDummy";
    testWS.Cell(1, 4).Value = filterDummy;

    //Regular SumIfs
    testWS.Cell(1, 5).FormulaA1 = $"SUMIFS(A1:A5,C1:C5,C1)";

    //Failing SumIfs
    testWS.Cell(1, 6).FormulaA1 = $"SUMIFS(IF(D1=\"{filterDummy}\",A1:A5,B1:B5),C1:C5,C1)";

    Console.WriteLine("Evaluation of regular SumIf:");
    Console.WriteLine($"Value is: {testWS.Cell(1, 5).Value}");

    Console.WriteLine("Evaluation of failing SumIf:");
    try
    {
        Console.WriteLine($"Value is: {testWS.Cell(1, 6).Value}");
    }
    catch(NullReferenceException nre)
    {
        Console.WriteLine("The evaluation failed with a NullReferenceException:");
        Console.WriteLine(nre.Message);
    }

    Console.WriteLine("Press Enter to exit.");
    Console.ReadLine();
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue) (Not Needed, Sample code should be Sufficient!)

**Comment by mrwrighty** [comment]
I'm having the same issue where a summary sheet takes cell values from another sheet. I then have to SUMIFS the values depending on the text in column A. SUMIFS doesn't work. The formula's are correct but the values shown are not. If I click in the cell and press enter on the cell formula the values returned are then corrected and return the right value in the cell.

**Comment by jahav** [comment]
IF has been marked as range function in #2509, so it doesn't implicitly intersects references and SUMIFS has been reimplemented in #2499. 

As a result, the provided reproducible scenario no longer throws NRE and calculates value `7` in both cases, which is same result as Excel.

> Evaluation of regular SumIf:
> Value is: 7
> Evaluation of failing SumIf:
> Value is: 7
> Press any key to continue

![image](https://github.com/user-attachments/assets/188ef8dc-c676-4305-aeac-8e16742444b6)
