### ISSUE TITLE
Implicit intersection doesn't work correctly

### ISSUE THREAD

**Issue by Shad0wlife** [ClosedXML/ClosedXML#1710]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.4

**What is the current behavior?**

In Code:
- Is-Functions can be given 1 to int.max parameters.
- Is-Functions that get passed a range will only return the result for the first Cell of that range.

In Excel (Office 365):
- Is-Functions can only take exactly 1 parameter
- Is-Functions that get passed a range will give a range of the same size of results.
  - Additionally, Excel files generated with the Is-Functions from ClosedXML will instead use the intersection operator "@" in Excel (Office 365)
  (See #1600) 
  While this is fine, the slicing operator will target the element of the corresponding line in the range, while the current code implementation only targets the first cell.

(Information on this behaviour:
https://exceljet.net/glossary/implicit-intersection
https://support.microsoft.com/en-us/office/implicit-intersection-operator-ce3be07b-0101-4450-a24e-c1c999be2b34 )

**What is the expected behavior or new feature?**

The Is-Functions target the correct location in the range (if a range is passed and intersection applies). The Is-Functions take the correct number of parameters (which is exactly 1). The approach to fix this can correspond with the solution of #1707 , that XObjectExpressions return the RangeObject for ranges with >1 Cell when evaluated instead of only the first cell (and then the n-th element can be picked by the Is-Function). I don't know if it is currently possible for a function to know its own cell(-location) though.

**Is this a regression from the previous version?**

No.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public static void Demo()
        {
            XLWorkbook testWB = new XLWorkbook();

            IXLWorksheet testWS = testWB.AddWorksheet("TEST");

            //Set Up data
            testWS.Cell(1, 1).InsertData(new List<int>() { 1, 2 });
            testWS.Cell(4, 1).InsertData(new List<int>() { 4, 5 });

            //Range IsBlank in each of the fields
            //IsBlank(A1:A5) results in IsBlank(@A1:A5) in Excel 365 - implicit slicing operator
            testWS.Cell(1, 2).FormulaA1 = $"ISBLANK(A1:A5)";
            testWS.Cell(2, 2).FormulaA1 = $"ISBLANK(A1:A5)";
            testWS.Cell(3, 2).FormulaA1 = $"ISBLANK(A1:A5)";
            testWS.Cell(4, 2).FormulaA1 = $"ISBLANK(A1:A5)";
            testWS.Cell(5, 2).FormulaA1 = $"ISBLANK(A1:A5)";


            //Print B1:B5
            //Will result in 5x FALSE in console, but will be FALSE, FALSE, TRUE, FALSE, FALSE in Excel
            Console.WriteLine($"B1: ISBLANK(B1): {testWS.Cell(1, 2).Value}");
            Console.WriteLine($"B1: ISBLANK(B1): {testWS.Cell(2, 2).Value}");
            Console.WriteLine($"B1: ISBLANK(B1): {testWS.Cell(3, 2).Value}");
            Console.WriteLine($"B1: ISBLANK(B1): {testWS.Cell(4, 2).Value}");
            Console.WriteLine($"B1: ISBLANK(B1): {testWS.Cell(5, 2).Value}");

            //Save File in Output directory for comparison
            testWB.SaveAs("IsFunctionTestFile.xlsx");

            Console.WriteLine("Saved File.");
        }
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue) <-- The file to compare with console output is created by the code and will be saved in the bin output folder of the executable.

**Comment by jahav** [comment]
The issue of incorrectly implemented implicit intersection has been resolved in #1812.

This issue has an unclear scope, because there are many things that are described here:
* implicit intersection didn't work, it now does
* IS functions are still broken (in a way that they don't always return what they should) - will be fixed in nearest release
* It uses a result of dynamic array formula and compares it to the result from ClosedXML that doesn't support even Excel 2016 array formulas (for now).

I am closing it as resolved, because the demo code now works on develop branch, `IS` functions will be fixed as a quick-win in next release and array formulas/dynamic array evaluation is a part of #1812.
