### ISSUE TITLE
System.InvalidOperationException: 'Table name cannot be a valid Cell Address 'T1'.' but Excel currently allows that name

### ISSUE THREAD

**Issue by NikiLentz** [ClosedXML/ClosedXML#1712]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [ ] No

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

Currently creating a workbook with a worksheet named "T1" throws an error. IMO this is wrong, since Excel 365 allows me to do this

**What is the expected behavior or new feature?**

No Exception thrown anymore for "Table name cannot be a valid cell adress" or at least a possibility to willfully ignore it.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
```
public void Main()
{
 XLWorkbook wb = new XLWorkbook();
                    
                wb.Worksheets.Add(dataTable, "T1");
}
```
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by danreg** [comment]
Is there any plan to fix this? It was also occuring for worksheet named TSS1234

**Comment by NickNack2020** [comment]
@jahav this is a problem because sheetName is used when inserting the table, and Table names can't be named like a cell reference like T1.

Code that causes the issue
```
       public IXLWorksheet Add(DataTable dataTable, String sheetName)
        {
            var ws = Add(sheetName);
            ws.Cell(1, 1).InsertTable(dataTable, sheetName);
            return ws;
        }
```
I propose we add an overload

```
 public IXLWorksheet Add(DataTable dataTable, String sheetName,  String tableName){
            var ws = Add(sheetName);
            ws.Cell(1, 1).InsertTable(dataTable, tableName);
            return ws;
        }
```

And forward Add(DataTable dataTable, String sheetName) to the new overload. 

I am happy to make this change if approved.

**Comment by jahav** [comment]
I think it would be better to replace table names with a generated names Table1, Table2.... That way, there won't be an exception. 
@igitur You have replaced generated table names in #1444, along with a check whether autofilter overlaps with a table. Did it have a reason or was it just an improvement?

@NickNack2020 Adding an overload doesn't solve underlaying issue that API has a hidden constraint of the `Add` method. There is a workaround of adding a worksheet, adding a table data and so on.

**Comment by igitur** [comment]
> Did it have a reason or was it just an improvement?

It was just an improvement based on personal pref. I use Excel tables a lot, generally 1 per sheet and always name the sheet and table identically. When debugging formulas that references this, it just simplifies things. @pankraty approved of it in https://github.com/ClosedXML/ClosedXML/pull/1444/commits/bafcff71fd82eb84cf34fa562d1e1ce763c53acb#r429775081

**Comment by jahav** [comment]
@NickNack2020 In that case please add an overload with both sheetName and tableName and modify the original so it uses a generated name. That aligns better with other places where table is created: unless user specifies a table name, a generated one is used.

That way, using the same name for sheet and table is just a matter of duplicating the variable name 
```
// Interface
IXLWorksheet Add(DataTable dataTable, String sheetName, String tableName);

// usage to add a table with same name of the table as the sheet.
wb.Worksheets.Add(dataTable, sheetName, sheetName);
```
