### ISSUE TITLE
Is asyncronous stream reading available (for Blazor)? 

### ISSUE THREAD

**Issue by CaiusJard** [ClosedXML/ClosedXML#1733]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [X] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

![image](https://user-images.githubusercontent.com/68939130/138321242-6ec963de-5bf2-4575-aa7e-a520b7ccc9ad.png)

**What is the current behavior?**

Blazor likes reading from streams to be done async; I wonder if it's supported. SO far I'm using CsvHelper, CsvHelper.Excel and ClosedXml; CSVH.E is an adapter between CXML and CSVH, that (i guess) facades an XLSX as a CSV so that CSVH can read it

CSVH.E does this in it's main constructor:

    var workbook = new XLWorkbook(stream, XLEventTracking.Disabled);

The moment it does this, a blazor server app gets an exception "Syncronous reads are not supported"

**What is the expected behavior or new feature?**

I'm wondering if there is an async reading of the stream available. If I pass the stream and CX reads it async I'm sure Blazor won't complain. Of course, I could also buffer the whole file in a memory stream asyncly, and then give the memstream to CX, but it would be nice to not have to load it into memory twice, as some of my files are huuuge

**Is this a regression from the previous version?**

I doubt it

## Reproducibility

1) Make a new blazor server app from template in VS2019 (probably doesn't matter the VS version so much)
2) Install nuget package ClosedXml
3) Paste code below over the top of the Counter.razor page contents generated from the project template
4) Run app and pick an XLSX file you have that is less than 1mb big

**Code to reproduce problem:**
```c#
@page "/counter"

<h1>Load an XLSX</h1>
<InputFile OnChange="@LoadFilesAsync"> </InputFile>

@code {
    void LoadFilesAsync(InputFileChangeEventArgs e)
    {
        using var stream = e.File.OpenReadStream(1024000);
        var workbook = new ClosedXML.Excel.XLWorkbook(stream, ClosedXML.Excel.XLEventTracking.Disabled);
    }
}
```

**Comment by jahav** [comment]
As far as I can tell, there is no async code in the whole codebase, nor is there any use of a Task type. I am afraid you will have to buffer the file. /random-passerby
