### ISSUE TITLE
PRODUCT function doesn't work on cell range

### ISSUE THREAD

**Issue by joshcampbell191** [ClosedXML/ClosedXML#1744]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

The `PRODUCT` function doesn't return the correct result when passed a cell range.

**What is the expected behavior or new feature?**

When passed a cell range, the `PRODUCT` function should return the product of the values within the cell range.

**Is this a regression from the previous version?**

No

## Reproducibility

```c#
public void Main()
{
    using (var wb = new XLWorkbook())
    {
        var ws = wb.Worksheets.Add("Sample Sheet");
        ws.Cell("A1").SetValue(1).CellBelow().SetValue(2).CellBelow().SetValue(3);
        ws.Cell("B1").FormulaA1 = "=PRODUCT(A1:A3)";
        ws.Cell("C1").FormulaA1 = "=PRODUCT(A1, A2, A3)";

        var rangeProduct = ws.Cell("B1").Value; // Incorrectly returns 1
        var cellProduct = ws.Cell("C1").Value;  // Correctly returns 6
    }
}
```

**Comment by jahav** [comment]
`PRODUCT` function has been reimplemented in #2442 (and then again to use Tally in #2471). The provided repro now calculates correct value 6 in both cases, which is identical to to excel.
