### ISSUE TITLE
Allow references to worksheet with a space in its name

### ISSUE THREAD

**Issue by andrewkress** [ClosedXML/ClosedXML#175]
when print area has comma in the definedName.Text, ie:
'C100,C101,102,103,C200'!$A$1:$F$271

the line:
`foreach (string area in definedName.Text.Split(','))`
in XLWorkbook_Load.cs does not parse it correctly resulting in the call to ParseReference to throw the index out of range exception when assigning the sheetArea variable.

This will occur when there is a comma in any Sheet name that has a Print Area defined.  Attached is a file that will replicate this issue.
[Test Workbook.xlsx](https://github.com/ClosedXML/ClosedXML/files/730695/Test.Workbook.xlsx)

**Comment by andrewkress** [comment]
I created a fix for this in my repo:
https://github.com/andrewkress/ClosedXML/tree/issue175-parse-commas-in-print-area

Let me know what is required and I can create a pull request.

**Comment by andrewkress** [comment]
#177 Tagging the pull request

**Comment by igitur** [comment]
I'm considering moving to https://github.com/spreadsheetlab/XLParser for the entire parsing.

**Comment by andrewkress** [comment]
If there is an existing library that this functionality is duplicating, that would make sense.  What aspects could we use it to parse?

**Comment by andrewkress** [comment]
I can use this library to fix the current issue.  I will create a new pull request as that will be cleaner.  If there are other instances that the library can be used to parse information, that can be done in other pull requests.

**Comment by andrewkress** [comment]
Alright, digging in more, this maybe useful...I'll play with it.

**Comment by igitur** [comment]
If you can upgrade, I would recommend this. It's getting difficult to maintain the .NET 3.5 dependency.
