### ISSUE TITLE
Loading a complex file crashes the process

### ISSUE THREAD

**Issue by samusaran** [ClosedXML/ClosedXML#1757]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

- 0.95.4
- AppVeyor 0.95.999.2326

**What is the current behavior?**

While loading a big XLSX file (21MB, more than 10 worksheets, a couple of PowerQuery queries, a lot of pivot tables), the programs hangs, while increasing memory usage, and then crashes [here](https://github.com/ClosedXML/ClosedXML/blob/ce7fb695a70d2e870078db4efe143a9e90ac7ad2/ClosedXML/Excel/XLWorkbook_Load.cs#L823) with the following exception:

```
System.ArgumentOutOfRangeException: 'Specified argument was out of the range of valid values.
Parameter name: index'
```

**What is the expected behavior or new feature?**

To load the document.

**Is this a regression from the previous version?**

I don't know, I could test this with previous versions if needed.

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
   using var workbook = new XLWorkbook("C:\\MyExcelFile.xlsx");
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

If needed I can send the spreasheet that causes this problem to some of you, since it may contains confidential data.
I'll try to delete thing in the file until I get the smallest possible file that still have the issue.

**Comment by jahav** [comment]
> 21MB, more than 10 worksheets, a couple of PowerQuery queries, a lot of pivot tables

Issue is stale, declared version was 0.95.4 (4 y/o), doesn't have repro and ClosedXML is not in a state to deal with such a complex workbooks.

Closing.
