### ISSUE TITLE
Saving value date '1000-01-01' in xlsx

### ISSUE THREAD

**Issue by Yafar** [ClosedXML/ClosedXML#176]
Hi,

 I try to save, for example, code like this, as xlsx:

```
SELECT CAST('1000-01-01' AS DATE) DATA
UNION ALL
SELECT CAST('1000-01-01' AS DATE) DATA
UNION ALL
SELECT CAST('1000-01-01' AS DATE) DATA
UNION ALL
SELECT CAST('1000-01-01' AS DATE) DATA
UNION ALL
SELECT CAST('1000-01-01' AS DATE) DATA
UNION ALL
SELECT CAST('1000-01-01' AS DATE) DATA
```

The values are in DataTable table, and I'm saving like that:

```
                XLWorkbook wb = new XLWorkbook();

                wb.Worksheets.Add(table, "sheet1");

                wb.SaveAs(place);
```

And it saves like this:

> DATA
> ########
> ########
> ########
> ########
> ########
> ########

When I move the cursor on the value it shows: -328716

How I can bypass this issue without interfering in sql code?

Ps. Sory for my english :<

**Comment by igitur** [comment]
1000-01-01 isn't a date that Excel can handle. You can try entering it manually into a cell in Excel and you'll see it doesn't accept it, but changes it to another date.

My suggestion is after adding the datatable, to loop through the cells and change the cells' values to something that you want that Excel can display.

**Comment by Yafar** [comment]
So, no simple solutions, thx for an answere, I wasn't aware of this :)

**Comment by igitur** [comment]
Pleasure. Pity you can't change the SQL. It should be returning nulls instead of invalid dates. It's poor design.

**Comment by Yafar** [comment]
yeah that's how the db is designed, unfortunatelly :<
