### ISSUE TITLE
VLOOKUP doesn't work correctly

### ISSUE THREAD

**Issue by EngineThatCould** [ClosedXML/ClosedXML#1763]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

When reading the Cell.Value, in C#, from a valid .xlsx file I receive a "No matches found" exception message.

**What is the expected behavior or new feature?**

Cell.Value should contain the valid string value as displayed in the worksheet.

**Is this a regression from the previous version?**

Don't believe so.

## Reproducibility
**Code to reproduce problem:**
The Excel cell formula that is causing the issue is:
```Excel
=IF(ISNA(VLOOKUP($A2,Sheet2!$A$2:$B$10,1,FALSE)),"Default",IF(B2>VLOOKUP($A2,Sheet2!$A$2:$B$10,2,FALSE),"Found","Not Found"))
```

```c#
public void Main()
{
    DataTable dt = null;
    string filePath = "No Match Found - Sample.xlsx";  //Add path to Excel Spreadsheet here

    if (File.Exists(filePath)) {
        using (var fileStream = File.OpenRead(filePath)) {
            using (var workbook = new XLWorkbook(fileStream)) {
                var ws = workbook.Worksheet("Sheet1");
                    dt = ToDataTable(ws);
            }
        }
    }
}

public static DataTable ToDataTable(IXLWorksheet worksheet, int headerRow = 1) {
    var dt = new DataTable(worksheet.Name);
    //Range for reading the cells based on the last cell used.
    var maxCol = 1;
    worksheet.RowsUsed().ForEach(r => maxCol = Math.Max(r.LastCellUsed().Address.ColumnNumber, maxCol));
    var readRange = $"1:{maxCol}";
    worksheet.RowsUsed().ForEach(row => {
        if (row.RangeAddress.FirstAddress.RowNumber == headerRow) { //If reading the First Row (used) then add them as column name
            row.Cells(readRange).ForEach(cell => {
                var uniqueColumnNum = 1;
                while (cell.Address.ColumnNumber > dt.Columns.Count + 1) {
                    dt.Columns.Add("Untitled_Column_" + (dt.Columns.Count + 1).ToString());
                }
                var headerName = cell.Value.ToString().Replace('\n', ' ').Trim();
                while (dt.Columns.Contains(headerName)) {
                    headerName = cell.Value.ToString().Replace('\n', ' ').Trim() + "_" + uniqueColumnNum++;
                }
                dt.Columns.Add(headerName);
            });
            while (maxCol >= dt.Columns.Count + 1) {
                dt.Columns.Add("Untitled_Column_" + (dt.Columns.Count + 1).ToString());
            }
        } else if (row.RangeAddress.FirstAddress.RowNumber > headerRow) {
            //Adding a Row in datatable
            dt.Rows.Add();
            var cellIndex = 0;
            //Updating the values of datatable
            row.Cells(readRange).ForEach(cell => {
                dt.Rows[dt.Rows.Count - 1][cellIndex] = cell.Value.ToString();  //This is where the exception occurs, "No Matches Found"
                cellIndex++;
            });
        }
    });
    return dt;
}

```

- [x] I attached a sample spreadsheet.
[No Match Found - Sample.xlsx](https://github.com/ClosedXML/ClosedXML/files/8047212/No.Match.Found.-.Sample.xlsx)

**Comment by jahav** [comment]
I have simplified the error case to this `ISNA(VLOOKUP(...))`. The VLOOKUP didn't match anything and ended with #N/A and ISNA should convert it to true or false.
It didn't. It only works when a with a constant (`ISNA(#N/A)`) and it seems that most other error functions in Information category have the similar problem (they expect that they will get a return value on error, but exception is thrown).

Basic issue is that error handling is inconsistent and doesn't work properly.

**Comment by jahav** [comment]
The code from original now works. CalcEngine has been significantly redesigned, VLOOKUP function and info functions were reimplement to be compliant with Excel.

VLOOKUP  still doesn't support wildcard search for exact search. I would have to parse it, find escapes and match it. Converting to could regexp also work, but regexp are overkill and pretty slow (+.NET4 allocate memory) and VLOOKUP should be fast. There is a pretty fast algorithm out there for wildcard matching: https://en.wikipedia.org/wiki/Krauss_wildcard-matching_algorithm, but that is something for future me.
