### ISSUE TITLE
Formulas like TODAY(), NOW() throws error #VALUE! in excel after using saveAs with evalueFormulae set to true

### ISSUE THREAD

**Issue by rao-moka** [ClosedXML/ClosedXML#1771]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**
Formulas like TODAY(), NOW() throws error after using saveAs with evalueFormulae set to true.

Complete this.

**What is the expected behavior or new feature?**

Complete this.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

**Code to reproduce problem:**
```c#
public void Main()
{
    
    

            
            workbook.SaveAs(sw,false,true);
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
Closing as not reproducible. It's likely it was resolved in the meantime.

If I try to just save the functions and use SaveAs with `evaluateFormulae:true` (as shown as the only line in the code snippet), file is saved and can be opened in Excel.

```csharp
using var wb = new XLWorkbook();
var ws = wb.AddWorksheet();
ws.Cell("A1").FormulaA1 = "NOW()";
ws.Cell("A2").FormulaA1 = "TODAY()";
wb.SaveAs(@"c:\Temp\Issues\1771\test.xlsx", false, evaluateFormulae: true);
```
