### ISSUE TITLE
InsertTable has error with nested objects

### ISSUE THREAD

**Issue by exitxhu** [ClosedXML/ClosedXML#1781]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**
0.95.4
**What is the current behavior?**

when the method "IXLTable InsertTable<T>(IEnumerable<T> data)" is called, if the T type has a nested object not set to null, it throws an error like "Unable to set cell value to Affiliate.Model.Entities.Website.LevelCommissionGroup".
forexapmle for this data I have error:
            var temp = new List<CategoryCommission> { new CategoryCommission
            {
                CategoryId =1,
                Commission =1,
                LevelCommissionGroup = new LevelCommissionGroup()
            } };

when I set that property to null the code executed without error:
            var temp = new List<CategoryCommission> { new CategoryCommission
            {
                CategoryId =1,
                Commission =1,
                LevelCommissionGroup = null
            } };

**What is the expected behavior or new feature?**

this method can just ignore nested objects.

## Reproducibility

**Code to reproduce problem:**
```c#
public class CategoryCommission 
{
    public LevelCommissionGroup LevelCommissionGroup { get; set; }
    public int CategoryId { get; set; }
    public float Commission { get; set; }
}
public class LevelCommissionGroup 
{
    public int LevelCommissionGroupId { get; set; }
    public string Name { get; set; }
}
public void Main()
{
      var temp = new List<CategoryCommission> { new CategoryCommission
            {
                CategoryId =1,
                Commission =1,
                LevelCommissionGroup = new LevelCommissionGroup()
            } };
           using var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("somename");

            worksheet.Cell(1, 1).InsertTable(temp); // error
            worksheet.Columns().AdjustToContents();
....
}
```

**Comment by jahav** [comment]
Write an adapter that will take input IEnumerable and transforms it into a `System.Data.DataTable` (anything IEnumerable<System.Data.IDataRecord>) or IEnumerable<System.Data.DataRow>. Pass the adapter (probably `DataTable`) to `InsertTable` method.

See Wiki for example: https://github.com/ClosedXML/ClosedXML/wiki/Inserting-Tables

I am not sure if ignoring nested object is desired correct behavior. InsertTable method would get an an object with data and decided to only partially transform them to table, ignoring some data while using other. Someone else might want to expand the tree structure into a table and have additional columns from nested objects, maybe 1 level, some might want 2 levels, some might infinite....  

Current behavior seems sensible - one level only, throw error on unexpected property value. If a specific behavior is needed, write an adapter for the required behavior.

/2¢

**Comment by exitxhu** [comment]
i see you'r point there.
i did a similar work around as you suggested, but with some extra dtos.

**Comment by exitxhu** [comment]
i see you'r point there.
i did a similar work around as you suggested, but with some extra dtos.

**Comment by Pankraty** [comment]
Adding to @jahav 's answer, another good option would be to define plain DTO class with the structure matching the desired table. In that class you'll be able to use the `XLColumn` attribute that allows specifying custom headers, like this:
```
class CategoryCommissionDto
{
    [XLColumn("Category ID")]
    public string CategoryId { get; set; }

    // More properties here
}
```
