### ISSUE TITLE
Get a worksheet by ID

### ISSUE THREAD

**Issue by timunie** [ClosedXML/ClosedXML#1786]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [X] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [X] No ► I had a look in the latest source and saw that the issue is still there

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

It's only possible to get a sheet by position or by name, but not by `SheetId`. this leads to porblems if a user renames a sheet or reorders the sheets. The `SheetId` on the other hand will not change. 

**What is the expected behavior or new feature?**

It's possible to get a sheet by its ID or at least its possible to read the ID. The property is already there: 
https://github.com/ClosedXML/ClosedXML/blob/ce7fb695a70d2e870078db4efe143a9e90ac7ad2/ClosedXML/Excel/XLWorksheet.cs#L150

**Is this a regression from the previous version?**

No

## Reproducibility

Consider this template file with two sheets: 

```
Template file: 
---------------
1: "Sheet A" (Position 1)
2: "Sheet B" (Position 2) 

User 1 renamed the sheets to German: 
------------------------------------------
1: "Blatt A" (Position 1)
2: "Blatt B" (Position 2) 

User 2 reordered the sheets: 
---------------
2: "Sheet B" (Position 1) 
1: "Sheet A" (Position 2)
```

**Code to reproduce problem:**
```c#
public void Main()
{
     using var wb = new XLWorkbook(_fileName);
     var ws1 = wb.Worksheet("Sheet A"); // This will fail for User 1
     var ws2 = wb.Worksheet(1);         // This will fail for User 2 
}
```
- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)

[GetSheetById_Template.xlsx](https://github.com/ClosedXML/ClosedXML/files/8554302/GetSheetById_Template.xlsx)
[GetSheetById_User_1.xlsx](https://github.com/ClosedXML/ClosedXML/files/8554303/GetSheetById_User_1.xlsx)
[GetSheetById_User_2.xlsx](https://github.com/ClosedXML/ClosedXML/files/8554304/GetSheetById_User_2.xlsx)

I hope the idea is getting clearer now. 

If you don't mind I can make a PR to handle this. 

Happy coding 
Tim

**Comment by jahav** [comment]
Closing for reasons outlined in https://github.com/ClosedXML/ClosedXML/pull/1789#issuecomment-1780127445.
