### ISSUE TITLE
Issue with Evaluating formula : Unable to calculate the cell value when using Table reference, MATCH and INDEX inside SUMIFS function

### ISSUE THREAD

**Issue by LokeshRajana** [ClosedXML/ClosedXML#1788]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Did you test against the latest CI build?**
Yes

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.4

**What is the current behavior?**
Unable to calculate the cell value when using MATCH and INDEX inside SUMIFS function
Complete this.

## Reproducibility
When cell having below formula, Unable to get the calculated value.

=IFERROR(SUMIFS(INDEX(Tbl_DS[#Data],,MATCH(M$1,Tbl_DS[#Headers],0)),INDEX(Tbl_DS[#Data],,MATCH($B12,Tbl_DS[#Headers],0)),$C12,INDEX(Tbl_DS[#Data],,MATCH($D$1,Tbl_DS[#Headers],0)),$E$1)/1000000,"")

**Code to reproduce problem:**
```c#
public void Main()
{
   using (var excelWorkbook = new XLWorkbook(item))
                        {
                            
                            var workSheetsAvailable = excelWorkbook.Worksheets;
                            for (var i = 1; i <= workSheetsAvailable.Count; i++)
                            {
                                var sheet = excelWorkbook.Worksheet(i);
                               
                                    var cellsUsedwithFormulas = sheet.CellsUsed(c => c.HasFormula);
                                    foreach (var cell in cellsUsedwithFormulas)
                                    {
                                        Object value = cell.Value; //// Please note we want to use re calculated value instead cached value.
                                        cell.Clear(XLClearOptions.Contents); 
                                        cell.Value = value; 
                                    }
                                }
                                
                            }
                            excelWorkbook.Save();
                           
                        }
}

Formula used in Excel:
=IFERROR(SUMIFS(INDEX(Tbl_DS[#Data],,MATCH(M$1,Tbl_DS[#Headers],0)),INDEX(Tbl_DS[#Data],,MATCH($B12,Tbl_DS[#Headers],0)),$C12,INDEX(Tbl_DS[#Data],,MATCH($D$1,Tbl_DS[#Headers],0)),$E$1)/1000000,"")

Please note Tbl_DS is table name from another sheet.

Kindly help on the same where closedXML unable to evaluate above formula and throwing null exception.

**Comment by igitur** [comment]
Neither external workbook references nor table style references (`Tbl_DS[#Data]`) are supported yet.

**Comment by LokeshRajana** [comment]
Hi @igitur 

Thanks for your reply.

As ClosedXML not supporting table style references, We have replaced table style references with sheet references still we we are getting null exception while trying to get cell value.

Please see below formula for your reference:

"IFERROR(SUMIFS(INDEX(Sheet10!$A$2:$AR$4298,,MATCH(AT$1,Sheet10!$A$1:$AR$1,0)),INDEX(Sheet10!$A$2:$AR$4298,,MATCH($B12,Sheet10!$A$1:$AR$1,0)),$C12,INDEX(Sheet10!$A$2:$AR$4298,,MATCH($D$1,Sheet10!$A$1:$AR$1,0)),$E$1)/1000000,"")"

**Comment by igitur** [comment]
And the external refs?

**Comment by LokeshRajana** [comment]
Hi @igitur 

We don't have any external workbook references, We are using different sheet reference under same workbook.

**Comment by igitur** [comment]
> Please note Tbl_DS is table name from another sheet.

Sorry, I misread this. I thought you meant this is from another file.

Ok, please UNnest the formulas and track down the exact formula that is giving the wrong result.

**Comment by LokeshRajana** [comment]
Hi @igitur 

Please find below evaluations for nested formulas, I have executed for all nested MATCH and INDEX separately and then for sumifs with single criteria and then multiple criteria. Also please find the screenshot for your reference.

<img width="790" alt="Image2" src="https://user-images.githubusercontent.com/104625834/166654754-3bc63918-51bc-492b-aec3-749b66b5ba36.PNG">


**Formula Evaluated for Nested Formula 1** 
 sheet.Evaluate("INDEX(Sales_Reporting_Data!$A$2:$AR$1723,,MATCH('US Retail-BU'!G1,Sales_Reporting_Data!$A$1:$AR$1,0))");

**Result** : "Bad expression." (Exception generated)

**Formula Evaluated for Nested Formula 2** 
                                    sheet.Evaluate("INDEX(Sales_Reporting_Data!$A$2:$AR$1723,,MATCH('US Retail-BU'!B12,Sales_Reporting_Data!$A$1:$AR$1,0))");

**Result** : "Bad expression." (Exception generated)

**Formula Evaluated for Nested Formula 1 (sumifs with single criteria range)** 
                                   sheet.Evaluate("SUMIFS(INDEX(Sales_Reporting_Data!$A$2:$AR$1723,,MATCH('US Retail-BU'!G1,Sales_Reporting_Data!$A$1:$AR$1,0)),INDEX(Sales_Reporting_Data!$A$2:$AR$1723,,MATCH('US Retail-BU'!B12,Sales_Reporting_Data!$A$1:$AR$1,0)),'US Retail-BU'!C12)");

**Result** :  System.NullReferenceException: 'Object reference not set to an instance of an object.'


**Formula Evaluated for Nested Formula 3** 
                                    sheet.Evaluate("INDEX(Sales_Reporting_Data!$A$2:$AR$1723,,MATCH('US Retail-BU'!D1,Sales_Reporting_Data!$A$1:$AR$1,0))");

**Result** : "Bad expression." (Exception generated)

**Formula Evaluated for Nested Formula 1 (sumifs with multiple criteria range)** 
                                    sheet.Evaluate("IFERROR(SUMIFS(INDEX(Sales_Reporting_Data!$A$2:$AR$1723,,MATCH('US Retail-BU'!G1,Sales_Reporting_Data!$A$1:$AR$1,0)),INDEX(Sales_Reporting_Data!$A$2:$AR$1723,,MATCH('US Retail-BU'!B12,Sales_Reporting_Data!$A$1:$AR$1,0)),'US Retail-BU'!C12,INDEX(Sales_Reporting_Data!$A$2:$AR$1723,,MATCH('US Retail-BU'!D1,Sales_Reporting_Data!$A$1:$AR$1,0)),'US Retail-BU'!E1)/1000000,'')");

**Result** :  System.NullReferenceException: 'Object reference not set to an instance of an object.'

**Comment by igitur** [comment]
Also remember to upload your sample workbook. The issue template was clear that this is required.

**Comment by LokeshRajana** [comment]
Hi @igitur 

Please find attached sample workbook to reproduce the issue.

You can find the calculated cell(A1) in Sheet1. 

**Formula under sheet 1:**

=IFERROR(SUMIFS(INDEX(Sales_Reporting_Data!$A$2:$U$1723,,MATCH('US Retail-BU'!G1,Sales_Reporting_Data!$A$1:$U$1,0)),INDEX(Sales_Reporting_Data!$A$2:$U$1723,,MATCH('US Retail-BU'!B12,Sales_Reporting_Data!$A$1:$U$1,0)),'US Retail-BU'!C12,INDEX(Sales_Reporting_Data!$A$2:$U$1723,,MATCH('US Retail-BU'!D1,Sales_Reporting_Data!$A$1:$U$1,0)),'US Retail-BU'!E1)/1000000,"")


[Sample Workbook Test.xlsx](https://github.com/ClosedXML/ClosedXML/files/8619573/Sample.Workbook.Test.xlsx)

**Comment by LokeshRajana** [comment]
Hi @igitur 

Can you please help me on this ASAP.

Thank you.

**Comment by jahav** [comment]
Due to various work on calc engine and reimplementation of SUMIFS (#2499), INDEX (#2518) and MATCH (#2522) functions, the supplied test workbook at https://github.com/ClosedXML/ClosedXML/issues/1788#issuecomment-1117169753 now calculates the correct value `718.4859269599983`. Closing the issue.

```csharp
using var wb = new XLWorkbook(@"c:\Temp\Issues\1788\SampleWorkbook.xlsx");
var ws = wb.Worksheets.Worksheet("Sheet1");

for (var i = 0; i < 5; ++i)
{
    var sw = Stopwatch.StartNew();
    // Because workbook loads value in cells, ensure it actually is
    // recalculated instead of just returning cached values.
    wb.RecalculateAllFormulas();
    sw.Stop();
    Console.WriteLine($"{i}: Got '{ws.Cell("A1").Value}' in {sw.ElapsedMilliseconds:N0} ms");
}

Console.WriteLine("Press any key to continue");
Console.ReadKey();
```

Time is not great, but most of it is due to calculation chain ordering that is done during the first execution.

> 0: Got '718.4859269599983' in 882 ms
> 1: Got '718.4859269599983' in 140 ms
> 2: Got '718.4859269599983' in 118 ms
> 3: Got '718.4859269599983' in 103 ms
> 4: Got '718.4859269599983' in 107 ms
> Press any key to continue

This issue also mentioned external workbooks in formulas, that is tracked in #121.
