### ISSUE TITLE
Generated Excel documents starts with SheetId:2 and r:Id 2

### ISSUE THREAD

**Issue by thommelutten** [ClosedXML/ClosedXML#1792]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

**What is the current behavior?**

SheetId and r:id starts at 2 instead of 1.

**What is the expected behavior or new feature?**

SheetId and r:id should start at 1.

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
   var workBook = new XLWorkbook();

    workBook.AddWorksheet("Sheet1");
    workBook.AddWorksheet("Sheet2");
    workBook.SaveAs("Testxml.xlsx");
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Testxml.xlsx](https://github.com/ClosedXML/ClosedXML/files/8668934/Testxml.xlsx)

**Comment by jahav** [comment]
Hi, the r:id is a relationship id between individual parts of xlsx (actually [Open Packaging Conventions or ECMA-376 part 2])https://en.wikipedia.org/wiki/Open_Packaging_Conventions)).

The identifier is an implementation detail and could be anything, like guid (see example value from spect below) or something like that. You shouldn't expect values to be of any specific format. ClosedXml is using a sequential generator for ids and the rId1 is used for relationship to app.xml part. While uniqueness necessary only locally per part, it's just more convenient to have them unique globally.

> ECMA-376 part 2 - 6.5.3.4
> Attributes Id
> This attribute specifies the identifier of a relationship. The value of the Id attribute shall be unique within the Relationships part. This attribute is required. 
> EXAMPLE 2   Id="A5FFC797514BC"

SheetId is pretty much same, an implementation detail (in ClosedXml case, number is same as relationship id) that is generated by an algorithm that can change at any time.

@[thommelutten](https://github.com/thommelutten) Why do you need to look at the individual values? In any case, don't rely on the ids to be generated sequentially or anything outside of spec requirements for id.

**Comment by thommelutten** [comment]
Thanks for your explanation - I found a workaround, so I'll close the issue after this message.

As for the reason. I have thirdparty that I need to upload the xlsx file to, and they made the design decision to impose a hard link between the SheetId and the name of the sheet. Furthermore, they also require the first sheet to be named Sheet1 and have SheetId 1. Not exactly the smartest decision, but it's out of my hands.

The solution I went with is to use OpenXML to generate the workbook, then passing it into ClosedXML after creation.

**Comment by igitur** [comment]
![image](https://user-images.githubusercontent.com/145854/173303364-1c62117d-226e-42c1-b6d7-147e9019d545.png)

Oh, no, it's not visible in VBA. But maybe it's an easy fix anyway.

**Comment by igitur** [comment]
It seems that since 2010 we have this statement, that sets the SheetId "equal" to the rId (for new sheets):

```xlSheet.SheetId = Int32.Parse(rId.Substring(3));```

We could change that, but it's going to require a change on all our test reference files. And we need to make very sure that we don't accidentally generate duplicate sheet IDs when the workbook already contains sheets when opened.

**Comment by igitur** [comment]
What do you expect the `SheetId` to be for the single resulting sheet in:

```c#
var workBook = new XLWorkbook();

var ws1 = workBook.AddWorksheet("Sheet1");
ws1.Delete();

ws1 = workBook.AddWorksheet("Sheet2");

workBook.SaveAs("Testxml.xlsx");
```

**Comment by thommelutten** [comment]
As a novice I'd assume the ```SheetId``` was 1, since ws1 is deleted before adding Sheet2? I'm guessing workBook does not contain a history of previously added sheets.

**Comment by jahav** [comment]
Won't fix, see https://github.com/ClosedXML/ClosedXML/pull/1814#issuecomment-1780099163.
