### ISSUE TITLE
Can you also add webp support for adding images?

### ISSUE THREAD

**Issue by lmahzenl** [ClosedXML/ClosedXML#1793]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**

Complete this.

**What is the expected behavior or new feature?**

Complete this.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
        public enum XLPictureFormat
    {
        Unknown,
        Bmp,
        Gif,
        Png,
        Tiff,
        Icon,
        Pcx,
        Jpeg,
        Emf,
        Wmf
    }
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
@lmahzenl Could you please clarify what you mean?
Do you want a functionality that will take webp image and convert it to some supported image and add converted to xlsx? That is out of scope of this project,

If you want to save webp into the xlsx as-is, I don't believe it's possible if you actually want to see the image when the file is opened in excel (though it might be possible just save it in the file as an embedded object, but that doesn't seem useful).

Although it's possible to add webp file to the file in Excel through Image - > Pictures menu, the webp file is actually converted to png file when saved. Could you please share an example of desired result file (probably created in excel)?

**Comment by igitur** [comment]
Thanks for the help @jahav

**Comment by igitur** [comment]
> Although it's possible to add webp file to the file in Excel through Image - > Pictures menu, the webp file is actually converted to png file when saved. Could you please share an example of desired result file (probably created in excel)?

Because of this, I think this request is out of scope for ClosedXML. External image libraries can be used to imitate Excel's webp -> jpg conversion.

**Comment by jahav** [comment]
No clarification has been provided and webp is rather out of range of expected image formats. Spec also recommends to use mostly png/jpeg for compatibility and even `ImagePartType` type from `DocumentFormat.OpenXml.Packaging`  doesn`t contain webp. Closing the issue.

> 15.2.14 Image Part
> A producer that wants interoperability should use one of the following standard formats:
> * image/png ISO/IEC 15948:2003, http://www.libpng.org/pub/png/spec/
> * image/jpeg, http://www.w3.org/Graphics/JPEG
