### ISSUE TITLE
[Solved] Row number must be between 1 and 1048576, Column number must be between 1 and 16384

### ISSUE THREAD

**Issue by rtek1000** [ClosedXML/ClosedXML#1795]
I'll leave these images here, in case anyone can't notice the number "1" in the warning (just like I hadn't noticed, using VS2008 I had to install VS2012 to have the same problem, then I managed to understand my failure, hey you who have reached this point, take more rest breaks)

"The computer world starts counting at 0, but humans who don't make programs count from 1" :sweat_smile:

![Start_Number_One](https://user-images.githubusercontent.com/8660811/168141446-7b2d9920-2a71-4f13-bbf2-88ea3193d5e1.png)
![Start_Number_One_Col](https://user-images.githubusercontent.com/8660811/168141450-fcf7bb0a-6485-4837-b042-d27d6bc52c6a.png)

**Comment by igitur** [comment]
This is documented in the Wiki.
