### ISSUE TITLE
ClosedXML not handling dates correctly

### ISSUE THREAD

**Issue by pueblonative** [ClosedXML/ClosedXML#181]
Using .NET

Data:

![image](https://cloud.githubusercontent.com/assets/21036649/22472485/00e752da-e793-11e6-82e5-ce3bde910374.png)

Code:

```c#
void MainFormShown(object sender, EventArgs e)
{
    var xlTestData = new XLWorkbook("testdata.xlsx");
    var xlWorksheet = xlTestData.Worksheet(1);
    
    for (int i=1;i<20;i++) {
        String strDate = xlWorksheet.Cell(i,1).GetString(); <--- prints out a number
        DateTime dtTime = xlWorksheet.Cell(i,1).GetDateTime(); <-- causes a System.Exception
        lbDates.Items.Add(strDate + dtTime.ToShortDateString());
        
    }
    
}
```

This is the output for the string line:

![closedxmltester](https://cloud.githubusercontent.com/assets/21036649/22472624/6b9c6d0e-e793-11e6-9305-30eecbb0b39e.PNG)

Note: I could not attach the Excel File even though it had an .xlsx format.  Github is saying that it doesn't support that file type.  This issue also just occured within the past few weeks.

**Comment by vbjay** [comment]
https://github.com/closedxml/closedxml/wiki/Cell-Values

**Comment by pueblonative** [comment]
Tried it, didn't work.  Directly assigning it to a DateTime gave the same exception, GetString() returned the above, and GetFormattedString() returned the following screenshot:

![closedxmltester2](https://cloud.githubusercontent.com/assets/21036649/22475425/29b0e27c-e79c-11e6-965a-989a07cbae91.PNG)
i did notice one thing, though:  when I copied and pasted directly from the listbox to here, it came up with the correct date.

I'm using .NET version 4.5 just to add that information.

**Comment by igitur** [comment]
Github should support uploading of `.xlsx` files. Try again to attach the file or email it to me. My email address is my Github username @ gmail.com.

**Comment by pueblonative** [comment]
[testdata.xlsx](https://github.com/ClosedXML/ClosedXML/files/746522/testdata.xlsx)
Note:  the file was created in LibreOffice, but I've had issues with Google Sheets doing the same thing as well (also, I don't have access to MSO).

**Comment by igitur** [comment]
LibreOffice saves the dates differently to MS Office. Refer to https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.cellvalues(v=office.15).aspx 

I submitted a PR to deduce the data type from the format string.

**Comment by pueblonative** [comment]
Okay.  However, it was working correctly up until a few weeks ago with no changes in the code.

**Comment by igitur** [comment]
The PR has been merged into the `develop` branch. I'd appreciate it if you could pull the `develop` branch and check that it solves your issue. Thanks.
