### ISSUE TITLE
I have an existing workbook which uses COLUMN function, but this is currently not supported in ClosedXML. Could it please be added?

### ISSUE THREAD

**Issue by tmslva** [ClosedXML/ClosedXML#1818]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x ] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

 0.95.4

**What is the current behavior?**

error ClosedXML.Excel.CalcEngine.Exceptions.NameNotRecognizedException: 'The identifier `COLUMN` was not recognised.'

**What is the expected behavior or new feature?**

Complete this.

**Is this a regression from the previous version?**

no

## Reproducibility
ws.Cell(1,1).FormulaA1 = $"=COLUMN(D6)";
"=COLUMN(D6)"
ws.Cell(1,1).Value
Exception thrown: 'ClosedXML.Excel.CalcEngine.Exceptions.NameNotRecognizedException' in ClosedXML.dll

**Code to reproduce problem:**
c#
public void Main()
{
ws.Cell(1,1).FormulaA1 = $"=COLUMN(D6)";
ws.Cell(1,1).Value
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
Hi, unfortunately current CalcEngine doesn't have a capability to provide function like COLUMN or ROW. They require a calculation engine context (the function must be aware of where it is executed) that isn't there (e.g. #1415). Probably watch issue #1812 for now.

This feature has been requested many times and it's definitely on the radar.
