### ISSUE TITLE
InsertData Skipping Columns

### ISSUE THREAD

**Issue by paulogleuwyo** [ClosedXML/ClosedXML#182]
I've created a list of saleReportEntity objects:

```c#
SaleReportEntity sre = new SaleReportEntity();
sre.office= sale.Office.Code;
sre.SaleDate = sale.SaleDate.ToShortDateString();
sre.IsPostponed = sale.IsPostponed;
sre.IsCancelled = "No";
sre.rcd = "Test";
saleReports.Add(sre);
```
Here is where I insert the objects:
```c#
worksheet.Cell(2, 1).InsertData(saleReports);
```

And here is the resulting output in the spreadsheet.
![output](https://cloud.githubusercontent.com/assets/1029177/22476913/48d44f2c-e7a1-11e6-87c7-2b27dc0e9cea.PNG)

InsertData is skipping a column and putting "Test" into F column. If I were to add headers, this could the spreadsheet off. 

Any ideas?

**Comment by igitur** [comment]
What public properties does `SaleReportEntity` expose? I suspect there is a public property that you're not populating and that is causing the blank column.

**Comment by igitur** [comment]
You can also explicitly use the `ClosedXML.Attributes.ColumnOrderAttribute` attribute to specify the order of your columns.
