### ISSUE TITLE
Can we write data and char in power point file by ClosedXML

### ISSUE THREAD

**Issue by karlosRivera** [ClosedXML/ClosedXML#184]
please tell me is it possible to write data and char in power point file by ClosedXML. if yes then i need some code sample which guide me how i can use ClosedXML  to write data and char in power point file. looking for help and suggestion. 

is this library developed by Microsoft ?
thanks

**Comment by igitur** [comment]
No, we're not affiliated to Microsoft and ClosedXML cannot write to PowerPoint files. Sorry.
