### ISSUE TITLE
AllowEditRanges with password and using user list (NTLM)

### ISSUE THREAD

**Issue by rockxl1** [ClosedXML/ClosedXML#1841]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**
0.96.0

**What is the current behavior?**

Right now, as i know, i just i'm abled to unprotect range witout password. 

**What is the expected behavior or new feature?**

Is possible to add password in unprotected ranges inside a protected sheet and put user access list like COM api does?

**Comment by jahav** [comment]
Hi, I am not quite sure what you are asking. I am not familiar with COM api.

You can lock whole sheet and mark an cell as unprotected. See the [SheetProtection.cs example](https://github.com/ClosedXML/ClosedXML/blob/develop/ClosedXML.Examples/Misc/SheetProtection.cs) in the repo. Is this sufficient for your needs?

As far as NTLM or any kind of user access list, I think that is out of scope of this project.

**Comment by jahav** [comment]
Provided an info for the requested feature, further clarification wasn't provided. Closing.
