### ISSUE TITLE
Micro-Optimizations of code details

### ISSUE THREAD

**Issue by LeaFrock** [ClosedXML/ClosedXML#1844]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.96.0

**What is the current behavior?**

It's a great library and thanks a lot for the contributors since my recent work is based on this. I'm interested in contributing to this repo (as a win-win feedback) and I want to start from relatively easy issues because I'm not an OpenXml/Excel experts.

When I browser the source codes, I find many details can be optimized. So I wonder if I can contribute my C# skills to this area. This issue is to ask for your guidance or warnings about my future PR(s).

**What is the expected behavior or new feature?**

Lower cost. Better perf.

**Is this a regression from the previous version?**

No.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Many codes can be optimized. [Here](https://github.com/ClosedXML/ClosedXML/blob/develop/ClosedXML/XLHelper.cs#L362) is an example which always does some unnecessary array allocations. Another example is [DictionaryExtensions.cs](https://github.com/ClosedXML/ClosedXML/blob/develop/ClosedXML/Extensions/DictionaryExtensions.cs). See the micro-benchmark sample below.

**Code to reproduce problem:**
```c#
    [MemoryDiagnoser]
    public class DictionaryTest
    {
        private readonly Dictionary<string, string> _dictionary = Enumerable.Range(1, 100000).Select(p => new KeyValuePair<string, string>(Guid.NewGuid().ToString(), Random.Shared.Next(99).ToString())).ToDictionary(p => p.Key, p => p.Value);

        [Benchmark(Baseline = true)]
        public int RemoveOnKeyOnly()
        {
            RemoveAll1(_dictionary, Filter);
            return _dictionary.Count;
        }

        [Benchmark]
        public int RemoveOnKeyValue()
        {
            RemoveAll2(_dictionary, Filter);
            return _dictionary.Count;
        }

        private static bool Filter(string a) => a.Length > 2; // Let it always return false(not remove key-value) in fact


        public static void RemoveAll1<TKey, TValue>(Dictionary<TKey, TValue> dic, Func<TValue, bool> predicate)
        {
            var keys = dic.Keys.Where(k => predicate(dic[k])).ToList();
            foreach (var key in keys)
            {
                dic.Remove(key);
            }
        }

        public static void RemoveAll2<TKey, TValue>(Dictionary<TKey, TValue> dic, Func<TValue, bool> predicate)
        {
            var keys = dic.Where(p => predicate(p.Value)).Select(p => p.Key).ToList();
            foreach (var key in keys)
            {
                dic.Remove(key);
            }
        }
    }
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by LeaFrock** [comment]
If the key type of `_dictionary` is `string`, here is the benchmark result.

![1658844203853](https://user-images.githubusercontent.com/20787265/181025336-f20903cd-2a92-4512-9b97-9efc97ebb80a.png)

If the key type is `int`, the difference is not very obvious.

![1658844450834](https://user-images.githubusercontent.com/20787265/181026254-9f573474-8c3b-445e-b582-9bffcfc6b5db.png)

`RemoveOnKeyValue` has a bit more memory use, but the gap is relatively stable and the perf is often better than the current one (depends on hashing of `Key`). Since extension methods always have global usage,  I think its optimization will benefit the whole project.

**Comment by jahav** [comment]
Did you notice that the extension method is used only in one place (removal of the sheet by position)?

It would be easier just delete it completely as a dead code and replace the only usage by `_worksheets.Remove(ws.Name)`

**Comment by jahav** [comment]
I apologize if I sounded rude. Any help is welcome. @igitur Can you please provide some guidance for potential contributor?

**Comment by LeaFrock** [comment]
> Did you notice that the extension method is used only in one place (removal of the sheet by position)?

My VS informs me of three references.

![1658851099667](https://user-images.githubusercontent.com/20787265/181053768-c54dcb55-8606-4f63-a361-9443e9e259f4.png)

> I apologize if I sounded rude

Oh never mind, I don't think so at all. Thanks for your  kindness 😄 . @jahav

**Comment by jahav** [comment]
Two of the three references are functions that by themselves don't have any references.

**Comment by LeaFrock** [comment]
> Two of the three references are functions that by themselves don't have any references.

Yep, I've found that. If removing it is good for perf, I'm glad to do so (and similar kind of things like this).  It's just an example.
