### ISSUE TITLE
Excel found unreachable content in xlsx. Do you want to recover

### ISSUE THREAD

**Issue by prakashbysani** [ClosedXML/ClosedXML#1849]
I am currently using closedxml v4.0.30319 to generate an excel sheet with couple of styles like applying background color to the cells, date formatting and hyperlinks creation.

When I am trying to export nearly 40k records which contains hyperlinks in two columns and it would be 80k.

After exporting to the excel, when I am trying to open "excel found unreadable content in xbox.xlsx. Do you want to recover the contents of this workbook? If you trust source of this workbook, click yes" error was coming and after clicking on excel sheet was repaired and its showing removed feature : all the hyperlinks removed from xml part.

After lot of trouble shooting if I am exporting excel with only one hyperlink column with 40k rows no error was coming. Is there any limitation how many hyperlinks should be present in the excel.

Could you please help me on this issue and let me know if there any such existing issue or limitation.

**Comment by jahav** [comment]
The reported issue is missing basic requirements:
* Version is not a version of ClosedXML
* Doesn't contain reproduction code and neither the corrupted Excel file
* Doesn't use template.

Closing. If you still haven't solved the problem, please reopen with the required information.
