### ISSUE TITLE
'ROW' Formula Is Not Supported

### ISSUE THREAD

**Issue by DiamondDiancie10** [ClosedXML/ClosedXML#1851]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

In my current xlsx file, I use the ROW() formula to get the number of the row for a particular cell; but, ClosedXML wasn't able to parse the formula. You can find its use here:
[https://support.google.com/docs/answer/3093316?hl=en](https://support.google.com/docs/answer/3093316?hl=en)

**Version of ClosedXML**

0.95.4

**What is the current behaviour?**

When I try to parse my xlsx file, I get the error **Identifier 'ROW' was not recognized** which stops me from continuing.

**What is the expected behaviour or new feature?**

=ROW() should return an integer matching the current row of the cell being parsed, while =ROW(A1), for example, should return 1 and so on.

## Reproducibility
**Code to reproduce the problem:**
```c#
public class Example //A basic class to try to parse the data.
{
        public string Name { get; set; }
        public int ID { get; set; }
}

public void Main() //Try to get the data as normal and the formula will flag.
{
            string filePath = System.IO.Path.GetFullPath("ROW_Usage_Example.xlsx");
            using (var reader = new ExcelParser(filePath))
            {
                Console.WriteLine("File found!");
                using (var csv = new CsvReader(reader))
                {
                    Console.WriteLine("Beginning parsing...");
                    var PokeList = csv.GetRecords<Example>().Where(x => !string.IsNullOrWhiteSpace(x.Name)).ToList();
                }
            }
}
```

- [x] I attached a sample spreadsheet. This is a basic version of the one I am using to show how I'm using ROW().
[ROW_Usage_Example.xlsx](https://github.com/ClosedXML/ClosedXML/files/9305531/ROW_Usage_Example.xlsx)

**Comment by Pankraty** [comment]
Duplicates #1818 (and a few others)

**Comment by jahav** [comment]
Technically #1818 is for COLUMN, not ROW function. In any case, ROW function was implemented (though it was mostly so I some demonstration for new features of CalcEngine in release notes).
