### ISSUE TITLE
Address of the cell in ClosedXML doesn't match cell address in Excel

### ISSUE THREAD

**Issue by PrzemyslawKlys** [ClosedXML/ClosedXML#1852]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.96.0

**What is the current behavior?**

I have an excel file that looks like this:

![image](https://user-images.githubusercontent.com/15063294/184476128-66aff202-24ba-4f17-8077-e6602269f4c4.png)

For some reason, it seems to say F1 doesn't have any value, and G1 in ClosedXML is actually a value from F1 (basically moves +1 left cell) everything. 

When I look at XML structure it's obvious:

![image](https://user-images.githubusercontent.com/15063294/184476210-ab880de1-8b91-424b-9fd1-ab9491a77388.png)

It seems Excel ignores a cell when it doesn't have cellValue attached to it. 

```csharp
        // Creates an Cell instance and adds its children.
        public Cell GenerateCell()
        {
            Cell cell1 = new Cell(){ CellReference = "F1", StyleIndex = (UInt32Value)17U };
            return cell1;
        }
```

It only reads those:

```csharp
        public Cell GenerateCell()
        {
            Cell cell1 = new Cell(){ CellReference = "G1", StyleIndex = (UInt32Value)14U, DataType = CellValues.SharedString };
            CellValue cellValue1 = new CellValue();
            cellValue1.Text = "501";

            cell1.Append(cellValue1);
            return cell1;
        }
```

**What is the expected behavior or new feature?**

Skip all cells that don't have CellValue attached, just like Excel does.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[TestDocument.xlsx](https://github.com/ClosedXML/ClosedXML/files/9331127/TestDocument.xlsx)

**Comment by jahav** [comment]
I am confused what exactly is the problem.

> For some reason, it seems to say F1 doesn't have any value, and G1 in ClosedXML is actually a value from F1 (basically moves +1 left cell) everything.

E1,E2,F1, F2,G1,G2 have same value in excel, your screenshot and ClosedXml (0.96). When you say "it", do you mean excel or ClosedXml? Dtto for who moves it.

```csharp
void Main()
{
	var excel = new XLWorkbook(@"C:\temp\TestDocument.xlsx");
	var ws = excel.Worksheets.Single();
	Print(ws, "E1") ;
	Print(ws, "E2");
	Print(ws, "F1");
	Print(ws, "F2");
	Print(ws, "G1");
	Print(ws, "G2");
}

private static void Print(IXLWorksheet ws, string cell)
{
	var cellValue = ws.Cell(cell).Value;
	Console.WriteLine($"Cell {cell}: \"{cellValue }\" isEmpty:{(cellValue is string cellString && string.IsNullOrEmpty(cellString))}");
}
```

gave me

> Cell E1: "Option to script" isEmpty:False
> Cell E2: "Yes" isEmpty:False
> Cell F1: "setting" isEmpty:False
> Cell F2: "" isEmpty:True
> Cell G1: "status" isEmpty:False
> Cell G2: "published" isEmpty:False

Each cell in the worksheet has an explicitly stated reference, so the they really shouldn't be moving around at all, e.g. the cells for the screenshot you are referencing is
<details>
  <summary>Click me</summary>
```
		&lt;row r="2"
		     spans="1:8"
		     s="5"
		     customFormat="1"
		     x14ac:dyDescent="0.35"&gt;
			&lt;c r="A2"
			   s="6"
			   t="s"&gt;
				&lt;v&gt;1&lt;/v&gt;
			&lt;/c&gt;
			&lt;c r="B2"
			   s="6"
			   t="s"&gt;
				&lt;v&gt;6&lt;/v&gt;
			&lt;/c&gt;
			&lt;c r="C2"
			   s="6"
			   t="s"&gt;
				&lt;v&gt;8&lt;/v&gt;
			&lt;/c&gt;
			&lt;c r="D2"
			   s="7"
			   t="s"&gt;
				&lt;v&gt;15&lt;/v&gt;
			&lt;/c&gt;
			&lt;c r="E2"
			   s="7"
			   t="s"&gt;
				&lt;v&gt;14&lt;/v&gt;
			&lt;/c&gt;
			&lt;c r="F2"
			   s="6"/&gt;
			&lt;c r="G2"
			   s="6"
			   t="s"&gt;
				&lt;v&gt;12&lt;/v&gt;
			&lt;/c&gt;
			&lt;c r="H2"
			   s="6"
			   t="s"&gt;
				&lt;v&gt;13&lt;/v&gt;
			&lt;/c&gt;
		&lt;/row&gt;
```
</details>

**Comment by PrzemyslawKlys** [comment]
During my testing the columns were shifted by 1 when there was empty cell. I am not sure how that happend. Unfortunetly I can't reproduce this anymore. Sorry for wasting your time. The problem must have been between monitor and a chair.
