### ISSUE TITLE
closedxml and Excel's Camera Tool

### ISSUE THREAD

**Issue by blackbullfx** [ClosedXML/ClosedXML#1854]
Is it possible to use the Excel camera tool with ClosedXML?

**Comment by jahav** [comment]
No. I tried to create it to see what it does and it uses an extension in the spreadsheetDrawing (basically not a part of official spec = no documentation). 

ClosedXml doesn't even support chart creation yet, so I am closing this (I don't see a implementation is a forseeable future).

**Comment by blackbullfx** [comment]
Thanks @jahav , I will have it inserted manually.
