### ISSUE TITLE
Open and Edit a SharePoint Excel File 

### ISSUE THREAD

**Issue by BSchaap** [ClosedXML/ClosedXML#1856]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug?
- [x] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.96.0

**What is the current behavior?**

File not found exception on an excel file located in SharePoint

**What is the expected behavior or new feature?**

In the Excel Interop package using the Workbooks.Open() you are able to provide a path to an excel file (.xlsx) located in a SharePoint document library. Doing so allows you to update the document accordingly and have your changes seen while the file is opened in SharePoint. I have created a solution that can do this with interop, but it is not feasible as we are unable to install office on the server. I have just come to learn this is a big no no. 

The expected new behavior/feature would be similar functionality, if at all possible.

**Is this a regression from the previous version?**

Yes, this occurs on 0.95.4 and 0.94.2

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    //Instantiate a new workbook
    IXLWorkbook workbook = new
    XLWorkbook(@"https://<SharepointURL>/[Sites]/[Team]/Shared%20Documents/[ExcelFileName].xlsx");
    IXLWorksheet worksheet = workbook.Worksheet("Sheet1");
    //More code follows manipulating the excel file.. not relevant to error/bug/feature request
    workbook.Save();

    //Sample with Interop (V15 from NuGet)
    pathToExcelFile = @"https://<SharepointURL>/[Sites]/[Team]/Shared%20Documents/[ExcelFileName].xlsx");
    Excel.Application excelApp = new Excel.Application();
    excelApp.Visible = false;
    Excel.Workbook workbook = excelApp.Workbooks.Open(pathToExcelFile);
    //More code follows manipulating the excel file.. not relevant to error/bug/feature request
    workbook.Save();

}
```
**File does not matter, current implementation attempt looks at a blank/fresh excel file**
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
I am not familiar with sharepoint nor excel interop. Do you have a link to a documentation that would explain how that functionality works?

Your report indicates that it is a regression from 0.95.4. I don't see any commit that would just scream this is it. Please use git bisect to isolate a commit that broke it.

**Comment by BSchaap** [comment]
Apologies I may have misunderstood the regression section, I understood it as previous builds that it did not work in, I tried the earlier versions and was unable to open a SharePoint link.

For Interop: https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.interop.excel?view=excel-pia used mostly for AddIn Developments

For SharePoint the starting place I used was: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code

**Comment by jahav** [comment]
Let me clarify my request for documentation. Scope of this project is to reading/manipulating/writing files in Office Open XML.

I am trying to discern whether is doing the notification uses some kind of intrinsic part Office Open XML format or if it is some extra piece of of code in the interop that detects that file is from sharepoint and sends some kind of notification to the sharepoint.

By your description, it seems that latter is more likely. That is the kind of documentation I am asking for - is the sharepoints integration dependent on the file itself (and if so, how) or not. That is whether it is in the scope of the project. 

Though to be honest, whatever the answer, there are many high priority issues that this will likely end up at the bottom of the queue, unless it is really simple.

**Comment by BSchaap** [comment]
I will take a look around and see what I can find and Appreciate the responses! 

No worries about the priority, definitely a nice to have and not a high priority!

Thanks again!

**Comment by jahav** [comment]
I am trying to clean up my issue backlog, so I am closing this due out of scope and inactivity.
