### ISSUE TITLE
FileLoadException when calling GetExportedTypes()

### ISSUE THREAD

**Issue by ZjzMisaka** [ClosedXML/ClosedXML#1865]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

1.96.0
btw, version 0.95.4 returns the correct result. 

**What is the current behavior?**

FileLoadException when calling GetExportedTypes()

**What is the expected behavior or new feature?**

return a Type

**Is this a regression from the previous version?**

no

## Reproducibility

Call GetExportedTypes to get a Type

**Code to reproduce problem:**
```c#
Assembly closedXMLAssembly = Assembly.LoadFrom("ClosedXML.dll");
foreach (Type type in closedXMLAssembly.GetExportedTypes())
{
    // do something
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
I don't think we can guarantee anything returned through Reflection at this stage. But in any case, please post the full exception details.

**Comment by ZjzMisaka** [comment]
> I don't think we can guarantee anything returned through Reflection at this stage. But in any case, please post the full exception details.

I solved the problem, thats my bad. 
I only updated the ClosedXml nuget package from v0.95.4 to 0.96.0 but forgot to update OpenXml nuget package from v2.18.0.
