### ISSUE TITLE
Requested value 'baseline' was not found

### ISSUE THREAD

**Issue by moshodj** [ClosedXML/ClosedXML#1867]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

When trying to open an excel file with the OpenXml library, an error occurs "Requested value 'baseline' was not found".

**What is the expected behavior or new feature?**

Opening excel file without exception.

**Is this a regression from the previous version?**

It's not. The problem was detected on version v0.94.2, but it was not fixed on the last version either.

## Reproducibility

**Code to reproduce problem:**
```c#
using OfficeOpenXml;

ExcelPackage package = new ExcelPackage(memoryStream);

ExcelWorksheet worksheet = package.Workbook.Worksheets[1];
```
The break occurs on this line of code: "ExcelWorksheet worksheet = package.Workbook.Worksheets[1];" with a message "Requested value 'baseline' was not found".

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
According to the example code, you are using EPPlus, not ClosedXML package. Please open an issue on their bugracker.
