### ISSUE TITLE
Explore saving without intermediate representation

### ISSUE THREAD

**Issue by jahav** [ClosedXML/ClosedXML#1874]
We have many reports about memory performance problems. One of the key problems I have seen is that 
* user generates workbook - that creates a workbook in our internal structures.
* user calls `XLWorkbook.Save`. This method takes our internal structure and converts them in-memory to documentFormat.OpenXml structure. That takes 1.5x-2x memory compared to ClosedXml structure (at least based on few simplified demos)

We can (and will) improve sice/perfromance our internal structures, but as long as the second part remains, it won't help much. The library is a key dependency and has been cornerstone of the ClosedXml since the start and is ovioudly out of our control.

This issue is an **exploration**, if we could just stream **sheet part** (and **only** sheet part, rest would still be saved by DocumentFormat.OpenXml) data to xlsx without converting it to documentFormat.OpenXml as an intermediate representation. E.g. linq-to-xml just generates stream without significant memory overhead.

If I can save a valid workbook with rows and cells (no styling no anything, just some values), it might be worth exploring more in depth.

Obviously, this would have several drawbacks
* no validation provided by DocumentFormat.OpenXml
* we would have to completely rework sheet part saving (not sure how many tags or how large it is) - significant possible regression
* a massive amount of work that is now done by DocumentFormat.OpenXml

Resources:
* An example of saving through streaming - https://web.archive.org/web/20160216062257/http://blogs.msdn.com/b/brian_jones/archive/2010/06/22/writing-large-excel-files-with-the-open-xml-sdk.aspx
* FeedData API endpoint (seems too low level in comparisont o streaming, but it exists) -  https://stackoverflow.com/questions/11636258/openxml-replace-specific-customxml-part-of-word-document.
* DocumentFormat.OpenXml issue for an example of how to replace a xml subtree in a part - https://github.com/OfficeDev/Open-XML-SDK/issues/566

**Comment by jahav** [comment]
I have tried it and saving through partial streaming (stream rows data, keep rest in DOM) seems doable (my super dirty exploration code at least saved something). Basic idea is two phase saving:
* first determine all parts that must be added/removed and assign them RelIds (RelId is the relationship between parts, so before we write parts themselves, RelIds must be assigned). The RelId is currently often assigned in the middle of part writing.
* Then write individual parts. There should be a separate writer for each part, not a fan of 5k+ super file. Separate out of XLWorkbook.

There will probably be different ways to save individual parts, but for worksheet part:
* Load DOM worksheet object from the workbook/create new one (if possible, skip `sheetData`, but that is optional).
* Use `GenerateWorkbookPart` logic to update DOM to required state, but **don't add  `sheetData` element to DOM*, other elements will be loaded in the DOM (e.g. sheet properties, tables, and so on) .
* Create a `OpenXmlReader` from the worksheet DOM and `OpenXmlWriter` that writes into a stream (basically [this](https://web.archive.org/web/20160216062257/http://blogs.msdn.com/b/brian_jones/archive/2010/06/22/writing-large-excel-files-with-the-open-xml-sdk.aspx)), but once we see a sheetData element in the reader stream (that is empty, because we skipped it in previous step to save memory), use XLWorkbook to directly stream from CellCollection to rows of sheetData.

This allows us to migrate pieces of DOM saving into SAX stream saving, basically don't read into the DOM and when saving the DOM, detect a part that should be streamed and stream it. No memory benchmark so far.

There are of course some caveats, but no deal-breaker so far.

**Comment by jahav** [comment]
Saving file through streaming seems to work really well. I used a code from #1753 to generate 30k rows (gist [here](https://gist.github.com/jahav/b467e2ed953731005e6c4d1d1d381472)) and saving through DOM (AS-IS) took 1:40 minutes and 1.27 GiB. Using streaming took 1:25 minutes and 570MiB. 320MiB was already allocated before file started to be saved.

> This was a triumph.
> I'm making a note here:
> huge success.
> It's hard to overstate
> My satisfaction.

The following two pictures are from dotMemory. The place where is snapshot # 1 is the momemt when worksheet was filled with data. At that time, XLWorksheet had took about 320 MiB. Not great or 30k of rows, but it is what it is. The memory usage constantly grew, as the DOM got bigger and bigger as more rows were added to Open XML SDK DOM for a worksheet part. Once the whole DOM was created, it was saved at once. That is indicated by the grew of the purple (that is Large Object Heap, basically memory stream for seekable uncompressed zip file stream) at the end.
![1874-dtoMemory-save-30k-DOM](https://user-images.githubusercontent.com/7634052/208199681-8cee4e6f-ead9-40d7-b451-bcf6b88bc913.png)

The streaming on the other had used a very little more memory for saving (of course it used some), pretty much all additional memory was allocated to the zip stream memory file (the purple thing).
![1874-dtoMemory-save-30k-streaming](https://user-images.githubusercontent.com/7634052/208199672-1ee28508-bf7c-4d1e-8c0a-180d3d597fe1.png)

This is pretty neat, but the PR at this moment doesn;t stream shared string table, so if each row had a different string, it would eat memory, because shared string table is still saved through DOM. The demo file uses same strings = no additional memory required. I plan to add a streaming for shared string table too.

It seems that there is no way to stream data into a zip archive without a memory stream. The default zip archive supports seeking and to seek it must keep uncompressed memory stream of compressed file stream. There are some libraries that support non-seekable zip streams, but hooking them to Open XML SDK doesn't seems like a good idea at the moment, though likely feasible. There is more low-hanging fruit. I tried to change [CompressionOption](https://learn.microsoft.com/en-us/dotnet/api/system.io.packaging.compressionoption) to `CompressionOption.NotCompressed`, but it didn't help.

**Comment by jahav** [comment]
The ticket has been resolved in PR #1937.  The philosophy of the PR has been minimal necessary change, so pretty much all code has just been moved around and then saved through streaming in a very small change.

After delving through save code, I am convinced that 2 phase save described in the https://github.com/ClosedXML/ClosedXML/issues/1874#issuecomment-1291099386 is the correct way forward. Saving code needs to be further split to be more manageable. Separate writer for each part is a correct way forward. This is only a first step, it will need a lot more TLC in teh future.

I did another test where each cell had a different text, otherwise same as original gist test case. Decrease from **2.08** 🡆 **0.8** GiB. That is about the best I can do at this time (the purple part is once again bytes of uncompressed package zip stream).

Save cells and strings through DOM: **2.08 GiB**
![1874-dtoMemory-save-30k-text-DOM](https://user-images.githubusercontent.com/7634052/208317997-24765ff2-17c2-4272-9b66-5d98fe08c089.png)

Save cells through streaming and strings through DOM: **1.47 GiB**
![1874-dtoMemory-save-30k-text-DOM-sst,cell-streaming](https://user-images.githubusercontent.com/7634052/208318007-0483f5fb-47c5-462f-91b6-f73f306bdec8.png)

Save cell and strings through streaming: **0.8 GiB**
![1874-dtoMemory-save-30k-text-streaming](https://user-images.githubusercontent.com/7634052/208318008-2df5f259-0ffd-48fe-8f44-272d173e415f.png)

**Comment by Pitterling** [comment]
Working well, in my case memory footprint dropped from 1.5G down to 0.99G .. keep up the great work

**Comment by jahav** [comment]
@Pitterling Thanks.
There has been a great news from OpenXML SDK lately (that is the problem with the purple part). They finally added an abstraction for package in https://github.com/OfficeDev/Open-XML-SDK/pull/1295. When I looked at that issue, it has been kicked around for something like 5 years in several repos (BCL basically refused due to breaking changes). Plus there might even be something that takes care of memory issues for me https://github.com/OfficeDev/Open-XML-SDK/issues/807#issuecomment-1377733580 , though I will have to investigate more when I have time.
