### ISSUE TITLE
Blazor Wasm Clientside , does not read fonts

### ISSUE THREAD

**Issue by Tasmanakos** [ClosedXML/ClosedXML#1879]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [x] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.97

**What is the current behavior?**

When using the Library on clientside blazor . The Default Graphics Engine Cannot Find any fonts . 
The Constructor of the Engine uses LoadFont Method , which in turn gets the SystemFontCollection.Collection from SixLabors
But six labors checks for fonts only in Windows/Linux/MAC platforms and returns an empty array when in browser

**What is the expected behavior or new feature?**

Maybe , be able to load one or more fonts manually to the Default Graphics Engine ? 
Is there any other way except implementing a new IXLGrapgicsEngine? 

**Is this a regression from the previous version?**

This problem was not present in 0.96.1 Preview 
There where two engines and the default one was not using SixLabors Library

## Reproducibility
Running the Library in a Blazor application in the Client .

throws exception 
Unhandled exception rendering component: Unable to find font Calibri or fallback font Microsoft Sans Serif. Install missing fonts or specify a different fallback font through 'LoadOptions.DefaultGraphicEngine = new DefaultGraphicEngine("Fallback font name")'.
System.ArgumentException: Unable to find font Calibri or fallback font Microsoft Sans Serif. Install missing fonts or specify a different fallback font through 'LoadOptions.DefaultGraphicEngine = new DefaultGraphicEngine("Fallback font name")'.

Method that produces above exception (When using AdjustToContents())
```c#
public static byte[] GetReport()
        {
            using var wb = new XLWorkbook();
            var ws = wb.Worksheets.Add("testSheet");
            ws.Cell("B3").Value = "test";
            ws.Cell("B8").Value = "test";
            ws.Columns().AdjustToContents();

            using MemoryStream stream = new();
            wb.SaveAs(stream);
            stream.Position = 0;
            return stream.ToArray();
        }
```

**Comment by jahav** [comment]
Hi @Tasmanakos, would the code from PR be sufficient? 

The CI build of the branch is at appveyor: https://ci.appveyor.com/api/buildjobs/k5kwuxdhmrtm3qlk/artifacts/ClosedXML%2Fbin%2FRelease%2FClosedXML.0.97.0.nupkg

Basically get a stream for a font from some source. `SixLabors.Fonts` needs a seekable stream, so `HttpBaseStream` is out, memory stream would work.

```csharp
//  Specify fallback font
using stream fallbackFontStream = Assembly.GetManifestResourceStream("SomeFont.ttf");
LoadOptions.DefaultGraphicEngine = new DefaultGraphicEngine(fallbackFontStream)
```

```csharp
using stream fallbackFontStream = Assembly.GetManifestResourceStream("SomeFont.ttf");
// provide extra fonts from other sources, so we don't always use fallback
using stream calibriStream = /* some way to get a seekable stream with Calibri */;
LoadOptions.DefaultGraphicEngine = new DefaultGraphicEngine(fallbackFontStream, calibriStream)
```

> Is there any other way except implementing a new IXLGrapgicsEngine?
You can try to write a wrapper over a default graphic engine. GetPictureInfo would call the original, you would have to implement the font methods though.

**Comment by Tasmanakos** [comment]
Hi @jahav 
That was swift , Thanks for taking the time ,

> would the code from PR be sufficient?

Yes i think this is Fine! 
Will have to embed font and then retrieve the stream something like below as per your above example.
Maybe also a Sixlabors.Font.FontCollection as an argument would be fine ?

```c#
var assembly = Assembly.GetExecutingAssembly();
var path = "FontPath/font.ttf";
using (Stream stream = assembly.GetManifestResourceStream(path));
LoadOptions.DefaultGraphicEngine = new DefaultGraphicEngine(stream);

// or also 
FontCollection fonts = new();
//...
//Create any fonts needed by the app as per [SixLabors Docs](https://docs.sixlabors.com/articles/fonts/gettingstarted.html)
//...
LoadOptions.DefaultsGraphicEngine = new DefaultGraphicEngine(fonts);
```

I Downloaded the CI build but the stream arg , ctor is not there (only the previous ctor from 0.97 is there) 
I think i got something wrong ?

Forgive my lack of knowledge i am fairly new in coding .

**Comment by jahav** [comment]
The problem with missing ctor was very likely stale nuget cache and the old version. 

I have updated version and wrote a guide [Dev builds](https://github.com/ClosedXML/ClosedXML/wiki/Development-Builds) on how to test dev builds. It will probably come handy in the future.
The PR was rebased: https://ci.appveyor.com/project/ClosedXML/closedxml/builds/45150879/artifacts

As for the FontCollection - I don't want to expose API of SixLaborsFonts in ClosedXMl API. The fact that ClosedXml is using that library should be hidden (basically an implementation detail).  List of streams is a neutral interface.

It's a better from design perspective, it's pre release package, and SixLabors are trying to find a reasonable monetization plan (=frequent license changes).

**Comment by Tasmanakos** [comment]
> The problem with missing ctor was very likely stale nuget cache and the old version.
I have updated version and wrote a guide [Dev builds](https://github.com/ClosedXML/ClosedXML/wiki/Development-Builds) on how to test dev builds. It will probably come handy in the future.

I was not aware of the cache thing , thanks for the guide!
I have tried the new build and it works fine in blazor clientside,
just great , can delegate all the xls generation work to the client now !

> As for the FontCollection - I don't want to expose API of SixLaborsFonts in ClosedXMl API. The fact that ClosedXml is using that library should be hidden (basically an implementation detail). List of streams is a neutral interface.

I Understand i think that was the goal from the begining , when you had the two engines apart . (One Default and seperate package for SixLabors)

Will you be able to release this small fix to nuget.org soon ? 
Asking cause otherwise will have to somehow use a private feed for 0.97.1 preview to use the package in the application.

In every case thank you for the swift fix , replies and overall help 

For Blazor Clientside: 
```c#
var assembly = Assembly.GetExecutingAssembly();
//Gets the names of the Embeded Resources (handy to detect full path of the embeded files)
//var resources = assembly.GetManifestResourceNames();
//foreach (var resource in resources) Console.WriteLine(resource);

//Create stream to inject to Graphics engine
using Stream fontStream = assembly.GetManifestResourceStream($"yourResourcePath") 
?? throw new Exception("Resource not Found");
//Load the font(s)
LoadOptions.DefaultGraphicEngine = new DefaultGraphicEngine(fontStream);
```
```c#
public static byte[] GetTestReportBytes()
{
            using var wb = new XLWorkbook();
            var ws = wb.Worksheets.Add($"testSheet");
            ws.Cell("B3").Value = "test";
            ws.Cell("B4").Value = "longtextTestlongtextTest";
//Adjust to Contents
            ws.ColumnsUsed().AdjustToContents();

            using MemoryStream stream = new();
            wb.SaveAs(stream);
            stream.Position = 0;
            return stream.ToArray();
        }
```
// Javascript Function to get the file to download
```js
// Save Generated File from Base64string
function saveAsFile(filename, bytesBase64) {
    var link = document.createElement('a');
    link.download = filename ?? '';
    link.href = "data:application/octet-stream;base64," + bytesBase64;
    document.body.appendChild(link); //Needed for Firefox
    link.click();
    document.body.removeChild(link);
}
```
//Call javascript function from .net 

```c#
[inject] public IJSRuntime js { get; set; }

        public async Task SaveGeneratedFileAs(string filename , byte[] data)
        {
            await js.InvokeAsync<object>(
                "saveAsFile",
                filename,
                Convert.ToBase64String(data));
        }
```
```c#
//Call this from a component button to generate the file and download it
private async Task GetXLSTestReport()
        {
            byte[] reportBytes = GetTestReportBytes();
            await SaveGeneratedFileAs("test.xlsx", reportBytes);
        }

```

**Comment by jahav** [comment]
@Tasmanakos My rough plan is to release next version in December before Christmas.

**Comment by Tasmanakos** [comment]
@jahav  Great thanks for sharing the timeframe and for implementing this feature.

**Comment by vip-ehowlett** [comment]
I've come across this issue and while I was trying to implement the solution, I can't figure out how you guys are managing to embed the font files in the assembly. Would you mind sharing?

**Comment by Tasmanakos** [comment]
Hello Ehowlett

Have you tried the above code with preview version 0.97.1 ?

You need to use the below link version via a local nuget 
[https://ci.appveyor.com/project/ClosedXML/closedxml/builds/45150879/artifacts](url)

Because the current release does not have a way for you to use your font files in blazor clientside.

If you use 0.97.1 , you can use a folder in your project with the font files you want and pass the font stream to the Default Graphics engine

```c#
//Gets the Executing assembly (The compiled project actual file)
var assembly = Assembly.GetExecutingAssembly();

//Gets the names of the Embeded Resources (handy to detect full path of the embeded files)
var resources = assembly.GetManifestResourceNames();
foreach (var resource in resources) Console.WriteLine(resource);

//Creates a stream of the font file requested , so it can be injected to the Graphics engine!
//Replace "ExcelSupportLib.Fonts.calibri.ttf" with your path
using Stream fontStream = assembly.GetManifestResourceStream($"ExcelSupportLib.Fonts.calibri.ttf") ?? throw new Exception("Resource not Found");

//Loads the font and generates a new default Graphics Engine
LoadOptions.DefaultGraphicEngine = new DefaultGraphicEngine(fontStream);
```


Edit : Well just saw there is a new Release just now , so i beleive you can do it directly with the current release

**Comment by vip-ehowlett** [comment]
The problem I had was embedding the font files in the assembly. Instead, when the component is initialized, I just make an http request for it.

```C#
protected override async Task OnInitializedAsync() {
        var client = HttpClientFactory.CreateClient("{name}");
        var response = await client.GetAsync("/fonts/roboto.ttf");
        var fs = await response.Content.ReadAsStreamAsync();
        ClosedXML.Excel.LoadOptions.DefaultGraphicEngine = ClosedXML.Graphics.DefaultGraphicEngine.CreateWithFontsAndSystemFonts(fs);
    }

**Comment by jahav** [comment]
@vip-ehowlett Unfortunately, the stream must be seekable. Wrap it to MemoryStream. https://closedxml.readthedocs.io/en/latest/features/graphic-engine.html#how-to-use-in-blazor

**Comment by vip-ehowlett** [comment]
You're not understanding. What I did worked. It _is_ being read into a stream. 

This didn't work for me because I don't know how you're _embedding_ the font file in the assembly.
```C#
//Gets the Executing assembly (The compiled project actual file)
var assembly = Assembly.GetExecutingAssembly();

//Gets the names of the Embeded Resources (handy to detect full path of the embeded files)
var resources = assembly.GetManifestResourceNames();
foreach (var resource in resources) Console.WriteLine(resource);

**Comment by jahav** [comment]
Ah, sorry for misunderstanding.

I wrote an idea to Fonts anyway https://github.com/SixLabors/Fonts/discussions/319

**Comment by Tasmanakos** [comment]
> You're not understanding. What I did worked. It _is_ being read into a stream.
> 
> This didn't work for me because I don't know how you're _embedding_ the font file in the assembly.
> 
> ```cs
> //Gets the Executing assembly (The compiled project actual file)
> var assembly = Assembly.GetExecutingAssembly();
> 
> //Gets the names of the Embeded Resources (handy to detect full path of the embeded files)
> var resources = assembly.GetManifestResourceNames();
> foreach (var resource in resources) Console.WriteLine(resource);
> ```

Great ! 
If you want to embed , just use a File normally inside your project folder and mark the fonts as "Embedded resource"
If you are not using VisualStudio you can go to the Project code and add the below 
```C#
//Replcae "Fonts\calibri.ttf" with your Path to the fonts
<ItemGroup>
    <EmbeddedResource Include="Fonts\calibri.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>
```

**Comment by vip-ehowlett** [comment]
Thank you, I appreciate the help! I didn't know you could do that. I'm new to the .net platform so that's a neat trick to have.
