### ISSUE TITLE
Fail to SaveAs spreadsheet with indexed color 80

### ISSUE THREAD

**Issue by skyflyer** [ClosedXML/ClosedXML#1884]
When an Excel file (generated by Excel on Windows) contains indexed color `80`, the library breaks when calling `SaveAs` on the loaded workbook.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [X] Yes (tested against develop branch of github)
- [ ] No

**Version of ClosedXML**

Latest commit from develop, specifically `779a4c03`.

**What is the current behavior?**

Currently, the library breaks when trying to obtain indexed color `80`. Here is the stacktrace:

```
   System.Collections.Generic.KeyNotFoundException : The given key '80' was not present in the dictionary.
  Stack Trace:
     at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ClosedXML.Excel.XLColor.get_Color() in /.../ClosedXML/ClosedXML/Excel/Style/Colors/XLColor_Public.cs:line 57
   at ClosedXML.Excel.XLWorkbook.GenerateCommentShape(XLCell c) in /.../ClosedXML/ClosedXML/Excel/XLWorkbook_Save.cs:line 3271
```

**What is the expected behavior or new feature?**

I'm not sure what the correct approach would be, since indexed color `80` is not defined (at least I could not find it). Would defaulting to Color.Transparent make sense in this case or... perhaps just preserving what came "in" and not trying to return something else?

There is already special-case handling for `81` from 5 years ago:

```cs
        /// <summary>
        /// Usually indexed colors are limited to max 63
        /// Index 81 is some special case.
        /// Some people claim it's the index for tooltip color.
        /// We'll return normal black when index 81 is found.
        /// </summary>
        private const Int32 TOOLTIPCOLORINDEX = 81;
```

**Is this a regression from the previous version?**

Not that I am aware of.

## Reproducibility

**Code to reproduce problem:**
```c#
using ClosedXML.Excel;

if (args.Length < 1) {
    Console.WriteLine($"provide source excel file");
    return;
}

using var workbook = new XLWorkbook(args[0]);

workbook.SaveAs("result.xlsx");
```

- [X] I attached a sample spreadsheet you can use with this program: 
[sample-4.xlsx](https://github.com/ClosedXML/ClosedXML/files/9852069/sample-4.xlsx)

**Comment by jahav** [comment]
Comments are made from legacy VML. The colors are a simplecolor ECMA-376:4, 20.1.2.3.
Per ECMA-376:1, 18.8.27 (the indexedColors element for palette)
> When values not present in the above list are used, the behavior is implementation-defined.

The [[MS-OI29500]: Office Implementation Information](https://interoperability.blob.core.windows.net/files/MS-OI29500/%5bMS-OI29500%5d.pdf) specifies additional colors in chapter **2.1.1889: Part 4 Section 20.1.2.3, ST_ColorType (Color Type)"**
specifies additional colors and their names for palette entries, not exact color.

Add the palette entries from MS-OI29500 to the color (I think they are in order after 65, so the 81 is a palette entry _InfoText_ and so on). Except there isn't a color, just a name...

* Add colors from implementation detail (index->name and I guess actually color, though name is important thing here).
* GenerateCommentShape should write name of color and its index (for indexed colors outside of standard colors).

**Comment by jahav** [comment]
How to get actual colors:
* Create a new file, change a color of a single cell. Save
* Open the sheet and modify the styles.xml so the fill is 
```xml
 		<fill>
			<patternFill patternType="solid">
				<fgColor indexed="80"/>
				<bgColor indexed="80"/>
			</patternFill>
		</fill>
```
* Open excel
* Use color picker to get actual color.

Any index over 242 (mod 256) causes an error and excel wants to recover the workbook,

**Comment by skyflyer** [comment]
@jahav, thank you very much for an informative feedback. So what do you think would be an appropriate fix for this in your library? Returnign `Color.Empty` in such case? Do you want me to send a PR for that?

**Comment by skyflyer** [comment]
Thank you! 🙏
