### ISSUE TITLE
System.NotImplementedException in ConvertLegacyCellValueToScalarValue for integer value

### ISSUE THREAD

**Issue by cjundt** [ClosedXML/ClosedXML#1887]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.97.0

**What is the current behavior?**

Throws System.NotImplementedException: Not sure how to get convert value 0 (type Int32) to AnyValue.

**What is the expected behavior or new feature?**

Should treat Int32 value as ordinary numeric value.

**Is this a regression from the previous version?**

No.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
using ClosedXML.Excel;

public void Main()
{
	using( var wb = new XLWorkbook( ) ) {
		var ws = wb.Worksheets.Add("Sample Sheet");
		ws.Cell( "A1" ).FormulaA1 = "=A2";
		ws.Cell( "A10" ).FormulaA1 = "=SUM(A1:A9)";

		Console.WriteLine( $"A10={ws.Cell( "A10" ).Value}" );
	}
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

PS : Pull request will follow

**Comment by jahav** [comment]
Thanks. Until I fix the XLCell typing issues, adapter must somehow work.
