### ISSUE TITLE
When trying to upgrade to nuget package version 0.97.0 I get a dependency error

### ISSUE THREAD

**Issue by Sicos1977** [ClosedXML/ClosedXML#1890]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve dependency 'SixLabors.Fonts'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'.

**Comment by jahav** [comment]
Please try one of methods from

https://github.com/ClosedXML/ClosedXML/issues/1883#issuecomment-1289521384

**Comment by Sicos1977** [comment]
Okey will try that did not even know that packages.config is deprecated. It is in a project that is already 12 years old :-)
