### ISSUE TITLE
XLCell value representation

### ISSUE THREAD

**Issue by jahav** [ClosedXML/ClosedXML#1894]
`XLCell` currently represents value in a string. That has several problems:
* Correctness problem (e.g. blank is not representable, formals are often wrong)
* performance problem (e.g. it takes time to convert string to a number)
* memory problem: it takes up a lot more memory than it should

This is a tracking ticket to try to tackle the issue. 

The research will probably have to come first, to determine how should the actual value from xlsx, DataType and formula type values coordinate.

**Comment by jahav** [comment]
@Pankraty  @igitur FYI
I have been thinking about this for a while and I have decided to make the cut and change semantic of `IXLCell.Value` property to be in-line with OOXML type system. I don't see any future where it is allowed to stay in current form. It should have been done a decade ago, but better now than never. Postponing this would only lead to more users using a original semantic - higher migration in the future.

It is super important to have this semantic clear to user and to ClosedXML. Comparison, formula type coercion, autofilter, sorting... everything relies on it. Current semantic is highly unintuitive -> hard to use library.

Basic changes:
* Removal of `IXLCell.SetDataType` and `IXLCell.DataType` setter (plus related method in range ect.) - changing a type means to do a conversion of the value. Sometimes conversion is funky (e.g. "14,5" to number will end up as an error in en-US locale while succeeds on `cs-CZ`). That is basically a `reinterpret_cast` and it is not something we should do (+ I don't see a use case). Replacement: If user wants to change type, the user should just do a conversion and set a new value with a different type. The type coercion is a thing CalcEngine is responsible for during formula calculation and it was heavily improved in the #1899.
* `IXLCell.Value` will accept only types `Blank` (something like `DbNull`), `bool`, `double` (+probably u/short, u/int, u/long), `string`, `DateTime`, `TimeSpan`, `XLError` and `RichText`. Other types will throw `ArgumentException`. Its semantic will be to set a value of the cell, nothing more, no type conversions. The original logic (accepting IEnumerable, XLRangeRows, XLRangeColumns and so much more) will be moved to another method `SetValueFuzzy(object o)` (name pending). In the long run, I want to expose structure `ScalarValue` and use it for `IXLCell.Value` with implicit casting operators. I don't want to hide `ScalarValue` behind interface because that means to  always box it (interface = virtual methods), but `ScalarValue`'s internal structure are going to be in flux for a while and since it is a struct, that is a no-go.
*  `IXLCell.SetValue<T>(object o)` will undergo similar treatment. There will be `SetValue(Blank)`, `SetValue(double)`... An overload for each acceptable type.
* The `IXLCell.GetDouble`, `IXLCell.GetDateTime`, `IXLCell.GetTimeSpan` and so on will have an additional argument `coerceType` set by default to `false`. Without the flag, there won't be any attempt of conversion and if type won't be compatible = exception. With the flag, ClosedXML will try to coerce type and only  if coercion is unsuccessfuly = exception.

Since this is a significant change to semantic, I am considering to use 0.100 version (haven't decided yet).

**Comment by jahav** [comment]
Work continues. Although my dev branch is a complete mess, test at least pass (I know the pain points).

Test files often had cell value type without a value. Excel interprets that as a blank value and thus so do I.

**Comment by 2mik** [comment]
Hello,
Making IXLCell.DataType read only affected my code. May I ask, in the old version, when a user's code changes data type, was there a data conversion made by ClosedXML or it was done by Excel application?

Likely, [Wiki](https://github.com/closedxml/closedxml/wiki/Data-Types) should be updated.

**Comment by jahav** [comment]
@2mik The conversion was done by ClosedXML, see DataType setter from 0.97 https://github.com/ClosedXML/ClosedXML/blob/0.97.0/ClosedXML/Excel/Cells/XLCell.cs#L905

**Comment by 2mik** [comment]
Thank you for quick reply. In this case, definitely, removing SetDataType is right.
