### ISSUE TITLE
Pictures' and Shapes' display order is not respected after save

### ISSUE THREAD

**Issue by J-Sanna** [ClosedXML/ClosedXML#1896]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [X] Yes
- [ ] No

**Version of ClosedXML**

0.97.0

**What is the current behavior?**

When saving a workbook containing stacked pictures and shapes, the assets display order is scrambled. Pictures always get in front of shapes.

**What is the expected behavior or new feature?**

Images and shapes should keep the disposition they had in opened file.

**Is this a regression from the previous version?**

This is not a regression. Bug was present in 0.92.0 already.

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
	var filePath = "C:\Tests\Images-Shapes.xlsx"
	var workbook = new XLWorkbook(filePath);
	workbook.SaveAs(filePath + ".test.xlsx");
}
```

- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)

I found a possible cause and fix for this issue in ClosedXML.Excel.XLWorkbook.AddPictureAnchor method.
This comes from the position the new OpenXml elements describing the picture are inserted in WorksheetDrawing part.
Since they are appended, they seem to be drawn last. Because other types of graphics (i.e. shapes) are ignored, these end-up being sent to back.
By keeping track of the original part's ordering, this issue can be resolved.

[Images-Shapes.xlsx](https://github.com/ClosedXML/ClosedXML/files/9888765/Images-Shapes.xlsx)

**Comment by jahav** [comment]
Resolved by #1944
