### ISSUE TITLE
ObjectReader should exclude indexer properties to fix exception 'Parameter count mismatch'

### ISSUE THREAD

**Issue by StefH** [ClosedXML/ClosedXML#1904]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Did you test against the latest CI build?**
- [x] Yes

**Version of ClosedXML**

e.g. `develop`

**What is the current behavior?**

When a class has an indexer defined and is used on `cell.InsertData()` you get an exception Parameter count mismatch.

Example class :
``` c#
public class X
{
    public string Name { get; set; }

    public object? this[string name]
    {
        get
        {
             // logic here
        }

        set
        {
            // logic here
        }
    }
}

cell.InsertData(new X()); // Fails with exception
```

**What is the expected behavior or new feature?**

A check should be added to the [ObjectReader.cs](https://github.com/ClosedXML/ClosedXML/blob/develop/ClosedXML/Excel/InsertData/ObjectReader.cs#L31) to exclude indexer properties.

Possible example code:
``` c#
int parameters = propertyInfo.GetIndexParameters().Length;
if (parameters > 0)
{
	// The property is an indexer, skip this.
	continue;
}
```

**Comment by rubeesh** [comment]
Hi, is this issue fixed?
