### ISSUE TITLE
Blocking error when setting core properties "System.IO.Packaging Unrecognized root element in Core Properties"

### ISSUE THREAD

**Issue by willyskipper** [ClosedXML/ClosedXML#1908]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.96.0

**What is the current behavior?**

Hello ClosedXML community,

As a company we have chosen to use Closed XML to replace Aspose.Cell. We are currently blocked by an exception thrown randomly when we open a xlsx or xltx file. We cannot reproduce the bug locally on our developpement machines. 

Let me describe the context in a few words.  We are using a template file to create reports for our business. The template is a static file that never changes and was created using the latest version of Excel. Our scheduling suite runs overnight batches which generate around 50 reports using the same template file. Some of the jobs are launched in parallel by the scheduler.  

Every once in a while we observe an exception which blocks the generation of the Excel report. Process stops with below exception:

```
System.Xml.XmlException at System.IO.Packaging Unrecognized root element in Core Properties Part. Line 2, Position 2.
at System.IO.Packaging.PartBasedPackageProperties.ParseCorePropertyPart(PackagePart part)
at System.IO.Packaging.PartBasedPackageProperties..ctor(Package package)
at System.IO.Packaging.get_PackageProperties()
at ClosedXML.Excel.XLWorkbook.SetProperties (SpreadsheetDocument dSpreadsheet)
at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument (SpreadsheetDocument dSpreadsheet)
at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName)
```

When I looked into the [XLWorlbook](https://github.com/ClosedXML/ClosedXML/blob/c3b33f410901363ac007d791ccd9a0e7d3e3c24e/ClosedXML/Excel/XLWorkbook_Load.cs#L3006) class at line 3008 ClosedXML will call 

var p = dSpreadsheet.PackageProperties where dSpreadSheet is the OpenXML object SpreadsheetDocument. 

First of all we don’t understand why this exception occurs randomly and since it works 9 out of 10 times we assume that this is not a corrupt file issue. 

Second, we have tested against multi-threading and we haven’t observed any problems with concurrent access. 

Any help for understanding or fixing the issue is highly appreciated. We really want to keep ClosedXML as a part of our System, however we can not have random exceptions blocking out production. 

**What is the expected behavior or new feature?**
I would suggest to catch exceptions when setting the properties so that if there is a problem it should't be a blocker.

**Is this a regression from the previous version?**
No this is not a regression

## Reproducibility
We haven't been able to reproduce the problem on our dev machines, exception only occures on servers.

**Code to reproduce problem:**
```c#
public void Main()
{
     var workbook = new XLWorkbook("Path to a xlt file of your choice");
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by kenleese** [comment]
@willyskipper OpenXML is not thread safe.

**Comment by willyskipper** [comment]
> @willyskipper OpenXML is not thread safe.
@kenleese you are right we knew that it was not thread safe. I am not sure if our issue is really a threading issue since we are not doing multi-threading in our code but, the scheduler launches different separate processes on multiple servers.

Also Aspose.cells uses same OpenXML library and they some how managed it, we never had this issue.

**Comment by jr01** [comment]
The underlying multi threading problem in System.IO.Packaging is fixed in .net 6. See my issue here:  https://github.com/dotnet/runtime/issues/43012 

This library could be updated to target .net 6 directly (and not use `<PackageReference Include="System.IO.Packaging" Version="4.7.0" />`).

**Comment by willyskipper** [comment]
> The underlying multi threading problem in System.IO.Packaging is fixed in .net 6. See my issue here: [dotnet/runtime#43012](https://github.com/dotnet/runtime/issues/43012)
> 
> This library could be updated to target .net 6 directly (and not use `<PackageReference Include="System.IO.Packaging" Version="4.7.0" />`).

@jr01 Juuriaan this is excellent news. We currently running on core 2.2 but, will be moving to .NET 6 soon.

**Comment by jahav** [comment]
@jr01 Thank you for the information. I didn't know that.

I generally go for lowest compatible version 4.7.0 is the lowest version version for .NET Standard it is 4.7.0 and also minimal version `DocumentFormat.OpenXml`. 

I plan to stay on .NET Standard 2.0 for a while. Thankfully, `System.IO.Packaging` still has NET Standard 2.0 version, I will look if there is any breaking change in the `System.IO.Packaging` library and update the version if there isn't and works fine on .NET Framework and Core.

@willyskipper You should be able to add a direct dependency on `System.IO.Packaging` 6.0.0 and it should pick up .NET Standard version fow pre-NET6 environments.
