### ISSUE TITLE
ClassicPivotTableLayout does not work

### ISSUE THREAD

**Issue by vcoderv** [ClosedXML/ClosedXML#191]
Please check if , setting this does not seem to do anything when I check actual pivot table property for Classic View.  Thank youl

```c#            
pt = ws.PivotTables.AddNew("BenchmarkEventsPivot", ws.Cell(9, 1), source);
pt.ClassicPivotTableLayout = true;

pt.RowLabels.Add("SUBMASTER","Client");

pt.RowLabels.Add("SIDE", "Side");
pt.RowLabels.Add("SYMBOL", "Symbol");
pt.RowLabels.Add("TRADER", "Trader");

pt.Values.Add("PL").SetSummaryFormula(XLPivotSummary.Sum).NumberFormat.Format = "#0,000";
pt.Values.Add("QTY").SetSummaryFormula(XLPivotSummary.Sum).NumberFormat.Format = "#0,000";
```

**Comment by vcoderv** [comment]
Anyone?  ty

**Comment by igitur** [comment]
Fixed in #199

**Comment by vcoderv** [comment]
When will this be available ?

**Comment by vbjay** [comment]
Gee. Fixed in 199 3 DAYS AGO!!!

You comment 4 hours ago asking when it will be available.

**Comment by vcoderv** [comment]
I meant for the download..  ver 0.87

**Comment by vbjay** [comment]
Since there are no milestones
https://github.com/ClosedXML/ClosedXML/milestones, you have two options.
Wait till they release or build from code.

**Comment by igitur** [comment]
The PR has been merged into the `develop` branch. I'd appreciate it if you could pull the `develop` branch and check that it solves your issue. Thanks.
