### ISSUE TITLE
Package upgrade request - XLParser - contains .netcore vulnerability

### ISSUE THREAD

**Issue by vcha0018** [ClosedXML/ClosedXML#1919]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.97.0

**What is the current behaviour?**

The Package is depended on XLParser which is built on Microsoft.NETCore.Platforms 3.1.0

**What is the expected behaviour or new feature?**

.NET versions 5.0 through 5.0.6 and .NET Core versions 3.1 through 3.1.15 is vulnerable to Denial of Service.
Expected .NETCore v6.

**Is this a regression from the previous version?**

No

## Reproducibility

Version Upgrade Request
Could you please update XLParser to the latest .NETCore v6?

**Comment by jahav** [comment]
Not sure what exactly is the problem: 
1. Microsoft.NETCore.Platforms is a package with only JSON and no code. I don't see how it could lead to DOS.
2. XLParser doesn't depend on Microsoft.NETCore.Platforms. It only depends on Irony.NetCore + netstandard library. Even Microsoft.NETCore.Platforms required by NetStandard.Library resolves to a minimal version of 1.1.0, not 3.1.15.
3. Projects using NetStandard through .NET5+ runtime use 5/6/7 versions of assemblies from NETCore anyway through. per [direct dependency wins](https://learn.microsoft.com/en-us/nuget/concepts/dependency-resolution#direct-dependency-wins):
> When a closer dependency in the same subgraph has a higher version than a further one, then NuGet ignores that dependency, NuGet also ignores all remaining dependencies on that branch of the graph.
