### ISSUE TITLE
sheet.Cell("B3").InsertData(table.AsEnumerable()) doesn't apply a user defined cell format

### ISSUE THREAD

**Issue by yooontheearth** [ClosedXML/ClosedXML#192]
This attached excel has a cell which is set a user defined cell format "yy/MM/dd".
[format test.xlsx](https://github.com/ClosedXML/ClosedXML/files/765869/format.test.xlsx)

But the following code doesn't apply it when you open a saved file. It shows "2016/10/4" instead of "16/10/4". You need to manually click and leave the cell to affect the format.
```
var table = new System.Data.DataTable();
table.Columns.Add("Date");
table.Rows.Add("2016/10/4");    
sheet.Cell("B3").InsertData(table.AsEnumerable());
```

But this code does work well. It shows "16/10/4" properly.
`sheet.Cell("B3").Value = "2016/10/4";`

**Comment by vbjay** [comment]
Try using actual dates instead of strings.

**Comment by yooontheearth** [comment]
Ok, I'll let you know when I try that later since I'm away from work in a week.

**Comment by yooontheearth** [comment]
No setting an actual date type doesn't work either.

```
table.Columns.Add("Date");
table.Rows.Add(DateTime.Now);    
```

I even tried this way, and didn't work either.
```
table.Columns.Add("Date", typeof(DateTime));
table.Rows.Add(DateTime.Now);    
```

**Comment by igitur** [comment]
Please provide a fully reproducible code sample.

**Comment by yooontheearth** [comment]
Here is a full code sample.

```
using (var wb = new XLWorkbook("format test.xlsx"))
{
	var sheet = wb.Worksheet(1);
	var table = new System.Data.DataTable();
	table.Columns.Add("Date");
	table.Rows.Add(DateTime.Now);
	sheet.Cell("B3").InsertData(table.AsEnumerable());
	wb.SaveAs("output.xlsx");
}
```

**Comment by igitur** [comment]
I've fixed this, but you still have to explicitly specify your column data type in the `DataTable`, e.g.

```c#
table.Columns.Add("Date", typeof(DateTime));
```

**Comment by yooontheearth** [comment]
Awesome. No problem to specify a data type. Thanks.

**Comment by igitur** [comment]
The PR has been merged into the `develop` branch. I'd appreciate it if you could pull the `develop` branch and check that it solves your issue. Thanks.

**Comment by yooontheearth** [comment]
I confirmed that the bug was fixed. Thanks a lot!
