### ISSUE TITLE
v0.97 : ToAdjustContents() crash on Azure pipeline.

### ISSUE THREAD

**Issue by etiennejy** [ClosedXML/ClosedXML#1921]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.97.0

**What is the current behavior?**

Hi,
I have a unit test executing using ToAdjustContents method. This unit test is OK when I run it on local. When deployed to azure pipeline, I have the following error:

`  Error Message:
   System.ArgumentException : Unable to find font Calibri or fallback font Microsoft Sans Serif. Install missing fonts or specify a different fallback font through 'LoadOptions.DefaultGraphicEngine = new DefaultGraphicEngine("Fallback font name")'.
  Stack Trace:
     at ClosedXML.Graphics.DefaultGraphicEngine.LoadFont(MetricId metricId)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ClosedXML.Graphics.DefaultGraphicEngine.GetFont(MetricId metricId)
   at ClosedXML.Graphics.DefaultGraphicEngine.GetFont(IXLFontBase fontBase)
   at ClosedXML.Graphics.DefaultGraphicEngine.GetTextWidth(String text, IXLFontBase fontBase, Double dpiX)
   at ClosedXML.Excel.XLColumn.GetWidthInCharacters(String text, IXLFontBase font)
   at ClosedXML.Excel.XLColumn.AdjustToContents(Int32 startRow, Int32 endRow, Double minWidth, Double maxWidth)
   at ClosedXML.Excel.XLColumn.AdjustToContents(Int32 startRow, Int32 endRow)
   at ClosedXML.Excel.XLColumn.AdjustToContents(Int32 startRow)
   at ClosedXML.Excel.XLColumn.AdjustToContents()
   at ClosedXML.Excel.XLColumns.<>c.<AdjustToContents>b__13_0(XLColumn c)
   at ClosedXML.Excel.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action)
   at ClosedXML.Excel.XLColumns.AdjustToContents()`

The issue appeared on release 0.97. It works fine on release 0.96.

**What is the expected behavior or new feature?**

Same behaviour as previous release.

**Is this a regression from the previous version?**

Yes.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**
**Code to reproduce problem:**
The code looks like this:

```c#
public void Main()
{
`            var workbook = new XLWorkbook();
            IXLWorksheet worksheet = workbook.AddWorksheet(ExcelExportSheetName);

            IXLRow headerRow = worksheet.Row(1);
            row.Cell("A").SetValue("data1");
            row.Cell("B").SetValue("data2");
            ...
            row.Cell("AB").SetValue("dataN");

            worksheet.Columns("Z").AdjustToContents();

            for (int i = 0; i < orders.Count; i++)
            {
                var rowNumber = i + HeaderRowNumber + ExcelIndexOffset;
                IXLRow xlRow = worksheet.Row(rowNumber);
                xlRow.Cell("A").SetValue("some data");
                ...
                xlRow.Cell("AB").SetValue("some data");
            }
            worksheet.Columns("A:Y").AdjustToContents();
            worksheet.Columns("AA:AB").AdjustToContents();
`
}
```

**Comment by vbjay** [comment]
That would be a pipeline config issue.  What image are you basing the pipeline off of?  https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

**Comment by jahav** [comment]
The pipeline likely runs on non-windows environment (or maybe Azure pipeline uses some kind of very limited windows without fonts). 

As far as your problem, try one of the solutions from here:  https://github.com/ClosedXML/ClosedXML/issues/1902#issuecomment-1299196079.

`System.Drawing.Common` has been replaced by `SixLabors.Fonts` (#1805) because System.Common.Drawing only works on Windows and there are no  ready fonts available in all environments, see the explanation over here: https://github.com/SixLabors/Fonts/discussions/227

Picking a random available font is not a solution (each font has a different metrics), so it is left to a developer to ensure that font is present on the environment where the program is running.

**Comment by etiennejy** [comment]
Hi,

Thanks for your answers! I don't know which version of Azure pipeline I use. I use the one from my customer and I only have the right to deploy code and run build on it. I can't change anything else and It will not possible to install any font or change any settings on the server.

What is strange is that in my code I don't use explicitly any font. I guess that ClosedXML need to chose a font to run the "AdjustToContents()" method but in the previous release, there is no issue. It seems that the release 0.97 requires to have a font installed on the server whereas the release 0.96 doesn't need it.

**Comment by vbjay** [comment]
I gave you a link about the images Microsoft hosts that even tells you what the defaults are. You could look at your repo and deternine which image is used. That will determine if it is Linux or Windows based. 

You could start by reading https://github.com/ClosedXML/ClosedXML/releases/tag/0.97.0

**Comment by etiennejy** [comment]
Thanks !

It works by adding: 
`LoadOptions.DefaultGraphicEngine = new DefaultGraphicEngine("DejaVu Sans");`

**Comment by vbjay** [comment]
I'll admit the version numbering for this project doesn't provide the info of breaking changes which I feel definitely was a breaking change. Of course when we go to 1.0 https://giphy.com/gifs/thedudeperfectshow-cmt-the-dude-perfect-show-l3V0lsGtTMSB5YNgc would be my reaction.

**Comment by jHabjanMXP** [comment]
If someone else is checking why this crashes on Linux distros.
I did it like this:

```csharp
/// <summary>
/// If runtime platform is not Windows, we have to set graphics engine fallback font in order
/// for AdjustToContents to work.
/// We're setting preferred font to DejaVu Sans, which is available on most linux distros. If not, we're
/// falling back to first available font.
/// </summary>
private static void UpdateGraphicsEngineFonts()
{
    bool isWindows = RuntimeInformation.IsOSPlatform(OSPlatform.Windows);
    if (isWindows) return;

    // https://github.com/ClosedXML/ClosedXML/releases/tag/0.97.0
    const string preferredFont = "DejaVu Sans";
    List<string> fonts = SystemFonts.Collection.Families.Select(f => f.Name).ToList();

    // If the preferred font is not available, use the first available font
    var fontName = fonts.Contains(preferredFont) ? preferredFont : fonts.First();

    // All workbooks created later will use the engine with a fallback font DejaVu Sans
    // (or the first available font)
    LoadOptions.DefaultGraphicEngine = new DefaultGraphicEngine(fontName);
}
```
And call `UpdateGraphicsEngineFonts()` *BEFORE* creating a workbook with `using XLWorkbook workbook = new();`.
