### ISSUE TITLE
Out of range activeTab value

### ISSUE THREAD

**Issue by 0MG-DEN** [ClosedXML/ClosedXML#1929]
## Read and complete the full issue template
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature
- [ ] Question

**Did you test against the latest CI build?**

- [x] Yes
- [ ] No

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**

Apperently, some auto-generated workbooks can have -1 as **activeTab** property of **workbookView**.
Thus accessing **ActiveTab.Value** property (since it's casted to UInt32) results in **FormatException** being thrown.

```xml
<!-- workbook.xml -->
<workbook>
    <bookViews>
        <workbookView activeTab="-1"/>
    </bookViews>
    <!-- ... -->
</workbook>
```
**What is the expected behavior or new feature?**

As Excel does when opening such files, make first tab active.

## Reproducibility
**Code to reproduce problem:**
```c#
using ClosedXML.Excel;

var workbook = new XLWorkbook("Book1.xlsx")
```

- [x] I attached a sample spreadsheet.
[Book1.xlsx](https://github.com/ClosedXML/ClosedXML/files/10143259/Book1.xlsx)

**Comment by jahav** [comment]
Thanks for the contribution.
