### ISSUE TITLE
DataValidation not working copy from another cell

### ISSUE THREAD

**Issue by jona2017** [ClosedXML/ClosedXML#193]
Hi, 

I'm working about existing template of Excel, I want add new row on the table, this rows have DataValidation, but I try with get rows 1 (not header) and cellformat.CopyTo(cellnew), This not working, copy format Style is Ok but not copy DataValidation. I need duplicate DataValidation, please how resolve this problem.

PD: Sorry my Englihs, I speak Spanish. Espero que me pueda ayudar a resolver esta duda. Gracias

This is my code example:

```c#
XLWorkbook workBook = new XLWorkbook(filePath);
var ws1 = workBook.Worksheet("Ejemplo");
var celda_formato = ws1.Cell("A1"); //This have DataValidation 

for (int i = 1; i <= 10; i++)
{
    for (int ii = 1; ii <= 100; ii++)
    {
        if (ii == 1 && i == 1) { continue; }
        string column = GetExcelColumnName(i) + ii.ToString();
        IXLCell actual = ws1.Cell(column);

        celda_formato.CopyTo(actual); //Copy format Sytle is Ok
        if (celda_formato.HasDataValidation) //as it does not working, I try this, copy DataValidation
        {
            string get_range = celda_formato.DataValidation.Ranges.ToString();
            actual.SetDataValidation().AllowedValues = XLAllowedValues.List;
            //actual.SetDataValidation().Ranges = celda_formato.DataValidation.Ranges;
            //This range not working, no get real ranger.
            actual.SetDataValidation().List(get_range, true);
        }

        actual.Value = "Opcion04";
    }
}
workBook.SaveAs(filePath);
```

Imagen of Excel file
![error_datavalidatio](https://cloud.githubusercontent.com/assets/25689232/22831339/fa37eec6-ef77-11e6-84f6-e388b862f359.png)

**Comment by igitur** [comment]
I can't reproduce this with v0.89. Data validation copies perfectly. Please try again and let me know if there are problems. I'll reopen the issue if there are.
