### ISSUE TITLE
Licensing issue with new dependency XLParser

### ISSUE THREAD

**Issue by dro123** [ClosedXML/ClosedXML#1932]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.97.0

**What is the current behavior?**

Licensing issues with the new XLParser dependency:
https://github.com/spreadsheetlab/XLParser/issues/169

**What is the expected behavior or new feature?**

If I understand it correctly the XLParser library is used for formulars.
The license used in that project is less permissive than the license used by this project.
Is there any chance we can get a version without that dependency and formular support removed/only basic fucntions supported in case the following issue gets rejected?
https://github.com/spreadsheetlab/XLParser/issues/169

**Is this a regression from the previous version?**

I would argue it's a "yes" here ;-)

**Comment by jahav** [comment]
There aren't any plan to have a version without XLParser dependency.

MPL2.0 provides a very reasonable terms that allow incorporation into a closed source code which basically boils down to
"you have to add a notice somewhere about use of a library and it's license and put there a link to project website. Executable itself can be distributed under any terms and conditions, not under MPL2.0." (see article 3.2 of MPL2.0)

> 12. Could you give some examples of what it means to "inform"?
> More generally, notices should be put in the place a reasonable person is likely to look for legal information about the software they have recieved.
> https://www.mozilla.org/en-US/MPL/2.0/Revision-FAQ/#what-does-inform-mean

Reasonable person would look for license files in an installation directory and requirement to have a license notice as a part of the software is already requirement of MIT license, so I don't see any problems and you haven't explained any problems you actually have with the license.

> 3.2. Distribution of Executable Form
>  If You distribute Covered Software in Executable Form then:
>
> a. such Covered Software must also be made available in Source Code Form,
>    as described in Section 3.1, and You must inform recipients of the
>    Executable Form how they can obtain a copy of such Source Code Form by
>    reasonable means in a timely manner, at a charge no more than the cost
>    of distribution to the recipient; and
>
> b. You may distribute such Executable Form under the terms of this
>    License, or sublicense it under different terms, provided that the
>    license for the Executable Form does not attempt to limit or alter the
>    recipients' rights in the Source Code Form under this License.

**Comment by dro123** [comment]
I don't argue that the license has reasonable terms, but they are different than MIT :-)
3.2.a for example states that I have to make the source code form available of the package even if I distribute only the executable. Such condition is not there in a MIT licenses.
So to be fully compliant (especially for a long time!) I have to personally keep a copy of the source code around in case it gets removed from github or something like this.
Again I'm not arguing if this is reasonable, just that it's less permissive than MIT.

**Comment by jahav** [comment]
Thanks for the info. As I wrote, I don't plan a version without XLParser. It is maintained project that accepts PR and is compatible with a closed-source software.

Closing as not planned.
