### ISSUE TITLE
Cell with only white space is trimmed

### ISSUE THREAD

**Issue by theuselessone** [ClosedXML/ClosedXML#194]
I am trying to save a cell that only contains white space but the spaces are removed when saving.
Is it possible to save and preserve white space?

```vb
Using sl As New XLWorkbook()
  Dim ws = sl.AddWorksheet("TextList")
  sl.ShowWhiteSpace = True
  ws.ShowWhiteSpace = True
  ws.Cell(1, 1).Value = "'" & "Test"
  ws.Cell(2, 1).Value = "'" & "     " 
  sl.SaveAs("test.xlsx")
End Using
```

**Comment by igitur** [comment]
The PR has been merged into the `develop` branch. I'd appreciate it if you could pull the `develop` branch and check that it solves your issue. Thanks.

**Comment by theuselessone** [comment]
I tried the update and i can now both save and load space and no break space which did not work before.

     textToAdd = " "
      textToAdd = ChrW(160) 'No break space

Many thanks for an awesome job with the library!



Mvh
Martin Bratt
martinbratt@hotmail.com<mailto:martinbratt@hotmail.com>



________________________________
Från: Francois Botha <notifications@github.com>
Skickat: den 20 mars 2017 10:35
Till: ClosedXML/ClosedXML
Kopia: theuselessone; Author
Ämne: Re: [ClosedXML/ClosedXML] Cell with only white space is trimmed (#194)


The PR has been merged into the develop branch. I'd appreciate it if you could pull the develop branch and check that it solves your issue. Thanks.
