### ISSUE TITLE
Need some instruction on using SixLabor.Fonts with ClosedXML

### ISSUE THREAD

**Issue by genifycom** [ClosedXML/ClosedXML#1947]
## Read and complete the full issue template

I have read all the threads like https://github.com/ClosedXML/ClosedXML/issues/1805 about the deprecation of System.Drawing.Common and about fonts in AWS linux.

What I cannot find is once I have loaded a SixLabors.Fonts.Font, how do I use it in ClosedXML?

From here: https://github.com/SixLabors/Fonts

FontCollection fonts = new FontCollection();
FontFamily font1 = fonts.Add("./path/to/myfont.ttf");

Now it is is the FontCollection, how do I get it into ClosedXML?

This one: https://github.com/ClosedXML/ClosedXML/wiki/Styles-Font adds a Font by name, but from where? Not from the SixLabors FontCollection.

 wb.Style.Font.SetFontName("MyFont"); 

ultimately gives me "Unable to find font MyFont."

Searches like "closedxml how to use custom fonts" are unhelpful.

So "use SixLabors.Fonts for netstandard2.0 and others" how?

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.97.0

**What is the current behavior?**

Unable to find font MyFont

**What is the expected behavior or new feature?**

Unknown. Just trying to find a way to get it to work for me.

**Is this a regression from the previous version?**

Unknown

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by vbjay** [comment]
Read the latest release notes.

**Comment by genifycom** [comment]
Thanks for responding. You mean using this line?

// All workbooks created later will use the engine with a fallback font DejaVu Sans
LoadOptions.DefaultGraphicsEngine = new DefaultGraphicEngine("DejaVu Sans"); // or Tahoma or any other font that is installed

BTW, I believe it should say (DefaultGraphicsEngine -> DefaultGraphicEngine):

LoadOptions.DefaultGraphicEngine = new DefaultGraphicEngine("DejaVu Sans"); 

While this does not fail, the resulting xlsx cannot be opened in Windows Excel (I guess due to DejaVu Sans not being present).

**Comment by vbjay** [comment]
Pick a default font that does exist. It was an example.

**Comment by jahav** [comment]
I have added the some info and possible solutions to the the documentation https://closedxml.readthedocs.io/en/latest/tips/missing-font.html.

To get a list already installed fonts, use snippet like this:
```cshapr
foreach (var fontFamily in SixLabors.Fonts.SystemFonts.Collection.Families)
   Console.WriteLine(fontFamily.Name);
```

**Comment by genifycom** [comment]
Hi jahav, thank you so much for adding additional information about the fonts.

So should it be possible to load a font into a stream (from a file for example) and set the DefaultGraphicEngine directly to that stream. That would be awesome!

Can we use SixLabors font load as well https://docs.sixlabors.com/articles/fonts/gettingstarted.html

When will v0.100 be released?

**Comment by jahav** [comment]
@genifycom Likely during weekend. It was supposed to be released around Christmas, but life happened.

SixLabors.Fonts interfaces and classes will always be hidden. ClosedXML won't expose them. 
1. I might need to replace them again, just like System.Drawing. It's an implementation detail.
2. SixLabors has changed license several times during past few years. *SixLabors.Fonts* are still under Apache, but *SixLabors.ImageSharp* is under [Six Labors Split License](https://github.com/SixLabors/ImageSharp/blob/main/LICENSE) and it is not at all certain that won't happen to Fonts too and in that case ... well, I will cross that bridge when I come to it.

**Comment by genifycom** [comment]
Hi jahav,

I tested 0.100.0 with calibri.ttf (the easiest to test with). I used the code as (final path points at the correct calibri.ttf).

 ```
       using (var fallbackFontStream = File.OpenRead(finalPath))
        {
            LoadOptions.DefaultGraphicEngine = DefaultGraphicEngine.CreateOnlyWithFonts(fallbackFontStream);
        }
```
The spreadsheet has a single cell entry.

  ```
      IXLWorkbook wb = new XLWorkbook();
        {
            IXLWorksheet ws = wb.Worksheets.Add("Receipts");
            ws.Cell(1, 2).Value = $"Receipt Settlement Report";
            ws.Columns().AdjustToContents();
        }
```
[settlement-2023-01-02-2023-0
[settlement-2023-01-02-2023-01-02 (1).xlsx](https://github.com/ClosedXML/ClosedXML/files/10377662/settlement-2023-01-02-2023-01-02.1.xlsx)
1-02.xlsx](https://github.com/ClosedXML/ClosedXML/files/10377660/settlement-2023-01-02-2023-01-02.xlsx)

Same code for Windows (7kb) opens in Excel fine, for Linux (10kb) says in Excel "We found a problem with some content ... Do you want us to try to recover as much as we can? If you trust the source of this workbook, click yes.

File is corrupt and cannot be opened."

I know calibri is copyrighted, but should this work the same in both environments?

What can I provide to help with this?

**Comment by jahav** [comment]
@genifycom It looks like the second file is completely corrupted. xlsx file is a zip file with a different extension and the second one isn't openable. When I look at it as hex stream, it doesn't look like it should.

![image](https://user-images.githubusercontent.com/7634052/212401552-aac2cade-2d4c-4ef1-81ce-b31804ad06db.png)

**Comment by jahav** [comment]
@genifycom It looks like very byte with value over 128 has been turned into a mush and the remaining bytes that are lower are left between mush (by mush I mean that every byte over 128 was turned into three bytes 0xEF 0xBF 0xBD). 

Please make sure the file didn't pass through some weird text encoding process (e.g. at the end of the program, do a checksum of created file or just check the length of created file).

If that doesn't help, please open a separate issue and include **reproducible details** (exact code and environment) + if it works when you remove AdjustToContent.

**Comment by jahav** [comment]
@genifycom Pretty sure not bug in ClosedXML, see this SO with exact same byte sequence and linux to windows move  https://stackoverflow.com/questions/8318314/linux-to-windows-bad-encoding-response
