### ISSUE TITLE
Theme XLColor to System.Drawing.Color

### ISSUE THREAD

**Issue by Moonlgum** [ClosedXML/ClosedXML#196]
Is there a way to convert a cell's fill background color if it is a theme ColorType to system.drawing.color ?
```c#
XLColor c = XLColor.FromTheme(cell.Style.Fill.BackgroundColor.ThemeColor, cell.Style.Fill.BackgroundColor.ThemeTint);
return c.Color;
```
fails : 
`"Cannot convert theme color to Color."`

Thanks!

**Comment by igitur** [comment]
Unfortunately there's not a straight-forward way, but it's definitely something we should look at. You can do it through Reflection, which is slow, so I prefer to use the `FastMember` library for such things. Here is a piece of sample code that illustrates how you can do it:

```c#
using System;
using System.Linq;
using ClosedXML.Excel;
using FastMember;

namespace ClosedXML_Sandbox
{
    class Program
    {
        private static void Main(string[] args)
        {
            using (var wb = new XLWorkbook("test.xlsx"))
            {

                var ws = wb.Worksheets.First();
                var cell = ws.FirstCell();
                var themeColourName = cell.Style.Fill.BackgroundColor.ThemeColor.ToString();
                var color = ObjectAccessor.Create(wb.Theme)[themeColourName] as XLColor;
                var rgb = color.Color.ToHex().Substring(2);

                Console.WriteLine(rgb);
            }

            Console.WriteLine("Press any key to continue");
            Console.ReadKey();
        }
    }
}
```

**Comment by igitur** [comment]
or you probably just want `var drawingColor = color.Color;` to get `System.Drawing.Color`

**Comment by Moonlgum** [comment]
A method in ClosedXml would be nice to have.The color won't be correct until it has the theme color tint applied to it.
Thanks! 

    On Tuesday, February 14, 2017 9:49 AM, Francois Botha <notifications@github.com> wrote:
 

 or you probably just want var drawingColor = color.Color; to get System.Drawing.Color—

**Comment by igitur** [comment]
Look at #210 :
```c#
workbook.Theme.ResolveThemeColor(XLThemeColor themeColor)
```

**Comment by vmsp** [comment]
@igitur That method doesn't apply the tint, though, right?

**Comment by igitur** [comment]
@vmsp No, it doesn't.
