### ISSUE TITLE
Cannot implicitly convert type 'decimal' to 'ClosedXML.Excel.XLCellValue'

### ISSUE THREAD

**Issue by mserioli** [ClosedXML/ClosedXML#1960]
I have upgraded from version 0.97.0 to 0.100.0 and I'm facing the following issues:

ws.Cell(rowNum, 7).Value = 123m;
but decimals are no more supported

ws.Cell(rowNum, 12).Value = operation.IsMandatory.HasValue ? (operation.IsMandatory.Value ? 1 : 0) : null;
but null is no more supported (or nullable)

I also used to assign generic objects but it doesn't work anymore.
ws.Cell(rowNum, 7).Value = myObject; 

Is this a wanted change? 

HAve you introduced a new way of doing what I used to do, or is simply no more supported?

Many thanks for your help

**Comment by jahav** [comment]
The change itself is intended, see [release note](https://github.com/ClosedXML/ClosedXML/releases/tag/0.100.0). For time being, use explicit casting to double.

There isn't an implicit operator from decimal to `XLCellValue`, I will think about if it should be there or not. Excel can't represent all decimal values, only double.

**Comment by jahav** [comment]
I have thought about decimal implicit conversion and it is better to add it. That is how it used to work and there is no reason to force users of library to add explicit cast from decimal to double everywhere. Will make a 0.100.1 with implicit conversion.

```
// How did 0.97.0 deal with different types
var wb = new XLWorkbook();
var ws = wb.AddWorksheet();
ws.Cell(1,1).Value = (decimal)1;
Console.WriteLine(ws.Cell(1,1).Value.GetType()); // Double

ws.Cell(1, 1).Value = (sbyte)-5;
Console.WriteLine(ws.Cell(1, 1).Value.GetType()); // Double
```

**Comment by jahav** [comment]
@mserioli

I have published package right away in order to mitigate amount of people who have to deal with the missing conversion. 

> I also used to assign generic objects but it doesn't work anymore.
> ws.Cell(rowNum, 7).Value = myObject;

Yes. This won't work, if the object was used to insert data (it implemented IEnumerable), use InsertData (see [doc](https://closedxml.readthedocs.io/en/latest/features/bulk-insert-data.html)). If it is just some object, cell will no longer accept unknown object, you have to convert it to something that is a cell value.

> ws.Cell(rowNum, 12).Value = operation.IsMandatory.HasValue ? (operation.IsMandatory.Value ? 1 : 0) : null;

Use Blank.Value instead of null.

**Comment by mserioli** [comment]
Thank you very much,

really appreciated

**Comment by andycnguyen** [comment]
I'm finding that if I use `InsertTable<T>` where `T` has a decimal property, the resulting table column for that property carries a warning that it has numbers stored as text. By contrast, I don't find this if the field is a double, or if I manually assign decimal values to the table cells. Is this behavior related to the issue that the implicit conversion addresses?

**Comment by jahav** [comment]
No, that is a separate bug. Thanks for noticing.

The conversion from decimal to xlcellvalue happens at the code where compiler picks up the correct conversion, while insertdata gets anunknown object and ClosedXML tries to pick the correct conversion by itself.
