### ISSUE TITLE
No document shows how to migrate XLEventTracking.Disabled

### ISSUE THREAD

**Issue by EdiWang** [ClosedXML/ClosedXML#1964]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.100.2

**What is the current behavior?**

Can not compile

```csharp
var workbook = new XLWorkbook(XLEventTracking.Disabled)
```

**What is the expected behavior or new feature?**

Migration document should contain information about how to migrate this: https://github.com/ClosedXML/ClosedXML/wiki/Turning-off-events

**Is this a regression from the previous version?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**

```c#
public void Main()
{
    var workbook = new XLWorkbook(XLEventTracking.Disabled)
    {
        // ...
    }
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
Thanks, will update doc.

Event tracking hasn't been doing anything for likely years.

https://github.com/ClosedXML/ClosedXML/commit/61fd48e2489963f15f5b2bd737f8a79d251d2708

**Comment by jahav** [comment]
I have updated the [migration guide](https://closedxml.readthedocs.io/en/latest/migrations/migrate-to-0.100.html#xleventtracking-removed), changed wiki page to inform user about removal and removed the wiki page from FAQ about performance. I bundled doc change to #1967.
