### ISSUE TITLE
Current NuGet packages are Debug Builds failing validation on non US systems

### ISSUE THREAD

**Issue by SmartBuster** [ClosedXML/ClosedXML#198]
The currently released version 0.86.0 & 0.85.0 are debug builds that use validation by default.
This is a problem because validation always fails on non US system because the DocumentFormat.OpenXML uses the current locale to transform numbers which than violates MaxInclusive constraints.

**Comment by igitur** [comment]
@Pyropace I think we've briefly discussed this. Will you check it out?

@SmartBuster, in the meantime you can disable the validation using the `SaveAs(..., false)` overload.

**Comment by SmartBuster** [comment]
The mentioned overload works as expected, but I prefer to use a version where the "default" methods does not require the additional parameter especially when others that don't be aware of this run into this issue.
Therefore I currently got back to 0.80.1.

Maybe you should check the NuGet packages first

Creating OpenXml Word documents have the same problem with those two lines:
var validator = new OpenXmlValidator();
var errors = validator.Validate(mDoc);

**Comment by igitur** [comment]
You're losing out on a lot of improvements just to avoid an extra parameter, but it's your choice.
