### ISSUE TITLE
XLWorkbook cannot load the xlsx file which a sheet name does not have a whitespace and PageSetup.PrintAreas is added.

### ISSUE THREAD

**Issue by norainu98** [ClosedXML/ClosedXML#1983]
Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.100.3
0.100.2
0.100.1
0.100.0
0.97.0
0.96.0

**What is the current behavior?**

XLWorkbook cannot load the xlsx file which a sheet name does not have a whitespace and **PageSetup.PrintAreas** is added.
An eception(There isn't a worksheet named '{SheetName}!{PrintRange},{SheetName}') occurs.

**What is the expected behavior or new feature?**

Even If a sheet name does not have a whitespace, it's possible to load a xlsx file which **PageSetup.PrintAreas** is added.

**Is this a regression from the previous version?**

0.95.4 does not have a problem. 
From 0.96.0 is occured a proble. 

## Reproducibility

```csheap
public static int Main(string[] args)
{
	// There is not a spaces in sheet name.-> An exception occur: System.ArgumentException: There isn't a worksheet named 'A!$A$1:$B$2,A'
	TestPrintArea("A");
	// There is some spaces in sheet name. -> An exception does not occur.
	TestPrintArea("A ");
	return 0;
}

private static void TestPrintArea(string sheetName)
{
	const string FileName = "printarea.xlsx";
	if (File.Exists(FileName))
	{
		File.Delete(FileName);
	}
	using (var workbook = new XLWorkbook())
	{
		var ws1 = workbook.Worksheets.Add(sheetName);
		ws1.PageSetup.PrintAreas.Add("A1:B2");
		ws1.PageSetup.PrintAreas.Add("D3:D5");
		workbook.SaveAs(FileName);
	}
	try
	{
		using (var workbook = new XLWorkbook(FileName))
		{
			Console.WriteLine($"'${sheetName}'\r\n -> SUCCESS");
		}
	}
	catch(Exception ex)
	{
		Console.WriteLine($"'${sheetName}'\r\n -> Exception occur. (${ex.Message})");
	}
}
```

:resut(v0.100.3)

```console
'$A'
 -> Exception occur. ($There isn't a worksheet named 'A!$A$1:$B$2,A'.)
'$A '
 -> SUCCESS
```

:resut(v0.95.4)

```console
'$A'
 -> SUCCESS
'$A '
 -> SUCCESS
```

**Comment by norainu98** [comment]
[issue1983.patch](https://github.com/ClosedXML/ClosedXML/files/10472050/issue1983.patch)

Probably, I think ```XLWorkbook.validateDefinedNames``` method is wrong in always expecting single quotes in a sheet name.  
So, it returns an invalid value when a sheet name does not have a whitespace and **PrintAreas** has multiple areas.

example for, 

- SheetName:"A" -> ["A!$A$1:$B$2,A!$D$3:$D$5"]
- SheetName:"A " -> ["'A '!$A$1:$B$2", "'A '!$D$3:$D$5"]

ClosedXML/ClosedXML/Excel/XLWorkbook_Load.cs
Line:1570

- Problem?

  ```csharp
    private static Regex definedNameRegex = new Regex(@"\A'.*'!.*\z", RegexOptions.Compiled);
  ```

- Probably right.

  ```csharp
    private static Regex definedNameRegex = new Regex(@"\A('.*'|[^ ]+)!.*\z", RegexOptions.Compiled);
  ```

A patch also is attached.

**Comment by norainu98** [comment]
this issue is not resolved yet.
Shoud I push PR but too late ? Since I don't core member, I refrain from push...

**Comment by fopsdev** [comment]
hi there
i'm also running into this issue
any news?

**Comment by Mikado3780** [comment]
I would be also really glad if this problem will be resolved.
Thanks.

**Comment by igitur** [comment]
Does this problem still exist on the latest version of the `develop` branch? If so, please attach a reproducible test case file.

**Comment by Mikado3780** [comment]
Yes:
`System.ArgumentException: 'There isn't a worksheet named 'TestSheet!$B$2:$M$41,TestSheet!$B$46:$M$72,TestSheet'.'`

[TestFile.xlsx](https://github.com/user-attachments/files/16636137/TestFile.xlsx)

**Comment by rominator1983** [comment]
This should be addressed in https://github.com/ClosedXML/ClosedXML/pull/2420
