### ISSUE TITLE
Sheets with invalid id are not being ignored

### ISSUE THREAD

**Issue by mihailmacarie** [ClosedXML/ClosedXML#1992]
In case a file that contains a sheet with an empty string id is loaded using 
`new XLWorkbook(stream)` 
the sheets with an invalid id like null or empty string are causing an exception problem in the calls `dSpreadsheet.WorkbookPart.GetPartById(dSheet.Id) as WorksheetPart` in XLWorkbook_Load.cs

My suggestion would be to ignore completely the sheets that have an invalid id like Excel is doing.

It could be as simple as 

![image](https://user-images.githubusercontent.com/33224962/215094347-40479a9b-6f1f-40ad-8b1f-25279f154624.png)

and

![image](https://user-images.githubusercontent.com/33224962/215094250-6544aee2-bc51-451f-9440-1b113a0a011a.png)

**Comment by NickNack2020** [comment]
@mihailmacarie do you have a workbook that exhibits this, is that even a valid workbook, or would excel show it as corrupt?

**Comment by mihailmacarie** [comment]
@NickNack2020 I have such a workbook but I can't expose it due to GDPR and because it is generated by a third party using some library I can't modify it in Excel as it will fix it. Excel opens it correctly as it ignores the sheet with the invalid id. If I save it in Excel the invalid sheet disappears in the saved file and then the ClosedXML library can open it.

**Comment by jahav** [comment]
Resolved in #2008.

Behavior during loading now mimics Excel = add a blank sheet with name and specified visibility when encountering a sheet with empty r:id.
