### ISSUE TITLE
closedxml with vs2012 does not work

### ISSUE THREAD

**Issue by balamcsd** [ClosedXML/ClosedXML#1997]
When i use closedxml with visual studio 2012 .NET framework 4.5 MVC project , it does not work (internal server error)
Same working in vs 2017. How to fix it vs2012
Thanks

**Comment by jahav** [comment]
Internal server error is a message from IIS server or MVC. That is out of scope of this project. Any issue must be only for ClosedXML or directly related to it and it requires a [minimal complete and verifiable](https://stackoverflow.com/help/mcve) code sample. 

Also, ClosedXMl requires netstandard 2.0 that is supported only from 4.6.2 (should mostly work on 4.6.1, only a very small API subset is missing)

That is also part of the template you have deleted. No repro, closing.
