### ISSUE TITLE
XLColumn.AdjustToContents throws exception

### ISSUE THREAD

**Issue by skhairnar** [ClosedXML/ClosedXML#2003]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.100.3

**What is the current behavior?**

While creating excel worksheet a call to AdjustToContents with 1 to 100 start and end row parameters is throwing following exception:

_Row Collated Compare: Sheet format failed?
System.ArgumentException: Unable to find font Calibri or fallback font Microsoft Sans Serif. Install missing fonts or specify a different fallback font through 'LoadOptions.DefaultGraphicEngine = new DefaultGraphicEngine("Fallback font name")'. Additional information is available at https://closedxml.readthedocs.io/en/latest/tips/missing-font.html page.
   at ClosedXML.Graphics.DefaultGraphicEngine.LoadFont(MetricId metricId)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ClosedXML.Graphics.DefaultGraphicEngine.GetFont(MetricId metricId)
   at ClosedXML.Graphics.DefaultGraphicEngine.GetFont(IXLFontBase fontBase)
   at ClosedXML.Graphics.DefaultGraphicEngine.GetTextWidth(String text, IXLFontBase fontBase, Double dpiX)
   at ClosedXML.Excel.XLColumn.GetWidthInCharacters(String text, IXLFontBase font)
   at ClosedXML.Excel.XLColumn.AdjustToContents(Int32 startRow, Int32 endRow, Double minWidth, Double maxWidth)
   at ClosedXML.Excel.XLColumn.AdjustToContents(Int32 startRow, Int32 endRow)
   at ClosedXML.Excel.XLColumns.<>c__DisplayClass15_0.<AdjustToContents>b__0(XLColumn c)
   at ClosedXML.Excel.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action)
   at ClosedXML.Excel.XLColumns.AdjustToContents(Int32 startRow, Int32 endRow)_

**What is the expected behavior or new feature?**

Code need to handle this exception and adjust column width as per content length.

**Is this a regression from the previous version?**

Regressions get higher priority. Tested  this function against previous minor version 0.97.3 and 0.96.3 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

Code is running under following docker image provided by Microsoft for .netcore runtime.

**_mcr.microsoft.com/dotnet/core/aspnet:$LSRUNTIME-bionic AS finalbase_**

**Code to reproduce problem:**
```c#
public void Main()
{
            var dt = new DataTable();
            dt.Columns.Add("Test long column without wrapping");
            dt.Rows.Add("Test value for large column 1");
            dt.Rows.Add("Test value for large column 2");
            dt.Rows.Add("Test value for large column 3");
            dt.Rows.Add("Test value for large column 4");
            dt.Rows.Add("Test value for large column 5");
            dt.Rows.Add("Test value for large column 6");
            dt.Rows.Add("Test value for large column 7");
            dt.Rows.Add("Test value for large column 8");
            dt.Rows.Add("Test value for large column 9");
            dt.Rows.Add("Test value for large column 10");
            dt.Rows.Add("Test value for large column 12");
            dt.Rows.Add("Test value for large column 13");
            dt.Rows.Add("Test value for large column 14");
            dt.Rows.Add("Test value for large column 15");
            dt.Rows.Add("Test value for large column 16");
            dt.Rows.Add("Test value for large column 17");
            dt.Rows.Add("Test value for large column 18");
            using var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("MyWB");
            worksheet.Style.Alignment.WrapText = false;
            if (worksheet.Tables.Count() > 0)
            {
                var tbl = worksheet.Tables.Last().AppendData(dt);
            }
            else
            {
                // Incase the attribute is true for the first table.
                var tbl = worksheet.Cell(1, 1).InsertTable(dt, "MyWS", false);
            }
            worksheet.Columns().AdjustToContents(1, 100);

            var exportFile = Path.Combine(Path.GetTempPath(), "export.xlsx");
            using var fileStream = File.Create(exportFile);
            workbook.SaveAs(fileStream, false, false);
            fileStream.Flush();
            fileStream.Close();
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
@skhairnar Please follow the instructions in the exception message. 

Microsoft has decided to kill System.Drawing.Common and not provide an alternative and I am just dealing with the fallout.
