### ISSUE TITLE
decimal datatype not handled properly as number

### ISSUE THREAD

**Issue by SmartBuster** [ClosedXML/ClosedXML#201]
When I assign a value of type decimal to a cell the resulting sheet is not as expected on non US systems.

```c#
var workbook = new XLWorkbook(XLEventTracking.Enabled);
var worksheet = workbook.Worksheets.Add("Sheet1");
var cell = worksheet.Cell(1, 1);
cell.Style.NumberFormat.Format = "0.00 €"; 
cell.Value = 1878.5m;
cell = worksheet.Cell(1, 2);
cell.Style.NumberFormat.Format = "0.00 €";
cell.Value = 1.5d;

workbook.SaveAs("O:\\output.xlsx", false);
```

Using this the cell with 1878.5 is written as string "1878,5" (type="s" and included in the sharedStrings.xml) which results in a "numbers stored as text" warning from excel.
Using double as datatype creates the expected type="n" entry for the cell

Versions tested 0.86.0 & 0.80.1

**Comment by vbjay** [comment]
Look at the datatype property of cells and ranges

**Comment by SmartBuster** [comment]
Thanks for the info, I was using version 0.68.0 before updating and this version had a better "auto-detection" for number values.
Beside that on my german system adding
```C#
cell.DataType = XLCellValues.Number;
```
results in the exception
`Cannot set data type to Number because '1878,5' is not recognized as a number.`

Only if I wrap all code with
```C#
var currentCulture = Thread.CurrentThread.CurrentCulture;
try
{
  Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
  // more code here
}
finally
{
  Thread.CurrentThread.CurrentCulture = currentCulture;
}
```

resolves the problem (and the problem with enabled validation too)

**Comment by SmartBuster** [comment]
adding the decimal type to line 263 of XLCell.cs will make a better auto detection.
The current code will use the ToString() to convert the decimal to a culture bound string where the following DataType change tries to re-parse the string with InvariantCulture which fails.

**Comment by igitur** [comment]
The PR has been merged into the `develop` branch. I'd appreciate it if you could pull the `develop` branch and check that it solves your issue. Thanks.
