### ISSUE TITLE
@ Symbol gets inserted into formula

### ISSUE THREAD

**Issue by SergeBerwert** [ClosedXML/ClosedXML#2012]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.100.3

**What is the current behavior?**

Try to set a Formula witch ads an @ sign in front of the Function name

**What is the expected behavior or new feature?**

not inserting the @ symbol

**Is this a regression from the previous version?**

Was on version 0.94.3 the same problem 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce the problem:**
```c#
  var workbook = new XLWorkbook();
  IXLWorksheet worksheet = workbook.Worksheets.Add("InventoryItems");

  var c = worksheet.Cell(row, column);
  c.FormulaA1 = "IMAGE(\"" + image.ResourceUrl +"\")";
```

Result:
![Excel](https://user-images.githubusercontent.com/7489837/218775842-5d598a19-4207-4be2-b1c7-f316d6b86195.png)

**Comment by jahav** [comment]
That is not a bug in ClosedXML, but a behavior of an Excel. Excel is adding implicit intersection to formulas to pre-2019 xlsx to keep original behavior. Without explicit intersection, Excel 2019+ would  spill arrays.

See [MS Support - Implicit intersection operator: @ When do we add the @ to old formulas?](https://support.microsoft.com/en-us/office/implicit-intersection-operator-ce3be07b-0101-4450-a24e-c1c999be2b34#ID0EDL).

ClosedXML doesn't have a way to to avoid it atm. We would have to support dynamic arrays and spilling for that.

**Comment by SergeBerwert** [comment]
I have found a solution to my problem. I saw a note in the documentation that functions that are not part of the original Excel functions must each be called with the _xlfn suffix. The following code works for me with the latest version of the library.

` cell.SetFormulaR1C1($"=_xlfn.IMAGE(\"https://upload.wikimedia.org/wikipedia/en/a/aa/Bart_Simpson_200px.png\")");`
