### ISSUE TITLE
Installing from nuget gives this issue

### ISSUE THREAD

**Issue by tayyeb89** [ClosedXML/ClosedXML#2013]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Did you test against the latest CI build?**
- [ ] Yes

**Version of ClosedXML**
e.g. 0.100.3

## Reproducibility
When installing ClosedXML from manager console to ASP.NET MVC 5 Project

Severity	Code	Description	Project	File	Line	Suppression State
Error	
Could not install package 'ClosedXML 0.100.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)
![image](https://user-images.githubusercontent.com/65479841/218928718-4fda48b7-b114-42de-bc41-4c8a90090aea.png)

**Comment by jahav** [comment]
Please read this: https://closedxml.readthedocs.io/en/latest/installation.html#sixlabors-fonts
