### ISSUE TITLE
azure function c# script Could not load file or assembly System.IO.Packaging, Version=4.0.5.0

### ISSUE THREAD

**Issue by heliobarbosa** [ClosedXML/ClosedXML#2014]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.100.3

**What is the current behavior?**

I'm using azure function with c# script and added to function.proj nuget package referente for ClosedXml as below
<PackageReference Include="ClosedXML" Version="0.100.3" />
then it throws exception Could not load file or assembly System.IO.Packaging, Version=4.0.5.0

**What is the expected behavior or new feature?**
Open excel by using a stream variable with azure function c# script 

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

I went down to version 0.97.0 wich I was able to get a instance of XLWorkbook with stream as argument

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public static async Task<IActionResult> Run(HttpRequest req, ILogger log)
{
    var bs = new BlobStorage();
    var templateStream = bs.ReadTemplateFromBlob();
    var wbook = new XLWorkbook(templateStream);
    log.LogInformation("finished!!!");
    return new OkObjectResult("OK");
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
Due to racing condition bug, the required version of System.IO.Packaging has been increased to 6.0.0. The version 4.0.5.0 from the issue is a version in an assembly reference WindowsBase.dll in .NET Framework IIRC.

You have to use version nuget package instead, it is .NET Standard 2.0 package (or assembly binding). https://www.nuget.org/packages/System.IO.Packaging

I don't know how to do that in cscript Azure Function.
