### ISSUE TITLE
Spreadsheet with invalid Find function gives "String not found." exception in sheet.RecalculateAllFormulas();

### ISSUE THREAD

**Issue by FranzThomsen1089** [ClosedXML/ClosedXML#2015]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

ClosedXML.0.101.0-preview

Spreadsheet with invalid Find function gives "String not found." exception in sheet.RecalculateAllFormulas();

**What is the expected behavior or new feature?**

I would expect the value in the cell to read 0

**Is this a regression from the previous version?**

Not sure

## Reproducibility
In a spreadsheet add

=COUNT(FIND({2;5;4;5;6;7},8)) to Sheet1!A1

It throws a System.ArgumentException: 'String not found.' in sheet.RecalculateAllFormulas();

**Code to reproduce problem:**
```c#
var fileName = @"C:\myspreadsheet.xlsx";
var workbook = new XLWorkbook(fileName);
var sheet = workbook.Worksheets.FirstOrDefault(r => r.Name == "Sheet1");
sheet.RecalculateAllFormulas();
```

**Comment by jahav** [comment]
I removed the exception from the FIND function, but note that the formula you have used will still fail because array formulas are not supported (tracked in #1812).
