### ISSUE TITLE
cannot operate with existing excel file

### ISSUE THREAD

**Issue by andreyshv** [ClosedXML/ClosedXML#202]
There is a simple excel file produced by third party software. I opened it with ClosedXML and saved with no modification. Then opened it with MS Excel and got an error (something about drawings). Excel opens original document with no problem. Can you tell me there problem is or how can I fix it?
Thank you.
[original.xlsx](https://github.com/ClosedXML/ClosedXML/files/775523/original.xlsx)
[output.xlsx](https://github.com/ClosedXML/ClosedXML/files/775525/closedxml.xlsx)

**Comment by igitur** [comment]
Your original file contains 2 drawings, which aren't supported in `ClosedXML` yet.

```
    <x:drawing r:id="rId1" />
    <x:legacyDrawing r:id="rId2" />
```

**Comment by andreyshv** [comment]
They are empty. Open/save with Excel removes them. Can I remove them with ClosedXML or OpenXML?

**Comment by igitur** [comment]
I'm still looking at the issue. I see the rId2 refers to a VmlDrawing which are closely tied to cell comments. There's definitely a ClosedXML bug there, but I'm trying to get my head around it. Previous developers did that part. 

But yes, a quick workaround would be to open the file with OpenXML and delete the VmlDrawing parts. I think that should work.

**Comment by igitur** [comment]
The PR has been merged into the `develop` branch. I'd appreciate it if you could pull the `develop` branch and check that it solves your issue. Thanks.
