### ISSUE TITLE
No ColumnName when insert a DataTable

### ISSUE THREAD

**Issue by Jiafan1999** [ClosedXML/ClosedXML#2028]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.100.3.0

**What is the current behavior?**

when adding a datatable, the column's name didn't show, only shows Column1,2,3  .... 
![image](https://user-images.githubusercontent.com/100297294/224915457-ad024d06-b8f4-47c4-bd85-5f55b0049518.png)

**Code to reproduce problem:**
```c#
public void Main()
{
var wb= new IXLWorkbook();
   wb.Worksheets.Add(dt);
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by Jiafan1999** [comment]
findout why the column name is strange, set the `column.caption=String.Empty`;

Maybe there are some difference in the 0.100.3.

But can we add a param in the `Worksheets.Add()` function to control this, use `column.columnname or column.caption `

**Comment by jahav** [comment]
No repro, closing. As far as I can tell, it also works correctly.

See more docs at:
https://closedxml.readthedocs.io/en/latest/features/tables.html
https://github.com/ClosedXML/ClosedXML/wiki/Inserting-Tables

```
using System.Data;
using ClosedXML.Excel;

using var wb = new XLWorkbook();
var ws = wb.AddWorksheet();

var dataTable = GetTable();
ws.Cell(1, 1).InsertTable(dataTable);

wb.SaveAs("tables-datatable.xlsx");

DataTable GetTable()
{
    DataTable table = new DataTable();
    table.Columns.Add("Dosage", typeof(int));
    table.Columns.Add("Drug", typeof(string));
    table.Columns.Add("Patient", typeof(string));
    table.Columns.Add("Date", typeof(DateTime));

    table.Rows.Add(25, "Indocin", "David", DateTime.Now);
    table.Rows.Add(50, "Enebrel", "Sam", DateTime.Now);
    table.Rows.Add(10, "Hydralazine", "Christoff", DateTime.Now);
    table.Rows.Add(21, "Combivent", "Janet", DateTime.Now);
    table.Rows.Add(100, "Dilantin", "Melanie", DateTime.Now);
    return table;
}
```

![image](https://user-images.githubusercontent.com/7634052/225188046-660c5a0a-af00-43a8-b416-3246b730877b.png)
