### ISSUE TITLE
Nested IF in formula

### ISSUE THREAD

**Issue by viga99** [ClosedXML/ClosedXML#2030]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.4.0

**What is the current behavior?**

I'm using excel in Italian.

When I generate the file, the file is generated and downloaded correctly.
But when I open the file, I get a window with written "There was a problem with some of the contents of 'filename.xslx'. Try to recover the content? If the workbook is considered alertable, click yes."
I clicked yes.

I got another window saying:

"The file could be opened by removing or restoring unreadable content.
Records removed: Formula from /xl/worksheets/sheet1.xml
Records removed: Formula from part /xl/calcChain.xml (Calculation Properties)"

The file is correct, but removed the cell with the formula.

How can I solve this problem?

**What is the expected behavior or new feature?**

Put formula in cell.

## Reproducibility
**Code to reproduce problem:**
```vb.net
ws.Cell(1, 19).FormulaA1 = "=SE(VAL.VUOTO(M1), SE(((OGGI() - B1) > 10), 1, 2), SE(((N1) > 10), 3, 4)"
```

**Comment by vbjay** [comment]
https://www.excelfunctions.eu/VAL.VUOTO/Italian-English

Use the correct formula. I would imagine you need to use the correct
functions.  You can't assume the file will be loaded by Italian.

**Comment by vbjay** [comment]
Do this test. Open excel and set up the formula and then read the cell
formula in closedxml. See if it matches the formula or did it save the
English formula names.

**Comment by viga99** [comment]
I'm sorry. I forgot to specify that if I write only one if the function works.

Example: 
ws.Cell(1, 19).FormulaA1 = "=SE(VAL.VUOTO(M1),1,2)"

**Comment by vbjay** [comment]
Ok. Setup the formula in excel not closedxml to make sure formula is right. Then use closedxml to read the formula.  Does excel change your formula?  Do you have to alter formula in excel to make it work?

**Comment by viga99** [comment]
Nevermind

I tried to insert the formula from vb.NET in english and it works.

Thanks
Have a good day
Chiara
