### ISSUE TITLE
Cells assigned TextRotation values between -90 and -1 exhibit a variety of incorrect behaviors

### ISSUE THREAD

**Issue by misterspeedy** [ClosedXML/ClosedXML#2033]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.101.0-preview
0.100.2
0.100.3

**What is the current behavior?**

Cells assigned `TextRotation` values between -90 and -1 exhibit a variety of incorrect behaviors when the created file is opened in Excel. For example the first cell in the attached spreadsheet was assigned a `TextRotation` of -90, but renders at an angle of -76 degrees. This is apparent both visually and when the user selects the "Aligment" tab in "Format Cells" and views the "Orientation" control.

Cells assigned `TextRotation` values in the range -75 to -2 do not render any text at all in Excel, and most of them show a value of 0 in the "Orientation" control.

Cells assigned zero and positive `TextRotation` values are rotated correctly - for example the cell assigned a `TextRotation` of 33 renders correctly and has the correct value in the "Orientation" control in Excel.

**What is the expected behavior or new feature?**

Text rotation values between -90 and +90 should render with the appropriate rotation when the resulting file is opened in Excel. (-90 to +90 is the settable range in the Excel UI.)

When a cell with text rotation applied in this range is selected, and the user then selects the "Alignment" tab in "Format Cells", the Orientation dial and field should also show the assigned `TextRotation` value.

**Is this a regression from the previous version?**

No.

## Reproducibility

**Code to reproduce problem:**
```c#
using ClosedXML.Excel;

using (var workbook = new XLWorkbook())
{
    var worksheet = workbook.Worksheets.Add("Sample Sheet");
    for (int angle=-90; angle<=+90; angle++) {
        var column = angle+91;
        var cell = worksheet.Cell($"A{column}");
        cell.Value = $"Rotation: {angle}";
        cell.Style.Alignment.TextRotation = angle;
    }
    workbook.SaveAs("TextRotation.xlsx");
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[TextRotation.xlsx](https://github.com/ClosedXML/ClosedXML/files/11012338/TextRotation.xlsx)

**Comment by misterspeedy** [comment]
I don't know if this is helpful or relevant, but when I opened `TextRotation.xlsx` in Libre Office Calc on a Linux box, none of the cells were visibly rotated nor did they have a non-zero rotation in the orientation control in the Libre Office Calc UI.

**Comment by jahav** [comment]
This value is only passed through to the file, so it should be used angle < 0 ? 90 - angle : angle.

We should improve the contract for negative values and supply better documentation. Will think about it.


> Text rotation in cells. Expressed in degrees. Values are in the range 0 to 180. The first
> letter of the text is considered the center-point of the arc.
> For 0 - 90, the value represents degrees above horizon. For 91-180 the degrees below the
> horizon is calculated as:
> [degrees below horizon] = 90 - textRotation.
> Source: ISO29500 §18.8.1

EDIT:
VBA accepts only values -90..90 and 255. It throws on other values, so it should probably be our behavior.

**Comment by misterspeedy** [comment]
@jahav Thank you so much for the considered response - and the fix!
