### ISSUE TITLE
default cell style

### ISSUE THREAD

**Issue by andreyshv** [ClosedXML/ClosedXML#206]
I have a style.xlsx. ClosedXML and Excel understand default style differently
This is original style.xlsx
![original](https://cloud.githubusercontent.com/assets/13389499/22985904/9543dfcc-f3b2-11e6-8154-554bbfaf9a09.png)
And after I open/save file with ClosedXML
![changed](https://cloud.githubusercontent.com/assets/13389499/22985905/9547f63e-f3b2-11e6-9645-8235cfd578f3.png)
Font size in row 1 changed to 8, font in rows 3 to 12 changed to Calibri-11

[style.xlsx](https://github.com/ClosedXML/ClosedXML/files/777723/style.xlsx)

**Comment by igitur** [comment]
Even though Excel renders it correctly, your file is corrupt. The elements of the `<font>` element have to appear in a certain order. Yours is in the wrong order, e.g.: 
```xml
		<font>
			<name val="Arial"/>
			<charset val="0"/>
			<family val="2"/>
			<b val="false"/>
			<i val="false"/>
			<strike val="false"/>
			<sz val="10"/>
			<u val="none"/>
		</font>
```

Please use the [Open XML SDK 2.5 Productivity Tool](https://www.microsoft.com/en-za/download/details.aspx?id=30425) to validate your files first.
