### ISSUE TITLE
Unable to read/load Excel file having Pivot tables and External links

### ISSUE THREAD

**Issue by amitkhajuria** [ClosedXML/ClosedXML#2063]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x ] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.100.0

**What is the current behavior?**
Error: A malformed URI was found in the document. Please provide a OpenSettings.RelationshipErrorRewriter to handle these errors while opening a package
Error: Specified argument was out of the range of valid values. (Parameter 'index')

Complete this.

**What is the expected behavior or new feature?**
The Excel workbook with Pivot tables  and external links should load and should  allow to read all sheets data.
Complete this.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Excel workbook will be loaded as stream
    using (XLWorkbook xlworkBook = new XLWorkbook(stream))
      {

      }
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
Closing as not reproducible. No test case, no workbook as supplied, not even a stacktrace.

I tried to load a workbook with a pivot table using a link to external workbook it loaded in in 0.100.
