### ISSUE TITLE
DateTime parsing algorithm has critical problem

### ISSUE THREAD

**Issue by PARKGIBAEK** [ClosedXML/ClosedXML#2064]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.101.0

**What is the current behavior?**

**When I input a datetime format data '4/18/2023  1:00:00 PM' in excel sheet.

Then Closed XML parsed into '4/18/2023  01:00:00 AM' in C#.

And also '4/24/2023  1:00:00 AM' parsed into '4/24/2023  12:59:59 AM'.**

**What is the expected behavior or new feature?**

It should be parsed as it input.

**Is this a regression from the previous version?**

I have no idea.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
   string value = sheet.Cell(row, currentColumn).GetDateTime().ToString();
  // or
   string value = sheet.Cell(row, currentColumn).Value.ToString();
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)
[0_datetime_test.xlsx](https://github.com/ClosedXML/ClosedXML/files/11245670/0_datetime_test.xlsx)

**Comment by vbjay** [comment]
Excel stores dates as serial and is not text.    You are getting stuck on format vs value. Use Ctrl ~ to see actual value of cell. Stop treating the dates as strings. Closedxml will give you the datetime value.  Also understand difference between datetimeoffset and datetime.

**Comment by PARKGIBAEK** [comment]
> Excel stores dates as serial and is not text. You are getting stuck on format vs value. Use Ctrl ~ to see actual value of cell. Stop treating the dates as strings. Closedxml will give you the datetime value. Also understand difference between datetimeoffset and datetime.

I know that.

Both are the same result.

string value = sheet.Cell(row, currentColumn).Value.ToString();
DateTime value2 = sheet.Cell(row, currentColumn).GetDateTime();

**Comment by jahav** [comment]
When I look into the file, the cells C8 and C9 have serial datetime fraction 0.541666666664 (e.g. 45036.541666666664). That is roughly 13:00/1:00 PM and that is also what ClosedXML says.  Cells C10 through C28 have serial datetime fraction  0.041666608799 which is roughly 1:00 after midnight/12:00 AM.

You can get the actual serial datetime value through `XLCellValue.GetUnifiedNumber()` method (e.g. `ws.Cell("C10").Value.GetUnifiedNumber()`).

The reproducible sample hasn't is missing a information that could be demonstrate issue. No this and this row shows this and should show that. As far as I can see, the only problem is a rounding error, that serial datetime fraction 0.541666666664/1:00 after midnight is shown as a `0:59:59`

**Comment by jahav** [comment]
Even that rounding is only a matter of Excel displaying data. If you use custom time format to see more precise time,. it is accurate, 59:59.995.

![image](https://user-images.githubusercontent.com/7634052/232495326-eaee20cd-9754-4261-959b-52db2bf74d01.png)


So overall, I see no bug here.

**Comment by PARKGIBAEK** [comment]
> When I look into the file, the cells C8 and C9 have serial datetime fraction 0.541666666664 (e.g. 45036.541666666664). That is roughly 13:00/1:00 PM and that is also what ClosedXML says. Cells C10 through C28 have serial datetime fraction 0.041666608799 which is roughly 1:00 after midnight/12:00 AM.
> 
> You can get the actual serial datetime value through `XLCellValue.GetUnifiedNumber()` method (e.g. `ws.Cell("C10").Value.GetUnifiedNumber()`).
> 
> The reproducible sample hasn't is missing a information that could be demonstrate issue. No this and this row shows this and should show that. As far as I can see, the only problem is a rounding error, that serial datetime fraction 0.541666666664/1:00 after midnight is shown as a `0:59:59`

Thanks, jahav !!

It's matter of fraction parts!

**Comment by PARKGIBAEK** [comment]
Issue closed.
