### ISSUE TITLE
Missing font exception on Ubuntu since 0.101.0

### ISSUE THREAD

**Issue by jr01** [ClosedXML/ClosedXML#2066]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes - tested with 0.101.999.3068
- [ ] No

**Version of ClosedXML**

0.101.0

**What is the current behavior?**

With 0.101.0 our automated tests on Github Linux/Ubuntu runner throw at  `new XLWorkbook(stream)`.

```
Unhandled exception. System.ArgumentException: Unable to find font Calibri or fallback font Microsoft Sans Serif. Install missing fonts or specify a different fallback font through 'LoadOptions.DefaultGraphicEngine = new DefaultGraphicEngine("Fallback font name")'. Additional information is available at https://closedxml.readthedocs.io/en/latest/tips/missing-font.html page.
   at ClosedXML.Graphics.DefaultGraphicEngine.LoadFont(MetricId metricId)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ClosedXML.Graphics.DefaultGraphicEngine.GetFont(MetricId metricId)
   at ClosedXML.Graphics.DefaultGraphicEngine.CalculateMaxDigitWidth(MetricId metricId)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ClosedXML.Graphics.DefaultGraphicEngine.GetMaxDigitWidth(IXLFontBase fontBase, Double dpiX)
   at ClosedXML.Excel.XLWorkbook.CalculateColumnWidth(Double charWidth, IXLFont font, XLWorkbook workbook)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)
   at ClosedXML.Excel.XLWorkbook.Load(Stream stream)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream, LoadOptions loadOptions)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream)
   at Program.<Main>$(String[] args) in /home/jur/linuxrepos/external/closedxmlbug/Program.cs:line 3
```
  
The information at the URL is helpful for finding a workaround. In our case it's a dumb implementation of IXLGraphicEngine where we just `return default` in all methods. We are not using any `AdjustToContent` and are just using XLWorkbook to read cell contents. 

I think this is a bug in ClosedXML. Some reasons:
1. We are not doing any `AdjustToContent`  and the exception already happens at `new XLWorkbook(stream)`. 
2. From a ClosedXML library perspective this makes it harder for people to start out with this library on systems (like Ubuntu) that don't have the mentioned Calibri or Microsoft Sans Serif. 
3. Didn't happen with any release before 0.101.0 and the release notes didn't say anything about a breaking change.

https://github.com/ClosedXML/ClosedXML/commit/b655dc7a7334c991635dc82efc47153a353a39ef seems to have introduced this.

**What is the expected behavior or new feature?**

I would expect `new XLWorkbook(stream)` to not require having installed any fonts.

**Is this a regression from the previous version?**

-

## Reproducibility

**Code to reproduce problem:**

In standard Ubuntu installation with dotnet sdk installed. I'm using WSL locally. And our CI uses Github actions with `ubuntu-latest` runner.

```
> dotnet new console
> dotnet add package ClosedXML
```

Program.cs:
```c#
using ClosedXML.Excel;
using var stream = File.OpenRead("./hello.xlsx");
_ = new XLWorkbook(stream);
```

- [x] I attached a sample spreadsheet. 
[hello.xlsx](https://github.com/ClosedXML/ClosedXML/files/11292775/hello.xlsx)

**Comment by jahav** [comment]
Fonts... bane of my existence. It hasn't occurred to me that width calculation for #837 is a breaking change due to font requirement.

[For 0.102](https://github.com/ClosedXML/ClosedXML/discussions/2067), I will try to embed stripped Carito font, so there is **something** to provide font metrics for all environments.

**Comment by wilkmaia** [comment]
For anyone else having this problem under Linux:

A quick/temporary workaround is to set the engine with a fallback font as instructed in https://closedxml.readthedocs.io/en/latest/features/graphic-engine.html#set-engine. I haven't tried the optins described in https://closedxml.readthedocs.io/en/latest/tips/missing-font.html but they might do the trick as well.

**Comment by adamhathcock** [comment]
Doesn't work with docker image `mcr.microsoft.com/dotnet/aspnet:7.0.5-bullseye-slim` will have to look at font management under Linux

**Comment by CodeCasterNL** [comment]
Encountering this as well on GitHub Actions. Repro:
* Have a "template" file built in Excel
* Have an integration test that wants to read the data from this file
* Read it through `using var workbook = new XLWorkbook(File.OpenRead(excelFilePath))`
* Encounter the stated exception because Excel's default theme wants the Calibri font

Workaround:
1. Wait for [0.102](https://github.com/ClosedXML/ClosedXML/discussions/2067) (Expected release date: Start of June)
2. Revert to 0.100.3

**Comment by nbarbettini** [comment]
Similar issue, and like @jr01 I don't need to call `AdjustToContent` or do any saving at all. This workaround worked fine on v0.101.0 (Linux):

```csharp
    /// <summary>
    /// Dummy implementation of <see cref="IXLGraphicEngine"/> to avoid any dependency on specific fonts.
    /// In our case we don't need font support at all, because we are only reading data from the file.
    /// See https://github.com/ClosedXML/ClosedXML/issues/2066
    /// </summary>
    public sealed class NoFontsXLGraphicEngine : IXLGraphicEngine
    {
        public double GetDescent(IXLFontBase font, double dpiY) => default;

        public GlyphBox GetGlyphBox(ReadOnlySpan<int> graphemeCluster, IXLFontBase font, Dpi dpi) => default;

        public double GetMaxDigitWidth(IXLFontBase font, double dpiX) => default;

        public XLPictureInfo GetPictureInfo(Stream imageStream, XLPictureFormat expectedFormat)
            => DefaultGraphicEngine.Instance.Value.GetPictureInfo(imageStream, expectedFormat);

        public double GetTextHeight(IXLFontBase font, double dpiY) => default;

        public double GetTextWidth(string text, IXLFontBase font, double dpiX) => default;
    }
```
