### ISSUE TITLE
Support WebP images

### ISSUE THREAD

**Issue by Pekshev** [ClosedXML/ClosedXML#2068]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.101.0

**What is the current behavior?**

When reading an Excel file, the error "Unable to determine the format of the image."

**Is this a regression from the previous version?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

The file contains pictures in jpg and jpeg format. I hope that the attached file will solve the problem in this case and in similar cases in the future

**Code to reproduce problem:**
```c#
public void Main()
{
    try
    {
      var file = @"E:\Temp\Ведомость сантехники_ванная.xlsx";
      var workbook = new XLWorkbook(file);
      var worksheet = workbook.Worksheet(1);
    }
    catch (Exception exception)
    {
      Debug.Print(exception.ToString());
      MessageBox.Show(exception.ToString());
    }
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Ведомость сантехники_ванная.xlsx](https://github.com/ClosedXML/ClosedXML/files/11307571/_.xlsx)

**Comment by jahav** [comment]
One of images is not jpeg, but WEBP in a RIFF container with a jpg extension. Once it is replaced with a converted jpeg (xlsx is just a zip), file loads.
> image1.jpg: RIFF (little-endian) data, Web/P image

There should be a better error message to specify which file failed.

**Comment by Pekshev** [comment]
Excel itself, however, can process them. In the library, in theory, is it possible to add processing of such pictures?

**Comment by jahav** [comment]
Yes, we just need size in pixels and DPI (if exists/provided, haven't seen whether WebP does store DPI) and write another ImageInfoReader in the ClosedXML.Graphics namespace.

If you need it now, create a new type implementing IXLGraphicEngine interface and wrap/inherit DefaultGraphicEngine and set it as a default ([see documentation ](https://closedxml.readthedocs.io/en/latest/features/graphic-engine.html)for more info), though be warned that part is pretty unstable and likely to change.

**Comment by ctmatt** [comment]
this is happening in 102.3

**Comment by ctmatt** [comment]
applied the following patch, and now it can open the excel file.  it also does get the dimensions of the images properly at this point.  The offending excel files have jpeg images with vandalized or otherwise rambunctious headers (as mentioned above)

```
 ClosedXML-develop/ClosedXML/Graphics/JpegInfoReader.cs | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/ClosedXML-develop/ClosedXML/Graphics/JpegInfoReader.cs b/ClosedXML-develop/ClosedXML/Graphics/JpegInfoReader.cs
index 18e8388..a1d1c9b 100644
--- a/ClosedXML-develop/ClosedXML/Graphics/JpegInfoReader.cs
+++ b/ClosedXML-develop/ClosedXML/Graphics/JpegInfoReader.cs
@@ -17,6 +17,7 @@ internal class JpegInfoReader : ImageInfoReader
     {
         private static readonly byte[] APP0Identifer = Encoding.ASCII.GetBytes("JFIF\0");
         private static readonly byte[] APP1Identifer = Encoding.ASCII.GetBytes("Exif\0\0");
+        private static readonly byte[] APP2Identifer = Encoding.ASCII.GetBytes("Adobe\0");
 
         protected override bool CheckHeader(Stream stream)
         {
@@ -32,6 +33,8 @@ protected override bool CheckHeader(Stream stream)
                         return IsIdentifier(stream, APP0Identifer);
                     case Marker.APP1:
                         return IsIdentifier(stream, APP1Identifer);
+                    case Marker.APP2:
+                        return IsIdentifier(stream, APP2Identifer);
                     default:
                         stream.Position += length;
                         break;
@@ -128,6 +131,7 @@ private static class Marker
             public const ushort SOI = 0xFFD8;
             public const ushort APP0 = 0xFFE0;
             public const ushort APP1 = 0xFFE1;
+            public const ushort APP2 = 0xFFEE;
             public static readonly ushort[] SOFx = new ushort[] { 0xFFC0, 0xFFC1, 0xFFC2, 0xFFC3, 0xFFC5, 0xFFC6, 0xFFC7, 0xFFC9, 0xFFCA, 0xFFCB, 0xFFCD, 0xFFCE, 0xFFCF };
         }
 

```

**Comment by igitur** [comment]
Kindly submit the patch as a pull request with test cases.
