### ISSUE TITLE
Symbol files for ClosedXML are missing from Nuget

### ISSUE THREAD

**Issue by zclimber** [ClosedXML/ClosedXML#2070]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.101.0

**What is the current behavior?**

Symbols are missing from Nuget download server.

**What is the expected behavior or new feature?**

Symbols are present at Nuget download server.

**Is this a regression from the previous version?**

Symbols were present in nuget package for v0.96.0

## Reproducibility

Status for v101 https://nuget.info/packages/ClosedXML/0.101.0
Status for v96 https://nuget.info/packages/ClosedXML/0.96.0 - packets are present in nuget package, though not in nuget symbol server.
Also, you can try to download symbols with dotnet-symbols:
```
dotnet-symbol --server-path https://symbols.nuget.org/download/symbols ClosedXML.dll
Downloading from https://symbols.nuget.org/download/symbols/
ERROR: 403 Forbidden: ClosedXML.pdb - 'https://symbols.nuget.org/download/symbols/closedxml.pdb/b5c4abaffdd049d5ac7ba9c901391a3cFFFFFFFF/closedxml.pdb'
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
![image](https://github.com/ClosedXML/ClosedXML/assets/7634052/031394a1-10ba-40a9-8beb-01c0f9c6fa7a)

It seems Fody screws up PDB checksums (https://github.com/jbevain/cecil/issues/610).

**Comment by MagicAndre1981** [comment]
add [DotNet.ReproducibleBuilds](https://github.com/dotnet/reproducible-builds#dotnetreproduciblebuilds-nuget-package) which enables reproducible builds and embedded the PDBs with source link:

```
<ItemGroup>
  <PackageReference Include="DotNet.ReproducibleBuilds" Version="1.1.1" PrivateAssets="All"/>
</ItemGroup>
```

**Comment by jahav** [comment]
Ok, let's hope it works. At least the package now includes pdb and should point to github sources.

This was rather frustrating experience... hard to test it locally (at least I couldn't) and dubious benefits of Source Link. Gain smaller size of pdb and in exchange hope that third party service (github) never goes down.... Way of the future I guess.

![image](https://github.com/ClosedXML/ClosedXML/assets/7634052/175a6a24-1228-4c48-938b-9cf9a50725db)

**Comment by arashberlin** [comment]
Hi, when you plan to release the v0.104?
