### ISSUE TITLE
When opening and then saving an existing macro enabled excel file, VBA code get lost.

### ISSUE THREAD

**Issue by vecale** [ClosedXML/ClosedXML#2077]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No
 

**Version of ClosedXML**

0.101.0

**What is the current behavior?**
When opening and then saving an existing macro enabled excel file, VBA code get lost. 

**What is the expected behavior or new feature?**
The code should create a file ("functionally") identical to the original one.

**Is this a regression from the previous version?**
I obtain the same behavior using v0.96 or v0.97 too (maybe Microsoft 365 uses some kind of different specifications for VBA format? I haven't found a way to export the workbook in previous version of Excel, e.g. 2019 or prior).

## Reproducibility 
**Code to reproduce problem:**
```c#
public void Main()
{
  var tpt_m = "D:\\tmp\\closedXML\\tpt_macro.xlsm";
  var outFile_m = "D:\\tmp\\closedXML\\generatedReport_macro.xlsm";
  
  using (var workbook = XLWorkbook.OpenFromTemplate(tpt_m))
  {
      workbook.SaveAs(outFile_m);
  }
}
```

- [x] I attached a sample spreadsheet
The zip archive (xlsm format is not allowed) contains both tpt_macro.xlsm and generatedReport_macro.xlsm
[closedXML_VBA_missingCode.zip](https://github.com/ClosedXML/ClosedXML/files/11355088/closedXML_VBA_missingCode.zip)

**Comment by jahav** [comment]
Don't use `XLWorkbook.OpenFromTemplate` that is for excel template (xlst) files, not excel files with macros (xlsm).

When I just save it the normal way, it the output file contains vba.
```csharp
using (var workbook = new XLWorkbook(tpt_m))
            {
                workbook.SaveAs(outFile_m);
            }
```

**Comment by jahav** [comment]
I am closing the issue because I think that solves the problem, it it doesn't please reopen.
