### ISSUE TITLE
IXLDataValidation.Date.EqualOrGreaterThan does not work properly with DateTime.Now

### ISSUE THREAD

**Issue by maslewandowski** [ClosedXML/ClosedXML#2122]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.102.0

**What is the current behavior?**

`IXLDataValidation.Date.EqualOrGreaterThan(DateTime.Now)` in excel file throws message, that date is not valid, right after i created the excel file.

**What is the expected behavior or new feature?**

I would expect the EqualOrGreatherThan method to accept the value that I insert in the cell right after excel file creation.

**Is this a regression from the previous version?**

No

## Reproducibility
**Code to reproduce problem:**
```c#
var deliveryDateColumnDataValidation = dataTable.Column("Q").CreateDataValidation();
deliveryDateColumnDataValidation.Date.EqualOrGreaterThan(DateTime.Now);
deliveryDateColumnDataValidation.ErrorStyle =XLErrorStyle.Warning;
deliveryDateColumnDataValidation.ErrorTitle = "Bitte Format beachten!";
deliveryDateColumnDataValidation.ErrorMessage = "Bitte geben Sie ein Datum ein, größer oder gleich heute.";
```

- [x] I attached a sample spread sheet.  (You can drag files on to this issue)
![bug_closed_xml](https://github.com/ClosedXML/ClosedXML/assets/119415167/4554dfaa-7fc8-4bb9-938f-a002a6c047d1)

**Comment by jahav** [comment]
I believe that this is correct behavior. `deliveryDateColumnDataValidation.Date.EqualOrGreaterThan(DateTime.Now)` will create a data validation that date times should be after current time, e.g. 2023-10-26 16:41. The entered date value without time is at midnight, i.e. 2023-10-26 00:00 which is before the referenced date and thus Excel will correctly complain that datetime is not equal or greater to referenced value.

In such cases `deliveryDateColumnDataValidation.Date.EqualOrGreaterThan(DateTime.Now.Date)` would be a better choice to achieve the desired result.
