### ISSUE TITLE
Error as System.NotImplementedException : The method or operation is not implemented when reading excel file size bigger than 500kb

### ISSUE THREAD

**Issue by ToeToeAung** [ClosedXML/ClosedXML#2137]
I am encountering the error System.NotImplementedException : The method or operation is not implemented when reading excel file size bigger than 500kb. The code that I am using is as below. Getting exception in this line - using (var stream = excelFile.OpenReadStream()) when the excel file size is bigger. If I tested the file size as 140kb, it is working fine. 

if (excelFile != null && excelFile.Length > 0)
{
bool isValidRow = true;
using (var stream = excelFile.OpenReadStream())
{
using (var workbook = new XLWorkbook(stream))
{
stream.Position = 0;
var worksheet = workbook.Worksheet(sheetName);
}
}
}

**Comment by jahav** [comment]
Closing due to not following template.
