### ISSUE TITLE
how can I preserve the leading single quote/apostrophe of a grid cell when reading in a file?

### ISSUE THREAD

**Issue by michaelgorman** [ClosedXML/ClosedXML#2145]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [ ] Feature
- [X ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [ X] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.1

**What is the current behavior?**

When reading in an excel file, how can I preserve the leading single quote/apostrophe of the cell value? I know the leading quote has special meaning and forces the cell to be formatted as a string but is there anyway to preserve it other than doubling up the quote?

**What is the expected behavior or new feature?**

Preserve single quote

**Is this a regression from the previous version?**

no

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

I'm grabbing the value from:  cell.GetValue<String>(); after opening the file

**Code to reproduce problem:**
```c#
 I'll add a complete sample if someone tells it is possible
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
Use `IncludeQuotePrefix` property of the style to check for the quote. Tha value itself won't contain the quote.
```csharp
var wb = new XLWorkbook(@"c:\Temp\Issues\2145\quoted.xlsx");
var ws = wb.Worksheets.First();
var cell = ws.Cell("A1");
Console.WriteLine("Value: {0}", cell.Value);
Console.WriteLine("Quote prefix: {0}", cell.Style.IncludeQuotePrefix);
```

[quoted.xlsx](https://github.com/ClosedXML/ClosedXML/files/12309812/quoted.xlsx)

**Comment by michaelgorman** [comment]
Thank @jahav might be a good to add this example to the cell value documentation
