### ISSUE TITLE
Add async overloads for file operations

### ISSUE THREAD

**Issue by fjmorel** [ClosedXML/ClosedXML#2147]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.102.0

**What is the current behavior?**

When saving a workbook, it happens synchronously. If I try to write directly to the response stream in ASP.NET Core, I get a runtime exception unless I run this on the HttpContext:
```csharp
HttpContext.Features.GetRequiredFeature<IHttpBodyControlFeature>().AllowSynchronousIO = true;
```

**What is the expected behavior or new feature?**

I would like async overloads of SaveAs (and other workbook methods if appropriate) that work with streams/files asynchronously.

**Is this a regression from the previous version?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
This has to be pasted into a controller, not a simple console application.
```c#
[HttpPost("export")]
public ActionResult ExportToExcel()
{
    // this line is currently necessary, but I would like to remove it and have a "SaveAsAsync" instead
    HttpContext.Features.GetRequiredFeature<IHttpBodyControlFeature>().AllowSynchronousIO = true;
    // skipping lines to set file name and mime type on response headers
    var workbook = new XLWorkbook();
    // skipping lines to add data
    workbook.SaveAs(HttpContext.Response.Body);
    return Empty;
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
Hi, this is not possible to do without support of dependencies. System.IO.Package (two levels down) doesn't support async and neither does OpenXML SDK (direct dependency), see https://github.com/dotnet/Open-XML-SDK/issues/913 https://github.com/dotnet/Open-XML-SDK/issues/1490#issuecomment-1631624202

I don't think it's possible to do at this time and thus I am closing the issue.

**Comment by Phen-Ro** [comment]
Is there interest in reopening this issue?  Based on that first Open XML SKD link, async overloads are available as of last year.
