### ISSUE TITLE
XLConditionalFormat CopyFrom NULL exception

### ISSUE THREAD

**Issue by mzdunio** [ClosedXML/ClosedXML#215]
When copying conditional format as part of column being deleted null exception occures in the described below situation.

Worksheet has conditional formatting for some columns - it's 3-color scale formatting with the following settings: 

![edit-formatting-rule](https://cloud.githubusercontent.com/assets/26089239/23407998/af930042-fdc6-11e6-888c-5a638f51a728.png)

Exception is thrown at line 112 of XLConditionalFormat:
`other.Values.ForEach(kp => Values.Add(kp.Key, new XLFormula(kp.Value)))`

kp.Value is NULL for in the formula value for the first and third color in scale formatting. As a result wrong constructor of XLFormula is called (ctor XLFormula(string) should be called while XLFormula(XLFormula defaultFormula) is currently being called))

**Comment by igitur** [comment]
Please post fully reproducible code and test file.

**Comment by Pankraty** [comment]
It's been 15 months with no reaction. @igitur shall we close it?

**Comment by igitur** [comment]
Yup
