### ISSUE TITLE
Faster way to search for text

### ISSUE THREAD

**Issue by igitur** [ClosedXML/ClosedXML#216]
http://stackoverflow.com/questions/42422305/is-it-possible-to-perform-a-find-in-excel-using-closedxml

**Comment by Pyropace** [comment]
let me look into this

**Comment by vbjay** [comment]
One thought is to search the shared strings table and if found, find all
cells with that found index and t=s.

**Comment by igitur** [comment]
ClosedXML doesn't keep a copy of the shared strings table. The OpenXML data is copied into new objects.

**Comment by Pyropace** [comment]
@igitur @vbjay , well i am starting off with     

`internal class XLCellsCollection`, i think there is room for optimization there

**Comment by vbjay** [comment]
With  https://github.com/morelinq/MoreLINQ and
https://www.dotnetperls.com/asparallel we could speed things up.

**Comment by vbjay** [comment]
Or with Rx extensions we could create a cell searcher that they can
subscribe to and it tells them when a value is found.

**Comment by igitur** [comment]
Just keep planned support for .NET Standard in mind.

**Comment by vbjay** [comment]
https://github.com/Reactive-Extensions/Rx.NET/issues/174

**Comment by Pyropace** [comment]
![image](https://cloud.githubusercontent.com/assets/88437/24662585/7359f9c8-1923-11e7-8edf-b7389c8a82c0.png)

we can probably be smarter here lol

**Comment by vbjay** [comment]
That begs the question, does int cover the max row count?

**Comment by vbjay** [comment]
Found it.
https://support.office.com/en-us/article/Excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3?ui=en-US&rs=en-US&ad=US&fromAR=1
