### ISSUE TITLE
Use of System namespace seems inappropriate and causes problems

### ISSUE THREAD

**Issue by GregSmalter** [ClosedXML/ClosedXML#2163]
I recently suffered from [Issue 2133](https://github.com/ClosedXML/ClosedXML/issues/2133), which was resolved, in a way, [here](https://github.com/ClosedXML/ClosedXML/pull/2134/files).

However, while this fixes the problem, I think the problem could have been avoided had the System namespace not been used at all, and I think that is still a better direction to go. I don't think adding code to the System namespace is appropriate. And if the motivation is to make it so these extension methods are easy to discover even without adding using statements, a better solution would be GlobalUsings.

https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/extension-methods
https://softwareengineering.stackexchange.com/questions/57294/adding-to-the-system-namespace-in-c

**Comment by jahav** [comment]
Using extension method in System namespace is a standard mechanism for polyfill of APIs present in NETStandard 2.1, but not Netstandard 2.0. There are several packages for polyfills, haven't decided which one is the suitable one.
