### ISSUE TITLE
SixLabors.Fonts v2.0.0

### ISSUE THREAD

**Issue by stefannikolei** [ClosedXML/ClosedXML#2168]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.102.1

**What is the current behavior?**

Currently ClosedXml targets SixLabors.Fonts v1.0.0 and is build against .NETStandard 2.0 and 2.1

**What is the expected behavior or new feature?**

What is the way forward?  Sixlabors.Fonts 2.0.0 targets .NET6 only. So ClosedXml can not use this version. This will prevent users to update to any Sixlabors package to the newest version (ImageSharp v3, ImageSharp.Drawing v2, Fonts v2)

Are there any plans to just target .NET6 or soon .NET8?

**Comment by jahav** [comment]
I want to keep targeting netstandard2.0. Don't know yet what I am gonna do (possibly depend on SkiaSharp).

 I knew fonts were eventually follow ImageSharp with split license and net6, but I thought I would have more time. It was nearly a year from beta19 to 1.0.

**Comment by hagaygo** [comment]
> I want to keep targeting netstandard2.0. Don't know yet what I am gonna do (possibly depend on SkiaSharp).
> 
> I knew fonts were eventually follow ImageSharp with split license and net6, but I thought I would have more time. It was nearly a year from beta19 to 1.0.

@jahav 

Hi

We have a project that uses .net 4.8 and we can not update the dependency of Sixlabors.Fonts to 2.X because it does not support it.
For now we keep on keeping Sixlabors.Fonts on version 1.

Is there any chance the dependcy could change to a package that keeps targeting .net standard ?

Thanks.
