### ISSUE TITLE
Conditional formatting to stop when true

### ISSUE THREAD

**Issue by igitur** [ClosedXML/ClosedXML#217]
http://stackoverflow.com/questions/42008831/closedxml-c-sharp-how-to-get-conditional-formating-for-excel-to-stop-when-true

**Comment by NickNack2020** [comment]
@igitur I am currently taking a stab at this.

**Comment by igitur** [comment]
Waiting for @NickNack2020  to clean up the conflicts in his PR.

**Comment by igitur** [comment]
https://www.nuget.org/packages/ClosedXML/0.90.0-beta2 is released and should include the fix for this issue.

**Comment by igitur** [comment]
I'm relooking at this. Am I right that there's no way the user can *get* the `StopIfTrue` value? The property is internal.
