### ISSUE TITLE
Formula with Datetime-Input should handle blank as error / no throw of 'Null object cannot be converted to a value type.'

### ISSUE THREAD

**Issue by georgheimltwat** [ClosedXML/ClosedXML#2179]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.102.1

**What is the current behavior?**

- Formula "=YEAR(A1)" ,where A1 is blank, throws an exception 'Null object cannot be converted to a value type.'

**What is the expected behavior or new feature?**

- Result of the formula should be XLError.NoValueAvailable

**Is this a regression from the previous version?**

No, 0.101.0 has same problem

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
        var wb = new XLWorkbook();
        var ws = wb.AddWorksheet();
        ws.Cell("A1").Value = Blank.Value;
        ws.Cell("A2").FormulaA1 = @"=YEAR(A1)";
        //Exception: 'Null object cannot be converted to a value type.'
        var valueA2 = ws.Cell("A2").Value;
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
Fixed in #2180. YEAR has been reimplemented from legacy function and null to DateTime for legacy functions now returns an equivalent of 0 serial date time (that is behavior more in line with most functions).
