### ISSUE TITLE
Cannot open existing Excel File

### ISSUE THREAD

**Issue by bwiltfong** [ClosedXML/ClosedXML#219]
I'm trying to open an existing Excel file and can't get past the "Using" statement below.

That line returns the following error:

Object reference not set to an instance of an object.

        Dim ExcelFile As New FileInfo("E:\Temp\AgingReport.xlsx")

        Try
            Using workbook As New XLWorkbook(ExcelFile.FullName)
                Dim ws = workbook.Worksheet("Data")

Can you please let me know what I need to do to fix this issue?

Thanks,
Bob

**Comment by bwiltfong** [comment]
My Excel file had a chart and a pivot table. I tried deleting these sheets one at a time and it still didn't work. When I deleted both, I was able to modify the workbook.

**Comment by igitur** [comment]
Please attach the file.

**Comment by bwiltfong** [comment]
The excel file with the pivot table is what I am trying to accomplish with the data. At first, I was trying to create another sheet with my pivot table but when I set the file name, I got the error.

The following is my application in Visual Basic. Can you please help me get the pivot table set up like the attached spreadsheet?

        Dim ExcelFile As New FileInfo("AgingReport - DataOnly.xlsx")

        Try
            Using workbook As New XLWorkbook(ExcelFile.FullName, XLEventTracking.Enabled)
                Dim ws = workbook.Worksheet("Data")
                Dim header = ws.Range(1, 1, 1, 3)
                Dim dataRange = ws.Range(header.FirstCell(), ws.Cell("D442"))

                Dim ptSheet = workbook.Worksheets.Add("BobsPivot")
                Dim pt = ptSheet.PivotTables.AddNew("BobsPivot", ptSheet.Cell(1, 1), dataRange)

                pt.SetClassicPivotTableLayout(True)
                pt.SetShowValuesRow(True)

                pt.RowLabels.Add("CustomerName")

                pt.ColumnLabels.Add("Month")

                pt.Values.Add("CustomerName", "#Pallets")
                pt.Values.Add("Age", "#Months")

                ptSheet.Columns().AdjustToContents()

                workbook.Save()
            End Using
        Catch ex As Exception
            MessageBox.Show(ex.ToString)

            End
        End Try

Thanks,
Bob

**Comment by bwiltfong** [comment]
In the previous email, there was an attachment with DataOnly in the name. I forgot to take out the pivot table and the chart.

**Comment by igitur** [comment]
Github comments via email don't post the attachments. Please open this issue in your browser and attach the file.
