### ISSUE TITLE
Save Existing Excel file: File gets corrupted

### ISSUE THREAD

**Issue by krishnaps1592** [ClosedXML/ClosedXML#220]
I am trying to update data in my excel file created using closed xml using c# code. What I  observed is that when I save the file after making the desired changes, the file becomes unreadable. The reason that I found out was that the workbook.Save() method creates an duplicate 
entry in the workbook.xml file under the sheet node.
<x:sheet r:id="rId2" sheetId="2" name="My Data"/>

Also by default, when an excel file is created using the sheet name, the default sheet id in the workbook.xml under the sheets node is 2.

**Comment by igitur** [comment]
You closed this issue. Can I assume that it's solved?

**Comment by krishnaps1592** [comment]
Yes. It is solved. It was my misunderstanding on the usage. Sorry about
that.
