### ISSUE TITLE
Non-existent sheet appears in VBA window

### ISSUE THREAD

**Issue by TYasuhiro** [ClosedXML/ClosedXML#2200]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.103.0 -beta

**What is the current behavior?**

If I delete a sheet from an xlsm file, looks the sheet information become incorrect.
The sheet that was supposed to be deleted appears in the 'Project Explorer' of the VBA Window.

**What is the expected behavior or new feature?**

The contents of 'Project Explorer' are displayed correctly.

**Is this a regression from the previous version?**

I haven't used previous versions

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
  ClosedXML.Excel.XLWorkbook workbook = new ClosedXML.Excel.XLWorkbook("test.xlsm");
  ClosedXML.Excel.IXLWorksheet s1 = workbook.Worksheet("sheet1");
  s1.CopyTo(workbook, "sheet99");
  s1.Delete();
  workbook.Save();
  workbook.Dispose();
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[test.zip](https://github.com/ClosedXML/ClosedXML/files/13065408/test.zip)
![image](https://github.com/ClosedXML/ClosedXML/assets/144971411/284d9cf2-b39f-46bd-b75c-633a1902f495)

**Comment by jahav** [comment]
The VBA project is a part of xlsm. It consists of several (document) modules, per sheet. The document module references the sheet, even though it was deleted. Excel likely removes document module when sheet is removed, but ClosedXML doesn't. It would require parser of VBA project and significant work. It's not really something I consider to be in scope of the project at this time.

For more info, see [[MS-OVBA].pdf](https://msopenspecs.azureedge.net/files/MS-OVBA/%5bMS-OVBA%5d.pdf)

**Comment by TYasuhiro** [comment]
jahav, thank you for reply. I understood it.
Also, I don't think this is really a fatal bug and I'm not really concerned about it.
