### ISSUE TITLE
Numbers always formatted as Text

### ISSUE THREAD

**Issue by afabri73** [ClosedXML/ClosedXML#2217]
Hi,
I have problem with format cells when export to an xlsx files.

This is my code (cellValue is a string)

`xlsxWorkSheet.Cell(currentRow, 10).SetValue(cellValue);
xlsxWorkSheet.Cell(currentRow, 10).Style.NumberFormat.SetFormat("0.00");`

When I open the file, the cell format is correctly number, but I see the attention icon that tell me that the number is stored as Text (see attached image).
Infact the number is alligned to the left of the cell.
If I click on the bar to edit the value and confirm (without any modify), the number will be correctly formatted as a number and aligned to the right.

![Screenshot 2023-11-17 173847](https://github.com/ClosedXML/ClosedXML/assets/6714121/11fc3f0c-59f0-4567-afa7-88354c5e9576)

Can anyone give me support?
I'm using ClosedXML v0.102.0

Thank you
Adriano

**Comment by jahav** [comment]
Not using template. Closing.

**Comment by afabri73** [comment]
Hi Jahav,
sorry but I didn't understand what you mean (but I'm glad to see that your comment makes a smile).
This is the first time I use ClosedXML and I kindly ask you to explain what you mean

Thank you
Adriano

**Comment by Tasmanakos** [comment]
You have not used the Template to report the Issue
Use the Template when you open an Issue and provide information to the requested points.

![image](https://github.com/ClosedXML/ClosedXML/assets/80647048/fe364485-441d-4705-835f-9533ea1b6b05)

**Comment by igitur** [comment]
And it was me who smiled.
