### ISSUE TITLE
Columns().AdjustToContents(1, 20) - Performance regression

### ISSUE THREAD

**Issue by Pitterling** [ClosedXML/ClosedXML#224]
Hi,
i just upgraded from 0.80 to 0.86 and figured out that my program runs now several seconds longer then before - i was able to nail it down to the 

`Worksheet.Columns.AdjustToContents(1, 20)`

Statement, which has been touched in 0.85 to fix #77 
I already restricted to the first 20 lines in order to avoid long runtimes (my excels are huge).

Thanks,
P.

**Comment by igitur** [comment]
Can you attach a sample file?

**Comment by Pitterling** [comment]
will compile something - my file contains sensitive data.

**Comment by igitur** [comment]
Please pull in #232 and let me know if it solves the performance issues.

**Comment by Pitterling** [comment]
@igitur thanks .. i will have a look .. i'm short on time at the moment.

**Comment by igitur** [comment]
Can we close this?

**Comment by Pitterling** [comment]
@igitur i'm not able to reproduce it. Obviously i was completely wrong. Thanks to look into this anyway.
Indeed InsertRowsBelow and InsertData are slower compared to v0.80.

**Comment by igitur** [comment]
There is an existing PR that will speed up InsertData

**Comment by Pitterling** [comment]
@igitur Which PR is it? Based on the description i could not find it. Furthermore in my case InsertRowsBelow takes twice as long as InsertData .. is this addressed too?

**Comment by igitur** [comment]
I'm referring to #210 . If there is a problem with `InsertRowsBelow`, please address it in a separate issue.
