### ISSUE TITLE
Support for structured table references in formula evaluation

### ISSUE THREAD

**Issue by ronimizy** [ClosedXML/ClosedXML#2247]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.102.1

**What is the current behavior?**

When trying to evaluate value of cell with structured table reference in formula, the exception occurs 

```
Unhandled exception. System.NotImplementedException: Evaluation of structured references is not implemented.
   at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, StructuredReferenceNode node)
   at ClosedXML.Excel.CalcEngine.StructuredReferenceNode.Accept[TContext,TResult](TContext context, IFormulaVisitor`2 visitor)
   at ClosedXML.Excel.CalcEngine.CalcEngine.EvaluateFormula(String expression, CalcContext ctx)
   at ClosedXML.Excel.CalcEngine.CalcEngine.EvaluateFormula(String expression, XLWorkbook wb, XLWorksheet ws, IXLAddress address)
   at ClosedXML.Excel.XLCellFormula.CalculateNormalFormula(String fA1, XLCell cell)
   at ClosedXML.Excel.XLCellFormula.ApplyFormula(XLCell cell)
   at ClosedXML.Excel.XLCell.Evaluate(Boolean force)
   at ClosedXML.Excel.XLCell.get_Value()
   at Program.<Main>$(String[] args) in /Users/george/Documents/C#/Playground/ConsoleApp1/Program.cs:line 18
```

**What is the expected behavior or new feature?**

1. Structured references should be evaluated, and its values should be used in formula evaluation.
2. `Main()` snipped should not throw 

**Is this a regression from the previous version?**

No

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
    var workbook = new XLWorkbook();
    var worksheet = workbook.AddWorksheet("test");

    worksheet.Cell("A1").Value = "Name";
    worksheet.Cell("B1").Value = "Value";

    worksheet.Cell("A2").Value = "Text";
    worksheet.Cell("B2").FormulaA1 = "Table[#This Row, Name]";

    worksheet.Range("A1:B2").CreateTable("Table");

    Console.WriteLine(worksheet.Cell("B2").Value);
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by ronimizy** [comment]
I would be glad to contribute to this feature implementation

**Comment by jahav** [comment]
Note that `SUBTOTAL` function used in totals row of table can be considered working in the most loose term of the word (e.g. counts even hidden values, likely works only on numbers and so on).

**Comment by ronimizy** [comment]
@jahav hello, can you provide any estimate on this feature being released to NuGet?

**Comment by BloodNTear** [comment]
> @jahav hello, can you provide any estimate on this feature being released to NuGet?

if you are using nuget version and cannot retrieve information from a cell using a formula maybe you can try this approach: using CachedValue, the result of the formula will be stored at CachedValue. Here's an example:

string unitID;
var tryGetUnitID= workSheet.Cell(i, 1).TryGetValue(out untiID);
if (!tryGetUnitID)
{
				untiID= workSheet.Cell(i, 1).CachedValue.ToString();
}

**Comment by michsco** [comment]
@jahav -- circling back to this to see if there is any idea of when this will be released?

**Comment by jahav** [comment]
@michsco See https://github.com/ClosedXML/ClosedXML/issues/2357

**Comment by ronimizy** [comment]
@jahav hi, release of this feature is highly desirable and going to save a lot of time. what tasks are holding it back? can I offer any help to speed up this process?
