### ISSUE TITLE
Upgrade OpenXML to v2.7.1

### ISSUE THREAD

**Issue by Pitterling** [ClosedXML/ClosedXML#225]
Hi,

in the meantime OpenXML 2.7.1 has been released.

[Open-XML-SDK @Github ](https://github.com/OfficeDev/Open-XML-SDK)
[Nuget package](https://www.nuget.org/packages/Joelharkes.DocumentFormat.OpenXml/2.7.1)

Any plans to upgrade to 2.7.1?

Thx,
P.

**Comment by igitur** [comment]
What are the benefits of upgrading?
And is .NET 3.5 supported?

**Comment by Pitterling** [comment]
[Open-XML-SDK changes](https://github.com/OfficeDev/Open-XML-SDK#change-log)
mainly fixes and newer .NET versions

it seems that minimum .NET release is now 4.5. Why is .NET3.5 still required?

**Comment by igitur** [comment]
Some people are still on .NET 3.5. I don't have metrics of how many, but recently a commenter on an issue mentioned he is on .NET 3.5.

**Comment by twsouthwick** [comment]
If you're interested in support for .NET 3.5, we can definitely take a look at adding it. We're hoping to consolidate on one package to simplify dependency management, and if .NET 3.5 is needed, we can have a discussion on that.

**Comment by twsouthwick** [comment]
Is .NET 3.5 support a blocker for updating to the latest DocumentFormat.OpenXML? It will bring .NET Standard support so you can take your library to .NET Standard as well. I have a PR to support .NET 3.5, but at the moment, the .NET CLI doesn't understand .NET 3.5 and so we'll have to change our build process. So, the question is, how big of a user base are still using .NET 3.5 and how firm is the need to support it?

**Comment by igitur** [comment]
@twsouthwick Yes, that is a blocker.

Figuring out how many users actually use the .NET 3.5 is exactly what has been keeping me busy recently. I was hoping NuGet would have some metrics on the issue, but, unless I'm mistaken, that level of detail isn't stored. 

The only measure I have currently is based on feedback from users in the comments in the issues here on Github. 

My personal biased view is that there are more benefits in supporting .NET standard than supporting .NET 3.5, so if it has to come down to a choice, I'd go with .NET standard. I also consider `ClosedXML` as pre-v1 and don't feel we have to be as stable as post-v1 libraries, but I don't want to alienate users.

Looking for feedback from anybody...

**Comment by twsouthwick** [comment]
Unfortunately, NuGet does not provide that at the moment. I created an issue here https://github.com/NuGet/NuGetGallery/issues/3450 a couple of months ago as another project was wondering the same thing (but for .NET Framework 4.0)

**Comment by igitur** [comment]
@ManuelDeLeon Can we take ownership of DocumentFormat.OpenXML on NuGet please?

**Comment by SimonTestNet** [comment]
Sorry for the delay. I added both of you (igitur & Pyropace)

**Comment by igitur** [comment]
See #292 for upgrading of OpenXML. Does anyone have to nice new features that we can easily take advantage of?

**Comment by igitur** [comment]
In the meantime, the artifacts at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.271/artifacts may be tested. @Pitterling , I assume you'd want to.

**Comment by PhilPJL** [comment]
When do you think the next release with 2.7.1 will be?

**Comment by vbjay** [comment]
Let me introduce you to milestones. https://github.com/ClosedXML/ClosedXML/milestones

**Comment by PhilPJL** [comment]
Thanks 👍

**Comment by igitur** [comment]
Fixed in #225

**Comment by igitur** [comment]
Fixed in #292
