### ISSUE TITLE
Formula Text excel different behavior

### ISSUE THREAD

**Issue by devel0** [ClosedXML/ClosedXML#226]
with excel enter follow cells:
```
A1 : 211x
B1 : Text(A1, "#00")
```

of course we expect a inconsistent source from A1 because we want to format value in B1 as a number, and using ClosedXML I got 00 number, but this differs from what I have from and excel spreadsheet that results in 211x.

May the expected behavior of an inconsistent source type in formatting with Text formula is to get the source value itself instead to squeeze it into a 0 number ?

**Comment by igitur** [comment]
The PR has been merged into the `develop` branch. I'd appreciate it if you could pull the `develop` branch and check that it solves your issue. Thanks.

**Comment by devel0** [comment]
I confirm it worked either with numeric values 1 -> 01, 100 -> 100 and string "211x" -> "211x"

![image](https://cloud.githubusercontent.com/assets/13405008/24096872/b7266838-0d63-11e7-8092-7a6bcafdafec.png)

test

![image](https://cloud.githubusercontent.com/assets/13405008/24096919/ee26b414-0d63-11e7-9405-976bbe6c0fba.png)

thanks
