### ISSUE TITLE
Remove references to "System.Net.Http" and "System.Text.RegularExpressions"

### ISSUE THREAD

**Issue by Arjan321** [ClosedXML/ClosedXML#2265]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**
`0.104.0-preview2`

**What is the current behavior?**
Because of [this commit](https://github.com/ClosedXML/ClosedXML/commit/ce6ce6a11324dbbe25ccdc209520d66893b3d418#diff-1e6758ed2a0ed27e66cb0c73f876f6909cf3552bda17d548b01aa3f0058a8188) the dependency on [`XLParser v1.5.2`](https://www.nuget.org/packages/XLParser/1.5.2#dependencies-body-tab) has been removed. This package brought in the `NETStandard.Library v1.6`, which in turn brought in the (vulnerable versions of) `System.Net.Http` and `System.Text.RegularExpressions`.

Now that `XLParser` is gone, these explicit upgrades of these packages can also be safely removed from `ClosedXML`. 

**What is the expected behavior or new feature?**
No more dependency on `System.Net.Http v4.3.4` and `System.Text.RegularExpressions v4.3.1`.

**Is this a regression from the previous version?**
No

**Comment by Arjan321** [comment]
For reference, here are two `packages.lock.json` files. One with the explicit reference from `ClosedXml`, and one with the explicit references removed.
[packages.lock-before.json](https://github.com/ClosedXML/ClosedXML/files/13977657/packages.lock-before.json) (41kb)
[packages.lock-after.json](https://github.com/ClosedXML/ClosedXML/files/13977658/packages.lock-after.json) (2kb)

**Comment by rgroenewoudt** [comment]
@jahav Would it be possible to release a new preview nuget package? We are running into this issue in which the old packages are flagged.
