### ISSUE TITLE
Move a row instead of InsertRowsAbove() to improve efficiency?

### ISSUE THREAD

**Issue by r-liciotti** [ClosedXML/ClosedXML#2295]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [X] No

Since inserting a new row/column has a big impact, is it possible to move an empty row/column from unused space to where we want to insert a new row/column?

**Comment by jahav** [comment]
No. Isn't possible for columns at all in current structure (see #1969). Rows could be swapped, but there is it's not something planned in near future.
