### ISSUE TITLE
Sort(3);  does not work on sheets

### ISSUE THREAD

**Issue by rogersbrad** [ClosedXML/ClosedXML#23]
Created an Excel file with 11 worksheets, had set the worksheets

` var wb = new XLWorkbook();
 var ws1 = wb.Worksheets.Add("Da
 var ws2 = wb.Worksheets.Add("S
 var ws3 = wb.Worksheets.Add("H
 var ws4 = wb.Worksheets.Add("W
 var ws5 = wb.Worksheets.Add("W
 var ws6 = wb.Worksheets.Add("R
 var ws7 = wb.Worksheets.Add("B
//and set some values
 ws.Cell("A" + c).Value = Pr
 ws.Cell("B" + c).Value = Pr
 ws.Cell("C" + c).Value = Na
 ws.Cell("D" + c).Value = pr
 ws.Cell("E" + c).Value = St
 ws.Cell("F" + c).Value = Sc
 ws.Cell("G" + c).Value =  t
 ws.Cell("H" + c).Value = Pa
 ws.Cell("I" + c).Value = Pw
 ws.Cell("J" + c).Value = Nu
 ws.Cell("K" + c).FormulaR1C
 ws.Cell("L" + c).Value = Wo
 ws.Cell("M" + c).Value = Mo
 ws.Cell("N" + c).Value = Pw
 ws.Cell("O" + c).Value = Pw
 ws.Cell("P" + c).Value = "-
 ws.Cell("Q" + c).Value = "-
 ws.Cell("G" + c).Style.Numb
 ws.Cell("K" + c).Style.Numb
 ws.Cell("L" + c).Style.Numb

// and some cells have formatting
 ws.Cell("K" + c).Style.NumberFormat.Format = "0%";        // formats for percent, zero decimal places
                    ws.Cell("L" + c).Style.NumberFormat.Format = "0%";
                    ws.Cell("M" + c).Style.NumberFormat.Format = "0%";
                    ws.Cell("N" + c).Style.NumberFormat.Format = "0%";
                    ws.Cell("O" + c).Style.NumberFormat.Format = "0%";

                    ws.Cell("H" + c).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                    ws.Cell("I" + c).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                    ws.Cell("J" + c).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                    ws.Cell("K" + c).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                    ws.Cell("L" + c).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                    ws.Cell("M" + c).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                    ws.Cell("N" + c).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                    ws.Cell("O" + c).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

//then color the cells based on something else
  if ( StartDate.Contains("2009"))

                    {

                        ws2.Cell("A"  + c).Style.Fill.BackgroundColor = XLColor.AliceBlue;
                        ws2.Cell("B"  + c).Style.Fill.BackgroundColor = XLColor.AliceBlue;
                        ws2.Cell("C"  + c).Style.Fill.BackgroundColor = XLColor.AliceBlue;
                        ws2.Cell("D"  + c).Style.Fill.BackgroundColor = XLColor.AliceBlue;
                        ws2.Cell("E"  + c).Style.Fill.BackgroundColor = XLColor.AliceBlue;
                        ws2.Cell("F"  + c).Style.Fill.BackgroundColor = XLColor.AliceBlue;
                        ws2.Cell("G"  + c).Style.Fill.BackgroundColor = XLColor.AliceBlue;

//covering dates there are different colors.
                    ws2.Sort("E");
                    ws2.Sort(5, XLSortOrder.Descending, false,  true);

here, 2 sort commands added the first then second.   Previously this worked fine, several worksheets would color in row data and the sheets would sort right.
 
`

Now, all worksheets sort by column 1 no matter what Sort(n) command is there or where its placed, appears the syntax is correct yet it will not sort?

**Comment by rogersbrad** [comment]
There is another side effect, it will arbitrarily lock the rows in column 1 then put the other rows in a different order, breaking up the row data.  I had to look closely to see this.  And there was some mixup that ws.Sort(N) is 0th based, so Column A = 0, B = 1

So while the sorting took place, it was happening on a column with only Y or N, when I expected the Date to sort which wasnt happening;  but ok now it sorts on the date but still breaks up the rows, because it sorts everything on the 5th column which is ws.Sort(4);  then it goes back and forces column 1 alone into order based on those values.  If not for coloring in the rows, it would not have been found this fast.

There is no other sort command, but why would it break up the row data?  which corrupts it?

**Comment by rogersbrad** [comment]
looks like in XLColumn.cs line 565 its forcing column 1 to sort

`   public IXLColumn Sort(XLSortOrder sortOrder = XLSortOrder.Ascending, Boolean matchCase = false,
                              Boolean ignoreBlanks = true)
        {
            Sort(4, sortOrder, matchCase, ignoreBlanks);
            return this;
        }`


Like this?  my worksheet sorts perfectly.  It was set as Sort(1, sortOrder

**Comment by igitur** [comment]
If you can ensure that your code is properly formatted in your original comment, it would help a lot. Refer to https://guides.github.com/features/mastering-markdown/#examples on how to format code.

**Comment by rogersbrad** [comment]
`  var mydata = from records245 in db2.Astr
                             select records245;

             mydata = mydata.OrderBy(m => m.ItemNumber);`


Lets close this ticket.  When filling in values directly was sorting fine, I went to create a similar example reading from the database.  Then noticed this.   

I had searched back/forth for any kind of keyword "SORT"  but this is what did it.  sorry.
