### ISSUE TITLE
Error with "old" date

### ISSUE THREAD

**Issue by Benixoid** [ClosedXML/ClosedXML#2304]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.102.2

**What is the current behavior?**
Error with converting date "14-Aug-0025" to excel date.

**What is the expected behavior or new feature?**
Should be converted to Excel date 14-Aug-0025

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
                //start export to excel
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("HistoryTopics");

                //Fill header                
                worksheet.Cell(1, 1).Value = "ID";
                //.... some other headers                
                worksheet.Cell(1, 16).Value = "Topic name";
                worksheet.Cell(1, 17).Value = "Historical date";
                worksheet.Cell(1, 18).Value = "Export status";

                //Fill data
                var data = await _dataManager.HistoryTopicsService.GetTopics(SelectedStatusId, searchString).ToListAsync();
                var row = 2;
                if (data.Count == 0)
                {
                    worksheet.Cell(2, 1).Value = "No data available";
                }
                else
                {                    
                    foreach (var record in data)
                    {
                        try
                        {
                            worksheet.Cell(row, 1).Value = record.Id;
                           //some other fields to export
                            worksheet.Cell(row, 16).Value = record.topic.Name;
                            worksheet.Cell(row, 17).Value = record.Topic.Date; //Here is issue with date "14-Aug-0024";
                            worksheet.Cell(row, 17).Value = "Ok";
                        }
                        catch (Exception ex)
                        {
                            worksheet.Cell(row, 18).Value = $"Error for record id: {record.Id}, error message: {ex.Message}";
                            row++;
                        }                            
                    }
                    
                }
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by Benixoid** [comment]
error message: Not a legal OleAut date.

**Comment by igitur** [comment]
Excel doesn't support dates that go that far back. Try it yourself from the front-end. It sets it as text.

**Comment by jahav** [comment]
As @igitur mentioned, You need to convert date to string for such early dates.

The earliest date is 1900-01-01 which is a representation of a number 1 (there are no dates, only numbers masquerading/formatted as dates). Technically there is 1900-01-00 for, but day zero of a month is an Excel quirk.

**Comment by Benixoid** [comment]
Ok. Noted.
--
Отправлено из Mail.ru для Android четверг, 29 февраля 2024, 01:13AM +06:00 от Jan Havlíček  ***@***.*** :
