### ISSUE TITLE
Getting Stream was too large.

### ISSUE THREAD

**Issue by AjayT18** [ClosedXML/ClosedXML#2310]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [ x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**

0.102.2

**What is the expected behavior or new feature?**

I am getting Stream was too large issue while writing the excel with more than 10 lacks records.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
 here create the worksheet and adding data to the sheets
    using (var stream= new FileStream(savePath,FileMode.Create,FileAccess.Write))
                        {
                            workbook.SaveAs(stream);
                        }
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
Basically, open xml sdk through one of their BCL dependencies uncompressed data and memory stream can be at most 2GB large.

See also
https://github.com/dotnet/Open-XML-SDK/issues/807
https://github.com/dotnet/runtime/issues/1544

Nothing that can be done ATM.
