### ISSUE TITLE
SUMIF formula does not work for horizontal ranges

### ISSUE THREAD

**Issue by Brainman643** [ClosedXML/ClosedXML#2320]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.104.0-preview3

**What is the current behavior?**

SUMIF formula always returns 0 if horizontal range is passed. E.g SUMIF(A1:D1,300000,A2:D2)

**What is the expected behavior or new feature?**

SUMIF formula returns correct values for any dimensions.

**Is this a regression from the previous version?**

No, it's not. I also checked version 0.102.2.

## Reproducibility

**Code to reproduce problem:**
```c#
        [TestCase(33, "SUMIF(A1:D1,300000,A2:D2)")]
        public void SumIf_ReturnsCorrectValues_HorizontalRanges(int expectedOutcome, string formula)
        {
            using (var wb = new XLWorkbook())
            {
                wb.ReferenceStyle = XLReferenceStyle.A1;

                var ws = wb.AddWorksheet("Sheet1");

                ws.Cell("A1").Value = 100000;
                ws.Cell("B1").Value = 200000;
                ws.Cell("C1").Value = 300000;
                ws.Cell("D1").Value = 400000;

                ws.Cell("A2").Value = 11;
                ws.Cell("B2").Value = 22;
                ws.Cell("C2").Value = 33;
                ws.Cell("D2").Value = 44;

                Assert.AreEqual(expectedOutcome, ws.Evaluate(formula).GetNumber());
            }
        }
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[wb.xlsx](https://github.com/ClosedXML/ClosedXML/files/14842942/wb.xlsx)

**Comment by jahav** [comment]
`SUMIF` has been reimplemented in #2495 and the provided example now calculates correct value 33 even for horizontal range.
