### ISSUE TITLE
The supplied file was empty (zero bytes long)

### ISSUE THREAD

**Issue by zanyar3** [ClosedXML/ClosedXML#2326]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x]  Yes
- [ ] No

**Description:**
Attempting to asynchronously fetch a stream file, results in failure, while synchronous fetching works properly.

**Actual Behavior:**
Asynchronous fetch operation encounters an issue, unlike its synchronous counterpart.

**Version of ClosedXML**

0.102.2

When I want to fetch stream file with asynchronous happened this issue but for synchronous not happened 

**Code to reproduce problem:**
```c#
using var stream = new MemoryStream();
await file.OpenReadStream().CopyToAsync(stream);

ExcelMapper excelMapper = new();
var result = await excelMapper.FetchAsync(stream); 
// var  result = await excelMapper.Fetch(stream); // this line working 
```

**Comment by igitur** [comment]
It looks like you're using https://github.com/mganss/ExcelMapper and not this project, ClosedXML.
