### ISSUE TITLE
Master Spreadsheet with logo. Logo is distorted when saved using CloseXML

### ISSUE THREAD

**Issue by mrwrighty** [ClosedXML/ClosedXML#2339]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ X] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.102.2

**What is the current behavior?**

I use a Master spreadsheet with my App. On one page is a logo which is correctly sized in the master. After opening and writing to the master and saving as a new document the image is squashed.

**What is the expected behavior or new feature?**

Image remains unchanged

**Is this a regression from the previous version?**

Went from 0.97.0 to 0.102.2 same issue

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

There is no code, open an existing spreadsheet withC containing an image and save with Closedxml and image is distorted.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
Closing, missing reproducible example.

Tried  the
> There is no code, open an existing spreadsheet withC containing an image and save with Closedxml and image is distorted.

which doesn't produce distorted image (file created by Excel).

```csharp
using var wb = new XLWorkbook(@"c:\Temp\Issues\2339\issue2339.xlsx");
wb.SaveAs(@"c:\Temp\Issues\2339\issue2339-out.xlsx");
```
[issue2339.xlsx](https://github.com/ClosedXML/ClosedXML/files/15279228/issue2339.xlsx)
