### ISSUE TITLE
Open excel and add row

### ISSUE THREAD

**Issue by slagusev** [ClosedXML/ClosedXML#234]
Hi
For a long time already I'm suffering I can not make adding rows to the table from the sheet.
InsertData - overwrites.

**Comment by igitur** [comment]
Please explain in more detail. Try to post a sample of code of what you have tried.

**Comment by slagusev** [comment]
```
                var wb = new XLWorkbook(@"test.xlsx");
                var ws = wb.Worksheet("1");
                ws.Cell(1, 1).InsertData(el);
                wb.Save();
```
Tried this. The file is overwritten

**Comment by igitur** [comment]
Sorry, I still don't understand. The purpose of `InsertData` is to overwrite the cells with the contents of `el`. That is by design. What behaviour were you expecting?
