### ISSUE TITLE
When will there be a release with support for DocumentFormat.OpenXml 3.0.x?

### ISSUE THREAD

**Issue by SlavkaOnline** [ClosedXML/ClosedXML#2348]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**What is the expected behavior or new feature?**

When will there be a release with support for DocumentFormat.OpenXml 3.0.x? We have problems opening user files, possibly created in the latest versions of Office. The assembly compiled from the development branch works perfectly with these files.

**Comment by jahav** [comment]
When I finish pivot rework (mostly https://github.com/ClosedXML/ClosedXML/pull/2307). No timeframe.
