### ISSUE TITLE
Support System.ComponentModel.DataAnnotations

### ISSUE THREAD

**Issue by vanillajonathan** [ClosedXML/ClosedXML#2353]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.102.2

**What is the current behavior?**

Attributes used on a model fed to the `InsertTable` method have no effect.

**What is the expected behavior or new feature?**

ClosedXML should adjust output according to attributes from the `System.ComponentModel.DataAnnotations` namespace.

**Is this a regression from the previous version?**

No.

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
    var collection = new List<TestData>();
    collection.Add(new TestData
    {
        Date = DateTime.Now,
        Email = "example@example.com",
        Url = "https://www.example.com/",
    });

    using var workbook = new XLWorkbook();

    var worksheet = workbook.AddWorksheet();
    worksheet.Cell("A1").InsertTable(collection);

    workbook.SaveAs("test.xlsx");
}

public class TestData
{
    [DataType(DataType.Date)]
    public DateTime Date { get; set; }

    [DataType(DataType.EmailAddress)]
    public DateTime Date { get; set; }

    [DataType(DataType.Url)]
    public string Url { get; set; }
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
Thank you for the suggestion, but this is not something I wish to have in core library.  It's basically out of scope of the project. 

Generally speaking, ClosedXML should provide ability to determine concrete formatting, without actually doing a concrete formatting convention. E.g. `DataType.Date` has many possible formats, e.g. ISO8601, long date, short date...  Whatever choice is selected, it would be wrong for someone (plus fun with formats for different countries). Therefore ClosedXML shouldn't do it. Also, many enum values don't really make sense for formatting, e.g. `DataType.Upload`.

`IXLCell.InsertTable` should insert data, nothing more. Is user desires to fix formatting, he should set it himself.
