### ISSUE TITLE
Next release date

### ISSUE THREAD

**Issue by PSafonov** [ClosedXML/ClosedXML#2357]
@jahav Hello!
Do you have any idea what the next release date will be?

**Comment by jahav** [comment]
I am hoping within a month, though as usual, no guarantees. 

I made a significant mistake of starting a refactoring pivot tables that can't ship when it's half not done (plus as usual, other things got in a way). Should have shipped a version with OpenXML SDK 3.0 before that, but oh well...

Working on it in PR #2307. After that there are few small things, but that is the key.
