### ISSUE TITLE
Columns().AdjustToContents(1, 20) - throwing several System.Exception

### ISSUE THREAD

**Issue by Pitterling** [ClosedXML/ClosedXML#237]
Hi, my immediate window is flooded (130+) with "Exception thrown: 'System.Exception' in ClosedXML.dll" entries. This is caused by the AdjustToContents function.

![image](https://cloud.githubusercontent.com/assets/4181164/23756504/2481fa56-04e4-11e7-9b78-e76137c748bd.png)

**Comment by Pitterling** [comment]
its caused by Excel Functions in the cell like : "=[@Header7]*[@Header9]"

**Comment by igitur** [comment]
That style of table column references is not supported yet.

**Comment by igitur** [comment]
Duplicate of #271
