### ISSUE TITLE
Columns().AdjustToContents - TableHeader Column names ?

### ISSUE THREAD

**Issue by Pitterling** [ClosedXML/ClosedXML#238]
parts of the column header names are hidden by the filter button

![image](https://cloud.githubusercontent.com/assets/4181164/23761173/2fc2a47a-04f2-11e7-8ccc-65a8a78edb46.png)

i would expect the format like Excel does:
![image](https://cloud.githubusercontent.com/assets/4181164/23761200/4c36a3ae-04f2-11e7-98e6-4992da5f1b3d.png)

**Comment by Pitterling** [comment]
small example
[ClosedXML-Memory-Issues](https://github.com/Pitterling/ClosedXML-Memory-Issues)
- just adjust factor = 5000 to 500 (line 51)

**Comment by igitur** [comment]
Please upgrade your code to the latest version and try again.

**Comment by Pitterling** [comment]
@igitur downloaded latest develop branch and problem still exist, no difference compared to v0.86

**Comment by igitur** [comment]
Try the changes from #232

**Comment by Pitterling** [comment]
@igitur i try to merge the new commit within PR232 to my fork, but it is not provided ... GitHub issue with later added commits?

**Comment by igitur** [comment]
not provided?

**Comment by Pitterling** [comment]
The new commit is not offered for the for a PR
![image](https://cloud.githubusercontent.com/assets/4181164/24050329/bf0a92ae-0b2e-11e7-9e9a-de6ad454a71b.png)

**Comment by Pitterling** [comment]
my bad - wrong comparison .. need to change base and head fork :( ..

**Comment by Pitterling** [comment]
@igitur looks better now, 

![image](https://cloud.githubusercontent.com/assets/4181164/24053177/7bd01248-0b38-11e7-8764-af2e74b468b7.png)

its now even wider than excel is formatting
![image](https://cloud.githubusercontent.com/assets/4181164/23761200/4c36a3ae-04f2-11e7-98e6-4992da5f1b3d.png)

**Comment by igitur** [comment]
The goal isn't to match Excel or LibreOffice's width perfectly.

**Comment by Pitterling** [comment]
@igitur fair enough .. i don't expect it, just thought because you're touching this code anyway ...

it looks like you just add the arrow width to the widest field value -- visible at date/time column. but yeah, no real need to adjust this. Thanks.

**Comment by igitur** [comment]
When I calculated the width, I used an actual `Excel` example and `ClosedXML` and `Excel` aligned. It seems there are some cases, e.g. yours, where `Excel` calculates the width differently. It's not worth the effort to try to reverse engineer that. Anyway, the cell widths are dependent on the fonts' metrics, and we don't even have a guarantee that the fonts are installed on the user's PC.
