### ISSUE TITLE
exception thrown when trying to open Excel files with embedded 'Adobe' branded jpeg images

### ISSUE THREAD

**Issue by ctmatt** [ClosedXML/ClosedXML#2381]
Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [X] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [X] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

 v0.102.3

**What is the current behavior?**

Crashes upon opening the excel file

```
System.ArgumentException: Unable to determine the format of the image.
   at ClosedXML.Graphics.DefaultGraphicEngine.GetPictureInfo(Stream stream, XLPictureFormat expectedFormat)
   at ClosedXML.Excel.Drawings.XLPicture..ctor(IXLWorksheet worksheet, Stream stream, XLPictureFormat format)
   at ClosedXML.Excel.XLWorkbook.LoadDrawings(WorksheetPart wsPart, XLWorksheet ws)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName)
   at ClosedXML.Excel.XLWorkbook..ctor(String file)
```

**What is the expected behavior or new feature?**

allows opening Excel files having embedded adobe branded jpegs

**Is this a regression from the previous version?**

I don't think it's a regression, just an ongoing struggle to deal with naughty applications.  but there is this: 

https://github.com/ClosedXML/ClosedXML/issues/2068

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

```
var file = "offender.xlsx";
using XLWorkbook wb = new(file);
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

With the following patch applied it can open the excel files.  It also does get the dimensions of the images properly at this point.  The offending excel files have jpeg images with vandalized or otherwise rambunctious headers.  Excel has no problem with them and doesn't fix them in its compatibility and problem finder/fixer tools.

```
 ClosedXML-develop/ClosedXML/Graphics/JpegInfoReader.cs | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/ClosedXML-develop/ClosedXML/Graphics/JpegInfoReader.cs b/ClosedXML-develop/ClosedXML/Graphics/JpegInfoReader.cs
index 18e8388..a1d1c9b 100644
--- a/ClosedXML-develop/ClosedXML/Graphics/JpegInfoReader.cs
+++ b/ClosedXML-develop/ClosedXML/Graphics/JpegInfoReader.cs
@@ -17,6 +17,7 @@ internal class JpegInfoReader : ImageInfoReader
     {
         private static readonly byte[] APP0Identifer = Encoding.ASCII.GetBytes("JFIF\0");
         private static readonly byte[] APP1Identifer = Encoding.ASCII.GetBytes("Exif\0\0");
+        private static readonly byte[] APP2Identifer = Encoding.ASCII.GetBytes("Adobe\0");
 
         protected override bool CheckHeader(Stream stream)
         {
@@ -32,6 +33,8 @@ protected override bool CheckHeader(Stream stream)
                         return IsIdentifier(stream, APP0Identifer);
                     case Marker.APP1:
                         return IsIdentifier(stream, APP1Identifer);
+                    case Marker.APP2:
+                        return IsIdentifier(stream, APP2Identifer);
                     default:
                         stream.Position += length;
                         break;
@@ -128,6 +131,7 @@ private static class Marker
             public const ushort SOI = 0xFFD8;
             public const ushort APP0 = 0xFFE0;
             public const ushort APP1 = 0xFFE1;
+            public const ushort APP2 = 0xFFEE;
             public static readonly ushort[] SOFx = new ushort[] { 0xFFC0, 0xFFC1, 0xFFC2, 0xFFC3, 0xFFC5, 0xFFC6, 0xFFC7, 0xFFC9, 0xFFCA, 0xFFCB, 0xFFCD, 0xFFCE, 0xFFCF };
         }
```

**Comment by igitur** [comment]
Kindly submit the patch as a pull request with test cases.

**Comment by ctmatt** [comment]
LOL no thanks.  Go ahead and disregard this because whoever is responsible for, or whoever likes to maintain, this code, should be able to quickly discern what they need, if anything.  Have a sweet day.

**Comment by ctmatt** [comment]
A silver platter and you want MORE? No thanks. Go ahead and toss this in the trash bin or whatever you want.
