### ISSUE TITLE
Return blank when the cell has a value

### ISSUE THREAD

**Issue by phenya-prod-by-aRL** [ClosedXML/ClosedXML#2389]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.102.3

**What is the current behavior?**

When reading a cell with a number, I get a Blank, but there is a value in the cell.
The cells do not contain the formula.
![image](https://github.com/user-attachments/assets/b34ee738-5f28-4ab9-bf94-09be615a280d)
![image](https://github.com/user-attachments/assets/2759da96-8d12-47bc-a2df-df6ba332ff4c)

**What is the expected behavior or new feature?**

I think I should get an unformatted number.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

**Code to reproduce problem:**
```c#
public void Main()
{
    using (FileStream stream = File.Open(input, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
    {
        XLWorkbook workBook = new XLWorkbook(stream);
        IXLWorksheet workSheet = workBook.Worksheets.First();
        var firstCell = worksheet.FirstCellUsed();
        var lastCell = worksheet.LastCellUsed();

        IXLRange wsRange = worksheet.Range(firstCell, lastCell);
        IXLCells cells = wsRange.Cells();
        
        foreach (IXLCell cell in cells)
                var str = GetCellStringValue(cell);
    }
}

private static string GetCellStringValue(IXLCell ixlCell)
{
      if (!ixlCell.HasFormula)
             return ixlCell.GetFormattedString();

      var cachedValue = ixlCell.CachedValue;
      var cellType = cachedValue.Type;

      switch (cellType)
      {
             case XLDataType.Blank:
                   return "0,0";
             case XLDataType.Number:
                    return cachedValue.GetNumber().ToString(numberFormat.Format);
              case XLDataType.Text:
                   return cachedValue.GetText();
              default:
                   return null;
       }
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[BlankIssue.xlsx](https://github.com/user-attachments/files/16828025/BlankIssue.xlsx)

**Comment by jahav** [comment]
I am unable to reproduce (tried 0.102.3 and develop). The screenshot displays cells B2 in inspection and J2 is selected in the Excel screenshot.

Af far as I can see, the file contains only the sequence of numbers 0.1 .. 0.01 on first line and 0.01 .. 0.001 on second line. That corresponds to the screenshot and the XML content file. No cell had a blank value.

If problem persists, please provide more clear reproducible example.

```csharp
void Main()
{
	using (FileStream stream = File.Open(@"c:\Temp\Issues\2389\BlankIssue.xlsx", FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
	{
		XLWorkbook workBook = new XLWorkbook(stream);
		IXLWorksheet worksheet = workBook.Worksheets.First();
		var firstCell = worksheet.FirstCellUsed();
		var lastCell = worksheet.LastCellUsed();

		IXLRange wsRange = worksheet.Range(firstCell, lastCell);
		IXLCells cells = wsRange.Cells();

		foreach (IXLCell cell in cells)
		{
			var str = GetCellStringValue(cell);
			Console.WriteLine(str);
		}
	}
}

private static string GetCellStringValue(IXLCell ixlCell)
{
	if (ixlCell.CachedValue.IsBlank)
		throw new Exception("Maybe here?");

	if (ixlCell.Value.IsBlank)
		throw new Exception("Or here?");

	if (!ixlCell.HasFormula)
		return ixlCell.GetFormattedString();
		
		
	throw new Exception("If it gets here, there is a formula");
}
```

Output:
```
0.100
0.090
0.080
0.070
0.060
0.050
0.040
0.030
0.020
0.010
0.010
0.009
0.008
0.007
0.006
0.005
0.004
0.003
0.002
0.001
```
