### ISSUE TITLE
Creating a hyperlink with a space within path breaks the spreadsheet for Excel 2007.

### ISSUE THREAD

**Issue by VladiStep** [ClosedXML/ClosedXML#2397]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.102.3 (also tested with CI 0.104.0-preview3).

**What is the current behavior?**

When you create (and set) a `XLHyperlink` that links to a external file with a path that contains a space character, Excel 2007 (SP3) can't properly read the file: "Excel found unreadable content".
When you accept to restore it, then it removes the hyperlink (only the underlined text is present).
Also, it breaks the document style (column width, row colors).

**What is the expected behavior or new feature?**

Excel 2007 (SP3) should be able to read the file (Excel 2016 can read it).

**Is this a regression from the previous version?**

No, version 0.101.0 behaves similarly.

## Reproducibility
**Code to reproduce problem:**
```c#
using ClosedXML.Excel;

public void Main()
{
    using XLWorkbook book = new();

    var sheet = book.Worksheets.Add("Sheet1");
    var link = new XLHyperlink(new Uri("test 1\\test.png", UriKind.Relative));
    
    sheet.Row(1).Style.Fill.BackgroundColor = XLColor.SkyBlue;
    sheet.Columns().Width = 50;
    sheet.Cell(1, 1).Value = "A link";
    sheet.Cell(1, 1).SetHyperlink(link);
    sheet.Cell(1, 5).Value = "test";

    book.SaveAs("test.xlsx");
}
```

- [x] I attached a sample spreadsheet.
[test.xlsx](https://github.com/user-attachments/files/16966932/test.xlsx)

Here you can see that the column width (`50`) is ignored and the row color only visible for non-empty cells:
![image](https://github.com/user-attachments/assets/8c28efe0-f861-40c8-b7d7-9fd422b7d232)

And here is how it should look like (I removed the space character from the path):
![image](https://github.com/user-attachments/assets/074ae25b-024d-466d-a097-43860368c754)

Replacing the space with `%20` in the `Target` property of a `Relationship` fixes the document.

**Comment by VladiStep** [comment]
Hm, if I replace the space character with `%20` here (`"test 1\\test.png"`), then it also works properly.

**Comment by jahav** [comment]
I am closing this as not planned, because Excel 2007 is too old and it's not worth it. I don't even own the license.

**Comment by VladiStep** [comment]
> I am closing this as not planned, because Excel 2007 is too old and it's not worth it. I don't even own the license.

Then it's time to update the "About" section I guess (or I misread it)
![image](https://github.com/user-attachments/assets/38d6a8cb-628a-49f4-9be1-b54c195d32f6)

**Comment by VladiStep** [comment]
Also, judging by the source code, it's probably the OpenXML issue

**Comment by VladiStep** [comment]
@jahav
(just in case)

**Comment by jahav** [comment]
The bug is likely in Excel 2007, not ClosedXML. I have literaly hundreds of issues and this one definitely not worth it to even keep track. It will never get done.

**Comment by VladiStep** [comment]
Okay, then I think there should be a mention of that somewhere, so another developer that needs Excel 2007 compatibility won't waste their time to investigate the source of the corruption, as long as the about section mentions Excel 2007.

**Comment by VladiStep** [comment]
Something like:
"Note: Excel 2007 requires that the external hyperlink address shouldn't contain the space character, instead it should be replaced with `%20`."
