### ISSUE TITLE
Pivot table creation performance with large numbers of unique strings

### ISSUE THREAD

**Issue by benedict-odonovan** [ClosedXML/ClosedXML#2402]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

e.g. 0.104.0-rc1

**What is the current behavior?**

Creating a pivot table based on a table with a large (e.g. 50k) number of rows with unique strings takes a significant amount of time. On a i7-14700k with 32GB RAM it's taking 32s.

**What is the expected behavior or new feature?**

Creating a pivot table is done in less time.

**Is this a regression from the previous version?**

In 0.104.0-preview2 the same task completed in 0.9s on the same machine.

## Reproducibility

**Code to reproduce problem:**
```c#
      void Main(string[] args)
      {
          var data = new List<object>();

          data.Add(new
          {
              Col1 = "Col1",
              Col2 = "Col2",
              Col3 = "Col3",
          });

          for (int i = 0; i < 50_000; i++)
          {
              data.Add(new
              {
                  Col1 = "Col1-" + i,
                  Col2 = "Col2",
                  Col3 = 1
              });
          }

          using (var wb = new XLWorkbook())
          {
              var ws = wb.AddWorksheet();
              var range = ws.FirstCell().InsertData(data);

              Stopwatch sw = Stopwatch.StartNew();
              var pivotTable = ws.PivotTables.Add("pvt", ws.Cell(1, 10), range);

              pivotTable.RowLabels.Add("Col1");
              pivotTable.ColumnLabels.Add("Col2");
              pivotTable.Values.Add("Col3");
              pivotTable.SetShowGrandTotalsColumns(false);

              wb.SaveAs("test.xlsx");
              Console.WriteLine($"Done in {sw.ElapsedMilliseconds}");
          }

          Console.ReadLine();

      }
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[test.xlsx](https://github.com/user-attachments/files/17044467/test.xlsx)

**Comment by jahav** [comment]
When a pivot table cache is being created, it also builds pivot table cache shared items (basically unique items of a field that may be used/displayed in pivot table as labels and such). Items are being added one by one and each one [checks](https://github.com/ClosedXML/ClosedXML/blob/0.104.0-rc1/ClosedXML/Excel/PivotTables/XLPivotCacheValues.cs#L129) whether it already is in the shared items = n^2 complexity.

It would be better to collect them and insert them at once. Cache always uses an array of values, so single value method is not useful anyway.

I haven't seen large memory consumption (dotMemory of the provided code peaks at 110 MB)
![image](https://github.com/user-attachments/assets/3fa05b65-6c61-4a7e-86f1-796fbed42fdf)
