### ISSUE TITLE
Release Date for Version 0.104.0?

### ISSUE THREAD

**Issue by NavrimCPP** [ClosedXML/ClosedXML#2405]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.102.2

**What is the current behavior?**

Complete this.

**What is the expected behavior or new feature?**

Complete this.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

I noticed on nuget.org that there is a release candidate for version 0.104.0. I am currently using version 0.102.2, which results in some transitive dependencies that are not ideal. The new version would solve this issue for me. I wanted to ask if there is a plan for when version 0.104.0 will be released?

**Comment by igitur** [comment]
There is a release candidate available at https://www.nuget.org/packages/ClosedXML/0.104.0-rc1

**Comment by NavrimCPP** [comment]
Just to confirm, the RC1 is not the official release of version 0.104.0, correct?

**Comment by jahav** [comment]
Difference is very limited. Unless there are some blockers reported, it will be released in a few days (so far there is only minor #2402), ~week from rc. 

There is no extra testing or anything.
