### ISSUE TITLE
Not possible to change "IXLRichString.Text" property

### ISSUE THREAD

**Issue by traf72** [ClosedXML/ClosedXML#2430]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.104.1

**What is the current behavior?**

Not possible to change the `Text` property of `IXLRichString`.

**What is the expected behavior?**

Possible to change the `Text` property of `IXLRichString`.

**Is this a regression from the previous version?**

- [x] Yes. It worked in version 0.102.3.

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
    var wb = new XLWorkbook();
    var ws = wb.AddWorksheet();
    var cell = ws.Cell(1, 1);

    cell
        .CreateRichText()
        .AddText("Text 1")
        .SetItalic()
        .AddText(" Text 2")
        .SetBold();

    IXLRichString richString = cell.GetRichText().ToList().First();

    richString.Text = "Changed text"; // Assignment happens correctly and the "Text" property gets the new value

    Console.WriteLine(richString.Text); // Console shows "Changed text", so it was really changed

    IXLRichString richStringAfterChange = cell.GetRichText().ToList().First();
    Console.WriteLine(richStringAfterChange.Text); // Still has the initial value "Text 1"
}
```

- [x] I attached a sample project.

[ClosedXmlBug.zip](https://github.com/user-attachments/files/17255256/ClosedXmlBug.zip)

I suppose it's by design, but in my application I need to change the text of rich cells dynamically. How can I achieve this with the new version?

**Comment by jahav** [comment]
Setter didn't call envelope (in this case cell) that it should update the rich text (rich text is immutable behind the scenes).

As a workaround, you may set a property that does call the envelope and set it, e.g.
```csharp
	richString.Text = "Changed text"; // Assignment happens correctly and the "Text" property gets the new value   
	richString.Bold = richString.Bold;
```
