### ISSUE TITLE
How to add IEnumerable<Customer> object to ClosedXML ?

### ISSUE THREAD

**Issue by shivasanika** [ClosedXML/ClosedXML#244]
have an IEnumerable List right now and need to export the data to EXCEL.

wb.Worksheets.Add(objDataTable);

Instead of adding a datatable object to workbook is there any way to add list object to it by using ClosedXML? Or any other plugin?

TIA :)

**Comment by vbjay** [comment]
You will have to create a projection using select but closed XML will let
you use ienumerable<>.

**Comment by shivasanika** [comment]
var lstCustomers = _repo.GetAllt().ToList();

I have a list like this, It mean you want me to select each column from list ?

FYI : My data columns are dynamic.

**Comment by vbjay** [comment]
_repo.GetAllt().Select(cust=>....).Tolist();

**Comment by igitur** [comment]
@shivasanika Look at the documentation at https://github.com/ClosedXML/ClosedXML/wiki/Inserting-Data for how to use `IXLCell.InsertData(IEnumerable data)`
