### ISSUE TITLE
Add formula for SumProduct

### ISSUE THREAD

**Issue by warlev** [ClosedXML/ClosedXML#245]
I have an existing workbook which uses SUMPRODUCT, but this is currently not supported in ClosedXML. Could it please be added?

**Comment by igitur** [comment]
You can test the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.577/artifacts

**Comment by igitur** [comment]
https://www.nuget.org/packages/ClosedXML/0.90.0-beta2 is released and should include the fix for this issue.
