### ISSUE TITLE
Update NuGet Badge for Visual Consistency

### ISSUE THREAD

**Issue by hitensam** [ClosedXML/ClosedXML#2469]
Description:
Update the NuGet badge in the README to use the flat style and show the version, improving its appearance and consistency.

Expected Outcome:
Replace the old badge with the new version-specific flat badge.

**Comment by hitensam** [comment]
PR: https://github.com/ClosedXML/ClosedXML/pull/2468

**Comment by jahav** [comment]
Merged.
