### ISSUE TITLE
Asp.Net file delivering example

### ISSUE THREAD

**Issue by TKharaishvili** [ClosedXML/ClosedXML#247]
I have a question about [this example in the documentation](https://github.com/ClosedXML/ClosedXML/wiki/Deliver-an-Excel-file-in-ASP.NET). Why is the additional `MemoryStream` variable necessary? I tried to save the workbook directly to response like so:

```C#
workBook.SaveAs(response.OutputStream);
```
and it worked like charm. I did do it in MVC not Web Forms though but I doubt that would make a difference as the underlying `System.Web` infrastructure is the same as far as I know...

So, if there's no specific reasoning behind the additional `MemoryStream` object, then this example can be simplified.

**Comment by igitur** [comment]
Good question. We inherited the documentation from the previous developer, so unfortunately I don't have an answer. I can only imagine that using `MemoryStream`, one might be able to make changes and save the resulting file multiple times before writing it to `response.OutputStream`. I suspect that might not be possible with writing to `response.OutputStream` directly.

**Comment by TKharaishvili** [comment]
Do you think it should be simplified? I could offer a pull request. I'm also ready to test it in web forms too, to make sure it works fine.

**Comment by vbjay** [comment]
My thoughts are that this allows for things like encryption,
compression...  What if the user wants to deliver a file that includes the
excel workbook as part of a larger file.  I think the thinking was it was
done this way to simplify layering of streams if needed.

**Comment by TKharaishvili** [comment]
Those points are valid but I think that's beside the point of that example. If demonstration of the compression is the purpose of the example then compressing is what the example should be doing, not leaving it up to user's imagination. This way it just seems redundant.

**Comment by vbjay** [comment]
It may be.  However, I think that leaving room for extension points in a sample is a good point especially since the people looking up the samples would most likely be looking for those points of extension.  Why not make it easier for them?  Once it goes to the output stream, you're done.

**Comment by vbjay** [comment]
We could alter it with a comment that says if extension not needed just save to output stream.  Or, we could comment out but not delete the memory stream lines and add a comment that says something like if you want to alter the file with encryption, compression... see this example.  I am against just deleting it.
