### ISSUE TITLE
Rows/columns ReferenceArea isn't correctly converted to text

### ISSUE THREAD

**Issue by nikminer** [ClosedXML/ClosedXML#2472]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.104.1

**What is the current behavior?**
Exception "Unable to determine token" for line defineted name when copy or rename Worksheet.

**What is the expected behavior or new feature?**
Rename or copy Worksheet

**Is this a regression from the previous version?**
Yes, in version 0.100.3 or 0.102.3 it`s work

## Reproducibility
1. Add to new name in row, using excel,  example diapasone like: "=Page1!$18:$18" in worksheet
![image](https://github.com/user-attachments/assets/baab9c24-99e5-4473-ae8e-9e0ed5d3c73a)

2. Try rename or CopyTo this worksheet in code:

3. Getting exception:
![image](https://github.com/user-attachments/assets/36d9c949-7900-40f0-81ce-d917b571a58f)

Stack Trace:
   в ClosedXML.Parser.FormulaParser`3.Formula()
   в ClosedXML.Parser.FormulaParser`3.CellFormulaA1(String formula, TContext context, IAstFactory`3 factory)
   в ClosedXML.Excel.CalcEngine.Visitors.FormulaReferences.ForFormula(String formula)
   в ClosedXML.Excel.XLDefinedName.set_RefersTo(String value)
   в ClosedXML.Excel.XLDefinedName.RenameFormulaSheet(String oldSheetName, String newSheetName)
   в ClosedXML.Excel.XLDefinedName.ClosedXML.Excel.IWorkbookListener.OnSheetRenamed(String oldSheetName, String newSheetName)
   в ClosedXML.Excel.XLWorksheets.Rename(String oldSheetName, String newSheetName)
   в ClosedXML.Excel.XLWorksheet.set_Name(String value)
   в ProductTracker.Excel.ExportOrderExcel.ExportOrder(Int32 orderId)

**Comment by jahav** [comment]
I have published ClosedXML.Parser 1.3.0 that should have a fix.

```csharp
using var wb = new XLWorkbook();
var ws = wb.AddWorksheet("Original");
var name = wb.DefinedNames.Add("name", "Original!$18:$18");
ws.Name = "New name";
Console.WriteLine(name.RefersTo);           
```
> 'New name'!$18:$18
