### ISSUE TITLE
Type RelationshipErrorHandler not found with 0.104.1

### ISSUE THREAD

**Issue by Wolfware2023** [ClosedXML/ClosedXML#2475]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.104.1

**What is the current behavior?**

Complete this.

**What is the expected behavior or new feature?**

Complete this.

**Is this a regression from the previous version?**
Yes. RelationshipErrorHandler  Type still existed in 0.102.3

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

Im not lazy. I am creating this issue to inform you instead of just ignoring it..

**Code to reproduce problem:**
```c#
using DocumentFormat.OpenXml.Packaging;
using Serilog;

public class UriRelationshipErrorHandler : RelationshipErrorHandler
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by Wolfware2023** [comment]
https://github.com/ClosedXML/ClosedXML/issues/249#issuecomment-953351159
This used to work.

**Comment by jahav** [comment]
`RelationshipErrorHandler` is part of Open XML SDK dependency, not ClosedXML. It was removed in 3.0.

[Open XML SDK 3.0 Changelog](https://github.com/dotnet/Open-XML-SDK/blob/main/CHANGELOG.md)
> Removed OpenXmlSettings.RelationshipErrorHandlerFactory and associated types and replaced with a built-in mechanism to enable this

**Comment by Wolfware2023** [comment]
I did not update OpenXml, in fact I dont even use it.
I only updated ClosedXml and now this stopped working. 

What is the new way to fix malformed URLs, which ClosedXML cannot parse?
