### ISSUE TITLE
Autofilter Removed When Copying Sheet

### ISSUE THREAD

**Issue by kbensen1** [ClosedXML/ClosedXML#248]
I have a piece of code which creates multiple Excel sheets using ClosedXML.  When creating each sheet, I apply the Autofilter before saving the sheet.  If I open those Excel files the Autofilter is on.  Once the sheets have been created, the code copies those sheets to another workbook.  However, when the target workbook is opened, the sheets no longer have the Autofilter.  Is there a way for ClosedXML to retain the Autofilter when copying a sheet (with Autofilter on) to a different workbook?

**Comment by igitur** [comment]
Is this still an issue with the latest version, or is 0.89? If so, please post a short code sample to reproduce the problem.

**Comment by kbensen1** [comment]
Hello @igitur - I was able to test this issue with 0.89 today and was able to confirm that this issue still exists.  I will get a short code sample together for you and get it posted here tomorrow.  Thanks for asking!

**Comment by kbensen1** [comment]
@igitur  - here is a short code sample that will reproduce the issue.  Let me know if anything else is needed.  Thanks!

Sub Main()
        Dim FileName1 As String = "C:\ExcelFile1.xlsx"
        Dim FileName2 As String = "C:\ExcelFile2.xlsx"

        Call CreateFile(FileName1, "FILE1")
        Call CreateFile(FileName2, "FILE2")
        'All Files Have Autofilter On Through This Point

        Dim TargetWb As New ClosedXML.Excel.XLWorkbook(FileName1)
        Dim SourceWb As New ClosedXML.Excel.XLWorkbook(FileName2)
        SourceWb.Worksheet("FILE2").CopyTo(TargetWb, "FILE2")
        TargetWb.Save()
        'Only original tab "FILE1" has autofilter now.  
        '"FILE2" tab that was copied no longer has autofilter on.

    End Sub

    Sub CreateFile(ByVal FileName As String, ByVal SheetName As String)
        Dim XlFile = New ClosedXML.Excel.XLWorkbook
        Dim XlSheet = XlFile.Worksheets.Add(SheetName)
        XlSheet.Cell("A1").Value = "HEADER_1"
        XlSheet.Cell("B1").Value = "HEADER_2"
        XlSheet.Cell("C1").Value = "HEADER_3"
        XlSheet.Cell("A2").Value = "VALUEA1"
        XlSheet.Cell("B2").Value = "VALUEB1"
        XlSheet.Cell("C2").Value = "VALUEC1"
        XlSheet.Cell("A3").Value = "VALUEA2"
        XlSheet.Cell("B3").Value = "VALUEB2"
        XlSheet.Cell("C3").Value = "VALUEC2"
        XlSheet.Range(1, 1, 1, 3).SetAutoFilter()
        XlSheet.AutoFilter.Enabled = True
        XlFile.SaveAs(FileName)
    End Sub

**Comment by igitur** [comment]
Is the problem still present? Or else why close this issue?

**Comment by kbensen1** [comment]
@igitur - 
My mistake!  Sorry about that!  I didn't mean to close the issue.  It is still a problem.  Reopening

**Comment by igitur** [comment]
Please try with the builds at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.597/artifacts

**Comment by igitur** [comment]
https://www.nuget.org/packages/ClosedXML/0.90.0-beta2 is released and should include the fix for this issue.
