### ISSUE TITLE
Different XLWorksheets can no longer be modified in parallel in 0.104.1

### ISSUE THREAD

**Issue by Macaddict42** [ClosedXML/ClosedXML#2487]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [X] No

**Version of ClosedXML**
0.104.1

**What is the current behavior?**
Entire workbook is not thread safe due to addition of SharedStringTable that is not thread-safe. It could use thread-safe collections internally such as a ConcurrentDictionary, but it does not.

**What is the expected behavior or new feature?**
Previously in 0.102.3 Worksheets could be modified in parallel without concerns of thread-safety. However, with the addition of the SharedStringTable that is not thread-safe, no concurrent changes can be made to the entire workbook. This has an incredible impact on trying to parallelize work across multiple worksheets. 

**Is this a regression from the previous version?**
Yes, regression from 0.102.3

## Reproducibility
I can't provide code that reproduces the problem but it is very straight forward what is happening. Here is a stack trace:

   at System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported()
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at ClosedXML.Excel.SharedStringTable.IncreaseTextRef(Text text)
   at ClosedXML.Excel.SharedStringTable.IncreaseRef(String text, Boolean inline)
   at ClosedXML.Excel.ValueSlice.SetCellValue(XLSheetPoint point, XLCellValue cellValue)
   at ClosedXML.Excel.XLCell.set_SliceCellValue(XLCellValue value)
   at ClosedXML.Excel.XLCell.SetOnlyValue(XLCellValue value)
   at ClosedXML.Excel.XLCell.SetValueAndStyle(XLCellValue value)
   at ClosedXML.Excel.XLCell.SetValue(XLCellValue value, Boolean setTableHeader, Boolean checkMergedRanges)
   at ClosedXML.Excel.XLCell.SetValue(XLCellValue value)
   
   If SetValue() is called in parallel by two different threads that are each setting a cell value on separate worksheets, they will throw because they're both calling add on a non-thread-safe Dictionary. The collections in the SharedStringTable should be changed from List<> and Dictionary<> to ConcurrentDictionary<>.

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by kenleese** [comment]
@Macaddict42 See https://closedxml.io/ClosedXML/#frequent-answers

**Comment by Macaddict42** [comment]
Please read what I wrote. This has nothing to do with OpenXML and everything to do with _new_ code that was added in 0.104.1. Yes, worksheets are not thread safe. But there is no reason you shouldn't be able to make changes to multiple worksheets in parallel as long as the changes to an individual worksheet are in serial. This is objectively a regression and the fix is easy to implement. I could write the code myself if you wanted.

The only reason not to improve this is if the decision to use a Dictionary instead of ConcurrentDictionary was intentional due to performance concerns. But even that wouldn't be a valid concern in this case because both Dictionary and ConcurrentDictionary writes are on the order of < 30ns. You would have to have millions of cells being updated before you even felt milliseconds of difference in performance.

**Comment by jahav** [comment]
As was mention and as is written on the front page.
> **ClosedXML is not thread-safe.** The underlying OpenXML library is also not thread-safe.

It's pure coincidence that modifying cell values from multiple sheets used to work. The only correct way is to use one thread. Use of bulk methods like `IXLCell.InsertData` should be preferred over setting each cell individually, though work on optimizing that is a long way off.

Changing dictionary would solve nothing, e.g. let's take [`SharedStringTable.DecreaseRef`](https://github.com/ClosedXML/ClosedXML/blob/0.104.2/ClosedXML/Excel/Cells/SharedStringTable.cs#L77) operation, there is a clear race condition. If multiple threads would try to clear same text in two different sheets, data might be corrupted.

Closing, works as designed.
