### ISSUE TITLE
Security update is required

### ISSUE THREAD

**Issue by IngoManthey** [ClosedXML/ClosedXML#2494]
The System.IO.Packaging package 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-qj66-m88j-hmgj.
The System.IO.Packaging package 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-f32c-w444-8ppv.

**Comment by MatejMa2ur** [comment]
The update of package was already done to the code. 
The source just needs to be packaged and shared.

**Comment by ibakirov** [comment]
This is duplicate for #2491

**Comment by jahav** [comment]
Duplicate of #2491
