### ISSUE TITLE
ClosedXML not reading (skipping) the first column in VS 2017

### ISSUE THREAD

**Issue by mpo6065** [ClosedXML/ClosedXML#250]
ClosedXML is not reading the first column when I use it with Visual Studio 2017. It just skips it and starts with the second column. It has done this with more than one Excel file, so it's not the file. I'm not sure if it's the new version of Visual Studio that's causing the problem, but it was working fine in Visual Studio 2015.

**Comment by igitur** [comment]
Please post code to fully reproduce the issue.

**Comment by mpo6065** [comment]
Here is the code, pretty straightforward. THe CurrentID variable ends up containing the value in the second column. If I set it to sh.Cell(x, 0) it throws an error.  It is not just VS 2017, it does it on 2015 too. It was working before on my old laptop (WIndows 7). Not sure if it might be a Windows 10 related issue.

int x = 3;
string CurrentID = "";
do
{
	CurrentID = sh.Cell(x, 1).Value.ToString();
	...

} while (!string.IsNullOrEmpty(CurrentID));

**Comment by mpo6065** [comment]
I also tried sh.Cell("A3").Value.ToString() and it also uses the second column.

**Comment by mpo6065** [comment]
And also using sh.FirstColumn() returns the second column too so it's the problem is not in my code. The same code was working fine before upgrading to Windows 10.

**Comment by vbjay** [comment]
Can you do a quick test and show no hidden cells and it still fails?
Create a test with a1 value of 1 and b2 2. Prove that firstcolumn gets a
cell with 2 in it.

On Fri, Mar 31, 2017, 5:34 PM mpo6065 <notifications@github.com> wrote:

And also using sh.FirstColumn() returns the second column too so it's the
problem is not in my code. The same code was working fine before upgrading
to Windows 10.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ClosedXML/ClosedXML/issues/250#issuecomment-290835904>,
or mute the thread

**Comment by mpo6065** [comment]
I don't have a registered version of Excel (my client sent the file) so I can't create new files or make changes to xlsx files.

**Comment by mpo6065** [comment]
I'm creating a test. Hold on.

**Comment by mpo6065** [comment]
I created a file using CLosedXML (bc I don't have Office registered) and it did not happen there (which is expected since I used it to create the file) but it is still happening in the file I am trying to read. I tried copying the sheet to a new workbook and it excluded the first column and also added a column onto the end which it titled "Column23".  Can I send the file to you (but not publicly through the board)?

**Comment by igitur** [comment]
I think @vbjay is right and that there might be hidden cells / columns. I suggest installing at least [LibreOffice](https://www.libreoffice.org) or [WPS Office](http://www.kingsoftstore.com/software/kingsoft-office-freeware) to inspect your Excel file. 

Also check your cell's address using `sh.Cell(x, 1).Address.ToString()` to ensure that you are referencing the cell you want.

**Comment by igitur** [comment]
And yes, if you want to send me the file, email it to me. igitur .... gmail

**Comment by mpo6065** [comment]
It's definitely 100% NOT a hidden column nor field. I would know if it was. The files are generated by a piece of software they have and are only used for exporting, there is no reason to have a hidden field. We have been running it successfully for over a year compiling it on Windows 7, but when I upgraded to Windows 10 and compiled it on there that is when the issue occurred. I spoke with the client and they told me I should not send the file I have because it has sensitive information in it and we have decided to instead switch to using a different utility, so you can close this issue if you want as it is no longer a problem for me, but I am sure you will have to deal with it again.

**Comment by igitur** [comment]
Is there no way you can get a file with the sensitive information removed?

**Comment by mpo6065** [comment]
What I can do is tomorrow I will go to the library. They have Excel on the computers there. Then I can delete or alter the sensitive data and I will send it then.

**Comment by igitur** [comment]
Dude... install one of the suggested suites in https://github.com/ClosedXML/ClosedXML/issues/250#issuecomment-291097561

Make life easy for yourself.
