### ISSUE TITLE
References damaged after saving workbook

### ISSUE THREAD

**Issue by vojtek11** [ClosedXML/ClosedXML#252]
This is a simplest table : [1.xlsx](https://github.com/ClosedXML/ClosedXML/files/886217/1.xlsx)

First column is base value. second column is reference to first one. And I do this :

```c#
wb = new XLWorkbook("1.xlsx");
wb.Worksheet("Sheet1").Cell("A2").Value = "1";
wb.Save();
```

Cell value is updated properly, however all references are set to null. Not just this one affected by an updated value. All of them. When I open this file in Excel, on load, references are probably updated and that's why when I close Excel, it asks if this file should be resaved (even if I didn't do anything to it, but references were updated). Bigger problem is that all 3rd party applications that read this XLSX via ADO.NET, can never see those values. On read, they all are showing null values in all reference destination cells in the all worksheets.

I tried wb.ForceFullCalculation = true, I tried wb.CalculationOnSave = true;. I tried all possible combinations of wb.ReferenceStyle and wb.CalculateMode. Nothing makes those references reappear for ADO.NET based XLSX readers. The only way to restore them is to open Excel and resave this file.

Is there any way to restore references before save?

Regards,
Wojtek

**Comment by igitur** [comment]
Try the lastest `ClosedXML` code from the `develop` branch. This will be released soon. I suspect it will fix your issue.

fyi, @Pyropace

**Comment by vojtek11** [comment]
Nope. Sorry. It was the one I started with. Now I also checked 0.86 and 0.87. Same "null" effect on save at all references through out the entire workbook. Always.

W

**Comment by Pyropace** [comment]
0.87.0 is out

**Comment by igitur** [comment]
Please paste reproducible code you use to read the file via ADO.NET.

**Comment by igitur** [comment]
Also try this first:
```c#
wb.Worksheet("Sheet1").Cell("A2").Value = 1;
```

I suspect the mix of integer and strings values in the same columns causes problems for ADO.NET.

**Comment by vojtek11** [comment]
This is a simplest code to read from 1.xlsx : 

            string connectionString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=1.xlsx;Extended Properties=\"Excel 12.0 Xml;HDR=YES;IMEX=1\"";
            OleDbConnection connection = new OleDbConnection(connectionString);
            connection.Open();
            OleDbCommand command = new OleDbCommand("select * from [Sheet1]", connection);
            OleDbDataAdapter dataAdapter = new OleDbDataAdapter();
            dataAdapter.SelectCommand = command;
            DataTable dt = new DataTable();
            dataAdapter.Fill(dt);
            connection.Close();
            
And then You can make some sort of content check of dt (a DataTable). If I run this, before saving with ClosedXML, I get all correct cell values. After using ClosedXML, I get first (base) column correct and all values in second column (references) are System.DBNull.

Regarding Your suggestion of mixed types and potential problems with this for ADO.NET. Just for a test I did only that : 
wb = new XLWorkbook("1.xlsx");
wb.Save();

No value change. Just load and save. and that alone is "nulling" all reference cells all over the workbook.

I also created completely new workbook, with only integer numbers in 1st column (not even text header here). and all references in another. same result. null everywhere after saving with ClosedXML.

**Comment by igitur** [comment]
If you can, try the code at #269 and see if it solves your issue.

**Comment by igitur** [comment]
You will have to use the `wb.SaveAs(file, true, true)` override to evaluate the new formula values when saving.

**Comment by vojtek11** [comment]
It's better, but I allowed myself to go a bit further... 

See attached [2.xlsx](https://github.com/ClosedXML/ClosedXML/files/924142/2.xlsx)

In Sheet1 there is a "base" column (A). column B has references. after saving, now those references are good via ADO.NET. In Sheet2 (columns A and B) I created references to same cells from Sheet1. After reading with ADO.NET - all good. 3rd column in Sheet2 (C) is the sum of cells from local columns A and B. ADO.NET reads here correct values. However, in column D everything is nulled out. Column D contains following formula:

=SUM(Sheet1!A2:Sheet1!A3)

it sums up cells from another worksheet. and that is not processed at all. so the formulas are working, but only on local referenced values. never on referenced values from another worksheet (within same workbook).

Regards,
Wojtek

**Comment by igitur** [comment]
Are you able to evaluate the values of the formulae through normal `ClosedXML` operations?

**Comment by igitur** [comment]
Try the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/artifacts

**Comment by igitur** [comment]
Try the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.253/artifacts

**Comment by vojtek11** [comment]
Sorry. Still "null effect" on that formula :

=SUM(Sheet1!A2:Sheet1!A3)

... and pretty much any other formula that contain at least one argument that is non-local cell.

Regards,
Wojtek

**Comment by igitur** [comment]
Are you able to evaluate the values of the formulae through normal ClosedXML operations?
