### ISSUE TITLE
You should link to the wiki from the README

### ISSUE THREAD

**Issue by togakangaroo** [ClosedXML/ClosedXML#254]
Many projects don't actually use the Github wiki feature so this is not a place people think to look by default for documentation.

You should add a link to the wiki in the README so that people know to look there.

**Comment by igitur** [comment]
Looks like you're about to submit a pull request for that. ;-)

**Comment by togakangaroo** [comment]
Ugh, *fine*

https://github.com/ClosedXML/ClosedXML/pull/255

Even though I think that I don't need excel parsing for my project after all...

**Comment by Pyropace** [comment]
merged
