### ISSUE TITLE
Vulnerable dependency

### ISSUE THREAD

**Issue by dizzyrobotix** [ClosedXML/ClosedXML#2551]
Hi guys!

Looks like your NuGet package has dependency on System.Drawing.Common, which has vulnerability.
Can you upgrade the dependency please?

New version of VS is more strict on vulnerable dependencies.
In our setup we treat warnings as errors.
After VS upgrade we started receiving errors regarding vulnerable packages.

Thanks,
Mike K

<img width="653" alt="image" src="https://github.com/user-attachments/assets/31a907bc-dd47-463d-b551-13b8fcaaa9c5">

**Comment by jahav** [comment]
System.Drawing.Common has been removed in 0.97.0, more than 2 years ago.
