### ISSUE TITLE
.NET 9 

### ISSUE THREAD

**Issue by galiolas** [ClosedXML/ClosedXML#2565]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.104.2

**What is the current behavior?**

Will the package be compatible with .NET 9 soon ? 
I added the packgage in my code and it works very well. I'm in .NET 9. But when i want to publish the code on my AzureWebApp I have an error : "Unable to resolve 'ClosedXML.Parser (>= 1.2.0 && < 2.0.0)' for 'net9.0'. PackageSourceMapping is enabled, the following sources were not considered: C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages, nuget.org."

**Comment by jahav** [comment]
ClosedXML works on .net9. That is problem on your end, likely because you are using some offline repository of nuget packages instead of using live nuget.org.
