### ISSUE TITLE
Reference not added with version 0.87.0 (works with 0.86.0)

### ISSUE THREAD

**Issue by Kvasi** [ClosedXML/ClosedXML#257]
When adding the nuget package, a reference is not added when using version 0.87.0.

**Comment by vbjay** [comment]
Update-package.

**Comment by igitur** [comment]
I see the .dll files moved from the `lib` to `build` folder. I'll check with @Pyropace

**Comment by Pyropace** [comment]
reuploading the package. should be up soon. 

used a new tool to create a package, didn't notice the build folder

**Comment by igitur** [comment]
Looks like v0.87.1 is working through NuGet update-package
