### ISSUE TITLE
Does ClosedXML support .NET 8

### ISSUE THREAD

**Issue by jose-correia-visma** [ClosedXML/ClosedXML#2581]
## Does ClosedXML support .NET 8 ?

Hello,

We are planning to migrate our existing library to ClosedXML for commercial purposes and are also transitioning our entire application to .NET 8. Could you please confirm if ClosedXML currently supports .NET 8?

This information is crucial for us to evaluate whether ClosedXML is a reliable option for our use case.

Thank you for your assistance!

**Comment by jahav** [comment]
That's your job to determine that. 

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 

There is no "support" . It runs on .NET 8 and CI pipeline passes.

**Comment by jose-correia-visma** [comment]
Hi @jahav you look nervous , i don't understand why . :/
Was just a legit question for a library that is public available. 
Thanks for you wonderful collaboration and answer

**Comment by jahav** [comment]
Because you ask a question that is akin to "How do I use Console.Write"
