### ISSUE TITLE
Creating lots of sheets with lots of data, runs out of memory

### ISSUE THREAD

**Issue by dhrumil83** [ClosedXML/ClosedXML#259]
~100 sheets. Per sheet ~50k records.

This runs out of memory.
var workbook = new XLWorkbook();
for(1 - 100)
{
   var worksheet = workbook.Worksheets.Add(SomeName);
   MethodToWriteRecords(worksheet);
}
workbook.SaveAs(Location_To_ExcelFile);

What I cannot figure out is this:
At the end of each loop, save the content to the excel file, rather than keeping it in memory.
In the next loop, create a new sheet, and save contents there.

**Comment by igitur** [comment]
The way `ClosedXML` is designed is to keep the entire file in memory. For each cell, the styles and formats are stored in memory too. This creates a big memory load. We are aware of the problem and trying to find ways around it. Look at #86 for further discussion.

**Comment by igitur** [comment]
Duplicate of #86

**Comment by dhrumil83** [comment]
In some of my workflows, I simply take data out from places, and dump them in the excel sheet. I don't use styles and formats at all, but it still uses a lot of memory.
Any workaround to a lower memory footprint, when it's a simple data dump?
