### ISSUE TITLE
Getting exception "Unexpected token BANG_REFERENCE"

### ISSUE THREAD

**Issue by somnatic** [ClosedXML/ClosedXML#2592]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.104.999.4219 and 0.104.2 and 0.104.1

**What is the current behavior?**

When loading the Excel file attached to this report, I get the following exception:
`ClosedXML.Parser.ParsingException: 'Error at char 36 of 'OFFSET('Smelter Look-up'!$B$4,MATCH(!$B1,'Smelter Look-up'!$A:$A,0)-4,0,COUNTIF('Smelter Look-up'!$A:$A,!$B1),1)': Unexpected token BANG_REFERENCE.'`

**What is the expected behavior or new feature?**

No exception

**Is this a regression from the previous version?**

Yes, it works on 0.102.3 but not on 0.104.1

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

**Code to reproduce problem:**
```c#
        static void Main(string[] args)
        {
            var wb2 = new XLWorkbook(@"d:\temp\xx.xlsx");
        }
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[xx.xlsx](https://github.com/user-attachments/files/18207568/xx.xlsx)

**Comment by jahav** [comment]
Parsing issue was fixed in #2596. Bang reference can't be evaluated yet.

I assume the exception when a sheet is deleted or moved or something, because file loads in 104.1 without exception.

```csharp
using var wb = new XLWorkbook(@"c:\Temp\Issues\2592\xx.xlsx");
var name = wb.DefinedName("SN")!;
Console.WriteLine($"Before: {name.Name}: {name.RefersTo}");

var sheet = wb.Worksheet("Smelter Look-up");
sheet.Name = "Smelter Look-down";

Console.WriteLine($"After: {name.Name}: {name.RefersTo}");
```

> Before: SN: OFFSET('Smelter Look-up'!$B$4,MATCH(!$B1,'Smelter Look-up'!$A:$A,0)-4,0,COUNTIF('Smelter Look-up'!$A:$A,!$B1),1)
> After: SN: OFFSET('Smelter Look-down'!$B$4,MATCH(!$B1,'Smelter Look-down'!$A:$A,0)-4,0,COUNTIF('Smelter Look-down'!$A:$A,!$B1),1)
