### ISSUE TITLE
Add closedXML.Debug nuget package

### ISSUE THREAD

**Issue by vbjay** [ClosedXML/ClosedXML#260]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

**What is the current behavior?**
Only one nuget package exists.  
**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

**What is the expected behavior or new feature?**
Add nugget package that is a debug build of the project.

We could also have a develop package that is the latest successful build in the develop branch. 
**Did this work in previous versions of our tool?  Which versions?**

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Please explain why this is necessary.

**Comment by vbjay** [comment]
Having at least a debug build would allow us to get debug info in a system by letting us switch out the package if needed.  Having a ci build of the develop branch could be a great way to have a testbed system that could go beyond the tests and allow for someone to create a sample and all we have to do is update-package to stay current.

**Comment by igitur** [comment]
Sorry, I'm not going to create a separate NuGet package. I'll consider creating prerelease versions in Debug configuration once we hit v1. Final releases will always be in Release configuration. In any case, it's really simple just to add the ClosedXML source directly into your project.

**Comment by vbjay** [comment]
We could alter the build to get the current head sha-1 from git and add it as a property.

I was thinking of the nuget package being deployed through CI.  https://confluence.jetbrains.com/display/TCD9/NuGet+Publish

**Comment by vbjay** [comment]
Debug example.  http://www.nuget.org/packages/Kaazing.Enterprise.Debug/

**Comment by igitur** [comment]
If you need this, you're welcome to maintain your own CI and NuGet package for this.
