### ISSUE TITLE
[FeatureRequest] Create a copy of a Workbook without recreating a new stream.

### ISSUE THREAD

**Issue by koorellasuresh** [ClosedXML/ClosedXML#261]
[FeatureRequest] Create a copy of a Workbook without recreating a new stream.

Please let me know if you need more details. Also, Please point me if such feature already exists.

**Comment by igitur** [comment]
Yes, more details please.

**Comment by koorellasuresh** [comment]
Thanks a lot for quick response. 

We keep the multiple of copies (Read and Write) of XLWorkbooks in our cache, and if one copy goes out of sync then we use the other one to create a copy of XLWorkbook. 

Currently, I am creating a copy of XLWorkbook by creating a new stream, which is very costly. Is there any way I can avoid creating a new stream to create a copy of a workbook.

**Comment by igitur** [comment]
Not sure I understand fully. But if the files are on disk, why don't you just do File.Copy?
