### ISSUE TITLE
ClosedXML Changes Text Value

### ISSUE THREAD

**Issue by kbensen1** [ClosedXML/ClosedXML#265]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**
ClosedXML is changing the value in some cells with a hexadecimal value.  The cells are set to a text datatype but ClosedXML is changing them anyway.  Sample code is shown below where ClosedXML changes Hex value AD3AD08 to 42802.  

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**
Sample code which reproduces issue is shown below.

**What is the expected behavior or new feature?**
When cell is set to text datatype, value should be left as AD3AD08

**Did this work in previous versions of our tool?  Which versions?**
Not Sure

Sample Code:
```vb
        Dim FileName As String = "C:\ExcelFile.xlsx"
        Dim XlFile = New ClosedXML.Excel.XLWorkbook
        Dim XlSheet = XlFile.Worksheets.Add("EXAMPLE")
        XlSheet.Cell("A1").Value = "DECIMAL"
        XlSheet.Cell("B1").Value = "HEX"
        XlSheet.Cell("A2").Value = "181644552"
        XlSheet.Cell("A2").DataType = ClosedXML.Excel.XLCellValues.Text        
        XlSheet.Cell("B2").Value = "AD3AD08" 'ClosedXML changes value to 42802
        XlSheet.Cell("B2").DataType = ClosedXML.Excel.XLCellValues.Text
        XlFile.SaveAs(FileName)
```

**Comment by igitur** [comment]
When you set the  `Cell.Value` property, `ClosedXML` makes a guess about the data type. For some reason it happens that `AD3AD08` is a valid date. `DateTime.Parse("AD3AD08")` returns `2017-08-03 12:00:00 AM`.

If you want full control, you can use `Cell.SetValue<string>(val)`

More info at https://github.com/ClosedXML/ClosedXML/wiki/Cell-Values

**Comment by igitur** [comment]
And `42802` is just the numeric representation of `2017-08-03`.

**Comment by igitur** [comment]
More info about why `AD3AD08' is parsed as a `DateTime` at http://stackoverflow.com/questions/43339856/why-does-ad3ad08-represent-a-valid-date-in-the-net-framework

**Comment by kbensen1** [comment]
Thanks @igitur - the solution you posted works fine for me.  I appreciate the feedback as well as the additional information regarding why the data is being treated as a date.  Thanks again!

**Comment by noknok321** [comment]
Sorry to post here but i got a similar problem.
However I am not not using Cell.SetValue, I am doing this:
```
using (XLWorkbook inputWorkbook = new XLWorkbook(inputFileStream))
{
   foreach (IXLWorksheet inputWorksheet in inputWorkbook.Worksheets)
   {
      //get cell values in worksheet
   }
}
```

I have a file does not restrict input format.
There is a cell allow user to enter a date in any format, even in language form.
The XLWorkbook treat that cell as DateTime so it gets the wrong value.
Is it possible to force the XLWorkbook using plain text when reading the filestream?
