### ISSUE TITLE
.xltx / .xltm support

### ISSUE THREAD

**Issue by Dryhoof** [ClosedXML/ClosedXML#267]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

**What is the current behavior?**
Currently the library only supports xlsx / xlsm files.

**What is the expected behavior or new feature?**
Would be very nice to be able to open xltm files!

**Did this work in previous versions of our tool?  Which versions?**
Not that I know! :D

**Comment by igitur** [comment]
Are those file types also the same zipped OpenXML format as `.xlsx` and `.xlsm`? If so, it should be easy to extend.

**Comment by Dryhoof** [comment]
Goood question, i have no idea :D

There certainly are differences, because Excel itself will not allow me to open a file that was saved as xltm after changing it to xlsm by hand...

Saving a opened xltm as xlsm would also open up new problems, I guess.
