### ISSUE TITLE
Formatted String by GetFormattedString() is incorrect

### ISSUE THREAD

**Issue by SabotageAndi** [ClosedXML/ClosedXML#270]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**
I have a formatted cell with the format "TT\.MM\.JJJJ" and value "12.04.2017 13:41:00"
When I read it with GetFormattedString() I get "12.41.2017" back.

I think the reason for this is, that XLCell.Style.NumberFormat for the Cell is `{-1-dd\.mm\.yyyy}`.
The mm should be MM. Month are switches with minutes.

The values are in the german date format: Days.Month.Year

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

Repro Code to be executed against the provided Excel- File
```
static void Main(string[] args)
{
	var xlWorkbook = new XLWorkbook("DateFormat.xlsx");
	var sheet = xlWorkbook.Worksheets.First();
	var formattedString = sheet.Cell("A1").GetFormattedString();

	Console.WriteLine("Expected string: 12.04.2017");
	Console.WriteLine($"Actual string: {formattedString}");
	Console.Read();
}
```

**What is the expected behavior or new feature?**
I get the value "12.04.2017" from GetFormattedString()

**Did this work in previous versions of our tool?  Which versions?**
I tried it with 0.86.0 and 0.87.1

- [x] I attached a sample spreadsheet.  
[DateFormat.xlsx](https://github.com/ClosedXML/ClosedXML/files/916379/DateFormat.xlsx)

**Comment by igitur** [comment]
We reuse the built-in string formatting in the .NET framework. It's mostly similar to Excel, but this is one of the differences. Unfortunately it's unlikely that we'll get this fix. It would require our own implementation of string formatting, which is vastly complicated.

**Comment by SabotageAndi** [comment]
Do you have any suggestions for a workaround on my side for this?
How do you handle such cases normally?

**Comment by igitur** [comment]
I'd suggest you get the `Cell.Value` and `Cell.DataType` and decide yourself how you want to format the value.
