### ISSUE TITLE
Changing the value of a column header results in corrupt .xlsx file

### ISSUE THREAD

**Issue by muchidacopperleaf** [ClosedXML/ClosedXML#285]
- [x] Bug
- [ ] Feature

Since switching to the nugget package for ClosedXml we are encountering an excel error for some of our output.  So far it seems isolated to attempts at assigning values to a table header (ex table.Cell(1, 1).Value = "New value"; ), 

 ```c#
    class Program
    {
        static void Main(string[] args)
        {
            var wb = new XLWorkbook("Basic.xlsx");
            var filter = CreateFilterTable();
            var ws = wb.AddWorksheet("Test");
            var table = ws.Cell(2, 2).InsertTable(filter);

            table.Cell(1, 1).Value = "New value";       // Excel Error
            //ws.Cell(2, 2).Value = "New value";        // Excel Error
            //table.Cell(2, 1).Value = "New value";     // NO Excel Error

            wb.SaveAs("Basic_result.xlsx");
        }

        internal class FilterNameValue
        {
            public string Filter { get; set; }
            public string Value { get; set; }
        }
        public static List<FilterNameValue> CreateFilterTable()
        {
            // setup data
            return new List<FilterNameValue>
            { new FilterNameValue {Filter = "Title 1", Value = "Value 1"}
            , new FilterNameValue {Filter = "Title 1", Value = "Value 1"}
            };           
        }
    }
```

which results in an error when opening the resultant xlsx file as follows…

"We found a problem with content in.... Do you want us to try and recover as much as we can.... etc"

Now when you hit Yes and look at the results in excel, it looks ok, but something was messed up that excel had to recover from.
 
The most worrying part for us is the difference between the NuGet versions of Closed xml and the old Codeplex web site versions, which is where we originally got our ClosedXml 0.75 download from.  Even for the same version of ClosedXml (ex. ClosedXml 0.75) differs between CodePlex and NuGet ! 
We originally moved to NuGet packages and took the 0.86 version, which triggered this issue.  For the investigation we tested with 0.75 from NuGet as well and the latest 0.87, and had the same results.
 
CodePlex ClosedXml 0.75 is OK (what we’ve used for a long time without issue).
NuGet ClosedXml 0.75 gets error.
NuGet ClosedXml 0.86 and 0.87.1 gets error.
 
We also ran against excel 2010 and excel 2016, no difference.
DocumentFormatOpen.OpenXml is the same in all cases.

Attached is a simple sample app that demonstrates the issue (Visual Studio, C#, .net 4.5.1)
 
[CloseXMLConsoleApplication2.zip](https://github.com/ClosedXML/ClosedXML/files/956044/CloseXMLConsoleApplication2.zip)

fyi this looks a little similar to issue 205, in that it is a column change that results in the same errors and behaviour in excel.

Thanks for all your work on ClosedXML!

**Comment by igitur** [comment]
I get a corrupt file even if I use the ClosedXML v0.75 from Codeplex.

**Comment by igitur** [comment]
Use this code to rename a table field name:
```c#
table.Field("Filter").Name = "New value";
```

**Comment by igitur** [comment]
[ClosedXML v0.89.0-beta1](https://www.nuget.org/packages/ClosedXML/0.89.0-beta1) has been published and is ready for your testing.
