### ISSUE TITLE
Column Formulas in Table Do not Copy to New Row

### ISSUE THREAD

**Issue by FuzzyCoder** [ClosedXML/ClosedXML#288]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

1) Create a table with one column (e.g. Column C) containing the same formula in each cell of the data rows.
2) Place cursor on last row of table and tab out to create a new row in the table.

The formula in Column C is not copied to the new row.

3) Open the spreadsheet in Excel and Convert the Table to a Range then Recreate the Table
4) Formula is copied to new row.

When I look at the table.xml in the xlsx where the new row copies the formula, the formula is included as a calculatedColumnFormula in the tableColumn.

In the xlsx generated by ClosedXML, the formula is not found in the table.xml.

I have tried all manner of range and column formula assignments and even tried to programmatically remove and recreate the table.  None of these attempts have worked.

NOTE: Data Validation does work correctly, with new rows containing the lookup lists.

Addendum:  Also see the same issue with column styles; new rows don't extend the cell fills, borders, etc from previous rows.

**Comment by igitur** [comment]
Please post a code sample to illustrate the problem.

**Comment by igitur** [comment]
I'll reopen after you post a code sample.
