### ISSUE TITLE
Copy BackgroundColor from one IXLCell to each IXLCell in an IXLRange

### ISSUE THREAD

**Issue by NeededAnUnusedName** [ClosedXML/ClosedXML#290]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**
Unpredictable BackgroundColor value assignment. 

I try to use a default cell (A1) to have a Cell in the Default-Excel-Style, which I can then use to delete/reset Cells of different Ranges (A2:E2). (I haven't found another way to fully reset a cell, if there is, please tell me.) 

Not all Cells of Range (A2:E2) get the color of that origin Cell (A1), sometimes none (A2:E2 stay colored), sometimes only a few (only A2 gets the A1 Style, or A2 and B2 but not the rest, or A2 and C2 but not the rest, I have seen it all) and sometimes even the "origin Cell" gets the "destination Cell" BackgroundColor.  
Please have a look at code comments below.

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**
- I open a new Excel File, 
- select Range A2:E2, 
- hit the arrow Button next to the FillColor bucket in Excel,
- and choose a color of the shown "Designcolors"(<- german version)  palette 
- select another cell on the sheet
- Hit File -> save as "C:\MyTemp\empty.xlsx"
- Run Code in release or debug mode

**Did this work in previous versions of our tool?  Which versions?**
It worked for weeks with 
> cell.Value = "";
> cell.Style = DefaultCell.Style;
> cell.Style.Font.FontColor = XLColor.Black;
>   cell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.General;
now it wont. I don't know why, I havent changed the code or the file. (did a few runs with backup files with the same result)
In my production xlsx File (which I cannot provide) the origin Cell gets the color of a Range cell, and assigns that color to the whole Range too, I can't reproduce this behavior in my Testproject.

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[empty.xlsx](https://github.com/ClosedXML/ClosedXML/files/962121/empty.xlsx)

**Code to reproduce problem:**
```c#
static void Main(string[] args)
        {
            String Filename = @"C:\MyTemp\empty.xlsx";
            String Worksheet = "Tabelle1";
            using (XLWorkbook workbook = new XLWorkbook(Filename, XLEventTracking.Disabled))
            using (IXLWorksheet sheetXML = workbook.Worksheet(Worksheet))
            {
                IXLCell defaultcell = sheetXML.Cell(1, 1);
                IXLRange setColorRange = sheetXML.Range(2, 1, 2, 5);
                foreach (IXLCell cell in setColorRange.Cells())
                {
                    //cell.Style.Fill.SetBackgroundColor(defaultcell.Style.Fill.BackgroundColor); //leaves black background

                    //cell.Style = defaultcell.Style; 
                    //Works in this szenario, but not (anymore) in my "live.xlsx" which I cannot provide, sorry.
                    //the defaultcell AND all Range cells get the blue color

                    //cell.Style.Fill = defaultcell.Style.Fill; 
                    //Unpredictable behavior, most of the times A2 gets it right, rest of Range stays blue
                    //sometimes it manages to fill B2 and C2, sometimes only A2 and C2.... 
                    //I tried it with a new File each time and with the existing File. 

                    //cell.Style.Fill.BackgroundColor = defaultcell.Style.Fill.BackgroundColor; 
                    // right now it leaves a black background color, (tested with new file)
                    // usually I get the same result as I do with the cell.Style.Fill aproach (which makes sence)
                }
                workbook.Save(false);
            }
        }
```

package id="ClosedXML" version="0.87.1" targetFramework="net45"
package id="DocumentFormat.OpenXml" version="2.5" targetFramework="net45"
Microsoft Office Standard 2010 -> Excel: Version: 14.0.7173.5000 (32-Bit)
Visual Studio 2015 community Edition

Please let me know, if anything is unclear or more information is needed, thanks.

**Comment by igitur** [comment]
Ok, I can reproduce the problem. There's no easy solution and part of the problem is that `A1` has no style, so the workbook's default style is used. There are some problem when copying the default style. 

As a workaround, I suggest you use this code to set the target range's style:
```c#
setColorRange.Style = XLWorkbook.DefaultStyle;
```
Notice that you don't have to loop through the cells in the range. You can if you really want to, but it's unnecessary.

I think I will first add some methods to clear a cell's style (i.e. it reverts to the default style) and then later look at a proper solution for this bug.

PS: Styles are really complicated.

**Comment by Pyropace** [comment]
> PS: Styles are really complicated.

yes we will be working on making it simpler

**Comment by Pankraty** [comment]
Wow, it's almost the issue's Jubilee )

Now that styles were redesigned, the issue cannot be reproduced. 

1. `cell.Style = defaultcell.Style;` and `cell.Style.Fill = defaultcell.Style.Fill;` work fine with the provided example.
2. `cell.Style.Fill.SetBackgroundColor(defaultcell.Style.Fill.BackgroundColor);` and `ell.Style.Fill.BackgroundColor = defaultcell.Style.Fill.BackgroundColor; ` both leave the `A2:E2` range black but it is not a bug actually. The thing is, the default style's `BackgroundColor` is `Indexed(64)` (black) and the `PatternType` is `None`. When we copy the background color to `A2:E2` the color is naturally copied, but the `PatternType` remains `Solid` - as it was before copying. This is a correct behavior; if it is undesirable the entire `Fill` must be assigned.

**Comment by igitur** [comment]
Indexed colour 64 is transparent, not black.

**Comment by igitur** [comment]
Indexed colour 64 means tranparent. Refer to https://github.com/ClosedXML/ClosedXML/blob/develop/ClosedXML/Excel/Style/Colors/XLColor_Static.cs#L164

**Comment by igitur** [comment]
I agree `cell.Style = defaultcell.Style;` and `cell.Style.Fill = defaultcell.Style.Fill;` work as expected.

**Comment by igitur** [comment]
As I understand it, for non-differential styles, 2 fills should be equal if they are both transparent, regardless of the pattern type. Also, 2 fills should be equal if one is transparent, and the other one is unspecified (I'm referring to the OpenXML `Fill` element, which can have the colors specified or omitted).

That's why I've been experimenting with `XLFillKey`'s `Equals` and `GetHashCode` methods. I could save the problem in this issue, but it generated many failing tests that I still have to investigate. @Pankraty I can commit and push what I've done so far?

**Comment by Pankraty** [comment]
Go ahead. I will take a look at failing tests.

**Comment by igitur** [comment]
Very rough work, but check out https://github.com/igitur/ClosedXML/tree/issue290-transparent-background. I think we have to define 2 different comparers... one for normal styles and one for differential styles. For differential styles, we want to keep the transparent indicator.

**Comment by Pankraty** [comment]
With #862 all four ways produce the same result:
![image](https://user-images.githubusercontent.com/19576939/40273185-c533cf2a-5bcc-11e8-91e2-2e60e4d906b1.png)
