### ISSUE TITLE
Reading Values from Shared String table

### ISSUE THREAD

**Issue by krishnaps1592** [ClosedXML/ClosedXML#298]
**Do you want to request a *feature* or report a *bug*?**
- [x] Feature

**Trying to read a value of a cell using Cell.Value, returns an empty string, when the value of the string is a shared string and not an inline string.**

**How to read values from shared string table?**

```

**Comment by igitur** [comment]
Please fill out the complete [issue template](https://github.com/ClosedXML/ClosedXML/blob/develop/.github/ISSUE_TEMPLATE.md)
