### ISSUE TITLE
Support for lookup functions

### ISSUE THREAD

**Issue by Pyropace** [ClosedXML/ClosedXML#30]
https://support.office.com/en-us/article/VLOOKUP-function-0bbc8083-26fe-4963-8ab8-93a18ad188a1

**Comment by igitur** [comment]
I think most of the lookup functions are not implemented. 

https://support.office.com/en-us/article/Lookup-and-reference-functions-reference-8aa21a3a-b56a-4055-8257-3ec89df2b23e?ui=en-US&rs=en-US&ad=US

**Comment by Pyropace** [comment]
wow that was fast :)
