### ISSUE TITLE
Performance issue of creating merged cells

### ISSUE THREAD

**Issue by wtetsu** [ClosedXML/ClosedXML#300]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

**What is the current behavior?**

Creating hundreds of merged cells takes long time.

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

For example:

- Create a row with merged cell.
- Copy the row several hundreds times(The code will be described later)

It gradually get slower and slower.

**What is the expected behavior or new feature?**

I hope merged cells creation finished faster.

**Did this work in previous versions of our tool?  Which versions?**

- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)

- develop branch(0810d0d80155fb01ace3aa28e2f4c8919281cfa0)

**Code to reproduce problem:**
```c#
using (var wb = new XLWorkbook(@"template.xlsx"))
{
    var ws = wb.Worksheets.Worksheet(1);
    var firstRow = ws.FirstRow();

    var startTicks = DateTime.Now.Ticks;

    using (var range = ws.Range(1, 1, 1, 20))
    {
        for (int i = 0; i <= 500; i++)
        {
            using (var rangeTo = ws.Range(2 + i, 1, 2 + i, 20))
            {
                range.CopyTo(rangeTo);
            }
            if (i % 10 == 0)
            {
                Console.WriteLine((DateTime.Now.Ticks - startTicks) / 10000);
            }
        }
    }

    wb.SaveAs(@"template_new.xlsx");
}
```

[template.zip](https://github.com/ClosedXML/ClosedXML/files/983894/template.zip)

![chart01](https://cloud.githubusercontent.com/assets/515948/25810394/f8b8e376-344a-11e7-9750-e95f6d8db88d.png)

If there are no merged cells it takes less than 50 ms.

**Comment by igitur** [comment]
Thanks for you contribution. Keep them coming.
