### ISSUE TITLE
System.Exception 'Expression expected.' When calling GetValue on a cell with a formula

### ISSUE THREAD

**Issue by Tarboeuf** [ClosedXML/ClosedXML#303]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**

An exception is raised when running the given code. The problem seems to come from the last param of a "If" formula if it is empty.

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[IssueSheet.xlsx](https://github.com/ClosedXML/ClosedXML/files/989213/IssueSheet.xlsx)

**Code to reproduce problem:**
```c#
public void Main()
{
            using (FileStream fileStream = new FileStream(@"IssueSheet.xlsx", FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
            {
                using (XLWorkbook workbook = new XLWorkbook(fileStream, XLEventTracking.Disabled))
                {
                    var sheet = workbook.Worksheets.Worksheet(1);
                    var goodCell = sheet.Cell(2, 1);
                    var badCell = sheet.Cell(1, 1);
                    Console.WriteLine(goodCell.Value); // this cell works it has the Formula  =IF(TRUE,1,"")
                    Console.WriteLine(badCell.Value);// this cell doesn't work (System.Exception: 'Expression expected.') it has the Formula  =IF(TRUE,1,)
                }
            }
}
```

**Comment by igitur** [comment]
Thanks for the neat code sample. I'll look at it soon. 

Sidenote: you don't need to use `FileStream`. You can pass the file path directly to the `XLWorkbook` constructor.

**Comment by igitur** [comment]
Ok, the `=IF(TRUE,1,)` formula, with the empty last parameter is a really weird case.

**Comment by igitur** [comment]
Please test with the CI build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.291/artifacts

**Comment by Tarboeuf** [comment]
Yes, that works.

**Thank you for your fast answer.**

And for your advice.
