### ISSUE TITLE
[Question] How do I get the 64bit version of this dll?

### ISSUE THREAD

**Issue by koorellasuresh** [ClosedXML/ClosedXML#305]

**Comment by koorellasuresh** [comment]
[Question] How do I get the 64bit version of this dll? I am actually seeing some OOM failures in the current version and from the history - I can see a suggestion to move to 64bit. 

Checking if you already come across the pros of moving to 64bit version.

**Comment by koorellasuresh** [comment]
sorry for the messy title - issue submitted by mistake before the completion and it is not allowing me to edit the subject.

**Comment by igitur** [comment]
The library is built in `AnyCPU` mode, which means it will work for both 32bit and 64bit systems. See more info about `AnyCPU` builds at http://stackoverflow.com/a/516740/179494 .

**Comment by koorellasuresh** [comment]
Thanks a lot.
