### ISSUE TITLE
Crash on Invalid Color Index

### ISSUE THREAD

**Issue by crockeo** [ClosedXML/ClosedXML#307]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**

Upon saving an Excel workbook with an invalid color (e.g. `81`, but presumably any number `>65`), ClosedXML crashes with a `System.Collections.Generic.KeyNotFoundException`.

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

Load and save an Excel workbook with an invalid color index.

**What is the expected behavior or new feature?**

Provide more useful error information, or automatically reset color to an available default style.

**Did this work in previous versions of our tool?  Which versions?**

N/A (untested)

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
public void Main()
{
    string INPUT_PATH = "/path/to/excel/file.xlsx";
    string OUTPUT_PATH = "/path/to/output/file.xlsx";

    using (var wb = new XLWorkbook(INPUT_PATH, XLEventTracking.Disabled)) {
        using (var fs = new FileStream(OUTPUT_PATH, FileMode.Create))
        {
            wb.SaveAs(fs, false);
        }
    }
}
```

**Comment by igitur** [comment]
Please attach the problem file.

**Comment by crockeo** [comment]
(Publicly available) salary info table that has this issue:
 [09Salaries17FORM_TX_HEC17_RenameSheet.xlsx](https://github.com/ClosedXML/ClosedXML/files/994436/09Salaries17FORM_TX_HEC17_RenameSheet.xlsx)

**Comment by crockeo** [comment]
I was looking around a little, and it looks like there's a correct and an incorrect implementation of indexed colors available. In XLWorkbook's GetColor(...) we have:

```c#
else if (color.Indexed != null && color.Indexed < 64)
    retVal = XLColor.FromIndex((Int32)color.Indexed.Value);
```

but the faulty implementation is in XLColor_Public.cs where it is instead implemented as:

```c#
if (_colorType == XLColorType.Indexed)
    return IndexedColors[_indexed].Color;
```

Obviously the different implementation contexts imply different usages (e.g. assigning `retVal` rather than `return`ing), but it seems like the latter should be `if (_colorType == XLColorType.Indexed && _indexed < 64)`?

**Comment by igitur** [comment]
The `81` seems to indicate something special. Other people have noticed it too, e.g. http://stackoverflow.com/questions/14710674/what-does-color-indexed-81-mean . But I can't find any definitive answers yet. I want to know what color to return in the case that the index is 81.

**Comment by igitur** [comment]
Please use the CI build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.293/artifacts to test this.

**Comment by mcastillob** [comment]
> Tabla de información de salarios (disponible públicamente) que tiene este problema: [09Salaries17FORM_TX_HEC17_RenameSheet.xlsx](https://github.com/ClosedXML/ClosedXML/files/994436/09Salaries17FORM_TX_HEC17_RenameSheet.xlsx)


Color error 81 is in the notes that are generally hidden

![error notas documento](https://github.com/user-attachments/assets/d91a42bf-966a-4b1d-9c48-cc36f2edb0b9)

One solution is to eliminate the notes or add the color index 81

![none 81](https://github.com/user-attachments/assets/02c79a54-0306-4246-b79e-a61ab7e7cc76)
