### ISSUE TITLE
Error when i use range.CreateTable() and open the Excel file. 

### ISSUE THREAD

**Issue by jbranders** [ClosedXML/ClosedXML#308]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**
If i open my generated excel file i got the follow error. 
![image](https://cloud.githubusercontent.com/assets/16958349/25988782/a6ac64ac-36f9-11e7-8382-a5e549610e24.png)

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**
For reproduce this behavior, see code below. My Excel version is 2013 and i save the file as XLSX. 

**What is the expected behavior or new feature?**
I expect that the Excel opens without errors.
[Events.xlsx](https://github.com/ClosedXML/ClosedXML/files/995434/Events.xlsx)

- [ X] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
                var range = ws.Range(ws.FirstCellUsed(), ws.LastCellUsed());
                range.CreateTable();
```
[Events.xlsx](https://github.com/ClosedXML/ClosedXML/files/995443/Events.xlsx)

**Comment by igitur** [comment]
Ignore the reference to PR309. It was done by mistake and was meant for another issue.

**Comment by igitur** [comment]
Please post your _full_ code. I need to know how you're generating your Excel file. Are you creating a totally new one from scratch? Are you opening a template file? If so, attach the template. etc.

**Comment by jbranders** [comment]
I create a new Excel file from scratch, no template file.

**Comment by igitur** [comment]
No code. No fix.

**Comment by jbranders** [comment]
Okay, here is the code. 

`    public class BLReporting
    {
        // Variabelen
        ReportRepository _reportRepos = null;
        private XLWorkbook wb = new XLWorkbook();

        public BLReporting(ClientContext ctx)
        {
            _reportRepos = new ReportRepository(ctx);
        }

        public void GenerateReport()
        {
            // Variabelen and data
            List<HREvent> allEvents = _reportRepos.GetAllEvents();
            string worksheetName = null;
            int count = 2;

            // Generate workbooks in Excel with the data
            foreach (HREvent aEvent in allEvents)
            {
                // Check if worksheet already exists or not.
                worksheetName = GetWorksheetName(aEvent.Name);
                var ws = wb.Worksheets.FirstOrDefault(x => x.Name.Equals(worksheetName));

                // If worksheet not exists create a new one. 
                if (ws == null)
                {
                    // Initiate the count again for the cell rows. 
                    count = 2;

                    // Create new workbook
                    ws = wb.Worksheets.Add(worksheetName);
                }

                // Create worksheet header
                CreateHeader(ws);

                // Insert all related subscriber to the worksheet.
                InsertSubscribers(ws, aEvent, ref count);

                // Adjust all columns in workbooksheet. 
                ws.Columns().AdjustToContents();

                // Upload to SharePoint
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    stream.Position = 0;

                    _reportRepos.SaveToLibrary(stream);
                }

                // Dispose workbook
                ws.Dispose();
            }
        }

        public void CreateHeader(IXLWorksheet sheet)
        {
            sheet.Cell("A1").Value = "Event";
            sheet.Cell("B1").Value = "Begintijd";
            sheet.Cell("C1").Value = "Eindtijd";
            sheet.Cell("D1").Value = "Lokaal";
            sheet.Cell("E1").Value = "Naam";
            sheet.Cell("F1").Value = "E-mail";
        }

        public void InsertSubscribers(IXLWorksheet sheet, HREvent hrEvent, ref int count)
        {
            // Get all related subsribers
            foreach (HRSubscriber aSubscriber in _reportRepos.GetAllSubscribers(hrEvent.EventId))
            {
                // Set value to column
                sheet.Cell("A" + count).Value = hrEvent.Name;
                sheet.Cell("B" + count).Value = hrEvent.StartTime.ToString("dd-MM-yyyy H:mm");
                sheet.Cell("C" + count).Value = hrEvent.EndDate.ToString("dd-MM-yyyy H:mm");
                sheet.Cell("D" + count).Value = hrEvent.Location.ToString();
                sheet.Cell("E" + count).Value = aSubscriber.Name;
                sheet.Cell("F" + count).Value = aSubscriber.Email;

                // Increase count
                count++;
            }
        }

        public string GetWorksheetName(string name)
        {
            string worksheetName = Regex.Replace(name, @"[;\/:*?""<>|&']", String.Empty);
            worksheetName = worksheetName.Length > 31 ? worksheetName.Substring(0, 31) : worksheetName;

            return worksheetName;
        }
    }`

**Comment by jbranders** [comment]
Pay attention, this is code that is in production, but if i added the CreateTable() i got a couple of errors when i opening the Excel so it's tempory deleted from my code.

**Comment by igitur** [comment]
Code guidelines:

> Where possible, post full code to reproduce your issue that adheres to:
> - Fully runnable. I should be able to copy and paste this code into a 
>   console application and run it without having to edit it much.
> - Declare all your variables (this follows from the previous point)
> - The code should be a minimal code sample to illustrate issue. The code 
>   samples on the wiki are good examples of the terseness that I want. Don't
>   post your full application.

**Comment by jbranders** [comment]
`XLWorkbook wb = new XLWorkbook();
            var ws = wb.Worksheets.Add("TestCase");

            ws.Cell("A1").Value = "Event";
            ws.Cell("B1").Value = "Begintijd";
            ws.Cell("C1").Value = "Eindtijd";
            ws.Cell("D1").Value = "Lokaal";
            ws.Cell("E1").Value = "Naam";
            ws.Cell("F1").Value = "E-mail";

            ws.Cell("A2").Value = "CreateTable";
            ws.Cell("B2").Value = "12:00";
            ws.Cell("C2").Value = "13:00";
            ws.Cell("D2").Value = "5C";
            ws.Cell("E2").Value = "Hello World";
            ws.Cell("F2").Value = "helloworld@gmail.com";

            ws.Columns().AdjustToContents();
            ws.Range(ws.FirstCellUsed(), ws.LastCellUsed()).CreateTable();

            wb.SaveAs(@"C:\temp\test.xlsx");`

**Comment by igitur** [comment]
Cannot reproduce any problems with that code. I attach the file that I generated using it.
[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/1000650/test.xlsx)

Please try with the latest code from the `develop` branch in this git repo.

**Comment by jbranders** [comment]
Hi, I have download the latest github version and it's working now. But if i install it in VS with nuget package i got an error. But i will close this one.
