### ISSUE TITLE
Improve image-related API interaction

### ISSUE THREAD

**Issue by clinchergt** [ClosedXML/ClosedXML#311]
**Do you want to request a *feature* or report a *bug*?**
- [x] Feature

**What is the current behavior?**

Follow up from #48 

Adding images is a bit cumbersome at the moment. You need to add markers and depending on the amount you add and whether the `XLPicture` is absolute

**What is the expected behavior or new feature?**

Making image handling more seamless. Maybe allowing directly choosing the anchor type? Allowing setting noresize/moving/rescaling properties directly maybe as well?

Still not sure how duplicate detection would work either. (I'm still not sure if image duplicate detection should be ClosedXML's responsibility)

Input from other contributors is gonna be key here.

**Comment by igitur** [comment]
I have a few ideas. Will see what I can do. Have some exams coming up, so might disappear off the radar a bit.

**Comment by clinchergt** [comment]
Now that #323 was merged, I'm pretty happy with how the API works now.

The fact that you can now reference XLCells, setting offsets became more intuitive, images aren't locked in place anymore, and the image format implementation isn't as hacky anymore makes me think this issue should be closed now.

Huge nitpick here but this shouldn't be needed it seems: https://github.com/ClosedXML/ClosedXML/blob/develop/ClosedXML_Examples/ImageHandling/ImageAnchors.cs#L72

The new implementation now makes compiling require C# 6+ but I'm guessing everyone is fine with that.

Amazing work, @igitur

**Comment by igitur** [comment]
Thanks @clinchergt 

Yes, you're right, that line isn't currently necessary. However, I plan to introduce further enhancements to change the Placement type without having to call the `.MoveTo()` method. So that line is more of a placeholder for future stuff.

**Comment by igitur** [comment]
Fixed via #323
