### ISSUE TITLE
System.Exception: There isn't a worksheet named '[19]PPE-2004'.

### ISSUE THREAD

**Issue by VenkatGurram** [ClosedXML/ClosedXML#317]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

**What is the expected behavior or new feature?**
I am just trying to read the excel file and get the first worksheet name. It works for most of the file but for the attached excel file it give me the below error

{System.Exception: There isn't a worksheet named '[19]PPE-2004'.
   at ClosedXML.Excel.XLWorksheets.Worksheet(String sheetName)
   at ClosedXML.Excel.XLWorkbook.SetColumnsOrRowsToRepeat(String area)
   at ClosedXML.Excel.XLWorkbook.LoadPrintTitles(DefinedName definedName)
   at ClosedXML.Excel.XLWorkbook.LoadDefinedNames(Workbook workbook)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName)
   at ClosedXML.Excel.XLWorkbook.Load(String file)
   at ClosedXML.Excel.XLWorkbook..ctor(String file, XLEventTracking eventTracking)
   at ClosedXML.Excel.XLWorkbook..ctor(String file)
   at CARS.Core.Utilities.GetSheetname(String file, String SheetName, Boolean includeExtension)}

**Did this work in previous versions of our tool?  Which versions?**
Tried latest 2 version and did not work.

- [TestFile.xlsx](https://github.com/ClosedXML/ClosedXML/files/1017366/TestFile.xlsx)
] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```VB.Net

public void Main()
{
[TestFile.xlsx](https://github.com/ClosedXML/ClosedXML/files/1017368/TestFile.xlsx)

    Try
                Dim workbook = New XLWorkbook(file)
                'Get the first Worksheet
                Dim ws = workbook.Worksheet(1)
                retSheetName = ws.Name
Catch ex As Exception

End Try
}
```

**Comment by vbjay** [comment]
Worksheet (1) gets the second sheet.

**Comment by VenkatGurram** [comment]
Getting the exception in the first line of code while loading the file into XLWorkbook not even going to second line of code. Below is the file I am trying to read.

[TestFile.xlsx](https://github.com/ClosedXML/ClosedXML/files/1017375/TestFile.xlsx)

Dim workbook = New XLWorkbook(file)

**Comment by igitur** [comment]
You have a gazillion broken defined names. I think they are the cause of this problem. I'll look into a workaround, but in the meantime, you could try deleting them.

![image](https://cloud.githubusercontent.com/assets/145854/26296919/10add528-3ed1-11e7-9672-039c36b9c379.png)

**Comment by igitur** [comment]
It turns out it was the invalid print titles that were causing the exception. 
```xml
<x:definedName name="_xlnm.Print_Titles">'[19]PPE-2004'!$A$1:$A$65536,'[19]PPE-2004'!$A$1:$IV$7</x:definedName>
```

**Comment by igitur** [comment]
Please test with the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.307/artifacts

**Comment by VenkatGurram** [comment]
I replaced the .dll reference in the project with the build 0.8.307 one you specified. Getting the following error "Imports ClosedXML.Excel". 

Namespace or type specified in the Import 'ClosedXML.Excel' doesn't contain any public member or cannot be found. Make sure the namespace or the type is defined and contains at least one public member. Make sure the imported element doesn't use any aliases

**Comment by VenkatGurram** [comment]
I am using VS 2013 with Target Framework 4.5.1.  Can you recompile the DLL with framework target version 4.0 instead of 4.5.2.  This is one of difference I see when I decompile the DLL and compare with the current version 87.1
