### ISSUE TITLE
Remove Autofilter problem

### ISSUE THREAD

**Issue by skkanagaraj** [ClosedXML/ClosedXML#32]
worksheet.AutoFilter.Enabled=false;

Throws Exception

**Comment by igitur** [comment]
That's a really really short bug report. Could you by any chance give a bit more? Maybe some code samples of how you build up the worksheet? Are you sure your AutoFilter is enabled?

**Comment by skkanagaraj** [comment]
worksheet.AutoFilter.Enabled=false;

It throws "object reference not set to an instance of an object"

**Comment by igitur** [comment]
Post the your full code, please.

**Comment by skkanagaraj** [comment]
var workbook = new XLWorkbook();
worksheet = workbook.AddWorksheet(Datatbl, "Products");
worksheet.AutoFilter.Enabled=false;

Here 
Datatbl - is datatable, contains list of products.

**Comment by igitur** [comment]
I cannot reproduce the problem. Which version of ClosedXML are you using?

**Comment by skkanagaraj** [comment]
I am using v4.0.30319.

**Comment by igitur** [comment]
Which version of **ClosedXML** are you using?

**Comment by skkanagaraj** [comment]
version 0.76.0

**Comment by igitur** [comment]
Upgrade to 0.80.1 
https://www.nuget.org/packages/ClosedXML/

**Comment by skkanagaraj** [comment]
Now i installed  0.80.0.1

var workbook = new XLWorkbook();
worksheet = workbook.AddWorksheet(Dt, "Test");
worksheet.AutoFilter.Enabled=false;
workbook.SaveAs("C:\\Temp\\HelloWorld" + new Random().Next() + ".xlsx");

The column filter is not disabled. I have set worksheet.AutoFilter.Enabled=false;

**Comment by skkanagaraj** [comment]
![column filter](https://cloud.githubusercontent.com/assets/8091356/18593702/4e01d03a-7c5a-11e6-880e-dfc7af074b05.png)

**Comment by dayaaltosinc** [comment]
porblem in remove autofilter

**Comment by igitur** [comment]
@dayaaltosinc Please post a complete code sample to illustrate your problem.
