### ISSUE TITLE
Use ActiveBook 

### ISSUE THREAD

**Issue by EnOane** [ClosedXML/ClosedXML#321]
hello, I'm stupid Russian, how can I use "activebook" like

Workbook activeBook = Globals.ThisAddIn.Application.ActiveWorkbook;
 ```

**Comment by vbjay** [comment]
This is not an excel automation library.

**Comment by EnOane** [comment]
Else, I can't use this like that?

**Comment by igitur** [comment]
The closest equivalent is:
```c#
using (var workbook = new XLWorkbook())
{
    // use the workbook variable as you like
}
```
