### ISSUE TITLE
DATE Function bug

### ISSUE THREAD

**Issue by DmitriyPotapov** [ClosedXML/ClosedXML#325]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**
In Excel Worksheet i have a formula:
`=DATE(A2;B2+D2;C2)`
My cell values is: 

- A2 = 2017;
- B2 = 10;
- C2 = 25;
- D2 = 5;

Excel calculate this formula as 25.03.2018. But when I trying to read the value of a cell using a function: **_sheet.Cell("E2").GetString()_** ClosedXML throw an exception:
`Exception Message: Year, Month, and Day parameters describe an un-representable DateTime.
StackTrace:    at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   at ClosedXML.Excel.CalcEngine.Functions.DateAndTime.Date(List1 p) in C:\Sources\GitLab\WebLeasingMVC\ClosedXML\ClosedXML\Excel\CalcEngine\Functions\DateAndTime.cs:line 94 .........`.
In debug mode in a function **_ClosedXML.Excel.CalcEngine.Functions.DateAndTime.Date(List<Expression> p)_**, I have such runtime values

```c#
        private static object Date(List<Expression> p)
        {
            var year = (int)p[0];     // Runtime value 2017
            var month = (int)p[1]; //Runtime value 15
            var day = (int)p[2];      //Runtime value 25

            //Exception in this line
            return (int)Math.Floor(new DateTime(year, month, day).ToOADate()); 
        }
```
I think this is because the function incorrectly recognizes a part of the formula _**B2+C2**_ in Excel function DATE().

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

**What is the expected behavior or new feature?**

**Did this work in previous versions of our tool?  Which versions?**

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
public void Main()
{
      var workbook = new XLWorkbook(uploadedFile.InputStream);
      IXLWorksheet sheet;
      if (!workbook.TryGetWorksheet("ClosedXmlBug", out sheet))
                        return ;
    
     var bugDate = sheet.Cell("B4").GetString();  //Exception
     Console.WriteLine(bugDate.ToString());
}
```
**Code to temporary fix a problem:**
```c#
 private static object Date(List<Expression> p)
        {
            var year = (int)p[0];
            var month = (int)p[1];
            var day = (int)p[2];
            int tempMonth = 0;

            //Fix for problem
            if (month > 12)
            {
                tempMonth = month - 12;
                var tempDate = new DateTime(year, 12, day).AddMonths(tempMonth);
                return (int)Math.Floor(new DateTime(tempDate.Year, tempDate.Month, tempDate.Day).ToOADate());
            }
            return (int)Math.Floor(new DateTime(year, month, day).ToOADate());
        }
```
[ClosedXmlBug.xlsx](https://github.com/ClosedXML/ClosedXML/files/1039243/ClosedXmlBug.xlsx)

**Comment by DmitriyPotapov** [comment]
When I execute this code with the same data
```c#
public void Main()
{
      var workbook = new XLWorkbook(uploadedFile.InputStream);
      IXLWorksheet sheet;
      if (!workbook.TryGetWorksheet("ClosedXmlBug", out sheet))
                        return ;
    
     var bugDate = sheet.Cell("B4").GetDateTime();  //Exception
     Console.WriteLine(bugDate.ToString());
}
```
I Have an exception 
`
Message: Cannot convert cell value to System.DateTime
StackTrace:    at ClosedXML.Excel.XLCell.GetValue[T]() in C:\Sources\GitLab\WebLeasingMVC\ClosedXML\ClosedXML\Excel\Cells\XLCell.cs:line 282
`

**Comment by Pyropace** [comment]
could you create a pull request for your fix ?
