### ISSUE TITLE
Word version for ClosedXML

### ISSUE THREAD

**Issue by juanperezADD** [ClosedXML/ClosedXML#331]
Are there any plans to make a Word version for ClosedXML?

We think that both the community and us will be very interested.

**Comment by igitur** [comment]
I don't have time for such a big project, but I will gladly accept pull requests that start this, even if just a partial implementation.

**Comment by megapro17** [comment]
So there are no tools for manipulating Word and PowerPoint documents other than OpenXml, which is pretty low-level?
There is good old npoi, but it's a different beast. It does have one nice feature - support for legacy formats.
