### ISSUE TITLE
Exception thrown while reading file with a formula applied on an Excel table.

### ISSUE THREAD

**Issue by krishnaps1592** [ClosedXML/ClosedXML#332]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**While reading a spreadsheet with a RIGHT function applied on a "Table Column" throws "Identifier expected" exception.**

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

**The file containing the formula must be read correctly.**

**Not sure. But was using the latest version.**

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Formula_File.xlsx](https://github.com/ClosedXML/ClosedXML/files/1051341/Formula_File.xlsx)

**Code to reproduce problem:**
```c#
public void Main()
{
    // Where possible, post full code to reproduce your issue that adheres to:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
`try
			{
				using (var workBook = new XLWorkbook("Formula_File.xlsx"))
				{
					var sheet = workBook.Worksheet(1);
					Console.WriteLine("Reading Excel File...");
					var fields = sheet.Row(2)
									.Cells(1, 3)
									.Select(c => c.Value)
									.ToArray();
				}
			}
			catch (Exception ex)
			{
				Console.WriteLine("Error :" + ex.Message);
				Console.ReadKey();
			}`

}
```

**Comment by igitur** [comment]
Table columns are not supported yet. Please use normal `A1` style references.

**Comment by igitur** [comment]
Duplicate of #271

**Comment by krishnaps1592** [comment]
Thank you!
