### ISSUE TITLE
Bug creating Excel 2013 files, DLL modifies value, numbers are shown as dates

### ISSUE THREAD

**Issue by Manuvts** [ClosedXML/ClosedXML#334]
- [x] Bug
- [ ] Feature

Good morning, 
we've found a problem writing numbers to an Excel sheet, the value are transformated to a date, and then this value are transformed again to its date numeric value:

In order to reproduce the BUG, follow the following steps:

-Try to write "29,09" to an Excel file:
`Excel.Worksheet("DATA").Cell(filareport, 17).Value ="29,09"` (you can cast the number if you want, the output is the same)
-Open the Excel file and you'll see the value "29/09/2017" (converts the number into a "day/month" value)
-If the Excel sheet has a "Numeric" format, you will see 43007,00, which is the numeric representation of the mentioned date

**Code to reproduce problem:**
```c#
public void Main()
{
 ClosedXML.Excel.XLWorkbook Excel = new ClosedXML.Excel.XLWorkbook(path + "ExcelName.xlsx");
`Excel.Worksheet("DATA").Cell(filareport, 17).Value ="29,09"` 
Microsoft.Win32.SaveFileDialog saveFileDialog1 = new Microsoft.Win32.SaveFileDialog();

                saveFileDialog1.InitialDirectory = (Environment.SpecialFolder.MyDocuments).ToString();
                saveFileDialog1.Filter = "Excel Files|*.xlsx";
                saveFileDialog1.FilterIndex = 1;
                saveFileDialog1.RestoreDirectory = true;
                saveFileDialog1.FileName = "ExcelName1" +".xlsx";

                if (saveFileDialog1.ShowDialog() == true)
                {
                    string ruta = saveFileDialog1.FileName;
                   if (c_REPORTS.FileIsLocked(ruta) != true)
                    {
                        Excel.SaveAs(ruta);  //Save excel

                        Process.Start(ruta); //Open excel  
                    }
                    else
                    {
                        MessageBox.Show("The file is open. Please, close it before save");
                    }

                }
  }
```

The problem arises with later versions of 0.80.1.
You can try to edit the sheet format (beforo o after writing the file), but the correct value never appears.

Thank you in advance, 

Manuel

**Comment by igitur** [comment]
And if you do
```c#
Excel.Worksheet("DATA").Cell(filareport, 17).Value = 29.09;
```
?

**Comment by vbjay** [comment]
https://github.com/closedxml/closedxml/wiki/Cell-Values

**Comment by Manuvts** [comment]
Using code:

`Excel.Worksheet("DATA").Cell(filareport, 17).Value = 29.09;`

the output is the expected, it Works fine for me..
But i still think that if you execute the next:
`Excel.Worksheet("DATA").Cell(filareport, 17).Value = "29.09";`
you don't want to see a date, nor its numeric value...

Thanks again, i'll try to implement a function that returns a double (from a string), we just need to check that the string parameter for this function has correct range (not nulls, not letters, etc...)

NAd finally thanks for the link vbjay

**Comment by igitur** [comment]
If you use `.Value`, ClosedXML makes a guess about what data type you want. If you know the data type that you want, in this case `string`, you can use `Excel.Worksheet("DATA").Cell(filareport, 17).SetValue<string>("29.09")` or you can prepend your value with a `'` (refer to the page that @vbjay mentioned).

**Comment by Manuvts** [comment]
Yes, but if you use that, then you can't use the value as a number, for formules, etc... 
The option the enter a doublé value is better for e, becasue the name must postprocessed by Excel once created..

Thanks again
