### ISSUE TITLE
XML files inside XLSX are not encoded the same way Excel does

### ISSUE THREAD

**Issue by rwil02** [ClosedXML/ClosedXML#336]
[Content_Types_pre.zip](https://github.com/ClosedXML/ClosedXML/files/1053634/Content_Types_pre.zip)

Attached is a pre/post for the content types file.  But styles, rel, workbook, etc are also affected.
Difference is 
"Open in Excel", press control-B twice, and save the file
"Pre" contains Unicode byte markers at the start of the files
"Post" does not

**Comment by igitur** [comment]
It is not a goal of ClosedXML to produce binary replicas of what Excel produces. Why does this matter to you? If the resulting files are not corrupt and look and act the same, it should not be an issue. 

Anyway, (and I haven't double-checked this) I think this is out of ClosedXML's control. ClosedXML is a wrapper around OpenXML, which uses System.IO.Packaging for generating the content.
