### ISSUE TITLE
OpenXML updated to 2.7.1 causes ClosedXML to fail when trying to load OXML 2.5.0

### ISSUE THREAD

**Issue by MarkStega** [ClosedXML/ClosedXML#337]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**
Nuget offers an OpenXML update of 2.7.1; If you install this then ClosedXML fails to load as it tries to load OXML 2.5.0

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**
See current beavior above

**What is the expected behavior or new feature?**
Expect to be able to update OXML and have CXML continue to load.

**Did this work in previous versions of our tool?  Which versions?**
CXML0.87.1 works with OXML 2.5.0

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
n/a

**Comment by igitur** [comment]
Fixed in #225

**Comment by igitur** [comment]
Fixed in #292
