### ISSUE TITLE
Duplicate values produce while using wc.RichText.AddText("value"), multiple times in a loop

### ISSUE THREAD

**Issue by harshgangwar** [ClosedXML/ClosedXML#342]
```c#
public static string AddHeaderRows(ref int varRowNum, ref IXLWorksheet ws, string varListTitle)
{
    string rtn = "";

    //---- get header object
    var wrkInfoVars = default(MpgInfoVars);
    wrkInfoVars = (MpgInfoVars)SC.MpgInfoVars;

    int pos1 = 0;
    int len1 = 0;
    int inLen1 = 0;
    IXLCell wc = null;

    var arT = new[] { "Model Plan Area:", "Model Plan ID:", "Top Map Title:", "List Title:", "Date/Time:", "Date/Time:" };
    string wrkDateTime = Strings.Format(DateAndTime.Now, "yyyy/MM/dd hh:mm:ss tt");
    var arC = new[] { wrkInfoVars.ModelPlanAreaName, wrkInfoVars.MPAExtID, wrkInfoVars.TopMapTitle, varListTitle, wrkDateTime, wrkDateTime };

    var arL = new[] { 8, 12, 13, 20, 18, 8 };

    string wrkDashes = "--------------------------------------";
    string wrkInsert = "";
    int sp1 = 0;

    SC1.XlsxHeaderRowCount = arT.Length;
    for (int n = 0; n <= arT.Length - 1; n++)
    {
        pos1 = 0;
        wc = ws.Cell(varRowNum, 1);

        wrkInsert = Strings.Left(wrkDashes, arL[n]);

        var _with1 = wc.RichText;
        _with1.AddText(arT[n]);
        len1 = Strings.Len(arT[n]);
        _with1.Substring(pos1, len1).SetFontSize(10);
        pos1 = pos1 + len1;

        _with1.AddText(wrkInsert);
        len1 = Strings.Len(wrkInsert);
        _with1.Substring(pos1, len1).SetFontSize(10);
        _with1.Substring(pos1, len1).FontColor = XLColor.White;
        pos1 = pos1 + len1;

        _with1.AddText(arC[n]);
        len1 = Strings.Len(arC[n]);
        _with1.Substring(pos1, len1).SetFontSize(11);
        _with1.Substring(pos1, len1).SetBold();
        varRowNum += 1;
    }

    return "OK";
}
```

![excelsheetbug](https://user-images.githubusercontent.com/8593845/27072893-8cdb6924-503f-11e7-9aa3-ecd6324d19d9.png)

**Comment by igitur** [comment]
That's not valid C#. Did you use a VB.NET to C# translator?! Put in the effort and post a clean, reproducible code sample (VB.NET or C# is fine). Exclude any of your own variables and entities (e.g. `MpgInfoVars`). In short, I need a code sample that I can copy and paste into a console application and reproduce the problem.

**Comment by harshgangwar** [comment]
@igitur Thanks for your time, Yes you are correct, you can't run it on your console and its translated code from VB.Net to C# but the second thing I can't give you the runnable code, because its further code is used in another class or method. but I will try to give you the more specified, clean code...Thanks for help

**Comment by harshgangwar** [comment]
using System;

public class TestClass
{
   public static string AddHeaderRows()
    {  
        //Part of another class/method
        //---- create workbook
        XLWorkbook wb = new XLWorkbook();
        //---- create worksheet
        var ws = wb.Worksheets.Add("AMPTK_Download");
        //End part

        //RowNumber initialized zero
        int rowNum = 0;

        int pos1 = 0;
        int len1 = 0;
        IXLCell wc = null;


        var arT = new[] { "Model Plan Area:", "Model Plan ID:", "Top Map Title:", "List Title:", "Date/Time:", "Date/Time:" };
        var arC = new[] { "Temp", "B34RR2ZZ", "Central Process", "Map Parts,Evaluations, Priorities", "2017/06/13/03:32:34 PM", "2017/06/13/03:32:34 PM" };

        //Array for space between content of arT and arC
        var arL = new[] { 8, 12, 13, 20, 18, 8 };


        string wrkDashes = "--------------------------------------";
        string wrkInsert = "";

        for (var n = 0; n <= arT.Length - 1; n++)
        {
            pos1 = 0;
            wc = ws.Cell(rowNum, 1);

            wrkInsert = Strings.Left(wrkDashes, arL[n]);

            wc.RichText.AddText(arT[n]);
            len1 = Strings.Len(arT[n]);
            wc.RichText.Substring(pos1, len1).SetFontSize(10);
            pos1 = pos1 + len1;

            wc.RichText.AddText(wrkInsert);
            len1 = Strings.Len(wrkInsert);
            wc.RichText.Substring(pos1, len1).SetFontSize(10);
            wc.RichText.Substring(pos1, len1).FontColor = XLColor.White;
            pos1 = pos1 + len1;

            wc.RichText.AddText(arC[n]);
            len1 = Strings.Len(arC[n]);
            wc.RichText.Substring(pos1, len1).SetFontSize(11);
            wc.RichText.Substring(pos1, len1).SetBold();

            rowNum += 1;
        }

        //Part of a another class/Method, but mentioned here for Readability
        MemoryStream ms = new MemoryStream();
        wb.SaveAs(ms);
        ms.Seek(0, SeekOrigin.Begin);

        //for zip download 
        var wrkFs = new ZipDownloadContentPair
        {
            FileName = fileName,//any file name 
            ContentStream = ms
        };

        //Note: Local project variable where ContentArrayForDownLoad is a type of ArrayList
        var wrkAr = SC.ContentArrayForDownLoad;
        wrkAr.Add(wrkFs);
        SC.ContentArrayForDownLoad = wrkAr;

        return "OK";
    }

    //struct having file name, memoryStream content 
    public struct ZipDownloadContentPair
    {
        public string FileName;
        public MemoryStream ContentStream;
    }

}

**Comment by harshgangwar** [comment]
Actual Output you can consider same as mentioned before

**Comment by igitur** [comment]
I don't think you ran that code before posting it. I had to change `int rowNum = 0;` to `int rowNum = 1;`.

After that change, I get this output. I don't see anything wrong:
![image](https://user-images.githubusercontent.com/145854/27078112-b751fb30-5032-11e7-9612-dc298ced6b59.png)

**Comment by harshgangwar** [comment]
Thanks for your solution, Actually this is one of the module, actual module is more complex where I'm getting duplicate values. 
//---------------------

using System;

public class Class1
{
    /// <summary>
    /// Add Main Text method where duplicate values are coming, 
    /// Note:: This method is calling in a loop, 
    /// </summary>
    /// <param name="rx">rx holding values which is used for write and used for checking condition</param>
    /// <param name="varRowNum">row number starting from 8 and increasing as per loop
    /// </param>
    /// <param name="varListCode">used for checking the condition</param>
    /// <param name="wC1">IXLCell reference</param>
    public void AddMainText(XLSXRow rx, int varRowNum, string varListCode, ref IXLCell wC1)
    {

        //Part of another class/method
        //---- create workbook
        XLWorkbook wb = new XLWorkbook();
        //---- create worksheet
        var ws = wb.Worksheets.Add("AMPTK_Download");
        //End part

        string wrkMainText = "";
        string wrkPartTypeText = "";
        string wrkFirstSubPartText = "";
        string wrkSecondSubPartText = "";
        string wrkFlowDirectionText = "";

        int pos1 = 0;
        int len1 = 0;


        string sp = " ";
        string sp1 = ": ";

        try
        {
            wC1 = ws.Cell(varRowNum, 1);

            //----- start of rich text for Main Text column
            pos1 = 0;

            var _with1 = wC1.RichText;

            //---- SecondSubType
            switch (rx.SecondSubType)
            {
                case "PCA":
                case "":
                    break;
                default:
                    wrkSecondSubPartText = rx.SecondSubType + sp + sp;
                    len1 = Strings.Len(wrkSecondSubPartText);
                    _with1.AddText(wrkSecondSubPartText);
                    _with1.Substring(pos1, len1).SetItalic();
                    _with1.Substring(pos1, len1).SetFontSize(8);
                    pos1 += len1;
                    break;
            }



            //----- Flow Direction
            if (!string.IsNullOrEmpty(rx.FlowDirection))
            {
                wrkFlowDirectionText = TranslateFlowDirection(rx.FlowDirection) + sp1 + sp;
                len1 = Strings.Len(wrkFlowDirectionText);
                _with1.AddText(wrkFlowDirectionText);
                _with1.Substring(pos1, len1).SetFontSize(9);
                _with1.Substring(pos1, len1).SetBold();
                pos1 += len1;
            }

            //---- FirstSubType as prefix
            switch (rx.PartType)
            {
                case "EVAL":
                    if (!string.IsNullOrEmpty(rx.FirstSubType))
                    {
                        wrkFirstSubPartText = rx.FirstSubType + sp + sp;
                        len1 = Strings.Len(wrkFirstSubPartText);
                        _with1.AddText(wrkFirstSubPartText);
                        _with1.Substring(pos1, len1).SetItalic();
                        _with1.Substring(pos1, len1).SetFontSize(8);
                        pos1 += len1;
                    }
                    break;
                case "NOTE":
                    if (rx.FirstSubType != "Area Name")
                    {
                        wrkPartTypeText = "Note" + sp + sp;
                        len1 = Strings.Len(wrkPartTypeText);
                        _with1.AddText(wrkPartTypeText);
                        _with1.Substring(pos1, len1).SetItalic();
                        _with1.Substring(pos1, len1).SetFontSize(8);
                        pos1 += len1;
                    }
                    break;
                case "DSCL":
                    wrkFirstSubPartText = rx.FirstSubType + sp + sp;
                    len1 = Strings.Len(wrkFirstSubPartText);
                    _with1.AddText(wrkFirstSubPartText);
                    _with1.Substring(pos1, len1).SetItalic();
                    _with1.Substring(pos1, len1).SetFontSize(8);
                    pos1 += len1;
                    break;
            }


            //---- MainText
            if (!string.IsNullOrEmpty(rx.MainText))
            {
                wrkMainText = rx.MainText;
                wrkMainText = WebUtility.HtmlDecode(wrkMainText);
                len1 = Strings.Len(wrkMainText);
                _with1.AddText(wrkMainText);

                switch (varListCode)
                {
                    case "MapEval":
                        switch (rx.PartType)
                        {
                            case "BNDR":
                            case "STRR":
                            case "PRCR":
                            case "CLMN":
                                //, "FLWR"
                                _with1.Substring(pos1, len1).SetBold();
                                break;
                            case "NOTE":
                                if (rx.FirstSubType == "Area Name")
                                {
                                    _with1.Substring(pos1, len1).SetBold();
                                }
                                break;
                        }
                        break;
                    case "PCA":
                        switch (rx.PartType)
                        {
                            case "API":
                            case "PCA":
                                _with1.Substring(pos1, len1).SetBold();
                                break;
                        }
                        break;
                    case "Plan":
                        switch (rx.PartType)
                        {
                            case "API":
                                _with1.Substring(pos1, len1).SetBold();
                                break;
                        }
                        break;
                    case "Disc":
                        break;
                }

                _with1.Substring(pos1, len1).SetFontSize(11);
                pos1 += len1;
            }

            switch (rx.PartType)
            {
                case "BNDR":
                case "STRR":
                case "PRCR":
                case "NOTE":
                case "PCA":
                case "API":
                    switch (rx.PartType)
                    {
                        case "BNDR":
                            wrkPartTypeText = sp + sp + sp + sp + "Boundary outside of Central Process";
                            break;
                        case "STRR":
                            wrkPartTypeText = sp + sp + sp + sp + "Physical or Data Storage";
                            break;
                        case "PRCR":
                            if (Strings.InStr(rx.FirstSubType, "Map") != 0)
                            {
                                wrkPartTypeText = sp + sp + sp + sp +
                                                  Strings.Replace(rx.FirstSubType, "Map", " Map") + sp +
                                                  "Central Process";
                            }
                            else
                            {
                                wrkPartTypeText = sp + sp + sp + sp + "Sub-Process of Central Process";
                            }
                            break;
                        case "NOTE":
                            if (rx.FirstSubType == "Area Name")
                            {
                                wrkPartTypeText = sp + sp + sp + sp + "Model Plan Area Name";
                            }
                            break;
                        case "PCA":
                            wrkPartTypeText = sp + sp + sp + sp + "Proposed Change Action";
                            break;
                        case "API":
                            wrkPartTypeText = sp + sp + sp + sp + "Action Plan Item";

                            break;
                    }
                    len1 = Strings.Len(wrkPartTypeText);
                    _with1.AddText(wrkPartTypeText);
                    _with1.Substring(pos1, len1).SetItalic();
                    _with1.Substring(pos1, len1).SetFontSize(8);
                    pos1 += len1;
                    break;
            }
        }
        catch (Exception ex)
        {
            string exmsg = ex.Message;
            string wrkStop = "";
            ErrorLogService.WriteError(ex, "AddMainText", ServiceName);
        }
    }

}
![duplicatemaintext](https://user-images.githubusercontent.com/8593845/27078893-2c4bbcbc-5053-11e7-930a-7806ccbcc0ca.png)
![maintextclass](https://user-images.githubusercontent.com/8593845/27078901-35db4cde-5053-11e7-854b-1fd625536fd3.png)

**Comment by harshgangwar** [comment]
Actually Problem is with RichText, if I used wc.Value instead of RichText then it's working fine. But I can't add the styling in wc.Value by its index. You can see here I am adding more than one value in .AddText() method and applying styling accordingly....Thanks in advance if you could understand this unclear code.

**Comment by igitur** [comment]
So create a simplified, reduced test case that reproduces the problem.

Francois Botha

**Comment by harshgangwar** [comment]
Simply after replacing RichText to Value, no repetition of values, output is fine, but not able to use styling, as I have to use RichText.SubString to use index/position but as I used RichText anywhere, values are duplicating.

Updated Code:-

using System;

public class Class1
{
    public void AddMainText(XLSXRow rx, int varRowNum, string varListCode, ref IXLCell wC1)
    {

        //Part of another class/method
        //---- create workbook
        XLWorkbook wb = new XLWorkbook();
        //---- create worksheet
        var ws = wb.Worksheets.Add("AMPTK_Download");
        //End part

        //Add this variable to hold the string that will be added to the value function
        string tempMainTxt;

        string wrkMainText = "";
        string wrkPartTypeText = "";
        string wrkFirstSubPartText = "";
        string wrkSecondSubPartText = "";
        string wrkFlowDirectionText = "";

        int pos1 = 0;
        int len1 = 0;


        string sp = " ";
        string sp1 = ": ";

        try
        {
            //---reinitialize the string
            tempMainTxt = string.Empty;

            wC1 = ws.Cell(varRowNum, 1);

            //----- start of rich text for Main Text column
            pos1 = 0;

            var _with1 = wC1.RichText;

            //---- SecondSubType
            switch (rx.SecondSubType)
            {
                case "PCA":
                case "":
                    break;
                default:
                    wrkSecondSubPartText = rx.SecondSubType + sp + sp;
                    len1 = Strings.Len(wrkSecondSubPartText);

                    tempMainTxt = wrkSecondSubPartText;
                    //  _with1.AddText(wrkSecondSubPartText);
                    //_with1.Substring(pos1, len1).SetItalic();
                    //_with1.Substring(pos1, len1).SetFontSize(8);
                    pos1 += len1;
                    break;
            }



            //----- Flow Direction
            if (!string.IsNullOrEmpty(rx.FlowDirection))
            {
                wrkFlowDirectionText = TranslateFlowDirection(rx.FlowDirection) + sp1 + sp;
                len1 = Strings.Len(wrkFlowDirectionText);

                tempMainTxt += wrkFlowDirectionText;
                //_with1.AddText(wrkFlowDirectionText);
                //_with1.Substring(pos1, len1).SetFontSize(9);
                //_with1.Substring(pos1, len1).SetBold();
                pos1 += len1;
            }

            //---- FirstSubType as prefix
            switch (rx.PartType)
            {
                case "EVAL":
                    if (!string.IsNullOrEmpty(rx.FirstSubType))
                    {
                        wrkFirstSubPartText = rx.FirstSubType + sp + sp;
                        len1 = Strings.Len(wrkFirstSubPartText);

                        tempMainTxt += wrkFirstSubPartText;
                        //_with1.AddText(wrkFirstSubPartText);
                        //_with1.Substring(pos1, len1).SetItalic();
                        //_with1.Substring(pos1, len1).SetFontSize(8);
                        pos1 += len1;
                    }
                    break;
                case "NOTE":
                    if (rx.FirstSubType != "Area Name")
                    {
                        wrkPartTypeText = "Note" + sp + sp;
                        len1 = Strings.Len(wrkPartTypeText);

                        tempMainTxt += wrkPartTypeText;
                        //_with1.AddText(wrkPartTypeText);
                        //_with1.Substring(pos1, len1).SetItalic();
                        //_with1.Substring(pos1, len1).SetFontSize(8);
                        pos1 += len1;
                    }
                    break;
                case "DSCL":
                    wrkFirstSubPartText = rx.FirstSubType + sp + sp;
                    len1 = Strings.Len(wrkFirstSubPartText);

                    tempMainTxt += wrkFirstSubPartText;
                    //_with1.AddText(wrkFirstSubPartText);
                    //_with1.Substring(pos1, len1).SetItalic();
                    //_with1.Substring(pos1, len1).SetFontSize(8);
                    pos1 += len1;
                    break;
            }


            //---- MainText
            if (!string.IsNullOrEmpty(rx.MainText))
            {
                wrkMainText = rx.MainText;
                wrkMainText = WebUtility.HtmlDecode(wrkMainText);
                len1 = Strings.Len(wrkMainText);
                tempMainTxt += wrkMainText;
              //  _with1.AddText(wrkMainText);

                switch (varListCode)
                {
                    case "MapEval":
                        switch (rx.PartType)
                        {
                            case "BNDR":
                            case "STRR":
                            case "PRCR":
                            case "CLMN":
                                //, "FLWR"
                              //  _with1.Substring(pos1, len1).SetBold();
                                break;
                            case "NOTE":
                                if (rx.FirstSubType == "Area Name")
                                {
                                   // _with1.Substring(pos1, len1).SetBold();
                                }
                                break;
                        }
                        break;
                    case "PCA":
                        switch (rx.PartType)
                        {
                            case "API":
                            case "PCA":
                               // _with1.Substring(pos1, len1).SetBold();
                                break;
                        }
                        break;
                    case "Plan":
                        switch (rx.PartType)
                        {
                            case "API":
                              //  _with1.Substring(pos1, len1).SetBold();
                                break;
                        }
                        break;
                    case "Disc":
                        break;
                }

             //   _with1.Substring(pos1, len1).SetFontSize(11);
                pos1 += len1;
            }

            switch (rx.PartType)
            {
                case "BNDR":
                case "STRR":
                case "PRCR":
                case "NOTE":
                case "PCA":
                case "API":
                    switch (rx.PartType)
                    {
                        case "BNDR":
                            wrkPartTypeText = sp + sp + sp + sp + "Boundary outside of Central Process";
                            break;
                        case "STRR":
                            wrkPartTypeText = sp + sp + sp + sp + "Physical or Data Storage";
                            break;
                        case "PRCR":
                            if (Strings.InStr(rx.FirstSubType, "Map") != 0)
                            {
                                wrkPartTypeText = sp + sp + sp + sp +
                                                  Strings.Replace(rx.FirstSubType, "Map", " Map") + sp +
                                                  "Central Process";
                            }
                            else
                            {
                                wrkPartTypeText = sp + sp + sp + sp + "Sub-Process of Central Process";
                            }
                            break;
                        case "NOTE":
                            if (rx.FirstSubType == "Area Name")
                            {
                                wrkPartTypeText = sp + sp + sp + sp + "Model Plan Area Name";
                            }
                            break;
                        case "PCA":
                            wrkPartTypeText = sp + sp + sp + sp + "Proposed Change Action";
                            break;
                        case "API":
                            wrkPartTypeText = sp + sp + sp + sp + "Action Plan Item";

                            break;
                    }
                    len1 = Strings.Len(wrkPartTypeText);

                    tempMainTxt += wrkPartTypeText;
                    //_with1.AddText(wrkPartTypeText);
                    //_with1.Substring(pos1, len1).SetItalic();
                    //_with1.Substring(pos1, len1).SetFontSize(8);
                    pos1 += len1;
                    break;
            }
        }
        catch (Exception ex)
        {
            string exmsg = ex.Message;
            string wrkStop = "";
            ErrorLogService.WriteError(ex, "AddMainText", ServiceName);
        }
    }

}

Current Output but with no styling..
![exportmaintext](https://user-images.githubusercontent.com/8593845/27099784-af103e84-5099-11e7-8cc0-6d0db4491053.png)

**Comment by harshgangwar** [comment]
Any suggestion guys, why RichText creating problem

**Comment by igitur** [comment]
So create a simplified, reduced test case that reproduces the problem.
