### ISSUE TITLE
Develop - Null Exception in XLWorkbook_Save.cs

### ISSUE THREAD

**Issue by rianchipman** [ClosedXML/ClosedXML#344]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**
Unhanded Exception on line 2697 of XLWorkbook_Save.cs
Fixed by adding:
      if (props == null) continue;

Unhanded Exception on line 632 of XLWorkbook_Load.cs
Fixed by adding:
      if (imgId == null) continue;

Handled Exception on line 166 of XLPicture.cs ""Picture names cannot be more than 31 characters"
Fixed by adding:
      if (value.Length > 31) value = value.Substring(0, 31);

**Did this work in previous versions of our tool?  Which versions?**
Yes in non Develop build without Picture support

Can I request upload access to the Develop branch as I have a couple more minor fixes like this.

**Comment by igitur** [comment]
Hi thanks for the bug reports. You're welcome to submit pull requests to fix additional errors. Please submit a separate pull reques for each logical change you make. Where possible, include a unit test with your fix.

**Comment by rianchipman** [comment]
Thanks!  This Library is awesome and you are the man!  We parse tons of Excel files with this at Micron and it works great. I just recently needed image support so I built your Develop branch (which compiled perfectly in VS 2015 the 1st time!) and is now in the /bin folder on the web-server. I think I will avoid the Pull request for now as these are the only changes inside your library. 

I do not think there is anything special about our .xlsx files that cause these 3 errors.  On the long picture name, Microsoft named a hidden picture with "pic" + a GUID so it was like 40+ characters long. Is there a reason you limited to 31 characters? Thanks again...

**Comment by igitur** [comment]
Thanks, but most of the work was done by a previous develop, Manuel de Leon. 

Anyway, the picture name limit isn't something we built in. ClosedXML is a wrapper around OpenXML and its probably an OpenXML constraint. You can try using the `SaveAs(file, false)` overload to disable validation when saving.

**Comment by igitur** [comment]
Are you generating a new workbook from scratch or saving an existing workbook? If the latter, please attach and example.

**Comment by igitur** [comment]
Would love to help you get this resolved, but I need the feedback.

**Comment by igitur** [comment]
No response, so closing this.

**Comment by steveglen** [comment]
I'm encountering this exception opening an existing excel spreadsheet:

System.ArgumentException: Picture names cannot be more than 31 characters
   at ClosedXML.Excel.Drawings.XLPicture.SetName(String value)
   at ClosedXML.Excel.XLWorkbook.LoadDrawings(WorksheetPart wsPart, IXLWorksheet ws)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)

**Comment by igitur** [comment]
@steveglen Please open a new issue and follow the issue template carefully.
