### ISSUE TITLE
TEXT() incorrect for some dates

### ISSUE THREAD

**Issue by b-paul** [ClosedXML/ClosedXML#345]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**

The TEXT() function doesn't produce a zero for days or hours where the Excel equivalent would do so.

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

Sample code is included in the block below. Expected values shown in comments are those observed in MS Excel 2016 32-bit running on Windows 10.0.14393.

**What is the expected behavior or new feature?**

Excel appears to produce 0 instead of 12 for the hour component of times less than 1:00 AM, and 0 for the day only when the input number is zero or a positive number less than 1.

Excel also has the [Leap year bug](https://en.wikipedia.org/wiki/Leap_year_bug), which is not mimicked in the .NET implementation. All numbers from 2.0 up to 61.0 (exclusive) produce a day offset in ClosedXML that is 1 less than the Excel version.

My users are using this behavior of the TEXT function for formatting date spans where their dates are less than 30 days apart. (Note: I first attempted to use `ValueCached` on the cells where this was the case, but something about the process used appears not to provide cached values reliably.)

**Did this work in previous versions of our tool?  Which versions?**

Unknown

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
public void Main()
{
    var wb = new XLWorkbook();
    var ws = wb.AddWorksheet("Sheet1");

    var formula = "TEXT(0, \"d:h:mm\")";
    var result = ws.Evaluate(formula);
    Console.WriteLine("Evaluated \"{0}\": {1}", formula, result); // actual: 30:12:00. expected: 0:0:00

    var formula = "TEXT(1, \"d:h:mm\")";
    var result = ws.Evaluate(formula);
    Console.WriteLine("Evaluated \"{0}\": {1}", formula, result); // actual: 31:12:00. expected: 1:0:00

    var formula = "TEXT(60, \"d:h:mm\")";
    var result = ws.Evaluate(formula);
    Console.WriteLine("Evaluated \"{0}\": {1}", formula, result); // actual: 28:12:00. expected: 29:0:00

    var formula = "TEXT(61, \"d:h:mm\")";
    var result = ws.Evaluate(formula);
    Console.WriteLine("Evaluated \"{0}\": {1}", formula, result); // actual: 1:12:00. expected: 1:0:00

    Console.Write("Press any key to continue...");
    Console.ReadKey();
}
```

[Book1.xlsx](https://github.com/ClosedXML/ClosedXML/files/1072745/Book1.xlsx)

**Comment by igitur** [comment]
It's going to be difficult to replicate the `TEXT()` function exactly. At the moment, ClosedXML just uses the `ToString()` method for the appropriate type. I'm open to suggestions on how to implement it better, though.

**Comment by igitur** [comment]
#586 will fix this.
