### ISSUE TITLE
MOD() incorrect for fractions

### ISSUE THREAD

**Issue by b-paul** [ClosedXML/ClosedXML#346]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**

MOD(1.5, 1) => 0

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

**What is the expected behavior or new feature?**

MOD(1.5, 1) => 0.5

**Did this work in previous versions of our tool?  Which versions?**

Unknown

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
public void Main()
{
    var wb = new XLWorkbook();
    var ws = wb.AddWorksheet("Sheet1");
    var formula = "MOD(1.5, 1)";
    var result = ws.Evaluate(formula);
    Console.WriteLine("Evaluated \"{0}\": {1}", formula, result); // actual: 0. expected: 0.5

    Console.Write("Press any key to continue...");
    Console.ReadKey();
}
```

**Comment by igitur** [comment]
[ClosedXML v0.89.0-beta1](https://www.nuget.org/packages/ClosedXML/0.89.0-beta1) has been published and is ready for your testing.
