### ISSUE TITLE
Inserting rows causes changes of rows heights

### ISSUE THREAD

**Issue by Pankraty** [ClosedXML/ClosedXML#350]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**
When inserting one or many rows the heights of rows above change: it looks like data and formats are being moved down while rows themselves remain in their original places, which may cause breaking of the original formatting.

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**
Steps are provided in the sample code.

**What is the expected behavior or new feature?**
New rows have to be inserted with default heights (Worksheet.RowHeight), while rows above have to keep their original heights.

**Did this work in previous versions of our tool?  Which versions?**
[Example_01_expected.xlsx](https://github.com/ClosedXML/ClosedXML/files/1077128/Example_01_expected.xlsx)
[Example_01_input.xlsx](https://github.com/ClosedXML/ClosedXML/files/1077129/Example_01_input.xlsx)
[Example_01_output.xlsx](https://github.com/ClosedXML/ClosedXML/files/1077130/Example_01_output.xlsx)

- [x ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
public void Main()
{
            XLWorkbook book = new XLWorkbook(@"Example_01_input.xlsx");
            var sheet = book.Worksheets.Worksheet(1);
            sheet.Range("3:3").InsertRowsAbove(1);
            book.SaveAs(@"Example_01_output.xlsx");
}
```

**Comment by igitur** [comment]
I can reproduce the problem. It's better to insert rows using:
```c#
sheet.Row(3).InsertRowsAbove(1);
```

But I will see if I can find a fix.

**Comment by igitur** [comment]
[ClosedXML v0.89.0-beta1](https://www.nuget.org/packages/ClosedXML/0.89.0-beta1) has been published and is ready for your testing.
