### ISSUE TITLE
Impossible to reset row height to default

### ISSUE THREAD

**Issue by Pankraty** [ClosedXML/ClosedXML#352]
**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x] Feature
(Actually, I'm not sure whether it is a bug or a new feature request)

**What is the current behavior?**
Setting row height in code changes its flag HeightChanged. The specified value is written in XLSX then, and rows with specified height don't grow with their contents anymore.

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**
Trying to find a workaround for https://github.com/ClosedXML/ClosedXML/issues/350, I set row heights after inserting manually (in code). But this disables feature of automatical row expanding when WrapText is active.

**What is the expected behavior or new feature?**
My suggestion is to check for row height on saving, and save it to file only if it was modified and differs from default row height for worksheet.
Here is a fragment of GenerateWorksheetPartContent method from XLWorkbook class that could solve the issue:
```c#
                    if (thisRow.HeightChanged && thisRow.Height != xlWorksheet.RowHeight)
                    {
                        row.Height = thisRow.Height.SaveRound();
                        row.CustomHeight = true;
                        row.CustomFormat = true;
                    }
```

**Did this work in previous versions of our tool?  Which versions?**

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Example_02_expected.xlsx](https://github.com/ClosedXML/ClosedXML/files/1077161/Example_02_expected.xlsx)
[Example_02_input.xlsx](https://github.com/ClosedXML/ClosedXML/files/1077162/Example_02_input.xlsx)
[Example_02_output_01.xlsx](https://github.com/ClosedXML/ClosedXML/files/1077163/Example_02_output_01.xlsx)
[Example_02_output_02.xlsx](https://github.com/ClosedXML/ClosedXML/files/1077164/Example_02_output_02.xlsx)

**Code to reproduce problem:**
```c#
public void Main()
{
            XLWorkbook book = new XLWorkbook(@"Example_02_input.xlsx");
            var sheet = book.Worksheets.Worksheet(1);
            sheet.Range("3:3").InsertRowsAbove(3);
            sheet.Range("B3:B5").Style.Alignment.WrapText = true;
            sheet.Range("B3:B5").Value = "Some long text";
            book.SaveAs(@"Example_02_output_01.xlsx");

            sheet.Rows(3, 5).Height = sheet.RowHeight;
            sheet.Rows(6, 6).Height = 120;
            book.SaveAs(@"Example_02_output_02.xlsx");
}
```

**Comment by igitur** [comment]
[ClosedXML v0.89.0-beta1](https://www.nuget.org/packages/ClosedXML/0.89.0-beta1) has been published and is ready for your testing.
