### ISSUE TITLE
Misleading Github repository description

### ISSUE THREAD

**Issue by simon-k** [ClosedXML/ClosedXML#357]
The description of the repository starts with 

> ClosedXML makes it easier for developers to create Excel 2007/2010 files.

The readme says 

> ClosedXML makes it easier for developers to create Excel 2007/2010/2013 files.

**Comment by igitur** [comment]
Fixed in https://github.com/ClosedXML/ClosedXML/commit/1c917c3d60f319a3d098316a9639710cebff433f
