### ISSUE TITLE
Dependency resolution, DocumentFormat.OpenXml doesn't resolve correctly if using version 2.7.2

### ISSUE THREAD

**Issue by Rab815** [ClosedXML/ClosedXML#359]
When including a nuget package in a onion architecture project, ie... business layer.  When the resulting dependencies are copied to the bin folder to a higher level project Ie... a Web project.  The resolution of dependencies resolves incorrectly when version 2.5 of DocumentFormat.OpenXml was already installed previously via nuget.  In the lower level project DocumentFormat.OpenXml resolves to 2.7.2 however msbuild sees ClosedXML when it's copied to the bin of the higher level project and resolves to the hard dependency of DocumentFormat.OpenXml v2.5 instead of the one installed via nuget of v2.7.2

**Comment by igitur** [comment]
Fixed in #292

**Comment by Rab815** [comment]
Is this published to nuget yet?  When I looked at the internal dependencies of ClosedXML.dll it was still referencing 2.5 of DocumentFormat.OpenXml?

**Comment by igitur** [comment]
No, you'll notice #292 is targeted for v0.88.

**Comment by Rab815** [comment]
ah... any timeline on when this version will be available?

**Comment by igitur** [comment]
Nope. I can't plan my spare time that carefully. You can build ClosedXML from source if you wish.
