### ISSUE TITLE
cell.RichText.Text v/s cell.Value.Tostring()

### ISSUE THREAD

**Issue by smoloye** [ClosedXML/ClosedXML#36]
Hi,

I'm trying to read an excel file to get the formatted values for each cell and i'm having issues getting the correct value.
I have a cell with the value : 549.78
cell.RichText.Text is returning : _(\* 549.78) rather than 549.78

So shall i use cell.RichText.Text to get the formatted value or just use cell.Value.ToString()?
What is the proper way to get the displayed (formatted value of a cell)?

Thanks,
SanjeevM.

**Comment by igitur** [comment]
Have a look at `cell.GetFormattedString()`.

**Comment by smoloye** [comment]
Hi igitur,

cell.GetFormattedString() also returns me _(* 549.78) and not the formatted value.

Thanks,
SanjeevM.

**Comment by igitur** [comment]
What is your numberformat for this cell?

**Comment by smoloye** [comment]
cell.Style.NumberFormat.Format
"_(* #,##0.00_);_(* \\(#,##0.00\\);_(* \"-\"??_);_(@_)"

**Comment by smoloye** [comment]
If that helps, i'm having a formatException while reading the cell.Value:

**Comment by igitur** [comment]
I'll look into it. Obviously ClosedXML uses the standard .NET formatting
engine, and there will be times where that doesn't align with Excel's
formatting engine. But it looks like you just want the normal Accounting
format, am I right? If so, I think this should still work.

Francois Botha

**Comment by smoloye** [comment]
Actually i'm just looking to read an Excel file and get the formatted value in each cell not the underlying values. 
For example in another cell i have the following value 4.56789 but the formatted value (displayed value) is 4.57 so i want to recover that value rather than 4.56789

**Comment by igitur** [comment]
Yes, so GetFormattedString() is your best way. It's not going to work for
all Excel formats, but it's the closest we have.

Francois Botha

**Comment by smoloye** [comment]
Ok, thanks.
Any possibility of reading cell.Value and then applying the number format to it?
Do you have an example to accomplish that?

SanjeevM

**Comment by igitur** [comment]
You could read `cell.Value` and `cell.Style.NumberFormat.Format` separately and apply the format with a standard `value.ToString("xxx")`.

**Comment by vbjay** [comment]
If you know you want the two decimal places just get the value and round. Then format as you desire.

**Comment by smoloye** [comment]
I cant do that because i read several excel files and each one can have different decimal places. I need kind of a generic solution.

**Comment by vbjay** [comment]
https://msdn.microsoft.com/en-us/library/f5898377(v=vs.110).aspx. What do you think rounding does?  The input length doesn't matter. If you want to have a rounded 2 decimal value then you call math.round(the value,2). There is an overload that controls how the rounding works.

**Comment by smoloye** [comment]
i cant actually apply rounding, because i'm having kind of a generic excel file reader, to have the ability to read files from different sources. so they can have any number of decimal places and i just need to pick up the value which is displayed in each case.

**Comment by igitur** [comment]
I'm afraid Closedxml can't currently fulfil your needs.
