### ISSUE TITLE
Cell Value and CachedValue different

### ISSUE THREAD

**Issue by simmy007** [ClosedXML/ClosedXML#368]
I am opening an Excel 2010 file that has formulas on many cells. Normally when I open this kind of file (it is a standard template we receive from clients) I have no problem getting the calculated value for a cell. I have just received a file where while debugging I am seeing that the value in the property "value" is not the correct value whereas the value in "cachedvalue" is.

Any idea why this could be and any workarounds/fixes?

I am using C# .Net 3.5 VS 2013

Thanks!

**Comment by igitur** [comment]
Some formula is probably calculating an incorrect value. Or maybe a formula hasn't been implemented yet. You'll have to trace it.

**Comment by simmy007** [comment]
This problem has popped up in a different file/sheet and the solution I found previously doesn't apply here. How would I go about tracing the problem?

Thanks!

**Comment by igitur** [comment]
Does the applicable cell contain a formula? If so, identify each precedent cell (i.e. inputs into the formula) and list of those the ones which `Value` and `ValueCached` differ. For each of those cells, repeat this process until you encounter a cell for which `Value` and `ValueCached` differ, but where the precedent cells' `Value` and `ValueCached` don't differ. That cell would have a formula that is either missing in ClosedXML or not implemented yet.

**Comment by simmy007** [comment]
The problem is that for some reason XL isn't defining certain cells as being a "Date" data type. These cells are formatted as date and in XL the result of the formula is displayed correctly. Strange that the value and cachedvalue are different in ClosedXML.

**Comment by igitur** [comment]
Log a new issue with a reduced test case to illustrate that issue.
