### ISSUE TITLE
Unable to find reference

### ISSUE THREAD

**Issue by noknok321** [ClosedXML/ClosedXML#370]
I am building a SharePoint2013 - Visual Web Part Project, target framework is .NET 4.5.
Whenever I include ClosedXML, I got this error:
> Could not load file or assembly 'ClosedXML, Version=0.87.0.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b' or one of its dependencies. The system cannot find the file specified. 

I have added reference to DocumentFormat.OpenXml 2.5.0.
ClosedXML reference path is `Visual Studio 2015\Projects\MyProject\packages\ClosedXML.0.87.1\lib\net40`. I have checked the location , ClosedXML.dll is there.

Please Help...

**Comment by igitur** [comment]
Upgrade ClosedXML to v0.87.1

**Comment by noknok321** [comment]
In NuGet Package Manager, it shows that the project have already installed v0.87.1.

**Comment by noknok321** [comment]
It shows in NuGet v0.87.1 is installed. But in the Reference Manager it shows the ClosedXML.dll have `File Version: 0.87.0.0`. :(

**Comment by noknok321** [comment]
No idea where to get File version 0.87.1.
Downgraded to 0.86.0. Still get the same error.

**Comment by noknok321** [comment]
Placed the dll file somewhere else, worked!
Probably some security issues, make it not able to access the dll inside project.
But the openxml doesnt have this problem, strange.
Thank you.

**Comment by igitur** [comment]
Ok, great. 

Apologies. Version 0.87.1 still has an internal version of 0.87.0.
