### ISSUE TITLE
Failing on DocumentFormat.OpenXml 2.7.2 dependency

### ISSUE THREAD

**Issue by vkirienko** [ClosedXML/ClosedXML#373]
**- [x] Bug**
- [ ] Feature

What is the current behavior?

ClosedXML NuGet package shows dependency for DocumentFormat.OpenXml as **>=** 2.5.0

When I reference latest DocumentFormat.OpenXml (2.7.2) application fails with error below:

Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.5.5631.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by igitur** [comment]
Fixed in #362
