### ISSUE TITLE
How can i specify the path for save workbook?

### ISSUE THREAD

**Issue by kot-mapku3** [ClosedXML/ClosedXML#374]
wb.SaveAs(textBox1.Text + "_ready_price");
This fucntion takes name, not a path.

**Comment by vbjay** [comment]
Io.path.combine

**Comment by kot-mapku3** [comment]
I'm not understand. Where i must write it?

**Comment by vbjay** [comment]
You could try using a search engine and looking it up.

**Comment by kot-mapku3** [comment]
As if I do not know, otherwise I would not write here

**Comment by kot-mapku3** [comment]
I done it. Thanks)
