### ISSUE TITLE
How to copy values only?

### ISSUE THREAD

**Issue by nefcanto** [ClosedXML/ClosedXML#377]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

**What is the current behavior?**

Methods CoypTo and CopyFrom don't have overloads for pasting values only. They paste the original formula, or the original PivotTable. I want to be able to copy/paste values only.

**What is the expected behavior or new feature?**
Having an overload that specifies the type of paste operation (an enum that might have these values: Everything, Values, Formatting)

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[ConsoleApp1.zip](https://github.com/ClosedXML/ClosedXML/files/1116911/ConsoleApp1.zip)

**Code to reproduce problem:**
```c#
public void Main()
{
            using (var workbook = new XLWorkbook())
            {
                var sourceSheet = workbook.AddWorksheet("Source");
                var targetSheet = workbook.AddWorksheet("Target");
                sourceSheet.Cell(1, 1).SetValue(15);
                sourceSheet.Cell(1, 2).SetValue(25);
                sourceSheet.Cell(1, 3).SetFormulaA1("=A1+B1");
                sourceSheet.Cell(1, 3).CopyTo(targetSheet.Cell(1, 3));
                // sourceSheet.Cell(1, 3).CopyTo(targetSheet.Cell(1, 1)); // this line throws "Index was outside the bounds of the array." exception. I need to copy formula result's value, to another sheet.
                workbook.SaveAs(@"C:\Temp\Temp.xlsx");
            }
}
```

**Comment by igitur** [comment]
try:
```c#
targetsheet.Cell(1, 3).Value = sourceSheet.Cell(1, 3).Value;
```
