### ISSUE TITLE
How to get full column text

### ISSUE THREAD

**Issue by vinodvinu** [ClosedXML/ClosedXML#383]
**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x] Feature

Hi, I am using this in vb.net. So i am facing difficulties to read c# code. ("{}" s are really annoying).  Now, for getting text from any specific column, i am using a For loop and "xlSheet.Cell(Row, Col).getValue" to populate a list or array.  Is there any inner methods to get the full text of a column as a list or array  ?

**Comment by igitur** [comment]
Try for example:
```c#
ws.Column(3).CellsUsed().Select(c => c.Value).ToList();
```
