### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by PiotrPerak** [ClosedXML/ClosedXML#385]
**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x] Feature

**What is the current behavior?**
No support for adding images.

**What is the expected behavior or new feature?**
Possibility to add pictures to worksheets.

I've seen that image support has been merged into develop branch. When can we expect it to be merged and published in NuGet package?

**Comment by vbjay** [comment]
Creating an issue like this to ask this question is not how things are done. Close this issue and comment on the issue that added the feature. Also get familiar with milestones. https://github.com/ClosedXML/ClosedXML/milestones

**Comment by PiotrPerak** [comment]
https://github.com/ClosedXML/ClosedXML/pull/284#issuecomment-313410021
