### ISSUE TITLE
Add DataTable as a Worksheet causes Excel to Repair the Workbook when opened.

### ISSUE THREAD

**Issue by rollingharrier** [ClosedXML/ClosedXML#396]
- [x] Bug
- [ ] Feature

Version of ClosedXML= 0.87.0.0

I'm working in VS 2013 ASP.NET, .NET 4.5.1 c#. Downloaded ClosedXML downloaded through NuGet.

Everything seems fine when I add a simple Strongly Typed DataTable as a Worksheet to a workbook.
I save the workbook after being prompted to save it.
When I double click on the file Excel states "We found a problem with some content in ClosedXMLOutput.xlsx Do you want us to try and recover as much as we can?..."
If I click Yes the file and the contents are fine.
I've used both Chrome and Firefox.
 
So what I did was save the file twice. I opened one up and let Excel Fix it. Then I extracted the archive of both Excel files using 7zip. The difference I noticed was in the table.xml file. So I edited the failed table.xml file and replaced the contents with the contents of the repaired file. I did have to set the table and display names to Table from Table1. 
After updating the archive the file opened without issue.
File that fails
[ClosedXMLOutput - Copy.xlsx](https://github.com/ClosedXML/ClosedXML/files/1142936/ClosedXMLOutput.-.Copy.xlsx)
After repair
[ClosedXMLOutput.xlsx](https://github.com/ClosedXML/ClosedXML/files/1142937/ClosedXMLOutput.xlsx)

MyCode:
**aspx file**

<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="closedxmltest.aspx.cs" Inherits="WebApplication1.closedxmltest" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:Button ID="btn_CreateExcel" runat="server" Text="Export Excel" OnClick="btn_CreateExcel_Click" />
    </div>
    </form>
</body>
</html>

**.cs file**

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using WebApplication1.Models;
using WebApplication1.Models.closedxmlDSetTableAdapters;

using ClosedXML.Excel;
using System.IO;
using System.Text;

namespace WebApplication1
{
	public partial class closedxmltest : System.Web.UI.Page
	{
		protected void Page_Load(object sender, EventArgs e)
		{

		}

		protected void btn_CreateExcel_Click(object sender, EventArgs e)
		{
			try
			{
				ExpanseTableAdapter DTAdapter = new ExpanseTableAdapter();

				XLWorkbook backlogWB = new XLWorkbook();

				closedxmlDSet.ExpanseDataTable dTable = DTAdapter.GetData();

				backlogWB.AddWorksheet(dTable, "WS1");

				MemoryStream fs = new MemoryStream();
				backlogWB.SaveAs(fs);
				fs.Position = 0;

				PromptUserToSaveFile("ClosedXMLOutputFixed.xlsx", fs.GetBuffer());
			}
			catch (Exception err)
			{

			}
		}

		private void PromptUserToSaveFile(String file, Byte[] buf)
		{
			//System.IO.FileInfo file = new System.IO.FileInfo(pathFile);
			Response.Clear();
			Response.Charset = "UTF-8";
			Response.ContentEncoding = System.Text.Encoding.UTF8;
			Response.AddHeader("Content-Disposition", "attachment; filename=" + file);
			Response.AddHeader("Content-Length", buf.Length.ToString());
			Response.ContentType = "application/txt";
			String data = UTF8Encoding.UTF8.GetString(buf);
			Response.BinaryWrite(buf);

			HttpContext.Current.ApplicationInstance.CompleteRequest();
		}

	}
}

**Comment by igitur** [comment]
Please provide code that I can cut and paste and run myself.

**Comment by rollingharrier** [comment]
Hello igitur,
I've updated the first post with the aspx and cs file contents. 
The data adapter is connected to an MS SQL server database which has some test data in it. nothing special.
Thx
Jim

**Comment by igitur** [comment]
That's ASP.NET code. The issue template specifically asks for *console application* code. 

Please populate your DataTable manually with dummy data. 

Let me repeat: I want to be able to copy and paste your code directly into a blank console application and be able to reproduce the issue. 

Keep in mind I'm squashing ClosedXML bugs during my coffee breaks, so you need to make it easy for me.

**Comment by vbjay** [comment]
You don't get it. He wants a mock up. Write some code he can copy and paste
and run. You can create a table through code and even add rows. He doesn't
have your database.

**Comment by rollingharrier** [comment]
Ah OK I'll post as son as I can.
Thx
Jim

**Comment by rollingharrier** [comment]
It works fine if I save the file locally. So it's something not related to ClosedXML. Sorry for wasting you time.

**Comment by igitur** [comment]
You might be interested in https://www.nuget.org/packages/ClosedXML.Extensions.AspNet/

**Comment by exitxhu** [comment]
it may be late, use ToArray() instead of GetBuffer(), which solved for me and drastically reduce the response size.
