### ISSUE TITLE
Memory not released 

### ISSUE THREAD

**Issue by ganiths** [ClosedXML/ClosedXML#401]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

 0.87.1

**What is the current behavior?**

Memory is not released when using Open xml . Tried with a simple application that does opening a existing file, modify cell content and save it

**What is the expected behavior or new feature?**

Memory should be disposed properly once excel creation is complete.

**Did this work in previous versions of our tool?  Which versions?**

No

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
public void Main()
{
     string filePath = "C:\\template.xlsx";

            using (var wb = new XLWorkbook(filePath, XLEventTracking.Disabled))
            {
                var worksheet = wb.Worksheets.FirstOrDefault();

                if (worksheet != null)
                {
                    var cell = worksheet.Cell(1, 1);
                    cell.Value = cell.Value + "Appending ";
                }

                filePath = Path.Combine("C:\\test.xlsx");
                wb.SaveAs(filePath);
               }
}
```

**Comment by igitur** [comment]
What suggests that memory isn't disposed correctly?

**Comment by igitur** [comment]
Also, ensure you're running in `Release` configuration.

**Comment by ganiths** [comment]
I tried with release configuration.When i start my application my memory consumption was 4 MB. After using Open XML it got increased to 8 MB,But the memory didn't come down from that.

**Comment by vbjay** [comment]
You are worried about 4MB?  You have to understand the assemblies do not
get unloaded.  Load a huge excel spreadsheet and then have it disposed.
Look at memory usage after the file is loaded and then again after dispose.

**Comment by ganiths** [comment]
Am not worried about 4 MB memory. But just wanted to know what is teh cause of 4 MB increase as the complete assembly is only few KB's

As per your suggestion, I tried loading file with 10000 rows(65KB).Initial memory was 4 Mb and it has been increased to 29 MB after processing.

**Comment by igitur** [comment]
Try explicitly calling a garage collection (which is generally not encouraged).

**Comment by vbjay** [comment]
Correct.  .Net manages the memory for you.  Disposing of objects lets you
clean up objects right now.  Clean up does not mean the memory is cleaned
up.  Garbage collection is not determinant.  It will run when needed.
Things like memory strain and such will cause a GC.  Normally, you let the
garbage collector manage it for you.  Once you force one, you lose some of
the optimizations it has.

**Comment by igitur** [comment]
To recap, run this in `Release` mode and explicitly trigger garbage collection, e.g. with this method:
```c#
        private void TriggerGC()
        {
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();
        }
```

If you still see a significant memory usage, let me know. Of course there will be some minor increase in memory - static fields are not released.
