### ISSUE TITLE
Wrong picture coordinates 

### ISSUE THREAD

**Issue by acoto87** [ClosedXML/ClosedXML#404]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.88.0-beta

**What is the current behavior?**
The english metrics coordinates of the image with free floating placement are calculated wrong when the X or Y are large.

The problem is with the method:
`private static Int64 ConvertToEnglishMetricUnits(Int32 pixels, Double resolution)
 {
            return Convert.ToInt64(914400 * pixels / resolution);
 }`

when `pixels` is large enough the multiplication with `914400` overflows and the result is negative. 

One way to solve it is ensuring that `914400` is 64 bits long, or converting `pixels `to 64 bits before the multiplication.
`private static Int64 ConvertToEnglishMetricUnits(Int32 pixels, Double resolution)
{
            return Convert.ToInt64(914400L * pixels / resolution);
}`

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

**What is the expected behavior or new feature?**
The coordinates should be calculated correctly.

**Did this work in previous versions of our tool?  Which versions?**
No, picture support was added recently.

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
public void Main()
{
    var workbook = new XLWorkbook();
    var worksheet = workbook.Worksheets.Add("Sample Sheet");
    var picture = worksheet.AddPicture("path to image");
    picture.Placement = Drawings.XLPicturePlacement.FreeFloating;
    picture.Left = 2873;
    picture.Top = 608;
    picture.Width = 150;
    picture.Height = 150;
    workbook.SaveAs("HelloWorld.xlsx");
}
```

**Comment by igitur** [comment]
Thanks.
