### ISSUE TITLE
Trying to insert punjabi language font but the saved excel file contain ???????????? and not the punjabi font

### ISSUE THREAD

**Issue by Prabh2308** [ClosedXML/ClosedXML#413]
I am using the following code, but excel only showing English font and all the non English font (Punjabi

 in my case) are shown as "???????????? ??????????? ????????????"

```C#
using (SqlCommand cmd = new SqlCommand("SELECT  * FROM table1'"))
{
    using (SqlDataAdapter sda = new SqlDataAdapter())
    {
        cmd.Connection = con;
        sda.SelectCommand = cmd;
        using (DataTable dt = new DataTable())
        {
            sda.Fill(dt);
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt, "Project");

                Response.Clear();

                Response.Buffer = true;
                Response.Charset = "";
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment;filename=SqlExport.xlsx");
                using (MemoryStream MyMemoryStream = new MemoryStream())
                {
                    wb.SaveAs(MyMemoryStream);
                    MyMemoryStream.WriteTo(Response.OutputStream);
                    Response.Flush();
                    Response.End();
                }
            }
        }
    }
}
```

![code](https://user-images.githubusercontent.com/19783982/28329923-4bd7b4a6-6c09-11e7-8be7-f90724df22aa.PNG)

**Comment by igitur** [comment]
I can't reproduce the issue because I don't have access to your data. Please post code that I can use to reproduce the issue. Don't post ASP.NET code. Post code that I can copy and paste in a console application. Manually populate your datatable if necessary. Without me reproducing the problem, I can't fix it. Also post a sample file of what you expect to produce. I have no idea how to enter Punjabi myself, so you'll have to spoonfeed me the information.

**Comment by Prabh2308** [comment]
Sir the issue is the database file is 350mb. You can try this for any **_non english_** language and check whether it works or not.

**Comment by igitur** [comment]
It works fine for Afrikaans and Xhosa.

**Comment by Prabh2308** [comment]
can you send me code for the same. I am trying to import data from database and not through gridview. Will it work???

**Comment by igitur** [comment]
I used this code and the resulting file shows it perfectly. I repeat... I have to be able to reproduce the problem else I can't solve it. Produce a minimal code sample.

```c#
using (var wb = new XLWorkbook())
{
    var ws = wb.Worksheets.Add("Sheet1");
    var cell = ws.FirstCell();
    cell.SetValue("ਕਰਮ ਕਾਰਕ");

    wb.SaveAs(@"c:\temp\punjabi.xlsx");
}
```

![image](https://user-images.githubusercontent.com/145854/28406724-edf98024-6d31-11e7-9baf-16a364b2f109.png)

**Comment by Prabh2308** [comment]
Can i use the same code for ASP.Net?

**Comment by igitur** [comment]
Yes.

**Comment by Prabh2308** [comment]
Sir i tried to reuse your above code, it works fine when i try with a single value as you did, but as soon as i try to fetch data from database i get ?????????????????????????? only.

**Comment by vbjay** [comment]
Sounds like an encoding issue.
