### ISSUE TITLE
ClosedXML Create Pivot Table From SQL Query (DataTable)

### ISSUE THREAD

**Issue by PlastikdaN** [ClosedXML/ClosedXML#414]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.87.1

**What is the current behavior?**

When I save the output from a DataTable (that is populated by an SQL Query), the Excel sheet produces and error based on validation of the data within the PivotTabel

"Excel completed file level Validation and Repair. Some parts of this workbook may have been repaired or discarded.
Removed Feature: PivotTable Report from /xl/pivotTable.xml part (pivotTable view)
Removed Records: Workbook properties from /xl/workbook.xml part (Workbook)
Repaired Records: String properties from /xl/sharedStrings.xml part (Strings)"

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

Please see the code below;

**What is the expected behavior or new feature?**

The expected behavior is to have a Pivot Table added to a new Sheet (Named PivotTable) to be generated based on the Table that is stored in the sheet/workbook tagged as "quarter" in the below code

**Did this work in previous versions of our tool?  Which versions?**

I have tried version 0.85 with the same results.

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
cmd.Connection = con;
sda.SelectCommand = cmd;
using (DataTable dt = new DataTable())
{
    sda.Fill(dt);
    using (XLWorkbook wb = new XLWorkbook())
    {
           var sheet1 = wb.Worksheets.Add(dt, quarter);

           var dataRange = sheet1.RangeUsed();
           var ptSheet = wb.Worksheets.Add("PivotTable");
           var pt = ptSheet.PivotTables.AddNew("PivotTable", ptSheet.Cell(1, 1), dataRange);

           System.Diagnostics.Debug.WriteLine(dataRange);

           pt.RowLabels.Add("IP Address");
           pt.RowLabels.Add("Vulnerability Name");
           pt.Values.Add("Count Of Vulnerability ID");


           using (MemoryStream MyMemoryStream = new MemoryStream())
           {
                  wb.SaveAs(MyMemoryStream, false);                                      
                  MyMemoryStream.WriteTo(Response.OutputStream);
                  Response.Flush();
                  Response.End();
           }
     }
}
```

**Comment by igitur** [comment]
I can't reproduce the issue if you don't populate the data table manually. Please do so. I need a code sample that I can copy and paste into a console application. So remove the ASP.NET stuff as well, please.
