### ISSUE TITLE
Copying worksheet copies the worksheet scoped named range but "Refers To" continues to point to old cells

### ISSUE THREAD

**Issue by etsimber** [ClosedXML/ClosedXML#416]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.87.1

**What is the current behavior?**

The Template tab in the ExcelBuilderTemplateDynamicWorksheets.xlsx has a named range "TemplateRange" which is scoped to the worksheet itself, and points to cells A1 through C1.  If I run worksheet CopyTo functionality from the code below, it correctly creates a worksheet called "Copy", and creates a new named range also called "TemplateRange" which correctly has the scope of the new worksheet.  The Refers To cells on the new worksheet, however, still point to A1 through C1 on the original worksheet not on the new one.

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

Run the attached code from the unit test.
Open the "Name Manager" in excel
Check the Refers To column.  The cells pointed to by the new named range will be the original cells.

**What is the expected behavior or new feature?**
If I copy a worksheet in excel, the functionality is almost the same, but the new named range points to cells A1 through C1 on the "Copy" worksheet, not the original one.  As such I would expect the CopyTo functionality to be consistent with excel worksheet copy functionality

**Did this work in previous versions of our tool?  Which versions?**

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[ExcelBuilderTemplateDynamicWorksheets.xlsx](https://github.com/ClosedXML/ClosedXML/files/1162961/ExcelBuilderTemplateDynamicWorksheets.xlsx)

[OutExcelBuilderTemplateDynamicWorksheets.xlsx](https://github.com/ClosedXML/ClosedXML/files/1162962/OutExcelBuilderTemplateDynamicWorksheets.xlsx)

**Code to reproduce problem:**
```c#
public void Main()
{
            const string templatePath = @"SampleFiles\ExcelBuilderTemplateDynamicWorksheets.xlsx";
            const string outSampleFile = @"SampleFiles\OutExcelBuilderTemplateDynamicWorksheets.xlsx";
            var wb = new XLWorkbook(templatePath);
            IXLWorksheet worksheet = wb.Worksheet("Template");
            worksheet.CopyTo("Copy");
            wb.SaveAs(outSampleFile);
}
```

**Comment by vbjay** [comment]
Search issues first. #355

**Comment by etsimber** [comment]
While I appreciate the sentiment, I did search the the issues, and 355 does not represent the issue I am reporting, or at least the way I understood 355 it does not..  I am neither copying between the workbooks, nor getting the IndexOutOfRangeException, nor copying a range with an odd format..  The functionality appears to be mostly working, but not quite. The named range is almost copied correctly, but the Refers To is off which I believe to be a bug.  I will investigate if I can fix it, but in the mean time wanted to report it as an issue.

Thank you.

**Comment by vbjay** [comment]
The comment in that issue dies apply. 

commented about 1 month ago
Firstly, copying worksheets across workbooks hasn't been tested extensively. So a lot of bugs are popping up here.

The IndexOutOfRangeException was fixed in #338 .

But even so, the named ranges in the worksheet prevent the worksheet from being copied. Named ranges that contain formulas, e.g. the Clas1 named range with definition =OFFSET('ANNEXE 1'!$AJ$11,,,COUNTA('ANNEXE 1'!$AI:$AI)-1) is not supported. Currently the only workaround is to delete the unsupported named ranges.

**Comment by vbjay** [comment]
https://github.com/ClosedXML/ClosedXML/blob/5bd67e53d77cb7026ecb4cbb7805cfc4f812d6f8/ClosedXML/Excel/XLWorksheet.cs#L546. 

It's the same functionality.

**Comment by igitur** [comment]
[ClosedXML v0.89.0-beta1](https://www.nuget.org/packages/ClosedXML/0.89.0-beta1) has been published and is ready for your testing.
