### ISSUE TITLE
Can't set header on non empty header

### ISSUE THREAD

**Issue by shenhavba** [ClosedXML/ClosedXML#42]
I am using this code to set the header on a document that already contains headers(first page and odd even) and it does not work.

pageSetup.Header.Center.AddText("first", XLHFOccurrence.FirstPage);
pageSetup.Header.Center.AddText("odd", XLHFOccurrence.OddPages);
pageSetup.Header.Center.AddText("even", XLHFOccurrence.EvenPages);

if i delete the headers, it does work.

using pageSetup.Header.Center.Clear(); does not work either.

**Comment by igitur** [comment]
I found the bug, but please note that `AddText()` will indeed *add* text to any existing text. You will have to call `pageSetup.Header.Center.Clear()` first if you want to overwrite the existing text.

I will commit a fix shortly.

**Comment by Pyropace** [comment]
Fixed has been merged into develop
