### ISSUE TITLE
Double is not well parsed

### ISSUE THREAD

**Issue by sashberd** [ClosedXML/ClosedXML#421]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
0.88.0.0

I have in my Excel Version column with next values: 1.00, 2.00 2.50 etc. It  returns 1,2,2.5 accordingly without saving format of double.

It should return 1.00, 2.00, 2.50

For your review

**Comment by igitur** [comment]
Attach the file, please.

**Comment by sashberd** [comment]
[Book1.xlsx](https://github.com/ClosedXML/ClosedXML/files/1179068/Book1.xlsx)

**Comment by igitur** [comment]
Works fine for me. 
```c#
using (var wb = new XLWorkbook("test.xlsx"))
{
    var ws = wb.Worksheets.First();

    foreach (var c in ws.Column("C").CellsUsed())
        Console.WriteLine(c.GetFormattedString());
}
```

![image](https://user-images.githubusercontent.com/145854/28663563-053e7fdc-72be-11e7-93d9-285c1dc5ed94.png)

**Comment by igitur** [comment]
Did you [RTFM](https://github.com/ClosedXML/ClosedXML/wiki/Cell-Values)?

**Comment by sashberd** [comment]
You used GetFormatedString function
I used GetDouble
I think function with name GetDouble should not round 1.00 to 1... it is double not int

**Comment by igitur** [comment]
`GetDouble` returns a value of type `double`. `1.00` vs `1` is a formatting issue. Try this yourself:

```c#
double myDouble = 1.00;
Console.WriteLine(myDouble); // you will see 1
Console.WriteLine(myDouble.ToString("0.00")); // you will see 1.00
```
