### ISSUE TITLE
NullReferenceException on cell.SetValue

### ISSUE THREAD

**Issue by jvdslikke** [ClosedXML/ClosedXML#422]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.88.0

**What is the current behavior?**
NullReferenceException on cell.SetValue

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

**What is the expected behavior or new feature?**
**Did this work in previous versions of our tool?  Which versions?**
In previous version (0.87.1) we could set an empty value in a cell with SetValue(null)

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
public void Main()
{
    var wb = new XLWorkbook();
    var ws = wb.Worksheets.Add("Formulas");
    var cell = ws.Cell(1, 1);
    cell.SetValue(null); <- NullReferenceException here

}
```

**Comment by igitur** [comment]
The preferred way to clear a cell is with `IXLCell.Clear(clearOptions)`.

**Comment by jvdslikke** [comment]
@igitur Thanks for your reply

**Comment by jvdslikke** [comment]
@igitur Thanks for you replay. And thanks voor the ClosedXML library as well :)

We do not only SetValue(null) for clearing cells. We use SetValue to export data from a database, which can also contain  null values. So it would be great if SetValue null could result in an empty cell.

**Comment by igitur** [comment]
Please test with the built files at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.432/artifacts

**Comment by igitur** [comment]
[ClosedXML v0.89.0-beta1](https://www.nuget.org/packages/ClosedXML/0.89.0-beta1) has been published and is ready for your testing.
