### ISSUE TITLE
NullReferenceException on opening workbook

### ISSUE THREAD

**Issue by tuanchumanh** [ClosedXML/ClosedXML#424]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.88.0

**What is the current behavior?**
NullReferenceException on opening workbook (new XLWorkbook)

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**
- Open the file with new XLWorkbook
- NullReferenceException occurs

   場所 ClosedXML.Excel.XLNamedRanges.Add(String rangeName, String rangeAddress, String comment, Boolean acceptInvalidReferences)
   場所 ClosedXML.Excel.XLNamedRanges.Add(String rangeName, String rangeAddress, String comment)
   場所 ClosedXML.Excel.XLWorkbook.LoadDefinedNames(Workbook workbook)
   場所 ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   場所 ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)
   場所 ClosedXML.Excel.XLWorkbook..ctor(Stream stream, XLEventTracking eventTracking)

**What is the expected behavior or new feature?**

**Did this work in previous versions of our tool?  Which versions?**
Worked in 0.86.0

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
			using (var fileStream = new FileStream(file, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
			using (var wb = new XLWorkbook(fileStream, XLEventTracking.Disabled))
```

**Comment by igitur** [comment]
Attach the file

**Comment by tuanchumanh** [comment]
Here you go.
[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/1186414/test.xlsx)

**Comment by igitur** [comment]
Are you aware of the many hidden named ranges? Some of them are creating problems, due to a bug in ClosedXML, but you might want to remove them if you're not using them. 

To unhide them, do this in VBA:
```vb
Sub Unhide()
Dim nName as Name
For Each nName in ActiveWorkbook.Names
    nName.Hidden = False
Next nName
End Sub
```

then run `Unhide()` macro and then go to Name Manager to remove those that you don't want.

**Comment by tuanchumanh** [comment]
Thanks for the response.
However, I have 100+ files like this and I was trying to do some edit on all of them.
I think I will be using 0.86 for now.

**Comment by igitur** [comment]
[ClosedXML v0.89.0-beta1](https://www.nuget.org/packages/ClosedXML/0.89.0-beta1) has been published and is ready for your testing.
