### ISSUE TITLE
How to Embed real time currency converter in Excel using C#.Net

### ISSUE THREAD

**Issue by poornima82** [ClosedXML/ClosedXML#425]
** ClosedXML**

Hi,

i am using asp.net website project not a web application project.
Already  generating report in Excel using C# code.
I want to insert current currency rate of each country in that report and should refresh automatically.
I want to do all this through C# coding.
Here used   "using ClosedXML.Excel;" namespace in our website.
I need to use this Excel to integrate currency converter using ClosedXML.

Regards,
Poornima

**Comment by poornima82** [comment]
Hi Igitur,

Thanks for your reply.
I can able to create or generate .xlsx file using ClosedXML in C#.net.
What I want is,
 to embed Currency converter in this through coding,
How to achieve this?

Regards,
Poornima

**Comment by igitur** [comment]
Please answer all my questions in https://github.com/ClosedXML/ClosedXML/issues/425#issuecomment-319644432

Otherwise I can't help you.
