### ISSUE TITLE
Export to Activeworkbook

### ISSUE THREAD

**Issue by hwang74** [ClosedXML/ClosedXML#426]
Hi, 

I'm developing an excel add-in that exports datatable to it. I loved closedXML when exporting to a new excel but Is there a way to do it to the currently active workbook?

Thanks!
```

**Comment by igitur** [comment]
Do you mean to export to the currently active workbook in Excel? If so, no, ClosedXML has no dependencies on Excel, so this isn't possible.

**Comment by hwang74** [comment]
thank you for your quick response.
