### ISSUE TITLE
Review > Allow Users to Edit Ranges

### ISSUE THREAD

**Issue by rbrickel** [ClosedXML/ClosedXML#427]
- [X] Feature

Version of ClosedXML: 0.87.0

I'm looking for the ability to sort a protected worksheet. I use the following to protect the worksheet:

```c#
IXLSheetProtection protection = ws.Protect(EXCEL_PASSWORD);
protection.AutoFilter = true;
protection.Sort = true;
```

The "protection.Sort = true" does allow for a user to click the sort option in the worksheet but will not allow the sort. One way I could make this work is by adding a named range to the "Review > Allow Users to Edit Ranges" section (setting "Select locked cells" as false when protecting the worksheet). I do not see a way to insert a named range into the Allow Users to Edit Ranges section via the ClosedXML API. Did I miss how to do this in the documentation? if no, is this something that can be added?

**Comment by igitur** [comment]
If you want to sort cells on a protected worksheet, the cells in the sort range have to be unlocked. Did you explicitly unlock the cells first? 

Post a full code sample next time please.
