### ISSUE TITLE
Cross-worksheet hyperlink writes out the wrong sheet name

### ISSUE THREAD

**Issue by taoyue** [ClosedXML/ClosedXML#428]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.88.0

**What is the current behavior?**

When you construct a ```new XLHyperlink(IXLCell)```, the hyperlink is written to the XLSX file with the name of the worksheet that holds the XLHyperlink.

The same thing happens for a ```new XLHyperlink(IXLRangeBase)```.

**What is the expected behavior or new feature?**

A hyperlink to an IXLCell should point to the worksheet that holds the IXLCell, rather than the worksheet that holds the XLHyperlink.

A hyperlink to an IXLRangeBase should point to the worksheet that holds the IXLRangeBase.

**Did this work in previous versions of our tool?  Which versions?**

No, it was already broken as of 0.75.

I filed bug 9392 on Codeplex on 2014-11-17 and attached a patch: https://closedxml.codeplex.com/workitem/9392

**Code to reproduce problem:**

```
    static void Main(string[] args)
    {
      var workbook = new XLWorkbook();
      var sheet1 = workbook.Worksheets.Add("Sheet1");
      var sheet2 = workbook.Worksheets.Add("Sheet2");

      var targetCell = sheet2.Cell("A1");
      var targetRange = sheet2.Range("A1", "B1");

      // This should create a hyperlink to Sheet2!A1, but it actually creates
      // a hyperlink to Sheet1!A1.
      var linkCell1 = sheet1.Cell("A1");
      linkCell1.Value = "Link to IXLCell";
      linkCell1.Hyperlink = new XLHyperlink(targetCell);

      // This should create a hyperlink to Sheet2!A1:B1, but it actually
      // creates a hyperlink to Sheet1!A1:B1.
      var linkRange1 = sheet1.Cell("A2");
      linkRange1.Value = "Link to IXLRangeBase";
      linkRange1.Hyperlink = new XLHyperlink(targetRange);

      workbook.SaveAs("hyperlink.xlsx");
    }
```

**Result of running code**

[hyperlink.xlsx](https://github.com/ClosedXML/ClosedXML/files/1188715/hyperlink.xlsx)

**Comment by igitur** [comment]
Can you submit a PR, including a unit test?

**Comment by igitur** [comment]
@taoyue  ?

**Comment by igitur** [comment]
You snooze, you lose.

**Comment by igitur** [comment]
https://www.nuget.org/packages/ClosedXML/0.90.0-beta2 is released and should include the fix for this issue.
