### ISSUE TITLE
VLookup 

### ISSUE THREAD

**Issue by fmystal** [ClosedXML/ClosedXML#433]
**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [X ] Feature

Version 0.87.1

HLOOKUP and VLOOKUP are considered bad expressions reading worksheets cells

Just ty to read cell worksheet value that is calculated using HLOOKUP or VLOOKUP functions

Allow to get value of this functions/expressions

Never has worked (this featured is pending to be implemented)

**Comment by fmystal** [comment]
Are you working on this feature or can I do any stuff in order to solve this functionallity??

**Comment by igitur** [comment]
Upgrade to the latest version and if it's still a problem, create a new issue and fill out the issue template completely.
