### ISSUE TITLE
[Question] View Excel File

### ISSUE THREAD

**Issue by shaggygi** [ClosedXML/ClosedXML#434]
I know I'm overlooking something, but how do you open and view a file using ClosedXML?  It seems like most is about loading/saving files, but sometimes need to load and view the file.  Thx

**Comment by vbjay** [comment]
You don't. ClosedXML is wrapper around the openxmlsdk. All it does is read
and save excel spreadsheets.

**Comment by igitur** [comment]
ClosedXML is a way to generate Excel files without Excel being installed. Therefore there's no way to interact with Excel. 

But have a look at https://stackoverflow.com/questions/10174156/open-file-with-associated-application
