### ISSUE TITLE
NullReferenceException on XLWorkbook.Save()

### ISSUE THREAD

**Issue by v0idname** [ClosedXML/ClosedXML#435]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.85.0, 0.86.0, 0.87.1, 0.88.0

**What is the current behavior?**

NullReferenceException on second call of XLWorkbook.Save() after XLWorksheet.Delete():

```c#
ClosedXML.Excel.XLWorkbook.DeleteSheetAndDependencies(WorkbookPart wbPart, String sheetId)
ClosedXML.Excel.XLWorkbook.<>c__DisplayClass94_0.<CreateParts>b__7(String ws)
System.Collections.Generic.List`1.ForEach(Action`1 action)
ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, Boolean evaluateFormulae)
ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, Boolean validate, Boolean evaluateFormulae)
ClosedXML.Excel.XLWorkbook.Save(Boolean validate, Boolean evaluateFormulae)
ClosedXML.Excel.XLWorkbook.Save()
```
- [x] **I attached a sample spreadsheet.**
[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/1211996/test.xlsx)

**Code to reproduce problem:**
```c#
using ClosedXML.Excel;
public void Main()
{
    string fileName = ".\\test.xlsx";

    // file can be created manually or by ClosedXML:
    XLWorkbook book1 = new XLWorkbook();
    book1.AddWorksheet("sheet1");
    book1.AddWorksheet("sheet2");
    book1.SaveAs(fileName);

    XLWorkbook book2 = new XLWorkbook(fileName);
    book2.Worksheet(1).Delete();
    book2.Save();
    book2.Save();    // <- NullReferenceException
}
```

**Comment by igitur** [comment]
Issue template clearly states: Attach the file.

**Comment by v0idname** [comment]
I updated issue.
I didn't attach the file, because I have an error with any file (created manually or by ClosedXML).

**Comment by igitur** [comment]
[ClosedXML v0.89.0-beta1](https://www.nuget.org/packages/ClosedXML/0.89.0-beta1) has been published and is ready for your testing.
