### ISSUE TITLE
VLOOKUP is considered 'Bad expression'

### ISSUE THREAD

**Issue by fmystal** [ClosedXML/ClosedXML#438]
**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [X] Feature

Version =0.88.0

Cells where `VLOOKUP` excel functions is getting a decimal value, are considered as wrong expressions throwing a 'Bad expression' exception.

Although this behavior should be not  considered a bug, lets see steps to reproduce it:
Create an excel workbook with decimal values in any columns
Add a `VLOOKUP` function in any column referencing several columns which were set in the previous step
Try to get the cell result decimal value which `VLOOKUP` function has calculated into a decimal var (using c# console project for example)
```c#
Decimal cellValue= xlWorksheet.Cell(cellPosition).GetValue<Decimal>();
```

Decimal var should set withn the function result from excel workbook

This has never worked.  

- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)
[wookbook_example_issue.xlsx](https://github.com/ClosedXML/ClosedXML/files/1214417/wookbook_example_issue.xlsx)

**Code to reproduce problem:**
```c#
public void Main()
{
    try
    {
        XLWorkbook xlWorkBook = new XLWorkbook(..\wookbook_example_issue.xlsx);
        IXLWorksheet xlWorksheet = xlWorkBook.Worksheet('TC Eikon');
        string cellPosition = "I20";
        Decimal valorformula = xlWorksheet.Cell(cellPosition).GetValue<Decimal>();
        Console.writeLine(String.Format("Cell value is: {0}", cellPosition.ToString()));
    }
    catch (Exception ex)
    {
        Console.writeLine(String.Format("Exception trown: {0}", ex.Message));
    }
}
```

**Comment by igitur** [comment]
Cell `I20` contains the formula `VLOOKUP("1Y=",$A$8:$D$65,4,)`.

The last parameter is causing a problem. The comma is included so the formula parser is expected a parameter. Either include the parameter or remove the last comma.

I'll look at a fix, but it might take a while. I would recommend you rather use well defined parameters, especially with VLOOKUPs.

**Comment by fmystal** [comment]
Even deleting last comma, exception is being thrown.
Even more, after this comma no value is mandatory using VLOOKUP function (is set by default)

**Comment by igitur** [comment]
`ClosedXML` isn't 100% compatible with the way Excel treats formulae. Make it easy for yourself and explicitly enter all parameters. And don't start formulae with a +. If you do, `ClosedXML` will treat the values as numeric, so `=+MID(...)` will return `0`. Rather use `=MID(...)`.

**Comment by igitur** [comment]
[ClosedXML v0.89.0-beta1](https://www.nuget.org/packages/ClosedXML/0.89.0-beta1) has been published and is ready for your testing.
