### ISSUE TITLE
When opening the given file, ClosedXML crash with the message 'The picture name 'Group 1' already exists.'

### ISSUE THREAD

**Issue by Tarboeuf** [ClosedXML/ClosedXML#444]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**ClosedXML 0.88.0**

**What is the current behavior?**

When opening the given file, ClosedXML crash with the message 'The picture name 'Group 1' already exists.'
This file can be opened in Excel 2016.

**Did this work in previous versions of our tool?  Which versions?**
This worked with the version 0.87.1

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Headers.xlsx](https://github.com/ClosedXML/ClosedXML/files/1218379/Headers.xlsx)

**Code to reproduce problem:**
```c#
public void Main()
{
   using (XLWorkbook workbook = new XLWorkbook(@"Headers.xlsx"))
   {
   }
}
```

**Comment by igitur** [comment]
Wow, I didn't know Excel allows duplicate shape names. It's going to take some time to sort that out. In the meantime, I suggest you remove the duplicate group box or rename it to something else.

**Comment by igitur** [comment]
[ClosedXML v0.89.0-beta1](https://www.nuget.org/packages/ClosedXML/0.89.0-beta1) has been published and is ready for your testing.
