### ISSUE TITLE
A trial to rename a worksheet to its original name or a name modified only in character casing results in a "duplicate name" exception.

### ISSUE THREAD

**Issue by Chr-Spieler-Ffm-de** [ClosedXML/ClosedXML#446]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.88.0

**What is the current behavior?**
We use code to rename a worksheet. The new name differs from the original name only by case.
After updating to Version 0.88.0, the rename Operation fires an exception "name already exists in workbook". (This is not the exact wording of the error message...)

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

See the short demo method below...

When this test function gets called, all three "rename" operations should succeed without
raising any exception. However, currently, the code checks if the new name already exists in the workbook (by applying case-insensitive [ordinal ??] string comparison), without excluding the name of the target worksheet. According to the fixed issues for 0.88.1, this "check for name duplicates" has been added recently.

**What is the expected behavior or new feature?**

As in Excel itself, renaming a sheet to its original name or applying just character case changes to a sheet name should be considered as valid rename operations.

**Did this work in previous versions of our tool?  Which versions?**
This worked in Version 0.87.1

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
void sheetRenameDemos(IXLWorksheet tstSheet)
{
    // new sheet name is identical to original name (a NO-OP...)
    tstSheet.Name = tstSheet.Name;

    // new sheet name may differ from old sheet name only by character casing...:
    tstSheet.Name = tstSheet.Name.ToLower();
    tstSheet.Name = tstSheet.Name.ToUpper();
}
```

**Comment by igitur** [comment]
[ClosedXML v0.89.0-beta1](https://www.nuget.org/packages/ClosedXML/0.89.0-beta1) has been published and is ready for your testing.
