### ISSUE TITLE
ClosedXML in a .NET 4 Environemt

### ISSUE THREAD

**Issue by mwangepatrick** [ClosedXML/ClosedXML#450]
There seems to be a bug when trying to use closedxml with .net 4, 
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

Version 0.76.0 install via nuget package manager

**What is the current behavior?**

All compiles just fine, however trying to export my datatable to excel, I get the error that could load closedxml version 0.88.0 or one of its dependencies.

Since I am using version 0.76.0 I don't see why the reference to 0.88..

**Comment by igitur** [comment]
Shy don't you just upgrade?

**Comment by mwangepatrick** [comment]
Yeah, I am using the DLL in a project that is currently stuck at .NET 4 and since the the latest version of closedXML does not support .NET 4, I can't upgrade closedxml as well.

**Comment by vbjay** [comment]
Of course you can. You can use 2.0 libraries in 4.0 projects for example.

**Comment by igitur** [comment]
I'll see if I can include a NET40 build from the next release onwards.

But unfortunately I have no idea what causes your problem.

**Comment by igitur** [comment]
@mwangepatrick Try the NET40 artifacts at https://ci.appveyor.com/project/Pyropace/closedxml/build/artifacts

You will have to install the following dependencies manually:
- https://www.nuget.org/packages/DocumentFormat.OpenXml
- https://www.nuget.org/packages/FastMember.Signed

**Comment by mwangepatrick** [comment]
@igitur Works as expected. 

Thanks a lot.

**Comment by igitur** [comment]
I'm reopening this issue. Once I merge it, I will close it again. When it's merged, you can use the release from NuGet.

**Comment by igitur** [comment]
@mwangepatrick May I ask why your project is stuck on .NET4.0? Upgrading to .NET4.5.2 should be relatively easy. And many bugs were fixed. Both versions run on CLR4, so there weren't any major API changes.

**Comment by JavierJJJ** [comment]
I use net4.0 on some clients that use Windows xp. If continue Support it's excelent

**Comment by igitur** [comment]
This will be fixed in #315 but I'm looking for people to test. Also see comments in #101

**Comment by JavierJJJ** [comment]
Can you help me how I test? I can check functionality the library that I use on some clients and test.

**Comment by jupe** [comment]
I would like to have .NET 4 support as well. Tried with VS2012 but even with .NET 4.5.2 this doesn't compile anymore because there is features which landed to C# 6 like string interpolation etc.. There seems to be possible to get it work using NuGet package [Microsoft.Net.Compilers](https://www.nuget.org/packages/Microsoft.Net.Compilers/) but I'm not sure do I want to get it - could it cause any other trouble..

**Comment by igitur** [comment]
@jupe You can download VS Community 2015 for free and build with that.

Or look at the .NET 4 build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.547/artifacts

**Comment by mwangepatrick** [comment]
@igitur I can assist in testing cloxedxml for 4.0 support. I have been working with .NET 4 and overtime my application has so many .NET 4 dependencies so I can't simply upgrade to version 4.5.

**Comment by igitur** [comment]
@mwangepatrick .NET 4.5 is basically a drop-in replacement for .NET 4.0, so upgrading should be trivial. I don't understand what's holding you back.

**Comment by igitur** [comment]
Merging this into #101

**Comment by balamcsd** [comment]
When i use closedxml with visual studio 2012 .NET framework 4.5 MVC project , it does not work (internal server error)
Same working in vs 2017. How to fix it vs2012
Thanks
