### ISSUE TITLE
How to contribute to the wiki?

### ISSUE THREAD

**Issue by colinwurtz** [ClosedXML/ClosedXML#453]
Is the wiki open for pull requests? How do we contribute? I wanted to add some documentation to the Data Validation section, but when I pull it down I get the git errors below. It then shows every file as deleted and un-tracked. 

```
Resolving deltas: 100% (262/262), done.
error: unable to create file Does-it-support-Excel-2003-and-prior-formats-(.xls)                                                ?.md: Invalid argument
error: unable to create file How-can-I-insert-an-image?.md: Invalid argument
error: unable to create file How-do-I-get-the-result-of-a-formula?.md: Invalid a                                                rgument
error: unable to create file Text-with-numbers-are-getting-converted-to-numbers,                                                -what's-up-with-that?.md: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
```

**Comment by vbjay** [comment]
What is are you on?  ? Are not valid file name characters.

**Comment by colinwurtz** [comment]
Windows 10

**Comment by igitur** [comment]
Ok, let's experiment. Try doing a PR against https://github.com/ClosedXML/ClosedXML-wiki 

After merging, I'll have to sync it to the actual wiki. 

@vbjay Are you going to help contribute too?

**Comment by igitur** [comment]
@colinwurtz When I created the wiki way back, I did it locally from a Linux machine. I never clone it on a Windows machine before.

**Comment by igitur** [comment]
Ok, it's the question marks that are causing the trouble. I'll fix it on my side.

**Comment by igitur** [comment]
Try cloning again. The question marks are removed from the files.

**Comment by colinwurtz** [comment]
Just cloned down and no errors. 👍

**Comment by igitur** [comment]
While we're at it... I'm aware that the Pivot Tables and Images sections have to be updated. Most of the code samples come from the `ClosedXML_Examples` projects, so look there for updated code.

Also, the general layout of the topics needs to be updated. At the moment the wiki homepage and sidebar are basically identical. That's not ideal.

**Comment by colinwurtz** [comment]
Ok, sorry thought I had everything I needed. Is there a preferred way to contribute to the wiki? Seems you can't fork it in the same way you would normally fork the main repo and submit a PR.

**Comment by igitur** [comment]
Have you tried to fork  https://github.com/ClosedXML/ClosedXML-wiki

**Comment by vbjay** [comment]
Yes. I plan on it. I just got hired as a programmer Analyst. Learning
systems. Been pretty tired after work. Once I get in the groove, I plan on
jumping in.

**Comment by igitur** [comment]
Congrats on the job. Do what I do: work on ClosedXML during coffee breaks and lunch ;-)

**Comment by vbjay** [comment]
Lol. Got to eat some tine.

**Comment by igitur** [comment]
@colinwurtz Let me know if you succeed.

**Comment by igitur** [comment]
Hey, @colinwurtz , did you succeed or did I waste my time setting this up for you?

**Comment by colinwurtz** [comment]
Sorry been busy, just forked and create a pull request.

https://github.com/ClosedXML/ClosedXML-wiki/pull/2
