### ISSUE TITLE
Sparkline support - Charting

### ISSUE THREAD

**Issue by manoc** [ClosedXML/ClosedXML#454]
**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [X] Feature

**Version of ClosedXML**

0.88.0

**What is the current behavior?**

I haven't found any documentation on how to create a Sparkline, Looks like this feature is not implemented in ClosedXML. 
Are there any plans to implement this feature?

**Comment by vbjay** [comment]
Make it happen.

**Comment by vbjay** [comment]
That’s Not My Job

This is a story about four people named Everybody, Somebody, Anybody and
Nobody.  There was an important job to be done and Everybody was sure that
Somebody would do it.  Anybody could have done it, but Nobody did it.
Somebody got angry about that, because it was Everybody’s job.  Everybody
thought Anybody could do it, but Nobody realized that Everybody wouldn’t do
it.  It ended up that Everybody blamed Somebody when Nobody did what
Anybody could have

**Comment by igitur** [comment]
LOL - what went on here?

**Comment by igitur** [comment]
@manoc Attach a sample spreadsheet with what you want and I'll look into it.

**Comment by manoc** [comment]
Generated sparkline in attached Excel in "Column N" using Microsoft Excel.
[SparkLine.xlsx](https://github.com/ClosedXML/ClosedXML/files/1245542/SparkLine.xlsx)

I'm trying to achieve the same using ClosedXML if possible.

**Comment by igitur** [comment]
Ok, this isn't supported at the moment and there isn't a quick implementation. This will probably fall under general charting support when I start working on that.

**Comment by ghronkrepps** [comment]
I'm looking to implement this as a requirement for a project. Can you give any direction on how to implement this, and/or example of current feature that this would be similar to?

**Comment by Pankraty** [comment]
Very well said, it's worth putting in Wiki I think.

I often start with tests, but that's just a matter of personal preferences.

Things to test (rough checklist):
* Load existing file with sparklines and make sure they exist
* Generate a new file with sparklines, load it and make sure they exist
* Delete sparklines, save the file, load it and make sure they've gone
* Add sparklines, add/remove some rows/columns and make sure the ranges they refer to and ranges they are placed too are properly shifted
* Add sparklines, remove the range containing them and make sure they've gone
* Copy cells having sparklines to the same worksheet and make sure the new cell have sparklines too. Ideally, the sparklines themselves must not be multiplied - instead, the existing entries must cover new ranges (their addresses must be checked too)
* Copy cells having sparklines to another worksheet and make sure they are copied
* Copy worksheet having sparklines to another workbook, save it, load it and make sure sparklines exist

Perhaps you will need to perform the consolidation of sparklines on the worksheet like it is done for conditional formats and data validation rules.

**Comment by ghronkrepps** [comment]
I have some basic sparkline support workiung. I am able to load a file with sparklines and save a file with sparklines.

I would prefer to have one of you more experienced developers take a look at what I have so far and let me know if I am implementing this well. Is the best way to do this a pull request? I'm new to github devlopment so any pointers on how to do that would be appreciated.

Thanks.

**Comment by vbjay** [comment]
So make sure your sparkling work is in it's own branch. Push your branch up
to your work of our repo. Create a pull request to pull from your branch to
our develop branch.

**Comment by ghronkrepps** [comment]
I think I got it. hanks for your patience!

**Comment by igitur** [comment]
Closed by #1175
