### ISSUE TITLE
Image scale on production server

### ISSUE THREAD

**Issue by codeweb** [ClosedXML/ClosedXML#461]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.88

**What is the current behavior?**

I added a picture in a worksheet using the following methods; AddPicture() and MoveTo() a cell.
It worked nicely in localhost. On the production server the image was scaled at 80%.
I tried also using a jpg image.
I tried also to force to scale 100% to original on XLPicture.

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

**What is the expected behavior or new feature?**

The image would be sized 100% also on production server.

**Did this work in previous versions of our tool?  Which versions?**

I don't know.

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**

The code is not tested and it comes from a web page.
```c#
public void Main()
{
     XLWorkbook workbook = new XLWorkbook();
     IXLWorksheet worksheet = workbook.Worksheets.Add("Registro");
     worksheet.PageSetup.PaperSize = XLPaperSize.A4Paper;
     worksheet.PageSetup.Margins.Top = 0.5;
     worksheet.PageSetup.Margins.Bottom = 0.5;
     worksheet.PageSetup.Margins.Left = 0.3;
     worksheet.PageSetup.Margins.Right = 0.3;
     worksheet.PageSetup.Margins.Footer = 0.3;
     worksheet.PageSetup.Margins.Header = 0.3;
     worksheet.PageSetup.CenterHorizontally = true;
     worksheet.PageSetup.CenterVertically = true;

     IXLColumn colA = worksheet.Column("A");
     colA.Width = 4;
     IXLColumn colB = worksheet.Column("B");
     colB.Width = 20;
     IXLColumn colC = worksheet.Column("C");
     colC.Width = 25;
     IXLColumn colD = worksheet.Column("D");
     colD.Width = 20;
     IXLColumn colE = worksheet.Column("E");
     colE.Width = 25;

     using (Image image = Image.FromFile(Server.MapPath("~/img/logo.png")))
     {
          using (MemoryStream stream = new MemoryStream())
          {
               // Save image to stream.
                image.Save(stream, ImageFormat.Png);

                IXLPicture logo = worksheet.AddPicture(stream, XLPictureFormat.Png, "LogoImage");
                logo.MoveTo(worksheet.Cell("E1").Address);
          }
     }

     Response.Clear();
     Response.AddHeader("content-disposition", "attachment; filename=Registro.xlsx");
     Response.Charset = "";
     Response.ContentEncoding = System.Text.Encoding.Default;

    // If you want the option to open the Excel file without saving than
    // comment out the line below
    // Response.Cache.SetCacheability(HttpCacheability.NoCache);
    Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    using (MemoryStream myMemoryStream = new MemoryStream())
    {
          workbook.SaveAs(myMemoryStream);
          myMemoryStream.WriteTo(Response.OutputStream);
    }
    Response.Flush();
    Response.End();
}
```

**Comment by igitur** [comment]
Please 2 identical samples of the files, except that one is generated on localhost and the other on the server.

**Comment by codeweb** [comment]
The file is a png 180x96. I tried also using a jpg.

**Comment by codeweb** [comment]
They are private... Please download them and then i will remove.
http://www.expertweb.it/local.xlsx
http://www.expertweb.it/server.xlsx

**Comment by igitur** [comment]
Ok, you should actually have created generic examples so that you don't disclose private info. 

The sizes are stored in [EMUs](http://archive.oreilly.com/pub/post/what_is_an_emu.html), which depend on the Dpi setting of the machine. It looks like the server is set at 120 dpi and your local machine at 96. Can you confirm that?

**Comment by codeweb** [comment]
I'm looking for this setting in Windows 10

**Comment by codeweb** [comment]
Sorry i can't confirm. Where can i edit this setting? In localhost i have a Windows 10: is it the 100% of the display?

**Comment by codeweb** [comment]
Sorry i can't confirm. Where can i edit this setting? In localhost i have a Windows 10: is it the 100% of the display?
I found this article:
https://stackoverflow.com/questions/32123276/openxml-powerpoint-picture-scale-height-width
but i can't understand the code.
Can you help me?

**Comment by igitur** [comment]
What versions of Windows are installed on the localhost and server?

**Comment by codeweb** [comment]
Windows 10 PRO on localhost. I'm asking for the server version

**Comment by codeweb** [comment]
Windows 10 PRO on localhost and -maybe- Windows server 2012.
Please read articles in previous post: maybe are you missing this extents management?

**Comment by codeweb** [comment]
@igitur according to your idea, i could edit 100% (96 dpi) in localhost to get 120 dpi. How? I tried to edit 100% to 125% but it doesn't change.

**Comment by codeweb** [comment]
Other ideas, please?

**Comment by igitur** [comment]
Please confirm the Windows Server version. I want to try to replicate the problem. I appreciate your patience in this regard.

**Comment by igitur** [comment]
Also please execute this from the command line on both machines and paste the output here.

`wmic desktopmonitor get PixelsPerXLogicalInch, PixelsPerYLogicalInch`

**Comment by codeweb** [comment]
Server confirmed

**Comment by codeweb** [comment]
Now i changed 120% in 100% on the server. But i get Always 120 120. Must i restart the server?

**Comment by igitur** [comment]
Ok, now I understand the reason for the image scaling. It's definitely the DPI. 

Internally in an Excel file, the size of an image is stored as a multiple of inches. So if the DPI changes and the dimension of the image (in pixels) remains unchanged, these stored values in the Excel file will change. Therefore the image will have different dimensions if you open it on another machine with a different DPI setting. 

I assume Excel is not installed on the server? I'm curious to see what Excel does when inserting that image.

In the meantime, the easy workaround is to detect the DPI of the machine programmatically and scale the image up as a ratio of 96. You can look at the code in https://github.com/ClosedXML/ClosedXML/blob/develop/ClosedXML/Utils/GraphicsUtils.cs for how to determine the DPI of a machine.

Is it common? I don't know

**Comment by codeweb** [comment]
Thanks!
I can't understand the sample. I know;

> Graphics graphics = this.CreateGraphics(); 
> dpiX = graphics.DpiX; 
> dpiY = graphics.DpiY;

**Comment by igitur** [comment]
```c#
var image = new Bitmap(1, 1);
var graphics = Graphics.FromImage(image);
graphics.DpiX;
```

**Comment by codeweb** [comment]
` Graphics.FromImage(image);`
is 96 in local and on the server
`Graphics.FromHwnd(IntPtr.Zero)`
is 96 in local and 120 on the server
