### ISSUE TITLE
Column Width not working, width is not changing to what I set Column Width to.

### ISSUE THREAD

**Issue by bjm3819** [ClosedXML/ClosedXML#470]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
0.88.0.0
e.g. 0.87.1

**What is the current behavior?**
The excel column width is not sizing to the width I give the Width property. 

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

**What is the expected behavior or new feature?**
The expected behavior would be the excel column would have width of 37 instead of the default I see is set to 8.34 ish. 

**Did this work in previous versions of our tool?  Which versions?**
I do not know. 

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
public void Main()
{
    // Where possible, post full code to reproduce your issue that adheres to:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.

  XLWorkbook workbook = new XLWorkbook();
            IXLWorksheet worksheet = workbook.Worksheets.Add("Default");
 worksheet.Cell(rowI, colI).Value = "someColumnName";
                    worksheet.Cell(rowI, colI).Style.Font.Bold = true;
           
                        worksheet.Column("L").Width = 37;
}
```

**Comment by igitur** [comment]
Please post complete code, ie define and initialize your variables.

**Comment by bjm3819** [comment]
sorry..

public void Main()
{
    // Where possible, post full code to reproduce your issue that adheres to:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
           string filePath = "C:\tempExcel\file1.xlsx";
           XLWorkbook workbook = new XLWorkbook();
            IXLWorksheet worksheet = workbook.Worksheets.Add("Default");
            worksheet.Cell(0, 0).Value = "someColumnName";
           worksheet.Cell(0, 0).Style.Font.Bold = true;
           worksheet.Column("L").Width = 37;
           workbook.SaveAs(filePath);             
}

**Comment by igitur** [comment]
@bjm3819 ClosedXML v0.89 is out on NuGet. Please test with that and let me know. I need the feedback.

**Comment by maazsofttech** [comment]
> @bjm3819 ClosedXML v0.89 is out on NuGet. Please test with that and let me know. I need the feedback.

Great @igitur  , v0.89 is generating excel as per content length by default  (that's what i was looking for)

**Comment by SScilly** [comment]
Hello,
it seems that this feature is not working :-(
I use 0.95.3 and when I assign the colmn size I get always 82px width regarless the size I put.

 ws.Column(columnLetters).Width=aWidth;
Debug.WriteLine("Set column "+ ws.Column(columnLetters).ColumnLetter()+ " to:" + aWidth);

DEBUG OUTPUT IS
Set column A to: 60

but the resulting column size is 8,33 

![image](https://user-images.githubusercontent.com/71710205/93890042-33cf6c80-fcea-11ea-9de5-1bc9b8915722.png)

**Comment by Pankraty** [comment]
@SScilly check that you are not disposing a workbook before saving (it caused the similar symptoms, as I recall) and if this is not the case then submit a new issue with the minimal reproduction sample.

**Comment by iBolski** [comment]
I'm using ClosedXML v0.95.3.0. I want to set a column width to 0.08 but it's not working. This is how I do it:

worksheet.Column(1),Width = 0.08;

But when I open the spreadsheet, it's wider than 0.08. Any ideas?
