### ISSUE TITLE
XLCell InsertData / InsertTable does not output const or static fields.

### ISSUE THREAD

**Issue by aacx97** [ClosedXML/ClosedXML#471]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
0.88

**What is the current behavior?**
0.88 release now uses BindingFlags.Public | BindingFlags.Instance to get the field/property names, and as a result does not output anything const or static. There are times when this is desired, it should probably be an option for whether you want those excluded or not.

**Did this work in previous versions of our tool?  Which versions?**
Yes, 0.87

**Comment by igitur** [comment]
https://www.nuget.org/packages/ClosedXML/0.90.0-beta2 is released and should include the fix for this issue.
