### ISSUE TITLE
Change the Caption for the RowLabels in Pivot Table 

### ISSUE THREAD

**Issue by herlines** [ClosedXML/ClosedXML#473]
**Version of ClosedXML**

0.88

Hi everyone
I have in issue with the pivot tables
I would like to change the Caption of the RowLabels (today is the excel's by default one) and i couldnt find any funcionality to achieve that
Can u please help me??
I dnt know if is a bug or not. I think that is only not implemented yet
Thank u in advance
Sorry for my english...

this is my C# code
```c#
private void createTabellaPivot(IXLWorksheet foglioPivot, IXLWorksheet foglioData, int ultRiga)
{
	IXLRange source = foglioData.Range("A8:M" + ultRiga.ToString());


	foglioPivot.Column("A").Width = 40.00;
	foglioPivot.Column("B").Width = 20.00;
	foglioPivot.Column("C").Width = 20.00;
	foglioPivot.Column("D").Width = 20.00;


	IXLPivotTable xlPvTable = foglioPivot.PivotTables.AddNew("PivotTable", foglioPivot.Cell(3, 1), source);

	xlPvTable.RowLabels.Add("Riga");

	xlPvTable.Values.Add("Delta", "Scostamento Min").SetSummaryFormula(XLPivotSummary.Minimum);
	xlPvTable.Values.Add("Delta1", "Scostamento Max").SetSummaryFormula(XLPivotSummary.Maximum);
	xlPvTable.Values.Add("Delta2", "Scostamento Medio").SetSummaryFormula(XLPivotSummary.Average).NumberFormat.Format= "#,##0.00";

	xlPvTable.ShowGrandTotalsRows = false;
}
```
this is my result: Attached1
this is what i would like to: Attached2

![attached1](https://user-images.githubusercontent.com/31657653/30206915-ef7bf430-948d-11e7-8efc-0ccaa66fd34f.png)
![attached2](https://user-images.githubusercontent.com/31657653/30206914-ef7ad24e-948d-11e7-92e1-83e906f2090f.png)

My Excel is Excel2010 Italian version
Excel by default writes "Etticchette Di Riga" as caption for the rows fields and this is what i want to change

**Comment by igitur** [comment]
Correct, this is not implemented yet. Pivot tables are work in progress.

**Comment by igitur** [comment]
Please test with the build at at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.595/artifacts

You can use `IXLPivotTable.RowHeaderCaption` and `IXLPivotTable.ColumnHeaderCaption` to set these.

Also `IXLPivotTable.SetRowHeaderCaption(String value)` and `IXLPivotTable.SetColumnHeaderCaption(String value)`

**Comment by igitur** [comment]
https://www.nuget.org/packages/ClosedXML/0.90.0-beta2 is released and should include the fix for this issue.
