### ISSUE TITLE
Unhide worksheets not working

### ISSUE THREAD

**Issue by peetn** [ClosedXML/ClosedXML#476]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.88.0 (but was already present long before)

**What is the current behavior?**

Hiding a sheet works fine - that is OK
UNHIDING a sheet that was hidden and saved doesn't work. Nothing happens
I assume XLWorkbook_Save.cs needs to do this command always (not only when hiding):
sheet.State = xlSheet.Visibility.ToOpenXml();

**What is the expected behavior or new feature?**

Unhiding should show the sheet

**Did this work in previous versions of our tool?  Which versions?**

Not that I'm aware of. It was already failing in V0.60.0.0

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
            // create a file with a visible sheet and a hidden sheet
            string path = @"c:\temp\testonline.xlsx";
            var wb = new XLWorkbook();
            wb.Worksheets.Add("Visiblesheet");
            wb.Worksheets.Add("hiddensheet").Hide();
            wb.SaveAs(path);

            // unhide the hidden sheet
            XLWorkbook w = new XLWorkbook(path);
            IXLWorksheet s = w.Worksheets.Skip(1).First();
            if (s.Visibility == XLWorksheetVisibility.Hidden)
            {
                s.Unhide();
                // OR (neither work and Unhide is only a shortcut to change the visibility)
                //s.Visibility = XLWorksheetVisibility.Visible;
            }
            w.Save();

            // validate 
            w = new XLWorkbook(path);
            s = w.Worksheets.Skip(1).First();
            if (s.Visibility == XLWorksheetVisibility.Hidden)
            {
                Console.WriteLine("bug reproduced");
            }

}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
You can test with the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.534/artifacts
