### ISSUE TITLE
Enum or static number/date format ids and/or codes

### ISSUE THREAD

**Issue by wachulski** [ClosedXML/ClosedXML#478]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

**What is the current behavior?**

I need to go to https://github.com/closedxml/closedxml/wiki/NumberFormatId-Lookup-Table to check which id corresponds to what format code. I was just wondering if you could you make this enum or some static instances with proper XML summary docs? Then I'd simply navigate to declarations and remain within an IDE. Moreover, your list is not complete as https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.numberingformat.aspx provides more options.

**What is the expected behavior or new feature?**

```csharp
range.Style.NumberFormat.NumberFormatId = NumberFormat._1; // or
range.Style.NumberFormat.NumberFormatId = NumberFormatIds._1 // or 
range.Style.NumberFormat.NumberFormatId = NumberFormats.ZeroZeroDotZero // etc.
```

**Comment by vbjay** [comment]
You are welcome to add code.
