### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by igitur** [ClosedXML/ClosedXML#48]

**Comment by LesediM** [comment]
Hi When is this feature expected to be available?

**Comment by igitur** [comment]
When someone implements it. You're welcome to contribute by submitting pull requests.

**Comment by clinchergt** [comment]
Thoughts on this[1] fork's implementation of some rudimentary image support? 

[1]: https://closedxml.codeplex.com/SourceControl/network/forks/ajwhiteway/ClosedXMLImageSupport/changeset/cf33532eacb59f5392a809c301379cd6b6abf070

**Comment by igitur** [comment]
@clinchergt I have started looking at that fork, but at the moment we're squashing bugs before adding significant new enhancements.
