### ISSUE TITLE
Font name is not respected for right-to-left fonts

### ISSUE THREAD

**Issue by nefcanto** [ClosedXML/ClosedXML#480]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.87.0.0

**What is the current behavior?**

Font name is not applied. While after opening Excel the font name is shown on selecting the cell, the content is not actually rendered in that font. By changing font and changing back the correct font name is applied.

**What is the expected behavior or new feature?**

By setting the font name in program, the correct font be applied.

**Did this work in previous versions of our tool?  Which versions?**

I don't know.

## Reproducibility
Here is a simple program, and the result in gif:

```c#
    class Program
    {
        static void Main(string[] args)
        {
            using (var workbook = new ClosedXML.Excel.XLWorkbook())
            {
                var sheet = workbook.Worksheets.Add("Test");

                var a1 = sheet.Cells("A1");
                a1.Value = "سلام";
                a1.Style.Font.FontName = "Tahoma";
                a1.Style.Font.FontSize = 36;

                var a2 = sheet.Cells("A2");
                a2.Value = "سلام";
                a2.Style.Font.FontName = "B Yagut";
                a2.Style.Font.FontSize = 36;

                var a3 = sheet.Cells("A3");
                a3.Value = "سلام";
                a3.Style.Font.FontSize = 36;

                sheet.Columns("A").AdjustToContents();
                workbook.SaveAs(@"C:\Temp\ClosedXmlFontTest.xlsx");
            }
        }
    }
```

Here's the result file, it's NOT opened yet:
[ClosedXmlFontTest.xlsx](https://github.com/ClosedXML/ClosedXML/files/1293213/ClosedXmlFontTest.xlsx)

And here's the gif, showing it on my desktop (opened another copy, not the one attached here):
![closedxmlfonttest](https://user-images.githubusercontent.com/12782347/30284653-c4167086-9730-11e7-9d0d-704b31908f9c.gif)

Excel version: 2016 MSO (16.0.4266.1001) 64-bit
Windows version: 10 Enterprise 64-bit

**Comment by vmrocha** [comment]
Can you make the font files available?

**Comment by igitur** [comment]
I have installed the `B Yagut` font. If I run your code, I get this:
![image](https://user-images.githubusercontent.com/145854/30488169-dffde6aa-9a35-11e7-925d-050a87bfe715.png)
 <hr />
If I run this code (notice the extra line that sets the FontFamilyNumbering)

```c#
using (var workbook = new XLWorkbook())
{
    var sheet = workbook.Worksheets.Add("Test");

    var a1 = sheet.Cells("A1");
    a1.Value = "سلام";
    a1.Style.Font.FontName = "Tahoma";
    a1.Style.Font.FontSize = 36;

    var a2 = sheet.Cells("A2");
    a2.Value = "سلام";
    a2.Style.Font.FontName = "B Yagut";
    a2.Style.Font.FontSize = 36;
    a2.Style.Font.FontFamilyNumbering = XLFontFamilyNumberingValues.NotApplicable;

    var a3 = sheet.Cells("A3");
    a3.Value = "سلام";
    a3.Style.Font.FontSize = 36;

    sheet.Columns("A").AdjustToContents();
    workbook.SaveAs(@"ClosedXmlFontTest2.xlsx");
}
```

![image](https://user-images.githubusercontent.com/145854/30488235-0e46d83c-9a36-11e7-97ee-61e3c2dbb920.png)

Is that the expected output?

**Comment by nefcanto** [comment]
Sorry for the delay in response. This is the font pack link:

http://cdn.p30download.com/?b=p30dl-graphic&f=B.Borna.Rayaneh.ttf-png_p30download.com.zip

@igitur, that's in fact the expected result. But as I try it on my PC I don't get that result. My configuration is mentioned above, and also by reading that line all I understand is that it's related to "numbers" which is not included in this sample. Though it might trigger a behavior that makes the font getting applied.

**Comment by igitur** [comment]
@nefcanto Please run that code sample of mine and attach the file that it produces.

**Comment by nefcanto** [comment]
@igitur, this is what has been created.
[ClosedXmlFontTest2.xlsx](https://github.com/ClosedXML/ClosedXML/files/1308446/ClosedXmlFontTest2.xlsx)

May I first thank you for your awesome work and the time you spend on this. Because you have truly helped us by making things super easy. Even if this issue is not fixed, I still use ClosedXML as the number one and the only library in my works. It's thin, lightweight, easy to work with, and really developer-friendly.

**Comment by igitur** [comment]
Thanks, but `ClosedXML` was mostly created by a previous developer. You have to thank him.

What version of `DocumentFormat.OpenXml` are you using? I suspect you're using an old version.

**Comment by nefcanto** [comment]
I upgraded to the latest version of `ClosedXML` (version 0.89.0.0), and also `DocumentFormat.OpenXml` (version 2.7.2.0).
However, the problem didn't get solved.

**Comment by igitur** [comment]
Ok, send me the file that it creates now (after the upgrading).

**Comment by nefcanto** [comment]
[ConsoleApp9.zip](https://github.com/ClosedXML/ClosedXML/files/1310344/ConsoleApp9.zip)
[ClosedXmlFontTest2.xlsx](https://github.com/ClosedXML/ClosedXML/files/1310345/ClosedXmlFontTest2.xlsx)

I attached both the project which created the file, and the file created without being opened.

**Comment by igitur** [comment]
Ok, now we get the same files.

Do this:
- Open `ClosedXmlFontTest2.xlsx` in Excel
- Save it without making any changes as `Excel1.xlsx`
- Make the changes to fix the font and save it as `Excel2.xlsx`
- Attach both files.

**Comment by nefcanto** [comment]
[Excel1.xlsx](https://github.com/ClosedXML/ClosedXML/files/1310371/Excel1.xlsx)
[Excel2.xlsx](https://github.com/ClosedXML/ClosedXML/files/1310372/Excel2.xlsx)

I opened `ClosedXmlFontTest2.xlsx` in Excel
I saved it to `Excel1.xlsx` without any changes
I then applied changes to fix the font
I saved it to `Excel2.xlsx`

**Comment by igitur** [comment]
[Excel1_modified.xlsx](https://github.com/ClosedXML/ClosedXML/files/1310462/Excel1_modified.xlsx)
Does this Excel file have the problem?

**Comment by nefcanto** [comment]
No, It was OK. What did you do to it?

**Comment by igitur** [comment]
There is a hidden `charset` variable that is set to 178 (Arabic). `ClosedXML` doesn't use the variable at all and leaves it empty. I'll either have to expose it to the user or get a way to detect the charset from the font. I don't know much about font charsets, so any help would be appreciated.

**Comment by igitur** [comment]
[ClosedXmlFontTest_charset_added.xlsx](https://github.com/ClosedXML/ClosedXML/files/1310697/ClosedXmlFontTest_charset_added.xlsx)

Does this file work?

**Comment by nefcanto** [comment]
Yep. The `ClosedXmlFontTest_charset_added.xlsx` is fine too. I don't know things about font either. Let me search to see what can I find.

**Comment by nefcanto** [comment]
Are you using [System.Drawing.Font](https://msdn.microsoft.com/en-us/library/system.drawing.font.gdicharset(v=vs.110).aspx)?

**Comment by igitur** [comment]
Try the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.556/artifacts

Set the charset like this:
```c#
a2.Style.Font.FontCharSet = XLFontCharSet.Arabic;
```

No, not using `System.Drawing.Font`.

**Comment by nefcanto** [comment]
Well, I tested it, and it worked. Thank you so much.

**Comment by igitur** [comment]
https://www.nuget.org/packages/ClosedXML/0.90.0-beta2 is released and should include the fix for this issue.
