### ISSUE TITLE
Unable to create an excel file properly

### ISSUE THREAD

**Issue by Bikash89** [ClosedXML/ClosedXML#481]
Hi All,

I am using ClosedXML.Excel for creating new excel file from an another excel file based on worksheets.

I will be splitting the workbook based on worksheets and will create a new file.
I used vb.net code.

Using xlBook As New XLWorkbook(files.FilePath)
     Dim xlSheets As IXLWorksheets = xlBook.Worksheets()
         For Each xlSheet As IXLWorksheet In xlSheets
             Dim wb As XLWorkbook = New XLWorkbook
             wb.AddWorksheet(xlSheet)
             wb.SaveAs(sOutPath + "\" + xlSheet.Name + ext)
             wb.Dispose()
         Next
 End Using

By using the above code, I am able to create a new file.
But when I am trying to read the newly created file it's not able to.
Even when I am opening the file by double-clicking and then closing(Without doing any change) its asking to save.

I feel like there is a problem while writing the new file.

Could you please help me out?

Thanks In Advance
Bikash Kumar

**Comment by igitur** [comment]
[RTFM](https://github.com/ClosedXML/ClosedXML/blob/develop/.github/ISSUE_TEMPLATE.md)

**Comment by vbjay** [comment]
Why not just use xlbook.saveas(...)?

**Comment by Bikash89** [comment]
Hi @vbjay 

Thanks for your reply.

I can't use that xlbook.saveas(...)? directly because

- I need to pick the xlsheet from the parent workbook
- My requirement is to create new excel workbook from the parent workbook based on each worksheet. i.e. as many sheets are there in the parent workbook, those many new excel workbook I will create with the same data.

**Comment by vbjay** [comment]
Yes you can.

Declare array of paths that is in order of sheets in workbook.

Use saveas on each path in array
Use a counter loop to open each path in array and use index to know which
sheet to keep. Remove the others and save.
