### ISSUE TITLE
will support add image to excel?

### ISSUE THREAD

**Issue by hiwoei** [ClosedXML/ClosedXML#482]
## Read and complete the full issue template

will support add image to excel?

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

**Version of ClosedXML**

e.g. 0.87.1

**What is the current behavior?**

Complete this.

**What is the expected behavior or new feature?**

Complete this.

**Did this work in previous versions of our tool?  Which versions?**

Yes/No/v0.XX

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by bastien-boussouf** [comment]
Version 0.88 introduced a first version of this 
https://github.com/ClosedXML/ClosedXML/wiki/How-can-I-insert-an-image

**Comment by hiwoei** [comment]
Thnak you , It's Work
