### ISSUE TITLE
Fail to instantiate workbook if there are duplicate pictures across the worksheets. The picture id {value} already exists!

### ISSUE THREAD

**Issue by sylfree9999** [ClosedXML/ClosedXML#484]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**

0.89.0.0
visual studio 2015

**What is the current behavior?**

Fail to instantiate XLWorkbook if there are duplicate pictures in different worksheets. You can find the attached test file below.

**What is the expected behavior or new feature?**

Successfully instantiate an XLWorkbook object.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
I have tried two ways of instantiating XLWorkbook. One is by using stream to upload from web page, another one is directly reading file from the local system(you may need to change the path.) Both failed. You can create a basic MVC project and add upload function in there.

**Code to reproduce problem:**
```c#
    public ActionResult TestFile()
    {
        using (FileStream stream = System.IO.File.Open(@"C:\Users\xxx\Desktop\TestPic.xlsx", FileMode.Open))
        {
            using (XLWorkbook workbook = new XLWorkbook(stream))
            {
            }
        }
        return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult Index(HttpPostedFileBase file)
    {
        if (file.ContentLength > 0)
        {
            var fileName = Path.GetFileName(file.FileName);
            var path = Path.Combine(Server.MapPath("~/User/"), Guid.NewGuid() + "_" + fileName);
            var fileStream = new FileStream(path, FileMode.Create, FileAccess.ReadWrite);
            file.InputStream.CopyTo(fileStream);
            var test = new XLWorkbook(fileStream);
            fileStream.Close();
        }

        return RedirectToAction("Index");
    }
```
- [ ] Attached sample file: [TestPic.xlsx](https://github.com/ClosedXML/ClosedXML/files/1305455/TestPic.xlsx)
- [ ] Attached core code of the sample project:
[TestProjectCode.zip](https://github.com/ClosedXML/ClosedXML/files/1305511/TestProjectCode.zip)
- [ ] Attached console app. The console app is referencing ClosedXML-develop project dll:
[ConsoleApp.zip](https://github.com/ClosedXML/ClosedXML/files/1309088/ConsoleApp.zip)
![20170917210435](https://user-images.githubusercontent.com/15099465/30521100-2aeca4e6-9bec-11e7-9990-e05a0472f14f.png)

**Comment by igitur** [comment]
Is the MVC part relevant or can you reproduce it in a console application?

**Comment by sylfree9999** [comment]
@igitur Please see the updated post,many thanks

**Comment by igitur** [comment]
You can test with the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.553/artifacts

**Comment by igitur** [comment]
https://www.nuget.org/packages/ClosedXML/0.90.0-beta2 is released and should include the fix for this issue.
