### ISSUE TITLE
Inserting formula

### ISSUE THREAD

**Issue by rvkstudent** [ClosedXML/ClosedXML#486]
**Version of ClosedXML**
0.89
## Reproducibility

My code inserts formula, but this formula inserdet as text (i think) because it evelueting only when i double clicked to each cell. If i insert A+B such method - its all OK. Please help. Where is the problem? Thanks.

**Code to reproduce problem:**
```c#
public void Main()
{
    for (int i = row_num + 1; i <= strok_vniz + row_num + 1; i++)
    {
        var cellWithFormulaA1 = ws.Cell(i, column_num);
        cellWithFormulaA1.FormulaA1 = "==ВПР(" + ws.Cell(i, column_num - 1).Address.ToString() + ";" + range + ";" + prm[6] + ";1)";

        ws.Cell(i, column_num).Value = cellWithFormulaA1.FormulaA1;
    }
}
```
- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Планы.xlsx](https://github.com/ClosedXML/ClosedXML/files/1309744/default.xlsx)

**Comment by rvkstudent** [comment]
Made some test. When i Replace "=" to "=" from excel app...its all evalueting OK. It says about formula is OK, but when i insert it from my app - there is message: cell is constant ant cant be evaluated. Whats wrong?

**Comment by igitur** [comment]
I can't run your code. Where do you declare `ws` and the other variables?! I thought the issue template was very clear about the code sample requirements.

**Comment by rvkstudent** [comment]
Sorry, i thought not nessesary to declare full code. Here it is:

` if (com.Equals("ВПР", StringComparison.InvariantCultureIgnoreCase)) 
                {
                    string worksheet_name = "";
                    int worksheet_num = 0;
                    int column_num = 1;
                    int row_num = 1;
                    string column_name = "";

                    int strok_vniz = Convert.ToInt32(prm[4]);

                    string filename = prm[0];
                    files.TryGetValue(prm[0], out filename);

                    string range = prm[5];
                    ranges.TryGetValue(prm[5], out range);
                    
                    var wb1 = new XLWorkbook("c:\\XLTest\\" + filename);
                    IXLWorksheet ws;

                    if (prm[2] != "" && prm[2] != null)
                    {

                        try
                        {
                            column_num = Int32.Parse(prm[2]);

                        }
                        catch (FormatException)
                        {
                            column_name = prm[2];
                        }


                    }
                    if (prm[1] != "" && prm[1] != null)
                    {
                        try
                        {
                            worksheet_num = Int32.Parse(prm[1]);

                        }
                        catch (FormatException)
                        {
                            worksheet_name = prm[1];
                        }
                    }
                    
                    if (worksheet_name != "")
                        ws = wb1.Worksheet(worksheet_name);
                    else
                        ws = wb1.Worksheet(worksheet_num);

                    for (int i = 1; i < ws.CellsUsed().Count(); i++)
                    {
                        if (ws.Cell(i, column_num).Value.Equals("") == false)
                        {
                            row_num = i;
                            break;
                        }
                    }
                    if (strok_vniz > 0)
                    {
                        for(int i = row_num+1;i<= strok_vniz+ row_num + 1;i++ )
                        { 
                       var cellWithFormulaA1 = ws.Cell(i, column_num);
                            cellWithFormulaA1.FormulaA1 = "==ВПР(" + ws.Cell(i, column_num-1).Address.ToString() + ";" + range + ";" + prm[6]+";0)";
                           
                           ws.Cell(i, column_num).Value = cellWithFormulaA1.FormulaA1;                        
                        }

                    }
                    wb1.Save();
                    wb1.Dispose();
                }`

**Comment by igitur** [comment]
Nope. Read https://github.com/ClosedXML/ClosedXML/blob/develop/.github/ISSUE_TEMPLATE.md again.

**Comment by rvkstudent** [comment]
Here is sample code in console app with same result:

` static void Main(string[] args)
        {
                   
            int row_num = 1;
                        
            var wb1 = new XLWorkbook("c:\\XLTest\\Test.xlsx");

            IXLWorksheet ws = wb1.Worksheet(1);
            
                    row_num = 6;
               
          
           
                for (int i = row_num + 1; i <= 10; i++)
                {
                    var cellWithFormulaA1 = ws.Cell(i, 6);
                    cellWithFormulaA1.FormulaA1 = "==ВПР(" + ws.Cell(i, 1).Address.ToString() + ";" + "'c:\\XLTest\\[test2.xlsx]Лист1'!$A:$B; 2; 0)";

                    ws.Cell(i, 6).Value = cellWithFormulaA1.FormulaA1;

                }

            wb1.Save();

            wb1.Dispose();
        }
        
`
[Test.xlsx](https://github.com/ClosedXML/ClosedXML/files/1310181/Test.xlsx)
[Test2.xlsx](https://github.com/ClosedXML/ClosedXML/files/1310182/Test2.xlsx)

**Comment by igitur** [comment]
Uhm, you're explicitly setting the cell value, which of course overwrites the formula:
```c#
ws.Cell(i, 6).Value = cellWithFormulaA1.FormulaA1;
```

**Comment by rvkstudent** [comment]
if i dont do that i got a error in excel: cant read data - need to repair...

**Comment by igitur** [comment]
Then that is a separate problem. Log a new issue. This time show proper code sample to reproduce issue. Also format your code properly as is explained in https://guides.github.com/features/mastering-markdown/
