### ISSUE TITLE
Inserting formula error

### ISSUE THREAD

**Issue by rvkstudent** [ClosedXML/ClosedXML#488]
**Version of ClosedXML**
0.89
## Reproducibility
When i try to add formula to list got an excel error about damaged document and need to repair.
**Code to reproduce problem:**
```c#
public void Main()
{                     
            int row_num = 6;
                        
            var wb1 = new XLWorkbook("c:\\XLTest\\Test.xlsx");

            IXLWorksheet ws = wb1.Worksheet(1);
           
                for (int i = row_num + 1; i <= 10; i++)
                {
                    var cellWithFormulaA1 = ws.Cell(i, 6);
                    cellWithFormulaA1.FormulaA1 = "=ВПР(" + ws.Cell(i, 1).Address.ToString() + ";" + "'c:\\XLTest\\[test2.xlsx]Лист1'!$A:$B; 2; 0)";

                }

            wb1.Save();

            wb1.Dispose();
        }

```

[Test.xlsx](https://github.com/ClosedXML/ClosedXML/files/1310296/Test.xlsx)
[Test2.xlsx](https://github.com/ClosedXML/ClosedXML/files/1310295/Test2.xlsx)

**Comment by igitur** [comment]
Attach your files! Come on, dude. Read the guidelines!

**Comment by rvkstudent** [comment]
Files attached

**Comment by igitur** [comment]
Use commas to separate your formula parameters, not semicolons. Read the [wiki](https://github.com/ClosedXML/ClosedXML/wiki/Using-Formulas).

**Comment by rvkstudent** [comment]
I have read this wiki two days ), but haven't noticed commas ((...thank u, problem solved

**Comment by igitur** [comment]
Also, in the future, complete the FULL template. You deleted sections. Don't assume they are not relevant.

**Comment by rvkstudent** [comment]
OK
