### ISSUE TITLE
PivotTable Classic View Not Working

### ISSUE THREAD

**Issue by UCFKnights83** [ClosedXML/ClosedXML#489]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.89.0.0

**What is the current behavior?**

ptPivotTable.ClassicPivotTableLayout = true;  *DOES NOT WORK*

Oddly enough, the Display tab does show the option selected even though the appearance does not reflect the selection. I have to open the Excel file, deselect the classic appearance and then re-select it in order for the classic appearance to take affect.

**What is the expected behavior or new feature?**

PivotTable should revert to classic style

**Did this work in previous versions of our tool?  Which versions?**

Not sure

## Reproducibility

**Code to reproduce problem:**
```c#
public class Pastry
{
    public Pastry(string name, int amount, string month)
    {
	Month = month;
	Name = name;
	NumberOfOrders = amount;
    }

    public string Name { get; set; }
    public int NumberOfOrders { get; set; }
    public string Month { get; set; }
}

public void GeneratePivotTable()
{
    var pastries = new List<Pastry>
    {
      new Pastry("Croissant", 150, "Apr"),
      new Pastry("Croissant", 250, "May"),
      new Pastry("Croissant", 134, "June"),
      new Pastry("Doughnut", 250, "Apr"),
      new Pastry("Doughnut", 225, "May"),
      new Pastry("Doughnut", 210, "June"),
      new Pastry("Bearclaw", 134, "Apr"),
      new Pastry("Bearclaw", 184, "May"),
      new Pastry("Bearclaw", 124, "June"),
      new Pastry("Danish", 394, "Apr"),
      new Pastry("Danish", 190, "May"),
      new Pastry("Danish", 221, "June"),
      new Pastry("Scone", 135, "Apr"),
      new Pastry("Scone", 122, "May"),
      new Pastry("Scone", 243, "June")
    };

    var workbook = new XLWorkbook();
    var sheet = workbook.Worksheets.Add("PastrySalesData");
    IXLTable tTable = sheet.Cell(1, 1).InsertTable(pastries);

    var range = tTable.DataRange;
    var header = sheet.Range(1, 1, 1, 3);
    var dataRange = sheet.Range(header.FirstCell(), range.LastCell());            
    var ptSheet = workbook.Worksheets.Add("PivotTable");
    var pt = ptSheet.PivotTables.AddNew("PivotTable", ptSheet.Cell(1, 1), dataRange);
    pt.RowLabels.Add("Name");
    pt.ColumnLabels.Add("Month");
    pt.Values.Add("NumberOfOrders");

    pt.ClassicPivotTableLayout = true;

    workbook.SaveAs(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "test.xlsx"));
}
```
- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)

[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/1310707/test.xlsx)

**Comment by igitur** [comment]
Not a full code sample. Read the issue template again.

**Comment by UCFKnights83** [comment]
Sorry, updated with corrected sample code

**Comment by igitur** [comment]
You have got to be kidding me!

**Comment by igitur** [comment]
Ignore previous comment. Thought you changed the other issue's code.

**Comment by UCFKnights83** [comment]
Lol, I am unable to really put my code in due to the dynamics of the data so I am having to generate a working sample with static data. Using your example PivotTable code is the easiest way to do that   :)

**Comment by igitur** [comment]
Can't reproduce this. The resulting pivot table that I get is in classic layout.

![image](https://user-images.githubusercontent.com/145854/30654881-970a50f2-9e2f-11e7-8346-6edaa89f3ee8.png)

**Comment by igitur** [comment]
Your code is fine now, don't worry.

**Comment by igitur** [comment]
I just can't reproduce the issue.

**Comment by UCFKnights83** [comment]
It has it checked but the PivotTable is not actually displaying as Classic. Please uncheck that box, press Ok, then go back in and recheck it and press Ok. You will notice that the PivotTable updates at that point and reflects what a Classic view should actually be.

**Comment by igitur** [comment]
I still get this:
![image](https://user-images.githubusercontent.com/145854/30655026-10631ec0-9e30-11e7-8449-0ecf693011a1.png)

Paste a screenshot of what you expect it to look like.

**Comment by UCFKnights83** [comment]
That screenshot is the correct view. Notice that the Name and Month are now being displayed when previously they were not.

**Comment by igitur** [comment]
Ah ok! I'll look into it.

**Comment by igitur** [comment]
Please test with the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.566/artifacts

**Comment by igitur** [comment]
@UCFKnights83 Success?

**Comment by UCFKnights83** [comment]
Hi, sorry for the delayed response. I was out of town. Yes, it was a success! Thanks!
