### ISSUE TITLE
IndexOutOfRangeException when workbook with empty DataTable

### ISSUE THREAD

**Issue by astef** [ClosedXML/ClosedXML#493]
Bug

**Version of ClosedXML**

0.80.1-0.89.0

**What is the current behavior?**

IndexOutOfRangeException

**What is the expected behavior or new feature?**

Workbook saved to a stream

**Did this work in previous versions of our tool?  Which versions?**

Yes/v0.76.0

## Reproducibility

**Code to reproduce problem:**
```c#
static void Main(string[] args)
{
	DataTable table = new DataTable();
	table.TableName = "LookupData";
	XLWorkbook wb = new XLWorkbook();
	wb.Worksheets.Add(table).Cell(1, 1).SetValue("Hello World");
	// no exception with below line:
	//wb.Worksheets.Add("table").Cell(1, 1).SetValue("Hello World");
	using (MemoryStream memoryStream = new MemoryStream())
	{
		wb.SaveAs(memoryStream); // IndexOutOfRangeException here
	}
}
```

**Comment by igitur** [comment]
Please upgrade to the latest version of ClosedXML (v0.89) and try again.

**Comment by astef** [comment]
Please read my post again, "Version of ClosedXML". It reproduces in 0.89

**Comment by igitur** [comment]
You initially had only 0.80.1 and then edited it later. New posts generate an email (to which I responded by email), but edits don't generate an email.

![image](https://user-images.githubusercontent.com/145854/30598714-cecfe9dc-9d5a-11e7-9599-6079cb63479f.png)

**Comment by igitur** [comment]
Your data table is empty (no columns), which creates a problem with the ranges of the target table. I'll add some validation to prevent adding an empty table.

**Comment by igitur** [comment]
Can I assume that this is resolved?

**Comment by astef** [comment]
I don't know your workflow. I can still reproduce it in the latest version (since it was not updated, 0.89.0).

Sorry, I have no time to build it from sources and check, so feel free to manage it yourself.
