### ISSUE TITLE
Support for EMF Pictures

### ISSUE THREAD

**Issue by arubiomoreno** [ClosedXML/ClosedXML#503]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

**Version of ClosedXML**

0.89.0

**What is the current behavior?**

In the `ClosedXML.Excel.Drawings.XLPictures`, it is being used the `System.Drawing.Bitmap` to determine the dimensions and `XLPictureFormat `of the picture. 
This causes that `System.Drawing.Imaging.Metafile` files (which as `System.Drawing.Bitmap`, inherit from `System.Drawing.Image`) throw an exception and can not be added to the worksheet.

**What is the expected behavior or new feature?**

That this line works, when stream is an EMF stream:
`worksheet.AddPicture(stream, XLPictureFormat.Emf);`

Changing `System.Drawing.Bitmap` for `System.Drawing.Image` should do it.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**Proof that this should work**
Since I don't want to compile my own ClosedXML (because 1: I can break things, and 2: I have it all linked to NuGet), I implemented an extension method to solve this the ugly way: with Reflection
```c#
public static IXLPicture AddEmf(this IXLWorksheet worksheet, Stream stream)
{
  Metafile mf = new Metafile(stream);
  IXLPicture picture = null;

  using (Bitmap bm = new Bitmap(mf.Width, mf.Height, PixelFormat.Format32bppArgb))
  {
    using (MemoryStream pngStream = new MemoryStream())
    {
      bm.Save(pngStream, ImageFormat.Png);
      pngStream.Seek(0, SeekOrigin.Begin);

      picture = worksheet.AddPicture(pngStream, XLPictureFormat.Png);

      MemoryStream emfStream = new MemoryStream();
      MemoryStream srcStream;
      stream.Position = 0;
      stream.CopyTo(emfStream);
      emfStream.Seek(0, SeekOrigin.Begin);

      srcStream = picture.GetType().GetProperty("ImageStream").GetValue(picture) as MemoryStream;
      picture.GetType().GetProperty("ImageStream").SetValue(picture, emfStream);
      picture.GetType().GetProperty("Format").SetValue(picture, XLPictureFormat.Emf);

      srcStream.Dispose();
    }
  }

  return picture;
}
```
And it works! pretty vectorial graphics drawn with GDI+.

**Comment by igitur** [comment]
Image handling is changing significantly in the future, when we start doing a .NET Standard 2 build. See #315  for that. If you can get .emf files to work with that branch, please log a PR.

**Comment by jahav** [comment]
Closing this issue, because it's possible to add EMF picture to the workbook. I am not sure if it was possible back with `System.Common.Drawing`, but it is possible with current `IXLGraphicEngine` and there is an enum for EMF `XLPictureFormat.Emf`. There is a sample EMF file in the repo.

```csharp
using var wb = new XLWorkbook();
var ws = wb.AddWorksheet();
var picture = ws.AddPicture(@"ClosedXML\ClosedXML.Tests\Resource\Images\SampleImageEmf.emf", "Sample");
picture.MoveTo(ws.Cell("B4"));
picture.Scale(0.25);
wb.SaveAs(@"c:\Temp\Issues\0503\test.xlsx");
```
