### ISSUE TITLE
Use ClosedXML to open the xlsm file with the picture, the error message: The picture ID '27' already exists.

### ISSUE THREAD

**Issue by nathanQiu1** [ClosedXML/ClosedXML#509]
code : 
  try
 {
    var workbook = new XLWorkbook(“D:/FAI.xlsm”);//The file has a picture
 }
 catch (Exception e)
   {
           // error： The picture ID '27' already exists.

   }

When I develop the App , I faced the issue what I mentioned . who face the similar issue , plz provide one solution to me , tkx in advance .

**Comment by igitur** [comment]
Incomplete details
