### ISSUE TITLE
Full pivot table support

### ISSUE THREAD

**Issue by igitur** [ClosedXML/ClosedXML#51]

**Comment by DeveloperFarris** [comment]
Is it possible to use two fields as value fields in a closed XML pivot?

**Comment by mowmoth** [comment]
There's a lot to be desired in respect to Pivot Tables :/

* support number formats 
* support multiple row-/columnlabels in code 
* support AutoFitColumns (no effect as of right now)
* allow more customization in terms of creating the table

...

For my purposes it's sadly unusable currently as my current project relies heaviliy on using pivot tables and I will have to fall back to using OpenXML.

**Comment by DeveloperFarris** [comment]
So happy I'm able to use more than one value fields in my pivot now. 

Is there any update on the items tat Mowmoth referenced? such as Autofit, setting the layout style, etc for Pivots?

**Comment by igitur** [comment]
I'm leaving the cosmetic changes until later. If you see any functional shortcomings, please log them as separate issues. For example I'm currently working on #218 .

**Comment by jahav** [comment]
I am closing this, because it's non actionable, there are many other tickets about pivot tables with a more narrow scope that are actionable.

Full support is meaningless, it could mean things like OLAP support for pivot tables that are likely never going to happen.
