### ISSUE TITLE
Error installing NuGet package 0.89 in a .NET 4.5 project

### ISSUE THREAD

**Issue by Sicos1977** [ClosedXML/ClosedXML#512]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**
0.89

**What is the current behavior?**
Error when installing package from NuGet in a project that targets .NET 4.5 --> Could not install package 'ClosedXML 0.89.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

Complete this.

**What is the expected behavior or new feature?**
Installation

Complete this.

**Did this work in previous versions of our tool?  Which versions?**
0.88.7 works without any problems

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**
Try to install it in a .NET 4.5 project

**Comment by igitur** [comment]
Will be solved in #315, but in all honesty, why don't you upgrade to .NET 4.5.2?

**Comment by Sicos1977** [comment]
Didn't know it was solved when I use .NET 4.5.2 :-) ... and also upgrading is not that easy when you work in a very big company. Even these simple things take a lot of paper work.

**Comment by igitur** [comment]
You can of course also compile from source against the runtime of your choice.

**Comment by Sicos1977** [comment]
Yeah I know but I prefer NuGet packages. A lot easier to maintain.

**Comment by paulirwin** [comment]
@Sicos1977 Microsoft support for .NET 4.5 and 4.5.1 [ended on January 12, 2016](https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework). While multitargeting will fix the issue, if I were you, I would also encourage your employer to use a supported version of the .NET Framework as you're currently at risk for unpatched security vulnerabilities.
