### ISSUE TITLE
Issue on Excel to auto include formulas and formatting on tables for new rows after saving a file using ClosedXML

### ISSUE THREAD

**Issue by DiegoCotini** [ClosedXML/ClosedXML#513]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**

0.87.0

**What is the current behavior?**

I have an issue that is quite hard to understand, I'm going to try to explain that:

- I have a template xlsx file;
- There are some plans on this workbook and a table for each one;
- Some columns have formulas and specific formats (colors, time, currency and so one);
- If I open directly this template file and insert a new row in any table, things are going well (formulas and formats are being copied for this new row);
- However, if I use Closedxml to open it and saving then, even not manipulating anything, when I open the file and add a new row to some table this new row is coming with no formulas and formats for some cases only.

I have no idea what's going on and how to fix it but it's invalidating a requirement because I need to open the template, fill some tables and send to the user for download.

**What is the expected behavior or new feature?**

I expect that the behavior when I create a new row into a table on a xlsx file after saving it using ClosedXML would be the same as when creating on a xlsx file that before using ClosedXML.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
Very short code and template file example, if you open the attached file "Template Example.xlsx", then press TAB at last cell a new row with formatted cell on colum3 and a formula on colum5 will be created. If you open the attached file "Template Example after saving.xlsx" (or run the code and open the new file) and do the same, the new row won't have the formatted cell on colum3 or formula on colum5.  

```c#
MemoryStream ms = new MemoryStream();

var absoluteOriginalPath = "C:\\Users\\Diego\\Desktop\\Template Example.xlsx"; 
var absoluteSavingPath = "C:\\Users\\Diego\\Desktop\\Template Example after saving.xlsx"; 

using (FileStream fs = File.OpenRead(absoluteOriginalPath))
{
    fs.CopyTo(ms);

    using (var workbook = new XLWorkbook(ms))
    {   
        workbook.SaveAs(absoluteSavingPath);

        ms.Close();
    }
}
```

[Template Example.xlsx](https://github.com/ClosedXML/ClosedXML/files/1334796/Template.Example.xlsx)
[Template Example after saving.xlsx](https://github.com/ClosedXML/ClosedXML/files/1334795/Template.Example.after.saving.xlsx)

**Comment by igitur** [comment]
Post full, minimal sample code, as per issue template.

**Comment by andrecalil** [comment]
@igitur Just to let you know that the issue was updated with a full minimal repro code.

**Comment by igitur** [comment]
OK, will look into it soon.

**Comment by igitur** [comment]
Please test with the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.616/artifacts

**Comment by DiegoCotini** [comment]
@igitur thank you for helping. This new build works on that simple template file tested on a short test app. However, I can't test/use it on the main application in which we have many formats and formulas and that's motivated to open this issue because the .NET version target of this new build is v4.5.2 that is a higher version than ours application version v4.5.1.

Error: The primary reference "ClosedXML, Version=0.87.0.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.1".

**Comment by igitur** [comment]
You'll have to compile from source if you want to support NET451.

Note that Microsoft support for .NET 4.5 and 4.5.1 [ended on January 12, 2016](https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework).

**Comment by DiegoCotini** [comment]
@igitur Thanks, we are checking if we can update our version here in order to keep receiving updates from nuget. 
For meanwhile, I've updated our app here to test and I've seen those issues has been fixed but a new one is occurring now.
For cells that have a different background color, on new lines the background of them becomes black. 

I attached the template files before and after saving with this new issue.

[Template Example.xlsx](https://github.com/ClosedXML/ClosedXML/files/1357384/Template.Example.xlsx)
[Template Example after saving.xlsx](https://github.com/ClosedXML/ClosedXML/files/1357385/Template.Example.after.saving.xlsx)

**Comment by igitur** [comment]
Ok, try the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.619/artifacts

**Comment by DiegoCotini** [comment]
@igitur Thank you so much! It's fixed and working well now.
Do you know when this fix will be available for updating on nuget?

**Comment by igitur** [comment]
Unfortunately not too soon. This was a fairly big change and most of the changes for the next release are already selected.

**Comment by andrecalil** [comment]
Just so we understand: by _not too soon_ do you mean "a couple weeks" or more likely "a couple days"?
No pressure at all, just so we can plan accordingly.

**Comment by igitur** [comment]
At least a month.

**Comment by andrecalil** [comment]
Ok, thank you.

**Comment by vbjay** [comment]
FYI. If changing framework versions, run

update-package -reinstall
