### ISSUE TITLE
ClosedXML not working on IIS

### ISSUE THREAD

**Issue by zulu15** [ClosedXML/ClosedXML#515]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

  0.89

**What is the current behavior?**

My project is working fine locally but it crashes on production running IIS.

**What is the expected behavior or new feature?**

Complete this.

I dont know
Yes/No/v0.XX

## Reproducibility
 DataTable eneAct = (DataTable)Cache["eneAct"];
        DataTable mPot = (DataTable)Cache["maxPot"];

        IXLWorksheet ws;

        using (XLWorkbook wb = new XLWorkbook())
        {
            ws = wb.Worksheets.Add("test");
            wb.Worksheet(1).Cell(1, 1).Value = "DETALLE DE LOS VALORES DE DEMANDA MÁXIMA DE CECSAGAL";
            ws.Cell(1, 1).Style.Font.FontSize = 11;
            ws.Cell(1, 1).Style.Font.FontName = "Calibri";

            wb.Worksheet(1).Cell(2, 1).InsertTable(mPot).ShowAutoFilter = false;
            wb.Worksheet(1).Cell(2, 11).Value = " ";

 

            wb.Worksheet(1).Cell(8, 1).Value = "DETALLE DE LOS VALORES DE ENERGÍA ACTIVA DE CECSAGAL";
            ws.Cell(8, 1).Style.Font.FontSize = 11;
            ws.Cell(8, 1).Style.Font.FontName = "Calibri";

            wb.Worksheet(1).Cell(9, 1).InsertTable(eneAct).ShowAutoFilter = false;

            wb.Worksheet(1).Columns(2, 15).AdjustToContents();
            wb.Worksheet(1).Column(1).Width = 16;

            Response.Clear();
            Response.Buffer = true;
            Response.Charset = "";
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", "attachment;filename= test.xlsx");

            using (MemoryStream MyMemoryStream = new MemoryStream())
            {
                try
                {
                    wb.SaveAs(MyMemoryStream);
                    MyMemoryStream.WriteTo(Response.OutputStream);
                    Response.Flush();
                    Response.End();
                }
                catch (Exception)
                {

                }

            }
        }
```c#


- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
I assume you got it working, but in any case, you might be interested in the helper extension methods at https://github.com/ClosedXML/ClosedXML.Extensions.AspNet
