### ISSUE TITLE
Possible Null Reference Issues

### ISSUE THREAD

**Issue by channeloriginteam** [ClosedXML/ClosedXML#516]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.87.1

**What is the current behavior?**

In files XLFilterColumn.cs, XLFill.cs, XLBorder.CS, XLDataValidation.cs, XLCellsCollection.cs, XLAutoFiller.cs, Tally.cs, Lookup.cs, MathTrig.cs, and CalcEngine.cs, there are possible null reference issues. For example, in XLFilterColumn.cs, The method ShowAverage() in XLFilterColumn.cs can dereference a null pointer on line 266, thereby raising a NullException. 

**What is the expected behavior or new feature?**

No null reference issues

**Did this work in previous versions of our tool?  Which versions?**

No

**Comment by igitur** [comment]
Code to reproduce?

**Comment by igitur** [comment]
And I don't really understand this issue. Did you actually experience null reference exceptions? Or are you merely highlighting places where this could, in theory, occur?
