### ISSUE TITLE
Sheet default alignment overrides cell specific alignment when opening file

### ISSUE THREAD

**Issue by needsmatch** [ClosedXML/ClosedXML#517]
- [x] Bug

**Version of ClosedXML**
v.0.89.0

**What is the current behavior?**

When opening a sheet with a cell having a specific vertical alignment that is different than the alignment set for the rest of the sheet, ClosedXML is ignoring the specific alignment setting of the cell.

**What is the expected behavior or new feature?**

Alignment should be honored as found in the source document.

**Did this work in previous versions of our tool?  Which versions?**

I'm not sure

## Reproducibility

The attached file was created by:

- Select entire worksheet
- Set Vertical Alignment to 'Center'
- Enter Data into A1
- Select A1 cell and set Vertical Alignment to 'Bottom;
- Save workbook
- Open workbook in code using the following:

```
XLWorkbook workbook = new XLWorkbook(outputFileLocation);
IXLWorksheet dataSheet = workbook.Worksheet(1);
IXLCell testCell = dataSheet.Cell("A1");
Console.WriteLine(testCell.Style.Alignment.Vertical.ToString());
```

- Inspection of Vertical alignment on A1 now reads **Center** where it should read **Bottom**
- Saving the file will persist this change in alignment.  
- I'm seeing this issue also for Horizontal Alignment but have not experimented with other style options.

[example.xlsx](https://github.com/ClosedXML/ClosedXML/files/1338721/example.xlsx)

**Comment by igitur** [comment]
Read the issue template again.
