### ISSUE TITLE
Implement all Excel functions

### ISSUE THREAD

**Issue by igitur** [ClosedXML/ClosedXML#52]

**Comment by pichardoSoftware** [comment]
Any way I can help you with this?

**Comment by igitur** [comment]
Definitely. We appreciate any help we can get. 

If you want to ease in, you can start with some of the simpler functions. I think the Logical and Information groups of functions in Excel would be the easiest to implement.
![image](https://cloud.githubusercontent.com/assets/145854/19437042/ce9b35e8-9473-11e6-9ffc-d65e01c99599.png)

There is already a `Logical` class, which you can start extending. The `Is` class should probably be renamed to `Information` and extended. You're also welcome to try any of the other functions. Please group them according to the grouping that Excel uses. Let me know if you need additional info.

**Comment by pichardoSoftware** [comment]
Excellent

**Comment by igitur** [comment]
To implement something like `ISERR()`, we'll have to implement ClosedXML-specific exceptions which can be caught in the `ISERR` implementation. I'm almost done with those exceptions. You can have a look at https://github.com/igitur/ClosedXML/tree/improve-calcengine-exceptions if you're interested.

**Comment by pichardoSoftware** [comment]
Ok, I will start extending that class and check the exceptions.

**Comment by pichardoSoftware** [comment]
I've 2 questions:
-----
 - How should I manage errors, like #value, #error, etc?
  - It doesn't seem logical to implement functions like `IsErr()` and `IsError()` on a programmatically generated spreadsheet, Maybe on parsing an existing sheet.
 - There are some functions on the Information section that accept various or one argument, and some that only accept one, so do you think is a good idea to keep using `List<Expression>` or should we use variable parameters `params Expression[]`.

What do you think about this?

**Comment by pichardoSoftware** [comment]
How are you doing with the exceptions?

**Comment by igitur** [comment]
Sorry. Busy week. I'll try to get round to it.

**Comment by pichardoSoftware** [comment]
I understan @igitur, I'll continue with other classes then, Greetings

**Comment by jahav** [comment]
I am closing this issue since it is not reasonable ticket. It's something like "learn English" instead of "Learn conjugation of 5 irregular verbs". 

At the moment, we have [a table](https://closedxml.readthedocs.io/en/latest/features/functions.html ) of all functions and state of implementation and if dev feels like implementing one, the rest will be done per reported issues.

Easy pickings are done, a significant portion of functions are not sufficiently compliant with Excel, need verification (by fuzzer hopefully) against Excel.
