### ISSUE TITLE
Column number must be between 1 and 16384 error when loading a file

### ISSUE THREAD

**Issue by steen16** [ClosedXML/ClosedXML#522]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.89.0

**What is the current behavior?**
I am trying to process an Excel file from the ​​EIOPA's website (https://eiopa.europa.eu/).
I have attached the file. It also can be obtained from this page - https://eiopa.europa.eu/regulation-supervision/insurance/solvency-ii-technical-information/risk-free-interest-rate-term-structures 
Direct link to the ZIP file containing the Excel sheet - https://eiopa.europa.eu/Publications/Standards/EIOPA_RFR_20170831.zip
File name - EIOPA_RFR_20170831_VA_portfolios.xlsx

<img width="649" alt="error" src="https://user-images.githubusercontent.com/5644259/31090581-f9c57072-a79f-11e7-95df-0eb32deec0ab.png">

**What is the expected behavior or new feature?**

Load the file.

**Did this work in previous versions of our tool?  Which versions?**

N/A

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
var workbook = new XLWorkbook(@"EIOPA_RFR_20170831_VA_portfolios.xlsx");
}

```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
(https://github.com/ClosedXML/ClosedXML/files/1349749/EIOPA_RFR_20170831_VA_portfolios.xlsx)

**Comment by steen16** [comment]
This is interesting... 

https://books.google.co.uk/books?id=HsxPboAY5YMC&pg=RA2-PA5&lpg=RA2-PA5&dq=16,385+columns+excel&source=bl&ots=JPlsvcFHi_&sig=DNfivMvC9msdxAWmHniKcli8vkY&hl=en&sa=X&ved=0ahUKEwjapLXIwNLWAhWMHxoKHYh1CGoQ6AEIKzAB#v=onepage&q=16%2C385%20columns%20excel&f=false

If I compile from source and set the limit to 16385 it works. Bug in office? Incorrect documentation from MSFT?

**Comment by igitur** [comment]
It's the image on the first sheet that's a bit weird. I pushed a fix for it. Note that the image is cropped, which isn't supported in ClosedXML yet. So if save the file, the resulting image looks totally different. In my opinion, creator of the spreadsheet should have done a better job. 

PS, are you a quant?

**Comment by steen16** [comment]
Wow, that was quick. Thanks! The spreadsheet loads correctly now.
Luckily, I am just loading data, not manipulating spreadsheets.

Not a quant... just been working financial software lately. 
Having a math background helps though 😄 

p.s. what is the release schedule for the NuGet package?

**Comment by igitur** [comment]
I don't commit to any schedules. 

I sometimes work on https://github.com/amaggiulli/QLNettoo, that's why I asked.

**Comment by steen16** [comment]
Compile from source it is then...
Nice... we are using some bits and pieces from that lib also.
