### ISSUE TITLE
Feature :: Please add function INT in formulas

### ISSUE THREAD

**Issue by victorklimkovich** [ClosedXML/ClosedXML#529]
Feature :: Please add function INT in formulas

**Comment by victorklimkovich** [comment]
Sorry. There is already in library

**Comment by igitur** [comment]
So this can be closed?

**Comment by Duikmeester** [comment]
All those commented out lines with ce.RegisterFunction means they are yet to be implemented?

**Comment by igitur** [comment]
@Duikmeester Yes, that's the case. For the all the stats functions, I'm evaluating using https://github.com/mathnet/mathnet-numerics - but I have to see whether they have a netstandard build yet.

**Comment by igitur** [comment]
Closing as invalid as `INT` has been implemented.

**Comment by igitur** [comment]
@Duikmeester Of course you're welcome to send PRs for the remaining functions. I guess some of them won't be too difficult. Just keep in mind that some parameters are optional and that appropriate exceptions should (where applicable) be thrown to imitate Excel.
