### ISSUE TITLE
Is PROCV implemented?

### ISSUE THREAD

**Issue by alceucardoso** [ClosedXML/ClosedXML#536]
[] Bug
[x ] Feature

Version of ClosedXML: 0.89.0

I'm trying to use PROCV in a worksheet but always get error on open file.

Is this function already implemented?

Code C#:

using ClosedXML.Excel;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace GerarXls
{
    class Program
    {
        #region Constants/Variables

        private const int PRODUCT_HEADER_ROW = 1;
        private const int PRODUCT_FIRST_ROW = PRODUCT_HEADER_ROW + 1;
        private const int PRODUCT_LAST_ROW = PRODUCT_FIRST_ROW + 1000;

        private const int PRODUCT_PRODUCTTYPE_ID_COL = 10;
        private const int PRODUCT_PRODUCTGROUP_ID_COL = PRODUCT_PRODUCTTYPE_ID_COL + 1;
        private const int PRODUCT_UNITOFMEASURE_ID_COL = PRODUCT_PRODUCTGROUP_ID_COL + 1;

        private const int PRODUCT_PRODUCTTYPE_COL = 1;
        private const int PRODUCT_NAME_COL = 2;
        private const int PRODUCT_REFERENCE_COL = 3;
        private const int PRODUCT_PRODUCTGROUP_COL = 4;
        private const int PRODUCT_UNITOFMEASURE_COL = 5;
        private const int PRODUCT_COST_PRICE = 6;
        private const int PRODUCT_SALEPRICE_COL = 7;
        private const int PRODUCT_NETWEIGHT_COL = 8;
        private const int PRODUCT_GROSSWEIGHT_COL = 9;

        private const int EXTRA_FIRST_ROW = 1;

        private const int EXTRA_PRODUCTTYPE_REF_COL = 1;
        private static int EXTRA_PRODUCTTYPE_LAST_ROW = 1;
        private const int EXTRA_PRODUCTGROUP_REF_COL = EXTRA_PRODUCTTYPE_REF_COL + 2;
        private static int EXTRA_PRODUCTGROUP_LAST_ROW = 1;
        private const int EXTRA_UNITOFMEASURE_REF_COL = EXTRA_PRODUCTGROUP_REF_COL + 2;
        private static int EXTRA_UNITOFMEASURE_LAST_ROW = 1;

        #endregion

        static void Main(string[] args)
        {
            var workbook = new XLWorkbook();
            var productWorksheet = workbook.Worksheets.Add("Produtos");
            var extraWorksheet = CreateExtraData(workbook);

            CreateHeader(productWorksheet);
            CreateListValidations(productWorksheet, extraWorksheet);
            CreateListValueColumns(productWorksheet, extraWorksheet);
            FormatProductWorksheet(productWorksheet);

            workbook.SaveAs("Products.xlsx");
        }

        #region Product Worksheet

        private static void CreateHeader(IXLWorksheet worksheet)
        {
            worksheet.Cell(PRODUCT_HEADER_ROW, PRODUCT_PRODUCTTYPE_COL).Value = "Tipo";
            worksheet.Cell(PRODUCT_HEADER_ROW, PRODUCT_NAME_COL).Value = "Nome";
            worksheet.Cell(PRODUCT_HEADER_ROW, PRODUCT_REFERENCE_COL).Value = "Código";
            worksheet.Cell(PRODUCT_HEADER_ROW, PRODUCT_PRODUCTGROUP_COL).Value = "Grupo";
            worksheet.Cell(PRODUCT_HEADER_ROW, PRODUCT_UNITOFMEASURE_COL).Value = "Unidade";
            worksheet.Cell(PRODUCT_HEADER_ROW, PRODUCT_COST_PRICE).Value = "Preço de Custo";
            worksheet.Cell(PRODUCT_HEADER_ROW, PRODUCT_SALEPRICE_COL).Value = "Preço de Venda";
            worksheet.Cell(PRODUCT_HEADER_ROW, PRODUCT_NETWEIGHT_COL).Value = "Peso Líquido";
            worksheet.Cell(PRODUCT_HEADER_ROW, PRODUCT_GROSSWEIGHT_COL).Value = "Peso Bruto";
        }

        private static void FormatProductWorksheet(IXLWorksheet worksheet)
        {
            // Width
            worksheet.Column(PRODUCT_PRODUCTTYPE_COL).Width = 15;
            worksheet.Column(PRODUCT_NAME_COL).Width = 60;
            worksheet.Column(PRODUCT_REFERENCE_COL).Width = 20;
            worksheet.Column(PRODUCT_PRODUCTGROUP_COL).Width = 25;
            worksheet.Column(PRODUCT_UNITOFMEASURE_COL).Width = 25;
            worksheet.Column(PRODUCT_COST_PRICE).Width = 20;
            worksheet.Column(PRODUCT_SALEPRICE_COL).Width = 20;
            worksheet.Column(PRODUCT_NETWEIGHT_COL).Width = 20;
            worksheet.Column(PRODUCT_GROSSWEIGHT_COL).Width = 20;

            // BackgroundColor
            worksheet.Range(PRODUCT_HEADER_ROW, PRODUCT_PRODUCTTYPE_COL, PRODUCT_HEADER_ROW, PRODUCT_GROSSWEIGHT_COL).Style.Fill.BackgroundColor = XLColor.FromArgb(30, 144, 255);

            // FontColor
            worksheet.Range(PRODUCT_HEADER_ROW, PRODUCT_PRODUCTTYPE_COL, PRODUCT_HEADER_ROW, PRODUCT_GROSSWEIGHT_COL).Style.Font.FontColor = XLColor.FromArgb(255, 255, 255);

            // SetBold
            worksheet.Range(PRODUCT_HEADER_ROW, PRODUCT_PRODUCTTYPE_COL, PRODUCT_HEADER_ROW, PRODUCT_GROSSWEIGHT_COL).Style.Font.SetBold(true);

            // Alignment
            worksheet.Range(PRODUCT_HEADER_ROW, PRODUCT_COST_PRICE, PRODUCT_LAST_ROW, PRODUCT_COST_PRICE).Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Right);
            worksheet.Range(PRODUCT_HEADER_ROW, PRODUCT_SALEPRICE_COL, PRODUCT_LAST_ROW, PRODUCT_SALEPRICE_COL).Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Right);
            worksheet.Range(PRODUCT_HEADER_ROW, PRODUCT_NETWEIGHT_COL, PRODUCT_LAST_ROW, PRODUCT_NETWEIGHT_COL).Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Right);
            worksheet.Range(PRODUCT_HEADER_ROW, PRODUCT_GROSSWEIGHT_COL, PRODUCT_LAST_ROW, PRODUCT_GROSSWEIGHT_COL).Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Right);

            // NumberFormat
            worksheet.Range(PRODUCT_FIRST_ROW, PRODUCT_COST_PRICE, PRODUCT_LAST_ROW, PRODUCT_COST_PRICE).Style.NumberFormat.Format = "###,###,###,###,#0.00";
            worksheet.Range(PRODUCT_FIRST_ROW, PRODUCT_SALEPRICE_COL, PRODUCT_LAST_ROW, PRODUCT_SALEPRICE_COL).Style.NumberFormat.Format = "###,###,###,###,#0.00";
            worksheet.Range(PRODUCT_FIRST_ROW, PRODUCT_NETWEIGHT_COL, PRODUCT_LAST_ROW, PRODUCT_NETWEIGHT_COL).Style.NumberFormat.Format = "###,###,###,###,#0.000";
            worksheet.Range(PRODUCT_FIRST_ROW, PRODUCT_GROSSWEIGHT_COL, PRODUCT_LAST_ROW, PRODUCT_GROSSWEIGHT_COL).Style.NumberFormat.Format = "###,###,###,###,#0.000";
        }

        private static void CreateListValueColumns(IXLWorksheet productWorksheet, IXLWorksheet extraWorksheet)
        {
            var productTypeRange = productWorksheet.Range(
                PRODUCT_FIRST_ROW,
                PRODUCT_PRODUCTTYPE_ID_COL,
                PRODUCT_LAST_ROW,
                PRODUCT_PRODUCTTYPE_ID_COL
            );

            var formulaR1C1 = string.Format("=PROCV( RC[-{0}] ; {5}!R{1}C{2}:R{3}C{4} ; 2 ; 0 )",
                PRODUCT_PRODUCTTYPE_ID_COL - PRODUCT_PRODUCTTYPE_COL,
                EXTRA_FIRST_ROW,
                EXTRA_PRODUCTTYPE_REF_COL,
                EXTRA_PRODUCTTYPE_LAST_ROW,
                EXTRA_PRODUCTTYPE_REF_COL + 1,
                extraWorksheet.Name);

            productTypeRange.FormulaR1C1 = formulaR1C1;
        }

        #endregion

        #region ExtraData Worksheet

        private static IXLWorksheet CreateExtraData(XLWorkbook workbook)
        {
            var extraWorksheet = workbook.AddWorksheet("Extra");
            //extraWorksheet.Visibility = XLWorksheetVisibility.VeryHidden;

            CreateProductTypeList(extraWorksheet);
            CreateProductGroupList(extraWorksheet);
            CreateUnitOfMeasureList(extraWorksheet);

            return extraWorksheet;
        }

        private static void CreateProductTypeList(IXLWorksheet extraWorksheet)
        {
            var row = EXTRA_FIRST_ROW;

            foreach (var type in Enum.GetValues(typeof(ProductType)))
            {
                extraWorksheet.Cell(row, EXTRA_PRODUCTTYPE_REF_COL + 0).Value = type.ToString();
                extraWorksheet.Cell(row, EXTRA_PRODUCTTYPE_REF_COL + 1).Value = (int)type;
                row++;
            }

            EXTRA_PRODUCTTYPE_LAST_ROW = row - 1;
        }

        private static void CreateProductGroupList(IXLWorksheet extraWorksheet)
        {
            var productsGroups = ProductGroup.GetData();
            var row = EXTRA_FIRST_ROW;

            foreach (var group in productsGroups)
            {
                extraWorksheet.Cell(row, EXTRA_PRODUCTGROUP_REF_COL + 0).Value = group.Description;
                extraWorksheet.Cell(row, EXTRA_PRODUCTGROUP_REF_COL + 1).Value = group.Id;
                row++;
            }

            EXTRA_PRODUCTGROUP_LAST_ROW = row - 1;
        }

        private static void CreateUnitOfMeasureList(IXLWorksheet extraWorksheet)
        {
            var unitsOfMeasure = UnitOfMeasure.GetData();
            var row = EXTRA_FIRST_ROW;

            foreach (var unit in unitsOfMeasure)
            {
                extraWorksheet.Cell(row, EXTRA_UNITOFMEASURE_REF_COL + 0).Value = unit.Description;
                extraWorksheet.Cell(row, EXTRA_UNITOFMEASURE_REF_COL + 1).Value = unit.Id;
                row++;
            }

            EXTRA_UNITOFMEASURE_LAST_ROW = row - 1;
        }

        #endregion

        #region Validations

        private static void CreateListValidations(IXLWorksheet productWorksheet, IXLWorksheet extraWorksheet)
        {
            CreateProductTypeListValidation(productWorksheet, extraWorksheet);
            CreateProductGroupListValidation(productWorksheet, extraWorksheet);
            CreateUnitOfMeasureListValidation(productWorksheet, extraWorksheet);
        }

        private static void CreateProductTypeListValidation(IXLWorksheet productWorksheet, IXLWorksheet extraWorksheet)
        {
            var productTypeDataValidation = productWorksheet.Range(
                PRODUCT_FIRST_ROW,
                PRODUCT_PRODUCTTYPE_COL,
                PRODUCT_LAST_ROW,
                PRODUCT_PRODUCTTYPE_COL
            ).SetDataValidation();

            productTypeDataValidation.List(
                extraWorksheet.Range(
                    EXTRA_FIRST_ROW,
                    EXTRA_PRODUCTTYPE_REF_COL,
                    EXTRA_PRODUCTTYPE_LAST_ROW,
                    EXTRA_PRODUCTTYPE_REF_COL
                )
            );
        }

        private static void CreateProductGroupListValidation(IXLWorksheet productWorksheet, IXLWorksheet extraWorksheet)
        {
            var productGroupDataValidation = productWorksheet.Range(
                PRODUCT_FIRST_ROW,
                PRODUCT_PRODUCTGROUP_COL,
                PRODUCT_LAST_ROW,
                PRODUCT_PRODUCTGROUP_COL
            ).SetDataValidation();

            productGroupDataValidation.List(
                extraWorksheet.Range(
                    EXTRA_FIRST_ROW,
                    EXTRA_PRODUCTGROUP_REF_COL,
                    EXTRA_PRODUCTGROUP_LAST_ROW,
                    EXTRA_PRODUCTGROUP_REF_COL
                )
            );
        }

        private static void CreateUnitOfMeasureListValidation(IXLWorksheet productWorksheet, IXLWorksheet extraWorksheet)
        {
            var untiOfMeasureDataValidation = productWorksheet.Range(
                PRODUCT_FIRST_ROW,
                PRODUCT_UNITOFMEASURE_COL,
                PRODUCT_LAST_ROW,
                PRODUCT_UNITOFMEASURE_COL
            ).SetDataValidation();

            untiOfMeasureDataValidation.List(
                extraWorksheet.Range(
                    EXTRA_FIRST_ROW,
                    EXTRA_UNITOFMEASURE_REF_COL,
                    EXTRA_UNITOFMEASURE_LAST_ROW,
                    EXTRA_UNITOFMEASURE_REF_COL
                )
            );
        }

        #endregion
    }

    public class ProductGroup
    {
        public long Id { get; set; }
        public string Description { get; set; }

        public static List<ProductGroup> GetData()
        {
            var productsGroups = new List<ProductGroup>();

            productsGroups.Add(new ProductGroup() { Id = 1, Description = "Cabos" });
            productsGroups.Add(new ProductGroup() { Id = 2, Description = "Smartphones" });
            productsGroups.Add(new ProductGroup() { Id = 3, Description = "Notebooks" });
            productsGroups.Add(new ProductGroup() { Id = 4, Description = "Periféricos" });

            return productsGroups;
        }
    }

    public class UnitOfMeasure
    {
        public long Id { get; set; }
        public string Description { get; set; }

        public static List<UnitOfMeasure> GetData()
        {
            var unitsOfMeasure = new List<UnitOfMeasure>();

            unitsOfMeasure.Add(new UnitOfMeasure() { Id = 1, Description = "Unidade" });
            unitsOfMeasure.Add(new UnitOfMeasure() { Id = 2, Description = "Kilograma" });
            unitsOfMeasure.Add(new UnitOfMeasure() { Id = 3, Description = "Litro" });
            unitsOfMeasure.Add(new UnitOfMeasure() { Id = 4, Description = "Metro" });

            return unitsOfMeasure;
        }
    }

    public enum ProductType
    {
        Material = 0,
        Service = 1
    }
}

**Comment by igitur** [comment]
No, you have to use `VLOOKUP` - I think that's the English equivalent.
