### ISSUE TITLE
Running into issues with merge not working

### ISSUE THREAD

**Issue by ravensorb** [ClosedXML/ClosedXML#537]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**

0.90.0-beta2

**What is the current behavior?**

```
XLWorkbood workbook = new XLWorkbood();
IXLworksheet worksheet;
var worksheetName = args.Suite;

if (!workbook.Worksheets.TryGetWorksheet(worksheetName, out var worksheet))
{
   worksheet = workbook.Addworksheet(worksheetName);
}

var upperBound = 2;
var lowerBound = 10;
var range = worksheet.Range($"b{lowerBound}", $"b{upperBound}");
range.Cell(1, 1).Value = args.Case.Title;
range.Cell(1, 1).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.CenterContinuous;
range.Cell(1, 1).Style.Alignment.Vertical = XLAlignmentVerticalValues.Top;
range.Cell(1, 1).Style.Alignment.WrapText = true;
range.Merge();
```

The code above is not outputting a merged cell for "B2:B10".  At least from looking at the Wiki I think I have the code correct.

**What is the expected behavior or new feature?**

cell range "B2:B10" should be merged in the output xlsx file

**Did this work in previous versions of our tool?  Which versions?**

Not sure -- never used it with a previous version

## Reproducibility
See code above

**Comment by igitur** [comment]
Insufficient code sample. Read the template.

**Comment by ravensorb** [comment]
There really wasn't much ease -- I added the code to show creating a default workbook and handling adding a blank worksheet

**Comment by ravensorb** [comment]
I'll close this until I get a chance to create a console app

**Comment by igitur** [comment]
The code is fine now. It's important that I could see how you instantiate the class.

**Comment by igitur** [comment]
Your upper and lower bound should be the other way around.
`ws.Range("B10:B2")` isn't valid. `ws.Range("B2:B10")` is correct.

**Comment by ravensorb** [comment]
Had a feeling it was something simple.  I am moving something over from VSTO Excel COM based code and it accepts the range in either order.

Thanks!
