### ISSUE TITLE
Wrong bar proportions in DataBar

### ISSUE THREAD

**Issue by abeketov** [ClosedXML/ClosedXML#54]
[Official example](http://closedxml.codeplex.com/wikipage?title=Conditional%20Formatting&referringTitle=Documentation) (4th example).
Replacing **.LowestValue()** to **.Minimum(XLCFContentType.Number, 0)** not help.
If in saved .xlsx add to section <x14:dataBar **minLength="0" maxLength="100"**...
 by hand - all fine.

**Comment by igitur** [comment]
# Do you agree with this?
## Wrong:
![image](https://user-images.githubusercontent.com/145854/30656898-e85d071e-9e35-11e7-9d7a-1e436386269e.png)


## Correct:
![image](https://user-images.githubusercontent.com/145854/30656873-d79d13b0-9e35-11e7-8a46-e2c3ddd54efa.png)
