### ISSUE TITLE
.NET Standard 2.0 Performance 

### ISSUE THREAD

**Issue by rmontroy** [ClosedXML/ClosedXML#540]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- Bug

**Version of ClosedXML**
v0.90.0-beta2

**What is the current behavior?**
~~System.TypeLoadException occurred
  HResult=0x80131522
  Message=Could not load type 'System.Drawing.ColorTranslator' from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at ClosedXML.Excel.XLColor.FromHtml(String htmlColor)~~
Performance regression in XLCell.TryGetValue<>.

**What is the expected behavior or new feature?**
~~I don't believe all of System.Drawing is available in .netstandard20:
https://github.com/dotnet/corefx/issues/20325~~
Performance comparable to .NET Framework runtime.

**Did this work in previous versions of our tool?  Which versions?**
~~NA~~
No performance issue on .NET Framework.

## Reproducibility

Target framework: .NET Core 2.0

**Code to reproduce problem:**
~~var wb = new XLWorkbook(filePath);~~
See zip file in comment below.

**Comment by rmontroy** [comment]
Also seeing this warning with the 0.90.0-beta2 NuGet published package:
warning NU1701: Package 'ClosedXML 0.90.0-beta2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by igitur** [comment]
`0.90.0-beta2` is not supposed to be `netcore2.0` compatible, so the exception isn't surprising. What gave the impression that it's compatible?

Follow #101 the progress on `netstandard2.0`.

**Comment by rmontroy** [comment]
My mistake. I've been following the progress of #101 and it's been a little confusing. It was assigned to the v0.90 milestone at one point, and recent comments suggested a pre-release package to encourage testing. I thought this version was that pre-release.

FWIW, I'm trying the .netstandard2.0 DLL that you put on AppVeyor, and it appears to be working with my app thus far, although the performance is much slower.

**Comment by igitur** [comment]
You can look at https://github.com/ClosedXML/ClosedXML/pull/535 too. It's the same build but with a different pattern for handling events. Maybe that improves performance for your use case.

**Comment by rmontroy** [comment]
No, I'm not changing anything in the spreadsheet. It's spending most of it's time in XLCell.TryGetValue(). I haven't looked into whether it's something that's different on the develop branch, or it's something different in the runtime itself (like exception handling).

**Comment by igitur** [comment]
`XLCell.TryGetValue()` isn't used by `ClosedXML` itself (excluding the unit tests). So it must be your code that is calling it. Would still like a code sample to see whether I can improve anything inside `ClosedXML`.

**Comment by rmontroy** [comment]
[TryGetValue.zip](https://github.com/ClosedXML/ClosedXML/files/1379752/TryGetValue.zip)

Thanks for your patience.
The .NET Framework build of v0.90.0-beta2 doesn't have this performance issue.

**Comment by igitur** [comment]
The build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.630/artifacts seems to be the last build that was still performing well. Do you agree?

**Comment by rmontroy** [comment]
Agreed. That build is much faster.

**Comment by igitur** [comment]
Then it's the WeakEvent pattern that I introduced that causes the
performance hit. That's sad, because it's supposed to help with the memory
bloat. Not sure how I'm going to balance these 2.

**Comment by vbjay** [comment]
My 2 cents. I'd prefer accuracy and memory usage over speed. I understand
it needs to do work. I expect it to work hard.

**Comment by igitur** [comment]
@vbjay I agree, but a 12-fold decrease in performance isn't acceptable either.

**Comment by rmontroy** [comment]
Yeah, it seems to be a pretty severe hit. It was rather painful to wait for it to get through a decently sized spreadsheet. This isn't some micro-optimization.

**Comment by igitur** [comment]
This should be fixed in latest beta version.

**Comment by rmontroy** [comment]
Confirmed. No performance issues on 0.93.0-beta2. This is the first time I've been able to run my project on .NET Core. Thank you!
