### ISSUE TITLE
INDEX and MATCH functions not supported

### ISSUE THREAD

**Issue by GrumpyTroll64** [ClosedXML/ClosedXML#542]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [X] Feature

**Version of ClosedXML**

0.89.0-beta1 (Product version)
0.89.0.0 (File version)

**What is the current behavior?**
the following line of code is attempting to access a cell that contains a formula and results in an exception being thrown:
    centry.LastComplianceDateURL = lcdcell.GetValue<string>();

The formula is as follows:
=INDEX('\\wexfile\general\NEXT_Accessibility\[WDGScorecardPrototype_DataSheet.xlsx]WDG Product Detail'!$Y:$Y,MATCH(A4&C4,'\\wexfile\general\NEXT_Accessibility\[WDGScorecardPrototype_DataSheet.xlsx]WDG Product Detail'!$AD:$AD,0))

It appears that neither INDEX nor MATCH are supported at this time. 

**What is the expected behavior or new feature?**

I'm just trying to retrieve the displayed value of the cell (which is a URL), but with the unsupported formulas, ClosedXML throws an exception.

**Did this work in previous versions of our tool?  Which versions?**

No.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

The code, as noted above, was very simple, just trying to read the string value displayed in a cell that's calculated via formula from another spreadsheet. However, the information contained in both spreadsheets is company confidential, so I can't provide them. Hopefully, because it's a case of support for Not Yet Implemented formulas, that's not as necessary.

**Code to reproduce problem:**

```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
References to external workbooks are not supported yet.

**Comment by GrumpyTroll64** [comment]
so, if INDEX and MATCH were referencing other cells within the same workbook, would that work correctly? We do have some flexibility and could potentially ask the vendor providing the documents to merge them into a single Excel workbook.

**Comment by igitur** [comment]
I see in https://github.com/ClosedXML/ClosedXML/blob/develop/ClosedXML/Excel/CalcEngine/Functions/Lookups those functions aren't implemented yet. I welcome PRs. The MATCH function should be easy. INDEX has 2 versions, so that might be more tricky. Give it a go.

**Comment by igitur** [comment]
Have a look at https://github.com/ClosedXML/ClosedXML/pull/543 for an example of how to implement function. It should throw appropriate exception when the parameters are incorrect. And a unit test has to be included.
