### ISSUE TITLE
Regular expressions in formula conditions are not parsed correct

### ISSUE THREAD

**Issue by jongleur1983** [ClosedXML/ClosedXML#548]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
current develop branch

**What is the current behavior?**
When writing Unit tests for SumIf I tried to cover the examples from the Microsoft Excel documentation.
There the following formulas are given:

```
SUMIF(A2:A7, "Fruits", C2:C7)
SUMIF(A2:A7, "Vegetables", C2:C7)
SUMIF(A2:A7, "*es", C2:C7)
SUMIF(A2:A7, "", C2:C7)
```

The first argument in refers to a cell range containing string values, the second parameter is the condition, the third argument refers to the cell range containing numbers to sum up.

While the first two examples work as expected, the other two fail:

- [ ] `*es` as a condition parameter should be handled as kind of a regex, where * is a placeholder
- [ ] `""` (the empty string) should match all rows where the content is empty.
- [ ] `~*`should match the literal asterisk (`*`)
- [ ] `~?` should match the literal `?`
- [ ] `~~` should match the literal `~`

**What is the expected behavior or new feature?**
According to the Excel documentation at https://support.office.com/en-US/article/SUMIF-function-169B8C99-C05C-4483-A712-1697A653039B there are three special characters:

> You can use the wildcard characters—the question mark (?) and asterisk (*)—as the criteria argument. A question mark matches any single character; an asterisk matches any sequence of characters. If you want to find an actual question mark or asterisk, type a tilde (~) preceding the character.

For the two failing test cases above this means:
- *es should match any string that ends with the two characters `es`.
- the empty string should match any empty cell.

## Reproducibility

**Code to reproduce problem:**
```c#
/// <summary>
/// refers to Example 2 from the Excel documentation,
/// <see cref="https://support.office.com/en-us/article/SUMIF-function-169b8c99-c05c-4483-a712-1697a653039b?ui=en-US&rs=en-US&ad=US"/>
/// </summary>
/// <param name="expectedOutcome"></param>
/// <param name="formula"></param>
[TestCase( 2000, "SUMIF(A2:A7,\"Fruits\", C2:C7)")]
[TestCase(12000, "SUMIF(A2:A7,\"Vegetables\", C2:C7)")]
[TestCase( 4300, "SUMIF(A2:A7, \"*es\", C2:C7)")]
[TestCase(  400, "SUMIF(A2:A7, \"\", C2:C7)")]
public void SumIf_ReturnsCorrectValues_ReferenceExample2FromMicrosoft(int expectedOutcome, string formula)
{
  using (var wb = new XLWorkbook())
  {
    wb.ReferenceStyle = XLReferenceStyle.A1;

    var ws = wb.AddWorksheet("Sheet1");
    ws.Cell(2, 1).Value = "Vegetables";
    ws.Cell(3, 1).Value = "Vegetables";
    ws.Cell(4, 1).Value = "Fruits";
    ws.Cell(5, 1).Value = "";
    ws.Cell(6, 1).Value = "Vegetables";
    ws.Cell(7, 1).Value = "Fruits";

    ws.Cell(2, 2).Value = "Tomatoes";
    ws.Cell(3, 2).Value = "Celery";
    ws.Cell(4, 2).Value = "Oranges";
    ws.Cell(5, 2).Value = "Butter";
    ws.Cell(6, 2).Value = "Carrots";
    ws.Cell(7, 2).Value = "Apples";

    ws.Cell(2, 3).Value = 2300;
    ws.Cell(3, 3).Value = 5500;
    ws.Cell(4, 3).Value = 800;
    ws.Cell(5, 3).Value = 400;
    ws.Cell(6, 3).Value = 4200;
    ws.Cell(7, 3).Value = 1200;

    ws.Cell(1, 3).Value = 300000;

    Assert.AreEqual(expectedOutcome, (double)ws.Evaluate(formula));
  }
}
```

**Comment by igitur** [comment]
Does COUNTIF work yet? I'm not near a computer to check.

**Comment by jongleur1983** [comment]
@igitur CountIf is implemented, but existing unit tests for CountIf doesn't cover wildcards.
Adding the following test cases (locally for now):

```Csharp
[TestCase(@"=COUNTIF(Data!E:E, ""J*"")", 12)]
[TestCase(@"=COUNTIF(Data!E:E, ""*i*"")", 21)]
[TestCase(@"=COUNTIF(Data!E:E, ""*in*"")", 9)]
[TestCase(@"=COUNTIF(Data!E:E, ""*i*l"")", 9)]
[TestCase(@"=COUNTIF(Data!E:E, ""*i?e*"")", 9)]
[TestCase(@"=COUNTIF(Data!E:E, ""*o??s*"")", 10)]
[TestCase(@"=COUNTIF(Data!E:E, """")", 0)]
public void CountIf_ConditionWithWildcards(string formula, int expectedResult)
{
    var ws = workbook.Worksheets.First();

    int value = ws.Evaluate(formula).CastTo<int>();
    Assert.AreEqual(expectedResult, value);
}
```

From those the patterns `J*`, `*i?e*` and `*o??s*` fail (returning wrong numbers from the assertion, no parser exceptions here.
The other patterns `*i*`, `*i*l`, `*in*` and the empty string pass the tests.

I conclude that I was wrong in generalizing the pattern conditions were not implemented, but at least they're incomplete in `COUNTIF` and not used in `SUMIF` yet.

**Comment by jongleur1983** [comment]
I pushed my (still failing) tests for reference to my fork, will try to work on the issue in the next days.

**Comment by kenleese** [comment]
Consider additional tests that use "~?", "~*", and "~~" as criteria to match "?", "*", and "~" respectively.

**Comment by jongleur1983** [comment]
@kenleese yes, thanks, will do.

**Comment by igitur** [comment]
Have a look at `CalcEngineHelpers.ValueSatisfiesCriteria`. This method evaluates the criteria. If the criteria is "wildcardish", it attempts to convert it to a regular expression and evaluates it. You will have to adjust that part fo cater for the other kinds of wildcards. I see you're working on some fixes. I have some exams coming up. Will be able to look at it only next week.

**Comment by jongleur1983** [comment]
this issue could be closed, right?
