### ISSUE TITLE
Export to excel with ClosedXML not working after publish to IIS

### ISSUE THREAD

**Issue by ocortesmx** [ClosedXML/ClosedXML#549]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.69.1.0

**What is the current behavior?**

I have an application that uses the following code to export to excel. Everything works perfect on my development machine but when I go to Build -> Publish and publish the website to a folder in my machine and then copy the files to the virtual directory on IIS everything works but the Export to excel. When users click on Export the page just blinks and nothing gets downloaded. The application was developed by someone else and it works on IIS. I just made a change not related to export and re-publish the website and that is when I get the problem. 

I already check on the bin folder of the app and ClosedXML.dll, DocumentFormat.OpenXml.dll and DocumentFormat.OpenXml.xml are in there. Like I said a version of the website is already working on IIS but my republished version doesn't work. What am I missing? Any help will be appreciated it

**What is the expected behavior or new feature?**

Create an excel file

**Did this work in previous versions of our tool?  Which versions?**

Yes

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
   protected void btnExport_Click(object sender, EventArgs e)
        {
            try
            {
                var datesTo = txtDateTo.Text.Split('/');
                var datesFrom = txtDateFrom.Text.Split('/');

                hdnFromDate.Value = txtDateFrom.Text;
                hdnToDate.Value = txtDateTo.Text;

                var YearTo = datesTo[2];
                var MonthTo = datesTo[0];
                var DateTo = datesTo[1];

                var YearFrom = datesFrom[2];
                var MonthFrom = datesFrom[0];
                var DateFrom = datesFrom[1];

                var obj = new clsReport();
                var myds = new DataSet();
                if (chkroute.Checked)
                    myds = obj.getunChanged(YearFrom + "/" + MonthFrom + "/" + DateFrom,
                        YearTo + "/" + MonthTo + "/" + DateTo, txtRoute.Text, 1);
                else
                    myds = obj.getunChanged(YearFrom + "/" + MonthFrom + "/" + DateFrom,
                        YearTo + "/" + MonthTo + "/" + DateTo, txtRoute.Text, 0);
                using (var wb = new XLWorkbook())
                {
                    wb.Worksheets.Add(myds);
                    var fileName = "Report" + DateTime.Today.ToString("dd-MM-yyyy") + "_" + DateTime.Now.Hour +
                                   "-" + DateTime.Now.Minute + "-" + DateTime.Now.Second;
                    Response.Clear();
                    Response.Buffer = true;
                    Response.Charset = "";
                    Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                    Response.AddHeader("content-disposition", "attachment;filename=" + fileName + ".xlsx");
                    using (var MyMemoryStream = new MemoryStream())
                    {
                        wb.SaveAs(MyMemoryStream);
                        MyMemoryStream.WriteTo(Response.OutputStream);
                        Response.Flush();
                        Response.End();
                    }
                }
            }
            catch (ThreadAbortException)
            {
            }
            catch (Exception ex)
            {
            }
        }
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
I guess an exception is thrown and swallowed by he try/catch.

**Comment by ocortesmx** [comment]
I didn't think about that, I will check it. 
Thanks

**Comment by igitur** [comment]
Code sample is also way insufficient. RTFM. Closing this as there is no way for me to reproduce this.

**Comment by ocortesmx** [comment]
I was able to see the error after eliminating the try/catch. There was a problem with OpenXML different version than the one on development machine. After I installed the same version the application worked correctly. Thank you for the suggestion!

**Comment by GuruDevOp7884** [comment]
How can we see the open xml version? Can you teach me?
