### ISSUE TITLE
installed ClosedXml nuget from nuget manager but can't load an existing excel file

### ISSUE THREAD

**Issue by ravianand1988** [ClosedXML/ClosedXML#55]
I installed ClosedXml nuget from nuget manager but can't load an existing excel file.

    string file = "test.xlsx";
                if (System.IO.File.Exists(Server.MapPath("~/App_Data/" + file)))
                {
                    var path = Server.MapPath("~/App_Data/" + file);
                        
                    //var workbook = new XLWorkbook(Server.MapPath("~/App_Data/" + file));
                    var workbook = new XLWorkbook(path);

or  i did like

    var stream = ExcelHelper.getExcelFileAsStream();
    var workbook = new XLWorkbook(stream);

nothing works

**getting object instance not set an instance of an object on line**  
     
     var workbook = new XLWorkbook(stream);

any help would be highly appreciable,

**as discussed in stackoverflow, sample file attached.** 

[Test.xlsx](https://github.com/ClosedXML/ClosedXML/files/510515/Test.xlsx)

**Comment by igitur** [comment]
The problem is `Table2` on the `Data` worksheet has a hidden header row. I'll fix the problem, but the quick workaround for you is to enable the header row.

![image](https://cloud.githubusercontent.com/assets/145854/19113399/b3a397c6-8b09-11e6-92a7-a1264f4c4122.png)

**Comment by ravianand1988** [comment]
got it, but what if i don't want header row in this table.

**Comment by igitur** [comment]
I'll have to fix the bug first before you can do that.

**Comment by ravianand1988** [comment]
alright, will follow.  should i close this question?

**Comment by igitur** [comment]
No, leave open please.

**Comment by ravianand1988** [comment]
oaky.
