### ISSUE TITLE
No interface for XLWorkbook?

### ISSUE THREAD

**Issue by kendallb** [ClosedXML/ClosedXML#550]
**Do you want to request a *feature* or report a *bug*?**
- [x] Feature

**Version of ClosedXML**

0.89.0

**What is the expected behavior or new feature?**

In order to make it easier to unit tests code that uses ClosedXML, it would be greate if XLWorkbook had an IXLWorkbook interface that defines the public interface. Then you can easily inject it with dependency injection with a wrapper to create the actual class when you need it, which makes it possible to mock any calls to the workbook?

**Comment by kendallb** [comment]
I implemented this in my tree so it shows up in my current pull request:

https://github.com/ClosedXML/ClosedXML/pull/547

**Comment by igitur** [comment]
Sounds good but please keep separate PRs for separate issues.

**Comment by kendallb** [comment]
How do I make sure a new change does not automatically attach to my existing PR as that is what git did automatically?

**Comment by igitur** [comment]
You have to create a new branch on your side, based on the main
repository'n develop branch. And submit the PR from that branch. Branching
is a key concept  with git.

**Comment by igitur** [comment]
Oh, I see you did all your work on one branch. Yeah, not a good idea. Here's what I do (assuming origin and upstream for http://github.com/igitur/ClosedXML and http://github.com/ClosedXML/ClosedXML)

```
git checkout -b new_branch_name upstream/develop
<do changes>
<stage changes>
git commit -m "Your message"
git push origin new_branch_name
Go to your Github page and create PR
```

**Comment by kendallb** [comment]
Ok cool. I use branches all the time I just never made the connection between using a branch and creating a PR. Doh.

**Comment by kendallb** [comment]
Do you want me to separate them?

**Comment by igitur** [comment]
Yes, separate please.

**Comment by kendallb** [comment]
Ok original PR is closed and two new ones are created
