### ISSUE TITLE
Second instance of download rejected

### ISSUE THREAD

**Issue by AlBakerKY** [ClosedXML/ClosedXML#554]
[Testorama (3).xlsx](https://github.com/ClosedXML/ClosedXML/files/1398685/Testorama.3.xlsx)
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.89

**What is the current behavior?**

When trying to download the XMLfile it is rejected.  Virus scanners claim infection. This same issue is discussed by another user in the following SO post.

https://stackoverflow.com/questions/46515739/asp-net-mvc-5-with-closedxml-not-able-to-export-to-excel-getting-virus-detecti

Also noted this error.  Please see the inserted emphasis.....

{"Message":"An error has occurred.","ExceptionMessage":"The type initializer for 'MS.Utility.EventTrace' threw an exception.","ExceptionType":"System.TypeInitializationException","StackTrace":" at MS.Utility.EventTrace.EasyTraceEvent(Keyword keywords, Event eventID)\r\n at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)\r\n at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.CreateCore(Stream stream)\r\n at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Create(Stream stream, SpreadsheetDocumentType type, Boolean autoSave)\r\n at ClosedXML.Excel.XLWorkbook.CreatePackage(Stream stream, Boolean newStream, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)\r\n at ClosedXML.Excel.XLWorkbook.SaveAs(Stream stream, SaveOptions options)\r\n at HALCommon.Utilities.Reporting.Cba.Render()\r\n at HALTest.Controllers.API.JournalAPIController.ExportAsCba(String id)\r\n at lambda_method(Closure , Object , Object[] )\r\n at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.b__9(Object instance, Object[] methodParameters)\r\n at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Filters.ActionFilterAttribute.d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Dispatcher.HttpControllerDispatcher.d__1.MoveNext()","InnerException":{"$type":"System.Web.Http.HttpError, System.Web.Http","Message":"An error has occurred.","ExceptionMessage":"**Requested registry access is not allowed.**","ExceptionType":"System.Security.SecurityException","StackTrace":" at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)\r\n at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)\r\n at Microsoft.Win32.Registry.GetValue(String keyName, String valueName, Object defaultValue)\r\n at MS.Utility.EventTrace.IsClassicETWRegistryEnabled()\r\n at MS.Utility.EventTrace..cctor()"}}

**What is the expected behavior or new feature?**

Not being or matching the pattern of a virus.

**Did this work in previous versions of our tool?  Which versions?**

Unknown

## Reproducibility

For our particular installation, it occurs on all exported spreadsheets.

**Code to reproduce problem:**
```c#
 public MemoryStream Render()
        {
            var stream = new MemoryStream();
            CreateDocument().SaveAs(stream);
            return stream;
        }

   using (var stream = new HALCommon.Utilities.Reporting.Cba(journal).Render())
            {
                var result = new HttpResponseMessage(HttpStatusCode.OK)
                {
                    Content = new ByteArrayContent(stream.ToArray())
                };
 
                result.Content.Headers.ContentDisposition =
                    new ContentDispositionHeaderValue("attachment")
                    {
                        FileName = $"{journal.Name}.xlsx"
                    };
                result.Content.Headers.ContentType = new MediaTypeHeaderValue("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
                return ResponseMessage(result);
            }

**Comment by igitur** [comment]
Complete the full template.

**Comment by mikaelsnavy** [comment]
@igitur  - Did you ever find a solution??

**Comment by igitur** [comment]
No, sorry

**Comment by mikaelsnavy** [comment]
It appears to be related to impersonation in the web.config. Remove that and impersonate only where you need in code.
