### ISSUE TITLE
Poor performance deleting rows

### ISSUE THREAD

**Issue by rodriigomtz** [ClosedXML/ClosedXML#557]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.89.0

**What is the current behavior?**

I use ClosedXML in VB.NET to create about 9,000 Excel files, it runs smoothly creating 100 file per minute, recently i add code to delete some rows and the process decrease his performance.

**What is the expected behavior or new feature?**

Is there an alternative to improve the performance of this activity? 

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**

                Select Case number
                    Case 1 : worksheet.Rows("79:158").Delete()
                    Case 2 : worksheet.Rows("104:158").Delete() : worksheet.Rows("50:79").Delete()
                    Case 3 : worksheet.Rows("134:158").Delete() : worksheet.Rows("50:104").Delete()
                    Case 4 : worksheet.Rows("50:134").Delete()
                End Select

```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Not a complete code example. Read https://stackoverflow.com/help/mcve
Also try v0.90-beta2 on NuGet

**Comment by SiL3NC3** [comment]
What if you are firstly get all the data rows into a datatable (in memory) and the delete the rows in a datatable before creating the excel sheets?!

**Comment by rodriigomtz** [comment]
Hello @SiL3NC3 the code deletes the lines from a template depending a variable, so in this step i don´t add data to the sheet, thank you for commenting.
