### ISSUE TITLE
DateTime not being formatted correctly?

### ISSUE THREAD

**Issue by kendallb** [ClosedXML/ClosedXML#566]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**

0.90.0

**What is the current behavior?**

I am reading a date from a .xlsx file that is formatted like so:

"10/27/2017 21:00"

using the default Excel formatting for 24 hour times. However when this is loaded via ClosedXML, if I render it to a string using GetFormattedString() I get this as the result:

"0/26/13 9:00;@"

**What is the expected behavior or new feature?**

It should be returning the properly formatted date:

"10/27/2017 21:00"

**Did this work in previous versions of our tool?  Which versions?**

No idea

## Reproducibility

- [x ] I attached a sample spreadsheet.  (You can drag files on to this issue)
[bad-date.xlsx](https://github.com/ClosedXML/ClosedXML/files/1423459/bad-date.xlsx)

**Comment by kendallb** [comment]
In fact I just realized that it is actually reading the date as 2013? Not 2017? So it is not only getting the formatting wrong, it is reading it wrong?

**Comment by kendallb** [comment]
Also just notcied that if I change it to be formatted as the default (10/27/2017 9:00 PM) then it simply reads as a double and GetFormattedString() just returns this:

"[$-4415749]m/d/yy h:mm AM/PM"

[bad-date-2.xlsx](https://github.com/ClosedXML/ClosedXML/files/1423494/bad-date-2.xlsx)

**Comment by igitur** [comment]
ClosedXML currently uses the built in dotnet `ToString`function for converting a `DateTime` to `string`. This menas4there4are some eccentric formats that don't deliver the required result.

**Comment by kendallb** [comment]
Well when the value comes out of the Excel file as a double (OADate) it really needs to be converted into a DateTime, not returned as a double. So the second file is wrong there as well.

As for the formatting that is one thing but I cannot work around that bug by looking for a DateTime type and formatting it myself because it parses it incorrectly as 2013 not 2017 for the year? That part needs to be fixed ASAP as I am not sure why it does that, and then I could wok around the bad date formatting.

But the date formatting needs to work also. I assume .net is not going to understand Excel style date formatting, so there would need to be something to convert them to .net formats? That is how the C1.Excel library does it.

This library is one that the ExcelDataReader folks are building to do that. I wonder if it could be used here?

https://github.com/andersnm/ExcelNumberFormat

**Comment by igitur** [comment]
That library looks promising, thanks. I will look at it after my actuarial exams this year are finished. 

For anything ASAP, I suggest you submit a PR.

**Comment by kendallb** [comment]
Ok, I need to get VS2017 installed and then I can take a look. Maybe later this weekend.

**Comment by kendallb** [comment]
Nice! Is the new version on NuGet yet so I can try it out?

**Comment by igitur** [comment]
Yes, a pre-release was published today.
