### ISSUE TITLE
Days360 european version

### ISSUE THREAD

**Issue by Apskalle** [ClosedXML/ClosedXML#569]
**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x ] Feature

**Version of ClosedXML**

0.87.0.0

**What is the current behavior?**

There is a Days360(date, date) formula registered

**What is the expected behavior or new feature?**

I desperately need the one with the optional parameter set to true (european version)

**Did this work in previous versions of our tool?  Which versions?**

N/A

**Comment by igitur** [comment]
If it's urgent, I suggest you submit a PR.

**Comment by Apskalle** [comment]
My bad,

ClosedXML accepts the third param, works fine.

Thanks for a great tool!

/M

Från: Francois Botha [mailto:notifications@github.com]
Skickat: den 29 oktober 2017 21:57
Till: ClosedXML/ClosedXML <ClosedXML@noreply.github.com>
Kopia: Apskalle <pal-martin@outlook.com>; Author <author@noreply.github.com>
Ämne: Re: [ClosedXML/ClosedXML] Days360 european version (#569)


If it's urgent, I suggest you submit a PR.
