### ISSUE TITLE
Culture being ignored when adding sheet from DataTable

### ISSUE THREAD

**Issue by materiari** [ClosedXML/ClosedXML#573]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.88.0

**What is the current behavior?**

When I add a worksheet via a `DataTable`, I would expect the date formats to follow the locale/culture of the application but it appears to take that from the computer or be using.

```
string culture = "en-GB";
var newCulture = new CultureInfo(culture);
Thread.CurrentThread.CurrentCulture = newCulture;
Thread.CurrentThread.CurrentUICulture = newCulture; //probably unnecessary?
CultureInfo.DefaultThreadCurrentCulture = newCulture;

var workBook = new XLWorkbook();
// ... select myDateColumn, myIntCol, myString
workBook.AddWorksheet(myDataTableThatContainsQueryResults, tabName);

```
Now, you'd expect the first column (myDateColumn) to format using the short date format of the en-GB locale which should be `'31/10/2017'` but it's coming out as `'10/31/2017'` instead.

I checked the locale in the DataTable once I get it back from the SQLDataAdapter and it's correct as are the nested date formats. Note that there are multiple queries and I won't know where the dates are in advance.

**What is the expected behavior or new feature?**
The expected behavior is to use the formatting and globalization of the currently configured culture.

**Did this work in previous versions of our tool?  Which versions?**

Don't know, this is my first usage of ClosedXML.  Pretty amazing except for this weird issue.

Yes/No/v0.XX

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
//only thing that's hard for me to provide as a sample is a database and connection
//I can probably cobble together an item but you'd still need to tweak it for local use
string culture = "en-GB";
var newCulture = new CultureInfo(culture);
Thread.CurrentThread.CurrentCulture = newCulture;
Thread.CurrentThread.CurrentUICulture = newCulture; //probably unnecessary?
CultureInfo.DefaultThreadCurrentCulture = newCulture;

var workBook = new XLWorkbook();
// ... select myDateColumn, myIntCol, myString
// obviously I can't provide a DB connection from your environment to give you a DataTable
workBook.AddWorksheet(myDataTableThatContainsQueryResults, tabName);
    
}
```
- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)
[quick_test_basic.xlsx](https://github.com/ClosedXML/ClosedXML/files/1432494/quick_test_basic.xlsx)

**Comment by igitur** [comment]
Please try with v0.90

**Comment by materiari** [comment]
Upgraded my setup to use v0.90.  Tested again.  Still showing US-style dates.

**Comment by igitur** [comment]
Give me code that I can run. i.e. build your DataTable and populate manually

**Comment by materiari** [comment]
Fair enough.  Here you go.  I wrote a version that is self-contained (no DB) and creates a very similar `DataTable` on the fly.  All in one C# file.  Since attach in GitHub doesn't support .cs files, I've renamed to .txt and included a .xlsx of the output.

[CultureTestOutput.xlsx](https://github.com/ClosedXML/ClosedXML/files/1435005/CultureTestOutput.xlsx)
[CultureTestCS.txt](https://github.com/ClosedXML/ClosedXML/files/1435011/CultureTestCS.txt)

**Comment by igitur** [comment]
If you create a new workbook in Excel and set the first cell's formula to `=TODAY()`, what date format does it default to?

**Comment by materiari** [comment]
* The server creating the file is in the US
   * The recipient is not.  
* I can't control the data sets being sent back so I have no way of knowing which columns may contain dates.  Is there a way to know which ones are dates to force the formatting?

**Comment by materiari** [comment]
So, here's the issue:
![image](https://user-images.githubusercontent.com/7494427/32305589-9974408a-bf33-11e7-9572-a3e12f06a787.png)

Setting my local SHOWS me the data as UK but if you look at the value ("formula/edit" view) for the selected row, it's coming across as US.

**Comment by igitur** [comment]
You didn't answer my questions.

And you can inspect a datatable's columns' data type to see which ones are DateTime.

**Comment by materiari** [comment]
=TODAY() shows me US-dates.

**Comment by vbjay** [comment]
Dates in Excel are stored as a number from an epoch in the cell. If your
region is setup to display dates in that format then that's exactly what it
does. If you want the date in a different format, then set the number
format to a specific value.

**Comment by igitur** [comment]
What @vbjay said. 

ClosedXML is working as expected. The thread's culture doesn't affect the default formatting.

**Comment by daniloak** [comment]
> * The server creating the file is in the US
>   
>   * The recipient is not.
> * I can't control the data sets being sent back so I have no way of knowing which columns may contain dates.  Is there a way to know which ones are dates to force the formatting?

I have the same issue, sometimes the recipient culture is french, I am formatting using MM/dd/yyyy in french it would be "MM/jj/yyyy" and it doesn't format properly

**Comment by igitur** [comment]
@daniloak Please open a new issue and complete the issue template fully.
