### ISSUE TITLE
Refactoring: Change Code Structure to a more solid style

### ISSUE THREAD

**Issue by jongleur1983** [ClosedXML/ClosedXML#577]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Code refactoring to support new features and make maintenance easier. ;)

**Version of ClosedXML**
current develop branch

**What is the current behavior?**

Currently most code dealing with Expression evaluation is static and defined in a small set of classes.
These classes grow with a bigger number of supported functions and get hard to handle.

As the amount of tests for the functions is even bigger (once complete) than the function itself, this is especially true for the corresponding test classes (where currently one test class matches one implementation class).

**What is the expected result or new feature?**

I propose to change different aspects of the code architecture as outlined below:

- [ ] Introduce an interface IExcelFunction with the following signature:
  - Name: a readonly string property that returns the English (and therefore "base") name of the function
  - MinParamCount, MaxParamCount: properties specifying the expected parameter counts
  - Evaluate(): a function to be implemented that takes a number the parameters, for now let's keep the syntax the same as it is currently: object Evaluate(List<Expression>).
- [ ] Change the registration of functions: Currently Register() on all "category" classes is called explicitly by the CalcEngine, registering each included function. Instead I propose to use reflection to discover all implementors of IExcelFunction for registration: Collect all implementing classes within the ClosedXML assembly and call their Register() function.
- [ ] In a later step (not covered here directly, but could be a follow-up issue), Register() could be extended to take a CultureInfo parameter. This would allow localizations of Excel functions as required (e.g. nearly any function is translated to German), later to be used for extended features translating formulas etc.
- [ ] If there are functions not supported by any possible Excel version, Register() could take an excel version as compatibility level. Examples: AverageIf and AverageIfs are not supported in Excel 2003, but in 2007 and 2010, a lot of statistical distribution functions are new in 2010. By supporting the minimum required version of Excel ClosedXML could be safe to use with Excel 2003 as target, but on the same time supporting functions introduced later.
- [ ] Keep the pattern of one test class per functionality class in the long run. Short term, without starting with this feature itself, I propose to add new tests to separate classes per function already. This lowers the refactoring effort for this issue without making it a hard precondition to work on supporting more functions in the short run.

Implementors of IExcelFunction could - and IMHO should (without a technical requirement) support strongly typed versions of Evaluate() to be called directly where appropriate. With different overloads for different numbers of parameters etc, using enums for parameters where enums would be the "natural" .NET way to model something (as the mode for AGGREGATE).

**Comment by vbjay** [comment]
We could use MEF and put the formula processing into one or more
libraries.  This would allow things like DateFunctions.dll and
TrigFunctions.DLL.... This would help organize and make small function
libraries.  Your idea could be part of the base MEF interface.

https://docs.microsoft.com/en-us/dotnet/framework/mef/

**Comment by jongleur1983** [comment]
@vbjay I think that would be several steps ahead. IMHO all excel functions shoud be core part of ClosedXML, so using any mechanism to add external libraries might be too much overhead for very little benefits.
The benefits of MEF (or similar) are only there if it should be possible to extend the functionality of a library without access to it.
For this issue here, the function set of Excel is well defined and not easily extensible as far as I know, so external libraries are not of much use.
Or what's the benefit you see that I don't see yet?

**Comment by vbjay** [comment]
I was thinking that we provide the loading and saving, basic cell work like
setting values and such as the base closedxml piece. Then we could layer on
top the calculations and other features. This would allow others to write
plugins that plug the hole of I need feature x in my spreadsheet. This
would allow more hands and better separation.

My idea would be

export CalcFunctions
Export Pivot...
Export charting
Export image functionality

These things would extend cells, ranges, sheets..  This way the needed
items could be loaded on demand. Detect custom fornating so load custom
fornating plugins. If processing formulas, load calculations engine
plugins.

**Comment by jongleur1983** [comment]
I think it depends very much on the usage scenario.
Separating that far is beyond my current knowledge on the overall library, so I neither know how to best separate it into packages as you propose, nor I could estimate how much overhead that is compared to the benefits for some scenarios.
As we're talking about a library: Would it be possible to use Nuget/Paket as a separation model somehow instead of MEF?
As far as I understand MEF it's more an auto-connecting thing for plugin stuff, at least that's how MEF is used in Visual Studio. Is that a feature ClosedXML could benefit from (realistically)? or do you in fact want to propose just a way to keep the library as small as possible for different use cases?

In that case, why not build ClosedXML.Core, ClosedXML.Charts, ClosedXML.Pivot and so on, where you can add packages you need, and omit those you don't care about.

In general, packaging into different DLLs IMHO is a next step, I'd like to keep this issue focused on the current problems. MEF might solve a different issue, and might even benefit from this issue. If it's agreed to go the MEF route and you want to take that issue, that's okay for me, too, but it's nothing I personally would want to work at it (in a first glance), as I have no experience with it.

**Comment by igitur** [comment]
@jongleur1983 Thanks for the contribution. However, I don't think maintainability is a problem yet. If the files get really large, we can split into partial classes. I'm reluctant to add additional complexity just for the sake of maintainability. Splitting functions into a separate class could impact performance, because a new class would have to be instantiated for every formula evaluation. 

Excel Versioning isn't really applicable. Excel 2003 doesn't support .xlsx files anyway. And the goal of the project isn't to be a headless Excel clone. The goal is to read/write valid xlsx files that any of the spreadsheet apps, including LibreOffice Calc, can read/write. 

I also avoid Reflection like the plague, unless really necessary. 

Sorry, but I don't think the benefits outweigh the possible risks involved.

Internationalisation also isn't a priority right now. 

MEF could be useful for users to provide their own UDFs.

**Comment by jongleur1983** [comment]
@igitur if internationalization is not a priority for you, that's okay. If it's not a priority in general, it might be a showstopper for me.

More precise it might depend on how excel works in detail.
For reading existing excel files it would be crucial to be able to read excel files with German localization for me. 
If I'm right with my assumption, that the formulas are stored in the file as they have been written in Excel, then reading an Excel file created by a German Excel installation would crash once formulas have to be evaluated (as German formulas are not known).

Writing "readable" formulas (that is: German users are - unfortunately - used to the German function names) is not that important for me, but would be a great benefit as well.

**Comment by igitur** [comment]
What happens if a file created on Excel in DE is opened in Excel in UK? Does Excel understand them?

And I don't mean it won't be done. But the priorities now are: bug fixes, memory usage, netstandard support, finishing formulae, cross workbook actions, stabilising image and pivot table support.

**Comment by jongleur1983** [comment]
UPDATE (was writing an edit on my last comment, you're responding too fast ;) ):
after testing around with this issue I found out that Excel nowadays in fact stores the English formula only and translates that to the target locale for the user.
That is: Any English localized Excel file (e.g. the examples from the loading test suite) opened with Excel show German formulas, and a file created with a German localized Excel, read with ClosedXML returns English Formula names as well, so localization in fact is not an issue (sorry for the trouble here).

Although I still think keeping classes (not only files) reasonable small, not creating god classes that have hundrets of methods is the preferred way to go, I obviously have to step back for this refactoring approach. Thanks for the discussion anyway.

**Comment by vbjay** [comment]
I doubt the formulas are different by language.  The menu options in the ribbon might say something else, but the formula should be the excel formula no matter what.

I doubt you write

=Summe(12,5,4,2)

**Comment by jongleur1983** [comment]
@vbjay in fact in the Excel UI you write =Summe(12,5; 5; 4; 2) (comma is used as decimal separator in German locale, so 12,5 is the English 12.5, the semicolon is used for the argument separation instead.
But you're right: the document is always stored in en-US locale, so in the XML files it's still SUM(12.5, 5, 4, 2)

**Comment by vbjay** [comment]
Which means the display of the formula is handled by excel.  The formula that is stored is plain english excel formulas.  That would have been a nightmare if excel stored different formulas for different regions.  I bet the formulas also only use , to separate arguments in the xml.

**Comment by jongleur1983** [comment]
@vbjay yes, they do, everything's fine in that regard.
But about nightmares: Excel before the OpenDocument XML formats in fact did it that way, and "localization" for Exceptions and stuff like that is the same, so if you have anyone with a complete hungarian localization (system culture and ui culture), stacktraces become impossible to read, so sorry for my wrong guess, but it wasn't without reason.

**Comment by vbjay** [comment]
LOL.  That must have been fuuuunnn.  :D  They got wise.

**Comment by igitur** [comment]
@pankraty Your comments on these proposed changes?

**Comment by jahav** [comment]
I am closing this, because it's essentially bike shedding.

Generally speaking, I am pretty happy with Excel functions being represented by a delegate/function.

Any testing should be done through external API. Test against contract, not implementation. Implementation can change (as has happened during `Expression` to `AnyType` switch).
