### ISSUE TITLE
Unhandled exception thrown when loading a workbook with '#N/A' printarea

### ISSUE THREAD

**Issue by dhnc4u** [ClosedXML/ClosedXML#578]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.90

**What is the current behavior?**

ParseReference in XLWorkbook_Load.cs (Line 1227) can return an empty string for sheetName, which makes the calling code (Line 1138 of XLWorkbook_Load.cs) ...
WorksheetsInternal.Worksheet(sheetName).PageSetup.PrintAreas.Add(sheetArea);
... throw an unhandled exception.
 
**What is the expected behavior or new feature?**

Invalid print areas should be ignored, so the files can be loaded in ClosedXML.

One way to fix the issue is to add an additional sheetName check in line 1137:
 if (!(sheetArea.Equals("#REF") || sheetArea.EndsWith("#REF!") || sheetArea.Length == 0 || sheetName.Length == 0))

**Did this work in previous versions of our tool?  Which versions?**

Don't know

## Reproducibility

**Code to reproduce problem:**
```
Dim sInputFile As String = Path.Combine(Application.StartupPath, "xlsxfiles", "issue1.xlsx")
       Dim theWorkbook = New Excel.XLWorkbook(sInputFile)
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)
[issue1.xlsx](https://github.com/ClosedXML/ClosedXML/files/1443289/issue1.xlsx)

**Comment by igitur** [comment]
Thanks. Since you already know the fix,  kindly submit a PR, including a unit test. Look at the existing LoadingTests file. You can add the xlsx file to the others there.

**Comment by igitur** [comment]
You just set the xlsx file to be an embedded resource. In Visual Studio, select the file, press F4 and look in the properties.

**Comment by dhnc4u** [comment]
Regarding the unit test part: 
- I added the xlsx to the string list at line 21 of LoadingTests.cs.
- I added the xlsx file to 'ClosedXML_Tests\Resource\Misc' and included it to the project.
(- I referenced the ClosedXML_Tests project from my test project inside the solution)

That does not allow me to run CanSuccessfullyLoadFiles yet... what is required additionally please ?
Thrown error: System.ApplicationException: 'Can't find resource file ClosedXML_Tests.Resource.Misc.InvalidPrintArea.xlsx'

Thanks !
