### ISSUE TITLE
Out-of-memory exception when inserting a new column in what looks like a basic worksheet

### ISSUE THREAD

**Issue by dhnc4u** [ClosedXML/ClosedXML#579]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.90

**What is the current behavior?**

Inserting a column takes extremely long in some files for a yet unknown reason.
I stopped the process after 5 minutes, while the code was still keeping a full CPU core busy and memory was still raising.
I have added a slimmed down example of a real life Excel file.
The Excel GUI adds the column instantly.
In the real life files, the code results in an Out-Of-Memory exception.

**What is the expected behavior or new feature?**

Inserting a column should be faster.
There is probably some hidden complexity to the files (and the example file) that causes ClosedXML to behave as it does.

**Did this work in previous versions of our tool?  Which versions?**

Don't know.

## Reproducibility

**Code to reproduce problem:**
```
Dim sInputFile As String = Path.Combine(Application.StartupPath, "xlsxfiles", "issue3.xlsx")
        Dim theWorkbook = New Excel.XLWorkbook(sInputFile)
        Dim theWorksheet = theWorkbook.Worksheet("dummy")
        Dim theColumns = theWorksheet.Column(7).InsertColumnsAfter(1)
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)
[issue3.xlsx](https://github.com/ClosedXML/ClosedXML/files/1443348/issue3.xlsx)

**Comment by igitur** [comment]
I don't have a complete solution, but if you can consolidate the many disjointed conditional formatting rules, it will save a lot of memory.

**Comment by igitur** [comment]
#520 could also help in this regard.

**Comment by Laurakwakwak** [comment]
Hello,

I have the same problem and I don't find the solution, I just find this issue.

In a foreach I try to insert columns with this:
`worksheet.Column(clnFilled).InsertColumnsAfter(1)`

But in the third iteration it goes in the catch with a OutOfMemoryException and no explication.

Someone has found the solution since this time ?

Sorry for my english.

**Comment by Pankraty** [comment]
@Laurakwakwak, though the exception is the same, there may be different reasons for out-of-memory. Would you mind attaching a sample file and providing a code to reproduce the problem?

**Comment by Laurakwakwak** [comment]
Thanks for your quick answer.

Here is the code:
```
For Each CurrentGLS As BO_GLS In GLSList
	Dim result = FillExcel(worksheet, CurrentGLS, column_currentIndex)

	If (result) Then
		column_currentIndex += 1
	Else
		errorMessage = "Un problème est survenu lors du remplissage du template"
		GoTo error_during_report_fill
	End If
Next

Private Shared Function FillExcel(worksheet As IXLWorksheet, gls As BO_GLS, clnFilled As Integer) As Boolean
    Dim result As Boolean = True
	Dim rowPoste As Integer = 3

	Try
		'Insert a column to fill with the gls
		worksheet.Column(clnFilled).InsertColumnsAfter(1)
		'Set the name of the area
		worksheet.Cell(rowPoste, (clnFilled + 1)).Value = gls.Interfaces.sRecursifName

	Catch ex As Exception
		Throw New Exception("Un problème est survenu lors du remplissage du template")
	End Try

	Return result
End Function
```

And I attach the excel template
[Saint Eloi  2 sites Matrice Globale Vierge - Copie_v3_20180306114724.xlsx](https://github.com/ClosedXML/ClosedXML/files/1788698/Saint.Eloi.2.sites.Matrice.Globale.Vierge.-.Copie_v3_20180306114724.xlsx)


When I try this code in a new empty excel it works fine, so I don't understand what's wrong in my template

**Comment by Pankraty** [comment]
Well, it seems that the reason is in data validation rules defined in your workbook, just like in #680. I prepared a fix but did not create a pull request since I had to mute a couple of tests. 

@igitur, shall I create a PR anyway?

**Comment by igitur** [comment]
Ok, go ahead, but be patient while I review it. Lots of PRs coming in at the moment.

**Comment by Pankraty** [comment]
Nope, the problem is not in data validation. That's something new, related to conditional formats. Will create a new issue.

**Comment by Laurakwakwak** [comment]
I tried to remove all data validation and formula but it stills crash

**Comment by Pankraty** [comment]
Yeah, as I said, there may be different reasons, unfortunately. Switch to #719 for further discussion.

**Comment by igitur** [comment]
Is this still an issue with the latest v 0.939?

**Comment by dhnc4u** [comment]
I re-tested with the latest ClosedXML version and the same xlsx file as attached to my bug report above. This is now working as expected. Thanks for the good work !
