### ISSUE TITLE
Implement pageSetup 'copies' attribute to be able to 'fix' files that have the attribute set to 0

### ISSUE THREAD

**Issue by dhnc4u** [ClosedXML/ClosedXML#580]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x ] Feature

**Version of ClosedXML**

0.90

**What is the current behavior?**

Validation (upon save) will fail when the 'copies' attribute of the pageSetup element is set to 0, which is the case in several files I own. (Do not ask how that was set over the years...)
This is not an issue per se, but because ClosedXML does not expose the 'copies' attribute, there is no way to 'fix' a file before calling the save function.

Thrown exception in line 108 of XLWorkbook_Save.cs:
System.ApplicationException: 'The attribute 'copies' has invalid value '0'. The MinInclusive constraint failed. The value must be greater than or equal to 1. in /x:worksheet[1]/x:pageSetup[1]'

**What is the expected behavior or new feature?**

Implement and expose the OpenXML 'copies' property, which is linked to the copies attribute.

**Did this work in previous versions of our tool?  Which versions?**

N/A

## Reproducibility
**Code to reproduce problem:**
```
Dim sInputFile As String = Path.Combine(Application.StartupPath, "xlsxfiles", "issue4.xlsx")
        Dim theWorkbook = New Excel.XLWorkbook(sInputFile)
        theWorkbook.Save(True)
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)
[issue4.xlsx](https://github.com/ClosedXML/ClosedXML/files/1443376/issue4.xlsx)

**Comment by igitur** [comment]
You can disable validation if you save the file if you want to skip validation.

**Comment by dhnc4u** [comment]
Yes, I did that initially. Later I implemented the copies attribute, but quick and dirty and not under source control. I'll revisit and sent a pull request once I feel good about it.
