### ISSUE TITLE
DateTime arithmetic in formulas

### ISSUE THREAD

**Issue by Nephrops110** [ClosedXML/ClosedXML#584]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.87.1

**What is the current behavior?**

When it evaluates the formula "Today()" it returns a DateTime object. When it evaluates "Today() + 1" it returns an int.

**What is the expected behavior or new feature?**

It should return a DateTime object from a DateTime formula.

**Did this work in previous versions of our tool?  Which versions?**

Unknown but probably not.

## Reproducibility

The following code outputs:
06/11/2017 00:00:00
43046

**Code to reproduce problem:**
```c#
using System;
using ClosedXML.Excel;

namespace DateTimeIssue
{
    class Program
    {
        static void Main(string[] args)
        {
            XLWorkbook wb = new XLWorkbook();
            IXLWorksheet sheet = wb.AddWorksheet("Sheet1");

            Console.WriteLine(sheet.Evaluate("Today()"));
            Console.WriteLine(sheet.Evaluate("Today()+1"));
            Console.ReadLine();
        }
    }
}

**Comment by igitur** [comment]
Yeah, this is a known issue, but unlike to be fixed soon. Unless someone else submits a PR. 

I assume you have this formula in a cell and that you're not really calling `sheet.Evaluate()` in your own code? If so, have you tried explicitly setting the cell's `DataType` to `DateTime`?
