### ISSUE TITLE
Read or retrieve value from spreadsheet using existing rangenames

### ISSUE THREAD

**Issue by ravianand1988** [ClosedXML/ClosedXML#59]
i have an existing excel file and it has already defined cell name or cell range names.

I am able to get all cell range names using Openxml sdk. my sample code is given below:

     var path = @"D:\test.xlsx";
            using (var document = SpreadsheetDocument.Open(path, true))
            {
                var workbookPart = document.WorkbookPart;
                  var wb = workbookPart.Workbook;
                var definedNames = wb.DefinedNames;
                if (definedNames != null)
                {
                    System.Console.WriteLine("Name\tText\tName.Value");
                    foreach (DefinedName dn in definedNames)
                    {
                        System.Console.WriteLine(dn.Name + "\t" + dn.Text + "\t" + dn.Name.Value);
                       
                    }
                }

            }

Is there any way to retrieve or read cell value from defined name using this OpenXml or any other SDK in c#?
Any Help would be highly appreciable. 
Thanks

**Comment by igitur** [comment]
Have a look at [Named Ranges](https://closedxml.codeplex.com/wikipage?title=Named%20Ranges&referringTitle=Documentation) and [Accessing Named Ranges](https://closedxml.codeplex.com/wikipage?title=Accessing%20Named%20Ranges&referringTitle=Documentation)

(We're busy migrating the documentation over to here on GitHub).

**Comment by ravianand1988** [comment]
thanks a lot, it worked.

**Comment by ckernsiii** [comment]
Can we get a new reference to this as everything basically points to OLD data on a non-existing website. Everything points to github and it is very loosely pointing anywhere

**Comment by igitur** [comment]
@ckernsiii The new wiki is at https://github.com/ClosedXML/ClosedXML/wiki

**Comment by ckernsiii** [comment]
Thanks for the URL. I've already been there and still find my issue inconclusive with the given data. For instance, there is no equivalent exchange between OpenXML and ClosedXML so integrating Closed into Open is near impossible unless I fully learn everything about Closed AND Open before jumping in.

**Comment by igitur** [comment]
I have no idea what you're trying to do. Please open a new issue and complete the full issue template.
