### ISSUE TITLE
OutOfMemoryException on saving tiny file with pivot table

### ISSUE THREAD

**Issue by Blaaznar** [ClosedXML/ClosedXML#590]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.90

**What is the current behavior?**

OutOfMemoryException on saving file with empty pivot table.

XLRangeBase.cs line 778

**What is the expected behavior or new feature?**

To save the 15kb file without going out of memory.

**Did this work in previous versions of our tool? Which versions?**

Yes - up to and including v0.85
No - v0.86 (null reference on opening file)
No - v0.87.1 to v0.90.0 (out of memory)

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
using(var wb = new XLWorkbook(“sample.xlsx”)
wb.SaveAs(“output.xlsx”);
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[sample.xlsx](https://github.com/ClosedXML/ClosedXML/files/1475399/sample.xlsx)

**Comment by igitur** [comment]
Thanks for the good test case. 

The problem is that the pivot table references the entire column of the `PivotSource` sheet and that makes ClosedXML load every cell in that range. I'll look at solutions, but the meantime I suggest you limit the maximum row of the input data range to the pivot table.

**Comment by Blaaznar** [comment]
Unfortunately I have no control over this as my code is only modifying the excel files the end users provide. 
I'm stuck on v0.85 for the time being.
