### ISSUE TITLE
Unhandled OpenXmlPackageException when opening workbook which contains malformed email hyperlinks

### ISSUE THREAD

**Issue by dhnc4u** [ClosedXML/ClosedXML#593]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.90

**What is the current behavior?**
In XLWorkbook_Load, Loadsheets, the line...
var dSpreadsheet = SpreadsheetDocument.Open(fileName, false)
... receives an unhandled exception when a sheet contains a malformed email hyperlink, and further processing stops. 
The Excel file cannot be opened using ClosedXML, while Excel itself opens the file just fine.

**What is the expected behavior or new feature?**
This seems like a bug (or limitation ?) in the DocumentFormat.OpenXml library, really, so I'm not sure what ClosedXML can do ?

**Did this work in previous versions of our tool?  Which versions?**
Unknown

## Reproducibility
**'Code' to reproduce problem:**
In Excel, create a new workbook.
In cell A1, enter random text and a hyperlink (Right-click > Link).
Select 'E-mail address' and enter an invalid address, such as mailto:one@
Save the file and try to open the file with ClosedXML. 
It will not open due to above mentioned unhandled exception.

Note that the issue Workbook cannot be created with ClosedXML. Setting ExternalAddress to a malformed URI will throw a (valid) exception.

- [x ] I attached a sample spreadsheet.  (You can drag files on to this issue)
[issue6b.xlsx](https://github.com/ClosedXML/ClosedXML/files/1483318/issue6b.xlsx)

**Comment by vbjay** [comment]
Just a github tip.  

- [ ] unchecked
- [x] checked

**Comment by dhnc4u** [comment]
Thanks. Yes, I missed that, sorry.

**Comment by dhnc4u** [comment]
Now reported for the OpenXml SDK:
https://github.com/OfficeDev/Open-XML-SDK/issues/297

**Comment by igitur** [comment]
Thanks. Lets check what the OpenXML guys say.
