### ISSUE TITLE
Crash when opening file containing a pivot table created with MS Excel.

### ISSUE THREAD

**Issue by b0bi79** [ClosedXML/ClosedXML#596]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**
0.90.0

**What is the current behavior?**
If I open a file created with MS Excel that contains a pivot table, then I get an exception while saving with SaveAs.
```
 System.ApplicationException
Element 'DocumentFormat.OpenXml.Spreadsheet.PivotField' referenced by 'dataField@fld' does not exist in part '/xl/pivotTables/pivotTable1.xml'. The index is '7'. in /x:pivotTableDefinition[1]/x:dataFields[1]/x:dataField[1].
```

Stack trace:
```
   в ClosedXML.Excel.XLWorkbook.Validate(SpreadsheetDocument package) в D:\Sources\asr\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:строка 108
   в ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options) в D:\Sources\asr\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:строка 123
   в ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options) в D:\Sources\asr\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:строка 503
   в ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae) в D:\Sources\asr\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:строка 479
   в ClosedXML.Excel.XLWorkbook.SaveAs(String file) в D:\Sources\asr\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:строка 468
   в ClosedXML.Report.Tests.PivotTests.TestName() в D:\Sources\SSIV\ClosedXML.Report\tests\ClosedXML.Report.Tests\PivotTests.cs:строка 41

```

**Code to reproduce problem:**
```c#
public void Main()
{
     var workbook = new XLWorkbook("Static_Pivot5.xlsx");
     workbook.SaveAs("newPivot5.xlsx");
}
```
- [x] I attached a sample spreadsheet. 
[Static_Pivot5.xlsx](https://github.com/ClosedXML/ClosedXML/files/1487721/Static_Pivot5.xlsx)

**Comment by igitur** [comment]
Ok, it's a bug cause by the source range of the pivot table not starting in column A. I'll fix, but if you could move your source range one column to the left, it should work.

**Comment by b0bi79** [comment]
Thanks

**Comment by igitur** [comment]
I fixed the bug, but end up with a corrupt file, so this is going to take a bit longer. Keep in mind pivot tables are work in progress. Your pivot tables are way more complex than the samples I worked with. Bugs are expected.

**Comment by b0bi79** [comment]
I also fixed it, and now I get an error when I open file in Excel.
`Recovered records: Pivot table report from part /xl/pivotCache/pivotCacheDefinition1.xml (PivotTable cache)`

The error disappears if I change the file `pivotCacheDefinition1.xml` by adding the attribute `containsInteger = "1"` for `cacheField name = "OrderNo"` to `sharedItems`.

Now I study documentation https://technet.microsoft.com/ru-ru/library/documentformat.openxml.spreadsheet.shareditems.aspx
