### ISSUE TITLE
Conditional formatting rule fails when equals "0"

### ISSUE THREAD

**Issue by dontbyte** [ClosedXML/ClosedXML#597]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
Latest

**What is the current behavior?**
If you create a Conditional Formatting rule for the cell value "0" (string) then an empty cell is also formatted with this formatting rule. 

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
    var _Workbook = new XLWorkbook();
    var _Sheet = _Workbook.AddWorksheet("Test");

    var _Range = _Sheet.Range("A1:C10");
    _Range.AddConditionalFormat().WhenEquals("1").Fill.SetBackgroundColor(XLColor.Green);
    _Range.AddConditionalFormat().WhenEquals("0").Fill.SetBackgroundColor(XLColor.Red);
    _Range.AddConditionalFormat().WhenIsBlank().Fill.SetBackgroundColor(XLColor.White);

    _Workbook.SaveAs("Test.xlsx");
}
```
- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Test.xlsx](https://github.com/ClosedXML/ClosedXML/files/1487838/Test.xlsx)

**Comment by igitur** [comment]
And if you do it manually in Excel?

**Comment by dontbyte** [comment]
@igitur 
Okay, same behaviour. So this is not an ClosedXML issue.

Do you have an idea how to add the rule so that it only applies to cell value "0"?

**Comment by igitur** [comment]
Try changing the order of the rules. You probably want the blank one first.
