### ISSUE TITLE
Customized formula not persisted in  IXLCell

### ISSUE THREAD

**Issue by barongnt** [ClosedXML/ClosedXML#600]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**
0.90.0.0

**What is the current behavior?**

When setting programmatically a User Defined Excel formula on a  IXLCell instance, its value property throw an exception : **" (Closedxml.excel.instanceCell)cell).value threw an exception of type closed.excel.calcengine.expression parseException"**.

And if you set the value programmatically, the FormulaA1 property of the IXLCell instance get set to an empty string.

**What is the expected behavior or new feature?**

We want to set programmatically both FormulaA1 and Value properties.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

**Code to reproduce problem:**
```c#
public Stream ProcessWorkbookFormulas(Stream _workbookStream)
		{
			
			string formula = "=CustomFormula(\"\";$C$1;$C$2;\"6\";$A6)";

			using (XLWorkbook workBook = new XLWorkbook(_workbookStream))
			{
				
				int worksheetcount = workBook.Worksheets.Count;

				if (worksheetcount != 0)
				{
					foreach (IXLWorksheet workSheet in workBook.Worksheets)
					{
						foreach (IXLRow row in workSheet.Rows())
						{
							foreach (IXLCell cell in row.Cells())
							{
								if (cell.HasFormula)
								{
									cell.FormulaA1 = formula;
									cell.Value = 256;
								}
							}
						}
					}
				}

				var tempStream = new MemoryStream();
				workBook.SaveAs(tempStream);

				stream = new MemoryStream(tempStream.ToArray());
			}

			return stream;
		}
```

**Comment by igitur** [comment]
ClosedXML is design to have only a value or a formula. I don't understand why you want to input both. The formula should evaluate when you open the file in Excel.

**Comment by igitur** [comment]
PS: Hey, another Saffa! :-)

**Comment by barongnt** [comment]
I wanted to have both because I am dealing with User Defined Formula
instead of Excel formula.


Kind regards

 *Baron Isfandiyar*

Senior Software Engineer / Architect: Sage Intelligence Product Engineering

*Sage Group*



Office: 031-537-7244 | @BaronGnt

Sage.com <https://www.sage.com/> | Twitter
<https://twitter.com/sagegroupplc>| Instagram
<https://www.instagram.com/sageofficial/> | YouTube
<https://www.youtube.com/user/SageGroupPlc>| LinkedIn
<https://www.linkedin.com/company/sage-software>| Facebook
<https://www.facebook.com/sage>| Community <http://sagecity.na.sage.com/>

Durban, South Africa

**Comment by igitur** [comment]
If you can replicate such a file in Excel and attach it, then I can inspect it and see what I can do.

**Comment by barongnt** [comment]
Hi Francois,

Please find in attachment the Excel document.

Kind regards

 *Baron Isfandiyar*

**Comment by igitur** [comment]
Please use the Github web interface to upload attachments. Attachments through email replies don't work.

**Comment by barongnt** [comment]
sure, here is the file:

[UserDefinedFormulas.xlsx](https://github.com/ClosedXML/ClosedXML/files/1509637/UserDefinedFormulas.xlsx)

**Comment by igitur** [comment]
I assume you're referring to cells C6 to H14. Those cells just contain a formula. You can use the `cell.FormulaA1` to create that, as you did in the sample code above.

**Comment by barongnt** [comment]
Thanks, let me try that...

 *Baron Isfandiyar*

Senior Software Engineer / Architect: Sage Intelligence Product Engineering

*Sage Group*



Office: 031-537-7244 | @BaronGnt

Sage.com <https://www.sage.com/> | Twitter
<https://twitter.com/sagegroupplc>| Instagram
<https://www.instagram.com/sageofficial/> | YouTube
<https://www.youtube.com/user/SageGroupPlc>| LinkedIn
<https://www.linkedin.com/company/sage-software>| Facebook
<https://www.facebook.com/sage>| Community <http://sagecity.na.sage.com/>

Durban, South Africa

**Comment by barongnt** [comment]
Here is an example of what is happening now with the Excel Desktop.
As you can see, we have a user defined formula called "Client.Calulate" which is persisted in Excel together with its value which is "269342.88"

So I wanted to acheive the same thing with excel online.

![image](https://user-images.githubusercontent.com/5138048/33366706-bbdb6a6e-d4f4-11e7-8f61-28fab21d493b.png)

**Comment by igitur** [comment]
Ok, that's not currently possible in ClosedXML. If that element already exists in the Excel file, it will be populated in `XLCell.ValueCached` as a string, but setting it is not possible at the moment. Enabling a setter on that property opens a lot of other issues, e.g. should formula evaluation use the cached values or not. We're not at that stage yet. 

I propose that you could post-process the file with OpenXML to insert it.

**Comment by manojmathe85** [comment]
HI igitur

Does that mean ClosedXML dont support the formula caliculations as they cache values ?

i would share my ask, please help me if this Is supported in CloseXML
So my requirement is like this.

Row 1

Cell 1 : Captures Values 1 : Filled from code

Cell 2 : Captures values 2 : Filled from Code

Cell 3 : Formula calculation : Sum(cell 1:cell2) prepopulated forumla  ( i dont want to add this formula by code)

Cell 4: Drop Down with list of name defined in Sheet 1 of Taxonomy

Cell 5 : Formula to Auto Fill the location for he name selected in cell 4.

=IFNA(LOOKUP(D2,Taxonomy!$A$2:$A$5,Taxonomy!$B$2:$B$5),"")

Cell 6 : captures the text values : Filled from code 

I want to see data calculated in cell 3,5. please let me know if this possible to achieve ?

Thanks in Advance.
Manoj.
