### ISSUE TITLE
WorkBook.Save or SaveAs fail with "Range is Invalid" Exception

### ISSUE THREAD

**Issue by decrawford** [ClosedXML/ClosedXML#604]
[testfile.xlsx](https://github.com/ClosedXML/ClosedXML/files/1503192/testfile.xlsx)

## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.90.0

**What is the current behavior?**
When working with some workbooks, after manipulation of the content, Workbook.Save or SaveAs methods fail with "Range is Invalid" Exceptions with  StackTraces similar to the following:
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Range is invalid.
  Source=ClosedXML
  StackTrace:
   at ClosedXML.Excel.XLRangeAddress.get_FirstAddress()
   at ClosedXML.Excel.XLRangeAddress.ClosedXML.Excel.IXLRangeAddress.get_FirstAddress()
   at ClosedXML.Excel.XLWorkbook.GenerateWorkbookPartContent(WorkbookPart workbookPart, SaveContext context)
   at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file)
  

**What is the expected behavior or new feature?**

Successful save of file.

**Did this work in previous versions of our tool?  Which versions?**

Yes/v0.80

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
    class Program
    {
       static IXLCell GetColumnName(IXLTable table, string columnHeader)
        {
            var cell = table.HeadersRow().CellsUsed(c => c.Value.ToString() == columnHeader).FirstOrDefault();
            if (cell != null)
            {
                return cell;
            }
            return null;
        }
        static void Main(string[] args)
        {

            try
            {

                // now do the hard work walking through the Excel File

                var workbook = new XLWorkbook(@"c:\\temp\\testfile.xlsx");
                var worksheets = workbook.Worksheets;
                var worksheet = workbook.Worksheet(1);


                var range = worksheet.RangeUsed(); // the used range of the spreadsheet

                var theTable = range.AsTable();

                var headerrow = range.FirstRowUsed();

                foreach (var cell in headerrow.CellsUsed())
                {
                    cell.Value = cell.Value.ToString().ToUpper();
                }
                int theRow, theCol;
                // Check if the Target ID column is already in the spreadsheet, add it if it isn't
                if (GetColumnName(theTable, "TARGET ID") == null)
                {
                    range.InsertColumnsBefore(1);
                    theRow = range.RangeAddress.FirstAddress.RowNumber;
                    theCol = range.RangeAddress.FirstAddress.ColumnNumber - 1;
                    worksheet.Cell(range.RangeAddress.FirstAddress.RowNumber, range.RangeAddress.FirstAddress.ColumnNumber - 1).Value = "TARGET ID";
                    range = worksheet.RangeUsed();
                }

                // check if the Error Message column is already in the spreadsheet, add it if it isn't
                if (GetColumnName(theTable, "ERROR MESSAGE") == null)
                {
                    range.InsertColumnsAfter(1);
                    theRow = range.RangeAddress.FirstAddress.RowNumber;
                    theCol = range.RangeAddress.LastAddress.ColumnNumber;
                    worksheet.Cell(range.RangeAddress.FirstAddress.RowNumber, range.RangeAddress.LastAddress.ColumnNumber).Value = "ERROR MESSAGE";
                    range = worksheet.RangeUsed();
                }
                range = worksheet.RangeUsed();
                workbook.Save();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message + " " + ex.StackTrace);
            }
            Console.WriteLine("-----------------");
            Console.WriteLine("Press Any key to continue...");
            Console.ReadLine();
        }
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by decrawford** [comment]
This appears to be related to column shifting and hidden rows in the workbook I am using. I have not been able to nail down the specific location that is causing the failure but it appears to be somewhere in the code path of XLRange.WorksheetRangeShiftedColumns() and is apparently associated with the insertion of columns.

**Comment by igitur** [comment]
Your code sample seem to contains lots of statements not related to the problem. Can you please try reduce the code sample to a minimal version?

**Comment by decrawford** [comment]
See below. Essential characteristics with the sample file is to insert a column before the first column in the range, and set a cell value (column header), then save the file. 

  class Program
    {

         static void Main(string[] args)
        {

            try
            {

                int theRow, theCol;

                var workbook = new XLWorkbook(@"c:\\temp\\testfile.xlsx");
                var worksheet = workbook.Worksheet(1);


                var range = worksheet.RangeUsed(); // the used range of the spreadsheet


                // Insert a column before the range (new column should be column A / Column 1
                    range.InsertColumnsBefore(1);
                    theRow = range.RangeAddress.FirstAddress.RowNumber;
                    theCol = range.RangeAddress.FirstAddress.ColumnNumber - 1;
                    worksheet.Cell(theRow, theCol).Value = "New Colum Header";
                    range = worksheet.RangeUsed();
  
                workbook.Save();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message + " " + ex.StackTrace);
            }
            Console.WriteLine("-----------------");
            Console.WriteLine("Press Any key to continue...");
            Console.ReadLine();
        }
    }

**Comment by igitur** [comment]
Are you sure this used to work in `0.80.0` ?

**Comment by decrawford** [comment]
I used this same file previously using the same code, and 0.80.0 was the version I was using. I think the issue is related to shift columns right and hidden cells. I can probably work around it as I more or less control what is fed to the service that this code is in.

**Comment by igitur** [comment]
It's definitely a bug, but I can't find a previous version where this has worked. Easy workaround is to use `worksheet.Columns(1).InsertColumnsBefore()` instead of `range.InsertColumnsBefore()`.

**Comment by decrawford** [comment]
Will try that - was out of town on business all week and am just getting back to this project. Thanks.

**Comment by Pankraty** [comment]
Take a look on 3bb19c0e637e6faabbd56cba1b54b21e87358521. The test succeeds in first two cases ("A1:A4", "A1:B4") and fails in the last one ("A1:C4") with no apparent reason. Will try to figure it out later.
