### ISSUE TITLE
Problem with the conditional formatting

### ISSUE THREAD

**Issue by samorukov-s** [ClosedXML/ClosedXML#61]
Hi. 
I have a problem with the conditional formatting and Excel 2013. Reprosteps:
- Create a new .xlsx file using Excel 2013.
- Add to the first cell some number and then apply to this cell conditional formatting, for example color scales.
- Save this file. 
- Then I open this file using ClosedXML and save it without any changes. When I try to open this file using Excel 2013 I will get an error:
“Excel found unreadable content in 'FILENAME.xlsx'. Do you want to recover the contents of this workbook? If you trust the source of this workbook, click Yes.”

If I don’t apply conditional formatting to that cell, I won’t get an error after resaving file using ClosedXML.
Any suggestions?

PS: I validated the content of resaved .xlsx file using OpenXmlValidator.Validate() method and got this error:
![screenshot_1](https://cloud.githubusercontent.com/assets/22676679/19189366/b5b705d4-8ca8-11e6-984d-70a58d0ef497.png)

PPS: ConditionalFormatting node when file saved using Excel:
`<x:conditionalFormatting xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main" sqref="A1:C1">
      <x:cfRule type="colorScale" priority="1">
         <x:colorScale>
            <x:cfvo type="min" />
            <x:cfvo type="max" />
            <x:color rgb="FFFF7128" />
            <x:color rgb="FFFFEF9C" />
         </x:colorScale>
      </x:cfRule>
   </x:conditionalFormatting>`

ConditionalFormatting node when file resaved using ClosedXML:
`<x:conditionalFormatting xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main" sqref="A1:C1">
      <x:cfRule type="colorScale" priority="1">
         <x:colorScale />
      </x:cfRule>
   </x:conditionalFormatting>`

**Comment by igitur** [comment]
I tried your steps and I can't reproduce it exactly. I end up with a workbook that Excel can open without problems and no messages of unreadable content. However, the conditional formatting is partially lost.

Which versions of Excel and ClosedXML are you using?

**Comment by samorukov-s** [comment]
I am using ClosedXML of version 0.80.1 and Excel 2013.

**Comment by igitur** [comment]
Please attach the Excel file that you open with ClosedXML. Maybe the conditional formatting rules that I chose are a bit different.

**Comment by samorukov-s** [comment]
[original.xlsx](https://github.com/ClosedXML/ClosedXML/files/519774/original.xlsx)

**Comment by igitur** [comment]
Thanks. now I get the unreadable content error message. Will investigate.

**Comment by samorukov-s** [comment]
Thanks a lot!
