### ISSUE TITLE
Color sets in FontColor is not good

### ISSUE THREAD

**Issue by Tarboeuf** [ClosedXML/ClosedXML#621]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**

0.90.0

**What is the current behavior?**
When opening the given file 
[ARGB.xlsx](https://github.com/ClosedXML/ClosedXML/files/1543205/ARGB.xlsx)
the font color return White instead of Black

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
            var wb = new XLWorkbook(@"D:\temp\ARGB.xlsx");
            var cell = wb.Worksheet(1).Cell(1, 1);
            // cell.Style.Font.FontColor.Color should be 000
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Still trying to figure out what's going wrong, but I can see the the rest of column A is set to foreground color white. So somehow that color is inheriting to cell A1.

**Comment by Tarboeuf** [comment]
While looking for the origin of the issue, I see something weird :
Into the Dictionary `IndexedColors` of the class `XLColor` the ninth color : 
                            {8, FromHtml("#FF000000")},
But refering to excel ([documentation](http://dmcritchie.mvps.org/excel/colors.htm)) and my test in the [ExcelColor.xlsx](https://github.com/ClosedXML/ClosedXML/files/1547595/ExcelColor.xlsx) (color code are inverted)  it should have been #80000

**Comment by Tarboeuf** [comment]
I may find the issue,

When you have an indexed color for a column, excel does not use it for overiding cell values.
Look at this this macro on my file
![image](https://user-images.githubusercontent.com/5155564/33882404-4aec72aa-df38-11e7-877b-6799c8bb9707.png)

It seems that when you refer to a particular style Excel does not get the default column font style (for the cell A1)
The cell A2 refers to the same style has the column, and it takes the indexed color.

Don't know if I am clear and if it helps.

Whenever, thanks for your job

**Comment by igitur** [comment]
Do you perhaps have a link to any documentation about Excel not "inheriting" indexed colors?

**Comment by Tarboeuf** [comment]
Sorry, 

Unfortunately I don't know where to find any documentation of Excel it seems to be 
obscure.

**Comment by jahav** [comment]
The provided test case returns black color for font color - the actual color displayed in excel (previously white) since version 0.93.0. Considering the age and that test case is working, I am closing the issue.
