### ISSUE TITLE
Conditionalformatting - KeyNotFoundException

### ISSUE THREAD

**Issue by vknht** [ClosedXML/ClosedXML#622]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.90.0

**What is the current behavior?**

When Saving a xlsx-File with a conditionalformatting based on Date-Values, you get a KeyNotFoundException.

**What is the expected behavior or new feature?**

Not getting an Exception

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

**Code to reproduce problem:**
```c#
    public class Class1
    {
        public void LoadAndSaveXlsxFile(string file)
        {
            using (var fs = new FileStream(file, FileMode.Open, FileAccess.ReadWrite, FileShare.Read))
            {
                using (var wb = new XLWorkbook(fs))
                {
                    wb.Save();
                }
            }
        }
    }
```
- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)

[TestConditionalDateFormat.xlsx](https://github.com/ClosedXML/ClosedXML/files/1559561/TestConditionalDateFormat.xlsx)

Here is the Stacktrace, if it helps:
System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.

Result StackTrace:	
bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei ClosedXML.Excel.XLCFConverters.Convert(IXLConditionalFormat conditionalFormat, Int32 priority, SaveContext context) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\ConditionalFormats\Save\XLCFConverters.cs:Zeile 35.
   bei ClosedXML.Excel.XLWorkbook.GenerateWorksheetPartContent(WorksheetPart worksheetPart, XLWorksheet xlWorksheet, Boolean evaluateFormulae, SaveContext context) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:Zeile 4521.
   bei ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:Zeile 310.
   bei ClosedXML.Excel.XLWorkbook.CreatePackage(Stream stream, Boolean newStream, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:Zeile 136.
   bei ClosedXML.Excel.XLWorkbook.Save(SaveOptions options) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:Zeile 456.
   bei ClosedXML.Excel.XLWorkbook.Save(Boolean validate, Boolean evaluateFormulae) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:Zeile 440.
   bei ClosedXML.Excel.XLWorkbook.Save() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:Zeile 431.

**Comment by igitur** [comment]
Currently on holiday. Will look into it next year. Maybe try latest beta version from Nuget. But I doubt it will solve it.

**Comment by igitur** [comment]
I can't reproduce this with the latest codebase.

**Comment by vknht** [comment]
Hello,

sorry, my fault. The Save-Command gets rid of the Formattings and that is the file i Uploaded...

Here is a new one:
[TestConditionalDateFormat.xlsx](https://github.com/ClosedXML/ClosedXML/files/1600777/TestConditionalDateFormat.xlsx)

here is a Screenshot to set it up: (i hope you understand german :-/ )
![conditional_formatting_setup](https://user-images.githubusercontent.com/34534652/34526452-ca642548-f0a2-11e7-9371-41cb7b687736.png)

**Comment by igitur** [comment]
ClosedXML doesn't support that type of conditional format yet.
