### ISSUE TITLE
Hidden Columns are available while export

### ISSUE THREAD

**Issue by nachiaspac** [ClosedXML/ClosedXML#623]
Hi,

I am just exporting datatable to excel but found issue in extra columns are inside draggable borders. I wiant to know how to hide or disable this features.

using (XLWorkbook wb = new XLWorkbook())
    {
        wb.Worksheets.Add(dt, "Customers");
//theme set as none 
        wb.SaveAs(filelocation);
    }

Please find attached exported excel
[sample.xlsx](https://github.com/ClosedXML/ClosedXML/files/1561535/sample.xlsx)

**Comment by igitur** [comment]
I can't run your code sample.

**Comment by vbjay** [comment]
Hint. What is is still?

**Comment by nachiaspac** [comment]
Please use the below link for entire code block .

https://www.aspsnippets.com/Articles/Export-DataTable-to-Excel-using-OpenXml-in-Windows-Forms-WinForms-Applications-using-C-and-VBNet.aspx

My issue is I can`t hide the Border for all export.

public Form1()
{
    InitializeComponent();
    this.BindDataGridView();
}
 
private void BindDataGridView()
{
    DataTable dt = new DataTable();
    dt.Columns.AddRange(new DataColumn[3] { new DataColumn("Id", typeof(int)),
            new DataColumn("Name", typeof(string)),
            new DataColumn("Country",typeof(string)) });
    dt.Rows.Add(1, "John Hammond", "United States");
    dt.Rows.Add(2, "Mudassar Khan", "India");
    dt.Rows.Add(3, "Suzanne Mathews", "France");
    dt.Rows.Add(4, "Robert Schidner", "Russia");
    this.dataGridView1.DataSource = dt;
}
private void btnExportExcel_Click(object sender, EventArgs e)
{
    //Creating DataTable
    DataTable dt = new DataTable();
 
    //Adding the Columns
    foreach (DataGridViewColumn column in dataGridView1.Columns)
    {
        dt.Columns.Add(column.HeaderText, column.ValueType);
    }
 
    //Adding the Rows
    foreach (DataGridViewRow row in dataGridView1.Rows)
    {
        dt.Rows.Add();
        foreach (DataGridViewCell cell in row.Cells)
        {
            dt.Rows[dt.Rows.Count - 1][cell.ColumnIndex] = cell.Value.ToString();
        }
    }
 
    //Exporting to Excel
    string folderPath = "C:\\Excel\\";
    if (!Directory.Exists(folderPath))
    {
        Directory.CreateDirectory(folderPath);
    }
    using (XLWorkbook wb = new XLWorkbook())
    {
        wb.Worksheets.Add(dt, "Customers");
        wb.SaveAs(folderPath + "DataGridViewExport.xlsx");
    }
}

**Comment by igitur** [comment]
It's your responsibility to produce a MCVE. We don't have the time to decypher your code. Read https://stackoverflow.com/help/mcve and log a new issue when you have a MCVE.
