### ISSUE TITLE
Workbook.ToString() throws null reference exception

### ISSUE THREAD

**Issue by ndicenso** [ClosedXML/ClosedXML#624]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**

e.g. 0.90.0

**What is the current behavior?**
After creating a new WorkBook and called .ToString(), a null reference exception is thrown.

**What is the expected behavior or new feature?**
A valid type string or other should be returned

**Did this work in previous versions of our tool?  Which versions?**
Yes - 0.87.1

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
    var wb = new XLWorkbook();
    var ws = wb.AddWorksheet("Data");
    ws.FirstRow().Cell("A1").Value = "Test Data Cell Value";

    //This line below causes an exception
    //While I do not need to call ToString() explicitly, it is called via Moq implicitly during unit test 
    //execution
    var s = wb.ToString();
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by vbjay** [comment]
The question is, what is the string representation of a workbook?  The
name?  The name and stats(how many cells...)...?

**Comment by ndicenso** [comment]
By default, is should just return the type - something like "ClosedXml.Workbook." I think it is fine if it returns some more readable information as appropriate - if it can reliably do so safely, but it is a rare case that it should ever throw an exception. It appears that this method has only been overridden in recent updates and I suspect it is not intended to throw an exception under the current circumstance.

**Comment by igitur** [comment]
If you're using Moq, you should have sufficient knowledge to have a stab at this. Please submit a PR, which includes a unit test.

**Comment by ndicenso** [comment]
I don't mind taking a stab at resolving this issue. My first inclination would be to revert the previous change to simply allow the default behavior of .ToString(). It appears this regression was introduced on Sept 29 with commit "fd27a99e24aa070cce0ac076b2706786d8918415". The following code was added...
```c#
public override string ToString()
{
    return _originalFile ?? String.Format("XLWorkbook({0})", _originalStream.ToString());
}
```

Before I attempt a solution, can I ask what the design intent is here? Is there any significant value in the successful .ToString() result here?

**Comment by igitur** [comment]
It was just a naive change I made. I got tired of not seeing the class name when I have the workbook variable in my watch window. 

I think return an empty string for the string parameter if `_originalStream` is null.

In retrospect, I don't think a unit test is required for this.

**Comment by vbjay** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/enhancing-debugging-with-the-debugger-display-attributes
