### ISSUE TITLE
Negative Timespan Problem

### ISSUE THREAD

**Issue by tomaschl** [ClosedXML/ClosedXML#625]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.76.0

**What is the current behavior?**

I have a problem with exporting values of **TimeSpan datatype which are negative.**
For example, after

 ws.Cell(1,1).Value = new TimeSpan(0, -10, 0, 0);

the value -38:00:00 appears in that cell in sheet, although I expected -10:00:00.

This works by this way: 
 First parameter (days) of TimeSpan is decremented by 2 and the others are substracted from it. In this case:
 -2days + 10 hours = -38 hours.

**What is the expected behavior or new feature?**

Value -10:00:00 in Cell(1,1).

**Did this work in previous versions of our tool?  Which versions?**

I don't know.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Visual C#  .NET 4.6.01055

Code is placed in  public void ProcessRequest(HttpContext context) {} method.
        

**Code to reproduce problem:**
```c#
 using (XLWorkbook wb = new XLWorkbook())
                        {
                            wb.SetUse1904DateSystem(true);
                            var ws = wb.Worksheets.Add("SBIExport");
                            ws.Cell(1, 100).DataType = XLCellValues.TimeSpan;
                            ws.Cell(1,100).Value = new TimeSpan(0, -10, 0, 0);
                           
                            MemoryStream stream = GetStream(wb);
                            context.Response.Clear();
                            context.Response.Buffer = true;
                            context.Response.AddHeader("content-disposition", "attachment; filename=Export.xlsx");
                            context.Response.ContentType = "application/vnd.ms-excel";
                            context.Response.BinaryWrite(stream.ToArray());
                            context.Response.Flush(); 
                            context.Response.End();
                        }
 context.ApplicationInstance.CompleteRequest();
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by vbjay** [comment]
Check the formatting.

**Comment by igitur** [comment]
Your code sample contains ASP.NET stuff. So I can't run in a console application. Please fix.

**Comment by igitur** [comment]
Also upload a file that you created in normal Excel of what you want to see.

**Comment by igitur** [comment]
I'll reopen once you submit a sample file.
