### ISSUE TITLE
Excel found unreadable content - strip invalid XML characters?

### ISSUE THREAD

**Issue by gailshighsmith** [ClosedXML/ClosedXML#63]
Using a DataTable to build XLWorkbook and SaveAs MemoryStream.  
Code works fine on small data sets but receiving following error on large data sets.

"Excel found unreadable content in Filename.xlsx" Do you want to recover the contents of this workbook?

Am already stripping and replacing with "" space the following characters:
string r = "[\x00-\x08\x0B\x0C\x0E-\x1F\x26]";

Are there additional invalid XML characters I should be looking for and removing?
Thanks!

**Comment by igitur** [comment]
Would you mind grabbing the source and pulling in the commits from #62 ? I suspect it might give us more details about which characters are causing  the problem.

**Comment by gailshighsmith** [comment]
Using oWorkbook.SaveAs(memoryStream,true);

In the XLWorkdbook.cs SaveAs() 
CreatePackage() function call returning error:
"Input string was not in a correct format"

What to try now?

**Comment by igitur** [comment]
Do you have a stack trace of where that error occurs?

**Comment by gailshighsmith** [comment]
Using oWorkbook.SaveAs(memoryStream,true);

In the XLWorkdbook.cs SaveAs() 
CreatePackage() 
CreateParts(package);

CreateParts function processes 40 distinct rows before throwing error.  
Next line 117
---- if(validate) Validate(package); ---- this code never executes

**Comment by igitur** [comment]
I don't have much help other than to suggest that you try a brute force approach to narrow down the "illegal" character. You already know in which row it is. Now just to determine the column and then you're almost there. If the info isn't too sensitive, maybe you can dump it into another file in some other way and attach it here?

**Comment by igitur** [comment]
Try BCP to save the results to a file and inspect it manually. 

```
BCP "SELECT FileContent FROM table WHERE ID = 1" queryout "C:\file.txt" -T
share edit flag
```

**Comment by NickNack2020** [comment]
If some one wants to merge my pull request I opened back in June of 2015 this should solve the issue 

https://closedxml.codeplex.com/SourceControl/network/forks/NickNack2020/ClosedXml/contribution/8268 

Currently it encodes the invalid characters, but we could easily change it to strip them out and replace with spaces. @igitur what are your thoughts?

**Comment by igitur** [comment]
@gailshighsmith , if you pull the latest code from the `develop` branch, does it solve your problem?

**Comment by gailshighsmith** [comment]
igitur, I will pull the latest code soon.
First, the issue appears to be with negative numbers.  A call is made to a T-sql stored procedure that returns a "money" column value.  A C# SqlCommand executes the stored procedure and loads a "DataTable".  The "DataTable" is passed into the ClosedXML Export function which uses the oWorkBook.SaveAs(oMemoryStream) function to output the Excel file.  It does not seem to matter if I use the "wbSheet1.Column(21).Style.NumberFormat.NumberFormatId = 2;" format or not. 
If the result set contains a NEGATIVE number the Error occurs as previously described.
Is there a specific 'money' format I should be using? Thanks!

**Comment by gailshighsmith** [comment]
OK, here is the FIX!
We are using the most recent version of C# which has a data type "Money" just like T-sql. 
Excel currently does not recognize 'Money' data type.

To handle this issue I did a hard convert to numeric in the stored procedure on all money columns i.e.:
CONVERT(NUMERIC(18,2),ChargeAmount)) AS ChargeAmount

ClosedXML Export now runs correctly.
Thanks!

**Comment by igitur** [comment]
I'd still like to fix this without having to require the `CONVERT` command. What version of C# are you using?

**Comment by gailshighsmith** [comment]
Using Microsoft Visual C# 2015.

**Comment by igitur** [comment]
What version of the .NET framework are you using? v4.5.2? v4.6?

**Comment by gailshighsmith** [comment]
.NET 4.5

**Comment by NickNack2020** [comment]
Can you post an example?
