### ISSUE TITLE
Unhandled exception when saving (etc) after copying a cell containing a 'left pointing' formula

### ISSUE THREAD

**Issue by dhnc4u** [ClosedXML/ClosedXML#631]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
0.90

**What is the current behavior?**
An incorrect formula can be 'generated' in ClosedXML by copying a formula cell, with a left pointing reference, to a cell far enough to the left, making the resulting referenced cell to have a column number below 1.
As a result, an unhandled exception is thrown in GetColumnLetterFromNumber, which impacts a lot of functionality: saving is not possible, adjusttocontents is not working, etc.

**What is the expected behavior or new feature?**
The Excel GUI uses '=#REF!' to replace the invalid cell formula when doing a similar copy action.
What would be the best approach in ClosedXML ?

**Did this work in previous versions of our tool?  Which versions?**
Unknown

## Reproducibility
**Code to reproduce problem:**

```vb.net
        Dim theWorkbook = New Excel.XLWorkbook()
        Dim theSheet1 = theWorkbook.Worksheets.Add("Sheet1")
        theSheet1.Cell("A1").Value = "ValueA1"
        theSheet1.Cell("B2").FormulaA1 = "=A1"
        theSheet1.Range("A2").Value = theSheet1.Range("B2")
        theWorkbook.SaveAs(Path.Combine(Application.StartupPath, "issue7b_out.xlsx"), False, False)
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
I think the programmer should be checking for these cases and apply suitable logic.

**Comment by dhnc4u** [comment]
You could leave it up to the programmer, but in complex cases this adds quite some overhead to the application. 
The given example is extremely simplified, to make my point. 
In my situation, a large range of cells is copied to another worksheet and some cells contain rather complex formulas of which some 'point left'. The code threw an 'Index out of range' exception when calling AdjustToContents on the target range several code lines after copying the range. In took me a while to understand were that exception came from.

Don't you think it makes sense to (in)validate the formulas in ClosedXML instead and set the cell value to '#REF!' if needed ?

**Comment by vbjay** [comment]
I've been gnawing  on the idea that closedxml probably shouldn't have a
calcengine.  I know it's nice feature.  I think reading and writing excel
files is the main goal.  Excel can and does do automatic calculation or the
user can press f9.  I don't see the point of formula processing because
getting it to return "Excel" values is a tough goal.  Why can't we just
read in formulas and write out formulas.  If the value was stored from
excel, show in the value, otherwise return a calculation needed value.

**Comment by dhnc4u** [comment]
The Excel GUI actually still does 'something' when automatic formula calculation is set to manual...
You can try this:
Turn off automatic formula calculation
In cell B1, put text B1Value
In cell C1, put formula =B1 --> Enter will show the value in C1
Copy C1 to A1 --> A1 will show value B1Value, but formula =#REF!
Weird...

**Comment by igitur** [comment]
1. I admit that `AdjustToContents()` shouldn't choke on an issue like this. I'll fix this to swallow the error.
2. But I still feel that, as a programmer, I would prefer an exception to occur when I'm generating an invalid address. Mostly I don't want to generate any Excel files with invalid formulae, including formulae that contain #REF!'s. Keep in mind that the goal of ClosedXML is not to be a headless version of Excel, so don't expect the same behaviour. This is a programming API.

**Comment by dhnc4u** [comment]
Would below try/catch in XLCell GetFormula have side effects ?
```c#
// Check if the match is in between quotes
sb.Append(value.Substring(lastIndex, matchIndex - lastIndex));
try
{
sb.Append(conversionType == FormulaConversionType.A1ToR1C1
    ? GetR1C1Address(matchString, rowsToShift, columnsToShift)
    : GetA1Address(matchString, rowsToShift, columnsToShift));
}
catch
   {return "#REF!";}
}
```

**Comment by dhnc4u** [comment]
Thank you @igitur 
An exception is another option, as long as it is thrown at the correct time, i.e. when the cell value is set. That allows the calling code to take action.
Currently it is thrown when calling whatever function that is using GetFormula, which kinda masks the actual issue.

**Comment by igitur** [comment]
Yes, I agree with that.
