### ISSUE TITLE
an Idea - PDF

### ISSUE THREAD

**Issue by okarpov** [ClosedXML/ClosedXML#632]
I think it would be really great to have a functionality for PDF creating in this one library.

Thank you for your work!

**Comment by igitur** [comment]
Yes, great idea. Please submit your pull request when you're ready for the enhancements to be tested.

**Comment by okarpov** [comment]
Oh, sorry, I have no code for it, 
I meant it would be great if anyone would be able to create it and add it to this repo.
Just an idea, sorry.

**Comment by igitur** [comment]
It *is* a good. Maybe it should be a separate side-project and not included in the base ClosedXML. However, this is a community project, so if you want enhancements, it's up to you to contribute.

**Comment by vbjay** [comment]
Look at migradoc. http://pdfsharp.net
