### ISSUE TITLE
The sequence of "conditional formatting rules" has been changed after export Excel by using ClosedXML in my program

### ISSUE THREAD

**Issue by nathanQiu1** [ClosedXML/ClosedXML#637]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.89.0

**What is the current behavior?**

The sequence of "conditional formatting rules" has been changed after export Excel by using ClosedXML in my program

**What is the expected behavior or new feature?**

The sequence should not be changed in Excel template after export excel.

**Did this work in previous versions of our tool?  Which versions?**

 No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
      using (XLWorkbook workbook = new XLWorkbook(@"FAI.xlsm"))
   {
       workbook.Save();
   }
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Attach the file, please.

**Comment by nathanQiu1** [comment]
[test.zip](https://github.com/ClosedXML/ClosedXML/files/1605191/test.zip)
The blank part will change color.

**Comment by igitur** [comment]
Recently a change was introduced to try to consolidate conditional formats. For example in your file, the first 2 rules can be consolidated an applied to the `$O$4:$AR$8` range.

![image](https://user-images.githubusercontent.com/145854/34611100-c732cd9e-f22c-11e7-8138-0176255106a8.png)

However, there were some bugs, and I've tried to fix them. Does this attached file look correct to you? It's difficult for me to judge the logic behind the conditional formatting rules.

**Comment by nathanQiu1** [comment]
Thank you for your reply, in fact, the rules of logic is relatively simple, when the cell meets multiple conditional formats will be the first to apply the first, so the sort of conditional formatting is very important, but when the closexml open the file after the conditional formatting is wrong . . . .
waiting for your reply!

**Comment by igitur** [comment]
Please give me exact cells and exact cell values which illustrate the problem.

**Comment by nathanQiu1** [comment]
[test1.xlsx](https://github.com/ClosedXML/ClosedXML/files/1611399/test1.xlsx)

The rules that originally met the green color turned red after ClosedXML. The reason is that the sorting of the condition rules is wrong. Is there a better solution?
Thank you!

**Comment by nathanQiu1** [comment]
Dear Sir,

Do you fully understand what i mean? Do you need me to do more explanations on this?

**Comment by igitur** [comment]
Sorry, been on holiday. Will look at this soon again. Nothing more you need to explain until I ask again, thanks.

**Comment by igitur** [comment]
Please try the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/artifacts and let me know if it solves your problem.

**Comment by igitur** [comment]
Please try the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.91.764/artifacts and let me know if it solves your problem.

**Comment by nathanQiu1** [comment]
After a day of testing this version can solve the problem, I will continue to test if there is a problem will tell you in time.
Thank you again for providing this version!

**Comment by leezhenyu** [comment]
Hi, may I know latest version 0.91 fix this issue already? Or still pending. 

Thanks for the efforts from ClosedXML development team.

**Comment by nathanQiu1** [comment]
Hi team：
Sorry, did not reply in time, after this period of use, I found a small bug, when the set of rules for the color of "no color", by ClosedXML will change color "black", of course, this problem only in some special template Appears, so ClosedXML 0.91 basically solved my problem。
Thank you, ClosedXML development team!

**Comment by igitur** [comment]
@leezhenyu No, it hasn't been merged yet.

@nathanQiu1 I need a proper code sample, as always, please.

**Comment by nathanQiu1** [comment]
Hi  ClosedXML development team:
      When a template uses ClosedXML, "no color" cells change to "black."
      Attachments are templates.
      thank you!
[test2.xlsx](https://github.com/ClosedXML/ClosedXML/files/1706169/test2.xlsx)

**Comment by igitur** [comment]
@nathanQiu1  That's not related to conditional formatting. Please log a new, complete issue.

**Comment by igitur** [comment]
@nathanQiu1 Please try the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.92.819/artifacts

**Comment by nathanQiu1** [comment]
This version can solve the problem, thank you！

**Comment by nathanQiu1** [comment]
Hi ClosedXML development team:
     Sorry to bother you. The "conditional formatting rules" have changed again.
     When a template uses ClosedXML，The management rule changed at coordinates "L4",
     Is there a solution?    thank you! 


[test3.xlsx](https://github.com/ClosedXML/ClosedXML/files/1836834/test3.xlsx)

**Comment by igitur** [comment]
@nathanQiu1 How are you generating these files? The internals are massively complicated and the internal ordering of the conditional formats are very weird. Are you using a tool besides Excel?

**Comment by igitur** [comment]
I've merged the changes to fix your first few problems in this issue. Please create a new issue for `test3.xlsx`.
