### ISSUE TITLE
[Display(Name = "Example")] the function did not work fine.

### ISSUE THREAD

**Issue by FiddleLiu** [ClosedXML/ClosedXML#638]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

since v0.88.0 to v0.90.0

**What is the current behavior?**

When I use "InsertTable" function to insert an IEnumber collection that with Display Name,
the table's header did not use data annotation .

**What is the expected behavior or new feature?**

The export table header's name should rephrase to display name.

**Did this work in previous versions of our tool?  Which versions?**

Yes/ below v0.87.1

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
    public class DisplayNameTest
    {
        public void ExportFileWithDisplayName()
        {
            var wb = new XLWorkbook();
            var ws = wb.Worksheets.Add("test sheet");

            var list = new List<TestDisplayNameAttr>();
            list.Add(new TestDisplayNameAttr() { Name = "John", Age = 30, House = "On Elm St." });
            list.Add(new TestDisplayNameAttr() { Name = "Mary", Age = 15, House = "On Main St." });
            list.Add(new TestDisplayNameAttr() { Name = "Luis", Age = 21, House = "On 23rd St." });
            list.Add(new TestDisplayNameAttr() { Name = "Henry", Age = 45, House = "On 5th Ave." });

            ws.FirstCell().InsertTable(list);
            wb.SaveAs("DisplayNameTestTables.xlsx");
        }
    }
    class TestDisplayNameAttr
    {
        [Display(Name = "A")]
        public String Name { get; set; }
        [Display(Name = "B")]
        public Int32 Age { get; set; }
        [Display(Name = "C")]
        public String House { get; set; }
    }
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
![v0 87 1_displaynameworksfine](https://user-images.githubusercontent.com/32567321/34593936-f0b164d8-f208-11e7-9d60-ffe416a1ff00.png)
![v0 90_displaynamenotworking](https://user-images.githubusercontent.com/32567321/34593939-f51d647c-f208-11e7-8ac8-6364f5e71d4e.png)

**Comment by igitur** [comment]
You should now use the `XLColumn` attribute instead of `Display`. This was a breaking change some time ago.

**Comment by FiddleLiu** [comment]
I checked wiki and the document already update, you are so kind thank you.

**Comment by igitur** [comment]
So this issue can be closed?
