### ISSUE TITLE
Failed to "SaveAs" a file with a ReadOnly attribute

### ISSUE THREAD

**Issue by Pankraty** [ClosedXML/ClosedXML#640]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.90.0

**What is the current behavior?**

If open a file having a read-only attribute and then try to save it as a copy (with a different name) the operation fails (UserNotAuthorizedException). The copy of the original file is created though.

**What is the expected behavior or new feature?**

The file must be successfully saved at the specified location. It must have no ReadOnly attribute.

**Did this work in previous versions of our tool?  Which versions?**

No (as far as I am aware of)

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

A pull request with a test case will be provided soon.

**Code to reproduce problem:**
```c#
public void Main()
{
            string id = Guid.NewGuid().ToString();
            string original = string.Format("{0}original{1}.xlsx", _tempFolder, id);
            string copy = string.Format("{0}copy_of_{1}.xlsx", _tempFolder, id);

            using (var wb = new XLWorkbook())
            {
                var sheet = wb.Worksheets.Add("TestSheet");
                wb.SaveAs(original);
            }
            System.IO.File.SetAttributes(original, FileAttributes.ReadOnly);

            using (var wb = new XLWorkbook(original))
            {
                wb.SaveAs(copy); // This step fails
            }
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by vbjay** [comment]
Is the file path you are writing to, readonly?

**Comment by Pankraty** [comment]
No, the folder is accessible for writing, a specified file doesn't exist (before saving attempt). On saving, the original file is copied to the destination (along with its attributes), hence, it cannot be simply overwritten.
