### ISSUE TITLE
Setting Cell value to a number (double) larger than Decimal.Max throws an error

### ISSUE THREAD

**Issue by leomurillo** [ClosedXML/ClosedXML#642]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
0.90.0

**What is the current behavior?**
Throws exception "Value was either too large or too small for a Decimal."

**What is the expected behavior or new feature?**
Set cell value accordingly. Note Excel's Largest allowed positive number is 9.99999999999999E+307, slightly smaller than Double.Max.

**Did this work in previous versions of our tool?  Which versions?**
Don't know

## Reproducibility
Set column value as String to "9E+307" and all is good. But if you set cell value to a double = 9E+307 you get an exception. This is due to XLCell.SetValue function attempting to convert to Decimal, instead of converting to Double and checking if it's within Excel limits.
   at ClosedXML.Excel.XLCell.SetValue(Object value) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\Cells\XLCell.cs:line 1811

**Code to reproduce problem:**
```c#
        private const double MaxExcelNumber = 9.999E307;
        static void Main(string[] args)
        {
            var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("Sample Sheet");
            worksheet.Cell("A1").Value = Convert.ToString(MaxExcelNumber);
            worksheet.Cell("A1").Style.NumberFormat.Format = "0.0E+00";
            try
            {
                worksheet.Cell("A2").Value = MaxExcelNumber;
            }
            catch (Exception ex)
            {
                worksheet.Cell("A3").Value = ex.Message;
                worksheet.Cell("A4").Value = ex.StackTrace;
            }
            workbook.SaveAs("HelloWorld.xlsx");
        }
```
- [x] I attached a sample spreadsheet.  
[HelloWorld.xlsx](https://github.com/ClosedXML/ClosedXML/files/1609988/HelloWorld.xlsx)

**Comment by igitur** [comment]
Can you olese post the full stack trace? I suspect that this is a limitation of OpenXML

**Comment by leomurillo** [comment]
Here you go:
   at System.Decimal..ctor(Double value)
   at System.Double.System.IConvertible.ToDecimal(IFormatProvider provider)
   at System.Convert.ToDecimal(Object value)
   at ClosedXML.Excel.XLCell.SetValue(Object value) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\Cells\XLCell.cs:line 1811
   at ClosedXML.Excel.XLCell.set_Value(Object value) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\Cells\XLCell.cs:line 446
   at ClosedXMLBug.Program.Main(String[] args) in c:\users\leomu\source\repos\ClosedXMLBug\ClosedXMLBug\Program.cs:line 21
