### ISSUE TITLE
XLWorksheet.Protection.Objects property not persisting

### ISSUE THREAD

**Issue by ktrickey** [ClosedXML/ClosedXML#648]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.90

**What is the current behavior?**

When setting XLWorksheet.Protection.Objects the resulting saved spreadsheet does not have the Edit objects protection set.

**What is the expected behavior or new feature?**

The saved spreadsheet should have the Edit objects protection set when XLSheetProtection.Objects is set to true

**Did this work in previous versions of our tool?  Which versions?**

Unknown

## Reproducibility

**Code to reproduce problem:**
```c#
static void Main(string[] args)
{
	using (var book = new XLWorkbook())
	{
		var sheet = book.AddWorksheet("MySheet");

		var protection = sheet.Protect();
		protection.DeleteColumns = true;
		protection.Objects = true;

		using (var stream = new MemoryStream())
		{
			book.SaveAs(stream);

			using (var persistedBook = new XLWorkbook(stream))
			{

				var persistedprotection = persistedBook.Worksheets.Worksheet(1).Protection;

				Console.WriteLine(
					$"Deleted Columns - expected:{protection.DeleteColumns}, persisted:{persistedprotection.DeleteColumns}");
				Console.WriteLine($"Objects - expected:{protection.Objects}, persisted:{persistedprotection.Objects}");
				Console.ReadKey();
			}
		}
	}
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Fixing**
I've seen that the relevant protection saving and loading code for the Objects property is missing - I will raise a pull request.

**Comment by igitur** [comment]
Closed via #649
