### ISSUE TITLE
System.IndexOutOfRangeException when loading an xlsx with pivot table

### ISSUE THREAD

**Issue by kelleadr** [ClosedXML/ClosedXML#651]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.87.1
also tested with 0.90

**What is the current behavior?**

A crash happens if i load the attached file (direclty within XLWorkbook constructor)

**What is the expected behavior or new feature?**

At least it shall load the excel and ignore the invalid data if there are any (excel itself says everything is fine)

**Did this work in previous versions of our tool?  Which versions?**

Yes, different ones -> not related to this issue

## Reproducibility
We loaded the xlsx directly from a memory stream in our application:
using (var memoryStream = new MemoryStream(report))
var book = new XLWorkbook(memoryStream);

But it also happens if you just open it by filename: 
[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/1625805/test.xlsx)

**Code to reproduce problem:**
```c#
class Program
{
    static void Main(string[] args)
    {
        var book = new ClosedXML.Excel.XLWorkbook(@"test.xlsx");
    }
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
v0.90 should throw a meaningful `ArgumentException` with message `There isn't a worksheet named 'Pivot Data'`. Anyway, ClosedXML can't load the file because the pivot table refers to a non-existing sheet.

**Comment by kelleadr** [comment]
thanks for checking the issue. However I think it should be possible to load an excel with missing references. Excel can do that without any warning. If you reference a different workbook, it might work if it is next to the one you open. I need to update the workbook and ignore the "currently" missing reference. Do you see any chance I can do that?

**Comment by igitur** [comment]
Sorry, that's not possible in the foreseeable future. We don't exactly have an entire Office development team here.

**Comment by Pankraty** [comment]
I am reopening this since @BillyFromAHill has provided a fix.
