### ISSUE TITLE
Formulas Not caliculated until open is opened

### ISSUE THREAD

**Issue by manojmathe85** [ClosedXML/ClosedXML#653]
HI

i am facing issue with this " I have a formula with which is like this "IFNA(LOOKUP(L2, Taxonomy!$C$2:$C$23, Taxonomy!$B$2:$B$23),\"\")" , this depends on Colum L2 &  Sheet taxonomy which has all the data to be looked up for. Now the issue is the values gets caliculated when we open the file but i have a case where user will submit this file without even opening the file and the excelreader reads this cell value as empty.." is there any way we can evaluate the value of the formulas while  excel generation ??  "

In Line : 
I have some formulas prepopulated in my excel when the dependent cell values are populated the cell values which has the formulas doesnt get updated until i open the excel and save it" is there a way to fix this ??

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
0.91.0-beta2

**What is the current behavior?**
Formulas are calculated post opening the file and saving it, we want the formula ways to be prepoulated without having a dependency on openings & saving the file.

Complete this.

**What is the expected behavior or new feature?**
Formulas Values to be refreshed when the dependent cell values are populated.

**Did this work in previous versions of our tool?  Which versions?**
No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{

     Create("F:\\File1_Formula_Shared.xlsx", "F:\\File1_Formula_Shared_v1.xlsx");
     //When i read this file the formulas cell are read as empty.

    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
public static void Create(string temFilePath,String filePath)
        {
            var workbook = new XLWorkbook(temFilePath);
            var ws = workbook.Worksheets.LastOrDefault();


            ws.Cell(2, 2).Value = 2;
            ws.Cell(2, 3).Value = 3;
            ws.Cell(2, 5).Value = "Manoj";


            workbook.SaveAs(filePath);
            
        }

```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[File1_Formula_Shared.xlsx](https://github.com/ClosedXML/ClosedXML/files/1632902/File1_Formula_Shared.xlsx)

**Comment by igitur** [comment]
Use this overload:

`public void Save(Boolean validate, Boolean evaluate Formulae) `

**Comment by manojmathe85** [comment]
Thank you Somuch Francois.

That didnt help me, my excel template is protected and i upload the files
to azure blob do we have any dependency  with this ?

*Thanks*

*Manoj*

**Comment by igitur** [comment]
Sorry, I don't know what you mean.
