### ISSUE TITLE
Save file very very slow

### ISSUE THREAD

**Issue by ZhXueming** [ClosedXML/ClosedXML#654]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**
0.90

**What is the current behavior?**
I create a program has to output large excel file.
because of memory out of range. I slice it to many little files.
But even save 2000 rows to file, it is taking 2s.

Can anybody give me some advice?

**Comment by vbjay** [comment]
We have an issue template for a reason.
