### ISSUE TITLE
Can not delete picture

### ISSUE THREAD

**Issue by ZhXueming** [ClosedXML/ClosedXML#655]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**
0.90

**What is the current behavior?**

I load excel file and found the picture and delete it.
then save to file and reopen it.
but the picture even exist.

**Comment by vbjay** [comment]
We have an issue template for a reason.

**Comment by igitur** [comment]
Fixed in #674
