### ISSUE TITLE
Images in the Wiki pages are not displaying

### ISSUE THREAD

**Issue by liddictm** [ClosedXML/ClosedXML#672]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Comment by igitur** [comment]
Geez, they just disappeared.

**Comment by liddictm** [comment]
I was referring to them yesterday so this must have just happened within the last day.

**Comment by vbjay** [comment]
I'd raise an issue with GitHub if they don't fix it soon.

**Comment by igitur** [comment]
Oh, stupid me... many of the images were still hosted on Codeplex. Obviously those links don't work anymore. I got hold of the images in the archive from Codeplex, but it will take some time to fix. Unless someone else wants to do it. This is a non-code way for someone to contribute.

**Comment by Reivaj810** [comment]
Hi I can contribute with this issue,

**Comment by igitur** [comment]
Thanks, @Reivaj810 

You can send pull requests to https://github.com/ClosedXML/ClosedXML-wiki

The entire archive of the previous ClosedXML project, which includes the old wiki and its images, is available for download at http://closedxml.codeplex.com

I suspect one would be able to write a script to look for the image URIs in the current wiki and locate the images in the downloaded archive.

**Comment by igitur** [comment]
Wiki pages are now updated. Let me know if any images are still buggered.
