### ISSUE TITLE
It works on .Net Core 1.1 but not on Core 2.0. Any estimate when it will work with Core 2.0?

### ISSUE THREAD

**Issue by DMANCT** [ClosedXML/ClosedXML#683]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.87.1

**What is the current behavior?**

Complete this.

**What is the expected behavior or new feature?**

Complete this.

**Did this work in previous versions of our tool?  Which versions?**

Yes/No/v0.XX

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by vbjay** [comment]
See #101

**Comment by igitur** [comment]
If someone can show me a fast WeakEvent pattern on dotnet core, that would help.

**Comment by DMANCT** [comment]
Is it different on Core 1.1 vs Core 2.0. Your latest stable version 0.91.0 works perfect on Core 1.1.


________________________________

**Comment by igitur** [comment]
It's the first time that I hear reports that it works as is on Core 1.1. And I'm really surprised as there's a lot of stuff being used by ClosedXML (eg System.Drawing) that's not in Standard 2.0 even.

Can you provide a piece of code to illustrate?

**Comment by DMANCT** [comment]
Sorry my mistake. In my other project I use Core 1.1 and a full entity framework 4.6.


I don't do anything fancy, just convert a datatable to an excel and then return it

                var wbook = new ClosedXML.Excel.XLWorkbook();

                wbook.Worksheets.Add(groupsDataTable, "GroupTemplate");

                var memoryStream = new MemoryStream();

                wbook.SaveAs(memoryStream);

                //reset the position to the start of the stream
                memoryStream.Seek(0, SeekOrigin.Begin);

                return File(memoryStream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", groupTemplate.Name + ".xlsx");

It would be nice to use the same simple code in Core 2.0 without entity framework.

Tnx.
________________________________

**Comment by igitur** [comment]
You could achieve that by downloading the source, strip out the parts that are not supported by `netstandard2.0` and compile it.
