### ISSUE TITLE
percentage value and number datatype

### ISSUE THREAD

**Issue by Giois93** [ClosedXML/ClosedXML#687]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.87.1

**What is the current behavior?**

ClosedXML generate Exception trying to set Number DataType on percentage value.

**What is the expected behavior or new feature?**

Since MS Excel suggests Number DataType (and only recognize this) for percentage value, I should set it for a cell with percentage value.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

**Code to reproduce problem:**
```c#
public static void SetDataTypeForColumn(IXLCell cell)
{
    var cellValueStr = cell.Value.ToString();
    if (cellValueStr.EndsWith("%"))
    {
        cellValueStr = cellValueStr.Substring(0, cellValueStr.Length - 1);
    }

    double tmpDouble;
    if (double.TryParse(cellValueStr, NumberStyles.Number, CultureInfo.InvariantCulture, out tmpDouble))
    {
        cell.DataType = XLCellValues.Number;
    }
}
```

**Comment by igitur** [comment]
Can't reproduce, because you didn't attach test file or complete console application code sample.

But my guess is the cell's value is an actual string. In that case you should set the value to the parsed `tmpDouble` too.

**Comment by Giois93** [comment]
You did not get the point, I am trying to set a cell to numeric type as it should be (according to MS Excel or LibreOffice Calc), even if it's value is "[number]%" (number followed by "%").

See this pic:
![senza nome](https://user-images.githubusercontent.com/10637435/35966418-0c5c5ef2-0cbe-11e8-8061-fa3baeda24ae.png)

Maybe this is a missing feature rather than a bug, but if I try using a string cell value in other formulas I get errors since it must be a numeric type. 
In fact, a percentage value is and should be numeric type.

**Comment by igitur** [comment]
Attach sample file and code that I can run, as requested in the issue template.

**Comment by Giois93** [comment]
You just need to pick a cell with percentage or iterate over all cells and set its type with the code I attached.
Try to use this file
[Monitoring.xlsx](https://github.com/ClosedXML/ClosedXML/files/1706761/Monitoring.xlsx)

**Comment by Giois93** [comment]
I tried the actual version and this is what happens (same code):
- I try to set number datatype to cell containing "16%",
- cell value changes to 0.16 numeric value,
-  I expect 16%, although excel file has 0.16 value,

This is an improvement I suggest, because there is no way I can use a percentage value like 16% in formulas without converting it to 0.16.

**Comment by igitur** [comment]
Tey the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.92.820/artifacts

**Comment by Giois93** [comment]
Sorry I did not explain well, I have experienced in that exact version. 0.92.820
