### ISSUE TITLE
Cannot Set Header FontColor Of Table To Black

### ISSUE THREAD

**Issue by HumpaLumpa007** [ClosedXML/ClosedXML#689]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**

0.91.0

**What is the current behavior?**

I have some data which are displayed as a standard table. If I want to set the FontColor of the Table's Header to Black the FontColor is still white. If I set the color to almost black (`#FF010101` ) or some other color (e.g. `XLColor.Red`) it works as expected.

**What is the expected behavior or new feature?**

The FontColor of the Table's Header should be black.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

**Code to reproduce problem:**
```c#
class Data
{
  public int Property1 { get; set; }
  public int Property2 { get; set; }
  public int Property3 { get; set; }
  public int Property4 { get; set; }
  public int Property5 { get; set; }
}

class Program
{
  static List<Data> GenerateData()
  {
    List<Data> list = new List<Data>();
    Random r = new Random();
    for (int i = 0; i < 15; i++)
    {
      list.Add(new Data { Property1 = r.Next(0, 100), Property2 = r.Next(0, 100), Property3 = r.Next(0, 100), Property4 = r.Next(0, 100), Property5 = r.Next(0, 100) });
    }
    return list;
  }

  static void Main(string[] args)
  {
    var data = GenerateData();
    var typeAccessor = TypeAccessor.Create(typeof(Data));
    var path = System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "test.xlsx");

    using (var workbook = new XLWorkbook(XLEventTracking.Disabled))
    {
      using (var sheet = workbook.AddWorksheet("test"))
      {
        int row = 1;
        int column = 1;

        foreach (var member in typeAccessor.GetMembers())
        {
          sheet.Cell(row, column++).Value = member.Name;
        }
        row++;

        foreach (var item in data)
        {
          column = 1;
          foreach (var member in typeAccessor.GetMembers())
          {
            sheet.Cell(row, column++).Value = typeAccessor[item, member.Name];
          }
          row++;
        }

        using (var table = sheet.Range(1, 1, row - 1, column - 1).CreateTable())
        {
          using (var rangeRow = table.HeadersRow())
          {
            rangeRow.Style.Font.FontColor = XLColor.Black;  // doesn't work
            rangeRow.Style.Font.FontColor = XLColor.FromHtml("#FF010101");  // works
            rangeRow.Style.Fill.BackgroundColor = XLColor.NoColor;
          }
        }
      }
      workbook.SaveAs(path);
    }
  }
}
```

**Comment by igitur** [comment]
I can't reproduce this problem. Can you try with the latest CI build at https://ci.appveyor.com/project/Pyropace/ClosedXML/branch/develop/artifacts ?

**Comment by igitur** [comment]
Sidenote: you can significantly reduce your code by using the `InsertTable` method:

```c#
internal class Data
{
    public int Property1 { get; set; }
    public int Property2 { get; set; }
    public int Property3 { get; set; }
    public int Property4 { get; set; }
    public int Property5 { get; set; }
}

internal class Program
{
    private static List<Data> GenerateData()
    {
        List<Data> list = new List<Data>();
        Random r = new Random();
        for (int i = 0; i < 15; i++)
        {
            list.Add(new Data { Property1 = r.Next(0, 100), Property2 = r.Next(0, 100), Property3 = r.Next(0, 100), Property4 = r.Next(0, 100), Property5 = r.Next(0, 100) });
        }
        return list;
    }

    private static void Main(string[] args)
    {
        var data = GenerateData();
        var path = "test.xlsx";

        using (var workbook = new XLWorkbook(XLEventTracking.Disabled))
        {
            var table = workbook.AddWorksheet("Sheet1").FirstCell().InsertTable(data);

            using (var rangeRow = table.HeadersRow())
            {
                rangeRow.Style.Font.FontColor = XLColor.Blue;  
                rangeRow.Style.Fill.BackgroundColor = XLColor.NoColor;
            }

            workbook.SaveAs(path);
        }
    }
}
```

**Comment by HumpaLumpa007** [comment]
I still have the same problem, even with the latest CI build (see attached files).
Also tested this with Office 2010, 2013 and 2016 (mainly 2016) on different PCs, always the same behavior.

I'm using the "long" way because in the actual application the properties have to be exported in a special order and some may get concatenated with others (this structure is defined in an XML file). So I can't use ```InsertTable(...)``` function.

[test_FF010101.xlsx](https://github.com/ClosedXML/ClosedXML/files/1774395/test_FF010101.xlsx)
[test_Black.xlsx](https://github.com/ClosedXML/ClosedXML/files/1774396/test_Black.xlsx)

**Comment by igitur** [comment]
Ok, can you run my code sample as is and attach the output file that it generates?

**Comment by igitur** [comment]
PS: Thanks for the good code sample. It makes it a lot easier, even though I can't replicate the problem... yet.

**Comment by HumpaLumpa007** [comment]
Your sample: [test.xlsx](https://github.com/ClosedXML/ClosedXML/files/1774518/test.xlsx)

**Comment by HumpaLumpa007** [comment]
also tested with setting the ```FontColor = XLColor.Black```. Still same problem
[test_black.xlsx](https://github.com/ClosedXML/ClosedXML/files/1774525/test_black.xlsx)

**Comment by igitur** [comment]
If I open `test.xlsx` I see this:
![image](https://user-images.githubusercontent.com/145854/36893296-3264877e-1e10-11e8-9679-67eee31c487e.png)

**Comment by igitur** [comment]
Ah, but if I change it to `XLColor.Black`, I see this. This is obviously wrong. I'll look into it.

![image](https://user-images.githubusercontent.com/145854/36893379-7e02083c-1e10-11e8-9754-263c68403597.png)

**Comment by HumpaLumpa007** [comment]
Same thing for me (If I use your code sample).
![grafik](https://user-images.githubusercontent.com/5374005/36893381-1e31e54c-1e08-11e8-8367-210f0e2744e0.png)

and with the black FontColor:
![grafik1](https://user-images.githubusercontent.com/5374005/36893405-3d61cb12-1e08-11e8-935a-008c27c1ff14.png)

**Comment by igitur** [comment]
Hmm, I think this is an Excel bug! Open one of those files and try setting the colour manually to black. Don't use theme colours. Use actual RGB:

![image](https://user-images.githubusercontent.com/145854/36893470-d3d375d4-1e10-11e8-961d-1d3017d25ace.png)

If I do that, the text becomes transparent. What happens for you?

**Comment by HumpaLumpa007** [comment]
I have the exact same behaviour. 
Text getting transparent if I set the color to black via RGB

**Comment by igitur** [comment]
You could try `rangeRow.Style.Font.FontColor = XLColor.FromTheme(XLThemeColor.Text1);`.

**Comment by HumpaLumpa007** [comment]
This works, it sets the FontColor to Black (as expected).

**Comment by igitur** [comment]
Can this be closed?

**Comment by HumpaLumpa007** [comment]
Yes, it's not a bug in ClosedXML.
