### ISSUE TITLE
Brokens links in wiki

### ISSUE THREAD

**Issue by Reivaj810** [ClosedXML/ClosedXML#690]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [ x] Feature

**What is the current behavior?**
The wiki has all links brokens

**Did this work in previous versions of our tool?  Which versions?**
Yes

## Reproducibility
Just need see the wiki page, any post with images is broken :( 

**
![capture](https://user-images.githubusercontent.com/9388556/36052950-6cb2be3e-0db5-11e8-9a6a-00829a7b7428.PNG)

**Comment by vbjay** [comment]
Please search issues before posting. See #672.
