### ISSUE TITLE
Add worksheet from DataTable without SheetName

### ISSUE THREAD

**Issue by Giois93** [ClosedXML/ClosedXML#698]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.91.0

**What is the current behavior?**

I'm trying to add a worksheet by passing a DataTable to the following method:
```C#
IXLWorksheet Add(DataTable dataTable)
```

since I don't care about sheet name.

An exception is thrown saying "sheet name cannot be empty".

**What is the expected behavior or new feature?**

Since there is a method I can call without specify sheet name I expect a new sheet to be added with a default name ("sheet1", i suppose).

**Did this work in previous versions of our tool?  Which versions?**

Don't know

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

This feature is pretty helpful and widespread, 
e.g. [ClosedXML](https://joshclose.github.io/CsvHelper/writing#writing-a-single-record)

**Code to reproduce problem:**
```C#
public void WriteCollectionToExcelTable<T>(/*string sheetName, */params T[] elements)
{
    //creo una tabella da esportare
    var table = new DataTable();

    //prendo tutte le proprietà della classe e per ognuna creo una colonna nella tabella
    foreach (var p in (typeof(T).GetProperties()))
    {
        table.Columns.Add(p.Name, typeof(string));
    }

    //prendo tutti i testResultData e aggiungo una riga per ognuno con tutte le proprietà
    foreach (T trd in elements)
    {
        table.Rows.Add(trd.GetType().GetProperties().Select(p => p.GetValue(trd)).ToArray());
    }

    //creo un nuovo documento
    using (var workbook = new XLWorkbook())
    {
        //creo lo sheet
        var currSheet = workbook.Worksheets.Add(table/*, sheetName*/);

        //salvo il file
        if (workbook.Worksheets.Count > 0)
        {
            workbook.SaveAs(ReportFileXls);
        }
    }
}

```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Give your database a name in `DataTable.TableName`. That is used to create the sheet name.

**Comment by Giois93** [comment]
Ok, my bad. 

May I suggest the method not to throw exceptions in this case but handle this by using a default name?

**Comment by igitur** [comment]
I think it's best left to the user. I don't want to deal with the complication of checking whether the sheet already exists and trying to find another time not yet taken.
