### ISSUE TITLE
export a generics collection to Excel 

### ISSUE THREAD

**Issue by Giois93** [ClosedXML/ClosedXML#699]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [X] Feature

**Version of ClosedXML**

e.g. 0.91.0

**What is the current behavior?**
---

**What is the expected behavior or new feature?**
I would like to export a generics collection to Excel as in the code below.
The feature could accept a collection of objects, for every property of which it could add a column to a table in which every object rappresent a row (using properties values to fill columns).

**Did this work in previous versions of our tool?  Which versions?**
No, new feature

## Reproducibility
Code example for what I ask for
```c#
public void WriteCollectionToExcelTable<T>(/*string sheetName, */params T[] elements)
{
    //creo una tabella da esportare
    var table = new DataTable();

    //prendo tutte le proprietà della classe e per ognuna creo una colonna nella tabella
    foreach (var p in (typeof(T).GetProperties()))
    {
        table.Columns.Add(p.Name, typeof(string));
    }

    //prendo tutti i testResultData e aggiungo una riga per ognuno con tutte le proprietà
    foreach (T trd in elements)
    {
        table.Rows.Add(trd.GetType().GetProperties().Select(p => p.GetValue(trd)).ToArray());
    }

    //creo un nuovo documento
    using (var workbook = new XLWorkbook())
    {
        //creo lo sheet
        var currSheet = workbook.Worksheets.Add(table/*, sheetName*/);

        //salvo il file
        if (workbook.Worksheets.Count > 0)
        {
            workbook.SaveAs(ReportFileXls);
        }
    }
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Have a look at `IXLCell.InsertTable<T>(IEnumerable<T> data)`. It might do what you want to do.

**Comment by Giois93** [comment]
Thank you for your help.

Although, this approach need me to create a worksheet and select a cell, all things that can even be done automatically, so that i need to specify the source data only in order to abstract the process of writing data to the Excel file.

**Comment by igitur** [comment]
If you need that in ClosedXML, you're welcome to submit a PR.
