### ISSUE TITLE
Setting AutoFilter EqualTo on Date Column Doesn't Display Values When Spreadsheet Is Opened Until Filters Are Reapplied

### ISSUE THREAD

**Issue by MartynJones87** [ClosedXML/ClosedXML#701]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.91.0

**What is the current behavior?**

Applying an AutoFilter to a table, and setting filter values on columns which are Dates sets the filters as expected but when opening the spreadsheet, no data is shown until clicking the Sort & Filter -> Reapply button (Ctrl+Alt+L). 

**What is the expected behavior or new feature?**

Rows meeting the specified filter criteria should be shown when the spreadsheet is open, as happens when applying AutoFilter values to text columns.

**Did this work in previous versions of our tool?  Which versions?**

I don't know.

## Reproducibility

**Code to reproduce problem:**
```c#
static void Main(string[] args)
{
    var wb = new XLWorkbook();

    var list = new List<Person>();
    list.Add(new Person() { Name = "John", Age = 30, House = "On Elm St.", Birthday = new DateTime(2018, 02, 23), Salary = 1000.11 });
    list.Add(new Person() { Name = "Mary", Age = 15, House = "On Main St.", Birthday = new DateTime(2018, 02, 23), Salary = 2000.22 });
    list.Add(new Person() { Name = "Luis", Age = 21, House = "On Elm St.", Birthday = new DateTime(2018, 02, 22), Salary = 2000.22 });
    list.Add(new Person() { Name = "Henry", Age = 45, House = "On 5th Ave.", Birthday = new DateTime(2018, 02, 22), Salary = 1000.11 });

    var textFilterWorksheet = wb.Worksheets.Add("TextFieldFilter");
    var textFilterTable = textFilterWorksheet.Cell(1, 1).InsertTable(list.AsEnumerable());
    textFilterTable.SetAutoFilter().Column(1).EqualTo("On Elm St.");

    var dateFilterWorksheet = wb.Worksheets.Add("DateFieldFilter");
    var dateFilterTable = dateFilterWorksheet.Cell(1, 1).InsertTable(list.AsEnumerable());
    dateFilterTable.SetAutoFilter().Column(4).EqualTo("22/02/2018");
    // I have also tried the following line to set a filter and this doesn't work either
    // dateFilterTable.SetAutoFilter().Column(4).EqualTo(new DateTime(2018, 02, 22));

    var numericFilterWorksheet = wb.Worksheets.Add("NumericFieldFilter");
    var numericFilterTable = numericFilterWorksheet.Cell(1, 1).InsertTable(list.AsEnumerable());
    numericFilterTable.SetAutoFilter().Column(3).EqualTo(30);

    var currencyFilterWorksheet = wb.Worksheets.Add("CurrencyFieldFilter");
    var currencyFilterTable = currencyFilterWorksheet.Cell(1, 1).InsertTable(list.AsEnumerable());
    for (int i = 1; i < 5; i++)
    {
        currencyFilterWorksheet.Cell(i, 3).Style.NumberFormat.SetFormat("$#,##0.00");
    }
    currencyFilterTable.SetAutoFilter().Column(5).EqualTo(2000.22);

    wb.SaveAs("FieldFilter.xlsx");
}

class Person
{
    public String House { get; set; }
    public String Name { get; set; }
    public Int32 Age { get; set; }
    public DateTime Birthday { get; set; }
    public double Salary { get; set; }
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

The spreadsheet attached is the output of the supplied code.

You can see the TextFieldFilter worksheet is filtered as specified in the code and the data is visible as expected.

However, on the DateFieldFilter worksheet, the filter is applied, but, the data isn't shown until after clicking the Sort & Filter -> Reapply button (Ctrl+Alt+L).

[TextFieldFilter.xlsx](https://github.com/ClosedXML/ClosedXML/files/1751442/TextFieldFilter.xlsx)

**Comment by igitur** [comment]
Yes, currently it's not possible.

And there's no easy fix, because date filters work according to grouping. You can filter according to year, or to year and month, or year/month/day, etc. It's going to take a while to get a full solution to this.

**Comment by MartynJones87** [comment]
Hello, thank you for your quick reply.

In the particular use case I have, I want to set the filter to be one more specific year/month/day combinations.

Is there a possible workaround I can apply to get this case to work?

Thank you again so much for your help!

**Comment by igitur** [comment]
Didn't try it myself, but you can convert the entire column's data type to
XLDataType.Number and filter on new DateTime(2018, 2, 22).ToOADate() . That
should work. Then try setting the DataType back to DateTime and hopefully
the filter stays in place.

Francois Botha

**Comment by igitur** [comment]
This seems to work:

```c#
table.AutoFilter.Column(4).AddFilter(new DateTime(2018, 02, 23).ToString());
```

**Comment by igitur** [comment]
Try the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.92.838/artifacts

Here's a code sample of how to use date group filters:
```c#
using (var wb = new XLWorkbook())
{
    IXLWorksheet ws;

    #region Single Column Dates

    String singleColumnDates = "Single Column Dates";
    ws = wb.Worksheets.Add(singleColumnDates);

    // Add a bunch of numbers to filter
    ws.Cell("A1").SetValue("Dates")
                 .CellBelow().SetValue(new DateTime(2018, 1, 1).AddDays(2))
                 .CellBelow().SetValue(new DateTime(2018, 1, 1).AddDays(3))
                 .CellBelow().SetValue(new DateTime(2018, 1, 1).AddDays(3))
                 .CellBelow().SetValue(new DateTime(2018, 1, 1).AddDays(5))
                 .CellBelow().SetValue(new DateTime(2018, 1, 1).AddDays(1))
                 .CellBelow().SetValue(new DateTime(2018, 1, 1).AddDays(4));

    ws.Column(1).Style.NumberFormat.Format = "d MMMM yyyy";

    // Add filters
    ws.RangeUsed().SetAutoFilter().Column(1).AddDateGroupFilter(new DateTime(2018, 1, 1).AddDays(3), XLDateTimeGrouping.Day);

    // Sort the filtered list
    ws.AutoFilter.Sort(1);

    #endregion Single Column Dates

    ws.Columns().AdjustToContents();
    wb.SaveAs(filePath);
}

```

**Comment by MartynJones87** [comment]
Hello @igitur 

Wow! This is amazing. Thank you so much for your time.

I've just tried the custom build you linked to and it works perfectly.

Thank you again!
