### ISSUE TITLE
Unable to use rich text in a range

### ISSUE THREAD

**Issue by jatinkumar762** [ClosedXML/ClosedXML#702]
## I want to use rich text in a range like we use in cell
But there is no option available to use it in range.
![capture](https://user-images.githubusercontent.com/9286962/36594002-5bddc294-18c2-11e8-9b60-b42956fc4e30.PNG)

**Comment by igitur** [comment]
Explain more.

**Comment by jatinkumar762** [comment]
For more reference, you can refer the below link -
[https://github.com/ClosedXML/ClosedXML/wiki/Using-Rich-Text](url) 
you can see from above link we can give rich text in a single cell but can't in range.

There is an alternate way to do this is that first give value to a cell then merge. For more details, you can check below link -
[https://stackoverflow.com/questions/48947623/c-sharp-closedxml-rich-text-implement-in-range-not-in-cell](url)

**Comment by igitur** [comment]
Are you talking about a range or merged cells? Those 2 things are not the same.

**Comment by igitur** [comment]
Try to provide a full code sample (as explained in the issue template) of what you want to do.

**Comment by igitur** [comment]
I'll reopen when you post a proper code sample.
