### ISSUE TITLE
IXLTable.XLSortOrder only sorts in Ascending order

### ISSUE THREAD

**Issue by Dlockhart104** [ClosedXML/ClosedXML#705]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

91.0.0

**What is the current behavior?**

XLSortOrder.Descending sorts a table in Ascending order. 

**What is the expected behavior or new feature?**

Sort a table in Descending order

**Did this work in previous versions of our tool?  Which versions?**

Not in version 90.0.0 or 91.0.0

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**

https://hastebin.com/exayoxawac.vbs

VB

```vb
 Private Sub SortExcel()
     
        XLTemplateFilePath = "Template file path"
        newXLFilePath = "your file path"

        ClanUpdateFilePath.Add(newXLFilePath)

        ' Open the document for editing.
        Dim wb As New XLWorkbook
        wb = XLWorkbook.OpenFromTemplate(XLTemplateFilePath)
        wb.SaveAs(newXLFilePath)

        Dim ws As IXLWorksheet

        ws = wb.Worksheet("Template Sheet Name")
        Dim wsIsAvailable As Boolean = wb.TryGetWorksheet(ws.Name, ws)
        'ws = wb.Worksheets.Add(1)

        If wsIsAvailable Then
            ws.Name = "New Sheet Name"

            With ws

                Dim Tbl As IXLTable = ws.Table(0)
                Tbl.Sort("Points", sortOrder:=XLSortOrder.Descending, matchCase:=False, ignoreBlanks:=True)

            End With
        End If

        wb.Save()

    End Sub
```
- [x ] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Sleeping Giant Stats 02-26-2018 234618.xlsx](https://github.com/ClosedXML/ClosedXML/files/1760676/Sleeping.Giant.Stats.02-26-2018.234618.xlsx)

**Comment by Dlockhart104** [comment]
My first issue ever on GitHub. Sorry if I did anything wrong. I am a relatively new programmer as well, so I probably have some silly code. Bare with me.

**Comment by Dlockhart104** [comment]
Am I able to look at the source code and try to determine a fix? I realize my method is written in VB and that it is not the code of choice. I'd be happy to look at the C# source and submit a pull request if I find the fix.

**Comment by Pankraty** [comment]
> Am I able to look at the source code and try to...

Of course you are, that's the idea of Open Source. 

The easiest way to have a copy of source code is to download it from he Code page, but to be able to propose a pull request you will have to deal with Git tools. Are you familiar with it or you need an assistance with this?

**Comment by igitur** [comment]
I can reproduce the issue. I'll look into it.

**Comment by igitur** [comment]
I found the bug and will fix it. As a temporary workaround, use this syntax:
```vb
 Tbl.Sort("Points DESC", matchCase:=False, ignoreBlanks:=True)
```

**Comment by Dlockhart104** [comment]
So i really did find a bug? I was thinking I just had some silly syntax. Thanks for the workaround!

**Comment by igitur** [comment]
Haha, yes, you really did find a bug. When you're a bit more comfortable with Github, you could try fixing the next bug and submitting a pull request. Open source projects are everyone's responsibility.

**Comment by vbjay** [comment]
Funny way of looking at it.


This is a story about four people named Everybody, Somebody, Anybody, and
Nobody. There was a bug to be fixed and Everybody was asked to do it.
Everybody was sure Somebody would do it. Anybody could have done it, but
Nobody did it. Somebody got angry about that, because it was Everybody's
job. Everybody thought Anybody could do it but Nobody realized that
Everybody wouldn't do it. It ended up that Everybody blamed Somebody when
Nobody did what Anybody could have done.
