### ISSUE TITLE
Poor performance of TableCellType() method

### ISSUE THREAD

**Issue by Pankraty** [ClosedXML/ClosedXML#714]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Enchancement

**Version of ClosedXML**

Current develop

**What is the current behavior?**

During profiling, I noticed that line ```else if (xlCell.TableCellType() == XLTableCellType.Total)``` called for each cell when the workbook costs about 2 seconds from overal 7. 

**What is the expected behavior or new feature?**

The more efficient way of determining cell type should be used. 

----
I create this issue to go back to it when I have time.

**Comment by igitur** [comment]
Yeah, I coded that part in a real rush.
