### ISSUE TITLE
Inserting a column on a sheet with conditional formats works slow

### ISSUE THREAD

**Issue by Pankraty** [ClosedXML/ClosedXML#719]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.92.0 (current develop)

**What is the current behavior?**

As @Laurakwakwak has reported, ClosedXML causes OutOfMemoryException on attempts to insert a column. The issue is caused by conditional formats since without them adding a column takes 0.1 sec, but when they are presented is takes a minute and 2GB of RAM to add a single column. If columns are added in a loop the OutOfMemory is easily reached.

**What is the expected behavior or new feature?**

The new column should be inserted after a specified one in a reasonable time, no matter if there are conditional formats or not.

**Did this work in previous versions of our tool?  Which versions?**

No information

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
            using (var wb = new XLWorkbook(fileName))
            {
                var ws = wb.Worksheets.First();
                ws.Column(4).InsertColumnsAfter(1); // <-- hangs for a minute or until OutOfMemory fired
            }
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[sample_719.xlsx](https://github.com/ClosedXML/ClosedXML/files/1788898/sample_715.xlsx)

**Comment by Laurakwakwak** [comment]
Thanks for openning a new issue

My problem is solved, I have removed all data validation and conditional format rules in my template, everything works well !
Effectively the problem was in the conditional format rules

Thanks to Pankraty ! Yaaay  :)
