### ISSUE TITLE
Vlookup using wrong row numbers

### ISSUE THREAD

**Issue by LangGat** [ClosedXML/ClosedXML#72]
Hi Guys, I have run across a little bug in the VLOOKUP in Lookup.cs. 
The code 
r.RowNumber()
should be
r.RowNumber()-range.FirstRow().RowNumber()+1
?

```
        IXLRangeRow matching_row;
        matching_row = range.FindRow(r => new Expression(r.Cell(1).Value).CompareTo(lookup_value) == 0);
        if (range_lookup && matching_row == null)
        {
            matching_row = range.FindRow(r =>
            {
                if (r.RowNumber()-range.FirstRow().RowNumber()+1 < range.RowsUsed().Count() &&
                    new Expression(r.Cell(1).Value).CompareTo(lookup_value) <= 0 && 
                    new Expression(r.RowBelow().Cell(1).Value).CompareTo(lookup_value) > 0)
                    return true;
                else if (r.RowNumber()-range.FirstRow().RowNumber()+1 == range.RowsUsed().Count() &&
                    new Expression(r.Cell(1).Value).CompareTo(lookup_value) <= 0)
                    return true;
                else
                    return false;
            });
        }
```

Please verify that I am not (completely) crazy?
Thanks!

**Comment by igitur** [comment]
You might be right. I added the `VLOOKUP` and `HLOOKUP` functions only recently. It looks like the lookup table is not at `A1` on the worksheet, am I right?

**Comment by LangGat** [comment]
Hi igitur,

Dankie!

That is correct. I use the cell value VLOOKUP(C9,Factors!B7:D15,3,TRUE)
So it goes from B7 to B9, currently, and returns line number 9 as the highest possible lookup with the original implementation.

The results seem correct with my changes. This could also happen in HLOOKUP, but I do not call that function currently.

Another possible issue is the range lookup code, where the  (bool)(p[3]); throws an exception when I call it when the p[3] does not exist. i.e. VLOOKUP(C9,Factors!B7:D15,3)
(I have had issues like this in FORTRAN with Intel compilers before, where the compiler sends both evaluations to the CPU at the same time and then the second causes a fault as it does not exist.)

            bool range_lookup;
            if (p.Count < 4)
                range_lookup = true;
            else
                range_lookup = (bool)(p[3]);

**Comment by igitur** [comment]
Mind attaching the workbook if it doesn't contain sensitive info? I'd like to add it as a test case. En plesier. ;)

**Comment by LangGat** [comment]
[TestExample.xlsx](https://github.com/ClosedXML/ClosedXML/files/535865/TestExample.xlsx)
I have simplified the file and removed unnecessary information. Please let me know if you have any problems with this file.
Thanks!
