### ISSUE TITLE
XLPicturePlacement.MoveAndSize Fail

### ISSUE THREAD

**Issue by gdlfmaci** [ClosedXML/ClosedXML#720]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
e.g. 0.91.0

**What is the current behavior?**
Problems to save workbook when change the property XLPicturePlacement.Move to XLPicturePlacement.MoveAndSize. 

**What is the expected behavior or new feature?**
I need that image move and size according to cell.

**Did this work in previous versions of our tool?  Which versions?**

Yes/No/v0.XX

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
 [HttpGet]
        public FileResult Download(string register, string product, string partnumber, string customer, string supplier, string site, string building)
        {
              ......
               .....
               .....
            using (XLWorkbook wb = new XLWorkbook())
            {
                IXLWorksheet sheet = wb.Worksheets.Add("Sheet1");
                 foreach (DataColumn data_column in table.Columns)
                    {
                           IXLPicture pic_image = sheet.AddPicture(picture_stream);
                            pic_image.Placement = XLPicturePlacement.MoveAndSize;
                            pic_image.MoveTo(address);
                }
                     
 using (MemoryStream stream = new MemoryStream())
                {
                      wb.SaveAs(stream);
                      return File(stream.ToArray(), "application/vnd.openxmlformats officedocument.spreadsheetml.sheet", "MasterList_Report.xlsx");
                }
            }
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
I can't run your code. Read the instructions and try again.
