### ISSUE TITLE
DocumentFormat.OpenXml nuget dependency

### ISSUE THREAD

**Issue by dkabracadabra** [ClosedXML/ClosedXML#73]
Please consider switching from DocumentFormat.OpenXml to OpenXMLSDK-MOT package.
The second one is official and evolving.

**Comment by igitur** [comment]
What would be the benefit to ClosedXML?

**Comment by igitur** [comment]
I also see that the OpenXMLSDK-MOT package requires at least .NET4.5. Currently we're doing 2 builds in ClosedXML: one for .NET3.5 and one for .NET4.0. Neither of those build if I reference that package.

We could possible do a third separate build for .NET4.5+, but that's going to be a bit more work.

**Comment by igitur** [comment]
Continuing this at #225

**Comment by igitur** [comment]
Solved at #292
