### ISSUE TITLE
How to Read an Excel File with Merged Cells to an Array 

### ISSUE THREAD

**Issue by alainparsons** [ClosedXML/ClosedXML#733]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
Neither - It's a question

**Version of ClosedXML**
4.030319

Francois Botha asked me to place this question here for community benefit.

I need to read an excel file into a multi-dimensional array.  I will not know the number of columns or rows before doing this.  I do know, the excel file will contain merged cells. 

A sample image of data that I could need to read in:
![image](https://user-images.githubusercontent.com/37384225/37430269-07bb7c7a-27a8-11e8-88ff-6fa9633b1c8e.png)

I can add the values to a list but this is not helpful.  I would like to put this data in an array[3][10].  Any help would be greatly appreciated.  Thank you.  I'm assuming there's a way to get an array to look like this:

Hello Class                       |||   (Empty)     |||   (Empty)
Major                               |||    Name       |||   GPA
Computer Science           |||    Alison       |||   4.0
(Empty)                            |||    Celeste     |||   3.9
(Empty)                            |||    Jules         |||   3.8
(Empty)                            |||    Arthur      |||   3.7
Computer Engineering    |||    Armand   |||    3.7
(Empty)                            |||    Hugo       |||    3.8
(Empty)                            |||    Darcy       |||    3.9
Electrical Engineering      |||    Estelle      |||    4.0  

```c#
public void Main()

{
List<string> list = new List<string>();
var workbook = new XLWorkbook(filePath);

            foreach (var worksheet in workbook.Worksheets)
            {
                foreach (var row in worksheet.RowsUsed())
                {
                    foreach (var cell in row.CellsUsed())
                    {
                        asRangeList.Add(cell.AsRange().RangeAddress.ToString());
                        list.Add(cell.Value.ToString());
                    }

                }
            }

}
```

**Comment by igitur** [comment]
Why don't you know the number of columns in advance? How can there be more columns?

**Comment by alainparsons** [comment]
It can be variable.

**Comment by igitur** [comment]
Can you post a screenshot, like before, of a case with more columns. I want to see how it affects the merged cells.

**Comment by alainparsons** [comment]
It is possible a file may look like this as well.  Or any number of added columns (or even merged cells/rows).  Often the professors test us vs unknown but likely scenarios to see if our code still works.

Thank you!


![untitled](https://user-images.githubusercontent.com/37384225/37614268-b0f6ad6a-2b80-11e8-90fc-55c37e583c6e.jpg)

**Comment by igitur** [comment]
OK, so the merged cells will appear only in column A? Not in any other column?

**Comment by alainparsons** [comment]
Yes.

**Comment by igitur** [comment]
Here's a code sample of how I would have read the data. I would not have used jagged arrays, but rather a list of dictionaries. See whether that suits your needs.

```c#
using (var wb = new XLWorkbook("test.xlsx"))
{
    var ws = wb.Worksheets.First();

    var headers = ws.Row(2).CellsUsed().Select(c => c.GetString()).ToList();

    var results = new List<IDictionary<string, object>>();

    foreach (var row in ws.RowsUsed(r => r.RowNumber() > 2))
    {
        var item = new Dictionary<string, object>();

        for (var i = 1; i <= headers.Count; i++)
        {
            var c = row.Cell(i);

            object value;
            if (c.IsMerged())
            {
                var valueCell = ws.MergedRanges.FirstOrDefault(r => r.Contains(c)).FirstCell();
                value = valueCell.Value;
            }
            else
                value = c.Value;

            item.Add(headers[i - 1], value);
        }

        results.Add(item);
    }


    //// 


    foreach (var item in results)
    {
        foreach (var key in item.Keys)
            Console.WriteLine($"{key} = {item[key]}");

        Console.WriteLine();
    }
}
```

I admit the handling of merged cells could be more elegant, so I'll look into adding some helper functions.

**Comment by alainparsons** [comment]
Thank you so very much.  Elegant is not my expertise. Yet.  I'm getting better though!

**Comment by ricardodemauro** [comment]
> Here's a code sample of how I would have read the data. I would not have used jagged arrays, but rather a list of dictionaries. See whether that suits your needs.
> 
> ```cs
> using (var wb = new XLWorkbook("test.xlsx"))
> {
>     var ws = wb.Worksheets.First();
> 
>     var headers = ws.Row(2).CellsUsed().Select(c => c.GetString()).ToList();
> 
>     var results = new List<IDictionary<string, object>>();
> 
>     foreach (var row in ws.RowsUsed(r => r.RowNumber() > 2))
>     {
>         var item = new Dictionary<string, object>();
> 
>         for (var i = 1; i <= headers.Count; i++)
>         {
>             var c = row.Cell(i);
> 
>             object value;
>             if (c.IsMerged())
>             {
>                 var valueCell = ws.MergedRanges.FirstOrDefault(r => r.Contains(c)).FirstCell();
>                 value = valueCell.Value;
>             }
>             else
>                 value = c.Value;
> 
>             item.Add(headers[i - 1], value);
>         }
> 
>         results.Add(item);
>     }
> 
> 
>     //// 
> 
> 
>     foreach (var item in results)
>     {
>         foreach (var key in item.Keys)
>             Console.WriteLine($"{key} = {item[key]}");
> 
>         Console.WriteLine();
>     }
> }
> ```
> 
> I admit the handling of merged cells could be more elegant, so I'll look into adding some helper functions.

Exactly what I was looking for. thank you
