### ISSUE TITLE
SUMIFS fails at valid formula

### ISSUE THREAD

**Issue by Pankraty** [ClosedXML/ClosedXML#734]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

Current develop

**What is the current behavior?**

The formula that works fine in Excel throws NullReferenceException during evaluation in ClosedXML

**What is the expected behavior or new feature?**

Return the correct result

**Did this work in previous versions of our tool?  Which versions?**

No information

## Reproducibility

**Code to reproduce problem:**
```c#
        // put this into StatisticalTests
        [TestCase("SUMIFS(H:H, G:G, 50, I:I, \">900\")", 19.99d)]
        public void SumIfsMultipleCriteriaTest(string formulaA1, double expectedResult)
        {
            using (var wb = SetupWorkbook())
            {
                var ws = wb.Worksheets.First();

                var actualResult = (double)ws.Evaluate(formulaA1);

                Assert.AreEqual(expectedResult, actualResult, tolerance);
            }
        }
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[sample_734.xlsx](https://github.com/ClosedXML/ClosedXML/files/1814209/sample_734.xlsx)

**Comment by igitur** [comment]
`SetupWorkbook()` ?

**Comment by igitur** [comment]
Oh, found it in `LookupTests`.

**Comment by Pankraty** [comment]
I used ```StatisticalTests```, but they seem the same

**Comment by igitur** [comment]
Found the bug. The current `SumIfs_ReturnsCorrectValues_ReferenceExampleFromMicrosoft` test never had an assert!
