### ISSUE TITLE
Invalid data after writing to the cell

### ISSUE THREAD

**Issue by milovidov983** [ClosedXML/ClosedXML#737]
## Read and complete the full issue template

- [x] Bug
- [ ] Feature

e.g. 0.91

**What is the current behavior?**

### Invalid data after writing to the cell:
I'm trying to write a value to cell "10.1", but after writing in the cell, I get the value: "43110"

**What is the expected behavior or new feature?**

Complete this.

**Did this work in previous versions of our tool?  Which versions?**

I dont know

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
    class Program
    {
        static void Main( string[] args )
        {
            var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add( "Sample Sheet" );
            worksheet.Cell( "A1" ).Value = "10,1";
            worksheet.Cell( "A1" ).DataType = XLDataType.Text;

            string testValue = worksheet.Cell( "A1" ).Value.ToString();
            Console.WriteLine( testValue );

            workbook.SaveAs( "testSheet.xlsx" );

            Console.ReadKey();
        }
    }
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
ClosedXML is recognizing the string as a valid date. I'm guessing that your regional date settings allow `.` or `,` as a date separator. If you're sure you want to set the value as data type text, you can prepend the value with `'`.

i.e. 
```c#
 worksheet.Cell( "A1" ).Value = "'10,1";
```

More info about this at https://github.com/ClosedXML/ClosedXML/wiki/Cell-Values

**Comment by milovidov983** [comment]
@igitur Yes it solved my problem, thanks

**Comment by VBWebprofi** [comment]
In my mind codelines

`worksheet.Cell( "A1" ).Value = "10,1"``
`worksheet.Cell( "A1" ).DataType = XLDataType.Text;`

had to be changed in order as prevent interpretation of decimal value for a type. But we observed it's alo not doing right as XML states no Text type (numFmtId="49").
