### ISSUE TITLE
Error while Saving a file that contains GrayScaleColor conditionnal formatting with "Cannot convert theme color to Color" exception

### ISSUE THREAD

**Issue by Tarboeuf** [ClosedXML/ClosedXML#738]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**

e.g. 0.91.0

**What is the current behavior?**

ClosedXml crashes on an InvalidOperationException : "Cannot convert theme color to Color."

**Did this work in previous versions of our tool?  Which versions?**

I don't think so

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
            using (var wb = new XLWorkbook(@"D:\temp\test.xlsx"))
            {
               wb.SaveAs(@"D:\temp\test2.xlsx");
            }
}
```
- [x] I attached a sample spreadsheet.
[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/1815555/test.xlsx)

**Comment by igitur** [comment]
Please try the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.92.907/artifacts (once it's finished building)

**Comment by Tarboeuf** [comment]
That's perfect !
Thanks
