### ISSUE TITLE
First or Header row is autostyled and has filter on

### ISSUE THREAD

**Issue by mandeeplaha** [ClosedXML/ClosedXML#743]
Everytime when create a excel workbook, the First or Header row is autostyled and has filter on.

I tried several ways but not able to turn it off.

**Comment by Pankraty** [comment]
>I tried several ways

Could you please provide sample code to reproduce the issue?

**Comment by mandeeplaha** [comment]
try
            {
                string FileName = "D:\\Employee.xlsx";
                string SubDepartment = "IT, HR, JAVA";
                using (XLWorkbook wb = new XLWorkbook(FileName))
                {
                    string[] strArray = SubDepartment.Split(',');
                    foreach (string department in strArray)
                    {
                        SqlConnection con = new SqlConnection("server=(local);database=EmployeeDB;integrated security=SSPI");
                        DataSet ds = new DataSet("myDataset");
                        SqlDataAdapter da = new SqlDataAdapter(string.Format("SELECT * FROM Employee WHERE Department = '{0}'", department), con);
                        da.Fill(ds);
                        var ws = wb.Worksheets.Add(ds.Tables[0], department);
                        ws.Rows(1, 1).Style.Font.Bold = true;
                        ws.Columns().Width = 20;
                        ws.Columns().Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
                    }
                    wb.SaveAs(FileName);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }

**Comment by Pankraty** [comment]
I can't run this code unless I have an SQL Server installed and EmployeeDB rolled up. It would be nice of you to provide a runnable example with no dependencies that can be inserted into a console application's code - exactly as described in an issue template.

**Comment by mandeeplaha** [comment]
void EmployeeExcel()
        {
            try
            {
                string FileName = "D:\\Employee.xlsx";
                string Departments = "IT,HR,JAVA";
                using (XLWorkbook wb = new XLWorkbook(FileName))
                {
                    string[] DepartmentArray = Departments.Split(',');
                    foreach (string department in DepartmentArray)
                    {
                        System.Data.DataTable dtEmployee = GetEmployeeTable(department);
                        if (dtEmployee.Rows.Count > 0)
                        {
                            var ws = wb.Worksheets.Add(dtEmployee, department);
                            ws.Rows(1, 1).Style.Font.Bold = true;
                            ws.Columns().Width = 20;
                            ws.Columns().Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
                        }
                    }
                    wb.SaveAs(FileName);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        System.Data.DataTable GetEmployeeTable(string Department)
        {
            string[] Names = new[] { "Waylon", "Dalton", "Justine", "Henderson", "Abdullah", "Lang", "Marcus", "Cruz", "Thalia", "Cobb", "Mathias", "Little", "Eddie", "Randolph", "Angela", "Walker", "Lia", "Shelton", "Hadassah", "Hartman", "Joanna", "Shaffer", "Jonathon", "Sheppard" };
            System.Data.DataTable dtEmployee = new System.Data.DataTable();
            dtEmployee.Columns.Add("SRNO", typeof(int));
            dtEmployee.Columns.Add("FirstName", typeof(string));
            dtEmployee.Columns.Add("Email", typeof(string));
            dtEmployee.Columns.Add("Department", typeof(string));

            for (int i = 1; i <= 5000; i++)
            {
                string Name = Names[RandomNumber(0, 23)];
                DataRow drEmployee = dtEmployee.NewRow();
                drEmployee["SRNO"] = i;
                drEmployee["FirstName"] = Name;
                drEmployee["Email"] = Name.Replace(" ", string.Empty).ToLower() + "@gmail.com";
                drEmployee["Department"] = Department;
                dtEmployee.Rows.Add(drEmployee);
            }
            return dtEmployee;
        }

        public int RandomNumber(int min, int max)
        {
            Random random = new Random();
            return random.Next(min, max);
        }

Call EmployeeExcel()

**Comment by mandeeplaha** [comment]
`void EmployeeExcel()
        {
            try
            {
                string FileName = "D:\\Employee.xlsx";
                string Departments = "IT,HR,JAVA";
                using (XLWorkbook wb = new XLWorkbook(FileName))
                {
                    string[] DepartmentArray = Departments.Split(',');
                    foreach (string department in DepartmentArray)
                    {
                        System.Data.DataTable dtEmployee = GetEmployeeTable(department);
                        if (dtEmployee.Rows.Count > 0)
                        {
                            var ws = wb.Worksheets.Add(dtEmployee, department);
                            ws.Rows(1, 1).Style.Font.Bold = true;
                            ws.Columns().Width = 20;
                            ws.Columns().Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
                        }
                    }
                    wb.SaveAs(FileName);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        System.Data.DataTable GetEmployeeTable(string Department)
        {
            string[] Names = new[] { "Waylon", "Dalton", "Justine", "Henderson", "Abdullah", "Lang", "Marcus", "Cruz", "Thalia", "Cobb", "Mathias", "Little", "Eddie", "Randolph", "Angela", "Walker", "Lia", "Shelton", "Hadassah", "Hartman", "Joanna", "Shaffer", "Jonathon", "Sheppard" };
            System.Data.DataTable dtEmployee = new System.Data.DataTable();
            dtEmployee.Columns.Add("SRNO", typeof(int));
            dtEmployee.Columns.Add("FirstName", typeof(string));
            dtEmployee.Columns.Add("Email", typeof(string));
            dtEmployee.Columns.Add("Department", typeof(string));

            for (int i = 1; i <= 5000; i++)
            {
                string Name = Names[RandomNumber(0, 23)];
                DataRow drEmployee = dtEmployee.NewRow();
                drEmployee["SRNO"] = i;
                drEmployee["FirstName"] = Name;
                drEmployee["Email"] = Name.Replace(" ", string.Empty).ToLower() + "@gmail.com";
                drEmployee["Department"] = Department;
                dtEmployee.Rows.Add(drEmployee);
            }
            return dtEmployee;
        }

        public int RandomNumber(int min, int max)
        {
            Random random = new Random();
            return random.Next(min, max);
        }`

Call EmployeeExcel()

**Comment by mandeeplaha** [comment]
void EmployeeExcel()
        {
            try
            {
                string FileName = "D:\\Employee.xlsx";
                string Departments = "IT,HR,JAVA";
                using (XLWorkbook wb = new XLWorkbook(FileName))
                {
                    string[] DepartmentArray = Departments.Split(',');
                    foreach (string department in DepartmentArray)
                    {
                        System.Data.DataTable dtEmployee = GetEmployeeTable(department);
                        if (dtEmployee.Rows.Count > 0)
                        {
                            var ws = wb.Worksheets.Add(dtEmployee, department);
                            ws.Rows(1, 1).Style.Font.Bold = true;
                            ws.Columns().Width = 20;
                            ws.Columns().Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
                        }
                    }
                    wb.SaveAs(FileName);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        System.Data.DataTable GetEmployeeTable(string Department)
        {
            string[] Names = new[] { "Waylon", "Dalton", "Justine", "Henderson", "Abdullah", "Lang", "Marcus", "Cruz", "Thalia", "Cobb", "Mathias", "Little", "Eddie", "Randolph", "Angela", "Walker", "Lia", "Shelton", "Hadassah", "Hartman", "Joanna", "Shaffer", "Jonathon", "Sheppard" };
            System.Data.DataTable dtEmployee = new System.Data.DataTable();
            dtEmployee.Columns.Add("SRNO", typeof(int));
            dtEmployee.Columns.Add("FirstName", typeof(string));
            dtEmployee.Columns.Add("Email", typeof(string));
            dtEmployee.Columns.Add("Department", typeof(string));

            for (int i = 1; i <= 5000; i++)
            {
                string Name = Names[RandomNumber(0, 23)];
                DataRow drEmployee = dtEmployee.NewRow();
                drEmployee["SRNO"] = i;
                drEmployee["FirstName"] = Name;
                drEmployee["Email"] = Name.Replace(" ", string.Empty).ToLower() + "@gmail.com";
                drEmployee["Department"] = Department;
                dtEmployee.Rows.Add(drEmployee);
            }
            return dtEmployee;
        }

        public int RandomNumber(int min, int max)
        {
            Random random = new Random();
            return random.Next(min, max);
        }

Call EmployeeExcel()

**Comment by igitur** [comment]
You can disable the autofilter using this code:

```
var table = ws.Tables.First();
table.ShowAutoFilter = false;
```

The table is auto-styled, because that's what happens when you define a range as a table. It happens in Excel too.

**Comment by igitur** [comment]
More info about tables at https://github.com/ClosedXML/ClosedXML/wiki/Using-Tables

**Comment by mandeeplaha** [comment]
Thanks. Its working fine now.
