### ISSUE TITLE
CalcEngine fails with: 'Unbalanced parenthesis.'

### ISSUE THREAD

**Issue by itaroiu** [ClosedXML/ClosedXML#751]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.91.0

**What is the current behavior?**

The CalcEngine fails to calculate the result when formula contains more parenthesis than minimum required.
As instance, the formula from bellow is correct, but contains one more pair of parenthesis than minimum required:
=AVERAGE((A1:A10,B1:B10))
In this cases the application exit with "ClosedXML.Excel.CalcEngine.ExpressionParseException: 'Unbalanced parenthesis.'"

**What is the expected behavior or new feature?**

The additional parenthesis should be ignored when the formula is evaluated.

**Did this work in previous versions of our tool?  Which versions?**

Never tested before.

**Code to reproduce problem:**
```c#
public void Main()
{
    XLWorkbook _wb = new XLWorkbook(@"YourFilePath\FormulaTest.xlsx");
            var _ws = _wb.Worksheet("Sheet1");
            double _formulaResultOK = _ws.Cell("D1").GetValue<double>();//ok =AVERAGE(A1:A10,B1:B10)
            double _formulaResultNOK = _ws.Cell("D2").GetValue<double>();//exception =AVERAGE((A1:A10,B1:B10))
}
```
- [x] I attached a sample spreadsheet. 
[FormulaTest.xlsx](https://github.com/ClosedXML/ClosedXML/files/1829334/FormulaTest.xlsx)

**Comment by igitur** [comment]
Please fill in the entire issue template.
