### ISSUE TITLE
HowTo: Do labels on a row

### ISSUE THREAD

**Issue by AxiomX** [ClosedXML/ClosedXML#752]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.87.1
0.76.0.0

**What is the current behavior?**

Complete this.
Unknown

**What is the expected behavior or new feature?**

Complete this.
To be able to create a label across a row in a spreadsheet. See attached jpg

**Did this work in previous versions of our tool?  Which versions?**

Yes/No/v0.XX
Unknown

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

probably not a bug, just do not know how to do.
![spreadsheet label](https://user-images.githubusercontent.com/640507/37665197-aaa1dcda-2c54-11e8-93ec-277e8ae0eb78.JPG)

sorry no code for I do not know how to do it and cannot find anything in the current wiki that talks about it.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by vbjay** [comment]
Well the labels are done in Excel with number formatting set to a quoted
string if I remember correctly.

**Comment by igitur** [comment]
I don't know what labels you're referring to. Your screenshot shows a merged cell with a comment.

**Comment by AxiomX** [comment]
Ok, how do you do that?
That is a sample from an existing spreadsheet that I am duplicating.
