### ISSUE TITLE
Using ClosedXML I would like to code the ability to Add XSD / XML Schema to Excel File and Map fields as needed

### ISSUE THREAD

**Issue by datamd** [ClosedXML/ClosedXML#753]
## Read and complete the full issue template

**Do you want to request a *feature* or report 
[SuggestionAddXMLSchemaToExcelSuggestion.xlsx](https://github.com/ClosedXML/ClosedXML/files/1830091/SuggestionAddXMLSchemaToExcelSuggestion.xlsx)

a *bug*?**
- [] Bug
- [x] Feature

**Version of ClosedXML**

Latest Version

**What is the current behavior?**

Complete this.

Using ClosedXML I would like to code the ability to Add XSD / XML Schema to Excel File and Map fields as needed 

Below are the steps I wish to perform (Sample Excel File and XML Schema Files attached) 

Click on "Developer" menu item (If not showing then you may have to File, Options, Customize Ribbon and tick the "developer" box)
Click on "Source"
Click on "XML Maps..."
Give Path to the XSD file for "XSD_File_NoSeries.xml" (supplied)
Then ... 
Map TableID to cell C1
Map Packagecode to A1
Map Code to A3
Map Description to B3
Map DefaultNos to C3

... Happy to donate beers to the developer : - ) 

Complete this.

New Feature Request / Suggestion ... Add XML Schema to Excel File 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
   Using ClosedXML I would like to code the ability to Add XSD / XML Schema to Excel File and Map fields as needed 

Below are the steps I wish to  perform (Sample Excel File and XML Schema Files attached) 

Click on "Developer" menu item (If not showing then you may have to File, Options, Customize Ribbon and tick the "developer" box)
Click on "Source"
Click on "XML Maps..."
Give Path to the XSD file for "XSD_File_NoSeries.xml" (supplied)
Then ... 
Map TableID to cell C1
Map Packagecode to A1
Map Code to A3
Map Description to B3
Map DefaultNos to C3
[SuggestionAddXMLSchemaToExcelSuggestion.xlsx](https://github.com/ClosedXML/ClosedXML/files/1830068/SuggestionAddXMLSchemaToExcelSuggestion.xlsx)

... Happy to donate beers to the developer : - ) 

}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by datamd** [comment]
Below is a screenshot showing XML Source 

![image](https://user-images.githubusercontent.com/24790025/37666132-affda40a-2c56-11e8-8cbb-796821127065.png)

**Comment by datamd** [comment]
A copy of the XML File is below 

<?xml version="1.0" encoding="utf-8"?>
<DataList>
  <NoSeriesList>
    <TableID>308</TableID>
    <PackageCode>NO.SERIES</PackageCode>
    <NoSeries>
      <Code>string</Code>
      <Description>string</Description>
      <DefaultNos>string</DefaultNos>
      <ManualNos>string</ManualNos>
      <DateOrder>string</DateOrder>
      <zentity>string</zentity>
      <zall>string</zall>
    </NoSeries>
    <NoSeries>
      <Code>string</Code>
      <Description>string</Description>
      <DefaultNos>string</DefaultNos>
      <ManualNos>string</ManualNos>
      <DateOrder>string</DateOrder>
      <zentity>string</zentity>
      <zall>string</zall>
    </NoSeries>
  </NoSeriesList>
</DataList>

**Comment by datamd** [comment]
A copy of the XML file is below

![image](https://user-images.githubusercontent.com/24790025/37666232-f3f72aaa-2c56-11e8-9ea0-27fd4d362a31.png)

**Comment by datamd** [comment]
XML file renamed to .txt and attached below 

[XSD_File_NoSeries.xml.txt](https://github.com/ClosedXML/ClosedXML/files/1830107/XSD_File_NoSeries.xml.txt)

**Comment by igitur** [comment]
Sorry, this is out of the ClosedXML scope. You'll have to implement this yourself.
