### ISSUE TITLE
[info] sharing an utility based on ClosedXML

### ISSUE THREAD

**Issue by giuliohome** [ClosedXML/ClosedXML#754]
## This is not an issue, just a quick info I'd like to share, 

I've to write a program in **F#** which stores records from many excel files and then, based on a key column, produces a log of the differences.
I'm trying to develop the underlying library as _open source_.
Nothing special, just a thin wrapper layer around ClosedXML and some sqlite to achieve the above said, simple goal. The idea is to describe the xlsx header with a list of generic `DU` types, with the name and the format (`string`, `date`, `float`, `int`). I will use a generic `a'` (e.g. date time event), provided a function to show` a' `to `string`, to distinguish the different xlsx files. The only thing I still have to do is to import them all into sqlite - under these generic columns definition - and to produce the differences, based on a certain input key... 

This is my [repo](https://bitbucket.org/giuliohome2015/xlsxcompare), thank you.

**feel free to send me feedback or issue there or to close this post**

**Comment by igitur** [comment]
Thanks. Looks interesting. Do you have an example project or a test suite that illustrates its usage?

**Comment by giuliohome** [comment]
I'll keep you updated with an example and some tests. I'm developing the tool in these days, it should be ready in about a week or two. I'll post a comment here

**Comment by giuliohome** [comment]
I've added a simple demo example (plus a script test w.i.p.) in the readme and I'll continue to commit new changes in the next days.
