### ISSUE TITLE
How to stream excel file as pdf

### ISSUE THREAD

**Issue by punko96** [ClosedXML/ClosedXML#760]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [x ] Feature

**Version of ClosedXML**

e.g. 0.90.0.0

**What is the current behavior?**

Currently I'm able to save file as PDF only if using Microsoft.Office.Interop.Excel. We are trying to get away from this and not use MS office.

**What is the expected behavior or new feature?**

How can achieve this only using ClosedXML? Is it even possible?

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    HttpResponse httpResponse = HttpContext.Current.Response;
                    httpResponse.Clear();
                    httpResponse.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                    //httpResponse.AddHeader("content-disposition", "attachment;filename=\"Report.xlsx\"");
                    httpResponse.AddHeader("content-disposition", "attachment;filename=\"" + filename + "\"");

                    // Flush the workbook to the Response.OutputStream
                    using (MemoryStream memoryStream = new MemoryStream())
                    {                       
                        this.Workbook.SaveAs(memoryStream);
                        memoryStream.WriteTo(httpResponse.OutputStream);
                        memoryStream.Position = 0;
                        memoryStream.Close();
                        httpResponse.Flush();
                        httpResponse.SuppressContent = true;
                    }
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Sorry, this isn't possible with ClosedXML.
