### ISSUE TITLE
How to access filter data?

### ISSUE THREAD

**Issue by MrMadsea** [ClosedXML/ClosedXML#762]
If you open an Excel that is previously filtered, how can you read that information?
When looking for the usedRanged, the Range always provides the complete worksheet.

In interlop would be something like this:
Range filteredRange = sheet.UsedRange.SpecialCells(XlCellType.xlCellTypeVisible);

Thanks!

**Comment by igitur** [comment]
Why do you think it's OK to ignore the entire issue template?

**Comment by MrMadsea** [comment]
Maybe its not  sorry, i should re enter the issue again following the template?

**Comment by vbjay** [comment]
Yes.
