### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by igitur** [ClosedXML/ClosedXML#772]
The vector sources of the current logo is long gone. The current logo is also a bit dated and possibly breaking copyright rules. I don't know. Unfortunately, this isn't my forte, but if anyone out there can help, it would be appreciated. 

cc @beerwin (You helped out with OpenDBDiff's logo)

Current logo:
![image](https://user-images.githubusercontent.com/145854/38570950-63718b5c-3cef-11e8-8dee-9964eb7cedbf.png)

**Comment by beerwin** [comment]
Hi,

Unfortunately I'm rather busy these days, but I will try to come up with something later (can't be sure, when).

**Comment by igitur** [comment]
@beerwin Sure, it was a long shot anyway.

**Comment by igitur** [comment]
@arasatasaygin I didn't find anything applicable in http://openlogos.org - maybe you can spare some time to help us out?

**Comment by arasatasaygin** [comment]
Noted your project @igitur 
I'm considering to change the process if I do another batch of logos. Maybe I can pick some projects and help those.
Cheers.

**Comment by igitur** [comment]
Ok, thanks @arasatasaygin .

**Comment by igitur** [comment]
@Tobaloidee I see you like doing this stuff too. ;-)

**Comment by Tobaloidee** [comment]
Hi @igitur i can be of help here if i will be allowed.. :)

**Comment by igitur** [comment]
@Tobaloidee Definitely. Would you like me to explain the purpose of this project or does the `README.md` give you enough detail?

Because this library is a tool to generate and manipulate Excel file, I thought it would be nice to have a logo that is made from "cells", almost pixellated, but where the "pixels" are cells / blocks. I don't know if that makes sense to you? But you have the freedom to come with any suggestion.

**Comment by Tobaloidee** [comment]
Thanks for the info Sir..i will post here my initial designs when done..

**Comment by igitur** [comment]
Brilliant! I love it! 

@Pankraty @vbjay @b0bi79 Any comments? I first thought about maybe a different colour, but the green is strongly associated with Excel, so I think we should keep the colour.

**Comment by igitur** [comment]
@Tobaloidee Contact me privately on my email or Google hangouts (username igitur). I can't pay you, but I can at least send you a postcard of my hometown ;-)

**Comment by Pankraty** [comment]
Very nice, thank you @tabaloidee!
I agree about green, and I like the logo too.

**Comment by Tobaloidee** [comment]
Should i make a PR and upload the files? Im glad you liked it..

**Comment by b0bi79** [comment]
Great logo. And it does not look like Etszel and causes association with excel.
Thanks @Tobaloidee!

**Comment by Tobaloidee** [comment]
Thanks and im glad you liked it! :)

**Comment by Tobaloidee** [comment]
Sir @igitur i cant find your email address :)

**Comment by igitur** [comment]
igitur at gmail

**Comment by Tobaloidee** [comment]
Here is the final layout with other variations before i make a PR .  I can provide the needed files of all those options

![closedxml final-13](https://user-images.githubusercontent.com/36028424/41693010-e7c97166-7535-11e8-9869-01bba9b9df37.png)

**Comment by Tobaloidee** [comment]
I emailed you @igitur

**Comment by igitur** [comment]
@Tobaloidee That's perfect, thanks. Please create a PR and add the files in a `./resources/logo/` directory in the root of the repository.

**Comment by Tobaloidee** [comment]
Will do a PR later Sir..ill prepare the final files and uplaod all those versions..

**Comment by Tobaloidee** [comment]
Uploaded all the Logo versions & Updated the Readme file with this PR #915

Thanks and My best regards! - Tobaloidee

**Comment by igitur** [comment]
I don't mind, but maybe @Tobaloidee can help you here. Create an issue on ClosedXML.Report and explain to @Tobaloidee what the library is about and what it adds to the base ClosedXML library. I think the new logo with some kind of "report" overlay in the corner would be nice. What do you think?

**Comment by b0bi79** [comment]
Yes, I wanted to add in the corner the distinctive attributes of ClosedXML.Report - the parentheses {{}}. Thanks for the tip, I will create an issue on ClosedXML.Report.

**Comment by igitur** [comment]
@Tobaloidee I added your name to the bottom of the [README.md](https://github.com/ClosedXML/ClosedXML/blob/develop/README.md).

**Comment by igitur** [comment]
@b0bi79 And maybe you can reward @Tobaloidee in the same way I going to do, by sending a postcard of my hometown. That's the best I can do.
