### ISSUE TITLE
Bug with TotalsRowFunction

### ISSUE THREAD

**Issue by healkar01** [ClosedXML/ClosedXML#773]
Version of ClosedXML: 0.90.0

I am trying to add a totals row based on your example:

table.ShowTotalsRow = true;
table.Field("Income").TotalsRowFunction = XLTotalsRowFunction.Sum;

My code is adding it to every column like so:

                // Add Grand Total row
                var range = ws.Range(ws.FirstCellUsed(), ws.LastCellUsed());
                var table = range.CreateTable();
                table.ShowTotalsRow = true;

                foreach (var field in table.Fields)
                {
                    if (field.Index > 0 && field.Name != "")
                    {
                       field.TotalsRowFunction = XLTotalsRowFunction.Sum;
                    }
                }

I stepped through the code to make sure that the fields that I wanted to use were correct and looked at the formula that was produced for each field.  It looks like this: SUBTOTAL(109, [ABCD    ])
where ABCD is the column header.  This doesn't work and results in a bad reference.  I would have expected it to be SUBTOTAL(109, B2:B129)

I then tried making my own function:

field.TotalsRowFormulaA1 = "SUM(" + GetExcelColumnName(field.Index + 1) + "2:" + GetExcelColumnName(field.Index + 1) + (table.RowCount() - 1) + ")";

Which, oddly, worked, HOWEVER when the spreadsheet is opened, Excel complains and attempts to repair it.  But the totals are there and accurate.

Thank you,

Karen Healey

**Comment by igitur** [comment]
Please attach your workbook and point me to the relevant sheet.

**Comment by healkar01** [comment]
[SUMFormula.xlsx](https://github.com/ClosedXML/ClosedXML/files/1896335/SUMFormula.xlsx)
[XLTotalsRowFunctionSUM.xlsx](https://github.com/ClosedXML/ClosedXML/files/1896336/XLTotalsRowFunctionSUM.xlsx)

I attached two spreadsheets, each with just one sheet.  One of them uses XLTotalsRowFunction.Sum and the other uses the SUM formula.  The one using the SUM function has the correct results, but unfortunately opens with an error.  The other opens with an error and has an invalid reference.  Which, as I debugged is something like this: SUBTOTAL(109, [ABCD ]) but you will see SUBTOTAL(109, #REF)

Thank you,

Karen Healey

**Comment by igitur** [comment]
@healkar01 I need the input file before modification. I want to take your code + your file and reproduce the problem. Else I can't solve it.

**Comment by igitur** [comment]
Then it's up to you to create a dummy file or something to reproduce the problem. Or you could populate a `XLWorkbook` entirely by code. 

I refer you to the original issue template:

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
It might be the trailing spaces in the column headers (weird!). Also I see the last header starts with a hash. See if this build solves the issue:

https://ci.appveyor.com/project/Pyropace/closedxml/build/0.93.0.970/artifacts

**Comment by healkar01** [comment]
Hello, that was not the problem but thanks for considering it.  I found a few minutes to create the DataTable programatically. I kept it pretty simple and am still getting the error.

I have the following code to reproduce:

`                XLWorkbook wb = new XLWorkbook();

                DataTable dt = new DataTable();
                dt.Clear();
                dt.Columns.Add("Service", typeof(String));
                dt.Columns.Add("ABCD", typeof(Int32));
                dt.Columns.Add("ACTION", typeof(Int32));

                for (int i = 1; i < 50; i++)
                {
                    DataRow dtRow = dt.NewRow();
                    dtRow["Service"] = "Service " + i;
                    dtRow["ABCD"] = 500;
                    dtRow["ACTION"] = 500;
                    dt.Rows.Add(dtRow);
                }

                var ws = wb.Worksheets.Add("Program Services");

                // Insert our datatable into the data sheet at cell 1,1
                var source = ws.Cell(1, 1).InsertTable(dt, "Program Services", true);

                ws.Columns().AdjustToContents();

                // Add Grand Total row
                var range = ws.Range(ws.FirstCellUsed(), ws.LastCellUsed());
                var table = range.CreateTable();
                table.ShowTotalsRow = true;

                foreach (var field in table.Fields)
                {
                    if (field.Index > 0 && field.Name != "")
                    {
                        //                        field.TotalsRowFormulaA1 = "SUM(" + GetExcelColumnName(field.Index + 1) + "2:" + GetExcelColumnName(field.Index + 1) + (table.RowCount() - 1) + ")";
                        field.TotalsRowFunction = XLTotalsRowFunction.Sum;
                    }
                }

                table.Field(0).TotalsRowLabel = "Grand Total";

                wb.SaveAs("C:\\temp\\text1.xlsx");
`

Thank you,

Karen Healey

**Comment by igitur** [comment]
Your `var source = ws.Cell(1, 1).InsertTable(dt, "Program Services", true);` and `var table = range.CreateTable();` statements generate 2 duplicate tables over the same range. That causes the corrupt Excel file. I'll add a validation to avoid the creation of overlapping tables.

Running the following code on the latest development version generates the attached file:
```c#
XLWorkbook wb = new XLWorkbook();

DataTable dt = new DataTable();
dt.Clear();
dt.Columns.Add("Service", typeof(String));
dt.Columns.Add("ABCD", typeof(Int32));
dt.Columns.Add("ACTION", typeof(Int32));

for (int i = 1; i < 50; i++)
{
    DataRow dtRow = dt.NewRow();
    dtRow["Service"] = "Service " + i;
    dtRow["ABCD"] = 500;
    dtRow["ACTION"] = 500;
    dt.Rows.Add(dtRow);
}

var ws = wb.Worksheets.Add("Program Services");

// Insert our datatable into the data sheet at cell 1,1
var table = ws.Cell(1, 1).InsertTable(dt, "Program Services", true);

ws.Columns().AdjustToContents();

table.ShowTotalsRow = true;

foreach (var field in table.Fields)
{
    if (field.Index > 0 && field.Name != "")
    {
        field.TotalsRowFunction = XLTotalsRowFunction.Sum;
    }
}

table.Field(0).TotalsRowLabel = "Grand Total";

wb.SaveAs("C:\\temp\\text1.xlsx");
```
[text1.xlsx](https://github.com/ClosedXML/ClosedXML/files/1900539/text1.xlsx)

**Comment by healkar01** [comment]
Thank you!  

This was my 99% of my problem!  It turns out I was still getting the error but once I renamed the column that began with a hash, the error went away.  You should definitely release the other fix that you did as well!  Do you know when it will be available in NuGet?  (because I need to use a release version in our product).

Thanks again!

Karen Healey

**Comment by igitur** [comment]
Keep watching milestone 0.93 which includes the fixes mentioned above. Unfortunately there is not release schedule.

**Comment by somendra007** [comment]
This code work properly with total Sum in my end. @healkar01 @igitur 


`

       MemoryStream export(SalaryRecord salaryData)
        {
            using (var wb = new XLWorkbook())
            {
                var sheet = wb.Worksheets.Add("Salary");

                sheet.Range("A5:A6").Merge().Value = "Employee Code";
                sheet.Range("B5:B6").Merge().Value = "Name";
                sheet.Range("C5:C6").Merge().Value = "Department";
                sheet.Range("D5:D6").Merge().Value = "Sub Department";
                sheet.Range("E5:E6").Merge().Value = "Designation";
                sheet.Range("F5:F6").Merge().Value = "Grade";
                sheet.Range("G5:G6").Merge().Value = "DOJ";

                sheet.Cells("A5:G6").Style.Fill.BackgroundColor = XLColor.FromHtml("#BCD6EE");
                fillEmployeeDetails(sheet, salaryData.salarymaster);
                var colIndex = 7;
                var rowIndex = 7;
                foreach (var h in salaryData.payGroupRecords)
                {

                    var heads = salaryData.payHeadRecords.Where(o => o.PayGroupName == h.PayGroupName);

                    if (heads.Count() == 0) continue;

                    var range = sheet.Range(5, colIndex + 1, 5, colIndex + heads.Count());
                    range.Value = h.PayGroupName;
                    if (h.PayGroupName.ToLower() == "fixed head")
                    {
                        range.Style.Fill.BackgroundColor = XLColor.FromHtml("#FBE4D5");
                    }
                    if (h.PayGroupName.ToLower() == "earning")
                    {
                        range.Style.Fill.BackgroundColor = XLColor.FromHtml("#FFF3CB");
                    }
                    if (h.PayGroupName.ToLower() == "variable earning")
                    {
                        range.Style.Fill.BackgroundColor = XLColor.FromHtml("#FFDA65");
                    }
                    if (h.PayGroupName.ToLower() == "deduction")
                    {
                        range.Style.Fill.BackgroundColor = XLColor.FromHtml("#E2EFD9");
                    }
                    if (h.PayGroupName.ToLower() == "variable deduction")
                    {
                        range.Style.Fill.BackgroundColor = XLColor.FromHtml("#E2EFD9");
                    }
                    if (h.PayGroupName.ToLower() == "other")
                    {
                        range.Style.Fill.BackgroundColor = XLColor.FromHtml("#ACB9CA");
                    }

                    foreach (var head in heads)
                    {
                        colIndex++;
                        sheet.Cell(6, colIndex).Value = head.PayHeadName;
                        if (h.PayGroupName.ToLower() == "fixed head")
                        {
                            sheet.Cell(6, colIndex).Style.Fill.BackgroundColor = XLColor.FromHtml("#FBE4D5");
                        }
                        if (h.PayGroupName.ToLower() == "earning")
                        {
                            sheet.Cell(6, colIndex).Style.Fill.BackgroundColor = XLColor.FromHtml("#FFF3CB");
                        }
                        if (h.PayGroupName.ToLower() == "variable earning")
                        {
                            sheet.Cell(6, colIndex).Style.Fill.BackgroundColor = XLColor.FromHtml("#FFDA65");
                        }
                        if (h.PayGroupName.ToLower() == "deduction")
                        {
                            sheet.Cell(6, colIndex).Style.Fill.BackgroundColor = XLColor.FromHtml("#E2EFD9");
                        }
                        if (h.PayGroupName.ToLower() == "variable deduction")
                        {
                            sheet.Cell(6, colIndex).Style.Fill.BackgroundColor = XLColor.FromHtml("#E2EFD9");
                        }
                        if (h.PayGroupName.ToLower() == "other")
                        {
                            sheet.Cell(6, colIndex).Style.Fill.BackgroundColor = XLColor.FromHtml("#ACB9CA");
                        }
                        fillHeads(sheet, head.PayHeadName, h.PayGroupName, colIndex, salaryData.salarydetails, salaryData.salarymaster);
                    }

                    range.Merge();

                    if (h.PayGroupName.ToLower() == "fixed head")
                    {
                        sheet.Range(5, colIndex + 1, 6, colIndex + 1).Merge().Value = "Month Days";
                        sheet.Range(5, colIndex + 1, 6, colIndex + 1).Merge().Style.Fill.BackgroundColor = XLColor.FromHtml("#BCD6EE");
                        foreach (var d in salaryData.salarymaster)
                        {
                            sheet.Cell(rowIndex, colIndex + 1).Value = d.Month;
                            sheet.Cell(rowIndex, colIndex + 2).Value = d.Leaves;
                            sheet.Cell(rowIndex, colIndex + 3).Value = d.Absent;
                            sheet.Cell(rowIndex, colIndex + 4).Value = d.Attendance;

                            rowIndex++;
                        }
                        sheet.Range(5, colIndex + 2, 6, colIndex + 2).Merge().Value = "Leave";
                        sheet.Range(5, colIndex + 2, 6, colIndex + 2).Merge().Style.Fill.BackgroundColor = XLColor.FromHtml("#BCD6EE");
                        sheet.Range(5, colIndex + 3, 6, colIndex + 3).Merge().Value = "Absent";
                        sheet.Range(5, colIndex + 3, 6, colIndex + 3).Merge().Style.Fill.BackgroundColor = XLColor.FromHtml("#BCD6EE");
                        sheet.Range(5, colIndex + 4, 6, colIndex + 4).Merge().Value = "Working Days";
                        sheet.Range(5, colIndex + 4, 6, colIndex + 4).Merge().Style.Fill.BackgroundColor = XLColor.FromHtml("#BCD6EE");

                        colIndex += 4;
                    }
                    range.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                }
                colIndex++;
                sheet.Range(5, colIndex, 6, colIndex).Merge().Value = "Gross";
                sheet.Range(5, colIndex, 6, colIndex).Merge().Style.Fill.BackgroundColor = XLColor.FromHtml("#BCD6EE");
                rowIndex = 7;
                foreach (var d in salaryData.salarymaster)
                {
                    sheet.Cell(rowIndex, colIndex).Value = d.Gross;
                    rowIndex++;
                }
                colIndex++;
                sheet.Range(5, colIndex, 5, colIndex + 1).Merge().Value = "Total Deductions";
                sheet.Range(5, colIndex, 5, colIndex + 1).Merge().Style.Fill.BackgroundColor = XLColor.FromHtml("#BCD6EE");
                sheet.Cell(6, colIndex).Value = "Employee";
                sheet.Cell(6, colIndex).Style.Fill.BackgroundColor = XLColor.FromHtml("#BCD6EE");
                sheet.Cell(6, colIndex + 1).Value = "Employer";
                sheet.Cell(6, colIndex + 1).Style.Fill.BackgroundColor = XLColor.FromHtml("#BCD6EE");
                rowIndex = 7;
                foreach (var d in salaryData.salarymaster)
                {
                    sheet.Cell(rowIndex, colIndex).Value = d.Employee;
                    rowIndex++;
                }
                colIndex++;
                rowIndex = 7;
                foreach (var d in salaryData.salarymaster)
                {
                    sheet.Cell(rowIndex, colIndex).Value = d.Employer;
                    rowIndex++;
                }
                colIndex += 1;
                sheet.Range(5, colIndex, 6, colIndex).Merge().Value = "Net";
                sheet.Range(5, colIndex, 6, colIndex).Merge().Style.Fill.BackgroundColor = XLColor.FromHtml("#BCD6EE");
                rowIndex = 7;
                foreach (var d in salaryData.salarymaster)
                {
                    sheet.Cell(rowIndex, colIndex).Value = d.NetSalary;
                    rowIndex++;
                }
                //sheet.Cell(9 + salaryData.salarymaster.Count(), 8).FormulaA1 = @$"=SUM(H7:H{rowIndex + salaryData.salarymaster.Count()})";

                sheet.Range(5, 1, 6, colIndex).Style.Border.RightBorder = XLBorderStyleValues.Thin;
                sheet.Range(5, 1, 6, colIndex).Style.Border.BottomBorder = XLBorderStyleValues.Thin;
                sheet.Range(5, 1, 6, colIndex).Style.Border.TopBorder = XLBorderStyleValues.Thin;

                var _firstCell = sheet.FirstCellUsed();
                var _lastcell = sheet.LastCellUsed();
                var _range = sheet.Range(_firstCell, _lastcell);
                var table = _range.AsTable();
                //table.ShowTotalsRow = true;                
                foreach (var field in table.Fields)
                {
                    if (field.Index > 0 && field.Name != "")
                    {
                        if (field.Name.ToLower().Trim() != "name" && field.Name.ToLower().Trim() != "employeecode"
                            && field.Name.ToLower().Trim() != "department"
                            && field.Name.ToLower().Trim() != "sub department"
                            && field.Name.ToLower().Trim() != "designation"
                            && field.Name.ToLower().Trim() != "grade"
                            && field.Name.ToLower().Trim() != "doj"
                            && field.Name.ToLower().Trim() != "month days"
                            && field.Name.ToLower().Trim() != "leave"
                            && field.Name.ToLower().Trim() != "absent"
                            && field.Name.ToLower().Trim() != "working days"                            
                            )                            
                            sheet.Cell(7 + salaryData.salarymaster.Count(), field.Column.RangeAddress.FirstAddress.ColumnNumber).FormulaA1 = @$"=SUM({field.Column.RangeAddress.FirstAddress.ColumnLetter}{field.Column.RangeAddress.FirstAddress.RowNumber}:{field.Column.RangeAddress.LastAddress.ColumnLetter}{field.Column.RangeAddress.LastAddress.RowNumber})";
                        sheet.Cell(7 + salaryData.salarymaster.Count(), field.Column.RangeAddress.FirstAddress.ColumnNumber).Style.Fill.BackgroundColor = XLColor.FromHtml("#BFBFBF");
                    }                    
                }
                //table.Field(0).TotalsRowLabel = "Total ";
                //table.Field("Salary!H1:H9").TotalsRowFunction = XLTotalsRowFunction.Sum;
                //table.Field("Column35").TotalsRowFunction = XLTotalsRowFunction.Sum;
                sheet.Range(7 + salaryData.salarymaster.Count(), 1, 7 + salaryData.salarymaster.Count(), 7).Merge().Value = "Total";
                sheet.Range(7 + salaryData.salarymaster.Count(), 1, 7 + salaryData.salarymaster.Count(), 7).Style.Fill.BackgroundColor = XLColor.FromHtml("#BFBFBF");
                sheet.Range(1, 1, 1, colIndex).Merge().Value = "Company Name :-" + salaryData.salarycompany[0].compName;
                sheet.Range(2, 1, 2, colIndex).Merge().Value = "Address :-" + salaryData.salarycompany[0].address;
                sheet.Range(3, 1, 3, colIndex).Merge().Value = "Salary Register For The Month:-" + salaryData.salarycompany[0].salaryDate;
                sheet.Range(4, 1, 4, colIndex).Merge().Value = "Grade:- " + salaryData.salarycompany[0].grade + ", Department:- " + salaryData.salarycompany[0].department + ", Sub Department:- " + salaryData.salarycompany[0].subDepartment + ", Employee Group:- " + salaryData.salarycompany[0].employeeGroup + "";
                sheet.Range(1, 1, 1, colIndex).Style.Font.Bold = true;
                sheet.Range(2, 1, 2, colIndex).Style.Font.Bold = true;
                sheet.Range(3, 1, 3, colIndex).Style.Font.Bold = true;
                sheet.Range(4, 1, 4, colIndex).Style.Font.Bold = true;

                sheet.Columns().AdjustToContents();
                using var stream = new MemoryStream();

                wb.SaveAs(stream, new SaveOptions { EvaluateFormulasBeforeSaving = true });
                return stream;

            }
        }
        void fillEmployeeDetails(IXLWorksheet sheet, IList<SalaryMaster> data)
        {
            int rowIndex = 7;
            foreach (var d in data)
            {
                sheet.Cell(rowIndex, 1).Value = d.EmployeeCode;
                sheet.Cell(rowIndex, 2).Value = d.EmployeeName;
                sheet.Cell(rowIndex, 3).Value = d.Department;
                sheet.Cell(rowIndex, 4).Value = d.subdepartment;
                sheet.Cell(rowIndex, 5).Value = d.Designation;
                sheet.Cell(rowIndex, 6).Value = d.Grade;
                sheet.Cell(rowIndex, 7).Value = d.dateofJoining;
                rowIndex++;
            }

        }

        void fillHeads(IXLWorksheet sheet, string payheadName, string paygroup, int col, IList<SalaryMasterDeails> data, IList<SalaryMaster> datamaster)
        {
            int rowIndex = 7;
            foreach (var sm in datamaster)
            {
                foreach (var d in data)
                {
                    if (d.PayHeadName == payheadName && d.PayGroupName == paygroup && d.EmployeeId == sm.EmployeeId)
                    {
                        sheet.Cell(rowIndex, col).Value = d.Amount;
                    }
                }
                //sheet.Cell(7 + datamaster.Count(), 8).FormulaA1 = @$"=SUM(H7:H{7 + datamaster.Count()})";
                rowIndex++;
            }
        }`
