### ISSUE TITLE
StackOverflowException when getting cell value

### ISSUE THREAD

**Issue by Umeshpatil0012** [ClosedXML/ClosedXML#784]
ClosedXml Version: 0.75.0.0

Issue:
When i getting the value from cell I12, it throws StackOverflowException, 
The formula for cell I12 is =B12+C12+I12.
I know the Cell I12 is calculated in that formula, Is there any method to validate formula or is this issue fixed by ClosedXml dev team.

Please see the following code:
var ws = xlwrkbook.Worksheet(1);
string value = ws.Cell("I12").Value.ToString();

**Comment by Pankraty** [comment]
This must have been fixed in #740. Try version 0.92.1
