### ISSUE TITLE
ClosedXML.Excel.Drawings.XLPicture not supported in v 0.92.1.0

### ISSUE THREAD

**Issue by Umeshpatil0012** [ClosedXML/ClosedXML#785]
XLPicture attribute is not supported in v 0.92.1.0

**Comment by igitur** [comment]
Please complete the full issue template.

**Comment by Umeshpatil0012** [comment]
I want to read image from excel file.
When i create the object for image ClosedXML.Excel.Drawings.XLPicture it shows error for XLPicture as "XLPicture does not exist in namespace ClosedXML.Excel.Drawings"

I have write the following code:
var pic = new ClosedXML.Excel.Drawings.XLPicture
                {
                    NoChangeAspect = true,
                    NoMove = true,
                    NoResize = true,
                    ImageStream = File.Open(clsConfig.strELabLogoImagePath, FileMode.Open, FileAccess.Read, FileShare.Read),
                    Name = "ELabLogo"
                };

**Comment by igitur** [comment]
The correct way to add a picture is documented at https://github.com/ClosedXML/ClosedXML/wiki/How-can-I-insert-an-image
