### ISSUE TITLE
Insert image to excel cell using Asp.net

### ISSUE THREAD

**Issue by maheshmohan3004** [ClosedXML/ClosedXML#793]
Missing feature in closedXML for Asp.net

Would like to know if there is any way to insert an image to excel file using ClosedXML. 

Thanks.

**Comment by igitur** [comment]
https://github.com/ClosedXML/ClosedXML/wiki/How-can-I-insert-an-image

**Comment by maheshmohan3004** [comment]
getting error when using ClosedXML 0.9.0.0 and DocumentFormat.OpenXml 2.7.2.0

PM> Install-Package ClosedXML -Version 0.92.1
Attempting to resolve dependency 'DocumentFormat.OpenXml (≥ 2.7.2)'.
Attempting to resolve dependency 'ExcelNumberFormat (≥ 1.0.3)'.
Attempting to resolve dependency 'FastMember.Signed (≥ 1.3.0)'.
Install-Package : 'FastMember.Signed' already has a dependency defined for 'Microsoft.CSharp'.
At line:1 char:16
+ Install-Package <<<<  ClosedXML -Version 0.92.1
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by maheshmohan3004** [comment]
getting error when using ClosedXML 0.9.0.0 and DocumentFormat.OpenXml 2.7.2.0

PM> Install-Package ClosedXML -Version 0.92.1
Attempting to resolve dependency 'DocumentFormat.OpenXml (≥ 2.7.2)'.
Attempting to resolve dependency 'ExcelNumberFormat (≥ 1.0.3)'.
Attempting to resolve dependency 'FastMember.Signed (≥ 1.3.0)'.
Install-Package : 'FastMember.Signed' already has a dependency defined for 'Microsoft.CSharp'.
At line:1 char:16
   
   - Install-Package <<<< ClosedXML -Version 0.92.1      
      - CategoryInfo : NotSpecified: (:) [Install-Package], InvalidOperationException
      - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand



    On Thursday, April 19, 2018, 4:48:46 PM GMT+5:30, Francois Botha <notifications@github.com> wrote:  
 
 
https://github.com/ClosedXML/ClosedXML/wiki/How-can-I-insert-an-image

**Comment by Pankraty** [comment]
The issue is named "Insert image to excel cell using Asp.net". Please open a new one.
