### ISSUE TITLE
Showing error could not load file or assembly FastMember.Signed  1.3.0

### ISSUE THREAD

**Issue by maheshmohan3004** [ClosedXML/ClosedXML#795]
Showing error could not load file or assembly FastMember.Signed  1.3. when using ClosedXML 0.9.0.0 and DocumentFormat.OpenXml 2.7.2.0

PM> Install-Package ClosedXML -Version 0.92.1
Attempting to resolve dependency 'DocumentFormat.OpenXml (≥ 2.7.2)'.
Attempting to resolve dependency 'ExcelNumberFormat (≥ 1.0.3)'.
Attempting to resolve dependency 'FastMember.Signed (≥ 1.3.0)'.
Install-Package : 'FastMember.Signed' already has a dependency defined for 'Microsoft.CSharp'.
At line:1 char:16

   - Install-Package <<<< ClosedXML -Version 0.92.1
      - CategoryInfo : NotSpecified: (:) [Install-Package], InvalidOperationException
      - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by maheshmohan3004** [comment]
re installing nuget manager resolved the issue.
thanks

**Comment by JameemaMoses** [comment]
Hi,

I'm facing the same issue while trying to install ClosedXML 0.92.1 version. I tried re installing nuget package manager but that didn't resolve the issue. I have an urgent client requirement to insert the image into excel sheet which i cannot do with ClosedXML version 0.67.1 that is in my project. 

Please suggest how to fix this issue. I'm really stuck on this from pretty long time.

**Comment by vbjay** [comment]
You have to update the package.  What version of VS are you running?

**Comment by JameemaMoses** [comment]
Hi Jay,

thank you for the response.

I'm using VS 2012 and I cannot upgrade this to higher versions since this
is a client project.

Thank you.

Regards
Jameema
