### ISSUE TITLE
Method AdjustToContents is very slow on sheets with many merged ranges

### ISSUE THREAD

**Issue by crypto-rsa** [ClosedXML/ClosedXML#796]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
0.92

**What is the current behavior?**
Calling method `AdjustToContents` on a sheet with many merged ranges is painfully slow. That's because every cell in the range being adjusted is searched for in _every_ merged range, making the complexity of the operation O(n^2).

**What is the expected behavior or new feature?**
The method should be faster - for example by keeping a `HashSet` of all merged cells in the target range, so that each individual check is a O(1) operation, making the whole method a O(n) operation.

**Did this work in previous versions of our tool?  Which versions?**
No.

## Reproducibility
Attached is a sample [sheet](https://github.com/ClosedXML/ClosedXML/files/1931041/test.xlsx) with 20000 merged ranges. Calling the code below takes (in a Debug build) over 150 seconds.

**Code to reproduce problem:**
```c#
using( var wb = new XLWorkbook("test.xlsx") )
{
    wb.Worksheet( 1 ).ColumnsUsed().AdjustToContents();
}
```
- [x] I attached a sample spreadsheet.

**Comment by igitur** [comment]
Thanks. Sounds like you're half way to submitting a PR.

**Comment by crypto-rsa** [comment]
> Thanks. Sounds like you're half way to submitting a PR.

Almost :) I am new to this repository so I am still figuring out the best way to fix it.

**Comment by Pankraty** [comment]
On the other hand, if you'll come up with a solution that improves a single operation it's still worth submitting, that's for sure.

**Comment by crypto-rsa** [comment]
By the way, using checkboxes (especially for distinguishing between a bug and a feature) in the issue template leads to a lot of visual noise in the issue list. There will always be at least one "task" incomplete. IMHO a better usage of the checkboxes is for real tasks which need to be finished in order to close the issue - see for example [this issue](https://github.com/gitextensions/gitextensions/issues/4846) in the GitExtensions repository.
