### ISSUE TITLE
Remove dependency on FastMember

### ISSUE THREAD

**Issue by igitur** [ClosedXML/ClosedXML#797]
I originally added this library, because I read that Reflection is slow. And we used a lot of reflection in the `.InsertData` and `.InsertTable` methods. I actually never tested the impact on performance for this change.

I think it's worth relooking at this issue. We could either remove its use totally or compile it inside ClosedXML. 

FastMember is licensed under Apache v2

**Comment by igitur** [comment]
It's also worth looking at the `.InsertData` and `.InsertTable` methods in general together with this issue. Many users have a requirement just to dump lots of data into a table in an Excel format. I'd like to provide a super fast method with minimal type checking to do this.

**Comment by Pankraty** [comment]
I've prepared a benchmark comparing inserting random data using FastMember and pure reflection.

**1000 rows**
```
|     Method |     Mean |    Error |   StdDev |   Median | Ratio | RatioSD |
|----------- |---------:|---------:|---------:|---------:|------:|--------:|
| FastMember | 52.29 ms | 1.027 ms | 1.744 ms | 51.76 ms |  1.00 |    0.00 |
| Reflection | 53.11 ms | 1.062 ms | 2.169 ms | 52.06 ms |  1.03 |    0.05 |
```

**10 000 rows**
```
|     Method |     Mean |    Error |   StdDev | Ratio | RatioSD |
|----------- |---------:|---------:|---------:|------:|--------:|
| FastMember | 570.5 ms | 11.27 ms | 17.55 ms |  1.00 |    0.00 |
| Reflection | 572.6 ms |  6.55 ms |  5.80 ms |  1.00 |    0.04 |
```

**100 000 rows**
```
|     Method |    Mean |    Error |   StdDev | Ratio | RatioSD |
|----------- |--------:|---------:|---------:|------:|--------:|
| FastMember | 5.599 s | 0.1091 s | 0.1257 s |  1.00 |    0.00 |
| Reflection | 5.790 s | 0.1219 s | 0.1628 s |  1.04 |    0.04 |
```

The profiling results confirm that reading using reflection takes very little:
![image](https://user-images.githubusercontent.com/19576939/78220196-1d322080-74d2-11ea-987a-ec9ab9791cc9.png)
(don't look at percents; data generation took 78% and is out of scope). The real performance killer is deferred execution of LINQ expression over and over again. A simple `.ToList()` affects greatly.
![image](https://user-images.githubusercontent.com/19576939/78220362-700bd800-74d2-11ea-99bd-2cb3e88e00f1.png)

**Comment by Pankraty** [comment]
I have other ideas on how to speed up the `InsertData` method but they will take some time to implement. For now, let's start with a simple PR.

**Comment by jahav** [comment]
Closing this, because FastMember has been removed in #1388 few years ago ([0.95.0](https://github.com/ClosedXML/ClosedXML/releases/tag/0.95.0)).

As for the method of insertion without reflection, I am considering to add something with `XLCellValue` collection as an argument. That would remove need for reflection, because of implicit casting. But generally, I don't want to add a new API, unless really needed and for now, it can wait.

Also, the insert data has been significantly improved in [0.103.0-beta](https://github.com/ClosedXML/ClosedXML/releases/tag/0.103.0-beta).
