### ISSUE TITLE
PROPER function handling

### ISSUE THREAD

**Issue by vasilyevia** [ClosedXML/ClosedXML#8]
If a cell uses PROPER function which refers to another cell with empty value then ClosedXML fails with ArgumentOutOfRangeException.

e.g. I have A1 cell and it's value is "=PROPER(B1)". Value of B1 is empty.

Reading such a spreadsheet with ClosedXML results in error:

System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at ClosedXML.Excel.CalcEngine.Text.Proper(List`1 p)
   at ClosedXML.Excel.XLCell.get_Value()
   at ...

I would expect A1 cell to return empty value.

**Comment by igitur** [comment]
I can't reproduce the problem. Please attach your file.

**Comment by vasilyevia** [comment]
Can't really publish my spreadsheet as it has private data, but also can't edit it as I do not have software for that. Screenshot is attached if it can help.

![proper](https://cloud.githubusercontent.com/assets/692364/18385954/d190eab4-76bd-11e6-9af2-7e5206c593d7.png)

**Comment by igitur** [comment]
Unfortunately that doesn't help me much. I already tried a file with a normal Proper() function pointing to an empty cell.

I see you have OpenOffice. Why can't you remove the sensitive information and save the file?

**Comment by vasilyevia** [comment]
I should have been more precise in describing the issue. The error happens when I try to read cell value. Workbook initialization completes fine.

I do not think OpenOffice can save in XLSX format. Or do you mean you could try with some other format too?

**Comment by igitur** [comment]
Try LibreOffice. OpenOffice is dying.

**Comment by vasilyevia** [comment]
try this one

[Clean_template_for_import-CLEANED.xlsx](https://github.com/ClosedXML/ClosedXML/files/463908/Clean_template_for_import-CLEANED.xlsx)

**Comment by igitur** [comment]
Great, thanks. I found the bug. Will commit a fix for it soon.
