### ISSUE TITLE
Reading value from empty cell

### ISSUE THREAD

**Issue by rajashree1402** [ClosedXML/ClosedXML#82]

**Comment by rajashree1402** [comment]
Can any one help me how to read blank cell using Closed XML. Please reply asap its very urgent.

**Comment by igitur** [comment]
The regular way would be to use

```
ws.Cell("A1").Value
```

Is that not working for you?

**Comment by rajashree1402** [comment]
sorry but this is not working : 
this is my code
Stream stream = new MemoryStream(ReadFile(File));
                using (XLWorkbook workBook = new XLWorkbook(stream))
                {
                    //Read the first Sheet from Excel file.
                    IXLWorksheet workSheet = workBook.Worksheet(1);

                    //Create a new DataTable.
                  
                    //Loop through the Worksheet rows.
                    bool firstRow = true;
                    bool error = false;
                    foreach (IXLRow row in workSheet.Rows())
                    {
                        foreach (IXLCell cell in row.Cells())
                                    {
                                        if (cellCnt < 11)
                                        {
                                            dt.Columns.Add(cell.Value.ToString());
                                        }
                                        else
                                        {
                                            break;
                                        }
                                        cellCnt++;
                                        firstRow = false;
                                    }
}

 what is happening here when i go for header its showing 20 cells
but in data row it showing 19 . as one contain blank value . But  we need the blank value also.Please suggest where to modify it..

**Comment by igitur** [comment]
If the file information is not private, please attach the problematic file?

**Comment by rajashree1402** [comment]
[ISSUEFILE.xlsx](https://github.com/ClosedXML/ClosedXML/files/561377/ISSUEFILE.xlsx)

**Comment by rajashree1402** [comment]
attached file has a some blank cell
which was not read by the upper logic given above.

**Comment by igitur** [comment]
I can't reproduce the problem. I can read all cells in the file you attached. 

Which version of ClosedXML are you using?

**Comment by rajashree1402** [comment]
![closedxml](https://cloud.githubusercontent.com/assets/23162508/19848923/624f41be-9f76-11e6-8935-e581ceed1db0.png)

**Comment by rajashree1402** [comment]
are u able to read all 20 columns

**Comment by igitur** [comment]
Yes. 
![image](https://cloud.githubusercontent.com/assets/145854/19848989/59f53e28-9f59-11e6-95d7-292e2d6b2a1e.png)

And the rows after the first are also fine.

**Comment by igitur** [comment]
Do you know which cell exactly is giving the problem?

**Comment by rajashree1402** [comment]
veh make cell

**Comment by rajashree1402** [comment]
I didnot see the cells after vehicle vin  the screen shot that u have attached above.

**Comment by igitur** [comment]
![image](https://cloud.githubusercontent.com/assets/145854/19849205/80a79862-9f5a-11e6-9bc8-845f484ae368.png)

**Comment by igitur** [comment]
Try pull the latest version of the code from github and building against that.

**Comment by rajashree1402** [comment]
which one is latest version

**Comment by igitur** [comment]
Download the latest development version from https://github.com/ClosedXML/ClosedXML/archive/develop.zip

**Comment by rajashree1402** [comment]
I didnot find any dll in this folder

**Comment by igitur** [comment]
It's the source code. You have to build it yourself.

**Comment by rajashree1402** [comment]
But previously we had closedXML.dll which we download from online . Now we didn't get it from online.

**Comment by igitur** [comment]
Only released versions have a released DLL. If you want to benefit from unreleased code, which contain more bug fixes, you have to compile it yourself. It isn't difficult.

**Comment by rajashree1402** [comment]
which library we will consider to build the dll. i have taken the first one ClosedXML class library . But its not wokring.

**Comment by igitur** [comment]
I have made a build for you: https://www.dropbox.com/sh/3sbbu4j5idugj1z/AACd6XjtRMNRLopI288ywFi1a?dl=0

**Comment by rajashree1402** [comment]
site cannot be reached

**Comment by igitur** [comment]
Is your employer blocking www.dropbox.com ?

**Comment by rajashree1402** [comment]
yes

**Comment by rajashree1402** [comment]
give me the step i will do

**Comment by igitur** [comment]
Please ask a colleague to assist you in building ClosedXML from source.

**Comment by rajashree1402** [comment]
Actually there are four library in the downloaded  project . Can you please tell which we can refer to make the dll

**Comment by igitur** [comment]
The `ClosedXML` library.

**Comment by rajashree1402** [comment]
Please drop the dll over here

**Comment by rajashree1402** [comment]
I have made the dll from closedxml library .  but its not able to read the blank cell. Its existing issue.

**Comment by vbjay** [comment]
You gave to understand how excel works. It doesn't store every cell that is
possible in the file. It only stores values in rows that have a value or
formatting. If you only gave 19 cells in the row then extrapolate the empty
value by logic. Return a default value.

**Comment by rajashree1402** [comment]
sorry  but a file should have a empty cell so we have facility to read

**Comment by rajashree1402** [comment]
Is there any way  if we find a empty cell it just return empty

**Comment by igitur** [comment]
@vbjay Can you make out what the problem is?

**Comment by rajashree1402** [comment]
actually my requirement is to read the excel file and import the data in a database table. What happen when i read the file it just skipped all the blank cell value so in result it will insert wrong data in wrong cell.

**Comment by igitur** [comment]
Ok, let's try again:

- Which cell's value *exactly* are you trying to read? Give me a cell reference, e.g. `B5`.
- Does this happen for a single empty cell or all empty cells?
- You say it doesn't work. Give me more details. Is an exception thrown? Or do you get a null value in return?

**Comment by rajashree1402** [comment]
Cell L2, its didn't read that cell .its not throwing any exception. Also not even null . It just skipped that cell.

**Comment by igitur** [comment]
You're explicitly reading only the first 11 cells in a row!

```c#
 if (cellCnt < 11)
```

**Comment by rajashree1402** [comment]
just ignore that logic (Means that line)>please refer below

  foreach (IXLRow row in workSheet.Rows())
                    {
                        foreach (IXLCell cell in row.Cells())
                                    {
                                     
                                            dt.Columns.Add(cell.Value.ToString());
                                       
                                     
                                    }
}

**Comment by igitur** [comment]
You're not making this easy, you know.

**Comment by rajashree1402** [comment]
Sorry , that means  we cannot read an empty cell using Closed XML .

**Comment by igitur** [comment]
Replace 
```c#
foreach (IXLCell cell in row.Cells())
```
with
```c#
foreach (IXLCell cell in row.Cells(row.FirstCellUsed().Address.ColumnNumber, row.LastCellUsed().Address.ColumnNumber))
```

As @vbjay  mentioned, empty Cells are not stored in the underlying file. The above method creates an explicit Range which iterates over all cells between the given columns.

**Comment by rajashree1402** [comment]
Thanks Everyone for all your support It seems working fine now.

**Comment by milestogofromhere** [comment]
I ran into a similar issue and found this post. The line that @igitur posted didn't work for me, but this did:

`foreach (IXLCell cell in row.Cells(worksheet.FirstCellUsed().Address.ColumnNumber, worksheet.LastCellUsed().Address.ColumnNumber))`

**Comment by saineshwar** [comment]
Thanks it worked for me  foreach (IXLCell cell in row.Cells(row.FirstCellUsed().Address.ColumnNumber, row.LastCellUsed().Address.ColumnNumber))
                            {

**Comment by hasanseam** [comment]
Hi, This was pretty helpful guys. 
This code is worked for me.
foreach (IXLCell cell in row.Cells(row.FirstCellUsed().Address.ColumnNumber, row.LastCellUsed().Address.ColumnNumber))
{
}
but this has one problem. It count the first cell which is used. So this will be problematic if first 2 or 3 cell is empty it will skip this.
I over come it by manually replaced the parameter in row.Cells(1,12)
                        int i =0;
                        foreach (IXLCell cell in row.Cells(1,12))
                        {                        
                            dt.Rows[dt.Rows.Count - 1][i] = cell.Value.ToString();
                            i++;
                            Console.Write((cell.Value.ToString() == "") ?   "["+i+"]" : cell.Value.ToString());
                        }
Thank you.

**Comment by RamGenGIT** [comment]
Thank hasanseam, this worked for me as well:
foreach (IXLCell cell in row.Cells(1, x))  //where x equals cell count in range

**Comment by sarfarazengglb** [comment]
> Replace
> 
> ```cs
> foreach (IXLCell cell in row.Cells())
> ```
> 
> with
> 
> ```cs
> foreach (IXLCell cell in row.Cells(row.FirstCellUsed().Address.ColumnNumber, row.LastCellUsed().Address.ColumnNumber))
> ```
> 
> As @vbjay mentioned, empty Cells are not stored in the underlying file. The above method creates an explicit Range which iterates over all cells between the given columns.

This worked for me and saved hours. Very tricky issue.It skips the empty cell and you will be unable to read the row values properly.

If the above code gives "ClosedXML Object reference not set to an instance of an object." then use manual iteration
<code>
int i=0;
foreach (IXLCell cell in row.Cells(1,12))
{
dt.Rows[dt.Rows.Count - 1][i] = cell.Value.ToString();
i++;
Console.Write((cell.Value.ToString() == "") ? "["+i+"]" : cell.Value.ToString());
}
</code>
