### ISSUE TITLE
Improve diagnostic information for invalid xlsx (tdf100709.xlsx)

### ISSUE THREAD

**Issue by kenleese** [ClosedXML/ClosedXML#822]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**

0.93.0-beta2 with OpenXml 2.8.1 and TFM either net471 or netcoreapp2.0

**Observed behavior**

DocumentFormat.OpenXml.Packaging.OpenXmlPackageException: The specified package is invalid. The main part is missing.
at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Load()
at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(String path, Boolean isEditable, OpenSettings openSettings)
at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\XLWorkbook_Load.cs:line 41
at ClosedXmlTest.Program.Main() in D:\Vortini2\ClosedXmlTest\ClosedXmlTest\Program.cs:line 12

**What is the expected behavior or new feature?**

A well-known ClosedXml exception indicating "invalid file" with an InnerException (or exception Data property) providing details

**Did this work in previous versions?**

Unlikely :)

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
    try
   {
      using (var wb = new XLWorkbook("tdf100709.xlsx", eventTracking: XLEventTracking.Disabled))
      {
      }
   }
   catch (Exception ex)
   {
      Console.WriteLine(ex.GetType().ToString() + ": " + ex.Message);
      Console.WriteLine(ex.StackTrace);
   }
}
```
- [x] Input spreadsheet is LibreOffice tdf100709.xlsx

[tdf100709.xlsx](https://github.com/ClosedXML/ClosedXML/files/1957048/tdf100709.xlsx)

**Comment by igitur** [comment]
@kenleese Do you mean like in #892 ?

**Comment by kenleese** [comment]
@igitur @Pankraty Certainly. And thank you both for your considerable investments in this valuable technology.
