### ISSUE TITLE
cannot read string #N/A

### ISSUE THREAD

**Issue by davidbirchwork** [ClosedXML/ClosedXML#824]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

<package id="ClosedXML" version="0.92.1" targetFramework="net40" />

**What is the current behavior?**

When trying to read a spreadsheet cells with the text "#N/A" are read as blank
yes this is a weird thing to do I was seeking to write a unit test comparing ClosedXML with COM Interop - most things pass so far :-)

**What is the expected behavior or new feature?**

read the text "#N/A"

**Did this work in previous versions of our tool?  Which versions?**

Unknown

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    var _wb = new XLWorkbook(fname);
    if(_wb.Cell("Sheet1!A1").isEmpty()) Console.WriteLine(":(");
    var str = _wb.Cell("Sheet1!A1").GetString();
    if(str != "#N/A") Console.WriteLine(":(");
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[error.xlsx](https://github.com/ClosedXML/ClosedXML/files/1963407/error.xlsx)

**Comment by Pankraty** [comment]
What version of ClosedXML do you use?
I have a NullReferenceException at `_wb.Cell("Sheet1!A1").isEmpty()`.
If I change to `_wb.Worksheet("Sheet1").Cell("A1")` the reported issue reproduces too.

**Comment by igitur** [comment]
Latest version on NuGet is v 0.93.0-beta2. Please test with that.

**Comment by Pankraty** [comment]
> Latest version on NuGet is v 0.93.0-beta2. Please test with that.

It fails with the latest version as well. I just wondered how could `_wb.Cell("Sheet1!A1").isEmpty()` ever work. In code, I see that the method `XLWorkbook.Cell` did change for almost a year, and it does not work with cell addresses - only with named ranges.

**Comment by davidbirchwork** [comment]
Hi, I believe the two new open issues cover this issue more fully, so i'll close this one

thank you for a rapid response!
