### ISSUE TITLE
V.92 does not preserve leading ' for commented formula cells 

### ISSUE THREAD

**Issue by barrybriggs** [ClosedXML/ClosedXML#828]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.92

**What is the current behavior?**

When reading an Excel file with cells that have formulas commented out with a single quote, the single quote is not read. 

**What is the expected behavior or new feature?**

For a cell that has `'=if is not working` the leading single quote should be included as part of the text read by `cell.Value` -- see below (verbose for clarity):
     
                IXLCells cells = cellRange.Cells();
                foreach (IXLCell cell in cells) {
                    obj val=cell.Value;             // WAS '=if is not working
                    string s=val.ToString();    // s is =if is not working 
               }

Easy workaround, but thought you should know. 

**Did this work in previous versions of our tool?  Which versions?**

Yes/No/v0.XX

## Reproducibility
Should be obvious

**Comment by Pankraty** [comment]
That reminds me

**Comment by igitur** [comment]
This behaviour is by design.

**Comment by igitur** [comment]
This behaviour is by design. Refer to https://github.com/ClosedXML/ClosedXML/wiki/Cell-Values for setting cell values. In short, you can use `.SetValue()` or use `.Value = "''=if` (2 single quotes)

**Comment by barrybriggs** [comment]
I'm not sure this answer addresses the issue. In my case I am reading from a previously created Excel file (created manually). There are numerous cells that hold commented formulas, like `'=vlookup is a useful formula` for example -- when reading the file with ClosedXML the leading apostrophe/single quote is lost. 

Say then the text was rewritten to Excel, the text would be treated as a formula and an attempt would be made to evaluate it.

**Comment by igitur** [comment]
See, that's a totally different problem. Log a new issue and complete the entire issue template, including attaching a sample file that reproduces the issue.

**Comment by barrybriggs** [comment]
That's precisely the problem documented above :-)

**Comment by igitur** [comment]
No, it's not. You didn't attach a file. You also didn't provide code that I can copy and paste into the `Main` function of a console app to reproduce the problem. I believe the issue template was quite clear about what I require.
