### ISSUE TITLE
IsText Formula

### ISSUE THREAD

**Issue by LuciLiu** [ClosedXML/ClosedXML#834]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.91.0

**What is the current behavior?**

ClosedXML doesn´t support IsText formula.

**What is the expected behavior or new feature?**

ClosedXML  support IsText formula.

**Did this work in previous versions of our tool?  Which versions?**

No

**Comment by igitur** [comment]
This was definitely implemented somewhere in the past. Please retry with
the latest v0.93.0-beta2 from NuGet.

Francois Botha

**Comment by igitur** [comment]
Please complete the full issue template.
