### ISSUE TITLE
Worksheet default style is not read from file

### ISSUE THREAD

**Issue by Pankraty** [ClosedXML/ClosedXML#838]
One more part of #829 

## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.93.0-beta2

**What is the current behavior?**

On saving the default worksheet style is saved under `BuiltinId = 0` but it seems to be never read from there. As a result, the worksheet with custom style after an opening has the default style (Calibri, 11 pt, etc.)

**What is the expected behavior or new feature?**

We should read worksheet style from a file if it is specified. 

**Did this work in previous versions of our tool?  Which versions?**

No (tested at 0.91)

## Reproducibility

**Code to reproduce problem:**
```c#
        [Test]
        public void CanLoadWorksheetStyle()
        {
            using (var stream = TestHelper.GetStreamFromResource(TestHelper.GetResourcePath(@"Misc\BaseColumnWidth.xlsx"))) // The attached file
            using (var wb = new XLWorkbook(stream))
            {
                var ws = wb.Worksheet(1);

                Assert.AreEqual(8, ws.Style.Font.FontSize);
                Assert.AreEqual("Arial", ws.Style.Font.FontName);
                Assert.AreEqual(8, ws.Cell("A1").Style.Font.FontSize);
                Assert.AreEqual("Arial", ws.Cell("A1").Style.Font.FontName);
            }
        }
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[BaseColumnWidth.xlsx](https://github.com/ClosedXML/ClosedXML/files/1979264/BaseColumnWidth.xlsx)

**Comment by igitur** [comment]
This rings a bell and there was some reason why I couldn't fix it. Can't remember what that was now. Maybe it's fixable now.
