### ISSUE TITLE
reading empty cell issue

### ISSUE THREAD

**Issue by rajashree1402** [ClosedXML/ClosedXML#84]
sorry but this is not working : 
this is my code
Stream stream = new MemoryStream(ReadFile(File));
using (XLWorkbook workBook = new XLWorkbook(stream))
{
//Read the first Sheet from Excel file.
IXLWorksheet workSheet = workBook.Worksheet(1);

                //Create a new DataTable.

                //Loop through the Worksheet rows.
                bool firstRow = true;
                bool error = false;
                foreach (IXLRow row in workSheet.Rows())
                {
                    foreach (IXLCell cell in row.Cells())
                                {
                                    if (cellCnt < 11)
                                    {
                                        dt.Columns.Add(cell.Value.ToString());
                                    }
                                    else
                                    {
                                        break;
                                    }
                                    cellCnt++;
                                    firstRow = false;
                                }
}

what is happening here when i go for header its showing 20 cells
but in data row it showing 19 . as one contain blank value . But we need the blank value also.Please suggest where to modify it..

**Comment by igitur** [comment]
Please don't open a new issue for a comment. Please post your comment to #82 .
