### ISSUE TITLE
Saving File Issue

### ISSUE THREAD

**Issue by granticusmaximus** [ClosedXML/ClosedXML#842]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

version 0.92.1

**What is the current behavior?**

When I follow the routing path of my uri, it does not save the file in the format or even build the report I am trying to get. I will post the code below, but I am wanting it to save as "SystemMaintenance_" + DateTime.Now.ToString("yyyyMMddHHmm") + ".xls") and when the prompt comes through my browser, it only saves as the id that it is set, without saving as .xls

**What is the expected behavior or new feature?**

 I am wanting it to save as "SystemMaintenance_" + DateTime.Now.ToString("yyyyMMddHHmm") + ".xls") and when the prompt comes through my browser, it only saves as the id that it is set, without saving as .xls

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
**Business Service**
```c#
 public async Task<byte[]> GetSystemMaintenanceExcelFile(int id)
        {
            Systems sysRec = await dataAccess.GetSystemById(id);
            var excelFile = BuildSysMaintExcelFile(sysRec);
            return excelFile;
        }

        public byte[] BuildSysMaintExcelFile(Systems dataRec)
        {
            //Creating the workbook
            const int dataRowStart = 3;
            string templateName = "~/App_Data/SystemMaintenance_Template.xlsx";
            var workbook = new XLWorkbook(templateName);
            var worksheet = workbook.Worksheet(1);


            //string folderPath = "C:\\Excel\\";
            //if (!Directory.Exists(folderPath))
            //{
            //    Directory.CreateDirectory(folderPath);
            //}

            //default values for SysMaint
            var dt = BuildSysDetailLoaExcelTable(dataRec);

            worksheet.Cell(dataRowStart, 3).InsertData(dt.AsEnumerable());

            using (var ms = new MemoryStream())
            {
                workbook.SaveAs(ms);
                ms.Position = 0;
                return ms.ToArray();
            }
        }

        //Building the tables
        private DataTable BuildSysDetailLoaExcelTable(Systems record)
        {
            var dataTable = new DataTable();

            dataTable.Columns.Add("systemName", typeof(string));
            dataTable.Columns.Add("isActive", typeof(bool));
            dataTable.Columns.Add("localIAO", typeof(bool));
            dataTable.Columns.Add("localStaff", typeof(bool));
            dataTable.Columns.Add("informationOfficerRequired", typeof(bool));
            dataTable.Columns.Add("iaoRequired", typeof(bool));
            dataTable.Columns.Add("IAOs", typeof(string));
            dataTable.Columns.Add("StaffProcessors", typeof(string));
            dataTable.Columns.Add("StaffRevalidators", typeof(string));



            var dr = dataTable.NewRow();
            dr[0] = record.systemName;
            dr[1] = record.isActive;
            dr[2] = record.localIAO;
            dr[3] = record.localStaff;
            dr[4] = record.informationOfficerRequired;
            dr[5] = record.iaoRequired;
            dr[6] = record.IAOs;
            dr[9] = record.StaffProcessors;
            dr[11] = record.StaffRevalidators;
            return dataTable;
        }
```
**API**
```
        [HttpPost]
        [Route("api/file/{id}")]
        public async Task<HttpResponseMessage> GetSysMaintExcelFile(int id)
        {
            var response = await CreateFileResponse(rbs.GetSystemMaintenanceExcelFile(id), "SystemMaintenance_" + DateTime.Now.ToString("yyyyMMddHHmm") + ".xls");
            return response;
        }//Get
```

**Front End**
```
    getSysMaintXML: function getSysMaintXML(id) {
        var systemUrl = BaseURL + 'api/file/' + id;
        $.ajax({
            type: "POST",
            url: systemUrl, //call your controller and action
            contentType: "application/json; charset=utf-8",
            dataType: "json",
        })
    },
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by Pankraty** [comment]
Are you sure this is a ClosedXML issue? ClisedXML returns a byte array, and all the magic related to file names happens in CreateFileResponse method which I believe does not belong to ClosedXML (or does it?)

BTW, ClosedXML does not support XLS format - only XLSX.

**Comment by granticusmaximus** [comment]
I have tried using Google to figure out the right format of downloading the file, just have had no luck in doing so.

**Comment by granticusmaximus** [comment]
@Pankraty would `XLWorkbook.SaveAs(string file)` be a correct function of saving the file? And if so, how would I write that as to save it as "SystemMaintenance_" + DateTime.Now.ToString("yyyyMMddHHmm") + ".xlsx"

**Comment by vbjay** [comment]
A.  Do research on POST and other HTTP verbs.  GET is probably what you want.  
B.  ClosedXML just writes to the stream and gives you the correct binary data.  It has nothing to do with the filename.  
C.  Do research on what MIME is.

Following code adds the correct headers to show a pdf and when the user saves it, the filename is used when saving.
```c#
 private void SetupHeaders(string fileName) {
        Response.Headers.Add("Content-Disposition", "inline;filename={fileName}");
        Response.Headers.Add("Content-Transfer-Encoding", "binary");
        Response.ContentType = "application/pdf";
    }
```
No saving to a file path when you are returning it as the response to a web request doesn't make sense.

**Comment by granticusmaximus** [comment]
Thank you @vbjay

**Comment by vbjay** [comment]
Like everyone else said.  The filename may say xls but the content of the file will be xlsx.

**Comment by vbjay** [comment]
My example above was for an aspx page.  You will need to adjust for mvc.  I just wanted to show you what headers were involved.  Your ajax call will just return the binary response so you will have to handle that on your page.

**Comment by vbjay** [comment]
Oh, right.  One more thing.  Prob won't be inlining an excel file.

**Comment by granticusmaximus** [comment]
@vbjay I do not know what that means "Prob won't be inlining an excel file."

**Comment by vbjay** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

**Comment by igitur** [comment]
Definitely not a ClosedXML issue. But anyway, from what I remember downloading a file in jquery via the Ajax is not allowed due to security concerns. But I remember that from long ago. Maybe that has changed since.

**Comment by granticusmaximus** [comment]
@igitur is there a way in the api controller to write a function to download/save the file that is built by ClosedXML?

**Comment by vbjay** [comment]
You are already doing it. The controller will provide the file. What you can do is have a page that calls the API and writes the result to the response. You can then in your client open a new window to that page.

**Comment by igitur** [comment]
Post your code for `CreateFileResponse`.

**Comment by granticusmaximus** [comment]
`        protected HttpResponseMessage CreateFileResponse(Task<byte[]> data, string fileName = "", string contentType = "application/octet")
        {
            HttpResponseMessage result = new HttpResponseMessage(HttpStatusCode.OK);
            var tempData = data.Result;
            result.Content = new ByteArrayContent(tempData);
            result.Content.Headers.ContentType = new MediaTypeHeaderValue(contentType);
            result.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment");

            if (fileName != "")
            {
                result.Content.Headers.ContentDisposition.FileName = fileName;
            }

            return result;
        }`

**Comment by granticusmaximus** [comment]
```
        protected HttpResponseMessage CreateFileResponse(Task<byte[]> data, string fileName = "", string contentType = "application/octet")
        {
            HttpResponseMessage result = new HttpResponseMessage(HttpStatusCode.OK);
            var tempData = data.Result;
            result.Content = new ByteArrayContent(tempData);
            result.Content.Headers.ContentType = new MediaTypeHeaderValue(contentType);
            result.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment");

            if (fileName != "")
            {
                result.Content.Headers.ContentDisposition.FileName = fileName;
            }

            return result;
        }
```

**Comment by igitur** [comment]
Add a reference to this helper package: https://www.nuget.org/packages/ClosedXML.Extensions.WebApi

Then use the extension methods to delivery the workbook in your `ApiController`:

```c#
[HttpGet]
[Route("api/file/{id}")]
public async Task<HttpResponseMessage> DownloadFile(int id)
{
    var wb = await BuildExcelFile(id);
    return wb.Deliver("excelfile.xlsx");
}
```
The above code is for `GET` requests. Instead of using jquery ajax requests, use standard old `window.location.href = url;` in your Javascript. 

If you really HAVE to use `POST` (not advised), there are some hacky methods that create iframes etc. This is out of scope of ClosedXML. You can google for `jquery ajax download file post` if you want to use `POST` methods.

**Comment by granticusmaximus** [comment]
I am getting the following error under wb.Deliver:

`byte[] does nto contain a definition for Deliver and no extension method Deliver acception a first argument of type byte[] coulb be found`

**Comment by granticusmaximus** [comment]
I am not sure I understand this then. I am calling the class is wrapped in a byte array format. I am confused as to if I need to replace all byte arrays with XLWorkbook?

**Comment by igitur** [comment]
Generate your workbook and call `.Deliver` on it. Don't convert your workbook to a byte array.

**Comment by granticusmaximus** [comment]
What are the steps to do that? I am very much a greenhorn in both programming in C# and with ClosedXML

**Comment by granticusmaximus** [comment]
@igitur could you email me? Would that be better? grant_watson@cox.net

**Comment by igitur** [comment]
Hi. I think StackOverflow is better suited for general programming questions. I don't have the capacity for that. Check how many new issues were created in the past few days.

**Comment by granticusmaximus** [comment]
Gotcha
