### ISSUE TITLE
Get Cell's width in Pixel

### ISSUE THREAD

**Issue by mnts26** [ClosedXML/ClosedXML#846]
**Do you want to request a *feature* or report a *bug*?**
- [ x] feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.75.0.0

**What is the expected behavior or new feature?**
 
If this feature is not available it will be nice to get cell is size in pixel. Let's discuss.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

**Code to reproduce problem:**
```c#
public void ReadExcel(string path, int sheet_number)
        {
            try
            {
                temp_wb = new XLWorkbook(path);
                temp_wsh = temp_wb.Worksheet(sheet_number);
                IXLRange work_sheet_range = temp_wsh.RangeUsed(true);
                max_row = work_sheet_range.RangeAddress.LastAddress.RowNumber;
                max_col = work_sheet_range.RangeAddress.LastAddress.ColumnNumber;
                for (int row = 1; row <= max_row ; row++)
                {
                    list_of_kjs_cell = new List<IXLCell>();
                    for (int col = 1; col <= max_col ; col++)
                    {
                        IXLCell cell = temp_wsh.Cell(row, col); 
                        
                        if(!string.isNullOrEmpty(cell.GetString()) && cell.IsMerged()){
                            // Getting cell's size in pixel. 
                            Int width = cell.WidthInPixel();
                        }

                        
                    }
                }
                temp_wb.Dispose();
            }
            catch (System.IO.IOException e)
            {
                Console.WriteLine(e.Message);
            }
        }
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
It's dependent on your display settings, but I think this is a good estimate:

```c#
var width = cell.WorksheetColumn().Width;
var widthInPixels =(width*256+128/7)/256*7;
```

**Comment by mnts26** [comment]
How about row height. Is it same way?

**Comment by igitur** [comment]
Sorry, the above code will return the width of the text inside the cell. The cell also contains padding on the sides of the text, so if you want to get the width of the full cell, including padding, this should work.

```c#
var width = cell.WorksheetColumn().Width;
var widthInPixels = width * 7;
```

Remember that it's an estimate!

And as #858 shows, there are definitely still problems with calculating dimensions. It would help if we could find good specifications of how to do it. Maybe you can help search?

**Comment by igitur** [comment]
I don't know where the 7 comes from. That's just how I inherited the code from the previous developers.

**Comment by aboryczko** [comment]
I've ended up here from Google with the described issue and the "7" did not work for me and I ended up with using something like this:
```csharp
public static int GetWidthInPixels(this IXLColumn column)
{
    var width = column.Width;
    return width switch
    {
        < 0 => throw new ArgumentOutOfRangeException(nameof(column), "Column Width cannot have a negative number"),
        < 1 => (int)Math.Round(width * 12, 0, MidpointRounding.AwayFromZero),
        _ => 5 + (int)Math.Round(width * 7, 0, MidpointRounding.AwayFromZero)
    };
}
```
note that this is for 100% DPI
