### ISSUE TITLE
Named ranges are not deleted when the worksheet is deleted

### ISSUE THREAD

**Issue by Pankraty** [ClosedXML/ClosedXML#848]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

Current `develop`, 0.92.1

**What is the current behavior?**

When the worksheet deleted the named ranges remain in the workbook's collection which causes exceptions on attempt to work with ranges and also produces a mallformed XLSX file.

**What is the expected behavior or new feature?**

The named ranges must be deleted with the worksheet.

**Did this work in previous versions of our tool?  Which versions?**

Did not check.

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
    using (var wb = new XLWorkbook())
    {
        var ws1 = wb.Worksheets.Add("Sheet1");
        var ws2 = wb.Worksheets.Add("Sheet2");

        wb.NamedRanges.Add("Named range", ws2.Range("A1:C3"));

        ws2.Delete();
        Console.WriteLine($"Named ranges count: {wb.NamedRanges.Count()}, expected: 0");
    }
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[848_sample.xlsx](https://github.com/ClosedXML/ClosedXML/files/1999425/848_sample.xlsx)

**Comment by Pankraty** [comment]
Perhaps I am wrong. Global ranges should not be deleted, but their references should become `#REF!A1:C3` instead.

**Comment by igitur** [comment]
I agree that the named range should become `#REF!A1:C3`. Also, I think that `IXLNamedRanges` should get 2 functions: `IEnumerable<IXLNamedRange> ValidNames()` and `IEnumerable<IXLNamedRange> InvalidNames()` that mimic Excel's `Names with Errors` and `Names without Errors`:

![image](https://user-images.githubusercontent.com/145854/39992431-0e0407f0-5773-11e8-89d3-5902e2e90346.png)

**Comment by Pankraty** [comment]
> I agree that the named range should become `#REF!A1:C3`.

Do we have a way to construct invalid ranges like this? I didn't find it yet.

`ValidNames()`, `InvalidNames()` may be confusing. `ValidRanges()`, `InvalidRanges()` would be more clear, IMHO.

**Comment by CPSibo** [comment]
This still appears to be a problem (as of 0.93.1 from nuget) for workbook-scoped ranges that point to a worksheet being deleted. It produces a corrupt spreadsheet unless you delete the range at the workbook level first.

**Comment by Pankraty** [comment]
@CPSibo please create a new issue with the code sample and the produced corrupted file.
