### ISSUE TITLE
Reading dates wrong, gives bad data

### ISSUE THREAD

**Issue by 0101Jakob** [ClosedXML/ClosedXML#849]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.92.1.0

**What is the current behavior?**

Reading some dates gives wrong output.
Trying to read the date: 
03-01-1904  12:00:00
Gives:
03-05-2022  00:00:00

Adding just 1 sec, gives the correct read:
03-01-1904  12:00:01
Gives:
03-01-1904  12:00:01

Data is later in the document converted to [t]:mm:ss, thats the reason for the dates:
60:00:00
60:00:01

**What is the expected behavior or new feature?**

See above.

**Did this work in previous versions of our tool?  Which versions?**

No idea

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Insert dates

**Code to reproduce problem:**
```c#
public void Main()
{
    var workbook = new XLWorkbook("Path"); // Insert path 
    var worksheet = workbook.Worksheet(1);

    var cell1 = worksheet.Row(1).Cell(1);
    var cell2 = worksheet.Row(2).Cell(1);

    string cell1_string = cell1.GetString();
    //System.Windows.Forms.MessageBox.Show(cell1_string);

    string cell2_string = cell2.GetString();
    //System.Windows.Forms.MessageBox.Show(cell2_string);
}
```
I attached a sample spreadsheet. 

[TestDocument.xlsx](https://github.com/ClosedXML/ClosedXML/files/2000254/TestDocument.xlsx)

**Comment by igitur** [comment]
I can't reproduce this with the latest `develop` branch. Those 2 strings give me:
![image](https://user-images.githubusercontent.com/145854/39992127-0acdd986-5772-11e8-852b-61e0dbe4d6b9.png)

**Comment by 0101Jakob** [comment]
Thanks for the reply.

I have not looked for develop branch. Will try to find one.

Also I was thinking it might be a language related problem since you get the correct strings.
I am currently using danish with "," as delimiter.
Will try to change this to see if that makes a different.

I will get back on this tread when I have done some testing.

**Comment by igitur** [comment]
Ah, crucial piece of info you added there. This could be related to #830

**Comment by igitur** [comment]
Try  with v0.93-beta4 from NuGet

**Comment by 0101Jakob** [comment]
v0.93-beta4 was a success!
I see no trace of the problem in this build.
Thanks!
