### ISSUE TITLE
Pivot tables are broken on Save

### ISSUE THREAD

**Issue by LeifLazar** [ClosedXML/ClosedXML#850]
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.92.1 (also reproduced on 0.93.0-beta4)

**What is the current behavior?**

When opening and saving a file that contains a pivot table, something happens to the pivot table. When we open the file with Excel the following dialog appears: "There's already data in [TestTable.xlsx]Sheet1. Do you want to replace it?".
If we click the "Yes" button, the pivot table seems to be properly restored.
If we click the "No" button, the pivot table gets removed. The data is still there, but it's not part of a pivot table anymore.

**What is the expected behavior or new feature?**

Nothing should happen to the file, especially since nothing was done to it: no write or otherwise file-altering operations.

**Did this work in previous versions of our tool?  Which versions?**

Yes, it worked on 0.85.0. On 0.86.0 the library threw a System.NullReferenceException.
The observed behavior started in version 0.87.1. I tested all versions from 0.87.1 to 0.93.0-beta4 and reproduced this issue on all of them with the same code.

## Reproducibility

**Code to reproduce problem:**
```c#
public static void Main(string[] args)
{
    using (XLWorkbook wb = new XLWorkbook("TestTable.xlsx"))
    {
        wb.Save();
    }
}
```
- [x] I attached a sample spreadsheet. 
[TestTable.xlsx](https://github.com/ClosedXML/ClosedXML/files/2001189/TestTable.xlsx)

**Comment by igitur** [comment]
Fixed in #856, but I see there's another problem where the "Show values row" is not implemented propertly. I'll address that in a separate issue.
