### ISSUE TITLE
List<T> Support

### ISSUE THREAD

**Issue by dotnetnicholas** [ClosedXML/ClosedXML#854]
- [] Bug
- [X ] Feature

**Version of ClosedXML**

N/A

**What is the current behavior?**

N/A

**What is the expected behavior or new feature?**

Support for List<T> as an input type would be super nice to have.  I love the project and recommend it whenever I can, however, I run into memory issues with super large data sets from time to time when using DataTables due to their inherently large memory usage.  Obviously this isn't a problem on machines running in 64 bit mode with a super large amount of memory at their disposal but that isn't always the case.

**Did this work in previous versions of our tool?  Which versions?**

N/A

**Comment by igitur** [comment]
Support for lists where? Please give a code sample, as I begged for in the issue template.

**Comment by igitur** [comment]
You can achieve this with:
```c#
var ws = workbook.AddWorksheet("Sheet1");
ws.FirstCell().InsertData(objectsList);
```

More info at https://github.com/ClosedXML/ClosedXML/wiki/Inserting-Data

**Comment by igitur** [comment]
You see the problem with "obvious"?

**Comment by vbjay** [comment]
A.  We have generics now.  

List<Customer> customers=new List<Customer>();
customers.Add(new Customer("John Smith","123@123.com"));
customers.Add(new Customer("SaraSmith","321@321.com"));

B.  The issue template makes it so we can get issues taken care of.  We require them to be filled out.  

C.  As @igitur pointed out, our wiki has the answer.
