### ISSUE TITLE
Insert negative number of columns may fail

### ISSUE THREAD

**Issue by Pankraty** [ClosedXML/ClosedXML#855]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.92.1, `develop`

**What is the current behavior?**

When the large range is shrunk with `range.InsertColumnsAfter(-X);` it may fail with the exception "An item with the same key has already been added. Key: 25".

**What is the expected behavior or new feature?**

Range has to shrink.

**Did this work in previous versions of our tool?  Which versions?**

Don't know

## Reproducibility

**Code to reproduce problem:**
```c#
// This works fine
public void Main()
{
            using (var wb = new XLWorkbook())
            {
                var ws = wb.AddWorksheet("Sheet 1");
                var range = ws.Range("A2:Z2");
                range.SetValue(1);
                range.InsertColumnsAfter(-25);
                // range becomes A2:A2
            }
}

// This fails
public void Main()
{
            using (var wb = new XLWorkbook())
            {
                var ws = wb.AddWorksheet("Sheet 1");
                var range = ws.Range("A2:XFD2");
                range.SetValue(1);
                range.InsertColumnsAfter(-16359);
                // failure; expected range A2:Y2
            }
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
So we should just disallow non-positive numbers, right?

**Comment by vbjay** [comment]
Yep.  InsertColumnsAfter should always be >0

**Comment by Pankraty** [comment]
I'd rather figure out why -25 and -16539 behave differently. 
Now we have code 
```
range.InsertColumnsAfter(tempRng.ColumnCount() - range.ColumnCount(), true)
```
It makes `range` be the same width as `tempRng` no matter how wide they are originally. With that limitation this code will be broken.

**Comment by Pankraty** [comment]
> Yep. InsertColumnsAfter should always be >0

I would agree if this was done from the beginning.

**Comment by igitur** [comment]
From the beginning? Meaning you don't want to cause a breaking change? I think this is worth a breaking change.

**Comment by vbjay** [comment]
We are still <1.0 breaking changes are fine.

**Comment by Pankraty** [comment]
It fails to insert a cell with address `Y2`. We don't know in which other obstacles this may happen. If we just prohibit this particular case we'll just disguise the root issue.
