### ISSUE TITLE
Save a file cell is changed

### ISSUE THREAD

**Issue by mnts26** [ClosedXML/ClosedXML#858]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.75.0.0

**What is the current behavior?**

When i save  excel file  cell size changed. (or changed page breaks)
before save
![before](https://user-images.githubusercontent.com/331587/40166941-b6eccd00-59fa-11e8-99fc-6d6dfca491a5.png)
after save.
![after](https://user-images.githubusercontent.com/331587/40166940-b6c66516-59fa-11e8-89b7-e63dedbd362c.png)

**What is the expected behavior or new feature?**
Not changing cell size.

**Code to reproduce problem:**
```c#
public void Main()
{
            var dd = new XLWorkbook(@file);
            dd.Save();
}
```
- [] I attached a sample spreadsheet.  (You can drag files on to this issue)
[after_save.xlsx](https://github.com/ClosedXML/ClosedXML/files/2012509/after_save.xlsx)
[before_save.xlsx](https://github.com/ClosedXML/ClosedXML/files/2012510/before_save.xlsx)

**Comment by igitur** [comment]
Attach the file.
