### ISSUE TITLE
Excel's vlookup is not case sensative but ClosedXML's is

### ISSUE THREAD

**Issue by zgirod** [ClosedXML/ClosedXML#861]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.92.1

**What is the current behavior?**

If you look at the attached excel there is a very basic vlookup.  One of the lookups matches exactly and one of them matches but not on case.  In excel the vlookup gets the value for both vlookups however in ClosedXML the exact match gets a value while the case mismatch throws an error.

**What is the expected behavior or new feature?**

I would think that ClosedXML would match the behavior of excel and be case insensitive for vlookups.

**Did this work in previous versions of our tool?  Which versions?**

No

**Code to reproduce problem:**
```c#
public void Main()
{

var filepath = @"...\case sensitive example.xlsx";//update file location to match file location on your computer
            var excel = new XLWorkbook(filepath);
            var worksheet = excel.Worksheets.SingleOrDefault(x => x.Name == "Sheet1");

            var valueSunday = worksheet.Cell(2, 8).Value;//works
            var valueMonday = worksheet.Cell(3, 8).Value;//throws error
}
```
- [ X] I attached a sample spreadsheet.  (You can drag files on to this issue)

[case sensitive example.xlsx](https://github.com/ClosedXML/ClosedXML/files/2017084/case.sensitive.example.xlsx)

**Comment by Pankraty** [comment]
Special thanks for filling in the complete issue template! Such a rare case :)

**Comment by zgirod** [comment]
@Pankraty the least I could do.  Thanks for a great open source tool.

**Comment by AndrewSpalding** [comment]
FYI, ClosedXML case sensitivity differs from Excel in situations other than vlookup.
I have "S" in C", and the formula `=IF(C2="s","Match","NoMatch")`  in D2: in Excel this returns "Match" and in ClosedXML it returns "NoMatch".
I can open a separate issue with code to reproduce, if it looks like this is a separate issue.
