### ISSUE TITLE
Unprotect not functioning? Example needed.

### ISSUE THREAD

**Issue by michimkc** [ClosedXML/ClosedXML#866]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.92.1.0

**What is the current behavior?**

Unprotect on IXLWorksheet reports "Invalid Password" even if string passed to Unprotect() is the correct password, or if the excel sheet is protected without any password.

**What is the expected behavior or new feature?**

Unprotect should unprotect the sheet, given the correct password.

**Did this work in previous versions of our tool?  Which versions?**

Have not tested on previous versions.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.

        
            var wb = new XLWorkbook("protectedsheets.xlsx");

            var ws = wb.Worksheet(1);

            // sheet 1 - protected sheet with no password
            try
            {
                ws.Unprotect();
            }
            catch (Exception e)
            {
                Console.WriteLine("Could not unprotect sheet. Error was: " + e.Message);
            }

            // sheet 2 - protected sheet with password "abc"
            ws = wb.Worksheet(2);
            
            try
            {
                ws.Unprotect("abc");
            }
            catch (Exception e)
            {
                Console.WriteLine("Could not unprotect sheet. Error was: " + e.Message);
            }
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

[protectedsheets.xlsx](https://github.com/ClosedXML/ClosedXML/files/2024969/protectedsheets.xlsx)

**Comment by igitur** [comment]
Your workbook contains a new hashing method (apparently introduced in Exce 2013) that we don't implement yet. 

Be patient with this one, please.

Reference:
https://www.spreadsheet1.com/sheet-protection-2013.html

**Comment by igitur** [comment]
I'm jotting down some question for myself and the other developers:

When we add support for the SHA-512 hashing algorithm:
- Are we going to give the user the option to save files using either old or new algorithm. I think not.
- When saving new workbooks, how is the salt generated?
- When saving existing workbooks that are already protected with SHA-512, so we reuse the existing salt or generate new salt?

cc @Pankraty

**Comment by Cthuflu** [comment]
> Not sure. I'm hesitant to support something that I can't test easily myself. Do you perhaps have access to a Excel 2010 instance?
The file is readable in Excel 2010, Sheet2 is not protected.

**Comment by igitur** [comment]
Thanks @Cthuflu . So older versions of Excel just ignore the protection? You can edit any of the cells on Sheet2?

By the way, how did you arrive on this issue? Just curious.

**Comment by Cthuflu** [comment]
@igitur I think the sheet just isn't protected. Here is Visual Basic code that opens it and displays a cell in it.
```vb.net
Imports ClosedXML.Excel

Module Module1

    Sub Main()
        Dim wb = New XLWorkbook("protectedsheets.xlsx")
        Dim ws = wb.Worksheet(2)

        Console.WriteLine(ws.Cell(2, 1).Value)
        Console.Read()

    End Sub

End Module
```

I arrived at this issue because I was having issues with a protected file that was made in a newer version of Excel, I just haven't opened a new issue on it yet because I would need to make a test file with that version. 

(If you're curious, it causes a System.IO.FileFormatException on `New XLWorkbook("protectedfile.xlsx")` if the file is protected with a newer version of Excel.)

**Comment by amirvenus** [comment]
I am having a similar issue. 

An excel file created with Excel 2016 cannot be unprotected (it says invalid password).
