### ISSUE TITLE
Cannot shiftLeft Column when using Column.Delete()

### ISSUE THREAD

**Issue by ggever** [ClosedXML/ClosedXML#867]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.92.1.0

**What is the current behavior?**

When I use Column.Delete(). The result is not good.
I attached the original file and the result file. I just wanna delete Column 2.

**What is the expected behavior or new feature?**

It's working like we are using Microsoft Excel

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```VB.Net
Sub Main(args As String())
    ...
    export.DeleteColumn(2)
    ....
End Sub

Public Sub DeleteColumn(ByVal colIndex As Integer)
    If Not ws Is Nothing Then
        ws.Column(colIndex).Delete()
    End If
End Sub
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[currentResultFile.xlsx](https://github.com/ClosedXML/ClosedXML/files/2025479/currentResultFile.xlsx)
[expected.xlsx](https://github.com/ClosedXML/ClosedXML/files/2025480/expected.xlsx)
[originalFile.xlsx](https://github.com/ClosedXML/ClosedXML/files/2025481/originalFile.xlsx)

**Comment by igitur** [comment]
Please try with v 0.93.0-beta4

**Comment by ggever** [comment]
Sorry, Is there something wrong in  v 0.93.0-beta4? I just Open and SaveAs. The result file cannot be openned by Microsoft Excel(moreover, the size of original file is 41Kb, but the result is 121Kb) . I also tried v 0.93.0-beta1 and v 0.93.0-beta2, but had same result. Only using v 0.92.1 can work normally.
I attached the originalFile. Tks so much for your supporting.

**Comment by vbjay** [comment]
@ggever Clone this repo checkout develop branch and build. Run a git bisect building the project each time. 
8876d46fc53674bd1caaf1f4cf7f930156a44f89 is 92.0 beta 1. That's the commit you mark as good.  Check develop head. See if you can find the commit that caused this to happen. Give us the commit hash.

**Comment by ggever** [comment]
Thank you. I solved it.

**Comment by igitur** [comment]
What was the problem and solution? Other users might benefit from your feedback.

**Comment by ggever** [comment]
It's my bad. When opening the Workbook, the feature EventTracking is setted to XLEventTracking.Disabled. When I enable this feature again, it works normally.
