### ISSUE TITLE
ClosedXML - Cannot install 

### ISSUE THREAD

**Issue by JameemaMoses** [ClosedXML/ClosedXML#871]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.67.2

**What is the current behavior?**

My current version of ClosedXML does not expose properties to insert an image into excel sheet.

**What is the expected behavior or new feature?**

I want to upgrade ClosedXML version to 0.92.1.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
Hi,

I have an issue updating closedXML dll in my project. Below is the detailed explanation of my issue : Requirement : To insert an image into Excel sheet. 
Currently using version : ClosedXML - 0.67.0 
Platform : .NET/ VS2012/Framework 4.0

When I tried to upgrade closedXML to 0.92.1, I got the below error :

'FastMember.Signed' already has a dependency defined for 'Microsoft.CSharp'.

Note : I tried re installing nuget package manager but that didn't resolve the issue.

Please suggest how to fix this issue. I'm really stuck on this from pretty long time.

**Comment by igitur** [comment]
This isn't a ClosedXML issue, but if you google for `"already has a dependency defined for 'Microsoft.CSharp'."` you get lots of hits and solutions. The problem seems to be an outdated version of NuGet that is packaged with Visual Studio 2012. I think the only way is to upgrade your installation of Visual Studio. You can download and install Visual Studio 2017 Community for free at https://www.visualstudio.com/downloads

**Comment by igitur** [comment]
No, the only way is probably to download the source code of all the projects involved and compile them yourself. Note that if you are releasing software that you will have to abide by the license restrictions of each project.

**Comment by vbjay** [comment]
You do realize vs is backwards compatible?  You can open the project in
2017. It will still use the framework version in your project.
