### ISSUE TITLE
FormulaWithCircularReferenceFails2 test fails

### ISSUE THREAD

**Issue by igitur** [ClosedXML/ClosedXML#882]
`XLCellTests.FormulaWithCircularReferenceFails2` was never marked with the `Test` attribute and was skipped. It also fails with a `FormulaWithCircularReferenceFails2`

**Comment by jahav** [comment]
This was fixed in #1352 (924ba90aa1bc6f57b463039e7238c674110866aa), so it landed in 0.95.

Closing.
