### ISSUE TITLE
Need "Reapply Filter" functionality... SetAutoFilter().Column(...) across multiple columns apply filter but doesn't "actually" filter, only by last filter

### ISSUE THREAD

**Issue by jasonvogel** [ClosedXML/ClosedXML#886]
- [x] Feature

**Version of ClosedXML**

e.g. 0.87.1

**What is the current behavior?**

Filter is set, but the data is NOT actually filtered on each column.

**What is the expected behavior or new feature?**

I'm using SetAutoFilter().Column(...).AddFilter(...) on multiple, _different_ columns.  ClosedXML is applying the filter **_criteria_**.  I can open the spreadsheet in Excel and verify that.  However, the filter is not actually being applied though except for the last call to SetAutoFilter(). 

So in column 2, there are 3 different values [filter is set to only one of those values] and column 4 has 1 unique value.  Three rows will be shown.  Clicking "Reapply Filter" in Excel, will correctly filter down to one row.

So technically, I believe ClosedXML is working correctly as far as apply the filter, just need the "refresh" support.

**Did this work in previous versions of our tool?  Which versions?**

Don't know

**Comment by Pankraty** [comment]
Please attach a spreadsheet and provide sample code.
