### ISSUE TITLE
checkboxes support

### ISSUE THREAD

**Issue by yaronmil** [ClosedXML/ClosedXML#89]
is it possible to check checkboxes when manipulating a document ?

**Comment by igitur** [comment]
Checkboxes?

**Comment by yaronmil** [comment]
http://www.pcworld.com/article/2042382/software-productivity/add-checkboxes-to-an-excel-spreadsheet.html

**Comment by igitur** [comment]
Sorry, form controls aren't supported.

**Comment by atgrau** [comment]
It's not implemented yet? If so, it should be nice it implementation using OpenXML, I use to use something like this:

```
// key is the Id of the checkbox, usually something like "rIdX", where X is a uint (1,2,3,4,5..)
public void SetCheckBox(string sheetName, string key)
{
	// This like gets a worksheet part by, but it can be modified as u wish
	WorksheetPart worksheetPart = GetWorksheetPartByName(Document, sheetName);

	foreach (var control in worksheetPart.ControlPropertiesParts)
	{
		string name = worksheetPart.GetIdOfPart(control);
		if (name == key)
		{
			control.FormControlProperties.Checked = CheckedValues.Checked;
		}
	}
}
```

**Comment by mhagesfeld** [comment]
Agreed with @atgrau - would be very nice if this was implemented, and his solution is simple and effective.  Is there any chance of this feature being added, @igitur?

**Comment by igitur** [comment]
Please submit your proposal as a pull request.
