### ISSUE TITLE
Parsing of rich text inside inline string fails

### ISSUE THREAD

**Issue by 1omg** [ClosedXML/ClosedXML#91]
Hello. Try to read xlsx file, problem with multiline cell. My code:

```c#
            var workbook = new XLWorkbook(path);
            var ws1 = workbook.Worksheet(3);
            workbook.SaveAs("tmp.xlsx");
            
            int rowCount = 20; //example
            //first row headers
            for(int i = 1 ;i<rowCount;i++)
            {
                var row = ws1.Row(i);
                IXLCell cell = row.Cell("E");     //.Cell(5); 
                bool isEmpty = cell.IsEmpty();      //always empty on this column, but in original have 6 lines
                var val = cell.Value;   //cell.
                //vals += val + Environment.NewLine;
            }
```

Values at file:
![23b2a447f9](https://cloud.githubusercontent.com/assets/11645046/20098570/27b00eec-a5bd-11e6-8688-35d14f0bc9a1.jpg)

If i open workbook and resave it from code (.SaveAs) - values not lost. But in code (.Value , .GetString etc) it seens like empty cell.
What i do wrong?

**Comment by igitur** [comment]
Would you mind attaching the workbook?

**Comment by 1omg** [comment]
[tmp.xlsx](https://github.com/ClosedXML/ClosedXML/files/579205/tmp.xlsx)
3rd worksheet / column E

**Comment by igitur** [comment]
I see there is a bug in ClosedXML. Your workbook contains a rare combination of rich text inside an inline string. The normal way to save an Excel file is to use shared strings. I will add a fix. 

But how are you generating this workbook? Is it also programmatically?

**Comment by 1omg** [comment]
Workbook generating on external services, cant change it.
When i can wait a fix? Or what I can do to fix it?

**Comment by igitur** [comment]
You can check my PR in #97 for the fix.

**Comment by 1omg** [comment]
Thank you so much! I will try in the evening.
