### ISSUE TITLE
NumberFormat: #. ##0,00 _ € is changed to #, ##000 _ €

### ISSUE THREAD

**Issue by ChristianSpreckelsen** [ClosedXML/ClosedXML#911]
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.9.21 (Latest Version on NuGet)

**What is the current behavior?**

I try to save a number of type double (9999.99) in a german format like this: 9.999,99 €.

ws.Column(co).Style.NumberFormat.Format = "#.##0,00 _€" changed to "#, ##000 _ €"

**What is the expected behavior or new feature?**

ws.Column(co).Style.NumberFormat.Format = "#.##0,00 _€" keep "#.##0,00 _€"

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
[exportFzVerk20180614123716113.xlsx](https://github.com/ClosedXML/ClosedXML/files/2102063/exportFzVerk20180614123716113.xlsx)
```c#
static void Main(string[] args)
        {
            var workbook = new XLWorkbook();
            var ws = workbook.Worksheets.Add("Style NumberFormat");
            var co = 2;
            var ro = 1;
            ws.Column(co).Style.NumberFormat.Format = "#.##0,00 _€";
            ws.Cell(++ro, co).Value = "47147.12";
            ws.Cell(++ro, co).Value = Math.Round(Convert.ToDecimal(47147), 2);
            double test = 47147.12;
            ws.Cell(++ro, co).Value = test;
            ws.Cell(++ro, co).Value = Math.Round(Convert.ToDecimal(test), 2);
            ws.Cell(++ro, co).Value = "47147";
            ws.Cell(++ro, co).Value = Math.Round(Convert.ToDecimal(47147), 2);
            test = 47147;
            ws.Cell(++ro, co).Value = test;
            ws.Cell(++ro, co).Value = Math.Round(Convert.ToDecimal(test), 2);
            ws.Column(co).AdjustToContents();
            workbook.SaveAs("StylesNumberFormat.xlsx");
        }
```

**Comment by igitur** [comment]
You'll have to escape the format code. I found this by replicating the desired format in Excel and inspecting the `formatCode` in `styles.xml` inside the xlsx file.

`ws.Column(co).Style.NumberFormat.Format = @"#.##0\,00,_€";`

**Comment by ChristianSpreckelsen** [comment]
Thank you for your answer. Unfortunately that does not work yet. Now I have 47,147.12 instead of 47,147.12. The thousands delimiter must be a point. It is always exchanged for a comma.

**Comment by igitur** [comment]
Replicate what you want in Excel, save the file, rename to `.zip`, open it, and open the `styles.xml` file inside that. You can find the internal format code that Excel saves in that file.

**Comment by ChristianSpreckelsen** [comment]
That's it! ws.Column(co).Style.NumberFormat.Format ="#,##0.00\\ \"€\"";
The problem was probably Excel! Thank you!

**Comment by jabok** [comment]
i dont get it. how did you solve this?

**Comment by jahav** [comment]
@jabok 
1. Open Excel and in a set a desired custom number format of a cell (Format Cell dialog, tab Number, Category: Custom).
2. Save the file (e.g. template.xlsx].
3. Rename the  template.xlsx to template.zip (Excel files are basically only zip files with a bunch of xml inside)
4. Open the template.zip and find the styles.xml file (most likely xl/styles.xml)
5. Find the format in the file, it will be in some tag numFmt.
6. Use the format taken from xml as an argument of ws.Column(co).Style.NumberFormat.Format.

The problem is that what you see in the Excel dialogue is not what is actually saved in the xml file and we need to set the value to the value from xml file. The format strings are not identical, e.g. there are some escaping, see the example image.

![image](https://user-images.githubusercontent.com/7634052/190031720-1d6b3f2c-2690-4316-b95d-faece6ecb080.png)

**Comment by keytrap-x86** [comment]
> @jabok
> 
> 1. Open Excel and in a set a desired custom number format of a cell (Format Cell dialog, tab Number, Category: Custom).
> 2. Save the file (e.g. template.xlsx].
> 3. Rename the  template.xlsx to template.zip (Excel files are basically only zip files with a bunch of xml inside)
> 4. Open the template.zip and find the styles.xml file (most likely xl/styles.xml)
> 5. Find the format in the file, it will be in some tag numFmt.
> 6. Use the format taken from xml as an argument of ws.Column(co).Style.NumberFormat.Format.
> 
> The problem is that what you see in the Excel dialogue is not what is actually saved in the xml file and we need to set the value to the value from xml file. The format strings are not identical, e.g. there are some escaping, see the example image.
> 
> ![image](https://user-images.githubusercontent.com/7634052/190031720-1d6b3f2c-2690-4316-b95d-faece6ecb080.png)


In addition to this, for future references.

If in your `styles.xml` you have for example :
![image](https://github.com/user-attachments/assets/b0318c8c-fc55-4ef7-ab9c-650845d10f95)
Then you should do this :

```csharp
worksheet.Column(dataCol.Value).Style.NumberFormat.Format = @"#,##0.00 ""€""";
```

By the way this is the format for french currency that will show this in Excel when applied :
![image](https://github.com/user-attachments/assets/d4d9595b-e4be-4b10-b614-9b1172ce5c9d)
