### ISSUE TITLE
Hiding Subtotals Column in Pivot Table in C#

### ISSUE THREAD

**Issue by nnmmss** [ClosedXML/ClosedXML#914]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.87

**What is the current behavior?**

The SubTotal Columns are visible after creating Pivot Table

**What is the expected behavior or new feature?**

How can hide the subtotals Columns which are created in Pivot Table?

**Did this work in previous versions of our tool?  Which versions?**

Yes/No/v0.XX

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
   using (var workbook = new XLWorkbook())
                    {
                        var ws = workbook.Worksheets.Add("Data Source");
                        var table = ws.Cell(1, 1).InsertTable(dtFinal, "Data Source", true);
                        ws.Columns().AdjustToContents();

                        var ptSheet = workbook.Worksheets.Add("PivotTable");
                        var pt = ptSheet.PivotTables.AddNew("PivotTable", ptSheet.Cell(1, 1), table.AsRange());
                        pt.Subtotals = XLPivotSubtotals.DoNotShow;
                        pt.ShowGrandTotalsColumns = false;
                        pt.ShowGrandTotalsRows = false;

                        pt.RowLabels.Add("ptime");
                        pt.ColumnLabels.Add("Substation");
                        pt.ColumnLabels.Add("Voltage");
                        pt.ColumnLabels.Add("ColumnTitle");
                        pt.ColumnLabels.Add("S6_NAME");
                        pt.Values.Add("ValueAmount");
                        pt.Subtotals = XLPivotSubtotals.DoNotShow;
                        ptSheet.Columns().AdjustToContents();
                        
                        workbook.SaveAs("D:\\Temp\\XML\\PivotTable2.xlsx");

                    }
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
> If you are logging a possible bug or feature request, please test with the latest development build first.

**Comment by nnmmss** [comment]
Do you mean it is not possible with version 0.87?

**Comment by igitur** [comment]
I mean we're interested only in bugs and feature requests tested against the *LATEST* version.

**Comment by Pankraty** [comment]
The team has far not enough resources to support multiple versions simultaneously. If the bug existed in some of the previous versions and has been fixed in later releases it will remain in old versions forever. If it can, however, be reproduced in the latest version there is a non-zero chance it'll be fixed.

**Comment by pavelpykhtin** [comment]
This problem is still relevant in 0.95.4. 
It seems that values of ShowGrandTotalsColumns and ShowGrandTotalsRows properties are ignored.
