### ISSUE TITLE
Error Exporting datatable to Excel (.xlsx) 'Unable to set cell value to ' + uniqueidentifier

### ISSUE THREAD

**Issue by Wowdude07** [ClosedXML/ClosedXML#918]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

Less of a bug, more of a workaround, but I the person who provided the answer thought it might be valuable to communicate it to the developers.

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.93.0-rc3 (through Visual Studio NuGet)

**What is the current behavior?**
When exporting a datatable gathered from a SQL table, the uniqueidentifier field (at column index 0) cannot be exported using the standard export to Excel feature I get the error: "Unable to set cell value to [uniqueidentifier]". I have attempted to change the index of the column in the table but this has no effect.

**What is the expected behavior or new feature?**
I expected the uniqueidentifer to be treated as a text/string field.

**Did this work in previous versions of our tool?  Which versions?**
Unknown - Haven't attempted on previous versions.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
Converted from original VB.NET
````c# 
private void ExportToxlsxUsingClosedXML()
{
    string appPath = Directory.GetCurrentDirectory();
    string filename = appPath + "\mytest_" + Strings.Format(DateTime.Now, "yyyyMMddHHmmss") + ".xlsx";

    string SQL_Query = "select * FROM [mydb].[dbo].[mytable] where myDate >= '2017-01-01' ";

    DataTable myTable = CLS_SQL.SQL_Retrieve(SQL_Query);

    XLWorkbook wb = new XLWorkbook();
    wb.Worksheets.Add(myTable, "MyData");
    wb.SaveAs(filename);
}
```
I managed to fix the issue by casting my uniqueidentifier as VARCHAR(36) in the SQL statement, thanks to the help of AndrewMorton in the below StackOverflow thread:
https://stackoverflow.com/questions/50968359/closedxml-export-to-xlsx-error-unable-to-set-cell-value-to-uniqueidentifie

**Comment by vbjay** [comment]
You can use linq to create a projection from the table and use

var data = myTable.AsEnumerable().Select(row=> new {Prop=..., prop2=...});

**Comment by Wowdude07** [comment]
I didn't even consider using LINQ. Thanks for the response!

**Comment by vbjay** [comment]
Hmm.  Guess they don't parse markdown from email responses, even if you edit them.  

``` c#
var data = myTable.AsEnumerable().Select(row=> new {Prop=..., prop2=...});
```
