### ISSUE TITLE
number format

### ISSUE THREAD

**Issue by faramendi** [ClosedXML/ClosedXML#92]
Hi
I generate a spreadsheet with SSIS and I am trying to format it in the last step with ClosedXML

I set a table style and it works, but when I try to set the number format in several columns does not work.
I mean, when I open the file the values are not formatted but if I check the format column in the excel file it is set. If I chage the value manually the new value is formatted formatted

Any idea??

thanks

**Comment by faramendi** [comment]
I simplified the code and it does not work

The background color changes but the values are not properly formatted

     `var workbook = new XLWorkbook(Dts.Variables["User::ExportPathFile"].Value.ToString());
                foreach (var ws in workbook.Worksheets)
                {          
                    var range = ws.RangeUsed(false);
                    range.Clear(XLClearOptions.Formats);
                    ws.Cell(3, 5).Style.NumberFormat.SetFormat("#0.00");
                    ws.Cell(3, 5).Style.Fill.BackgroundColor = XLColor.Orange;

                    ws.Columns().AdjustToContents();    
                }

                workbook.Save();`

**Comment by igitur** [comment]
You closed the issue. I assume that means you solved the problem?

**Comment by faramendi** [comment]
no sorry, it was a mistake

I try to open it but I did not find how, so I opened a new one
