### ISSUE TITLE
Getting Exception of System.ArgumentOutOfRangeException type

### ISSUE THREAD

**Issue by amirvenus** [ClosedXML/ClosedXML#923]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
0.93.0

**What is the current behaviour?**
System.ArgumentOutOfRangeException: 'Specified argument was out of the range of valid values.
Parameter name: AZA is not recognized as a column letter'

**What is the expected behaviour or new feature?**
It is expected to open this file just like other files. 

**Did this work in previous versions of our tool?  Which versions?**
No

## Reproducibility
**Code to reproduce problem:**

```
var path = "gu.xlsx";
var wb = new XLWorkbook(path);

```

System.ArgumentOutOfRangeException: 'Specified argument was out of the range of valid values.
Parameter name: AZA is not recognized as a column letter'

That this the error I get when I try to open an excel file (attached here)

[gu.xlsx](https://github.com/ClosedXML/ClosedXML/files/2133659/gu.xlsx)

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Please complete the full issue template!

**Comment by amirvenus** [comment]
Edited.

**Comment by amirvenus** [comment]
I confirm the issue might exist in the latest version (0.93.0) only. 

0.91.0  should be fine.

**Comment by igitur** [comment]
There is a bug in ClosedXML, but you can easily work around this by deleting columns `App!F:XFD`. It will decrease the file size too. If you press `Ctrl+End` on the `App` worksheet, you should be reaching `E617`, not `XFD617`.

**Comment by igitur** [comment]
@Pankraty I added tests on this branch: https://github.com/igitur/ClosedXML/tree/issue923-argument-out-of-range-exception

**Comment by Pankraty** [comment]
Closed by #925

**Comment by amirvenus** [comment]
I confirm this problem still exists. 

Please check the file in the attachment. 
[en-ro.xlsx](https://github.com/ClosedXML/ClosedXML/files/2175402/en-ro.xlsx)

**Comment by igitur** [comment]
@amirvenus Did you test it against the latest code from the `develop` branch in the repo?

**Comment by amirvenus** [comment]
When using version v0.90 , it throws NullReference exception. 

```
   at ClosedXML.Excel.CalcEngine.CellRangeReference.GetValue() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\XLCalcEngine.cs:line 79
   at ClosedXML.Excel.CalcEngine.XObjectExpression.Evaluate() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\Expression.cs:line 475
   at ClosedXML.Excel.CalcEngine.CalcEngine.Evaluate(String expression) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 118
   at ClosedXML.Excel.XLCell.get_Value() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\Cells\XLCell.cs:line 386
```

**Comment by igitur** [comment]
This will be fixed when `0.93.1` is released.

**Comment by amirvenus** [comment]
Perhaps it will help, 

I tried to isolate the issue by surronding the code in try-catch and realised this invalid formula was the problem:

App->D100 

=+E99D98:E100

which just appears as #NAME? on Excel.

**Comment by amirvenus** [comment]
And now I am getting System.StackOverflowException and I cannot trace it

**Comment by amirvenus** [comment]
@igitur 

> Did you test it against the latest code from the release-candidate branch in the repo?

Sorry for being a noob, could you please guide me how I can do that?

**Comment by igitur** [comment]
I think the easiest is if you download and test the CI build at https://ci.appveyor.com/project/ClosedXML/closedxml/build/0.93.999.1305/job/16v5crvvg0cb2s6k/artifacts

**Comment by amirvenus** [comment]
@igitur 

Thanks! 
I think I am making progress here. Now the error is:

`System.InvalidOperationException: 'Circular Reference occured during evaluation. Cell: Skills!E197`

**Comment by amirvenus** [comment]
Circular Reference was the bad guy here! 
It is working now (using the Cl build)
