### ISSUE TITLE
Pictures do not change location on row insert

### ISSUE THREAD

**Issue by OkumaScott** [ClosedXML/ClosedXML#927]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.94

**What is the current behavior?**

When inserting a new Row, images in the document to not respect their placement setting. Image remains in the same location despite rows being inserted.

**What is the expected behavior or new feature?**

Images set to XLPicturePlacement.Move or XLPicturePlacement.MoveAndSize should shift their position down when row is inserted above.

**Did this work in previous versions of our tool?  Which versions?**

Presumably, No

## Reproducibility

**Code to reproduce problem:**

```c#  
    namespace ClosedXML_Examples
    {
        public class CreateFiles
        {
            public static void CreateAllFiles()
            {
                var path = Program.BaseCreatedDirectory;

                new ImageShift().Create(Path.Combine(path, "ImageShift.xlsx"));
```

---

```c# 
    public class ImageShift : IXLExample
    {
        public void Create(string filePath)
        {
            var wb = new XLWorkbook();
            IXLWorksheet ws;

            using (Stream fs = Assembly.GetExecutingAssembly().GetManifestResourceStream("ClosedXML_Examples.Resources.ImageHandling.jpg"))
            {

                ws = wb.Worksheets.Add("ImageShift");
                ws.AddPicture(fs, XLPictureFormat.Jpeg, "JpegImage")
                    .MoveTo(ws.Cell(5, 2).Address) // Insert to Row 5
                    .WithPlacement(XLPicturePlacement.Move);

                ws.Row(2).InsertRowsBelow(20); // At Row 2, Insert 20 rows. Image should now be on Row 25.

                wb.SaveAs(filePath);
            }
        }
    }
```

- [x] I attached a sample spreadsheet.

[ImageShift.xlsx](https://github.com/ClosedXML/ClosedXML/files/2141968/ImageShift.xlsx)

**Comment by igitur** [comment]
Thanks for the good repro code.
