### ISSUE TITLE
Number formatting does not work

### ISSUE THREAD

**Issue by faramendi** [ClosedXML/ClosedXML#93]
Hi
I generate a spreadsheet with SSIS and I am trying to format it in the last step with ClosedXML

I set a table style and it works, but when I try to set the number format in several columns does not work.
I mean, when I open the file the values are not formatted but if I check the format column in the excel file it is set. If I chage the value manually the new value is formatted formatted
    

I simplified the code and it does not work

The background color changes but the values are not properly formatted
```c#
var workbook = new XLWorkbook(Dts.Variables["User::ExportPathFile"].Value.ToString());
foreach (var ws in workbook.Worksheets)
{          
    var range = ws.RangeUsed(false);
    range.Clear(XLClearOptions.Formats);
    ws.Cell(3, 5).Style.NumberFormat.SetFormat("#0.00");
    ws.Cell(3, 5).Style.Fill.BackgroundColor = XLColor.Orange;

    ws.Columns().AdjustToContents();    
}

workbook.Save();
```
Any idea??

**Comment by faramendi** [comment]
I try to change the data type to number in order to format the values, but when :
ws.Column(5).DataType = XLCellValues.Number;

an exception is thrown. the column contains number values
"Cannot set data type to Number because 'columnName' is not recognized as a number."

**Comment by igitur** [comment]
Can you attach the workbook as it is generated before ClosedXML opens it?

**Comment by igitur** [comment]
`DataType` refers to the actual underlying data type. If one of the cells in the column is non-numeric, that will indeed throw an exception. That is by design.

I think you want to set the format, as you did in the original comment. If you attach the workbook, I'll investigate.

**Comment by DeanGeddes** [comment]
Try using

             currentSheet.Cell(09, 47).Style.NumberFormat.Format = "#,##0";

it works for me.
