### ISSUE TITLE
IXLWorksheet.Range function changed assignment behaviour between 0.93 and 0.92.1

### ISSUE THREAD

**Issue by blevalley** [ClosedXML/ClosedXML#933]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.93/0.92.1

**What is the current behavior?**

When using the IXLWorksheet.Range function in v0.93 to create IXLRange's, if two ranges are created with the same firstCellAddress and lastCellAddress then the created instances are reference equal. 

**What is the expected behavior or new feature?**

Its new behaviour, in v0.93, in v0.92.1 and prior the two instances of IXLRange could be modified independently, without affecting the other.

**Did this work in previous versions of our tool?  Which versions?**

N/A

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
            var wb = new XLWorkbook();
            var ws = wb.Worksheets.Add("Test");
            var range1 = ws.Range("$A$1", "$B$1");
            var range2 = ws.Range("$A$1", "$B$1");

            // Fails in v0.92.1, Succeeds in v0.93
            Debug.Assert(range1 == range2);

            // Succeeds in both
            Debug.Assert(range1.RowCount() == 1);
            Debug.Assert(range2.RowCount() == 1);

            range2.InsertRowsBelow(5);

            // Succeeds in v0.92.1, Fails in v0.93
            Debug.Assert(range1.RowCount() == 1);

            // Succeeds in both
            Debug.Assert(range2.RowCount() == 6);
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
This is unfortunately the natural consequence of the refactoring that we did. Ranges are now stored in a central repository and ranges with the same spans will return the same instance. This was to solve the problems with excessive memory use.

**Comment by igitur** [comment]
Instead of ranges, maybe use variables of type in the `XLRangeAddress`. They are immutable, but that also means that they won't change when you insert rows.

**Comment by blevalley** [comment]
Figured that might be what happened after reading the release notes, but thought I'd submit an issue just in case it wasn't intended. I depend on the mutability of the individual IXLRange objects, so unfortunately XLRangeAddress isn't an option, but its not particularly difficult to work around for now.

Thanks!

**Comment by igitur** [comment]
@pankraty Do you think it is possible to add a method eg `ws.DecoupledRange()` that would create a separate entry in the range repo?

**Comment by igitur** [comment]
Thanks. And that's a really smart workaround!

**Comment by blevalley** [comment]
That workaround works great. Closing this issue, appreciate the help.
