### ISSUE TITLE
Set Cell Format To Text

### ISSUE THREAD

**Issue by pabloarista** [ClosedXML/ClosedXML#935]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.
I searched what is currently being developed and I see nothing in this regard.

**Version of ClosedXML**

0.92.1

**What is the current behavior?**

Can't set the cell format to text when the value is a number, even if the DataTable has that column set to string nor by setting the cell data type. So for example, if I have a string column that has numbers with leading 0s, then when the excel file is outputted, it displays properly. The problem is when a user edits this field, the leading 0s are not retained. So say I have 00023, the moment the user edits this and just changes it to 00022, then excel changes it to 22. This of course does NOT happen if I manually set the cell's format to text. It always retains the leading 0s no matter how many times a user edits the value. In the sample code below, I have some lines commented out. I tried to set the number format. When this occurs, the leading 0s are displayed when the value is edited, but the value truncates the leading 0s. So displaying the leading 0s is not the problem, it's when editing the value that the 0s disappear or are NOT part of the value anymore.

**What is the expected behavior or new feature?**

To be able to set cell format to text, regardless of data type so in cases of numbers with leading 0s, the leading 0s will retain when the cell is changed. It could be some property to set the cell format. I'm not sure if perhaps that's possible already and I couldn't find it in the samples. It would be nice if there was documentation to search through, but even so I don't believe it's anywhere (at least when I searched each sample I couldn't find this at all).

**Did this work in previous versions of our tool?  Which versions?**

I'm not sure, but I believe no

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    System.Data.DataTable dt = new System.Data.DataTable("Test sheet");
    dt.Columns.Add("ID", typeof(int));
    dt.Columns.Add("AlphaNumericID", typeof(string));
	dt.Columns.Add("MoneyValue", typeof(decimal));
	dt.Columns.Add("Name", typeof(string));
	dt.Columns.Add("IntValue", typeof(int));
	dt.Columns.Add("AlphaNumericID2", typeof(string));

			new System.Collections.Generic.List<int> { 23, 1, 2, 5, 0, 5, 8 }.ForEach(x =>
			{
				System.Data.DataRow r = dt.NewRow();
				int i = -1;
				r[++i] = x;
				r[++i] = x.ToString("00000000#");
				r[++i] = x * 23;
				r[++i] = "Name " + x;
				r[++i] = x * 10;
				r[++i] = x.ToString("00000000#0000");
				dt.Rows.Add(r);
			});
			
			ClosedXML.Excel.XLWorkbook xlsx = new ClosedXML.Excel.XLWorkbook(ClosedXML.Excel.XLEventTracking.Disabled);
			
            xlsx.Worksheets.Add(dt);
            
            ClosedXML.Excel.IXLWorksheet xlWorksheet = xlsx.Worksheet(1);
            
            foreach(int c in new[] {2, 6})
            {
				xlWorksheet.Column(c).CellsUsed().SetDataType(XLDataType.Text);
				for (int r = 2; r < 9; ++r)
				{
					ClosedXML.Excel.IXLCell cell = xlWorksheet.Cell(r, c);
					string val = cell.Value + "";

					//cell.Style.NumberFormat.Format = "".PadRight(val.Length - 1, '0') + "#";
					//cell.SetValue<string>(val);
					cell.Value = "'" + val;
					
					cell.DataType = XLDataType.Text;
                                        //it would be nice if we had something like this since the above lines don't do much, except help in the presentation not when editing a cell
                                        //cell.CellFormat = CellFormat.Text;
				}//for row
            }//foreach col
			
			string path = "test.xlsx";
			xlsx.SaveAs(path);
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)
[201806300120296235.xlsx](https://github.com/ClosedXML/ClosedXML/files/2151304/201806300120296235.xlsx)

**Comment by igitur** [comment]
Current we don't, but if we implement `CellFormat.quotePrefix` ( https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.cellformat.aspx?f=255&MSPPError=-2147217396 ) then we can have "numerical text" displayed in Excel as `'000000023` instead of `000000023`. However, if a user edits the cell and remove the leading quotation mark, then the value will revert to a number again. That's an Excel feature out of our control.

@Pankraty If we implement `quotePrefix`, do you think it should be in `IXLStyle` or `IXLNumberFormat`? I'm leaning towards `IXLStyle` to align with the OpenXML spec.

**Comment by igitur** [comment]
@pabloarista So the best we could generate, is this: [test.xlsx](https://github.com/ClosedXML/ClosedXML/files/2151799/test.xlsx)

**Comment by Pankraty** [comment]
> If we implement `quotePrefix`, do you think it should be in `IXLStyle` or `IXLNumberFormat`? 

Sorry for the late reply.
`IXLNumberFormat` looks more logical to me. I think about copying the style from one cell to another: if the user only wants to copy number formats, but not colors, fonts, borders, etc. he would do something like `cell1.Style.NumberFormat = cell2.Style.NumberFormat`. And would most likely expect `QuotePrefix` to be copied as well.
Besides, the current implementation of `IXLStyle` does not have any "direct" properties, only groups (e.g. `Font`, `Border`, etc.) which in turn contain values. Putting `QuotePrefix` to the same level as more abstract entities seems slightly inconsistent.

**Comment by pabloarista** [comment]
So there's no way to set the format like in Excel (right click cell => Format Cells... => Category => Text?

What you mentioned is what I've done (one of the commented lines) and the number format is also there in my example. I mean both work as long as the user doesn't touch the cell. I wouldn't call this a feature I need and can't find workarounds, but it would be nice. Our other options are to make sure we generate all of the required fields and make those 2 columns not editable. I haven't tested that, but I believe that's possible with OpenXML, right? I saw in the samples, so basically just restricting 2 columns. That could be another option. I really appreciate the quick response.

**Comment by igitur** [comment]
@pabloarista Take the file in https://github.com/ClosedXML/ClosedXML/issues/935#issuecomment-401544872 , modify it in Excel to what you want, and upload it again here, so that I can see what you mean.

**Comment by igitur** [comment]
When #937 is implemented, you would be able to enable the quote prefix in code. See that changed (including example) that I added in that PR.

@Pankraty After coding the PR I'm more convinced that this should be in `IXLStyle`. I had a look at some of the other libraries too, including Aspose Cells and they all treat it like that. To me, a number format is exclusively a string which affects how numbers are displayed. The quote prefix is not part of that, and in fact, isn't even relevant to numbers, but only to cells formatted as text (whether they look like numbers or not). So I really think `IXLStyle` is the correct place.

**Comment by pabloarista** [comment]
Looks promising @igitur. I will test this PR

**Comment by Pankraty** [comment]
> After coding the PR I'm more convinced that this should be in `IXLStyle`

I will not argue

**Comment by sahin52** [comment]
I can show a big number in the excel file like this:
```
var currentRow=1;
var aBigNumber = "76512363613616161626121231"
worksheet.Cell(currentRow, 6).SetValue(aBigNumber);
worksheet.Column(6).Style.NumberFormat.Format = "@"; // NumberFormatId=49 source=  https://github.com/ClosedXML/ClosedXML-wiki/blob/master/NumberFormatId-Lookup-Table.md
```

**Comment by saidulla-sudo** [comment]
how to add multiple line in one row and one column.

**Comment by reddtoric** [comment]
Fine that this completed update is an option, but just FYI to others that to have a quote prefix is not the correct solution. The quote is still part of the value and what happens the value expected to not have anything else?

:point_down: This comment and code by @sahin52 is what answers the original issue/request and is what I'm looking for.
> I can show a big number in the excel file like this:
> 
> ```
> var currentRow=1;
> var aBigNumber = "76512363613616161626121231"
> worksheet.Cell(currentRow, 6).SetValue(aBigNumber);
> worksheet.Column(6).Style.NumberFormat.Format = "@"; // NumberFormatId=49 source=  https://github.com/ClosedXML/ClosedXML-wiki/blob/master/NumberFormatId-Lookup-Table.md
> ```
