### ISSUE TITLE
Package not signed

### ISSUE THREAD

**Issue by Sicos1977** [ClosedXML/ClosedXML#942]
Hi,

Could you please sign the new version of ClosedXml. I just upgraded to 0.93 but can't use it because my project uses strong names.

https://www.nuget.org/packages/ClosedXML/0.93.0

**Comment by igitur** [comment]
https://www.nuget.org/packages/ClosedXML.Signed/

**Comment by Sicos1977** [comment]
Hi,

Why 2 different packages? Signed packages can also be used from non signed projects.

**Comment by igitur** [comment]
Because many people want to avoid the problems associated with signing, eg binding redirects etc. Besides, signing is overrated. https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/

**Comment by Sicos1977** [comment]
I guess he is right :-)

**Comment by Bouke** [comment]
Well he's had a "change of heart": https://www.pedrolamas.com/2018/09/11/start-strong-naming-your-assemblies/
