### ISSUE TITLE
How to know Worksheets rows count

### ISSUE THREAD

**Issue by TaejongJang** [ClosedXML/ClosedXML#946]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
v 0.93.0
e.g. 0.87.1

**What is the current behavior?**
i wanna know that worksheets rows count. so i wrote like this

XLWorkbook wb = new XLWorkbook();
var ws = wb.Worksheets.Add(table);
for (int i = 2; i < ws.Rows().Count(); i++)

but application freezing when meet "ws.Rows().Count()".

**What is the expected behavior or new feature?**
how to know that worksheets's rows count

**Did this work in previous versions of our tool?  Which versions?**
No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
                    XLWorkbook wb = new XLWorkbook();
                    var ws = wb.Worksheets.Add(DanawaTable2);
                    List<XLColor> rgbList = new List<XLColor> {
                        XLColor.FromArgb(199, 229, 142), XLColor.FromArgb(236, 246, 80), XLColor.FromArgb(116, 190, 114),XLColor.FromArgb(232, 130, 114)};

                    int j = 0;

                    for (int i = 2; i < ws.Rows().Count(); i++)
                    {
                        if(i == (ws.Rows().Count() - 1))
                        {
                            ws.Cell("A" + i).Style.Fill.BackgroundColor = rgbList[j];
                        }
                        else if(ws.Cell("B" + i).Value.Equals(ws.Cell("B" + (i + 1))))
                        {
                            ws.Cell("A" + i).Style.Fill.BackgroundColor = rgbList[j];
                        } else
                        {
                            ws.Cell("A" + i).Style.Fill.BackgroundColor = rgbList[j++];
                            j = j % 4; 
                        }
                    }
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by Pankraty** [comment]
It does not freeze, it actually works heavy generating a million rows. If you'll be patient you'll get 1048576 eventually.

What you need is `XLWorksheet.RowsUsed().Count()` or `XLWorksheet.LastRowUsed().RowNumber()`

**Comment by TaejongJang** [comment]
I solved the problem! problem is not "Row().Count()". Thank's a lot!

**Comment by datamd** [comment]
Hi

Fixing #1063 would really help me on my current work project

I think I am waiting for version 0.95 to be made available ???

Just a quick question and trying my best not to to be pushy as I understand
you may all be quite busy with normal work / life

Regards
Mark Dicken

**Comment by saeidfeyziniya** [comment]
https://stackoverflow.com/a/73056242/15356914

This example has the best performance.
