### ISSUE TITLE
XLWorkbook.Protect(string workbookPassword) + overloads: output file in not protected with password.

### ISSUE THREAD

**Issue by Diomos** [ClosedXML/ClosedXML#951]
- [x] Bug
- [ ] Feature

Version of ClosedXML: 0.93.0

Current behavior:
You can call _Protect_ method on workbook however output file is not password protected.

Expected behavior:
After save the excel file is password protected. Upon opening in MS Excel it should ask for password.

**Did this work in previous versions of our tool?  Which versions?**
Don't know

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

**Code to reproduce problem:**
```c#
public void Main()
{
            using (XLWorkbook wb = new XLWorkbook())
            {
                // just dummy worksheet
                wb.AddWorksheet("SomeSheet");
                wb.Protect(true, true, "123");

                wb.SaveAs("C:\\someReport.xlsx");
            }
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Password protection to enable/disable the opening of a file is not supported with OpenXML. See https://blogs.msdn.microsoft.com/openspecification/2009/07/17/overview-of-protected-office-open-xml-documents/

You can only lock the structure and windows of an OpenXML document and that is indeed what the `wb.Protect()` method does.

**Comment by yogita3279** [comment]
https://youtu.be/kRvGnkt172o 
Here is a youtube video link contains a step-by-step process on how you can create a password-protected excel workbook using a closed XML library.
