### ISSUE TITLE
IXLCell.SetValue handles Enums differently in 0.93

### ISSUE THREAD

**Issue by blevalley** [ClosedXML/ClosedXML#953]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.93/0.92.1

**What is the current behavior?**

Currently, in 0.93, IXLCell.SetValue(parameter) throws an ArgumentException ("Unable to set cell value to...") when the type of the parameter is an enum.

**What is the expected behavior or new feature?**

In previous versions, calling SetValue with an enum argument would not throw an exception, and seemed to call ToString in the background before setting the value.

**Did this work in previous versions of our tool?  Which versions?**

Yes (tested v0.92.1 and 0.89).

## Reproducibility
**Code to reproduce problem:**
```c#
 class Program
    {
        static void Main(string[] args)
        {
            var wb = new XLWorkbook();
            var ws = wb.AddWorksheet("test");
            var value = TestEnum.I;
            ws.Cell(1, 1).SetValue(value);
        } 
    }
    public enum TestEnum
    {
        I,
        Am,
        An,
        Enum
    }
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
It was just by chance that it worked previously and never really explicitly supported. But it's a good idea and I will include support for it in v0.94. In the meantime, just use `ws.Cell(1, 1).SetValue(value.ToString());`

**Comment by Pankraty** [comment]
I was thinking about implementing a register of custom value providers so that users could define their own rules. E.g. 
```
  ValueProviders.RegisterType<System.Enum>(v => v.ToString());
  ValueProviders.RegisterType<MyAwesomeClass>(v => v.GetAwesomenessValue());
  ValueProviders.RegisterType<TestEnum>(v => LocalizationService.GetLocalizedValue(v, "ru-RU"));
```
Thus we would not have to change the library code to support more and more classes (Guids, enums, ...).

**Comment by igitur** [comment]
@pankraty The idea is nice, but the user would end up writing much more code than just using my workaround above or a local function to do the conversion. Right?

**Comment by Pankraty** [comment]
Your solution is fine for setting values cell-by-cell, but consider filling a table with DataSet or IEnumerable. In this case one would have to reorganise each collection, depending on value types inside.

**Comment by igitur** [comment]
Ah, yes, well, for bulk operations it could be useful. But the user could still pass his own `data.Select(e => e.SomeEnum.ToString())`. And I'm especially hesitant to add complexity to the bulk operations as it could impact performance. Some users want to dump thousands of rows in a worksheet.

My first priority is to ensure we support all data types that can be returned by ADO.NET, as was with the case with the `Guid` that we missed. For anything additional, I'm still leaning towards the user handling it on his own. But I haven't convinced myself yet either about this. ;-)

**Comment by vbjay** [comment]
Frankly linq is the way to go. If you have a dataset, you can use linq to
dataset to control the values from the tables and even which fields are
desired.
