### ISSUE TITLE
Absolute dependencies in 0.93.0

### ISSUE THREAD

**Issue by MarkStega** [ClosedXML/ClosedXML#957]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
[x] Bug
[ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.93.0

**What is the current behavior?**

Works if you have OpenXML 2.72.1 & FastMember 1.3.0 but if upgrade either of those then a failure occurs at run time with an explicit attempt to load 2.72.1/1.3.0

**What is the expected behavior or new feature?**

Since the dependencies are show as OXML >= 2.72.1 & FM >= 1.30 then I expect to be able to update to OXML 2.8.1 or FMS 1.4.1 without failure

**Did this work in previous versions of our tool?  Which versions?**

Unknown

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
c#
            m_Workbook = new XLWorkbook(XLEventTracking.Disabled);

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
What version of Visual Studio are you using?

**Comment by igitur** [comment]
Also paste the full exception and stack trace.

**Comment by MarkStega** [comment]
VS2015

`2018-07-23 08:35:33.128 - Error - Exception in ReportService.ReportWriterWorker of 'System.IO.FileLoadException: Could not load file or assembly 'FastMember.Signed, Version=1.3.0.0, Culture=neutral, PublicKeyToken=9e8f22703bef9a29' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'FastMember.Signed, Version=1.3.0.0, Culture=neutral, PublicKeyToken=9e8f22703bef9a29'
   at ClosedXML.Excel.XLTheme..ctor()
   at ClosedXML.Excel.XLWorkbook.InitializeTheme()
   at ClosedXML.Excel.XLWorkbook..ctor(XLEventTracking eventTracking)
   at Optimiser.ReportService.ReportService_GeneratePerformanceReport.CreateReport(Report_DD p_Report, ReportDescriptor_DD p_ReportDescriptor_DD, String p_ReportFilename, DateTime p_Start, DateTime p_Stop, SortedDictionary`2 p_DataDictionary, FiltersAllowThisCase p_FiltersAllowThisCase) in C:\Solutions\OHI\Optimiser\ReportService\ReportService_GeneratePerformanceReport.cs:line 52
   at Optimiser.ReportService.ReportService.GenerateReport(Report_DD p_Report, Report_BL p_Report_BL, ReportDetailPerioperativeFlow_BL p_ReportData_BL) in C:\Solutions\OHI\Optimiser\ReportService\ReportService_GenerateReport.cs:line 362
   at Optimiser.ReportService.ReportService.ReportWriterWorker() in C:\Solutions\OHI\Optimiser\ReportService\ReportService_ReportWriterWorker.cs:line 35

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].`

**Comment by igitur** [comment]
The https://www.nuget.org/packages/ClosedXML packaged changed from signed to unsigned. If you want to use a signed version of ClosedXML, use https://www.nuget.org/packages/ClosedXML.Signed

**Comment by MarkStega** [comment]
I guess I need a tutorial (or a pointer to one) on the implications of signed/unsigned. All I know is that I've been using ClosedXML and it now has an issue with the two dependencies of OpenXML & FastMember. I guess that the full name of FastMember.Signed should tell me something but I truly don't know what.

Sorry to be obtuse...

**Comment by igitur** [comment]
Easiest is to remove ClosedXML, Documentformat.OpenXML and Fastmember.Signed. If you don't really care about signing (which I suggest is the right way), install ClosedXML (not the signed version) after that.

**Comment by MarkStega** [comment]
That brings me back to a working solution after upgrading OXML & FM but the end result is the same. If I update OXML & FM I get the original error.

**Comment by igitur** [comment]
I can't reproduce the error. I could upgrade the packages and didn't experience a problem.

Please list your *exact* steps to reproduce the problem. Provide as much detail as you can.

**Comment by MarkStega** [comment]
This is occurring in a .NetFramework 4.7 console application that I've had as part of my solution for years. The system is Windows 10 x64 and up to date on patches. It has ,Net frameworks 4.5, 4.6, and 4.7 installed. I don't see anything remarkable about the csproj file; I can start from scratch and build up a new project file to see if that helps.

**Comment by igitur** [comment]
Yes, the exact steps to a new project would be ideal.

**Comment by MarkStega** [comment]
I built up a new solution and it doesn't have the anomaly.

The only significant difference with a newly generated project file is the addition of `<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects> ` in the csproj
and app.config getting
`      <dependentAssembly>
        <assemblyIdentity name="FastMember.Signed" publicKeyToken="9e8f22703bef9a29" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.4.1.0" newVersion="1.4.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="DocumentFormat.OpenXml" publicKeyToken="8fb06cb64d019a17" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.8.1.0" newVersion="2.8.1.0" />
      </dependentAssembly>
` 
getting placed in my app.config

If I remove change the generate to false and remove the redirects in app.config then the error returns. I've never needed the redirects in any other project. It does seem to indicate some absolute proect dependency in ClosedXML.

As an aside, the upgrade to OXML 2.8.1 brings a ton of dependencies into a project.

**Comment by igitur** [comment]
As far as I know, if one had signed dependencies, one *has* to use binding redirects if one upgrades them. I don't think there is a way to avoid that. Otherwise, download the ClosedXML code and see if you can fix it.

OpenXML issues must be logged at their repo.

**Comment by MarkStega** [comment]
After some research, the issue isn't with ClosedXML but with the downstream signed dependencies. If they are changing the AssemblyVersion then indeed the binding redirects are going to be needed. I found one example project that has taken the route of fixing the AssemblyVersion [FluentValidation](https://github.com/JeremySkinner/FluentValidation/wiki/l.-Strong-naming-and-signed-packages) so that binding redirects aren't needed. I am presuming that the same scheme is not being followed by OXML or in general.

**Comment by MarkStega** [comment]
Apparently fixing the AssemblyVersion for a major version  is the accepted method but the guidance is very poor. See [How to Version Assemblies Destined for Nuget](https://codingforsmarties.wordpress.com/2016/01/21/how-to-version-assemblies-destined-for-nuget/)

**Comment by igitur** [comment]
Thanks for the feedback.
