### ISSUE TITLE
Leading Zeros dropped off 

### ISSUE THREAD

**Issue by tlambert** [ClosedXML/ClosedXML#959]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.93.0

**What is the current behavior?**
When setting the DataType to Text - ws.Cell(row, col).SetDataType(XLDataType.Text); - leading zero's are now being dropped off 

Complete this.

**What is the expected behavior or new feature?**
keep leading zero's
Complete this.

**Did this work in previous versions of our tool?  Which versions?**

Yes - it works in 0.92.1

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
                        while (dataReader.Read())
                        {
                            row++;
                            col = 1;
                            for (var i = 0; i < dataReader.FieldCount; i++)
                            {
                                if (dataReader[i] == DBNull.Value)
                                    ws.Cell(row, col).Value = "";
                                else
                                    ws.Cell(row, col).Value = dataReader[i].ToString().Replace("12:00:00 AM", "");
                                // force column to text - i.e. census tract 0001.10 so it doesn't drop the formatting
                                if (dataReader.GetDataTypeName(i) == "varchar")
                                    ws.Cell(row, col).SetDataType(XLDataType.Text);
                                col++;
                            }
                        }

```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[70080785_Ramos_1.xlsx](https://github.com/ClosedXML/ClosedXML/files/2220143/70080785_Ramos_1.xlsx)

I also tried setting the datatype before setting the value and it didn't help.  The above code works fine in 0.92.1 and prior

**Comment by igitur** [comment]
Ok, I'll look into, but why aren't you using the `InsertTable` and `InsertData` methods for dumping a recordset to a worksheet?

**Comment by tlambert** [comment]
public class TestInfo
        {
            public string Name { get; set; }
            public string AcctNo { get; set; }
            public decimal Amount { get; set; }
        }

        static void Main(string[] args)
        {
            List<TestInfo> ti = new List<TestInfo>()
            {
                new TestInfo() { Name = "Spongebob", AcctNo = "0001234", Amount = 12.50M },
                new TestInfo() { Name = "Patrick", AcctNo = "12345", Amount = 10.50M },
                new TestInfo() { Name = "Squidward", AcctNo = "0101010", Amount = 14.33M },
                new TestInfo() { Name = "Mr Krabs", AcctNo = "0505050", Amount = 18.25M },
            };
            var wb = new XLWorkbook();
            var ws = wb.Worksheets.Add("Report");
            int row = 1;
            foreach(var i in ti)
            {
                ws.Cell(row, 1).Value = i.Name;
                ws.Cell(row, 2).Value = i.AcctNo;
                ws.Cell(row, 2).SetDataType(XLDataType.Text);
                ws.Cell(row, 3).Value = i.Amount;
                row++;
            }
            ws.Columns().AdjustToContents();
            wb.SaveAs(@"C:\temp\test.xlsx");
        }
    }

**Comment by igitur** [comment]
That code was relying on a bug and wasn't a feature. If you intend to set the cell value as a text value, use one of these:
`ws.Cell(row, 2).SetValue(i.AcctNo);` 
or 
`ws.Cell(row, 2).Value = "'" + i.AcctNo;`

**Comment by tlambert** [comment]
we changed all the code to use SetValue and now using the latest version.  Thank you
