### ISSUE TITLE
More than one Value to Pivot table not working

### ISSUE THREAD

**Issue by alexandrumetzak** [ClosedXML/ClosedXML#96]
base on your example with pastries if I would have another column like price and I would like to have in my pivot table two values like : 

pt.Values.Add("NumberOfOrders");
pt.Values.Add("Price");

if you add two Values to that pivot table it crashes.

**Comment by igitur** [comment]
I see what you mean. I don't think multiple values have ever worked in ClosedXML pivot tables. This might take a while to fix.

**Comment by igitur** [comment]
If you can pull the changes from #99 and let me know if it fixes your problem, that would be great.

**Comment by alexandrumetzak** [comment]
An unhandled exception of type 'System.ApplicationException' occurred in ClosedXML.dll

Additional information: The element has incomplete content. List of possible elements expected: <http://schemas.openxmlformats.org/spreadsheetml/2006/main:i>. in /x:pivotTableDefinition[1]/x:colItems[1]

**Comment by igitur** [comment]
Please paste your full code to reproduce this error.

**Comment by alexandrumetzak** [comment]
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ClosedXML.Excel;

namespace ConsoleApplication1
{
    class ClosedXMLExample
    {
        static void Main(string[] args)
        {
           
            ExportFromDt();
           
        }

        public static void ExportFromDt()
        {
            var dt = GenerateDataTable();
            //Codes for the Closed XML
            using (XLWorkbook wb = new XLWorkbook())
            {
                var sheet = wb.Worksheets.Add("Customers");

                // Insert our list of pastry data into the "PastrySalesData" sheet at cell 1,1
                var source = sheet.Cell(1, 1).InsertTable(dt, "Customers", false);

                //var sheet = wb.Worksheets.Add(dt, "Customers");

                // Add a new sheet for our pivot table
                var ptSheet = wb.Worksheets.Add("PivotTable");

                var range = source.DataRange;
                var header = sheet.Range(1, 1, 1, dt.Columns.Count);

                var data_range = sheet.Range(header.FirstCell(), range.LastCell());

                // Create the pivot table, using the data from the "PastrySalesData" table

                var pt = ptSheet.PivotTables.AddNew("PivotTable", ptSheet.Cell(1, 1), data_range);

                pt.RowLabels.Add("Abonnemangstyp");
                pt.RowLabels.Add("Tjänst");

                pt.Values.Add("Antal").SetSummaryFormula(XLPivotSummary.Sum);//.NumberFormat.Format = "#0.00";
                pt.Values.Add("Belopp").SetSummaryFormula(XLPivotSummary.Sum);//.NumberFormat.Format = "#0.00";

                wb.SaveAs(@"C:\DataGridViewExport.xlsx");
            }
        }

        public static DataTable GenerateDataTable()
        {
            DataTable dt = new DataTable();
            dt.Columns.AddRange(new DataColumn[14]
            {
                   new DataColumn("Faktura", typeof(decimal)),
                new DataColumn("Belopp", typeof(decimal)),
                new DataColumn("Period", typeof(string)),
                new DataColumn("Typ", typeof(string)),
                new DataColumn("Antaltjänster", typeof(int)),
                new DataColumn("Abonnemangstyp", typeof(string)),
                new DataColumn("Abonnemangsid", typeof(string)),
                new DataColumn("Antal", typeof(decimal)),
                new DataColumn("Tjänst", typeof(string)),
                new DataColumn("A-pris", typeof(decimal)),
                new DataColumn("Telefonnummer", typeof(string)),
                new DataColumn("Department 1", typeof(string)),
                new DataColumn("Tjänster", typeof(string)),
                new DataColumn("Namn", typeof(string))


            });
            for (int i = 0; i <= 5000; i++)
                dt.Rows.Add(
                    random.Next(0, 99999),
                    random.Next(0, 99999),
                    RandomString(15),
                    RandomString(16),
                    random.Next(0, 99999),
                    RandomString(19),
                    RandomString(18),
                    random.Next(0, 99999),
                    RandomString(15),
                    random.Next(0, 99999),
                    RandomString(19),
                    RandomString(19),
                    RandomString(19),
                    RandomString(19)
                    );

            return dt;
        }

        private static Random random = new Random((int)DateTime.Now.Ticks);
        private static string RandomString(int Size)
        {
            string input = "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZåäöÅÄÖ 1234567890";
            StringBuilder builder = new StringBuilder();
            char ch;
            for (int i = 0; i < Size; i++)
            {
                ch = input[random.Next(0, input.Length)];
                builder.Append(ch);
            }
            return builder.ToString();
        }
    }
}

**Comment by igitur** [comment]
Thanks for the good code sample. That helped a lot. I pushed another fix. I hope that solves the problem. Pivot tables are very complex!

**Comment by alexandrumetzak** [comment]
Hi, 
great work on that one, but now it's not working if it doesn't have any values (only rows) 
if you comment : 
   //pt.Values.Add("Antal").SetSummaryFormula(XLPivotSummary.Sum);//.NumberFormat.Format = "#0.00";
                //pt.Values.Add("Belopp").SetSummaryFormula(XLPivotSummary.Sum);//.NumberFormat.Format = "#0.00";
it will crash
