### ISSUE TITLE
In VB.NET dont copy contain of sheet

### ISSUE THREAD

**Issue by Dereckz** [ClosedXML/ClosedXML#960]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.87.1

**What is the current behavior?**

Complete this.

**What is the expected behavior or new feature?**

Complete this.

**Did this work in previous versions of our tool?  Which versions?**

Yes/No/v0.XX

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
  ruta = My.Application.Info.DirectoryPath() & "\Archivos\TEST.xlsx"


                Dim book As New ClosedXML.Excel.XLWorkbook(ruta)


                Dim libro As New ClosedXML.Excel.XLWorkbook

                book.Worksheet(1).CopyTo(libro, "SHEET")
           

                Dim hoja As IXLWorksheet = libro.Worksheets(0)
}

inside the sheet of the original book I have an image that nop craga in the copy
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Plesse try with v0.93

**Comment by Dereckz** [comment]
THE CLASS IS CLOSED

**Comment by igitur** [comment]
Sorry, I don't understand.
