### ISSUE TITLE
NUMBERVALUE not working

### ISSUE THREAD

**Issue by JDeuker** [ClosedXML/ClosedXML#964]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.91.0

**What is the current behavior?**

Excel will display #NAME? and does not evaluating the formula correctly.
After selecting the formula in the Excel formula row and pressing Enter, the formula will work.

**What is the expected behavior or new feature?**

NUMBERVALUE() will work as a formula function.
Also support for worksheet.Evaluate()

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
    var wb = new XLWorkbook();
    var ws = wb.AddWorksheet("test");

    double value = 123.45;
   
    var ic = CultureInfo.InvariantCulture;
    string textvalue = value.ToString(ic);          

    string formula = string.Format("NUMBERVALUE(\"{0}\",\"{1}\",\"{2}\")", textvalue, ic.NumberFormat.NumberDecimalSeparator, ic.NumberFormat.NumberGroupSeparator);
    ws.Cell(1, 1).FormulaA1 = formula;

}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Thanks. Many formulae have not been implemented yet. I want to encourage you to try do a pull request if you want this implemented soon.

**Comment by JDeuker** [comment]
Allright. Pull is requested: https://github.com/ClosedXML/ClosedXML/pull/965
