### ISSUE TITLE
Data validation isn't saved correctly

### ISSUE THREAD

**Issue by tisaacs** [ClosedXML/ClosedXML#968]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

Latest dev branch

**What is the current behavior?**

When saving a file with a large set of data validation rules, ClosedXML doesn't save them correctly.

For example, it transforms the XML from this:

```
<dataValidation type="textLength" operator="lessThanOrEqual" showInputMessage="1" showErrorMessage="1" prompt="not greater than 43 characters" sqref="C11:AH11 C19:AH19 C27:AH27 C35:AH35 C43:AH43 C51:AH51 C59:AH59 C67:AH67 C75:AH75 C83:AH83 C91:AH91 C99:AH99 C107:AH107 C115:AH115 C123:AH123 C131:AH131 C139:AH139 C147:AH147 C155:AH155 C163:AH163 C171:AH171 C179:AH179 C187:AH187 C195:AH195 C203:AH203 C211:AH211 C219:AH219 C227:AH227 C235:AH235 C307:AH307 C251:AH251 C259:AH259 C267:AH267 C275:AH275 C283:AH283 C291:AH291 C299:AH299 C243:AH243 C315:AH315 C323:AH323 C331:AH331 C339:AH339 C347:AH347 C355:AH355 C363:AH363 C371:AH371 C379:AH379 C387:AH387 C395:AH395 C403:AH403 C411:AH411 C419:AH419 C427:AH427 C435:AH435 C443:AH443 C451:AH451 C459:AH459 C467:AH467 C475:AH475 C483:AH483 C491:AH491 C499:AH499 C507:AH507 C515:AH515 C523:AH523 C531:AH531 C539:AH539 C547:AH547 C555:AH555 C563:AH563 C571:AH571 C579:AH579 C587:AH587 C595:AH595 C603:AH603 C611:AH611 C619:AH619 C627:AH627 C635:AH635 C643:AH643 C651:AH651 C659:AH659 C667:AH667 C675:AH675 C683:AH683 C691:AH691 C699:AH699 C707:AH707 C715:AH715 C723:AH723 C731:AH731 C739:AH739 C747:AH747 C755:AH755 C763:AH763 C771:AH771 C779:AH779 C787:AH787 C795:AH795 C803:AH803">
			<formula1>43</formula1>
		</dataValidation>
```
To this:

```
<x:dataValidation type="textLength" errorStyle="stop" operator="lessThanOrEqual" allowBlank="1" showDropDown="0" showInputMessage="1" showErrorMessage="1" errorTitle="" error="" promptTitle="" prompt="not greater than 43 characters" sqref="C11:AH803">
			<x:formula1>43</x:formula1>
```

I think the issue is that it merges the cells into a range, but the range isn't valid.

**What is the expected behavior or new feature?**

The original data validation rules should be saved correctly.

**Did this work in previous versions of our tool?  Which versions?**

Not sure.

## Reproducibility

I've pushed a test case that fails here:
https://github.com/tisaacs/ClosedXML/tree/DataValidationSaveBug

I'd also like to say thanks for such a brilliant library. If you point me in the right direction, I'd be more than happy to fix the issue myself.

**Comment by Pankraty** [comment]
If you have spare time, try to debug XLDataValidations.Consolidate() and XLRanges.Consolidate. I suspect the reason is there.

**Comment by Pankraty** [comment]
Most likely, XLRanges.Colnsolidate() fails on ranges 1 cell high. My bad.

**Comment by Pankraty** [comment]
Funny, I have fixed this - and another test started to fail. It turned out, we have another bug regarding `CellsUsed()` method, and these two happened to eliminate each other.
