### ISSUE TITLE
Feature : How do I lock whole sheet or specific cell/column ?

### ISSUE THREAD

**Issue by bismoy2013** [ClosedXML/ClosedXML#976]

**Comment by bismoy2013** [comment]
I did have a look at https://github.com/ClosedXML/ClosedXML/wiki/Sheet-Protection , couldn't find reference to cell protection, hence thought of asking about it here. Thanks

**Comment by vbjay** [comment]
It's all there.

**Comment by bismoy2013** [comment]
I am trying to make specific cells uneditable, while we should be able to see the contents clearly but certain cells should be totally edit-proof, therefore I have used the below snippet

ws.Cell("A1").Style.Protection.SetLocked(true) .

The downloaded excel file is still letting me **edit and save** in my local machine. Am I supposed to set password to lock that cell ? Or is it that I am using it wrongly ? Please let me know

Thanks

**Comment by vbjay** [comment]
Start a new excel file.  Put junk in.  Select some sells and make sure they
are locked.  Edit the cells.  Now lock the sheet.  They work hand in hand.

**Comment by bismoy2013** [comment]
Actually I figured it out.

worksheet.Protect() .....

ws.Cell("A1").Style.Protection.SetLocked(false) .... for cells where you want to be able to edit if required.

**Comment by bismoy2013** [comment]
How do I have some cells locked and some cells' width adjustable in a locked sheet ?
Because if I do sheet.Protect ( ) & then unlock some selected cells, the width still remains un-adjustable.

**Comment by bismoy2013** [comment]
Emm, true ! but I'm confused how these can be done from code, anyways thought of posting it here in case you can suggest some solutions by sharing some snippets.

**Comment by HemanthGali** [comment]
Hi @bismoy2013 @vbjay ,
Any luck how to allow column adjustments ? after locking the cells.

**Comment by Coder-Ganesh** [comment]
@bismoy2013 @HemanthGali 
may be you can try commenting the below line

worksheet.Columns().AdjustToContents();

I am able to resize the columns even after making them read only.

**Comment by mbaig-nowgray** [comment]
Put the Adjustment code before Protecting the Sheet Like above.
WorksheetsName.Columns().AdjustToContents();
WorksheetsName.Protect();
WorksheetsName.Column("A").Style.Protection.SetLocked(false);
