### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.8.1.0

### ISSUE THREAD

**Issue by epikgit** [ClosedXML/ClosedXML#977]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.93.1

**What is the current behavior?**

I'm testing the creation of an Excel file and, during runtime, I'm getting the error in subject.

**What is the expected behavior or new feature?**

Since I correctly referenced the DocumentFormat.OpenXml, Version=2.8.1.0 I expect ClosedXML to find it and create the Excel file.

**Did this work in previous versions of our tool?  Which versions?**

Until a certain time it works even with the current version (0.93.1). Then, out of the blue, it broke.

**Code to reproduce problem:**
```c#
public class ReportExcelClosedXml
	{
		public byte[] Create(DataSet result)
		{
			using (var excelStream = new MemoryStream())
			{
				using (var workbook = new XLWorkbook())
				{
					for (int i = 0; i < result.Tables.Count; i++)
					{
						var table = result.Tables[i];
						var ws = workbook.Worksheets.Add(table.TableName);

						// header 
						for (int headerCol = 0; headerCol < table.Columns.Count; headerCol++)
						{
							ws.Cell(1, headerCol + 1).Value = table.Columns[headerCol].ColumnName;
							ws.Cell(1, headerCol + 1).Style.Font.Bold = true;
						}

						// rows
						for (int dsRow = 0; dsRow < table.Rows.Count; dsRow++)
						{
							for (int dsCol = 0; dsCol < table.Columns.Count; dsCol++)
							{
								var dsValue = table.Rows[dsRow][dsCol];
								var cellDataType = XLDataType.Text;

								var columnType = table.Columns[dsCol].DataType.ToString();
								if (columnType.StartsWith("System.Int") || columnType.StartsWith("System.UInt") || columnType == "System.Long")
								{
									cellDataType = XLDataType.Number;
								}

								ws.Cell(dsRow + 2, dsCol + 1).Value = dsValue.ToString();
								ws.Cell(dsRow + 2, dsCol + 1).DataType = cellDataType;
							}
						}
						ws.Columns().AdjustToContents();
					}
					workbook.SaveAs(excelStream);
				}
				return excelStream.ToArray();
			}
		}
	}
```

**Comment by igitur** [comment]
https://www.nuget.org/packages/ClosedXML/ is now unsigned and https://www.nuget.org/packages/ClosedXML.Signed is now the signed package. Are you sure you're using the intended version?

**Comment by epikgit** [comment]
I'm using the unsigned version, regularly downloaded from NuGet. Am I supposed to use the other one?
Just in case, why?

**Comment by igitur** [comment]
Success?

**Comment by epikgit** [comment]
No sorry. 
I tried everything but it seems equally unfeasable. 
I resolved changing library.
