### ISSUE TITLE
The name on the button in the Form Controls is lost when saved  in Excle2010.

### ISSUE THREAD

**Issue by alfiveZ** [ClosedXML/ClosedXML#979]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.93.1

**What is the current behavior?**
The name on the button  in the Form Controls is lost when saved as  “.xlsm" in Excle2010.
For example, the button name of the source file is "Clear", but the button name of the saved target file is lost and becomes "Button". This phenomenon occurs in Excle2010.
 The source file:
![z1](https://user-images.githubusercontent.com/41245791/44639679-cb6d0e80-a9ef-11e8-91a9-8e9665f233b6.jpg)
Saved as  the target file：
![z2](https://user-images.githubusercontent.com/41245791/44639697-db84ee00-a9ef-11e8-8c06-a4ea85529ef5.jpg)

**What is the expected behavior or new feature?**

The name on the button in the Form Controls  is the same as the source file

**Did this work in previous versions of our tool?  Which versions?**

Yes,it works after V0.90.0.But it dose not work before V0.90.0.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**
 I  attach  my file,the “Book1.xlsm” in the file is the Source Excle File.And This phenomenon occurs in Excle 2010 but not in Excle 2013.

**Code to reproduce problem:**
```c#
private void button1_Click(object sender, EventArgs e)
 {
       FileStream fs = new FileStream("Book1.xlsm", FileMode.Open, FileAccess.ReadWrite);
       XLWorkbook workBook = new XLWorkbook(fs);
       workBook.SaveAs("Z.xlsm");
        fs.Close();
 }
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

[WindowsFormsApp1.zip](https://github.com/ClosedXML/ClosedXML/files/2328060/WindowsFormsApp1.zip)

**Comment by igitur** [comment]
Please attach your input file.

**Comment by alfiveZ** [comment]
The name on the button in the Form Controls is lost  When it is opened by Excle2010.But This phenomenon  doesn"t occur in Excle 2013.Below is my program。
[WindowsFormsApp1.zip](https://github.com/ClosedXML/ClosedXML/files/2328137/WindowsFormsApp1.zip)

**Comment by alfiveZ** [comment]
@igitur I attach my input file.This phenomenon doesn't occur in Excle 2013.But it occur in Excle 2010.Is there a better way to solve this?

**Comment by igitur** [comment]
I don't have an Excel 2010 installation, so unfortunately I can't do much. If I can't replicate the issue, I can't fix it. Maybe you can download the source code and try to submit a pull request to fix the issue.
