### ISSUE TITLE
Implement something sensible for IXLCell.ToString()

### ISSUE THREAD

**Issue by igitur** [ClosedXML/ClosedXML#980]

**Comment by vbjay** [comment]
Could provide a default that returns the value.tostring() and allow for formats

.ToString("V")//value
.ToString("F")//formatting or style
.ToString("C")//colors

...

**Comment by igitur** [comment]
And address too

**Comment by igitur** [comment]
The address could even be the default.

**Comment by igitur** [comment]
@Pankraty Your opinion on what the default value of `IXLCell.ToString()` should be?

**Comment by igitur** [comment]
My proposal:

```c#
public override string ToString()
{
    return ToString("A");
}

public string ToString(string format)
{
    switch (format.ToUpper())
    {
        case "A":
            return this.Address.ToString();
        case "C":
        case "F":
            return HasFormula ? this.FormulaA1 : string.Empty;
        case "NF":
            return Style.NumberFormat.Format;
        case "FC":
            return Style.Font.FontColor.ToString();
        case "BC":
            return Style.Font.FontColor.ToString();
        case "V":
            return GetFormattedString();
        default:
            throw new FormatException($"Format {format} was not recognised.");
    }
}
```

**Comment by Pankraty** [comment]
Sorry for the late response. For me, it seems more logical to expose a `Value` in the `.ToString()` by default, by analogy to copying cells to a clipboard in Excel. Besides, I'd rather have an enum defining a format - this way the user doesn't have to go to the documentation in order to recall the proper format.

**Comment by igitur** [comment]
> Sorry for the late response. For me, it seems more logical to expose a `Value` in the `.ToString()` by default, by analogy to copying cells to a clipboard in Excel. Besides, I'd rather have an enum defining a format - this way the user doesn't have to go to the documentation in order to recall the proper format.

What I like about the short strings instead of an enum is that I can easily use the short format strings in my IDE's Watch window. In fact, the currently useless `ToString()` implementation in the Watch window is what prompted me to create the PR. An enum just feels too verbose. I don't really expect users to use this new `ToString(format)` overload too much in practice.

**Comment by Pankraty** [comment]
I guess we also have to add a format for RC-style address. 

Also, it may be convenient to use standard .net formats (e.g. F2, N, G, etc.) and extend them with ClosedXML-specific formats based on different letters. It will, however, require more effort.
