### ISSUE TITLE
change sheet name, data range of chart will missing

### ISSUE THREAD

**Issue by hankhsutc** [ClosedXML/ClosedXML#981]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.93.1 

**What is the current behavior?**
template excel contains a chart. 
After changing the name of sheet,
the data range setting of the chart will missing.

**What is the expected behavior or new feature?**
the chart should be unchanged.

**Did this work in previous versions of our tool?  Which versions?**
not sure

## Reproducibility
the code is simple ,just set the name of a worksheet

**Code to reproduce problem:**
```c#

worksheet.Name = "new name";

[sample.xlsx](https://github.com/ClosedXML/ClosedXML/files/2334600/sample.xlsx)

```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Charts are currently not supported in ClosedXML.
