### ISSUE TITLE
InsertRowAbove/Below corrupts file

### ISSUE THREAD

**Issue by kevinkouketsu** [ClosedXML/ClosedXML#983]
[20160311.xlsx](https://github.com/ClosedXML/ClosedXML/files/2341205/20160311.xlsx)
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

last version

**What is the current behavior?**

When I save edited file with C# I get Corrupted File.

**What is the expected behavior or new feature?**

Normal save 

**Did this work in previous versions of our tool?  Which versions?**

My first use 

## Reproducibility
**Code to reproduce problem:**
```c#
                        using (var workbook = new XLWorkbook("D:\\SGR+ECAD\\dist006.xlsx"))
                        {
                            var worksheet = workbook.Worksheet("Plan1");

                            // Color the entire spreadsheet using rows
                            worksheet.Rows().Style.Fill.BackgroundColor = XLColor.LightCyan;

                                worksheet.Row(10).InsertRowsBelow(1);

                                worksheet.Row(10).Style.Font.FontSize = 11;
                                worksheet.Row(10).Style.Font.FontName = "Calibri";
                                worksheet.Row(10).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                                worksheet.Cell(10, 1).Value = String.Format("{0:dd/MM/yyyy}", date);
                                worksheet.Cell(10, 2).Value = String.Format("{0:HH:mm:ss}", reg.Hour);
                                worksheet.Cell(10, 3).Value = String.Format("{0}", reg.Music);
                                worksheet.Cell(10, 4).Value = String.Format("{0}", reg.Author);
                                worksheet.Cell(10, 5).Value = String.Format("{0}", reg.Interpreter);
                                worksheet.Cell(10, 6).Value = String.Format("{0}", reg.Record);
                                worksheet.Cell(10, 8).Value = "x";

                            workbook.SaveAs("D:\\SGR+ECAD\\dist007.xlsx");
                        }
```

It is just an example. 
Without the line InsertRowAbove or InsertRowBelow has no error but overwrite my template. When my program runs, I don't know how much lines I will add

- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Try with the latest version, please.

**Comment by kevinkouketsu** [comment]
Sorry, i'm using the lastest version, like u can see:
![image](https://user-images.githubusercontent.com/8815791/44946693-6d696e00-add7-11e8-9bbe-525608a2cf94.png)

[dist7.xlsx](https://github.com/ClosedXML/ClosedXML/files/2342417/dist7.xlsx)

**Comment by igitur** [comment]
Attach your unmodified `dist006.xlsx` file. Read all other instructions in the issue template to ensure that you haven't missed any MORE required info.

**Comment by igitur** [comment]
And trim down your code sample to the minimum that reproduces the error.

**Comment by kevinkouketsu** [comment]
This is my `dist006.xlsx ` 
[dist006.xlsx](https://github.com/ClosedXML/ClosedXML/files/2346363/dist006.xlsx)

The code is like I show before but you can complete with only text:
```using (var workbook = new XLWorkbook("D:\\SGR+ECAD\\dist006.xlsx"))
                        {
                            var worksheet = workbook.Worksheet("Plan1");

                                worksheet.Row(10).InsertRowsBelow(1);

                                worksheet.Cell(10, 1).Value = "Teste";
                                worksheet.Cell(10, 9).Value = "x";

                            workbook.SaveAs("D:\\SGR+ECAD\\dist007.xlsx");
                        }

```

Like I said, sometimes the code runs well and sometimes gets the corrupted file.

**Comment by kevinkouketsu** [comment]
I don't know why but apparently works fine right know ???.
I just copied and pasted my code above and voila, works.

Sorry for your time. If anything else happen, i'll be in touch.

Now I have a problem with accentuation (charset, I think). I need to create another issue post?
See:
![image](https://user-images.githubusercontent.com/8815791/45033652-866a5d00-b02b-11e8-8d40-e7dbbe3437c0.png)

**Comment by igitur** [comment]
Yes, create a new issue. Fill in the template completelyl.
