### ISSUE TITLE
XLConditionalFormat formats independent columns as one range for ColorScale

### ISSUE THREAD

**Issue by chaporovag** [ClosedXML/ClosedXML#989]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.94

**What is the current behavior?**

When trying to format several independent columns using ColorScale, all of them are formating in one range.

**What is the expected behavior or new feature?**

Each column is formatting separately.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
    using (var output = new MemoryStream())
            {
                using (var wb = new XLWorkbook())
                {
                    var sheet = wb.Worksheets.Add("test");
                    sheet.Column(1).AddConditionalFormat().ColorScale()
                    .LowestValue(XLColor.FromHtml("#f56a6d"))
                    .Midpoint(XLCFContentType.Percent, 50, XLColor.FromHtml("#fdec84"))
                    .HighestValue(XLColor.FromHtml("#63be7b"));

                    sheet.Column(2).AddConditionalFormat().ColorScale()
                    .LowestValue(XLColor.FromHtml("#f56a6d"))
                    .Midpoint(XLCFContentType.Percent, 50, XLColor.FromHtml("#fdec84"))
                    .HighestValue(XLColor.FromHtml("#63be7b"));

                    wb.SaveAs(output);
                }
            }
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

Current result:
![default](https://user-images.githubusercontent.com/6030730/45210600-b5d1d180-b298-11e8-8bd5-0495b1edfc53.JPG)

Expected result:
![1](https://user-images.githubusercontent.com/6030730/45210608-bbc7b280-b298-11e8-84fa-974d2c43232e.JPG)

**Comment by igitur** [comment]
Thanks. Did you test this with the latest development version? If so, I merged a PR this morning that might affect this behaviour.

**Comment by chaporovag** [comment]
@igitur Yes, I've been tested with the lastest development version, because previous version had issue that you get a null reference exception on save function when trying to create ColorScale for two or more independent columns.
