### ISSUE TITLE
When opening a workbook there is a crash into the method LoadAutoFilterColumns

### ISSUE THREAD

**Issue by Tarboeuf** [ClosedXML/ClosedXML#990]
- [x] Bug

**Version of ClosedXML**

e.g. 0.93.1

**What is the current behavior?**
When loading an excel file in french culture, il there is some autofilter filtering on this value "1 000", ClosedXml crash with the message

>  Input string was not in a correct format

**Did this work in previous versions of our tool?  Which versions?**

No

**Code to reproduce problem:**
```c#
public void Main()
{
    var wb = new XLWorkbook(@"D:\issue.xlsx");
}
```
- [x] [issue.xlsx](https://github.com/ClosedXML/ClosedXML/files/2361716/issue.xlsx)

**Comment by Tarboeuf** [comment]
Look at the code you can correct this issue using this code 
`if (!Double.TryParse(val, NumberStyles.Float | NumberStyles.AllowThousands, CultureInfo.InvariantCulture, out Double dTest))`
for the both calls to TryParse

**Comment by igitur** [comment]
@Pankraty Note that this is dependent on the culture. If I change my PC's regional settings to en-US settings, then open the file in Excel and then choose Data | Reapply, then the filter changes the displayed rows... and in fact no rows are shown.

**Comment by Pankraty** [comment]
I guess I'll have to dig deeper.

**Comment by igitur** [comment]
@Tarboeuf What are your regional settings? specifically your decimal symbol and digit grouping symbol?

**Comment by Tarboeuf** [comment]
@igitur That's French Decimal symbol is ',' and grouping symbol is ' '

**Comment by igitur** [comment]
@Tarboeuf Would you mind posting a screenshot of your Numbers regional settings screen:

Like this is mine:
![image](https://user-images.githubusercontent.com/145854/47081052-e434bc00-d209-11e8-8c55-e11172dc8bfe.png)

**Comment by igitur** [comment]
Interesting. I don't quite know why the autofilter is set to `10 000.00` is recognised as a valid number in Excel. If it were `10 000,00` I would understand. Just to confirm, do numbers like in Excel show with a decimal comma or period?

**Comment by igitur** [comment]
@Tarboeuf Do numbers in Excel show with a decimal comma or period?

**Comment by Tarboeuf** [comment]
They are displayed with decimal comma

**Comment by Tarboeuf** [comment]
I have done some tests and if I change the used Culture of Excel like that : 
![image](https://user-images.githubusercontent.com/5155564/47203368-5e874c80-d380-11e8-875b-f51ce8c3b806.png) 
the filter does not remain selected : 
![image](https://user-images.githubusercontent.com/5155564/47203456-b625b800-d380-11e8-9f2f-d2191b647feb.png)
And if I check back "use system separators", the filter selection is back :
![image](https://user-images.githubusercontent.com/5155564/47203651-567bdc80-d381-11e8-9f83-64db62867caf.png)

Hope that can help you

**Comment by igitur** [comment]
@Tarboeuf I'm confused. Is this issue about 
- an Excel-generated file that fails to load in ClosedXML or
- a ClosedXML-generated file that displays the wrong autofilter results in Excel?

**Comment by Tarboeuf** [comment]
It's about _an Excel-generated file that fails to load in ClosedXML_

My last posts are to give you some clues.

**Comment by Tarboeuf** [comment]
Thant you it works !
