### ISSUE TITLE
Cannot continues process when i try a excel file with large capacity ( size file = 10067KB)

### ISSUE THREAD

**Issue by HuanVo** [ClosedXML/ClosedXML#991]
public static void ExportDataExcel(string filePath)
        {
            string folderPath = "C:\\Excel\\";
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }
            if (File.Exists(filePath))
            {
                XLWorkbook wb = new XLWorkbook(filePath);
                IXLWorksheet workSheet = wb.Worksheet(1);
                wb.SaveAs(folderPath + "Hello.xlsx");
                wb.Dispose();
                Console.WriteLine("Done");
            }
        }

**Comment by Pankraty** [comment]
Fill the whole template, attach the file on which the issue can be reproduced.

**Comment by HuanVo** [comment]
[https://drive.google.com/file/d/1MJuIeTy1wAryjm-NxS4-2zlFNRCqsHwR/view?usp=sharing] link source code, please help me.

**Comment by igitur** [comment]
![image](https://user-images.githubusercontent.com/145854/45290158-2a05b280-b4ef-11e8-82ce-47d87dc8bcfe.png)

**Comment by HuanVo** [comment]
@igitur  it's safe, I assure you

**Comment by igitur** [comment]
We will help you, but you must follow the prescribed steps to report the issue. Fill out the original [issue template](https://github.com/ClosedXML/ClosedXML/blob/develop/.github/ISSUE_TEMPLATE.md). Paste your code sample to reproduce the issue in the template. We don't accept attachments via Google Drive.

Look at how other issues were reported if you are unsure.

**Comment by HuanVo** [comment]
@igitur ,   i'm sorry all, i will follow the prescribed steps to report the issue with a new issue.
