### ISSUE TITLE
Saving a file having thousands of conditional formats takes too long

### ISSUE THREAD

**Issue by HuanVo** [ClosedXML/ClosedXML#993]
**Version of ClosedXML**

0.93.1.0

**What is the current behavior?**
i cannot save as a new file from file available with XLWorkbook.SaveAs("newFilePath").
my file have size = 10076kb.
i was verified with file has small size (100kb) and good performance result.
 this is my code:
```
 using ClosedXML.Excel;
using System;
using System.IO;


namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            string filePath = @"[thm-viewer] Export_Data_Format_rev01";

            ExportDataExcel(filePath);

            Console.ReadLine();
        }
        public static void ExportDataExcel(string filePath)
        {
            if (File.Exists(filePath))
            {
                using (XLWorkbook wb = new XLWorkbook(filePath))
                {
                    wb.SaveAs("copyfile.xlsx");
                    Console.WriteLine("Done");
                }
            }
        }
    }
}
```

**What is the expected behavior or new feature?**
How do I copy large files with the XLWorkbook .SaveAs("copyfile.xlsx"); method?

**Did this work in previous versions of our tool? Which versions?**
No

**Comment by HuanVo** [comment]
@igitur  can you help me?

**Comment by igitur** [comment]
You didn't complete the full issue template!

**Comment by igitur** [comment]
Why did you just delete sections of the template?

**Comment by HuanVo** [comment]
I sorry, how do i can my mistake?

**Comment by HuanVo** [comment]
@igitur, my issue is very important, i can delay my project if my problem is not resolved. thank you!

**Comment by HuanVo** [comment]
@igitur , i updated issue, can you help me?

**Comment by igitur** [comment]
Attach your input file.

**Comment by igitur** [comment]
Why don't you just copy the file with `System.IO.File.Copy()` ?

**Comment by HuanVo** [comment]
I'm trying to open a relatively large file to fix the contents and save a new file. because want to use XLWorkbook .SaveAs("copyfile.xlsx")

**Comment by HuanVo** [comment]
this is my project

**Comment by igitur** [comment]
# Attach your input file.

I'm not asking again.

**Comment by HuanVo** [comment]
i cannot attach full project, because it's big. 
this is my file demo
[[thm-viewer] Export_Data_Format_rev01.zip](https://github.com/ClosedXML/ClosedXML/files/2366265/thm-viewer.Export_Data_Format_rev01.zip)

**Comment by vbjay** [comment]
All he wants is the Excel file.

**Comment by igitur** [comment]
> \>ClosedXML_Sandbox.exe
> Running OpenTestFile
> TypeID
> Action done in 00:54:45.1365039
> 
> Press any key to continue
> 

I can open and save the file, but it takes almost an hour. The most of the time is spent in consolidating the conditional formats. @Pankraty Maybe the CF consolidation should be an optional parameter when saving the file?

@HuanVo There's not much I can do to help you right now. I suggest you try to trim down your workbook and reduce the number of conditional formatting rules. For instance, worksheet `1510` has way too many conditional format rules. I'm sure you'd be able to simplify them into only a few rules.

**Comment by HuanVo** [comment]
thanks @igitur , thanks @Pankraty . I think, I will convert the excel file to array byte to execute, do you have documentation for this direction? Can you give me a reference?

**Comment by vbjay** [comment]
A byte array won't help.

**Comment by HuanVo** [comment]
I will convert from array byte to object and molding type to workbook. i hope it's true.

**Comment by vbjay** [comment]
You don't get it. It is not a byte array to begin with. Yes all files are
binary in a sense. No. You can't read the bytes of the Excel file and get a
workbook.

**Comment by HuanVo** [comment]
Thanks you @vbjay , I found a solution to my problem. I used the OpenXML library to work with large excel files.

**Comment by Pankraty** [comment]
I confirm, there are insanely many conditional format rules. But to my surprise, the consolidation itself works very fast: for example, having 10865 ranges it took only 140 ms to consolidate them into one. However, the code determining which ranges may be consolidated without breaking the priorities is much less efficient. It works fine for hundreds of ranges, but tens of thousand bring it to its knees.

Have to think about how to speed it up.

**Comment by Pankraty** [comment]
The issue will close automatically when the linked PR is closed.
