### ISSUE TITLE
Cannot open a file that contains a Table with empty header. Crash with message "The header row doesn't contain field name"

### ISSUE THREAD

**Issue by Tarboeuf** [ClosedXML/ClosedXML#995]
- [x] Bug

**Version of ClosedXML**

0.93.1
0.93.0
master
develop
I don't test it before

**What is the current behavior?**
When opening the given file, closed Xml crashes.

**Did this work in previous versions of our tool?  Which versions?**

I don't think so.

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
            var wb = new XLWorkbook(@"D:\issue_table_header.xlsx");
}
```
- [x] I attached a sample spreadsheet. 
[issue_table_header.xlsx](https://github.com/ClosedXML/ClosedXML/files/2375209/issue_table_header.xlsx)

**Comment by igitur** [comment]
The blank column headers are causing a problem. I'll look at a fix, but I generally advise against leaving table column headers empty.
